patternfly/patternfly-react

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

Adds code contribution and contribution process guidelines for the Patternfly React project.
issue: #4 
cc: @jgiardino @maryclarke @LHinson @bleathem

documentation: adds contributing.md

---

README.md

**What**:
Updates Community Meeting link to target pf.org page.
cc: @LHinson @jgiardino

docs(readme): update community meeting link

---

.gitignore
.npmignore
.prettierignore
.vscode/settings.json
less/patternfly-react.less
package-lock.json
package.json
storybook/config.js
storybook/less/base.less
storybook/less/patternfly.less
storybook/preview-head.html
storybook/webpack.config.js

**What**:
Changes PF-R Storybook to consume PatternFly LESS
**Why**:
This will enable other LESS in PF React project and allow us to further customize PatternFly LESS.
Deployed Storybook (PF LESS compiled with Webpack instead included in `preview-head.html`): https://rawgit.com/priley86/patternfly-react/patternfly-less-build/index.html

build(less): consume patternfly less within Storybook webpack config

---

src/components/Button/Button.stories.js
src/components/Button/ButtonGroup.js
src/components/Button/index.js

**What**:
This PR adds the PatternFly buttongroup patterns. To be used to close #12 (ButtonGroup) once done.
Storybook: https://rawgit.com/dabeng/patternfly-react/btn-group-storybook/.out/index.html?knob-Label=Danger%20Will%20Robinson%21&selectedKind=Button&selectedStory=ButtonGroup&full=0&down=1&left=1&panelRight=0&downPanel=storybooks%2Fstorybook-addon-knobs
**How**:
Encapsulating react-bootstrap buttongroup as a story of patternfly-react storybook.
@priley86 , please review.

feat(buttongroup): add the pf buttongroup

---

src/components/Spinner/Spinner.js
src/components/Spinner/Spinner.test.js
src/components/Spinner/index.js
src/index.js

**What**: Adding export for spinner component - sorry I missed this!
**Link to Storybook**: [storybook](https://rawgit.com/danseethaler/patternfly-react/spinner-component-stories/index.html?knob-Label=Danger%20Will%20Robinson%21&knob-Loading=true&knob-Inline=false&knob-Size=md&knob-Inverse=false&selectedKind=Widgets&selectedStory=Spinner&full=0&down=1&left=1&panelRight=0&downPanel=storybooks%2Fstorybook-addon-knobs)

fix(Spinner component): Adding the Spinner component export

---

src/components/Spinner/Spinner.stories.js

Sometimes you need to just squash a few PRs together :)
I think this is it @priley86

fix(Spinner): Update storybook import

---

package-lock.json
src/components/Alert/Alert.js
src/components/Alert/__snapshots__/Alert.test.js.snap
src/components/Alert/constants.js
src/components/Alert/helpers.js

**What**:
Small refactor to use Icon component inside Alert
[**Link to Storybook**](http://rawgit.com/sharvit/patternfly-react/storybook/alert-icon/index.html?knob-Label=Danger%20Will%20Robinson%21&selectedKind=Alert&selectedStory=with%20danger&full=0&down=1&left=1&panelRight=0&downPanel=storybooks%2Fstorybook-addon-knobs)

refactor(Alert): Migrate Alert icons to Icon component

---

.npmignore

Minor ignore tweak, related to distribution.
**What**:

fix(dist): Update for distributing less sass

---

package.json

**What**:
This fixes semantic-release npm script semantics. Apparently this changed recently ;0
https://github.com/semantic-release/semantic-release/issues/411#issuecomment-353233730
uugh......
nope
none

fix(semantic-release): fix semantic-release script for latest version

---

.travis.yml
package-lock.json
package.json

**What**:
Update semantic-release once more, as they also just recently added travis-deploy-once in the 12.0.0 release. (see breaking changes)
https://github.com/semantic-release/semantic-release/releases
nope
nope

fix(semantic-release): add travis-deploy-once and update once again

---

src/components/Grid/Grid.stories.js
src/components/Grid/index.js
src/components/Toolbar/Toolbar.js

**What**: 
Add Row, Col, and Clearfix as children of Grid. Now one just needs to import Grid and use Grid.Row, Grid.Col, and/or Grid.Clearfix
No visual or functional changes here.

fix(Grid): Provide Row, Col, Clearfix as children of Grid

---

src/components/ToastNotification/ToastNotificationList.js

fix(ToastNotificationList): do not override class toast-notifications-list-pf

---

package-lock.json
package.json
src/components/Switch/Switch.js
src/components/Switch/Switch.stories.js
src/components/Switch/SwitchConstants.js
src/components/Switch/index.js
src/index.js

**What**:
Adds Switch component based on [react-bootstrap-switch ](https://www.npmjs.com/package/react-bootstrap-switch)
Storybook: https://rawgit.com/jeff-phillips-18/patternfly-react/switch-storybook/index.html
Fixes #121

feat(Switch): add Switch component

---

CONTRIBUTING.md

**What**:  Fixes URL for patternfly-react repo in contributing md file
**Link to Storybook**: N/A
**Additional issues**: Closes #176

Fix the url for patternfly-react repo in the md file

---

package-lock.json
package.json
src/components/ListView/ListView.stories.js
src/components/ListView/ListViewItem.js
src/components/ListView/__mocks__/mockCompoundExpansionExample.js
src/components/ListView/__mocks__/mockListItems.js
src/components/ListView/__snapshots__/ListView.test.js.snap

**What**:
Adding compound expansion support to ListView
[Storybook Link](https://jeff-phillips-18.github.io/patternfly-react/?knob-Stacked=false&selectedKind=ListView&selectedStory=List%20with%20Compound%20Expansion&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)
**Patternfly Design**
http://www.patternfly.org/pattern-library/content-views/list-view/#compound-expansion
Fixes #174

feat(ListView): Add compound expansion support

---

src/components/ProgressBar/ProgressBar.js
src/components/ProgressBar/ProgressBar.stories.js
src/components/ProgressBar/ProgressBar.test.js
src/components/ProgressBar/__snapshots__/ProgressBar.test.js.snap
src/components/ProgressBar/index.js

**What**:
https://github.com/patternfly/patternfly-react/issues/182
https://rawgit.com/ZitaNemeckova/patternfly-react/ProgressBar/index.html

feat: Progress bar

---

src/index.js

**What**:
Add `ProgressBar` component to `src/index.js`. Forgotten in https://github.com/patternfly/patternfly-react/pull/188
@priley86 please, have a look. Thanks :)

Add ProgressBar to src/index.js

---

README.md

**What**:
It looks like the Storybook domain has changed... and then well this project's Prettier settings can explain the rest 😉

docs(readme): update storybook link

---

package-lock.json
package.json

**What**: The title in the Vertical Navigation examples is misaligned. A CSS fix has been merged in pf core, so we need to update core.
**Link to Storybook**: http://rawgit.com/mturley/patternfly-react/pf338storybook/index.html

build(package.json): Bump patternfly version to get CSS fixes

---

.gitignore
.travis.yml
README.md
package-lock.json
package.json

**What**:
* Configure jest to generate code-coverage
* Configure Travis to publish code-coverage to coveralls.io

test(code-coverage): Add code-coverage reports

---

CONTRIBUTING.md

Clarify contribution process related to using the project board, labels, creating issues, and adding
less/sass files.
**What**: Updates CONTRIBUTING.md
**Link**: [https://github.com/jgiardino/patternfly-react/blob/contributing/CONTRIBUTING.md](https://github.com/jgiardino/patternfly-react/blob/contributing/CONTRIBUTING.md)

docs(CONTRIBUTING.md): Clarify contribution process

---

src/common/helpers.js
src/components/InfoTip/InfoTip.js
src/components/InfoTip/InfoTip.stories.js
src/components/InfoTip/InfoTip.test.js
src/components/InfoTip/InfoTipMenu.js
src/components/InfoTip/InfoTipMenuFooter.js
src/components/InfoTip/InfoTipMenuItemIcon.js
src/components/InfoTip/InfoTipToggle.js
src/components/InfoTip/__snapshots__/InfoTip.test.js.snap
src/components/InfoTip/index.js

This is for Infotip component http://www.patternfly.org/pattern-library/widgets/#info-tip
Issue #170
Storybook : [Link](https://aljesusg.github.io/patternfly-react/)
Thanks  @sharvit for help

feat(infoTip): Add Infotip component

---

src/components/Button/Button.js
src/components/Button/Button.stories.js
src/components/Button/ButtonConstants.js
src/components/Button/__snapshots__/DropdownButton.test.js.snap
src/components/Button/__snapshots__/SplitButton.test.js.snap

**What**:
Allow `'success'` as a choice for `bsStyle` to use bootstrap's success button.
https://jeff-phillips-18.github.io/patternfly-react/?selectedKind=Button&selectedStory=Button

fix(Button): Allow bsStyle success

---

src/components/VerticalNav/VerticalNav.test.js
src/components/VerticalNav/VerticalNavConstants.js
src/components/VerticalNav/VerticalNavItemHelper.js
src/components/VerticalNav/__mocks__/basicExample.js
src/components/VerticalNav/__snapshots__/VerticalNav.test.js.snap

**What**:
Title says it all. Requested by @jeff-phillips-18 
https://rawgit.com/mturley/patternfly-react/VerticalNavItem-className-sb/index.html

feat(VerticalNavItem): Add support for custom className on a nav item

---

src/index.js

**What**:
Add InfoTip to exports

fix(InfoTip): Add InfoTip to Exports.

---

less/utilization-bar.less

**What**: SASS syntax used in LESS file to reference variable

fix(UtilizationBar): Syntax of LESS fixed

---

src/components/Pagination/PaginationRowBack.js
src/components/Pagination/PaginationRowForward.js

https://AllenBW.github.io/patternfly-react/
fixes #253 
when pagination row has disabled buttons, no actions should fire *NONE* 😋 🤣

fix(PaginationRow): disabled buttons don't fire actions

---

less/label-remove.less
less/patternfly-react.less
sass/patternfly-react/_label-remove.scss
sass/patternfly-react/_patternfly-react.scss
src/components/Filter/FilterItem.js
src/components/Filter/__snapshots__/Filter.test.js.snap
src/components/Label/DisposableLabel.js
src/components/Label/DisposableLabel.test.js
src/components/Label/Label.js
src/components/Label/Label.stories.js
src/components/Label/RemoveButton.js
src/components/Label/__mocks__/mockLabelExamples.js
src/components/Label/__snapshots__/DisposableLabel.test.js.snap
src/components/Label/index.js
src/components/Toolbar/__snapshots__/Toolbar.test.js.snap

**What**:
Fixes https://github.com/patternfly/patternfly-react/issues/222
https://karelhala.github.io/patternfly-react/?selectedKind=Label&selectedStory=Label%20with%20remove&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs
**Additional info**
This PR creates two new components, which can later be used as standalone components for labels.

feat(RemovableLabel): create RemovableLabel and LabelRemove

---

src/components/Pagination/Pager.js
src/components/Pagination/Pager.test.js
src/components/Pagination/Pagination.stories.js
src/components/Pagination/__snapshots__/Pager.test.js.snap
src/components/Pagination/index.js

closes #217 
Given discussion in #217, gonna rescope this to just be the pager component, the rest isn't desired for implementation
https://AllenBW.github.io/patternfly-react/
☝️ 📚

feat(Pagination): adds pager 

---

src/index.js

**What**:
Add Cards to exports

fix(Cards): Add Cards to exports

---

src/components/Cards/index.js

**What**: Export aggregate card components

fix(Cards): Export aggregate card components

---

storybook/config.js

- fix `stories.js` regexp
- simplify `forEach` in `loadStories()`

Small Storybook config fixes

---

src/components/ListView/ListView.stories.js
src/components/ListView/ListViewGroupItemContainer.js
src/components/ListView/ListViewItem.js

Fix for issue https://github.com/patternfly/patternfly-react/issues/277 where the hideCloseIcon property did not have an effect on expanded content.

fix(ListView): Fixed issue with hideCloseIcon not being respected

---

CONTRIBUTING.md

I have updated the contributing.md to include information about how to become a maintainer.

Updating the contributing.md 

---

CONTRIBUTING.md
src/common/controlled.js
src/common/helpers.js
src/components/Filter/__mocks__/mockFilterExample.js
src/components/InfoTip/InfoTip.js
src/components/ListView/ListViewItem.js
src/components/ListView/__mocks__/mockCompoundExpansionExample.js
src/components/Pagination/Paginator.js
src/components/Pagination/__mocks__/mockPaginationRow.js
src/components/Sort/__mocks__/mockSortExample.js
src/components/Table/TableConfirmButtonsRow.js
src/components/Table/__mocks__/mockClientPaginationTable.js
src/components/Table/__mocks__/mockClientSortableTable.js
src/components/Table/__mocks__/mockInlineEditCellTable.js
src/components/Table/__mocks__/mockInlineEditColumnTable.js
src/components/Table/__mocks__/mockInlineEditRowTable.js
src/components/Table/__mocks__/mockServerPaginationTable.js
src/components/ToastNotification/TimedToastNotification.js
src/components/ToastNotification/ToastNotificationList.js
src/components/Toolbar/ToolbarFind.js
src/components/Toolbar/__mocks__/mockToolbarExample.js
src/components/TreeView/__mocks__/MockTreeView.js
src/components/VerticalNav/VerticalNav.js
src/components/VerticalNav/VerticalNavItemHelper.js
src/components/Wizard/Stories/WizardExample.js
src/components/Wizard/Stories/WizardPatternExample.js
src/components/Wizard/Stories/mockWizardBase.js
src/components/Wizard/Stories/mockWizardReviewStepsManager.js

chore(all): Remove bindMethods in favor of Class properties

---

packages/console/package.json

**What**:
Update the package name for the console package to be in the @patternfly org.

chore(console): Update console package name

---

src/components/ToastNotification/ToastNotification.stories.js

Improves notification list example 
[here's the storybook of fun!](https://allenbw.github.io/patternfly-react/?selectedKind=ToastNotification&selectedStory=Toast%20Notification%20List&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)

feat(NotificationList) -Automates notification creation for list example

---

packages/core/src/components/Cards/Card.js

affects: `patternfly-react`
**What**:
testing one more publish...

fix(test): testing the lerna release on patternfly-react

---

storybook/webpack.config.js

docs(storybook): include styles from dependencies from all packages

---

packages/console/CREDITS.md
packages/console/src/SerialConsole/SerialConsole.test.js
packages/console/src/SerialConsole/SerialConsoleActions.test.js
packages/console/src/SerialConsole/XTerm.js
packages/console/src/SerialConsole/XTerm.test.js
packages/console/src/SerialConsole/__snapshots__/SerialConsole.test.js.snap
packages/console/src/SerialConsole/__snapshots__/SerialConsoleActions.test.js.snap
packages/console/src/SerialConsole/__snapshots__/XTerm.test.js.snap

More unit tests added plus the the CREDITS.md file.

test(SerialConsole): add more unit tests for the SerialConsole

---

packages/core/package.json
packages/core/src/components/Chart/BulletChart/BulletChart.js
packages/core/src/components/Chart/BulletChart/BulletChart.test.js
packages/core/src/components/Chart/BulletChart/BulletChartAxis.js
packages/core/src/components/Chart/BulletChart/BulletChartAxisTic.js
packages/core/src/components/Chart/BulletChart/BulletChartLegend.js
packages/core/src/components/Chart/BulletChart/BulletChartLegendItem.js
packages/core/src/components/Chart/BulletChart/BulletChartRange.js
packages/core/src/components/Chart/BulletChart/BulletChartThreshold.js
packages/core/src/components/Chart/BulletChart/BulletChartTitle.js
packages/core/src/components/Chart/BulletChart/BulletChartValue.js
packages/core/src/components/Chart/BulletChart/__snapshots__/BulletChart.test.js.snap
packages/core/src/components/Chart/BulletChart/index.js
packages/core/src/components/Chart/Chart.stories.js
packages/core/src/components/Chart/Stories/BulletChartStory.js
packages/core/src/components/Chart/Stories/index.js
packages/core/src/components/Chart/index.js
yarn.lock

ISSUES CLOSED: #347
https://rawgit.com/jeff-phillips-18/patternfly-react/bullet-chart-storybook/index.html?selectedKind=patternfly-react%2FData%20Visualization%2FCharts&selectedStory=Bullet%20Charts
Requires upgrade to patternfly 3.48.0

feat(bullet-chart): add Bullet Chart component

---

packages/core/src/components/Chart/BulletChart/BulletChart.js
packages/core/src/components/Chart/BulletChart/__snapshots__/BulletChart.test.js.snap

also,  pass along custom tooltips to legend items.

fix(bullet-chart): fix to not show ranges not in use

---

packages/eslint-plugin/src/config/recommended.js

affects: eslint-plugin-patternfly-react

feat(eslint react/sort-comp): remove the eslint error for react/sort-comp

---

packages/eslint-plugin/src/config/recommended.js

affects: eslint-plugin-patternfly-react

feat(eslint react/sort-comp): remove the eslint error for react sort-comp

---

packages/patternfly-react/less/patternfly-react.less
packages/patternfly-react/less/verticalnavdivider.less
packages/patternfly-react/sass/patternfly-react/_patternfly-react.scss
packages/patternfly-react/sass/patternfly-react/_verticalnavdivider.scss
packages/patternfly-react/src/components/VerticalNav/VerticalNav.js
packages/patternfly-react/src/components/VerticalNav/VerticalNavDividerItem.js
packages/patternfly-react/src/components/VerticalNav/VerticalNavItemHelper.js
packages/patternfly-react/src/components/VerticalNav/VerticalNavSecondaryItem.js
packages/patternfly-react/src/components/VerticalNav/__mocks__/basicExample.js
packages/patternfly-react/src/components/VerticalNav/__mocks__/mockNavItems.js
packages/patternfly-react/src/components/VerticalNav/index.js

(fix of commit message for work done by @gilad215 to create the patternfly-react release)

feat(add divider to vertical nav): (#330)

---

packages/patternfly-react/src/components/ApplicationLauncher/ApplicationLauncher.test.js
packages/patternfly-react/src/components/ApplicationLauncher/Wrappers/Wrappers.test.js
packages/patternfly-react/src/components/ApplicationLauncher/Wrappers/__snapshots__/Wrappers.test.js.snap
packages/patternfly-react/src/components/ApplicationLauncher/__snapshots__/ApplicationLauncher.test.js.snap

test(ApplicationLauncher): fixes application launcher tests to resolve eslint warnings.

---

packages/patternfly-react/src/components/Wizard/Patterns/StatefulWizardPattern.js
packages/patternfly-react/src/components/Wizard/Wizard.test.js

shouldDisableNextStep props is not working on Wizard component.
This pull request is here to fix the bug.

Fix shouldDisableNextStep in Wizard Statefull component

---

packages/react-core/src/components/Badge/Badge.d.ts
packages/react-core/src/components/Badge/Badge.js
packages/react-core/src/components/Badge/Badge.test.js
packages/react-core/src/components/Badge/__snapshots__/Badge.test.js.snap
packages/react-core/src/components/Badge/index.d.ts
packages/react-core/src/components/Badge/index.js
packages/react-core/src/components/index.d.ts
packages/react-core/src/components/index.js
packages/react-docs/src/components/example/example.js
packages/react-docs/src/pages/components/badge.js

Added Badge component
ISSUES CLOSED: #384 
Docs page: https://5b3b6092fdd72a4a235d4f0f--zen-swanson-2d3350.netlify.com/components/Badge

feat(react-core/Badge): introduce patternfly 4 badge component

---

packages/patternfly-react/src/components/Chart/Stories/AreaChartStory.js
packages/patternfly-react/src/components/Chart/Stories/BarChartStory.js
packages/patternfly-react/src/components/Chart/Stories/DonutChartStory.js
packages/patternfly-react/src/components/Chart/Stories/LineChartStory.js
packages/patternfly-react/src/components/Chart/Stories/PieChartStory.js

**What**: add link to c3 documentation
**Link to Storybook**:  [storybook](https://lizagilman.github.io/patternfly-react/?knob-Use%20Colors=Primary&knob-Warning%20threshold%20value=40&knob-Show%20Range%201=true&knob-Show%20Range%202=true&knob-Value%202%20Title=Data2&knob-Show%20Range%203=true&knob-Value%203%20Title=Data3&knob-Description=Description&knob-Value%204%20Title=Data4&knob-Show%20Error%20Threshold=true&knob-Value%205%20Title=Data5&knob-Show%20Axis=true&knob-Error%20threshold%20value=80&knob-Maximal%20value=100&knob-Range%201%20Title=Range%201&knob-Value%20Color%202=%233f9c35&knob-Warning%20Threshold=70&knob-Range%202%20Title=Range%202&knob-Value%20Color%203=%23f0ab00&knob-Range%203%20Title=Range%203&knob-Value%20Color%204=%23cc0000&knob-Value%20Title=Data1&knob-Value%20Color%205= …

docs(Charts): add link to c3 documentation

---

.babelrc.js
package.json
packages/react-core/package.json
packages/react-core/src/components/Alert/Alert.d.ts
packages/react-core/src/components/Alert/Alert.js
packages/react-core/src/components/Alert/Alert.test.js
packages/react-core/src/components/Alert/AlertAction.js
packages/react-core/src/components/Alert/AlertBody.js
packages/react-core/src/components/Alert/AlertIcon.js
packages/react-core/src/components/Alert/__snapshots__/Alert.test.js.snap
packages/react-core/src/components/Alert/index.d.ts
packages/react-core/src/components/Alert/index.js
packages/react-core/src/components/index.d.ts
packages/react-core/src/components/index.js
packages/react-core/src/internal/util.js
packages/react-docs/gatsby-node.js
packages/react-docs/src/pages/components/alert.js
packages/react-docs/src/pages/styles/icons.js
yarn.lock

ISSUES CLOSED: #391 
Added alert component
This is no HOLD because of missing icons.
React docs netlify - https://5b470993c6aed66e9b4a5803--zen-swanson-2d3350.netlify.com/components/alert/

feat(react-core/Alert): introduce Alert component from patternfly 4

---

packages/react-core/src/layouts/Level/Level.d.ts
packages/react-core/src/layouts/Level/Level.js
packages/react-core/src/layouts/Level/Level.test.js
packages/react-core/src/layouts/Level/LevelItem.d.ts
packages/react-core/src/layouts/Level/LevelItem.js
packages/react-core/src/layouts/Level/__snapshots__/Level.test.js.snap
packages/react-core/src/layouts/Level/index.d.ts
packages/react-core/src/layouts/Level/index.js
packages/react-core/src/layouts/index.d.ts
packages/react-core/src/layouts/index.js
packages/react-docs/src/pages/layouts/level.js

**Add Level layout**
Based on the design from patternfly team create react component coresponding to level layout 
https://5b4775fae39e7c44712d46c5--zen-swanson-2d3350.netlify.com/

feat(react-core/Level): introduce Level layout from pf4 specs

---

packages/react-core/src/layouts/Stack/Stack.d.ts
packages/react-core/src/layouts/Stack/Stack.js
packages/react-core/src/layouts/Stack/Stack.test.js
packages/react-core/src/layouts/Stack/StackItem.d.ts
packages/react-core/src/layouts/Stack/StackItem.js
packages/react-core/src/layouts/Stack/__snapshots__/Stack.test.js.snap
packages/react-core/src/layouts/Stack/index.d.ts
packages/react-core/src/layouts/Stack/index.js
packages/react-core/src/layouts/index.d.ts
packages/react-core/src/layouts/index.js
packages/react-docs/src/pages/layouts/stack.js

**What**:
Create new layout Stack which allows vertical alignment of items.
https://5b4f4dd4fdd72a01b2df0c1a--zen-swanson-2d3350.netlify.com/layouts/split/
ISSUES CLOSED: #477

feat(pf4-stack): introduce new Stack layout for PF4

---

packages/react-core/src/components/Checkbox/Checkbox.js
packages/react-core/src/components/Checkbox/Checkbox.test.js
packages/react-core/src/components/Checkbox/__snapshots__/Checkbox.test.js.snap
packages/react-core/src/components/Checkbox/index.js
packages/react-core/src/components/index.js
packages/react-docs/src/pages/components/checkbox.js

**Affects**: @patternfly/react-core, @patternfly/react-docs
**What**: Introducing the PF4 Check Component
ISSUES CLOSED:  https://github.com/patternfly/patternfly-react/issues/485

feat(react-core[Checkbox]): add pf4 checkbox component

---

packages/react-core/src/components/Radio/Radio.js
packages/react-core/src/components/Radio/Radio.test.js
packages/react-core/src/components/Radio/__snapshots__/Radio.test.js.snap
packages/react-core/src/components/Radio/index.js
packages/react-core/src/components/index.js
packages/react-docs/src/pages/components/radio.js

**Affects**: @patternfly/react-core, @patternfly/react-docs
**What**: Introducing the PF4 Radio Component
ISSUES CLOSED:  https://github.com/patternfly/patternfly-react/issues/486

feat(react-core[Radio]): add pf4 radio component

---

packages/react-core/package.json
packages/react-core/src/components/Modal/Backdrop.js
packages/react-core/src/components/Modal/Backdrop.test.js
packages/react-core/src/components/Modal/Modal.js
packages/react-core/src/components/Modal/Modal.test.js
packages/react-core/src/components/Modal/ModalBox.js
packages/react-core/src/components/Modal/ModalBox.test.js
packages/react-core/src/components/Modal/ModalBoxBody.js
packages/react-core/src/components/Modal/ModalBoxBody.test.js
packages/react-core/src/components/Modal/ModalBoxCloseButton.js
packages/react-core/src/components/Modal/ModalBoxCloseButton.test.js
packages/react-core/src/components/Modal/ModalBoxFooter.js
packages/react-core/src/components/Modal/ModalBoxFooter.test.js
packages/react-core/src/components/Modal/ModalBoxHeader.js
packages/react-core/src/components/Modal/ModalBoxHeader.test.js
packages/react-core/src/components/Modal/ModalContent.js
packages/react-core/src/components/Modal/ModalContent.test.js
packages/react-core/src/components/Modal/__snapshots__/Backdrop.test.js.snap
packages/react-core/src/components/Modal/__snapshots__/Modal.test.js.snap
packages/react-core/src/components/Modal/__snapshots__/ModalBox.test.js.snap
packages/react-core/src/components/Modal/__snapshots__/ModalBoxBody.test.js.snap
packages/react-core/src/components/Modal/__snapshots__/ModalBoxCloseButton.test.js.snap
packages/react-core/src/components/Modal/__snapshots__/ModalBoxFooter.test.js.snap
packages/react-core/src/components/Modal/__snapshots__/ModalBoxHeader.test.js.snap
packages/react-core/src/components/Modal/__snapshots__/ModalContent.test.js.snap
packages/react-core/src/components/Modal/index.js
packages/react-core/src/components/index.js
packages/react-core/src/internal/constants.js
packages/react-docs/src/pages/components/modal.js

**What**: Added the Modal, ModalBox and Backdrop Components.
ISSUES CLOSED: #398, #397

feat(react-core/Modal): added PatternFly 4 Modal, ModalBox and Backdrop Components

---

packages/react-core/src/components/TextInput/TextInput.docs.js
packages/react-core/src/components/TextInput/TextInput.js
packages/react-core/src/components/TextInput/TextInput.test.js
packages/react-core/src/components/TextInput/__snapshots__/TextInput.test.js.snap
packages/react-core/src/components/TextInput/examples/AltTextInput.js
packages/react-core/src/components/TextInput/examples/DisabledTextInput.js
packages/react-core/src/components/TextInput/examples/InvalidTextInput.js
packages/react-core/src/components/TextInput/examples/ReadOnlyTextInput.js
packages/react-core/src/components/TextInput/examples/SimpleTextInput.js
packages/react-core/src/components/TextInput/index.js
packages/react-core/src/components/index.js

ISSUES CLOSED: #460 
Introduced the text input component

feat(pf4-text-input): introduce text input component

---

packages/patternfly-react/less/compound-label.less
packages/patternfly-react/sass/patternfly-react/_compound-label.scss
packages/patternfly-react/src/components/Wizard/Patterns/StatefulWizardPattern.js
packages/patternfly-react/src/components/Wizard/__snapshots__/Wizard.test.js.snap

chore(test warnings): fixes lint and jest test warnings

---

packages/patternfly-react/src/components/Notification/Wrappers/NotificationDrawerPanelWrapper.js

**What**: Fix the NotificationDrawerWrapper to support actionless notification.

fix(NotificationDrawerWrapper): support empty notification action

---

packages/patternfly-react/src/components/SessionTimeout/CountDownSessionTimeout.js
packages/patternfly-react/src/components/SessionTimeout/CountDownSessionTimeout.test.js
packages/patternfly-react/src/components/SessionTimeout/SessionTimeout.stories.js
packages/patternfly-react/src/components/SessionTimeout/SessionTimeout.test.js
packages/react-docs/src/components/propsTable/propsTable.js

affects: patternfly-react, @patternfly/react-docs

chore(prettier): fix prettier errors

---

packages/patternfly-react/src/components/Notification/Wrappers/NotificationDrawerPanelWrapper.js
packages/patternfly-react/src/components/Notification/Wrappers/Wrappers.test.js
packages/patternfly-react/src/components/Notification/Wrappers/__snapshots__/Wrappers.test.js.snap

**What**: Fix the NotificationDrawerWrapper to support date-less notification.

fix(NotificationDrawerWrapper): support missing notification create_at

---

packages/patternfly-3/patternfly-react-extensions/less/patternfly-react-extensions.less
packages/patternfly-3/patternfly-react-extensions/less/variables.less
packages/patternfly-3/patternfly-react-extensions/less/vertical-tabs.less
packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_patternfly-react-extensions.scss
packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_variables.scss
packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_vertical-tabs.scss
packages/patternfly-3/patternfly-react-extensions/src/components/VerticalTabs/VerticalTabs.js
packages/patternfly-3/patternfly-react-extensions/src/components/VerticalTabs/VerticalTabs.stories.js
packages/patternfly-3/patternfly-react-extensions/src/components/VerticalTabs/VerticalTabs.test.js
packages/patternfly-3/patternfly-react-extensions/src/components/VerticalTabs/VerticalTabsTab.js
packages/patternfly-3/patternfly-react-extensions/src/components/VerticalTabs/__snapshots__/VerticalTabs.test.js.snap
packages/patternfly-3/patternfly-react-extensions/src/components/VerticalTabs/_mocks_/mockVerticalTabsExample.js
packages/patternfly-3/patternfly-react-extensions/src/components/VerticalTabs/index.js
packages/patternfly-3/patternfly-react-extensions/src/index.js

**What**:
Adds vertical-tabs component to patternfly-react-extensions
https://rawgit.com/jeff-phillips-18/patternfly-react/vertical-tabs-storybook/index.html?knob-Max%20Shown=5&knob-Leeway=2&selectedKind=patternfly-react-extensions%2FWidgets%2FVertical%20Tabs&selectedStory=Vertical%20Tabs&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

feat(vertical tabs): add vertical-tabs component

---

packages/patternfly-4/react-core/src/components/Select/Select.d.ts
packages/patternfly-4/react-core/src/components/Select/Select.docs.js
packages/patternfly-4/react-core/src/components/Select/Select.js
packages/patternfly-4/react-core/src/components/Select/Select.test.js
packages/patternfly-4/react-core/src/components/Select/SelectOption.d.ts
packages/patternfly-4/react-core/src/components/Select/SelectOption.js
packages/patternfly-4/react-core/src/components/Select/SelectOptionGroup.d.ts
packages/patternfly-4/react-core/src/components/Select/SelectOptionGroup.js
packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.js.snap
packages/patternfly-4/react-core/src/components/Select/examples/SelectInput.js
packages/patternfly-4/react-core/src/components/Select/examples/SelectInputDisabled.js
packages/patternfly-4/react-core/src/components/Select/examples/SelectInputGrouped.js
packages/patternfly-4/react-core/src/components/Select/index.d.ts
packages/patternfly-4/react-core/src/components/Select/index.js
packages/patternfly-4/react-core/src/components/index.d.ts
packages/patternfly-4/react-core/src/components/index.js

ISSUES CLOSED: #461
**What**: Added the Patternfly 4 Select component
Live Demo: http://tlabaj.surge.sh/

feat(patternfly-4/react-core/): added Select Component

---

packages/patternfly-3/patternfly-react-extensions/less/catalog-tile.less
packages/patternfly-3/patternfly-react-extensions/less/variables.less
packages/patternfly-3/patternfly-react-extensions/package.json
packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_catalog-tile.scss
packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_variables.scss
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/CatalogTileView.js
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/CatalogTileView.stories.js
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/CatalogTileView.test.js
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/CatalogTileViewCategory.js
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/__mocks__/mockCatalogTileViewExample.js
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/__mocks__/mockItems.js
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/__snapshots__/CatalogTileView.test.js.snap
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/index.js
packages/patternfly-3/patternfly-react-extensions/src/index.js

**What**:
Adds the CatalogTileView component
https://rawgit.com/jeff-phillips-18/patternfly-react/catalog-tile-view-storybook/index.html?selectedKind=patternfly-react-extensions%2FCatalog%20Components%2FCatalog%20Tile%20View&selectedStory=CatalogTileView&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs
@serenamarie125 @tlwu2013

feat(catalog-tile-view): add CatalogTileView component

---

packages/patternfly-3/patternfly-react-extensions/src/components/VerticalTabs/VerticalTabs.test.js
packages/patternfly-3/patternfly-react-extensions/src/components/VerticalTabs/__snapshots__/VerticalTabs.test.js.snap

chore(tests): fix test warnings in vertical tabs component

---

packages/patternfly-4/react-core/package.json
packages/patternfly-4/react-core/src/components/Card/__snapshots__/Card.test.js.snap

fix(card): Fix card background color (#630)

---

packages/patternfly-4/package.json
packages/patternfly-4/verifyCoreVersions.js

Force syncing PatternFly 4 Core versions across PatternFly 4 React packages.

chore(pf4): force version of @patternfly/patternfly-next across packages

---

.public/index.html
.travis.yml
.travis/deploy_pr.sh
package.json
packages/patternfly-4/react-docs/gatsby-config.js
packages/patternfly-4/react-docs/package.json

**What**:  Adding regular PR deploy for both pf3 and pf4 PR's
**Link to Storybook**: None - and this no longer matters if we do this

fix(surge): add surge pr support to travis

---

packages/patternfly-4/react-core/src/components/Badge/examples/ReadBadge.js
packages/patternfly-4/react-core/src/components/Badge/examples/UnreadBadge.js

docs(PF4 badge): update doc to show read/unread styles appropriately

---

packages/patternfly-3/patternfly-react-extensions/less/table-grid.less
packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_table-grid.scss
packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGrid.js
packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGrid.stories.js
packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGrid.test.js
packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGridHead.js
packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGridRow.js
packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/__snapshots__/TableGrid.test.js.snap
packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/_mocks_/mockTableGridExample.js

**What**:
Adds support for checkbox select  to the TableGrid component
https://rawgit.com/jeff-phillips-18/patternfly-react/table-grid-checkbox-storybook/index.html?selectedKind=patternfly-react-extensions%2FContent%20Views%2FTableGrid&selectedStory=TableGrid&knob-Selection%20Type=checkbox

feat(TableGrid): add Checkbox select support to TableGrid

---

packages/patternfly-3/package.json
packages/patternfly-4/package.json

**What**: These packages should be ignored by semantic-release

fix(commit): add private config to hidden packages

---

packages/patternfly-3/README.md

fix(README): add README text for the patternfly-3 package

---

packages/patternfly-3/patternfly-react/README.md

fix(README): update test command

---

packages/patternfly-4/react-core/src/layouts/Toolbar/examples/SimpleToolbar.js
packages/patternfly-4/react-core/src/layouts/Toolbar/examples/SimpleToolbarSection.js

**Changes**
Fixed titles for toolbar demo and corrected aria-labels in demo as well
**Live demo**
https://5bb1db2dc6aed6483e5d5da3--zen-swanson-2d3350.netlify.com/layouts/toolbar

docs(toolbar): correct titles and aria lables for toolbar

---

.travis.yml
.travis/deploy_pr.sh

**What**: This ensures a deploy is made to surge with each successful PR merge

fix(deploy): add surge deployment for merged pr's

---

packages/patternfly-4/react-core/src/components/Alert/Alert.js
packages/patternfly-4/react-core/src/components/Badge/Badge.js
packages/patternfly-4/react-core/src/components/Card/Card.js
packages/patternfly-4/react-core/src/components/Card/CardBody.js
packages/patternfly-4/react-core/src/components/Card/CardFooter.js
packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.js
packages/patternfly-4/react-core/src/components/Radio/Radio.js
packages/patternfly-4/react-core/src/components/Title/Title.js
packages/patternfly-4/react-core/src/layouts/Bullseye/Bullseye.js
packages/patternfly-4/react-core/src/layouts/Gallery/Gallery.js
packages/patternfly-4/react-core/src/layouts/Gallery/GalleryItem.js
packages/patternfly-4/react-core/src/layouts/Grid/Grid.docs.js
packages/patternfly-4/react-core/src/layouts/Grid/Grid.js
packages/patternfly-4/react-core/src/layouts/Grid/GridItem.js
packages/patternfly-4/react-core/src/layouts/Grid/examples/GridOverrides.js
packages/patternfly-4/react-core/src/layouts/Grid/examples/GridPlayground.js
packages/patternfly-4/react-core/src/layouts/Level/Level.js
packages/patternfly-4/react-core/src/layouts/Level/LevelItem.js
packages/patternfly-4/react-core/src/layouts/Split/Split.js
packages/patternfly-4/react-core/src/layouts/Split/SplitItem.js
packages/patternfly-4/react-core/src/layouts/Stack/Stack.js
packages/patternfly-4/react-core/src/layouts/Stack/StackItem.js

ISSUES CLOSED: #538
**What**:add missing comments to component props

fix(patternfly-4/react-core): add missing comments to component props

---

.travis/deploy_pr.sh
.travis/release.sh

**What**: Improving release methodology - hopefully this gets us a master release of surge

fix(release): move docs builds into common location and update release

---

packages/patternfly-4/react-core/src/components/Progress/Progress.d.ts
packages/patternfly-4/react-core/src/components/Progress/Progress.docs.js
packages/patternfly-4/react-core/src/components/Progress/Progress.js
packages/patternfly-4/react-core/src/components/Progress/Progress.test.js
packages/patternfly-4/react-core/src/components/Progress/ProgressBar.js
packages/patternfly-4/react-core/src/components/Progress/ProgressContainer.js
packages/patternfly-4/react-core/src/components/Progress/__snapshots__/Progress.test.js.snap
packages/patternfly-4/react-core/src/components/Progress/examples/LargeProgress.js
packages/patternfly-4/react-core/src/components/Progress/examples/ProgressFailure.js
packages/patternfly-4/react-core/src/components/Progress/examples/ProgressFailureWithoutMeasure.js
packages/patternfly-4/react-core/src/components/Progress/examples/ProgressInside.js
packages/patternfly-4/react-core/src/components/Progress/examples/ProgressInsideSuccess.js
packages/patternfly-4/react-core/src/components/Progress/examples/ProgressOutside.js
packages/patternfly-4/react-core/src/components/Progress/examples/ProgressOutsideFailure.js
packages/patternfly-4/react-core/src/components/Progress/examples/ProgressSuccess.js
packages/patternfly-4/react-core/src/components/Progress/examples/ProgressWithDynamicDescription.js
packages/patternfly-4/react-core/src/components/Progress/examples/ProgressWithoutMeasure.js
packages/patternfly-4/react-core/src/components/Progress/examples/SimpleProgress.js
packages/patternfly-4/react-core/src/components/Progress/examples/SmallProgress.js
packages/patternfly-4/react-core/src/components/Progress/index.d.ts
packages/patternfly-4/react-core/src/components/Progress/index.js
packages/patternfly-4/react-core/src/components/index.d.ts
packages/patternfly-4/react-core/src/components/index.js

ISSUES CLOSED: #588
Adds progress component as described in https://pf-next.com/components/progress/examples/
Live site: https://5baa53701f12b776b4237f64--zen-swanson-2d3350.netlify.com/components/progress

feat(pf4-progress): introduce new component progress with it's variants

---

packages/patternfly-3/patternfly-react/src/components/Filter/Filter.test.js
packages/patternfly-3/patternfly-react/src/components/Sort/Sort.test.js
packages/patternfly-3/patternfly-react/src/components/Sort/SortTypeSelector.js

**What**:
Added more tests to `Sort` and `Filter` + fixed a bug in `Sort`.
:no_entry_sign:  None
:no_entry_sign:  None

test(components): Add tests to Filter and Sort selectors 

---

package.json
yarn.lock

**What**:
Closes #738 . Updates lerna-changelog.
https://github.com/lerna/lerna-changelog/issues/122

fix(lerna-changelog): updates lerna-changelog to 0.8.1

---

packages/patternfly-4/react-core/src/components/LoginBox/LoginBox.d.ts
packages/patternfly-4/react-core/src/components/LoginBox/LoginBox.docs.js
packages/patternfly-4/react-core/src/components/LoginBox/LoginBox.js
packages/patternfly-4/react-core/src/components/LoginBox/LoginBox.test.js
packages/patternfly-4/react-core/src/components/LoginBox/LoginBoxBody.d.ts
packages/patternfly-4/react-core/src/components/LoginBox/LoginBoxBody.js
packages/patternfly-4/react-core/src/components/LoginBox/LoginBoxBody.test.js
packages/patternfly-4/react-core/src/components/LoginBox/LoginBoxFooter.d.ts
packages/patternfly-4/react-core/src/components/LoginBox/LoginBoxFooter.js
packages/patternfly-4/react-core/src/components/LoginBox/LoginBoxFooter.test.js
packages/patternfly-4/react-core/src/components/LoginBox/LoginBoxHeader.d.ts
packages/patternfly-4/react-core/src/components/LoginBox/LoginBoxHeader.js
packages/patternfly-4/react-core/src/components/LoginBox/LoginBoxHeader.test.js
packages/patternfly-4/react-core/src/components/LoginBox/__snapshots__/LoginBox.test.js.snap
packages/patternfly-4/react-core/src/components/LoginBox/__snapshots__/LoginBoxBody.test.js.snap
packages/patternfly-4/react-core/src/components/LoginBox/__snapshots__/LoginBoxFooter.test.js.snap
packages/patternfly-4/react-core/src/components/LoginBox/__snapshots__/LoginBoxHeader.test.js.snap
packages/patternfly-4/react-core/src/components/LoginBox/examples/SimpleLoginBox.js
packages/patternfly-4/react-core/src/components/LoginBox/index.d.ts
packages/patternfly-4/react-core/src/components/LoginBox/index.js
packages/patternfly-4/react-core/src/components/index.js

ISSUES CLOSED: #676  
Introduced the LoginBox component

feat(LoginBox): introduce the pf4 loginbox component

---

packages/patternfly-4/react-core/README.md
packages/patternfly-4/react-tokens/README.md
packages/react-icons/README.md

Fixes #741
**What**:  Update link for PF4-React documentation page

docs(README): Update link for PF4-React documentation page

---

packages/patternfly-4/react-core/src/layouts/Login/Login.d.ts
packages/patternfly-4/react-core/src/layouts/Login/Login.docs.js
packages/patternfly-4/react-core/src/layouts/Login/Login.js
packages/patternfly-4/react-core/src/layouts/Login/Login.test.js
packages/patternfly-4/react-core/src/layouts/Login/LoginFooter.d.ts
packages/patternfly-4/react-core/src/layouts/Login/LoginFooter.js
packages/patternfly-4/react-core/src/layouts/Login/LoginHeader.d.ts
packages/patternfly-4/react-core/src/layouts/Login/LoginHeader.js
packages/patternfly-4/react-core/src/layouts/Login/LoginHeaderBrand.d.ts
packages/patternfly-4/react-core/src/layouts/Login/LoginHeaderBrand.js
packages/patternfly-4/react-core/src/layouts/Login/__snapshots__/Login.test.js.snap
packages/patternfly-4/react-core/src/layouts/Login/examples/SimpleLoginLayout.js
packages/patternfly-4/react-core/src/layouts/Login/examples/common/getContainerProps.js
packages/patternfly-4/react-core/src/layouts/Login/index.d.ts
packages/patternfly-4/react-core/src/layouts/Login/index.js
packages/patternfly-4/react-core/src/layouts/index.d.ts
packages/patternfly-4/react-core/src/layouts/index.js

Adds the login layout to PF4.
Fixes https://github.com/patternfly/patternfly-react/issues/677

PF4: Login layout

---

packages/patternfly-4/react-core/src/components/Form/ActionGroup.d.ts
packages/patternfly-4/react-core/src/components/Form/ActionGroup.js
packages/patternfly-4/react-core/src/components/Form/ActionGroup.test.js
packages/patternfly-4/react-core/src/components/Form/Form.d.ts
packages/patternfly-4/react-core/src/components/Form/Form.docs.js
packages/patternfly-4/react-core/src/components/Form/Form.js
packages/patternfly-4/react-core/src/components/Form/Form.test.js
packages/patternfly-4/react-core/src/components/Form/FormContext.js
packages/patternfly-4/react-core/src/components/Form/FormGroup.d.ts
packages/patternfly-4/react-core/src/components/Form/FormGroup.js
packages/patternfly-4/react-core/src/components/Form/FormGroup.test.js
packages/patternfly-4/react-core/src/components/Form/__snapshots__/ActionGroup.test.js.snap
packages/patternfly-4/react-core/src/components/Form/__snapshots__/Form.test.js.snap
packages/patternfly-4/react-core/src/components/Form/__snapshots__/FormGroup.test.js.snap
packages/patternfly-4/react-core/src/components/Form/examples/AlternativeForm.js
packages/patternfly-4/react-core/src/components/Form/examples/HorizontalForm.js
packages/patternfly-4/react-core/src/components/Form/examples/InvalidForm.js
packages/patternfly-4/react-core/src/components/Form/examples/SimpleForm.js
packages/patternfly-4/react-core/src/components/Form/examples/VariousLabelsForm.js
packages/patternfly-4/react-core/src/components/Form/index.d.ts
packages/patternfly-4/react-core/src/components/Form/index.js
packages/patternfly-4/react-core/src/components/index.d.ts
packages/patternfly-4/react-core/src/components/index.js
packages/patternfly-4/react-core/src/internal/htmlConstants.js

**What**:
Adds Form, FormGroup, ActionGroup component
issue: #390 
http://chivalrous-scale.surge.sh/components/form
There are also issues with testing of console.errors. In some cases they work, in others not. I skipped them.

feat(formComponent): add Form, FormGroup, ActionGroup PF4 components

---

packages/patternfly-4/react-docs/README.md
packages/patternfly-4/react-docs/src/components/componentDocs/componentDocs.js
packages/patternfly-4/react-docs/src/components/example/example.js
packages/patternfly-4/react-docs/src/components/example/liveDemo.js

**What**:
Fix ability to toggle live mode

fix(react-docs): Fix live mode toggling

---

packages/patternfly-4/react-core/src/components/Progress/Progress.d.ts

Closes: #782
**What**:
Correct typescript definition for small progressbar.

fix(Progress): Correct small progress size

---

packages/patternfly-4/react-core/src/components/BackgroundImage/BackgroundImage.d.ts
packages/patternfly-4/react-core/src/components/BackgroundImage/index.d.ts
packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.d.ts
packages/patternfly-4/react-core/src/components/Form/FormGroup.d.ts

**What**:
fixes all remaining typescript definition errors found in #770. Also ensures I do not get any of these downstream in my prototype 😸 
(none)

fix(typescript definitions): fix ts defs for checkbox, BackgroundImage, and Form

---

packages/patternfly-3/patternfly-react-extensions/less/catalog-tile.less
packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_catalog-tile.scss
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/__images__/OpenShift.svg
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/__mocks__/mockItems.js

Description text could overflow the tile in Firefox. This is a better CSS constraint.

fix(CatalogTile): Fix to not allow the description text to overflow the tile

---

packages/patternfly-4/react-core/src/components/Radio/Radio.d.ts

**What**:
Re-addressing #770 after adding enhancements in #756.
none

fix(ts-definitions): fix type definitions for radio

---

packages/patternfly-4/react-core/package.json
packages/patternfly-4/react-core/src/components/Backdrop/__snapshots__/Backdrop.test.js.snap
packages/patternfly-4/react-core/src/components/BackgroundImage/__snapshots__/BackgroundImage.test.js.snap
packages/patternfly-4/react-tokens/package.json
yarn.lock

**What**:
Update PF4 core versions

chore(pf4): update core

---

packages/patternfly-4/react-core/src/components/Form/examples/HorizontalForm.js
packages/patternfly-4/react-core/src/components/Form/examples/SimpleForm.js

**What**:
- Changes radios in formComponent's examples to new radio component, which was merged recently
- https://805-pr-patternfly-react-patternfly.surge.sh/patternfly-4/components/form

docs(formComponent): changes radios in examples to radio component

---

packages/patternfly-4/verifyCoreVersions.js
packages/react-icons/package.json
yarn.lock

**What**:
Update core for react-icons and the compare versions script

chore(pf4): update core for react-icons

---

scripts/generators/package/.babelrc.hbs
scripts/generators/package/.npmignore.hbs
scripts/generators/package/index.js
scripts/generators/package/package.json.hbs

Added babelrc and npmignore files as part of the package generator. package.json scripts were also
added to reflect the new babel building structure

chore(generators): Update package generator to new build script styles

---

packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/CatalogTileView.test.js
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/CatalogTileViewCategory.js
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/__mocks__/mockCatalogTileViewExample.js
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/__snapshots__/CatalogTileView.test.js.snap

fix(CatalogTileView): Behave correctly when CatalogTile components are wrapped

---

packages/patternfly-4/react-core/src/components/Nav/Nav.js
packages/patternfly-4/react-core/src/components/Nav/NavExpandable.js
packages/patternfly-4/react-core/src/components/Nav/NavItem.js
packages/patternfly-4/react-core/src/components/Nav/NavToggle.js
packages/patternfly-4/react-core/src/components/Nav/__snapshots__/Nav.test.js.snap
packages/patternfly-4/react-core/src/components/Nav/examples/NavExpandableList.js

Closes: #852 
**What**:
- Allow onClick to be added to NavItem
- Don't stop event propagation from NavItem

Nav item update to handle onClick

---

packages/patternfly-4/react-core/src/components/Progress/ProgressBar.js

Closes #847 
Update usage of styles in ProgressBar

fix(PF4 - Progress): update styles usage

---

packages/patternfly-3/patternfly-react-extensions/less/badged-resource.less
packages/patternfly-3/patternfly-react-extensions/less/patternfly-react-extensions.less
packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_badged-resource.scss
packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_patternfly-react-extensions.scss
packages/patternfly-3/patternfly-react-extensions/src/components/BadgedResource/BadgedResource.js
packages/patternfly-3/patternfly-react-extensions/src/components/BadgedResource/BadgedResource.stories.js
packages/patternfly-3/patternfly-react-extensions/src/components/BadgedResource/BadgedResource.test.js
packages/patternfly-3/patternfly-react-extensions/src/components/BadgedResource/ResourceTypes.js
packages/patternfly-3/patternfly-react-extensions/src/components/BadgedResource/__snapshots__/BadgedResource.test.js.snap
packages/patternfly-3/patternfly-react-extensions/src/components/BadgedResource/index.js
packages/patternfly-3/patternfly-react-extensions/src/index.js

fixes #775
cc @rhamilto 
Direct storybook link: 
https://829-pr-patternfly-react-patternfly.surge.sh/patternfly-3/index.html?selectedKind=patternfly-react-extensions%2FWidgets%2FBadged%20Resource&selectedStory=BadgedResource

feat(BadgedResource): Add BadgedResource component to patternfly-react-extensions

---

packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutDefaultNav.js
packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutExpandableNav.js
packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutGroupsNav.js
packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutHorizontalNav.js
packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutHorizontalNavCondensed.js
packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutSimpleNav.js
packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutVerticalNavCondensed.js

fix(overlay): add anchor tag to filter overlay

---

packages/patternfly-3/patternfly-react-extensions/less/badged-resource.less
packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_badged-resource.scss
packages/patternfly-3/patternfly-react-extensions/src/components/BadgedResource/BadgedResource.js
packages/patternfly-3/patternfly-react-extensions/src/components/BadgedResource/BadgedResource.stories.js
packages/patternfly-3/patternfly-react-extensions/src/components/BadgedResource/BadgedResource.test.js
packages/patternfly-3/patternfly-react-extensions/src/components/BadgedResource/ResourceTypes.js
packages/patternfly-3/patternfly-react-extensions/src/components/BadgedResource/__snapshots__/BadgedResource.test.js.snap
packages/patternfly-3/patternfly-react-extensions/src/components/BadgedResource/index.js

Also provides defaults for some resource kinds.

fix(BadgedResource): Use css over inlined style for bg color

---

packages/patternfly-3/patternfly-react/src/components/DropdownKebab/DropdownKebab.js
packages/patternfly-3/patternfly-react/src/components/DropdownKebab/DropdownKebab.stories.js
packages/patternfly-3/patternfly-react/src/components/DropdownKebab/DropdownKebab.test.js
packages/patternfly-3/patternfly-react/src/components/DropdownKebab/__snapshots__/DropdownKebab.test.js.snap
packages/patternfly-3/patternfly-react/src/components/Table/__snapshots__/Table.test.js.snap
packages/patternfly-3/patternfly-react/src/components/Toolbar/__snapshots__/Toolbar.test.js.snap

**What**:
Allow the title attribute to be passed through for DropdownKebab

fix(DropdownKebab): Allow title attribute

---

packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.d.ts

**What**:
fixes issues noted in [#898](https://github.com/patternfly/patternfly-react/pull/898#issuecomment-436970806) and properly types DropdownProps types
none

fix(dropdown props): fix typescript typings

---

packages/patternfly-4/react-core/src/layouts/index.d.ts

**What**:
fixes the following error with layout index.d.ts:
```
| => yarn run dev
yarn run v1.7.0
$ rm -rf ./public/dist/ && ts-node -O '{"module":"commonjs"}' ./node_modules/.bin/webpack --mode development --watch --progress
Starting type checking service...
Using 1 worker with 2048MB memory limit
10% building modules 1/1 modules 0 active
Webpack is watching the files…
98% after emittingERROR in /Users/priley/GitHub/web-ui/frontend/node_modules/@patternfly/react-core/dist/js/layouts/index.d.ts(5,15):
TS2307: Cannot find module './Login'.
Version: typescript 2.9.2
Time: 17025ms
4683 modules
^C
```
origin-ci-test build log:
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_console/674/pull-ci-openshift-console-master-frontend/1034/build-log.txt
Last one for today …

fix(layout): fix layout tsd

---

packages/patternfly-3/patternfly-react/sass/patternfly-react/_expand-collapse.scss
packages/patternfly-3/react-console/README.md
packages/patternfly-3/react-console/less/console.less
packages/patternfly-3/react-console/less/desktop-viewer.less
packages/patternfly-3/react-console/less/variables.less
packages/patternfly-3/react-console/package.json
packages/patternfly-3/react-console/sass/_desktop-viewer.scss
packages/patternfly-3/react-console/sass/_variables.scss
packages/patternfly-3/react-console/sass/_vnc-console.scss
packages/patternfly-3/react-console/sass/console.scss
packages/patternfly-3/react-console/src/DesktopViewer/ConnectWithRemoteViewer.js
packages/patternfly-3/react-console/src/DesktopViewer/DesktopViewer.js
packages/patternfly-3/react-console/src/DesktopViewer/DesktopViewer.stories.js
packages/patternfly-3/react-console/src/DesktopViewer/DesktopViewer.test.js
packages/patternfly-3/react-console/src/DesktopViewer/ManualConnection.js
packages/patternfly-3/react-console/src/DesktopViewer/MoreInformationDefaultContent.js
packages/patternfly-3/react-console/src/DesktopViewer/MoreInformationInstallVariant.js
packages/patternfly-3/react-console/src/DesktopViewer/__snapshots__/DesktopViewer.test.js.snap
packages/patternfly-3/react-console/src/DesktopViewer/consoleDetailPropType.js
packages/patternfly-3/react-console/src/DesktopViewer/index.js
packages/patternfly-3/react-console/src/DesktopViewer/vvFileGenerator.js
packages/patternfly-3/react-console/src/common/constants.js
packages/patternfly-3/react-console/src/index.js
yarn.lock

**What**:  introduce DesktopViewer component
**Link to Storybook**: [https://607-pr-patternfly-react-patternfly.surge.sh](https://607-pr-patternfly-react-patternfly.surge.sh/patternfly-3/index.html?selectedKind=react-console%20%28%40patternfly%29%2FDesktopViewer&selectedStory=DesktopViewer&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)
**Additional info**:
The components unifies access to virtual machine/server console
connection via desktop (means non-browser) viewer application.
A button for downloading .vv file (of "application/x-virt-viewer" mime-type)
is rendered.
Console details are farther rendered in textual form to enable copy&paste
to a generic desktop viewer application.
This component implements common use case for …

feat(DesktopViewer): introduce DesktopViewer component

---

packages/patternfly-3/patternfly-react/src/components/LoginPage/__snapshots__/LoginPage.test.js.snap
packages/patternfly-3/patternfly-react/src/components/LoginPage/__snapshots__/SocialLoginPage.test.js.snap
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardForm.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardInput.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardRememberMe.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardSettings.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardSignUp.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardWithValidation.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginLanguagePicker.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginPageComponents/LoginFooterLinks.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginPageComponents/LoginPageHeader.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginPageComponents/LoginPageWithTranslation.js

While trying to implement the [LoginPage component in Foreman](https://github.com/theforeman/foreman/pull/6234)
I faced some problems which are fixed in this PR.

fix(LoginPage): small fixes.

---

packages/patternfly-3/patternfly-react-extensions/package.json
packages/patternfly-3/patternfly-react/package.json
packages/patternfly-3/patternfly-react/src/components/HintBlock/HintBlock.js
packages/patternfly-3/patternfly-react/src/components/HintBlock/HintBlock.stories.js
packages/patternfly-3/patternfly-react/src/components/HintBlock/HintBlock.test.js
packages/patternfly-3/patternfly-react/src/components/HintBlock/__snapshots__/HintBlock.test.js.snap
packages/patternfly-3/patternfly-react/src/components/HintBlock/index.js
packages/patternfly-3/patternfly-react/src/index.js
packages/patternfly-3/react-console/package.json

Direct storybook link: https://922-pr-patternfly-react-patternfly.surge.sh/patternfly-3/index.html?selectedKind=patternfly-react%2FCommunication%2FHintBlock&selectedStory=HintBlock

feat(HintBlock): Add the HintBlock component

---

packages/patternfly-4/react-charts/package.json
packages/patternfly-4/react-core/package.json
packages/patternfly-4/react-core/src/components/Progress/__snapshots__/Progress.test.js.snap
packages/patternfly-4/react-core/src/layouts/Page/__snapshots__/Page.test.js.snap
packages/patternfly-4/react-core/src/layouts/Page/__snapshots__/PageHeader.test.js.snap
packages/patternfly-4/react-styled-system/package.json
packages/patternfly-4/react-table/package.json
packages/patternfly-4/react-tokens/package.json
packages/react-icons/package.json
yarn.lock

**What**: 
Updating the patternfly-next version as some changes were merged in to resolve https://github.com/patternfly/patternfly-react/issues/888

chore(pf-core): update core for PF4

---

packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardWithValidation.js

As part of the [LoginPage implementation in Foreman](https://github.com/theforeman/foreman/pull/6234) there need to be some fixes in inputs validation.

fix(LoginPage): Improve inputs validation

---

packages/patternfly-3/react-console/less/console-selector.less
packages/patternfly-3/react-console/less/serial-console.less
packages/patternfly-3/react-console/less/vnc-console.less
packages/patternfly-3/react-console/sass/_console-selector.scss
packages/patternfly-3/react-console/sass/_serial-console.scss
packages/patternfly-3/react-console/sass/_vnc-console.scss
packages/patternfly-3/react-console/src/AccessConsoles/__snapshots__/AccessConsoles.test.js.snap
packages/patternfly-3/react-console/src/SerialConsole/SerialConsole.js
packages/patternfly-3/react-console/src/SerialConsole/__snapshots__/SerialConsole.test.js.snap
packages/patternfly-3/react-console/src/VncConsole/VncConsole.js
packages/patternfly-3/react-console/src/VncConsole/__snapshots__/VncConsole.test.js.snap

**What**: Partially unify code structure of related components.
Both components were created and reviewed independently leading to non-aligned code for the similar
visual effect. This patch unifies use of the Toolbar while having optional integration with
`AccessConsoles` component in mind.
Sass/Less of both components are refactored to use nesting.
No new feature is introduced.

refactor(SerialConsole,VncConsole): Unify use of Toolbar

---

packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardForm.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardSubmitButton.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardWithValidation.js

As part of the [LoginPage implementation in Foreman](https://github.com/theforeman/foreman/pull/6234) 
Adding loading spinner and disable mode to the login submit button.

fix(LoginPage): improve submit button UX

---

packages/patternfly-3/patternfly-react/less/treeview.less

**What**: Fixes less variables in treeview from scss file (https://github.com/patternfly/patternfly-react/issues/943)

fix(less): convert less variables from scss in treeview - #943

---

scripts/generators/patternfly-4-component/templates/component/examples/Simple{{componentName}}.js
scripts/generators/patternfly-4-component/templates/component/{{componentName}}.docs.js

#924
**What**: Update generator to match new docs structure introduced by PR #915 

chore(generator): Update generator to match new docs structure

---

CONTRIBUTING.md
packages/patternfly-3/patternfly-react/CONTRIBUTING.md
packages/patternfly-4/react-core/CONTRIBUTING.md

**What**: Hosting the documentation and Storybook is now a step in the build process. It is generated and linked after the pull request is built.

docs(Contribution Guide): update Contribution Guide demo hosting step

---

packages/patternfly-3/patternfly-react/src/index.js

**What**:
Adds LoadingState component to top level exports

fix(LoadingState): Add LoadingState component to exports (#881)

---

packages/patternfly-4/react-core/src/components/AboutModal/examples/SimpleAboutModal.js
packages/patternfly-4/react-core/src/components/Brand/examples/SimpleBrand.js
packages/patternfly-4/react-core/src/components/Form/examples/HorizontalForm.js
packages/patternfly-4/react-core/src/components/Form/examples/InvalidForm.js
packages/patternfly-4/react-core/src/components/Form/examples/SimpleForm.js
packages/patternfly-4/react-docs/src/components/navigation/navigation.js
packages/patternfly-4/react-docs/src/components/navigation/navigation.styles.js
packages/patternfly-4/react-docs/src/components/navigation/navigationItem.js
packages/patternfly-4/react-docs/src/components/navigation/navigationItem.styles.js
packages/patternfly-4/react-docs/src/components/navigation/navigationItemGroup.js
packages/patternfly-4/react-docs/src/components/navigation/navigationItemGroup.styles.js
yarn.lock

This PR applies some minor html adjustments for improved a11y experience.
**What**: Update html for better accessibility
**Additional issues**: fix https://github.com/patternfly/patternfly-react/issues/908
@jgiardino I notice that the combination of placeholder text and aria-label gives an interesting experience on VO (for the component search adjustment) - mind seeing how this reacts in JAWS? If you get a same experience, I'm inclined to recommend we dump placeholder text for a text description outside of the input. I know we've discussed this before in a11y reviews, now we finally have a real use case! Let me know what you think.
update alt text to match pf core
correct html attribute name
give component search an accessible name
align alt text for brand images

fix(a11y): tweak html for better accessibility

---

packages/patternfly-4/react-core/src/components/Badge/Badge.docs.js
packages/patternfly-4/react-core/src/components/Badge/examples/ReadBadge.js
packages/patternfly-4/react-core/src/components/Badge/examples/UnreadBadge.js
packages/patternfly-4/react-core/src/components/Badge/examples/common/getContainerProps.js

**What**: update badge examples to match core.
References #966

fix(Badge): remove margin between badges to match core

---

packages/patternfly-3/patternfly-react/sass/patternfly-react/_login-page.scss
packages/patternfly-3/patternfly-react/src/components/LoginPage/LoginPage.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/LoginPage.test.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/__snapshots__/LoginPage.test.js.snap
packages/patternfly-3/patternfly-react/src/components/LoginPage/__snapshots__/SocialLoginPage.test.js.snap
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/BasicLoginCardLayout.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCard.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardForgotPassword.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardForm.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardHeader.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardInput.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardInputWarning.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardRememberMe.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardSettings.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardSignUp.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardSocialColumns.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardSocialLink.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardSocialSection.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardSubmitButton.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginFormError.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginLanguagePicker.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/SocialLoginCard.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/mocks/messages.en.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/mocks/messages.fr.js

Adding Login Page Card components props documentations.
Refactoring small parts of the code to be more readable.

fix(LoginPage): add LoginPageCard inner components documentation.

---

packages/patternfly-4/react-core/src/components/Card/Card.docs.js
packages/patternfly-4/react-core/src/components/Card/examples/ContentOnlyCard.js
packages/patternfly-4/react-core/src/components/Card/examples/NoFooterCard.js
packages/patternfly-4/react-core/src/components/Card/examples/NoHeaderCard.js

**What**: Add documentation to match core variations and to use same language.
Addresses: #968

docs(Card): add card variations to documentation

---

packages/patternfly-4/react-core/src/layouts/Page/examples/HorizontalPage.js
packages/patternfly-4/react-core/src/layouts/Page/examples/VerticalPage.js

docs(Page): match example color order to core

---

packages/patternfly-4/react-core/src/components/AboutModal/examples/SimpleAboutModal.js

**What**: logo alt text in about modal was incorrect
**Refer to issue**: #1008

docs(AboutModal): update logo alt text to Patternfly Logo

---

packages/patternfly-4/react-core/src/components/Alert/Alert.docs.js
packages/patternfly-4/react-core/src/components/Alert/examples/DangerAlert.js
packages/patternfly-4/react-core/src/components/Alert/examples/InfoAlert.js
packages/patternfly-4/react-core/src/components/Alert/examples/SuccessAlert.js
packages/patternfly-4/react-core/src/components/Alert/examples/WarningAlert.js

docs(Alert): match Alert docs to core examples

---

packages/patternfly-3/patternfly-react/src/components/Chart/BulletChart/BulletChart.js
packages/patternfly-3/patternfly-react/src/components/Chart/BulletChart/BulletChart.test.js
packages/patternfly-3/patternfly-react/src/components/Chart/BulletChart/BulletChartRange.js
packages/patternfly-3/patternfly-react/src/components/Chart/BulletChart/BulletChartThreshold.js
packages/patternfly-3/patternfly-react/src/components/Chart/BulletChart/BulletChartValue.js
packages/patternfly-3/patternfly-react/src/components/Chart/BulletChart/__snapshots__/BulletChart.test.js.snap
packages/patternfly-3/patternfly-react/src/components/Chart/Stories/BulletChartStory.js

feat(BulletChart): Allow for custom values (non-percent) and legend text

---

CHANGELOG.md
packages/patternfly-4/CHANGELOG.md
packages/patternfly-4/package.json
packages/patternfly-4/react-core/CHANGELOG.md
packages/patternfly-4/react-core/package.json
packages/patternfly-4/react-docs/package.json
packages/patternfly-4/react-table/package.json

Local release to unblock semantic release

---

packages/patternfly-3/patternfly-react/src/components/Chart/BulletChart/BulletChart.js

fix(BulletChart): Fix for duplicate key warning on ranges

---

packages/patternfly-3/patternfly-react/src/components/LoginPage/SocialLoginPage.test.js

fix(SocialLoginPage): fix the props provided in SocialLoginPage test.

---

packages/patternfly-4/react-charts/package.json
packages/patternfly-4/react-core/package.json
packages/patternfly-4/react-core/src/components/Alert/__snapshots__/Alert.test.js.snap
packages/patternfly-4/react-core/src/components/BackgroundImage/__snapshots__/BackgroundImage.test.js.snap
packages/patternfly-4/react-core/src/components/Badge/__snapshots__/Badge.test.js.snap
packages/patternfly-4/react-core/src/components/Breadcrumb/__snapshots__/BreadcrumbHeading.test.js.snap
packages/patternfly-4/react-core/src/components/Breadcrumb/__snapshots__/BreadcrumbItem.test.js.snap
packages/patternfly-4/react-core/src/components/Button/__snapshots__/Button.test.js.snap
packages/patternfly-4/react-core/src/components/Card/__snapshots__/CardBody.test.js.snap
packages/patternfly-4/react-core/src/components/Card/__snapshots__/CardFooter.test.js.snap
packages/patternfly-4/react-core/src/components/Card/__snapshots__/CardHeader.test.js.snap
packages/patternfly-4/react-core/src/components/Checkbox/__snapshots__/Checkbox.test.js.snap
packages/patternfly-4/react-core/src/components/Label/__snapshots__/Label.test.js.snap
packages/patternfly-4/react-core/src/components/List/__snapshots__/List.test.js.snap
packages/patternfly-4/react-core/src/components/Modal/ModalBoxCloseButton.js
packages/patternfly-4/react-core/src/components/Modal/__snapshots__/ModalBoxCloseButton.test.js.snap
packages/patternfly-4/react-core/src/components/Popover/__snapshots__/Popover.test.js.snap
packages/patternfly-4/react-core/src/components/Radio/__snapshots__/Radio.test.js.snap
packages/patternfly-4/react-core/src/layouts/Level/__snapshots__/Level.test.js.snap
packages/patternfly-4/react-core/src/layouts/Page/Page.js
packages/patternfly-4/react-core/src/layouts/Page/PageHeader.js
packages/patternfly-4/react-core/src/layouts/Page/PageSection.js
packages/patternfly-4/react-core/src/layouts/Page/PageSidebar.js
packages/patternfly-4/react-core/src/layouts/Page/__snapshots__/Page.test.js.snap
packages/patternfly-4/react-core/src/layouts/Page/__snapshots__/PageHeader.test.js.snap
packages/patternfly-4/react-styled-system/package.json
packages/patternfly-4/react-table/package.json
packages/patternfly-4/react-tokens/package.json
packages/react-icons/package.json
yarn.lock

Updating core to 1.0.105
Resulting change:
Updated path for Page from layouts/Page/page.css to components/Page/page.css
Other affected components/layouts:
Alert
Badge
Breadcrumb
Button
Card
Checkbox
Label
List
Radio
Level

Update core .105

---

.public/index.html

fix(showcase): Fix style on showcase page

---

packages/patternfly-3/patternfly-react-extensions/less/diffview.less
packages/patternfly-3/patternfly-react-extensions/less/patternfly-react-extensions.less
packages/patternfly-3/patternfly-react-extensions/package.json
packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_diffview.scss
packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_patternfly-react-extensions.scss
packages/patternfly-3/patternfly-react-extensions/src/components/DiffView/DiffView.js
packages/patternfly-3/patternfly-react-extensions/src/components/DiffView/DiffView.stories.js
packages/patternfly-3/patternfly-react-extensions/src/components/DiffView/DiffView.test.js
packages/patternfly-3/patternfly-react-extensions/src/components/DiffView/__snapshots__/DiffView.test.js.snap
packages/patternfly-3/patternfly-react-extensions/src/components/DiffView/_mocks_/DiffViewMocks.js
packages/patternfly-3/patternfly-react-extensions/src/components/DiffView/index.js
packages/patternfly-3/patternfly-react-extensions/src/index.js
yarn.lock

**What**:
DiffView component.
The component accepts either a git diff patch or Old and New Text.
Thought the best place to put this component is inside extensions.
Example for Unified View:
Split View:

feat(component): Creating a DiffView Component

---

packages/patternfly-4/react-core/src/components/Alert/Alert.js
packages/patternfly-4/react-core/src/components/Alert/__snapshots__/Alert.test.js.snap

**What**: Added optional variant label to replace sr text with custom string. When not defined, uses the current lookup to get variant text.
**Refer to issue**: #1050

feat(Alert): add sr variant customization

---

packages/patternfly-4/react-core/src/components/BackgroundImage/BackgroundImage.d.ts
packages/patternfly-4/react-core/src/components/BackgroundImage/BackgroundImage.js
packages/patternfly-4/react-core/src/components/BackgroundImage/__snapshots__/BackgroundImage.test.js.snap
packages/patternfly-4/react-core/src/components/BackgroundImage/examples/SimpleBackgroundImage.js

Accelerating fix started by #1111

fix(BackgroundImage): remove old tokens

---

packages/patternfly-4/react-core/src/components/Select/Select.docs.js
packages/patternfly-4/react-core/src/components/Select/examples/SelectInputInvalid.js

**What**:
Added another example to the `Select` component: invalid select input.

docs(Select): Add an invalid select example

---

packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.docs.js
packages/patternfly-4/react-core/src/components/Dropdown/examples/IconDropdown.js

**What**:
Add example to show how to create an icon only drop down.

Updated drop down with icon only example

---

packages/patternfly-3/react-console/src/VncConsole/VncConsole.js

The VNC session is properly disconnected when unmounting the VncConsole component. This fixes
memory-leak and asynchronously fired events to an unmounted component.
**What**: Disconnect VNC when unmounting VncConsole component

fix(VncConsole): disconnect VNC session when unmounting

---

packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncher.d.ts
packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncher.docs.js
packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncher.js
packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncher.test.js
packages/patternfly-4/react-core/src/components/ApplicationLauncher/__snapshots__/ApplicationLauncher.test.js.snap
packages/patternfly-4/react-core/src/components/ApplicationLauncher/examples/SimpleApplicationLauncher.js
packages/patternfly-4/react-core/src/components/ApplicationLauncher/examples/TooltipApplicationLauncher.js
packages/patternfly-4/react-core/src/components/ApplicationLauncher/index.d.ts
packages/patternfly-4/react-core/src/components/ApplicationLauncher/index.js
packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.js
packages/patternfly-4/react-core/src/components/Dropdown/DropdownMenu.js
packages/patternfly-4/react-core/src/components/index.ts
yarn.lock

**What**:
Added Application Launcher Component.

Feat 1130: Application Launcher

---

packages/patternfly-4/react-charts/package.json
packages/patternfly-4/react-core/package.json
packages/patternfly-4/react-core/src/components/Alert/__snapshots__/Alert.test.js.snap
packages/patternfly-4/react-core/src/components/Avatar/index.d.ts
packages/patternfly-4/react-core/src/components/Avatar/index.ts
packages/patternfly-4/react-core/src/components/Button/__snapshots__/Button.test.js.snap
packages/patternfly-4/react-core/src/components/Card/__snapshots__/CardBody.test.js.snap
packages/patternfly-4/react-core/src/components/Card/__snapshots__/CardFooter.test.js.snap
packages/patternfly-4/react-core/src/components/Card/__snapshots__/CardHeader.test.js.snap
packages/patternfly-4/react-core/src/components/Form/__snapshots__/ActionGroup.test.js.snap
packages/patternfly-4/react-core/src/components/Form/__snapshots__/FormGroup.test.js.snap
packages/patternfly-4/react-core/src/components/Label/Label.js
packages/patternfly-4/react-core/src/components/Label/__snapshots__/Label.test.js.snap
packages/patternfly-4/react-core/src/components/Tooltip/Tooltip.d.ts
packages/patternfly-4/react-core/tsconfig.json
packages/patternfly-4/react-styled-system/package.json
packages/patternfly-4/react-table/package.json
packages/patternfly-4/react-tokens/package.json
packages/react-icons/package.json
yarn.lock

**What**:
Updated to use isolated modules for typescript, fixed Tooltip.d.ts, and updated pf-next.
Fixes issue #1121

Fix(dependencies): Fix react-tokens dependency and Tooltip typescript

---

packages/patternfly-4/react-core/package.json
packages/patternfly-4/react-core/src/components/Dropdown/DropdownItem.d.ts
yarn.lock

**What**:
fixes https://github.com/patternfly/patternfly-react/issues/1154
upstream issue: https://github.com/openshift/console/pull/1048

fix(Dropdown typings): fix the DropdownItem typings 

---

packages/patternfly-4/react-charts/package.json

fix(prerelease): attempt to add prerelease channel to react-charts

---

packages/patternfly-4/react-charts/package.json
packages/patternfly-4/react-core/package.json
packages/patternfly-4/react-core/src/components/Alert/Alert.js
packages/patternfly-4/react-core/src/components/Alert/__snapshots__/Alert.test.js.snap
packages/patternfly-4/react-core/src/components/Nav/NavExpandable.js
packages/patternfly-4/react-core/src/components/Nav/__snapshots__/Nav.test.js.snap
packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutDefaultNav.js
packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutExpandableNav.js
packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutGroupsNav.js
packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutHorizontalNav.js
packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutSimpleNav.js
packages/patternfly-4/react-styled-system/package.json
packages/patternfly-4/react-table/package.json
packages/patternfly-4/react-tokens/package.json
packages/react-icons/package.json
yarn.lock

Chore(update): Update core to 1.0.120

---

packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggle.js
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/DropdownToggle.test.js.snap
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Toggle.test.js.snap

**What**:
adds this functionality from core: https://github.com/patternfly/patternfly-next/pull/971

fix(dropdown): add span wrapper for dropdown toggle text

---

.travis/before_install.sh
package.json

**What**:
There seems to be some issues w/ migrating 2->3 and generating npmrc/changelogs...this should hopefully fix those.
https://github.com/almin/almin/issues/361
https://github.com/lerna/lerna/issues/1591#issuecomment-414668502

fix(lerna3): ignore npmrc

---

.travis/before_install.sh
package.json

Reverts patternfly/patternfly-react#1198

Revert "fix(lerna3): ignore npmrc"

---

packages/patternfly-4/react-core/src/components/Button/Button.docs.js
packages/patternfly-4/react-core/src/components/Button/examples/BlockButton.js
packages/patternfly-4/react-core/src/components/Button/examples/ButtonVariants.js
packages/patternfly-4/react-core/src/components/Button/examples/LinkButton.js

**What**: updating docs to match core
**References issue**: #967

docs(Button): update button docs to match core

---

packages/patternfly-4/react-core/src/components/Dropdown/DropdownItem.js
packages/patternfly-4/react-core/src/components/Dropdown/DropdownMenu.js
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.js.snap

**What**: Update to custom children to handle keyboard inputs and styling.
**Fixes issue**: #1196

feat(Dropdown): handle keyboard navigation and styling for Link children

---

.travis/after_success.sh
yarn.lock

**What**:
updates `yarn.lock` and adds a helpful lerna debugging statement
If the travis build generates or modifies any uncomitted files (including yarn.lock), it will cause lerna publish step to fail. This PR updates the lockfile and adds a git status so we can see exactly what files are touched in the log.
https://github.com/lerna/lerna/issues/1860#issue-397436384

fix(lockfile): updates out of date yarn.lock

---

packages/patternfly-4/react-core/src/components/Dropdown/DropdownItem.js

**What**: Adding onclick fix to the updated custom item mapping.
**Part of issue**: #1195

fix(Dropdown): add onclick fix to custom items

---

packages/patternfly-4/react-charts/README.md

fix(readme): update readme for react-charts

---

packages/patternfly-4/react-core/src/components/Nav/Nav.d.ts
packages/patternfly-4/react-integration/README.md
packages/patternfly-4/react-integration/demo-app-ts/src/App.tsx
packages/patternfly-4/react-integration/demo-app-ts/src/Nav.tsx

fix(ts): nav ts props

---

packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxHero.d.ts
packages/patternfly-4/react-styled-system/src/components/StyledSystem/StyledBox.d.ts
packages/patternfly-4/react-styled-system/src/components/StyledSystem/StyledFlex.d.ts
packages/patternfly-4/react-styled-system/src/components/StyledSystem/StyledText.d.ts
packages/patternfly-4/react-styled-system/src/components/StyledSystem/StyledTheme.d.ts
packages/patternfly-4/react-table/src/components/Table/Body.d.ts
packages/patternfly-4/react-table/src/components/Table/Header.d.ts
packages/patternfly-4/react-table/src/components/Table/SortColumn.d.ts
packages/patternfly-4/react-table/src/components/Table/Table.d.ts

Second (and final) piece of fixing issue #1149

chore(react-styled-system, react-table): Replace SFC syntax with FunctionComponent

---

packages/patternfly-4/react-core/src/components/Alert/Alert.d.ts
packages/patternfly-4/react-core/src/components/Alert/AlertActionCloseButton.js
packages/patternfly-4/react-core/src/components/Alert/AlertActionLink.js
packages/patternfly-4/react-core/src/components/Alert/index.d.ts
packages/patternfly-4/react-integration/demo-app-ts/src/App.tsx

fix(Alert): Fix index.d.ts file

---

packages/patternfly-4/react-core/src/components/Radio/Radio.js
packages/patternfly-4/react-core/src/components/Radio/__snapshots__/Radio.test.js.snap

**What**:
closes #1295 
//cc @mcoker

fix(Radio): Use pf-c-radio class in Radio

---

yarn.lock

fix(lock): fix out of date lock file

---

packages/patternfly-4/react-core/src/components/Alert/Alert.d.ts
packages/patternfly-4/react-core/src/components/Alert/Alert.js
packages/patternfly-4/react-core/src/components/Alert/Alert.test.js
packages/patternfly-4/react-core/src/components/Alert/__snapshots__/Alert.test.js.snap

Fixes [Issue #1290](https://github.com/patternfly/patternfly-react/issues/1290)

fix(Alert): Make Alert title required

---

packages/patternfly-4/react-integration/demo-app-ts/package.json
packages/patternfly-4/react-integration/demo-app-ts/tsconfig.json
packages/patternfly-4/react-integration/package.json
yarn.lock

chore(validatetypes): make sure types are validated on test build

---

packages/patternfly-4/react-core/src/components/Alert/__snapshots__/Alert.test.js.snap

fix(tests): update alert tests

---

packages/patternfly-4/react-charts/package.json
packages/patternfly-4/react-core/package.json
packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalBoxCloseButton.test.js.snap
packages/patternfly-4/react-core/src/components/Modal/__snapshots__/ModalBoxBody.test.js.snap
packages/patternfly-4/react-styled-system/package.json
packages/patternfly-4/react-table/package.json
packages/patternfly-4/react-tokens/package.json
packages/react-icons/package.json
yarn.lock

chore: Upgrade to PatternFly core 1.0.184

---

packages/patternfly-3/patternfly-react-extensions/package.json
packages/patternfly-3/patternfly-react/package.json
packages/patternfly-3/react-console/package.json
packages/patternfly-4/react-charts/package.json
packages/patternfly-4/react-core/package.json
packages/patternfly-4/react-styled-system/package.json
packages/patternfly-4/react-table/package.json
packages/patternfly-4/react-tokens/package.json
packages/react-icons/package.json

chore(versions): bump versions manually to match manual release

---

packages/patternfly-4/react-styles/package.json
packages/patternfly-4/react-styles/scripts/copyTS.js

Fix #875 Adds the Typescript def for patternfly-style

---

.travis.yml
yarn.lock

fix(lock): update yarn.lock file and shorten build temporarily

---

packages/patternfly-4/react-docs/package.json

fix(docs): bump react docs version

---

packages/patternfly-4/react-core/README.md

fix(readme): modify readme content for react-core release

---

.travis.yml
package.json

chore(ci): add ci check for publishing

---

packages/patternfly-4/react-core/src/components/Form/FormHelperText.d.ts
packages/patternfly-4/react-core/src/components/Form/FormHelperText.js
packages/patternfly-4/react-core/src/components/Form/FormHelperText.test.js
packages/patternfly-4/react-core/src/components/Form/__snapshots__/FormHelperText.test.js.snap
packages/patternfly-4/react-core/src/components/Form/index.d.ts
packages/patternfly-4/react-core/src/components/Form/index.js
packages/patternfly-4/react-core/src/components/LoginPage/LoginForm.d.ts
packages/patternfly-4/react-core/src/components/LoginPage/LoginForm.js
packages/patternfly-4/react-core/src/components/LoginPage/LoginMainFooter.d.ts
packages/patternfly-4/react-core/src/components/LoginPage/LoginMainFooter.js
packages/patternfly-4/react-core/src/components/LoginPage/LoginMainFooterBandItem.d.ts
packages/patternfly-4/react-core/src/components/LoginPage/LoginMainFooterBandItem.js
packages/patternfly-4/react-core/src/components/LoginPage/LoginMainFooterBandItem.test.js
packages/patternfly-4/react-core/src/components/LoginPage/LoginMainFooterLinksItem.d.ts
packages/patternfly-4/react-core/src/components/LoginPage/LoginMainFooterLinksItem.js
packages/patternfly-4/react-core/src/components/LoginPage/LoginMainFooterLinksItem.test.js
packages/patternfly-4/react-core/src/components/LoginPage/LoginPage.d.ts
packages/patternfly-4/react-core/src/components/LoginPage/LoginPage.js
packages/patternfly-4/react-core/src/components/LoginPage/__snapshots__/LoginForm.test.js.snap
packages/patternfly-4/react-core/src/components/LoginPage/__snapshots__/LoginMainFooterBandItem.test.js.snap
packages/patternfly-4/react-core/src/components/LoginPage/__snapshots__/LoginMainFooterLinksItem.test.js.snap
packages/patternfly-4/react-core/src/components/LoginPage/__snapshots__/LoginPage.test.js.snap
packages/patternfly-4/react-core/src/components/LoginPage/examples/SimpleLoginPage.js
packages/patternfly-4/react-core/src/components/LoginPage/index.d.ts
packages/patternfly-4/react-core/src/components/LoginPage/index.js

Fixes [issue #1239](https://github.com/patternfly/patternfly-react/issues/1239) and [issue #871](https://github.com/patternfly/patternfly-react/issues/871)

fix(Login): update component to match pf4 design changes

---

packages/patternfly-4/react-core/src/components/LoginPage/LoginMainHeader.d.ts
packages/patternfly-4/react-core/src/components/LoginPage/LoginMainHeader.js
packages/patternfly-4/react-core/src/components/LoginPage/LoginPage.d.ts
packages/patternfly-4/react-core/src/components/LoginPage/LoginPage.js
packages/patternfly-4/react-core/src/components/LoginPage/LoginPage.test.js
packages/patternfly-4/react-core/src/components/LoginPage/__snapshots__/LoginPage.test.js.snap
packages/patternfly-4/react-core/src/components/LoginPage/examples/SimpleLoginPage.js

#1243
**What**:
Screenshot of Login form without Language selector.

fix(LoginPage): Remove Language Selector from LoginPage

---

packages/patternfly-4/react-styles/README.md

fix(readme): fix typo in readme to force react-styles release

---

packages/patternfly-3/patternfly-react/src/components/LoginPage/LoginPage.stories.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/LoginPage.test.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/SocialLoginPage.test.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/__snapshots__/LoginPage.test.js.snap
packages/patternfly-3/patternfly-react/src/components/LoginPage/__snapshots__/SocialLoginPage.test.js.snap
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardWithValidation.js

fix(LoginPage): Submit is disabled when input is empty

---

packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncherMenu.js
packages/patternfly-4/react-core/src/components/ApplicationLauncher/Toggle.js
packages/patternfly-4/react-core/src/components/Dropdown/DropdownItem.js
packages/patternfly-4/react-core/src/components/Dropdown/DropdownMenu.js
packages/patternfly-4/react-core/src/helpers/constants.ts
packages/patternfly-4/react-core/src/helpers/util.test.js
packages/patternfly-4/react-core/src/helpers/util.ts

Modified keyHandler to work as a utility function for Dropdown and ApplicationLauncher and added some related constants.
Fixes #1374.

refactor(Dropdown and ApplicationLauncher): Refactor keyHandler usage

---

.circleci/config.yml
.circleci/release.sh
.travis.yml

**What**: Fix `lerna ERR! ENOGIT Detached git HEAD, please checkout a branch to choose versions` 
See [Travis.](https://travis-ci.org/patternfly/patternfly-react/jobs/493934158)
Also don't deploy on CircleCI if it's not a PR. Deploy to correct domain on Travis.

fix(build): fix lerna on master

---

packages/patternfly-4/react-core/src/components/LoginPage/LoginPage.d.ts
packages/patternfly-4/react-core/src/components/LoginPage/LoginPage.js

fix(login): Add union types for backgroundImgSrc

---

packages/patternfly-4/react-table/src/components/Table/Table.js
packages/patternfly-4/react-table/src/components/Table/__snapshots__/Table.test.js.snap
yarn.lock

**What**:
Because PF-core broke table and table grid into two seperate files we have to import grid styles for smaller screens.

fix(Table): Fix grid breakpoints for table

---

packages/patternfly-4/react-docs/src/components/navigation/navigationItem.styles.js
packages/patternfly-4/react-styled-system/src/components/StyledSystem/StyledTheme.js

**What**: Fix camelcase errors (318 of them). Ref #1409, towards #1256.

style(lint): fix camelcase errors

---

CONTRIBUTING.md
README.md
packages/patternfly-3/patternfly-react/CONTRIBUTING.md
packages/patternfly-4/react-core/CONTRIBUTING.md
packages/patternfly-4/react-docs/README.md

docs(update): remove semantic-release and update getting started

---

.circleci/config.yml
.travis.yml

**What**: Don't do CircleCI builds on master. Use default yarn version on Travis to avoid weird [GPG error](https://travis-ci.org/patternfly/patternfly-react/jobs/496126675).

build(flakes): fix some flaky build steps

---

packages/patternfly-4/react-core/src/components/DataList/DataListCheck.js
packages/patternfly-4/react-table/src/components/Table/SelectColumn.js
packages/patternfly-4/react-table/src/components/Table/__snapshots__/Table.test.js.snap

closes #1384 
//cc @mcoker @karelhala

refactor(datalist,table): use regular input checkbox

---

.circleci/release.sh

**What**: Last PR didn't work, after some debugging hopefully this one will.

build(lerna): fix lerna to release

---

.circleci/release.sh
packages/patternfly-4/react-core/package.json
packages/patternfly-4/react-docs/package.json
packages/patternfly-4/react-table/package.json

**What**: currently, lerna can't [`git push`](https://travis-ci.org/patternfly/patternfly-react/jobs/496703690).

build(lerna): fix build credentials

---

.codecov.yaml
.travis.yml
README.md
jest.config.js
package.json
yarn.lock

**What**: Coveralls is broken. Resolves #1175.
**Additional issues**: Let's see how long it takes and if it leaves PR comments.

build(coverage): add codecov

---

packages/patternfly-4/react-core/src/components/Form/ActionGroup.js
packages/patternfly-4/react-core/src/components/Form/__snapshots__/ActionGroup.test.js.snap
packages/patternfly-4/react-core/src/components/Form/examples/HorizontalForm.js
packages/patternfly-4/react-core/src/components/Form/examples/SimpleForm.js

**What**:
closes #1289 
//cc @mcoker

refactor(form): use form actions instead of toolbar

---

.circleci/config.yml
.gitignore
.travis.yml
README.md

**What**: Fix Travis caching for consistent pr-docs builds. Closes #1435 .

build(charts): fix charts deploy

---

packages/patternfly-4/react-charts/src/components/index.d.ts
packages/patternfly-4/react-charts/src/components/index.js

Simple fix to export ChartPoint.

Export ChartPoint

---

packages/patternfly-4/react-core/src/components/Select/Select.d.ts
packages/patternfly-4/react-core/src/components/Select/SelectOption.d.ts

**What**:
fix #1443 
explanation:
1.
```
A 'const' initializer in an ambient context must be a string or numeric literal or literal enum reference.
```
We should define string literal expressions currently with a `:` instead of the `=` in an ambient context. 
A 'const' initializer in an ambient context must be a string or numeric literal or literal enum reference.
[Link](https://github.com/Microsoft/TypeScript/issues/9729#issuecomment-234640402)
2.
```
Types of property 'onClick' are incompatible.
Type 'Function' is not assignable to type '(event: MouseEvent<HTMLOptionElement>) => void'.
Type 'Function' provides no match for the signature '(event: MouseEvent<HTMLOptionElement>): void'
```
from:
```
export interface SelectOptionProps extends Omit<HTMLProps<HTMLOptionElement>, 'disabled'> …
```

fix(Select): fix typescript def for SelectProps and SelectOptionProps

---

packages/patternfly-4/react-core/src/tsconfig.dts.json
packages/patternfly-4/react-docs/.gitignore
packages/patternfly-4/react-docs/build/transformTsDocs.js
packages/patternfly-4/react-docs/gatsby-config.js
packages/patternfly-4/react-docs/package.json
packages/patternfly-4/react-docs/src/components/componentDocs/componentDocs.js
packages/patternfly-4/react-docs/src/components/propsTableTs/index.js
packages/patternfly-4/react-docs/src/components/propsTableTs/propsTableTs.js
packages/patternfly-4/react-docs/src/components/propsTableTs/propsTableTs.styles.js
packages/patternfly-4/react-integration/demo-app-ts/src/App.tsx
yarn.lock

Using typedoc to parse ts files which spits out a json file. Read the json file in gatsby and use graphql to find the component. This will likely need to be adjusted when more TS components are added but should give us a good base to build upon.
Closes: #1033

Generate props for typescript components

---

packages/patternfly-4/react-core/src/components/ApplicationLauncher/examples/TooltipApplicationLauncher.js
packages/patternfly-4/react-core/src/components/Tooltip/Tooltip.js

Fixes #1418
**Before**
**After**

Application Launcher - Moved Tooltips to menu items

---

.travis.yml
packages/patternfly-4/react-docs/package.json

chore(build): fix gatsby

---

packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggle.js

**What**:
#1169 
Add css conditional for icon only drop down case

fix(iconOnly): Add conditional for icon only styles

---

packages/patternfly-4/react-core/src/components/DataList/DataListItem.js

fix(datalistitem): add validity check before cloning children

---

.circleci/config.yml

**What**: This will fix our currently failing CircleCI PR previews without each PR having to rebase.

chore(circle): clear cache through environment variable

---

.circleci/release.sh
.travis.yml

**What**: Don't double-build bot-created branches, don't fail releases if the Github release doesn't work.

chore(build): suppress travis bugs

---

.circleci/config.yml

**What**: Some builds might still timeout. Let's be extra safe

chore(circle): give circleci more time to build docs [ci skip]

---

.gitignore
package.json
packages/patternfly-3/patternfly-react-extensions/package.json
packages/patternfly-3/patternfly-react/package.json
packages/patternfly-3/react-console/package.json
packages/patternfly-4/react-charts/package.json
packages/patternfly-4/react-core/package.json
packages/patternfly-4/react-docs/.gitignore
packages/patternfly-4/react-docs/package.json
packages/patternfly-4/react-integration/.gitignore
packages/patternfly-4/react-integration/package.json
packages/patternfly-4/react-styled-system/package.json
packages/patternfly-4/react-styles/package.json
packages/patternfly-4/react-table/package.json
packages/patternfly-4/react-tokens/package.json
packages/react-icons/.gitignore
packages/react-icons/package.json
yarn.lock

**What**: Add `yarn clean` per-project.

build(clean): add `yarn clean` and modularize .gitignores

---

packages/patternfly-4/react-core/src/components/Tabs/TabContent.d.ts
packages/patternfly-4/react-core/src/components/Tabs/TabContent.js
packages/patternfly-4/react-core/src/components/Tabs/Tabs.js
packages/patternfly-4/react-core/src/components/Tabs/__snapshots__/Tabs.test.js.snap

fix(tabs): Move TabContent to its own component

---

packages/patternfly-4/react-core/src/components/Modal/Modal.d.ts
packages/patternfly-4/react-core/src/components/Modal/Modal.docs.js
packages/patternfly-4/react-core/src/components/Modal/Modal.js
packages/patternfly-4/react-core/src/components/Modal/ModalBox.d.ts
packages/patternfly-4/react-core/src/components/Modal/ModalBox.js
packages/patternfly-4/react-core/src/components/Modal/ModalBox.test.js
packages/patternfly-4/react-core/src/components/Modal/ModalBoxBody.js
packages/patternfly-4/react-core/src/components/Modal/ModalBoxHeader.d.ts
packages/patternfly-4/react-core/src/components/Modal/ModalBoxHeader.js
packages/patternfly-4/react-core/src/components/Modal/ModalContent.d.ts
packages/patternfly-4/react-core/src/components/Modal/ModalContent.js
packages/patternfly-4/react-core/src/components/Modal/__snapshots__/ModalBox.test.js.snap
packages/patternfly-4/react-core/src/components/Modal/__snapshots__/ModalContent.test.js.snap
packages/patternfly-4/react-core/src/components/Modal/examples/NoHeader.js

Fixes [issue #1383](https://github.com/patternfly/patternfly-react/issues/1383)
Most of the changes are not easy to document in a screen shot, but here are the UI changes:

fix(Modal): accessibility enhancements and other small fixes

---

packages/patternfly-4/react-table/src/components/Table/utils/transformers.test.js

**What**: All it had to do was be uncommented. Resolves #1533

fix(typeUtils): fix transformers test

---

.travis.yml
package.json

**What**: See title. Should fail PRs like #1255 that break `packages/react-*` tests.

build(tests): add misc test build target to travis

---

packages/patternfly-4/react-core/package.json
packages/patternfly-4/react-core/src/components/Modal/Modal.test.js
packages/patternfly-4/react-core/src/components/Modal/ModalBoxHeader.js
packages/patternfly-4/react-core/src/components/Modal/__snapshots__/ModalContent.test.js.snap
packages/patternfly-4/react-docs/package.json
yarn.lock

fix modal test

---

packages/patternfly-4/react-table/src/components/Table/ActionsColumn.js
packages/patternfly-4/react-table/src/components/Table/Body.js
packages/patternfly-4/react-table/src/components/Table/Table.d.ts
packages/patternfly-4/react-table/src/components/Table/__snapshots__/Table.test.js.snap
packages/patternfly-4/react-table/src/components/Table/index.d.ts
packages/patternfly-4/react-table/src/components/Table/utils/decorators/cellActions.js
packages/patternfly-4/react-table/src/components/Table/utils/decorators/collapsible.js
packages/patternfly-4/react-table/src/components/Table/utils/decorators/selectable.js
packages/patternfly-4/react-table/src/components/Table/utils/decorators/sortable.js

solves https://github.com/patternfly/patternfly-react/issues/1472 issue and passes useful data back to consumer. 
@priley86 @karelhala

feat(Table): pass rowData and extraData to table callbacks

---

packages/patternfly-4/react-core/src/components/ChipGroup/Chip.d.ts
packages/patternfly-4/react-core/src/components/ChipGroup/Chip.js
packages/patternfly-4/react-core/src/components/ChipGroup/__snapshots__/ChipGroup.test.js.snap
packages/patternfly-4/react-core/src/components/Nav/NavItem.d.ts
packages/patternfly-4/react-integration/demo-app-ts/src/Nav.tsx

fix(Chip, NavItem): Fixed Typescript definition file errors

---

packages/patternfly-4/react-core/src/components/Nav/NavItem.d.ts

**What**:
This fixes #1547 completely.

fix(Nav): add onClick to the definition file

---

packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.d.ts

fix(Dropdown): fix d.ts file to make props optional

---

packages/patternfly-4/react-core/package.json
packages/patternfly-4/react-styles/package.json
packages/patternfly-4/react-tokens/package.json
packages/react-icons/package.json

**What**: Add umd builds. Closes #1452

feat(umd): add umd for styles, tokens, and icons

---

.circleci/config.yml
.travis.yml
package.json
packages/patternfly-4/react-core/README.md
packages/patternfly-4/react-core/src/components/Avatar/Avatar.tsx
packages/patternfly-4/react-docs/README.md
packages/patternfly-4/react-docs/package.json
packages/patternfly-4/react-docs/src/components/componentDocs/componentDocs.js
yarn.lock

**What**: Fix http://patternfly-react.surge.sh/patternfly-4/index.html

chore(build): fix yarn build:docs and main site

---

packages/patternfly-4/react-core/src/components/DataList/DataList.js
packages/patternfly-4/react-core/src/components/DataList/__snapshots__/DataList.test.js.snap

**What**:
closes #1471
Remove the shadow-box class from `DataList`.
//cc @mcoker

fix(DataList): remove shadow-box

---

packages/patternfly-4/react-core/src/components/Form/examples/HorizontalForm.js

**What**:
closes #1577 
//cc @mcoker @mcarrano

docs(Form): update horizontal form example to pf core

---

packages/patternfly-3/patternfly-react/src/components/VerticalNav/VerticalNavItemHelper.js

**What**:
Quick fix to the last PR
pass null instead of empty strings to prevent empty attributes

fix(VerticalNav): fix attributes for secondary items

---

packages/patternfly-4/react-core/src/components/DataList/DataListCell.d.ts
packages/patternfly-4/react-core/src/components/DataList/DataListItem.d.ts
packages/patternfly-4/react-core/src/components/DataList/DataListToggle.d.ts

**What**:
fix #1607 
fix #1608 
//cc @ibolton336

fix(DataList): set width and isExpanded to optional in d.ts

---

packages/patternfly-4/react-core/src/components/Button/Button.js

Fixes typo hove->hover

---

packages/patternfly-4/react-core/src/helpers/util.test.js
packages/patternfly-4/react-core/src/helpers/util.ts

Fixes https://github.com/patternfly/patternfly-react/issues/1451
**What**: 
- Use `getBoundingClientRect` and `Math.floor` in `isElementInView` and `sideElementIsOutOfView` util functions to improve consistency of element left and right bound values across browsers. 
- Update `util.test.js` to mock `getBoundingClientRect` function.

fix(util.ts): Improve cross-browser compatibility of `isElementInView` and `sideElementIsOutOfView`

---

packages/patternfly-4/react-inline-edit-extension/src/components/InlineEdit/examples/EditableTable.js

Dropdown toggle button focused state was lost on rerender. Sadly the issue with gatsby to select an actual item still persist.
@jschuler @priley86 @karelhala

fix(InlineEdit): remove flickering of dropdown in an example

---

packages/patternfly-4/react-charts/src/components/LineChart/examples/SimpleChart.js
packages/patternfly-4/react-core/src/components/Nav/examples/NavSimpleList.js
packages/patternfly-4/react-docs/src/components/css-variables.js

Just some quick fixes to bring down our bug count.
Fixed #1484: LineChart example missing import
Fixed #1589: CSS Variables Table: Each child in a list should have a unique "key" prop
Fixed #1427: Navs missing id

fix(misc): small bug fixes

---

.travis.yml

chore(build): disable release for quiet period

---

packages/patternfly-4/react-docs/package.json
yarn.lock

**What**: Downgrading Gatsby fixes our [broken build](https://travis-ci.org/patternfly/patternfly-react/jobs/515841674) on Travis (it's fine on Circle and locally).

fix(build): downgrade gatsby

---

.travis.yml

**What**: Everyone can build it but you, Travis.

build(travis): please build our new doc site Travis

---

packages/patternfly-3/patternfly-react-extensions/less/patternfly-react-extensions.less
packages/patternfly-3/patternfly-react-extensions/less/select.less
packages/patternfly-3/patternfly-react-extensions/package.json
packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_patternfly-react-extensions.scss
packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_select.scss
packages/patternfly-3/patternfly-react-extensions/src/components/Select/Select.fixtures.js
packages/patternfly-3/patternfly-react-extensions/src/components/Select/Select.js
packages/patternfly-3/patternfly-react-extensions/src/components/Select/Select.stories.js
packages/patternfly-3/patternfly-react-extensions/src/components/Select/Select.test.js
packages/patternfly-3/patternfly-react-extensions/src/components/Select/SelectHelper.js
packages/patternfly-3/patternfly-react-extensions/src/components/Select/SelectInput.js
packages/patternfly-3/patternfly-react-extensions/src/components/Select/StatefulWrapperSelect.js
packages/patternfly-3/patternfly-react-extensions/src/components/Select/__snapshots__/Select.test.js.snap
packages/patternfly-3/patternfly-react-extensions/src/components/Select/index.js
packages/patternfly-3/patternfly-react-extensions/src/index.js

**What**:
WIP for a Select Component with a Search Input.
I took the design from [here](https://www.patternfly.org/pattern-library/widgets/#bootstrap-select) even though there is no search bar.
Right now the Component accept for options an object e.g. 
```
{
'1': 'one',
'2': 'two',
...
}
```
**TODO**:
- tests
- css variables
- more features?

[PF3] Select Component

---

packages/patternfly-4/react-core/src/components/ChipGroup/Chip.d.ts

fix(ChipGroup): remove unused prop badgeText from d.ts file

---

packages/patternfly-4/react-table/src/components/Table/Table.d.ts
packages/patternfly-4/react-table/src/components/Table/Table.js
packages/patternfly-4/react-table/src/components/Table/Table.md
packages/patternfly-4/react-table/src/components/Table/__snapshots__/Table.test.js.snap

Fixed border prop to show border on true and not show border on false.  #1674

Updated to border prop for compact table.

---

packages/patternfly-4/react-table/src/components/Table/Table.d.ts

fix #1463
**What**: column configs now optionally defined for transforms, cellTransforms, formatters, and cellFormatters

fix(table): Add optional types for table column

---

packages/patternfly-4/react-styles/src/build/babel/plugin.js
packages/patternfly-4/react-styles/src/build/util.js

fix(css): remove minification from full css files

---

packages/patternfly-4/react-core/src/components/EmptyState/EmptyState.d.ts
packages/patternfly-4/react-core/src/components/Select/CheckboxSelectGroup.d.ts
packages/patternfly-4/react-core/src/components/Select/CheckboxSelectOption.d.ts
packages/patternfly-4/react-core/src/components/Select/Select.d.ts
packages/patternfly-4/react-core/src/components/Tabs/Tab.d.ts
packages/patternfly-4/react-core/src/components/Tabs/Tabs.d.ts

**What**:
typescript definition updates, fixes #1772 

Ts def fixes

---

packages/patternfly-4/react-core/src/components/Tabs/Tabs.js
packages/patternfly-4/react-core/src/components/Tabs/__snapshots__/Tabs.test.js.snap

#1775, #1779, #1774, #1777 
**What**:

fix(Tabs): Move TabContent outside of Tabs div

---

packages/patternfly-4/react-core/README.md

fix(readme): version bump for last commit

---

.vscode/settings.json
packages/patternfly-4/react-core/README.md

fix(version): force bump

---

packages/patternfly-4/react-core/src/components/Modal/ModalContent.js
packages/patternfly-4/react-core/src/components/Modal/__snapshots__/ModalContent.test.js.snap

fix(Modal): Remove extra Bullseye from Modal

---

packages/patternfly-4/react-integration/demo-app-ts/src/App.tsx
packages/patternfly-4/react-integration/demo-app-ts/src/Wizard.tsx

**What**:
closes #1750 
Make the demo application work again.

fix(demo-app-ts): update typescript demo application

---

packages/patternfly-4/react-core/src/components/LoginPage/LoginMainHeader.js
packages/patternfly-4/react-core/src/components/LoginPage/LoginMainHeader.test.js
packages/patternfly-4/react-core/src/components/LoginPage/LoginPage.d.ts
packages/patternfly-4/react-core/src/components/LoginPage/LoginPage.js
packages/patternfly-4/react-core/src/components/LoginPage/LoginPage.md
packages/patternfly-4/react-core/src/components/LoginPage/__snapshots__/LoginMainHeader.test.js.snap
packages/patternfly-4/react-core/src/components/LoginPage/examples/SimpleLoginPage.js
packages/patternfly-4/react-core/src/components/LoginPage/examples/SimpleLoginPage.md

fix(login): added login subtitle

---

packages/patternfly-4/react-core/src/components/Card/Card.d.ts
packages/patternfly-4/react-core/src/components/Card/Card.js
packages/patternfly-4/react-core/src/components/Card/Card.md
packages/patternfly-4/react-core/src/components/Card/Card.test.js
packages/patternfly-4/react-core/src/components/Card/__snapshots__/Card.test.js.snap

feat(card): adds card is-hoverable modifier prop

---

packages/patternfly-4/react-core/src/components/ClipboardCopy/ClipboardCopy.md

fix(clipboardcopy): fix docs

---

packages/patternfly-4/react-core/src/components/AboutModal/AboutModal.d.ts
packages/patternfly-4/react-core/src/components/AboutModal/AboutModal.js
packages/patternfly-4/react-core/src/components/AboutModal/AboutModal.md
packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxHeader.js
packages/patternfly-4/react-core/src/components/AboutModal/AboutModalContainer.js

feat(aboutmodal): make productName optional

---

packages/patternfly-4/react-core/src/components/Page/Page.md
packages/patternfly-4/react-core/src/components/Page/PageSection.d.ts
packages/patternfly-4/react-core/src/components/Page/PageSection.js
packages/patternfly-4/react-core/src/components/Page/PageSection.test.js
packages/patternfly-4/react-core/src/components/Page/__snapshots__/Page.test.js.snap
packages/patternfly-4/react-core/src/components/Page/__snapshots__/PageSection.test.js.snap

feat(padding): add pagesection no padding props

---

packages/patternfly-3/patternfly-react-extensions/src/components/Select/Select.js
packages/patternfly-3/patternfly-react-extensions/src/components/Select/SelectInput.js

**What**:
Fix for the Select component imports

fix(Select): PF3 - fix Select imports

---

packages/patternfly-4/react-core/src/layouts/Grid/Grid.d.ts

**What**:
fixes #1718 
Added the span, sm, md, lg and xl props in the d.ts file

fix(grid): add missing props in d.ts

---

packages/patternfly-4/react-core/src/components/Select/SelectOption.js
packages/patternfly-4/react-core/src/components/Select/SelectOption.test.js
packages/patternfly-4/react-core/src/components/Select/__snapshots__/SelectOption.test.js.snap

refactor(Select): add selected state to single select

---

packages/patternfly-3/patternfly-react-extensions/README.md

**What**: Travis [didn't release the correct build](https://travis-ci.org/patternfly/patternfly-react/jobs/523533541) due to it using the cache from the previous job.

fix(build): bump patternfly-react-extensions

---

packages/patternfly-4/react-core/src/components/Wizard/Wizard.md
packages/patternfly-4/react-core/src/components/Wizard/Wizard.tsx
packages/patternfly-4/react-core/src/components/Wizard/WizardBody.tsx
packages/patternfly-4/react-core/src/components/Wizard/WizardHeader.tsx
packages/patternfly-4/react-core/src/components/Wizard/WizardNav.tsx
packages/patternfly-4/react-core/src/components/Wizard/WizardNavItem.tsx
packages/patternfly-4/react-core/src/components/Wizard/WizardToggle.tsx
packages/patternfly-4/react-core/src/components/Wizard/__snapshots__/Wizard.test.tsx.snap
packages/patternfly-4/react-core/src/components/Wizard/index.ts
packages/patternfly-4/react-core/src/components/index.ts

**What**:
Add two new props to Wizard:
- `isFullWidth` - set wizard to full width
- `isFullHeight` - set wizard to full height
closes #1761 
//cc @mcoker

feat(Wizard): support for full width and full height

---

packages/patternfly-4/react-core/src/components/BackgroundImage/BackgroundImage.js
packages/patternfly-4/react-core/src/components/BackgroundImage/BackgroundImage.md
packages/patternfly-4/react-core/src/components/BackgroundImage/__snapshots__/BackgroundImage.test.js.snap
packages/patternfly-4/react-core/src/components/BackgroundImage/examples/SimpleBackgroundImage.js
packages/patternfly-4/react-core/src/components/BackgroundImage/examples/SimpleBackgroundImage.md
packages/patternfly-4/react-docs/gatsby-node.js

feat(BackgroundImage): update background image component

---

packages/patternfly-4/react-core/src/components/ClipboardCopy/ClipboardCopy.js
packages/patternfly-4/react-core/src/components/ClipboardCopy/ExpandedContent.js
packages/patternfly-4/react-core/src/components/ClipboardCopy/ExpandedContent.test.js
packages/patternfly-4/react-core/src/components/ClipboardCopy/__snapshots__/ExpandedContent.test.js.snap

fix(clipboard): change expanded content in clipboard copy to ref

---

packages/patternfly-4/react-docs/plugins/gatsby-transformer-react-docgen-typescript/gatsby-node.js
packages/patternfly-4/react-docs/plugins/gatsby-transformer-react-docgen-typescript/package.json
yarn.lock

fix(docs): don't show inherited typescript props

---

packages/patternfly-4/react-core/src/components/Dropdown/Toggle.js
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/DropdownToggle.test.js.snap
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Toggle.test.js.snap
packages/patternfly-4/react-table/src/components/Table/__snapshots__/Table.test.js.snap

fix(dropdown): rename toggle export

---

packages/patternfly-4/react-charts/package.json
packages/patternfly-4/react-core/package.json
packages/patternfly-4/react-docs/package.json
packages/patternfly-4/react-inline-edit-extension/package.json
packages/patternfly-4/react-styled-system/package.json
packages/patternfly-4/react-table/package.json
packages/patternfly-4/react-tokens/package.json
packages/react-icons/package.json
yarn.lock

fix(version): bump patternfly version to 2.6.5

---

.circleci/release.sh

build(travis): fix async deploy problems

---

packages/patternfly-4/react-core/src/components/Wizard/Wizard.md
packages/patternfly-4/react-core/src/components/Wizard/Wizard.tsx

**What**:
Adding an example of how to remember the step on closing the wizard.
This fixes #1845 
//cc @ibolton336

docs(wizard): remember the last step on close

---

packages/patternfly-4/react-core/src/layouts/Bullseye/examples/Bullseye.md
packages/patternfly-4/react-core/src/layouts/Bullseye/examples/bullseye.scss
packages/patternfly-4/react-core/src/layouts/Gallery/examples/Gallery.md
packages/patternfly-4/react-core/src/layouts/Gallery/examples/gallery.scss
packages/patternfly-4/react-core/src/layouts/Grid/examples/Grid.md
packages/patternfly-4/react-core/src/layouts/Grid/examples/grid.scss
packages/patternfly-4/react-core/src/layouts/Level/examples/Level.md
packages/patternfly-4/react-core/src/layouts/Level/examples/level.scss
packages/patternfly-4/react-core/src/layouts/Split/examples/Split.md
packages/patternfly-4/react-core/src/layouts/Split/examples/split.scss
packages/patternfly-4/react-core/src/layouts/Stack/examples/Stack.md
packages/patternfly-4/react-core/src/layouts/Stack/examples/stack.scss
packages/patternfly-4/react-core/src/layouts/Toolbar/examples/Toolbar.md
packages/patternfly-4/react-core/src/layouts/Toolbar/examples/toolbar.scss

Fixes: https://github.com/patternfly/patternfly-org/issues/879

fix(styles): update layout styles for layouts

---

packages/patternfly-3/patternfly-react/less/dual-list-selector.less
packages/patternfly-3/patternfly-react/sass/patternfly-react/_dual-list-selector.scss
packages/patternfly-3/patternfly-react/src/components/DualListSelector/components/DualListDropDown.js
packages/patternfly-3/patternfly-react/src/components/DualListSelector/components/DualListHeading.js

- Moved drop down kebab into its own file
- hide when no menu items are provided
- fix css regression 
- fix default prop ID

fix(DualList): Hide dropdown when no menu items are provided

---

packages/patternfly-4/react-core/src/components/Dropdown/DropdownItem.d.ts
packages/patternfly-4/react-core/src/components/SkipToContent/SkipToContent.tsx

**What**:
Fixes for Dropdown item and update to skip to content for issue #1921 

fix (dropitems): Updates to drop down item and skip to content api

---

packages/patternfly-3/patternfly-react-extensions/package.json
packages/patternfly-3/patternfly-react-wooden-tree/package.json
packages/patternfly-3/patternfly-react/package.json
packages/patternfly-3/react-console/package.json
packages/patternfly-4/react-charts/package.json
packages/patternfly-4/react-core/package.json
packages/patternfly-4/react-inline-edit-extension/package.json
packages/patternfly-4/react-styled-system/package.json
packages/patternfly-4/react-styles/package.json
packages/patternfly-4/react-table/package.json
packages/patternfly-4/react-tokens/package.json
packages/react-icons/package.json

chore(build): quiet build log

---

packages/patternfly-3/patternfly-react/src/components/DualListSelector/DualList.js
packages/patternfly-3/patternfly-react/src/components/DualListSelector/components/DualListItem.js
packages/patternfly-3/patternfly-react/src/components/DualListSelector/helpers.js

Items that were default set to hidden, shouldn't be modified by the component.

fix(DualList): Distinguish between default hidden to filter hidden

---

packages/patternfly-3/patternfly-react/src/components/Pagination/PaginationRow.js
packages/patternfly-3/patternfly-react/src/components/Pagination/PaginationRowBack.js
packages/patternfly-3/patternfly-react/src/components/Pagination/PaginationRowForward.js
packages/patternfly-3/patternfly-react/src/components/Pagination/Paginator.js

**What**:
Add disableNext,disablePrev Props to the Paginator component.

feat(Paginator): Add disableNext,disablePrev Props

---

packages/patternfly-4/react-core/src/demos/PageLayout/PageLayout.md

fix(demo): fix page demo

---

packages/patternfly-4/react-core/package.json
packages/patternfly-4/react-table/package.json

feat(table): add umd to react-table

---

packages/patternfly-3/react-console/package.json
packages/patternfly-3/react-console/src/SpiceConsole/SpiceActions.js
packages/patternfly-3/react-console/src/SpiceConsole/SpiceActions.test.js
packages/patternfly-3/react-console/src/SpiceConsole/SpiceConsole.js
packages/patternfly-3/react-console/src/SpiceConsole/SpiceConsole.stories.js
packages/patternfly-3/react-console/src/SpiceConsole/__snapshots__/SpiceActions.test.js.snap
packages/patternfly-3/react-console/src/SpiceConsole/index.js
packages/patternfly-3/react-console/src/index.js
yarn.lock

**What**:
Adds Spice-JS support for react-console package.

add support for spice connectivity using JS based client

---

packages/patternfly-3/patternfly-react/less/login-page.less
packages/patternfly-3/patternfly-react/sass/patternfly-react/_login-page.scss
packages/patternfly-3/patternfly-react/src/components/LoginPage/LoginPage.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/SocialLoginPage.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginPageComponents/LoginPageAlerts.js

Accept also an array of alerts to display on the top of the page:

feat(LoginPage): support multiple alerts

---

packages/patternfly-3/patternfly-react/src/components/DualListSelector/helpers.js

The component shouldn't count, toggle or filter hidden items.

fix(DualList): The component shouldn't count, toggle or filter hidden items.

---

packages/patternfly-3/patternfly-react/src/components/DualListSelector/DualListControlled.js

Add callbacks of the updated state for each method in the controlled Dual List

fix(DualList): add callbacks to Controlled Dual List methods

---

packages/patternfly-3/patternfly-react-wooden-tree/package.json
packages/patternfly-3/patternfly-react-wooden-tree/src/components/TreeView/TreeView.stories.js
packages/patternfly-3/patternfly-react-wooden-tree/src/components/TreeView/TreeViewExample.js
packages/patternfly-3/patternfly-react/src/components/DualListSelector/DualListControlled.js
packages/patternfly-3/patternfly-react/src/components/DualListSelector/helpers.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardWithValidation.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginPageComponents/LoginPageAlerts.js
packages/patternfly-3/patternfly-react/src/components/MessageDialog/MessageDialog.test.js
packages/patternfly-3/patternfly-react/src/components/Modal/__mocks__/mockModalManager.js
packages/patternfly-3/patternfly-react/src/components/VerticalNav/VerticalNav.js
packages/patternfly-3/react-console/src/AccessConsoles/AccessConsoles.js
packages/patternfly-3/react-console/src/SpiceConsole/SpiceConsole.js

**What**: Fix lint errors found in patternfly-3 packages

chore(patternfly-3 lint): Fix existing patternfly-3 lint errors

---

.travis.yml
packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.tsx
packages/patternfly-4/react-core/src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap

**What**: Fix broken build on master

fix(build): update snapshots and fix linter errors

---

packages/patternfly-4/react-core/src/components/Wizard/Wizard.tsx

fix(wizard): wizards props extends div element props

---

packages/patternfly-4/react-core/src/components/Nav/Nav.md
packages/patternfly-4/react-core/src/components/Nav/Nav.tsx
packages/patternfly-4/react-core/src/components/Nav/NavList.tsx
packages/patternfly-4/react-core/src/components/Nav/__snapshots__/Nav.test.tsx.snap
packages/patternfly-4/react-core/src/components/Page/PageHeader.js

Makes the PF4 nav scrollable
Closes: #1709

PF4 Nav: make horizontal nav scrollable

---

packages/patternfly-4/react-charts/.babelrc
packages/patternfly-4/react-charts/.babelrc.js
packages/patternfly-4/react-charts/package.json
packages/patternfly-4/react-charts/tsconfig.typecheck.json

**What**: Make react-chart's babel and typescript config like react-core's. Fixes #2074

feat(charts): add typescript support to react-charts

---

packages/patternfly-4/react-charts/CHANGELOG.md

**What**: #2137 didn't work, but I hope this one does!

perf(charts): breaking change bump

---

packages/patternfly-4/react-styles/package.json
yarn.lock

**What**: Ref https://github.com/webpack/webpack/issues/8656#issuecomment-456010969

chore(react-styles): bump jsdom

---

packages/patternfly-3/patternfly-react-wooden-tree/CHANGELOG.md

**What**: Lerna is being silly, so hopefully this will force it to behave

perf(wooden-tree): major bump wooden-tree

---

.github/stale.yml

**What**: [This bot](https://github.com/probot/stale) should help us close nearly half of our current issues.

fix(issues): fix stalebot config to include issues

---

.github/stale.yml
packages/patternfly-4/react-core/package.json

chore(bot): update stale bot configuration and package sideeffects

---

.travis.yml

**What**: Fix build on master by caching react-virtualized-extension. Also cache react-topology which is coming soon.

chore(build): fix travis cache config

---

packages/patternfly-4/react-docs/src/components/componentDocs/liveEdit.js

**What**:
missed during rebase of #2011 - 🤞 this fixes react-docs

fix(react-docs): react-virtualized live edit

---

packages/patternfly-4/react-table/src/components/Table/Table.d.ts
packages/patternfly-4/react-table/src/components/Table/Table.js

Added breakpoint to list of available breakpoints and updated snapshot.
Fixes https://github.com/patternfly/patternfly-react/issues/2198.

feat(Table): Add support for .pf-m-grid-2xl breakpoint

---

packages/patternfly-4/react-styles/package.json

fix(styles): add sideeffects to react-styles

---

packages/patternfly-4/react-topology/src/components/TopologyView/TopologyView.tsx
packages/patternfly-4/react-topology/src/components/TopologyView/__snapshots__/TopologyView.test.tsx.snap
packages/patternfly-4/react-topology/src/components/TopologyView/examples/ProjectToolbar.js
packages/patternfly-4/react-topology/src/components/TopologyView/examples/ViewToolbar.js

**What**:
Remove hard coded margins on topology view subcomponents (toolbars).

fix(topology-view): Do not hard code margins on view components

---

packages/patternfly-4/react-topology/README.md

**What**:
No changes, just forcing a new version to include changes from previous updates.

fix(release): Version bump to distribute previous changes

---

packages/patternfly-4/react-integration/README.md

**What**: Fixes a broken link in the readme.

chore(readme): fix broken link

---

packages/patternfly-4/react-table/package.json
yarn.lock

fix(table): add lodash-es as a dependency

---

scripts/generators/package/package.json.hbs

fix(plop): fix handlebars file for new package to use new babel configs

---

packages/patternfly-4/react-topology/package.json

**What**:
Fix to generate correct JS exports in the react-topology package

fix(topology): Fixes JS dist for react-topology

---

packages/patternfly-4/react-core/src/components/Alert/Alert.md
packages/patternfly-4/react-core/src/components/Alert/Alert.test.tsx
packages/patternfly-4/react-core/src/components/Alert/Alert.tsx
packages/patternfly-4/react-core/src/components/Alert/__snapshots__/Alert.test.tsx.snap
yarn.lock

feat(Alert): Add the inline alert modifier

---

packages/patternfly-4/.babelrc
packages/patternfly-4/react-charts/package.json
packages/patternfly-4/react-core/.npmignore
packages/patternfly-4/react-core/package.json
packages/patternfly-4/react-inline-edit-extension/.npmignore
packages/patternfly-4/react-inline-edit-extension/package.json
packages/patternfly-4/react-styled-system/.npmignore
packages/patternfly-4/react-styled-system/package.json
packages/patternfly-4/react-styles/.npmignore
packages/patternfly-4/react-styles/package.json
packages/patternfly-4/react-table/.npmignore
packages/patternfly-4/react-table/package.json
packages/patternfly-4/react-tokens/.npmignore
packages/patternfly-4/react-topology/.npmignore
packages/patternfly-4/react-topology/package.json
packages/patternfly-4/react-virtualized-extension/.npmignore
packages/patternfly-4/react-virtualized-extension/package.json
packages/react-icons/.npmignore
packages/react-icons/package.json

**What**: Add source maps for PatternFly 4 packages, BUT exclude them from the published `dist` folders.

feat(build): add source maps

---

packages/patternfly-4/react-topology/tslint.json

**What**: React-topology currently isn't linting.

chore(topology): add tslint.json

---

packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalBoxCloseButton.test.tsx.snap
packages/patternfly-4/react-core/src/components/Alert/__snapshots__/Alert.test.tsx.snap
packages/patternfly-4/react-core/src/components/ApplicationLauncher/__snapshots__/ApplicationLauncher.test.js.snap
packages/patternfly-4/react-core/src/components/Breadcrumb/__snapshots__/BreadcrumbItem.test.tsx.snap
packages/patternfly-4/react-core/src/components/ClipboardCopy/__snapshots__/CopyButton.test.js.snap
packages/patternfly-4/react-core/src/components/ClipboardCopy/__snapshots__/ToggleButton.test.js.snap
packages/patternfly-4/react-core/src/components/ContextSelector/__snapshots__/ContextSelector.test.js.snap
packages/patternfly-4/react-core/src/components/ContextSelector/__snapshots__/ContextSelectorToggle.test.js.snap
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/DropdownToggle.test.js.snap
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Toggle.test.js.snap
packages/patternfly-4/react-core/src/components/Expandable/__snapshots__/Expandable.test.tsx.snap
packages/patternfly-4/react-core/src/components/Modal/__snapshots__/ModalBoxCloseButton.test.tsx.snap
packages/patternfly-4/react-core/src/components/Nav/__snapshots__/Nav.test.tsx.snap
packages/patternfly-4/react-core/src/components/OptionsMenu/__snapshots__/OptionsMenu.test.js.snap
packages/patternfly-4/react-core/src/components/Page/__snapshots__/Page.test.js.snap
packages/patternfly-4/react-core/src/components/Pagination/__snapshots__/Pagination.test.js.snap
packages/patternfly-4/react-core/src/components/Progress/__snapshots__/Progress.test.js.snap
packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.js.snap
packages/patternfly-4/react-core/src/components/Select/__snapshots__/SelectToggle.test.js.snap
packages/patternfly-4/react-core/src/components/Tabs/__snapshots__/Tabs.test.js.snap
packages/patternfly-4/react-inline-edit-extension/src/components/CancelButton/__snapshots__/CancelButton.test.js.snap
packages/patternfly-4/react-inline-edit-extension/src/components/ConfirmButton/__snapshots__/ConfirmButton.test.js.snap
packages/patternfly-4/react-inline-edit-extension/src/components/InlineEdit/__snapshots__/ConfirmButtons.test.js.snap
packages/patternfly-4/react-topology/src/components/TopologyControlBar/__snapshots__/TopologyControlBar.test.tsx.snap
packages/react-icons/src/common.d.ts
packages/react-icons/src/common.js
scripts/incrementalBuild.js

fix(react-icons): add noVerticalAlign prop to d.ts file

---

README.md

chore(readme): Update README.md with CircleCI Badge

---

packages/patternfly-4/react-virtualized-extension/src/components/Virtualized/VirtualGrid.ts

**What**:
seeing this warning downstream caused by typing inconsistency in VirtualGrid `aria-label`. For VirtualGrid and VirtualTableBody, this prop is optional. This will resolve our issue.
```
checkPropTypes.js:19 Warning: Failed prop type: The prop `aria-label` is marked as required in `VirtualGrid`, but its value is `null`.
in VirtualGrid (created by VirtualTableBody)
in VirtualTableBody (created by VirtualBody)
in VirtualBody (created by AutoSizer)
in div (created by AutoSizer)
in div (created by AutoSizer)
in AutoSizer (created by WindowScroller)
in WindowScroller (created by TableInner)
in div (created by TableWrapper)
in TableWrapper (created by TableInner)
in div (created by Data)
in Data (created by StatusBox)
in StatusBox (created by TableInner)
in div (created by TableInner) …
```

fix(virtual-grid): aria-label prop consistency

---

packages/patternfly-3/patternfly-react/src/components/Form/Form.stories.js
packages/patternfly-3/patternfly-react/src/components/Form/Stories/ModalForm.js

pf3(docs): fix modal form story example to allow close

---

packages/patternfly-4/react-core/src/components/Alert/Alert.tsx
packages/patternfly-4/react-core/src/components/Alert/__snapshots__/Alert.test.tsx.snap

fix(Alert): remove the <p> from the Alert description

---

RELEASE-NOTES.md

**What**: Format release notes using markdown.

chore(notes): format release notes

---

packages/patternfly-4/react-topology/src/components/TopologyControlBar/css/topology-controlbar-css.ts
packages/patternfly-4/react-topology/src/components/TopologySideBar/TopologySideBar.test.tsx
packages/patternfly-4/react-topology/src/components/TopologySideBar/TopologySideBar.tsx
packages/patternfly-4/react-topology/src/components/TopologySideBar/__snapshots__/TopologySideBar.test.tsx.snap
packages/patternfly-4/react-topology/src/components/TopologySideBar/css/topology-side-bar-css.ts
packages/patternfly-4/react-topology/src/components/TopologySideBar/index.ts
packages/patternfly-4/react-topology/src/components/TopologyView/TopologyView.test.tsx
packages/patternfly-4/react-topology/src/components/TopologyView/TopologyView.tsx
packages/patternfly-4/react-topology/src/components/TopologyView/__snapshots__/TopologyView.test.tsx.snap
packages/patternfly-4/react-topology/src/components/TopologyView/examples/ItemDetails.js
packages/patternfly-4/react-topology/src/components/TopologyView/examples/Topology.md
packages/patternfly-4/react-topology/src/components/TopologyView/examples/ViewToolbar.js
packages/patternfly-4/react-topology/src/components/index.ts

**What**:
Adds a TopologySideBar component and the ability to add the side bar to the TopologyVIew

feat( topology-sidebar): Adds TopologySidebar to react-topology

---

packages/patternfly-4/react-core/src/components/Alert/Alert.md

fix patternfly/patternfly-org#1213
**What**:
one of the alerts is not closeable

fix(Alert): fix close button action

---

packages/patternfly-4/react-topology/package.json

**What**:
Fix distribution for the JS in react-topology package

fix(topology): Fix react-topology distribution JS

---

packages/patternfly-4/react-core/src/components/Tabs/Tabs.tsx

Made variant prop optional.
Fixes #2345.

fix(Tabs): Make variant prop optional

---

packages/patternfly-4/react-core/src/components/Tabs/TabContent.tsx
packages/patternfly-4/react-core/src/components/Tabs/Tabs.tsx

fix(tabs): Remove comment from code

---

packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxContent.tsx
packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalBoxContent.test.tsx.snap
packages/patternfly-4/react-topology/src/components/TopologyControlBar/__snapshots__/TopologyControlBar.test.tsx.snap

fix(aboutmodal): change strapline element to paragraph

---

packages/patternfly-4/react-core/src/layouts/Grid/GridItem.js

fix(grid): always remove size props from {...props}

---

packages/patternfly-4/react-core/src/components/Card/Card.md
packages/patternfly-4/react-core/src/components/Card/Card.test.tsx
packages/patternfly-4/react-core/src/components/Card/Card.tsx
packages/patternfly-4/react-core/src/components/Card/CardHeader.tsx
packages/patternfly-4/react-core/src/components/Card/__snapshots__/Card.test.tsx.snap
packages/patternfly-4/react-core/src/components/Card/__snapshots__/CardHeader.test.tsx.snap
packages/patternfly-4/react-integration/cypress/integration/card.spec.ts
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/CardDemo/CardDemo.tsx

feat(card): Add compact card variation

---

packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenu.md
packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenu.test.js
packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenuToggle.tsx
packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenuToggleWithText.tsx
packages/patternfly-4/react-core/src/components/OptionsMenu/__snapshots__/OptionsMenu.test.js.snap
packages/patternfly-4/react-integration/cypress/integration/optionsmenu.spec.ts
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/OptionsMenuDemo/OptionsMenuDemo.tsx

feat(OptionsMenu): Add disabled modifier to the toggle

---

packages/patternfly-4/react-core/package.json
packages/patternfly-4/react-docs/package.json
packages/patternfly-4/react-inline-edit-extension/package.json
packages/patternfly-4/react-integration/demo-app-ts/package.json
packages/patternfly-4/react-table/package.json
packages/patternfly-4/react-topology/package.json
packages/patternfly-4/react-virtualized-extension/package.json

**What**: Unrelease the 4.0.0 branch that was accidentally published in #2201
**Additional issues**: Git tags have already been deleted for `lerna` to release. :crossed_fingers:

chore(core): unrelease 4.0.0 version branch

---

scripts/hashDir.js

fix(incremental-build): also hash folder names

---

RELEASE-NOTES.md

Adds release notes for 6/11 and 7/2 release bundles

chore(notes): update release notes for milestone

---

packages/patternfly-4/react-core/src/components/Select/Select.md

fix(select): removed ariaLabel from grouped checkbox select

---

packages/patternfly-4/react-charts/src/components/Chart/__snapshots__/Chart.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartArea/__snapshots__/ChartArea.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartAxis/__snapshots__/ChartAxis.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartBar/__snapshots__/ChartBar.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartContainer/__snapshots__/ChartContainer.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartGroup/__snapshots__/ChartGroup.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartLegend/__snapshots__/ChartLegend.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartLine/__snapshots__/ChartLine.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartPie/__snapshots__/ChartPie.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartPoint/__snapshots__/ChartPoint.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartStack/__snapshots__/ChartStack.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartTheme/themes/base-theme.ts
packages/patternfly-4/react-charts/src/components/ChartTooltip/__snapshots__/ChartTooltip.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartVoronoiContainer/__snapshots__/ChartVoronoContainer.test.tsx.snap

Need the latest pf-core changes to update charts. However, a var was removed which breaks the build.
Fixes https://github.com/patternfly/patternfly-react/issues/2460

Remove invalid pf-core var

---

.circleci/release.sh
.circleci/upload-docs.sh

**What**: Add comments on publishing a prerelease that lists the published versions. Example PR comment: https://github.com/patternfly/patternfly-react/pull/2433#issuecomment-507804797
**Additional issues**: Also gently refactor upload-docs.sh to be parametrized.

build(pr-comments): add PR comment on publish

---

packages/patternfly-4/react-charts/src/components/ChartTheme/themes/base-theme.ts

Removes an invalid pf-core import
fixes https://github.com/patternfly/patternfly-react/pull/2461

fix(charts): remove invalid pf-core var

---

.circleci/config.yml
.circleci/release.sh

**What**: Fixes #2416
**Additional issues**: Also remove debug leftover from #2433 and handle case where no packages are published from `lerna` (so there's no comment to leave).

chore(build): add check for breaking change to lint

---

packages/patternfly-4/react-core/src/layouts/Toolbar/Toolbar.d.ts
packages/patternfly-4/react-core/src/layouts/Toolbar/Toolbar.test.tsx
packages/patternfly-4/react-core/src/layouts/Toolbar/Toolbar.tsx
packages/patternfly-4/react-core/src/layouts/Toolbar/ToolbarGroup.d.ts
packages/patternfly-4/react-core/src/layouts/Toolbar/ToolbarGroup.tsx
packages/patternfly-4/react-core/src/layouts/Toolbar/ToolbarItem.d.ts
packages/patternfly-4/react-core/src/layouts/Toolbar/ToolbarItem.tsx
packages/patternfly-4/react-core/src/layouts/Toolbar/ToolbarSection.d.ts
packages/patternfly-4/react-core/src/layouts/Toolbar/ToolbarSection.tsx
packages/patternfly-4/react-core/src/layouts/Toolbar/__snapshots__/Toolbar.test.tsx.snap
packages/patternfly-4/react-core/src/layouts/Toolbar/examples/Toolbar.md
packages/patternfly-4/react-core/src/layouts/Toolbar/index.d.ts
packages/patternfly-4/react-core/src/layouts/Toolbar/index.js
packages/patternfly-4/react-core/src/layouts/Toolbar/index.ts
packages/patternfly-4/react-integration/cypress/integration/toolbar.spec.ts
packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/ToolbarDemo/ToolbarDemo.tsx
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts
packages/patternfly-4/react-topology/src/components/TopologyControlBar/__snapshots__/TopologyControlBar.test.tsx.snap
packages/patternfly-4/react-topology/src/components/TopologyView/__snapshots__/TopologyView.test.tsx.snap

feat(Toolbar): Convert toolbar to typescript

---

packages/patternfly-4/react-charts/src/components/ChartTheme/styles/common-styles.ts
packages/patternfly-4/react-charts/src/components/ChartTheme/styles/donut-styles.ts
packages/patternfly-4/react-charts/src/components/ChartTheme/themes/axis-theme.ts
packages/patternfly-4/react-charts/src/components/ChartTheme/themes/base-theme.ts

This updates the last remaining chart vars from pf-core.
fixes https://github.com/patternfly/patternfly-react/issues/2459

fix(charts): update pf-core vars

---

packages/patternfly-3/patternfly-react/src/components/BreadcrumbSwitcher/components/BreadcrumbSearchInput.js

**What**:
React requires camelCase for DOM attributes, we need to change `autocomplete` to `autoComplete` in PF.

fix(BreadCrumbSwitcher): Fix Autocomplete camelCase

---

packages/patternfly-3/patternfly-react/less/type-ahead-select.less

fix(pf3-react): add .css back to LESS import

---

packages/patternfly-4/react-core/src/components/Tabs/Tab.tsx
packages/patternfly-4/react-core/src/components/Tabs/TabContent.tsx
packages/patternfly-4/react-core/src/components/Tabs/Tabs.md
packages/patternfly-4/react-core/src/components/Tabs/Tabs.test.tsx
packages/patternfly-4/react-core/src/components/Tabs/Tabs.tsx
packages/patternfly-4/react-core/src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
packages/patternfly-4/react-integration/cypress/integration/tabsstringeventkey.spec.ts
packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TabsDemo/TabsStringEventKeyDemo.tsx
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts

feat(Tabs): Allow eventKey to accept a string

---

packages/patternfly-4/react-core/src/components/EmptyState/EmptyStateBody.tsx

feat(EmptyState): update EmptyStateBody to use <div> instead of <p>

---

packages/patternfly-4/react-core/src/components/Tabs/Tabs.md
packages/patternfly-4/react-core/src/components/Tabs/Tabs.tsx
packages/patternfly-4/react-core/src/components/Tabs/__snapshots__/Tabs.test.tsx.snap

feat(Tabs): Implement overflow styles for secondary tabs

---

README.md

**What**: This PR removes some problematic badges from the main readme, leaving the ones that are in good working order.
**Additional issues**: https://github.com/patternfly/patternfly-react/issues/2525

chore(badges): temporarily disable problematic badges

---

RELEASE-NOTES.md

**What**: For the next -org website update.
**Additional issues**: This should be done _before_ we promote next time.

Format RELEASE-NOTES.md

---

packages/patternfly-4/react-core/src/components/Form/Form.md

fix(form): replace radio with check

---

.circleci/release.sh

**What**: Fixes #2440
**Additional issues**: Will need a QUARKSTER_TOKEN from @quarckster added to CircleCI that used to be in Travis.

fix(quarkster): add curl command after release

---

scripts/hashDir.js
scripts/incrementalBuild.js

chore(incrementalBuild): invalidate all packages if yarn.lock changes

---

packages/patternfly-4/react-core/src/demos/PaginationTable.md

**What**:
closes #2337 
Added a working demo/example of pagination and table components.
//cc @tlabaj @jamesla

docs(Pagination): add a demo of table integrated with pagination

---

packages/patternfly-4/react-table/src/components/Table/Table.md
packages/patternfly-4/react-table/src/components/Table/index.js
packages/patternfly-4/react-table/src/components/Table/utils/decorators/wrappable.js
packages/patternfly-4/react-table/src/components/Table/utils/transformers.js
packages/patternfly-4/react-table/src/components/Table/utils/transformers.test.js

**What**:
closes #2578 
Add the wrap modifier to react-table through transforms.
//cc @karelhala @mcoker

feat(Table): Add the wrap transform

---

packages/patternfly-4/react-core/src/components/Button/Button.tsx
packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.tsx.snap

fix(button): add 'reset' to types

---

packages/patternfly-4/react-core/src/components/Select/Select.tsx
packages/patternfly-4/react-core/src/components/Select/SelectOption.tsx
packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.tsx.snap
packages/patternfly-4/react-core/src/components/Select/__snapshots__/SelectOption.test.tsx.snap
packages/patternfly-4/react-integration/cypress/integration/form.spec.ts
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/FormDemo/FormDemo.tsx

Added button="type" to buttons and updated tests. Verified in form demo.
Fixes #2029.

fix(Select): Prevent select from submitting forms

---

packages/patternfly-4/react-inline-edit-extension/src/components/InlineEdit/InlineEdit.md
packages/patternfly-4/react-inline-edit-extension/src/components/TableTextInput/TableTextInput.md
packages/patternfly-4/react-virtualized-extension/src/components/Virtualized/Virtualized.md
packages/patternfly-4/react-virtualized-extension/src/components/Virtualized/WindowScroller.md

**What**:
Improve the Gatsby doc for table extensions and add disclaimer about extension status... 

docs(extensions): add extension notes to Gatsby docs

---

RELEASE-NOTES.md

chore(Release Notes): update release notes for 2019.06

---

packages/patternfly-4/react-core/src/components/ApplicationLauncher/__snapshots__/ApplicationLauncher.test.js.snap
packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggle.tsx
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
packages/patternfly-4/react-core/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap

fix(Dropdown): Spread props to Dropdown toggle to fix regression

---

packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.md
packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggle.tsx
packages/patternfly-4/react-core/src/components/Dropdown/InternalDropdownItem.tsx

**What**: iconComponent's type was throwing a console warning and was marked as deprecated. Updated type to ElementType.
#2703

feat(Dropdown): adds missing class, changes icon type in toggle

---

RELEASE-NOTES.md

chore(notes): update release notes with versions

---

packages/patternfly-4/react-core/src/components/Tabs/TabContent.tsx
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TabsDemo/TabsDemo.tsx
packages/patternfly-4/react-table/src/components/Table/Table.tsx
packages/patternfly-4/react-table/src/components/Table/base/body-row.tsx
packages/patternfly-4/react-table/src/components/Table/base/body.tsx
packages/patternfly-4/react-table/src/components/Table/base/header-row.tsx
packages/patternfly-4/react-table/src/components/Table/base/header.tsx
packages/patternfly-4/react-table/src/components/Table/base/provider.tsx
packages/patternfly-4/react-table/src/components/Table/base/types.tsx

**What**: Fixes #2667, fixes #2674 in [systemjs-react](https://github.com/ssilvert/systemjs-react/tree/master).

Fix Table and TabContent types for SystemJS app

---

packages/patternfly-4/react-core/src/components/FormSelect/FormSelect.tsx
packages/patternfly-4/react-core/src/components/FormSelect/__snapshots__/FormSelect.test.tsx.snap

fix(formselect): adds isRequired prop

---

packages/patternfly-4/react-core/src/components/FormSelect/FormSelect.md

doc(formSelect): add the TS tag to FormSelect

---

packages/patternfly-4/react-table/src/components/Table/Table.md

docs(Table): update formatting of react-table link

---

packages/patternfly-4/react-core/src/experimental/components/Drawer/Drawer.md
packages/patternfly-4/react-docs/src/templates/mdxTemplate.js

**What**: Towards https://github.com/patternfly/patternfly-org/issues/1247

feat(experimental): add alert states for docs

---

README.md

Fix(badges): Add badges back

---

packages/patternfly-4/react-core/src/components/Modal/Modal.md

Adding the opt-in text for the modal

Modal optin text

---

packages/patternfly-4/react-table/src/components/Table/utils/decorators/cellWidth.ts

fix(table): use correct cellWidth class modifier

---

packages/patternfly-4/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx

**What**: This updates ClipboardCopy to update component if children changes
**Additional issues**: fixes #2846

fix(ClipboardCopy): Update if children change

---

packages/patternfly-4/react-core/src/components/ChipGroup/ChipGroupToolbarItem.tsx

fix(chipgroup): ChipGroupToolbarItem className

---

packages/patternfly-4/react-core/src/components/ChipGroup/ChipGroup.tsx

fix(chipgroup): allow chipgroup toolbar item to handle single chip

---

packages/patternfly-4/react-core/src/components/Expandable/Expandable.tsx
packages/patternfly-4/react-core/src/components/Expandable/__snapshots__/Expandable.test.tsx.snap

Fixes: https://github.com/patternfly/patternfly-react/issues/2954

fix controlled expandable

---

packages/patternfly-4/react-core/src/components/Pagination/Pagination.tsx
packages/patternfly-4/react-core/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap

Part of #2425
What: Added OUIA props to Pagination component

feat(Pagination): Added OUIA compatibility to Pagination component

---

packages/patternfly-4/react-core/src/components/Modal/Modal.md

**What**:
closes #2585 
Update Modal document to have cancel button as link.
@jschuler is that what you meant?

docs(modal): change the cancel button variant to link

---

packages/patternfly-3/patternfly-react/src/components/ApplicationLauncher/Stories/NavApplicationLauncherStory.js
packages/patternfly-3/patternfly-react/src/components/ApplicationLauncher/Stories/WrapperNavApplicationLauncherStory.js
packages/patternfly-3/patternfly-react/src/components/Cards/Stories/AggregateStatusCardStory.js
packages/patternfly-3/patternfly-react/src/components/Cards/Stories/BaseCardHeightMatchingStory.js
packages/patternfly-3/patternfly-react/src/components/Cards/Stories/BaseCardStory.js
packages/patternfly-3/patternfly-react/src/components/Cards/Stories/TrendCardStory.js
packages/patternfly-3/patternfly-react/src/components/Cards/Stories/UtilizationBarCardStory.js
packages/patternfly-3/patternfly-react/src/components/Cards/Stories/UtilizationCardStory.js
packages/patternfly-3/patternfly-react/src/components/DateTimePicker/DatePicker.stories.js
packages/patternfly-3/patternfly-react/src/components/DateTimePicker/DateTimePicker.stories.js
packages/patternfly-3/patternfly-react/src/components/HorizontalNav/HorizontalNav.stories.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/LoginPage.stories.js
packages/patternfly-3/patternfly-react/src/components/Notification/Stories/StatefulNotificationDrawerStory.js
packages/patternfly-3/patternfly-react/src/components/Notification/Stories/WrapperNotificationDrawerStory.js
packages/patternfly-3/patternfly-react/src/components/Notification/Stories/basicNotificationDrawerStory.js
packages/patternfly-3/patternfly-react/src/components/Slider/Slider.stories.js
packages/patternfly-3/patternfly-react/src/components/TypeAheadSelect/TypeAheadSelect.stories.js
packages/patternfly-3/react-console/src/SerialConsole/SerialConsole.stories.js
storybook/config.js

**What**: Fix PF3 storybook at https://patternfly-react.surge.sh/patternfly-3/ . It's currently looking sad:
**Additional issues**: Fixes #3001

fix(storybook): change addWithInfo to add

---

.circleci/config.yml
.codecov.yaml
README.md
jest.config.js

**What**: Fixes #3002, like #1432 except for CircleCI. Check https://codecov.io/gh/patternfly/patternfly-react

build(codecov): add back codecov

---

packages/patternfly-4/react-core/src/components/Button/Button.md
packages/patternfly-4/react-core/src/components/Button/Button.tsx
packages/patternfly-4/react-core/src/components/Button/__snapshots__/Button.test.tsx.snap
packages/patternfly-4/react-core/src/components/ContextSelector/ContextSelector.tsx
packages/patternfly-4/react-core/src/components/ContextSelector/__snapshots__/ContextSelector.test.tsx.snap
packages/patternfly-4/react-core/src/components/InputGroup/InputGroup.md
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/ButtonDemo/ButtonDemo.tsx
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/InputGroupDemo/InputGroupDemo.tsx

update context selector, input group examples
**What**:
**Refer to issue**: #2963

feat(Button): add control variant to button

---

packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarContent.tsx
packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarGroup.tsx
packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarItem.tsx
packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarToggleGroup.tsx
packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarUtils.tsx
packages/patternfly-4/react-core/src/helpers/util.test.js
packages/patternfly-4/react-core/src/helpers/util.ts
packages/patternfly-4/react-core/src/layouts/Flex/Flex.test.tsx
packages/patternfly-4/react-core/src/layouts/Flex/Flex.tsx
packages/patternfly-4/react-core/src/layouts/Flex/FlexItem.tsx
packages/patternfly-4/react-core/src/layouts/Flex/FlexUtils.tsx
packages/patternfly-4/react-core/src/layouts/Flex/__snapshots__/Flex.test.tsx.snap
packages/patternfly-4/react-core/src/layouts/Flex/examples/Flex.md
packages/patternfly-4/react-core/src/layouts/Flex/examples/flex.scss
packages/patternfly-4/react-core/src/layouts/Flex/index.ts
packages/patternfly-4/react-core/src/layouts/index.d.ts
packages/patternfly-4/react-core/src/layouts/index.js
packages/patternfly-4/react-integration/cypress/integration/flex.spec.ts
packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/FlexDemo/FlexDemo.tsx
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts

Added React support for Flex and FlexItem. Moved Nicole's DataToolbar breakpoint utility to main utils and added tests so I could reuse it for Flex.
Fixes #2860.

feat(Flex): Added support for flex layout, tests, etc.

---

packages/patternfly-4/react-core/src/components/Pagination/Navigation.tsx
packages/patternfly-4/react-core/src/components/Pagination/Pagination.md
packages/patternfly-4/react-core/src/components/Pagination/Pagination.test.tsx
packages/patternfly-4/react-core/src/components/Pagination/Pagination.tsx
packages/patternfly-4/react-core/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/PaginationDemo/PaginationDemo.tsx

**What**: Adds a flag to set whether the pagination component should be compact.
**Refer to issue**: #2874
PR #2904 updates the html structure and styling of pagination's toggle to match core

feat(Pagination): add compact variation flag

---

packages/patternfly-4/react-core/src/components/ClipboardCopy/ClipboardCopy.md
packages/patternfly-4/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx
packages/patternfly-4/react-core/src/components/ClipboardCopy/ClipboardCopyExpanded.tsx
packages/patternfly-4/react-core/src/components/ClipboardCopy/__snapshots__/ClipboardCopyExpanded.test.tsx.snap

Closes #2924. Any feedback/suggestions would be very much appreciated regarding how to clean up this PR. Thanks!

fix(copytoclipboard): wrap content in pre tag

---

packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarToggleGroup.tsx

fix(DataToolbar): add aria-haspopup to the toggle group

---

packages/patternfly-4/react-core/src/components/Alert/Alert.test.tsx
packages/patternfly-4/react-core/src/components/Alert/Alert.tsx
packages/patternfly-4/react-core/src/components/Alert/__snapshots__/Alert.test.tsx.snap

Part of #2425
What: Added OUIA props to Alert component

feat(Alert): Added OUIA compatibility to Alert component

---

packages/patternfly-4/react-core/src/components/Nav/Nav.tsx
packages/patternfly-4/react-core/src/components/Nav/__snapshots__/Nav.test.tsx.snap

Part of #2425
What: Added OUIA props to Nav component

feat(Nav): Added OUIA compatibility to Nav component

---

packages/patternfly-4/react-table/src/components/Table/Table.tsx

Some doc improvements for Table component properties.
Related to https://github.com/patternfly/patternfly-react/issues/2999, but not addressing most of the issues.

fix(react-docs): Improve the documentation for Table component from react-table

---

packages/patternfly-4/react-core/src/components/Breadcrumb/Breadcrumb.test.tsx
packages/patternfly-4/react-core/src/components/Breadcrumb/Breadcrumb.tsx
packages/patternfly-4/react-core/src/components/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap
packages/patternfly-4/react-core/src/components/Page/__snapshots__/Page.test.tsx.snap

Part of #2425
What: Added OUIA props to Breadcrumb component

 feat(Breadcrumb): Added OUIA compatibility to Breadcrumb component 

---

packages/patternfly-4/react-table/src/components/Table/utils/__snapshots__/transformers.test.tsx.snap
packages/patternfly-4/react-table/src/components/Table/utils/decorators/selectable.tsx

fix(table): remove scope=col from td elements

---

packages/patternfly-4/react-core/src/components/Tabs/Tabs.tsx
packages/patternfly-4/react-core/src/components/Tabs/__snapshots__/Tabs.test.tsx.snap

fix(Tabs): Fix the regression in the Tab class with the title prop

---

package.json
packages/patternfly-4/react-core/src/components/AboutModal/AboutModal.tsx
yarn.lock

**What**: Try to solve CI issues like https://circleci.com/gh/patternfly/patternfly-react/14816:
```
lerna ERR! ZlibError: zlib: invalid code lengths set
lerna ERR!     at Unzip.Zlib.(anonymous function) (/home/circleci/project/node_modules/minizlib/index.js:128:21)
lerna ERR!     at emitOne (events.js:121:20)
lerna ERR!     at Unzip.emit (events.js:211:7)
lerna ERR!     at Unzip.zlibOnError (zlib.js:156:8)
lerna ERR!     at Unzip._processChunk (zlib.js:411:30)
lerna ERR!     at Unzip.write (/home/circleci/project/node_modules/minizlib/index.js:254:30)
lerna ERR!     at Object.write (/home/circleci/project/node_modules/tar/lib/parse.js:305:58)
lerna ERR!     at Yallist.pipes.forEach.p (/home/circleci/project/node_modules/minipass/index.js:355:18)
lerna ERR!     at Yallist.forEach …
```

build(lerna): try to fix zip errors

---

RELEASE-NOTES.md

Updated release-notes.MD with 2019.08 release notes

Update RELEASE-NOTES.md [ci skip]

---

packages/patternfly-4/react-charts/src/components/ChartArea/examples/ChartArea.md
packages/patternfly-4/react-charts/src/components/ChartBar/examples/ChartBar.md
packages/patternfly-4/react-charts/src/components/ChartBullet/examples/ChartBullet.md
packages/patternfly-4/react-charts/src/components/ChartDonut/examples/ChartDonut.md
packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/examples/ChartDonutUtilization.md
packages/patternfly-4/react-charts/src/components/ChartLine/examples/ChartLine.md
packages/patternfly-4/react-charts/src/components/ChartPie/examples/ChartPie.md
packages/patternfly-4/react-charts/src/components/ChartStack/examples/ChartStack.md
packages/patternfly-4/react-charts/src/components/Sparkline/examples/sparkline.md

chore(charttutorial): update chart tutorial descriptions and links

---

RELEASE-NOTES.md

change tabs to spaces [ci skip]

---

packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncher.md
packages/patternfly-4/react-core/src/components/FormSelect/FormSelect.md
packages/patternfly-4/react-core/src/components/Nav/examples/Navigation.md
packages/patternfly-4/react-core/src/components/NotificationBadge/NotificationBadge.md
packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbar.md
packages/patternfly-4/react-topology/src/components/TopologyView/examples/Topology.md

**What**:
fixes React items in https://github.com/patternfly/patternfly-org/issues/1486; Zack is working on refactoring the HTML items in same issue.
Opened React issue to track this PR: https://github.com/patternfly/patternfly-react/issues/3062

fixed sentence case for component titles

---

packages/patternfly-4/react-core/src/components/Select/SelectOption.test.tsx
packages/patternfly-4/react-core/src/components/Select/SelectOption.tsx
packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.tsx.snap
packages/patternfly-4/react-core/src/components/Select/__snapshots__/SelectOption.test.tsx.snap

fix(Select): Allow custom components as select option

---

packages/patternfly-4/react-core/src/components/LoginPage/LoginForm.tsx
packages/patternfly-4/react-core/src/components/LoginPage/__snapshots__/LoginForm.test.tsx.snap

fix(loginform): pass 'remember me' state to isChecked

---

packages/patternfly-4/react-charts/src/components/ChartTooltip/examples/ChartTooltip.md

This simplifies the legend tooltip example
Fixes https://github.com/patternfly/patternfly-react/issues/3069

chore(charts): simplify legend tooltip example

---

packages/patternfly-4/react-core/src/components/Expandable/Expandable.tsx
packages/patternfly-4/react-core/src/components/Nav/NavExpandable.tsx
packages/patternfly-4/react-core/src/components/Page/Page.tsx
packages/patternfly-4/react-core/src/components/Select/Select.tsx
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/ApplicationLauncherDemo/ApplicationLauncherDemo.tsx
packages/patternfly-4/react-table/src/components/Table/ActionsColumn.tsx

Properly use this.setState in components

---

packages/patternfly-4/react-core/src/components/Button/Button.md

docs(button): add an example of a link button with anchor

---

packages/patternfly-4/react-core/src/components/DataList/DataListCheck.tsx
packages/patternfly-4/react-core/src/components/Select/CheckboxSelectOption.tsx
packages/patternfly-4/react-core/src/components/Select/SelectOption.tsx
packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.tsx.snap
packages/patternfly-4/react-core/src/components/Switch/Switch.test.tsx
packages/patternfly-4/react-core/src/components/Switch/Switch.tsx
packages/patternfly-4/react-core/src/components/Switch/__snapshots__/Switch.test.tsx.snap

**What**: Closes #2997, reverts #2749

fix(switch): revert defaultChecked to checked

---

packages/patternfly-4/react-core/src/components/ClipboardCopy/ClipboardCopyExpanded.test.tsx
packages/patternfly-4/react-core/src/components/ClipboardCopy/ClipboardCopyExpanded.tsx
packages/patternfly-4/react-core/src/components/ClipboardCopy/__snapshots__/ClipboardCopyExpanded.test.tsx.snap

**What**:
closes #3163 
//cc @christiemolloy @jessiehuff @jenny-s51

fix(copytoclipboard): wrap pre inside the expand element

---

packages/patternfly-4/react-core/src/components/Select/SelectToggle.tsx
packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.tsx.snap

fix(Select): add plain modifier to toggle button

---

packages/patternfly-4/react-core/src/components/Select/Select.tsx

docs(Select): update prop description for selctions

---

packages/patternfly-4/react-core/src/experimental/components/DataToolbar/__snapshots__/DataToolbar.test.tsx.snap

**What**: Fix broken snapshot on master

fix snapshot

---

RELEASE-NOTES.md

docs(Release Notes): Update release notes 2019.9

---

packages/patternfly-4/react-virtualized-extension/package.json
packages/patternfly-4/react-virtualized-extension/src/components/Virtualized/VirtualGrid.ts
packages/patternfly-4/react-virtualized-extension/src/components/Virtualized/VirtualTableBody.tsx

**What**: Fix virtual table issues in Openshift console

fix(virtualized): fix regressions from #2761

---

packages/patternfly-4/react-table/src/components/Table/Table.tsx

**What**: Fixes regression from #3008 for koko-ui and @dlabrecq .

fix(table): bind isTableEmpty function

---

packages/patternfly-4/react-table/src/components/Table/Table.tsx
packages/patternfly-4/react-virtualized-extension/src/components/Virtualized/__snapshots__/VirtualizedTable.test.tsx.snap

Reverts patternfly/patternfly-react#3242

Revert "fix(Table): Add opt out of disable header on empty table"

---

packages/patternfly-4/react-catalog-view-extension/sass/react-catalog-view-extension/_properties-side-panel.scss

Address: https://github.com/patternfly/patternfly-react/issues/3235 
**What**:

fix(PropertiesSidePanel) Align sass file with correct styles for properties panel

---

packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenuItem.tsx
packages/patternfly-4/react-core/src/components/OptionsMenu/__snapshots__/OptionsMenu.test.js.snap

**What**:
closes #3229 
//cc @mcoker

fix(optionmenu): remove the i element around selected item svg

---

packages/patternfly-4/react-catalog-view-extension/sass/react-catalog-view-extension/_catalog-item.scss
scripts/incrementalBuild.js

**What**: Fix bug reported by @jcaianirh where the extension wasn't rebuilt after #3236

fix(catalog-view-extension): check for sass changes

---

packages/patternfly-4/react-catalog-view-extension/package.json
yarn.lock

**What**: Remove unused dev dependencies from package.json

fix(catalog-view-extension): Remove unused dev dependencies from package.json

---

packages/patternfly-4/react-catalog-view-extension/sass/react-catalog-view-extension/_catalog-tile.scss
packages/patternfly-4/react-catalog-view-extension/src/components/CatalogTile/CatalogTile.tsx

Updated sass for better use in OpenShift. Added class to images.

fix(CatalogTile): Update scss and add class to image

---

packages/patternfly-4/react-catalog-view-extension/sass/react-catalog-view-extension/_catalog-tile.scss

Updated margins per design feedback and fixed hidden text bug.

fix(CatalogTile): Removed margin and fixed hidden text

---

packages/patternfly-4/react-core/src/components/AboutModal/AboutModal.tsx
packages/patternfly-4/react-core/src/components/Wizard/Wizard.tsx
packages/patternfly-4/react-core/src/components/Wizard/__snapshots__/Wizard.test.tsx.snap

**What**:
closes #3237 
//cc @keithjgrant

fix(wizard,aboutmodal): remove appendTo from props passed to div

---

scripts/promote.sh

**What**: Just a little build fix I'd like to commit upstream that makes my life easier to promote packages. No associated issue.
**Additional issues**: Closes #3322

chore(build): add new package to promotion script

---

packages/patternfly-4/react-core/src/components/Accordion/Accordion.tsx
packages/patternfly-4/react-core/src/components/Accordion/examples/Accordion.md
packages/patternfly-4/react-integration/cypress/integration/accordion.spec.ts
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/AccordionDemo/AccordionDemo.tsx

feat(Accordion): Add a prop to allow the box shadow to be removed

---

packages/patternfly-4/react-catalog-view-extension/sass/react-catalog-view-extension/_catalog-item.scss

Removed unneeded class that addresses a separate component for some reason.

fix(CatalogTile): Removed unneeded selector

---

packages/patternfly-4/react-catalog-view-extension/package.json
packages/patternfly-4/react-catalog-view-extension/src/components/CatalogTile/CatalogTile.test.tsx

remove unused packages from package.json

fix(catalog-view-extension): remove unused packages

---

RELEASE-NOTES.md

docs(RELEASE-NOTES): Update the release notes for 2019.10

---

packages/patternfly-4/react-core/src/demos/TableEmptyStatesDemo.md
packages/patternfly-4/react-core/src/demos/VariousTableStatesDemo.md

Add various table state demos

---

packages/patternfly-4/react-core/src/components/Popover/Popover.tsx
packages/patternfly-4/react-core/src/components/Popover/__snapshots__/Popover.test.tsx.snap

**What**: Closes #3368 
Also fixes that after closing the popover, the Button that opened it should be re-focused

Popover - make text selectable

---

packages/patternfly-4/react-core/src/components/Progress/examples/Progress.md

**What**: Fixes a typo to close #3380
**Additional issues**: No associated issue

docs(progress): fix typo

---

packages/patternfly-4/react-core/src/components/DataList/examples/DataList.md

Just look few lines above. It is already imported.
Thanks!
close: #3381

Remove duplicate import from the docs

---

packages/patternfly-4/react-core/src/components/EmptyState/EmptyStateIcon.tsx

docs(EmptyStateIcon): mark deprecated props

---

packages/patternfly-4/react-core/src/components/Pagination/Navigation.tsx
packages/patternfly-4/react-core/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap

fix(Pagination): fixed prev arrows are active with 0 rows

---

packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggleCheckbox.tsx
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/DropdownToggleCheckbox.test.tsx.snap

fix(Dropdown): Update component to use input rather than PF Checkbox

---

packages/patternfly-4/react-core/src/components/Breadcrumb/examples/Breadcrumb.md
packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayout.md

doc(PageLayout): set breadcrumb, nav and title texts to sentence case

---

.circleci/config.yml

don't cache stale doc builds

---

RELEASE-NOTES.md

chore(Release notes): update release notes for 2018.11

---

packages/patternfly-4/react-core/src/components/DataList/DataList.test.js
packages/patternfly-4/react-core/src/components/DataList/DataList.tsx
packages/patternfly-4/react-core/src/components/DataList/DataListItem.tsx
packages/patternfly-4/react-core/src/components/DataList/__snapshots__/DataList.test.js.snap

Fixes the breaking change causing OpenShift build to fail

fix(DataList): Revert React.Component back to React.FunctionComponent

---

packages/patternfly-4/react-core/src/components/DataList/DataList.test.js
packages/patternfly-4/react-core/src/components/DataList/DataListItem.tsx
packages/patternfly-4/react-core/src/components/DataList/__snapshots__/DataList.test.js.snap

Remove hook so Integrately can use DataList updates.

fix(DataList): remove hook

---

RELEASE-NOTES.md

chore(Release notes): Updated release notes with latest packages

---

RELEASE-NOTES.md

fix(Release notes): fix release notes

---

packages/patternfly-3/patternfly-react/src/components/DateTimePicker/DateComponents/__snapshots__/DecadeView.test.js.snap

chore(datetimepicker): update test snapshot due to new year

---

packages/patternfly-4/react-core/src/components/ClipboardCopy/ClipboardCopyButton.tsx
packages/patternfly-4/react-core/src/components/ClipboardCopy/ClipboardCopyToggle.tsx
packages/patternfly-4/react-core/src/components/ClipboardCopy/__snapshots__/ClipboardCopyButton.test.tsx.snap
packages/patternfly-4/react-core/src/components/ClipboardCopy/__snapshots__/ClipboardCopyToggle.test.tsx.snap

**What**: Closes #3443 
//cc @elad661

fix(clipboardcopy): set type of copy and toggle buttons to 'button'

---

packages/patternfly-4/react-core/src/components/ChipGroup/ChipGroup.test.tsx
packages/patternfly-4/react-core/src/components/ChipGroup/ChipGroupToolbarItem.tsx
packages/patternfly-4/react-core/src/components/ChipGroup/__snapshots__/ChipGroup.test.tsx.snap
packages/patternfly-4/react-core/src/components/ChipGroup/examples/ChipGroup.md
packages/patternfly-4/react-core/src/experimental/components/DataToolbar/__snapshots__/DataToolbar.test.tsx.snap
packages/patternfly-4/react-integration/cypress/integration/chipgrouptoolbar.spec.ts
packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/ChipGroupDemo/ChipGroupToolbarDemo.tsx
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts

feat(ChipGroup): add closable chip-group

---

packages/patternfly-4/react-core/src/components/Pagination/Navigation.tsx
packages/patternfly-4/react-core/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap

fix(pagination): disable navigation input if page is equal to zero

---

packages/patternfly-4/react-charts/src/components/ChartArea/examples/ChartArea.md
packages/patternfly-4/react-charts/src/components/ChartBar/examples/ChartBar.md
packages/patternfly-4/react-charts/src/components/ChartLegend/examples/ChartLegend.md
packages/patternfly-4/react-charts/src/components/ChartScatter/examples/ChartScatter.md
packages/patternfly-4/react-charts/src/components/ChartStack/examples/ChartStack.md
packages/patternfly-4/react-charts/src/components/ChartTheme/examples/ChartTheme.md
packages/patternfly-4/react-charts/src/components/ChartThreshold/examples/ChartThreshold.md
packages/patternfly-4/react-charts/src/components/ChartTooltip/examples/ChartTooltip.md

Fixed examples(*.md files) in charts package.

Lint md charts 3486

---

packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarChipGroupContent.tsx
packages/patternfly-4/react-core/src/experimental/components/DataToolbar/__snapshots__/DataToolbar.test.tsx.snap

fix(DataToolbar): add and remove some modifiers to match core

---

packages/patternfly-3/react-console/src/VncConsole/VncActions.js
packages/patternfly-3/react-console/src/VncConsole/VncConsole.js

**What**: Closes https://github.com/patternfly/patternfly-react/issues/3475
Added support of additional buttons for VncConsole toolbar.
**Additional issues**: It needed for completely replace local version of VncConsole by patternfly version https://github.com/oVirt/ovirt-web-ui/pull/1091

feat(VncConsole): Added `additionalButtons` prop to VncConsole

---

packages/patternfly-4/react-core/src/components/Select/SelectToggle.tsx
packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.tsx.snap
packages/patternfly-4/react-integration/cypress/integration/select.spec.ts
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectDemo.tsx

**What**: Closes #3463 
This is an easy fix.
I added `select` spec test to verify this works and there won't be regressions and updated the snapshot.

fix(select): Add the type prop to the select toggle button

---

packages/patternfly-4/react-catalog-view-extension/src/components/CatalogItemHeader/examples/CatalogItemHeader.md
packages/patternfly-4/react-catalog-view-extension/src/components/CatalogTile/examples/CatalogTile.md
packages/patternfly-4/react-catalog-view-extension/src/components/FilterSidePanel/examples/FilterSidePanel.md
packages/patternfly-4/react-catalog-view-extension/src/components/PropertiesSidePanel/examples/PropertiesSidePanel.md
packages/patternfly-4/react-catalog-view-extension/src/components/VerticalTabs/examples/VerticalTabs.md
packages/patternfly-4/react-docs/gatsby-config.js
packages/patternfly-4/react-inline-edit-extension/src/components/InlineEdit/InlineEdit.md
packages/patternfly-4/react-inline-edit-extension/src/components/TableTextInput/TableTextInput.md
packages/patternfly-4/react-virtualized-extension/src/components/Virtualized/VirtualizedTable.md
packages/patternfly-4/react-virtualized-extension/src/components/Virtualized/WindowScroller.md

**What**: Closes #3438 
//cc @redallen

docs(extensions): Move extensions to 'Extensions' in side nav category

---

packages/patternfly-3/patternfly-react/src/components/DateTimePicker/DateTimePicker.js
packages/patternfly-3/patternfly-react/src/components/DateTimePicker/TimeHelpers.js

**What**: Closes #3507 and fixes tests on master

fix(datetimepicker): try using toLocaleTimeString

---

.eslintrc_md.json
packages/patternfly-4/react-core/src/demos/BulkSelectTable.md
packages/patternfly-4/react-core/src/demos/FilterTableDemo.md
packages/patternfly-4/react-core/src/demos/PaginationTable.md
packages/patternfly-4/react-core/src/demos/TableEmptyStatesDemo.md

Updated *.md files in demos and verified they were working in codesandbox as well

Lint md react core demo 3486

---

packages/patternfly-4/react-table/src/components/Table/Table.md

fix linting of code blocks inside markdown files
https://github.com/patternfly/patternfly-react/issues/3486

fix(linting): minor updates to react-table package.

---

.eslintrc_md.json
packages/patternfly-4/react-virtualized-extension/src/components/Virtualized/VirtualizedTable.md
packages/patternfly-4/react-virtualized-extension/src/components/Virtualized/WindowScroller.md

Added super(props) to constructor(s)
Added space after opening comment chars. 
https://github.com/patternfly/patternfly-react/issues/3486

fix(linting): minor updates to VirtualizedTable examples.

---

packages/patternfly-4/react-core/src/components/Page/PageHeader.tsx
packages/patternfly-4/react-core/src/components/Page/__snapshots__/Page.test.tsx.snap
packages/patternfly-4/react-core/src/components/Page/__snapshots__/PageHeader.test.tsx.snap

Closes #3498.
**Additional issues**:  Addresses #2580.

fix(PageHeader): removing redundant role="banner" attribute

---

packages/patternfly-4/react-core/src/components/Select/Select.test.tsx
packages/patternfly-4/react-core/src/components/Select/SelectOption.tsx
packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.tsx.snap
packages/patternfly-4/react-core/src/components/Select/examples/Select.md

feat(Select): allow custom option data comparison

---

packages/patternfly-4/react-docs/package.json
yarn.lock

consume changes for gatsby-theme-patternfly-org package

fix(demos): upped version of gatsby-theme-patternfly-org

---

packages/patternfly-4/react-catalog-view-extension/src/components/CatalogTile/CatalogTile.tsx
packages/patternfly-4/react-catalog-view-extension/src/components/FilterSidePanel/FilterSidePanelCategory.tsx
packages/patternfly-4/react-catalog-view-extension/src/components/FilterSidePanel/FilterSidePanelCategoryItem.tsx
packages/patternfly-4/react-catalog-view-extension/src/components/PropertiesSidePanel/PropertyItem.tsx
packages/patternfly-4/react-core/src/components/Wizard/examples/SampleForm.js
packages/patternfly-4/react-core/src/layouts/Toolbar/examples/SimpleToolbar.js
packages/patternfly-4/react-core/src/layouts/Toolbar/examples/SimpleToolbarSection.js
packages/patternfly-4/react-docs/src/pages/icons.js
packages/patternfly-4/react-docs/src/pages/index.js
packages/patternfly-4/react-inline-edit-extension/src/components/CancelButton/CancelButton.js
packages/patternfly-4/react-inline-edit-extension/src/components/ConfirmButton/ConfirmButton.js
packages/patternfly-4/react-inline-edit-extension/src/components/InlineEdit/InlineEdit.api.test.js
packages/patternfly-4/react-inline-edit-extension/src/components/InlineEdit/editableTableBody.d.ts
packages/patternfly-4/react-inline-edit-extension/src/components/TableTextInput/TableTextInput.d.ts
packages/patternfly-4/react-inline-edit-extension/src/components/TableTextInput/TableTextInput.js
packages/patternfly-4/react-integration/demo-app-ts/src/common/State.ts
packages/patternfly-4/react-table/src/components/Table/ActionsColumn.tsx
packages/patternfly-4/react-table/src/components/Table/CollapseColumn.tsx
packages/patternfly-4/react-table/src/components/Table/RowWrapper.tsx
packages/patternfly-4/react-table/src/components/Table/Table.tsx
packages/patternfly-4/react-table/src/components/Table/utils/decorators/compoundExpand.tsx
packages/patternfly-4/react-topology/src/components/TopologyControlBar/TopologyControlBar.tsx
packages/patternfly-4/react-topology/src/components/TopologySideBar/TopologySideBar.tsx
packages/patternfly-4/react-topology/src/components/TopologyView/TopologyView.tsx
packages/patternfly-4/react-topology/src/components/TopologyView/examples/ItemDetails.js
packages/patternfly-4/react-topology/src/components/TopologyView/examples/ProjectToolbar.js

feat(pf4): Use absolute import paths for react core in pf4 packages.

---

packages/patternfly-4/react-core/src/demos/FilterTableDemo.md

fix (Datatoolbar): Updated example to not exclude previous filtered items.

---

packages/patternfly-4/react-table/src/components/Table/ActionsColumn.tsx

**What**: Closes #3577 
**Additional issues**: Issue introduced by #3525

fix(ActionsColumn): fixed import path for DropdownSeparator

---

packages/patternfly-4/react-integration/cypress/integration/alert.spec.ts
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/AlertDemo/AlertDemo.tsx

**What**: Fixes integration tests on master

fix(alert): fix integration test regression

---

RELEASE-NOTES.md

chore(Release notes): Update release notes for 2020.01

---

packages/patternfly-4/react-core/src/components/Wizard/Wizard.test.tsx
packages/patternfly-4/react-core/src/components/Wizard/WizardContext.ts

fix(wizard): add typeto wizard context

---

packages/patternfly-4/react-styles/package.json
yarn.lock

**What**: Closes #3629
cc @dlabrecq

fix(react-styles): move deps to dev deps

---

packages/patternfly-4/react-core/src/components/Page/Page.tsx
packages/patternfly-4/react-core/src/components/Page/PageHeader.tsx
packages/patternfly-4/react-core/src/components/Page/__snapshots__/Page.test.tsx.snap
packages/patternfly-4/react-integration/cypress/integration/page.spec.ts
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/PageDemo/PageDemo.tsx

**What**: Closes #2580. 
**Additional issues**: Following a discussion with @seanforyou23, it was decided that instead of removing the `role` attribute entirely (as was done in #3499), we should instead allow the user to optionally configure it using a prop.

fix(Page & PageHeader): adds optional "role" prop

---

.github/ISSUE_TEMPLATE.md

chore(github): fix broken link in issue template

---

packages/eslint-plugin-patternfly-react/lib/config/recommended.js
packages/eslint-plugin-patternfly-react/package.json
yarn.lock

feat(eslint): add react-hooks to eslint-plugin-patternfly-react

---

.circleci/config.yml

fix(build): update circleci config for pricing

---

packages/patternfly-4/react-core/src/demos/FilterTableDemo.md

docs(Demo): fixed the TextInput type in filter table demo

---

.circleci/config.yml
package.json

fix(react-core): fixed typo, added md lint to circleci

---

packages/patternfly-4/react-core/src/components/ContextSelector/ContextSelector.tsx

Updated signature for context selector to match what is returned.
fix #3694

fix(ContextSelector): Updated signature for context selector 

---

packages/patternfly-4/react-core/src/demos/FilterTableDemo.md
packages/patternfly-4/react-table/src/components/Table/Table.md
packages/patternfly-4/react-table/src/components/Table/utils/decorators/wrappable.ts

Table: support for truncated column headers

---

packages/patternfly-4/react-core/README.md

Updated node version in readme

fix(docs): updated node version in readme

---

packages/patternfly-4/react-table/src/components/Table/Body.tsx
packages/patternfly-4/react-table/src/components/Table/Header.tsx
packages/patternfly-4/react-table/src/components/Table/Table.tsx

Updated table property descriptions

fix(docs): updated table property descriptions

---

package.json
packages/patternfly-4/react-integration/cypress/integration/tableeditable.spec.ts
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TableDemo/TableEditableDemo.tsx
packages/patternfly-4/react-styled-system/scripts/copyTS.js
packages/patternfly-4/react-styled-system/src/components/StyledSystem/StyledTheme.d.ts
packages/patternfly-4/react-styled-system/src/components/StyledSystem/StyledTheme.js

**What**: Towards #3592 - resolves existing linter issues for react-styled-system

chore(react-styled-system): fixed linter errors

---

packages/patternfly-4/react-docs/package.json
packages/patternfly-4/react-inline-edit-extension/package.json
packages/patternfly-4/react-table/package.json
packages/patternfly-4/react-topology/package.json
packages/patternfly-4/react-virtualized-extension/package.json
packages/react-icons/package.json

Version fix 3759

---

packages/react-icons/README.md

**What**: Fixes typo in react-icons README file

fixed typo in README

---

RELEASE-NOTES.md

Please review these 2020.02 release notes

Release notes 2020.02

---

packages/patternfly-4/react-core/src/components/Tooltip/examples/Tooltip.md

remove TooltipContent from propComponents

---

packages/patternfly-4/react-core/src/components/Switch/Switch.tsx
packages/patternfly-4/react-integration/cypress/integration/switch.spec.ts
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/SwitchDemo/SwitchDemo.tsx

**What**: Closes #3662 
//cc @jeudy100

fix(switch): avoid switch id override by props

---

packages/patternfly-4/react-core/src/components/Pagination/Pagination.tsx
packages/patternfly-4/react-core/src/components/Pagination/__tests__/__snapshots__/Pagination.test.tsx.snap

**What**: Closes #3530 
//cc @LeshemNoa

fix(pagination): calculate navigation input according to last page

---

packages/patternfly-4/react-core/src/components/Select/examples/Select.md

docs(select): fix panel checkbox labels

---

package.json
packages/eslint-plugin-patternfly-react/lib/config/recommended.js
packages/eslint-plugin-patternfly-react/package.json
yarn.lock

fix(eslint): fix eslint recommendations

---

packages/react-core/src/components/withOuia/withOuia.tsx

fix(ouia): don't omit ouiaContext

---

packages/react-core/src/components/Wizard/WizardBody.tsx

fix(wizard): use patternfly-styles to set the no padding modifier

---

packages/react-codemods/transforms/pf3-pf4.button.test.js
packages/react-codemods/transforms/pf3-pf4.js
packages/react-codemods/transforms/pf3-pf4.test.js
packages/react-core/src/components/AboutModal/AboutModal.tsx
packages/react-core/src/components/AlertGroup/AlertGroup.tsx
packages/react-core/src/components/DataList/DataList.tsx
packages/react-core/src/components/DataToolbar/DataToolbar.tsx
packages/react-core/src/components/Modal/Modal.tsx
packages/react-core/src/components/Tabs/Tab.tsx
packages/react-core/src/components/Wizard/Wizard.tsx
packages/react-core/src/components/withOuia/withOuia.tsx
packages/react-core/src/helpers/safeHTMLElement.js
packages/react-core/src/helpers/util.ts
packages/react-icons/src/createIcon.js

**What**: Towards #3836
**Additional issues**: We don't mark lodash as a dependency or peer dependency, so really we shouldn't ever have included it!

chore(react-core): remove exenv and lodash

---

RELEASE-NOTES.md

chore(Realease Notes): Updated release notes for 2020.03 release

---

packages/react-core/README.md

blank update to force deploy

---

packages/react-core/src/components/Dropdown/Toggle.tsx

**What**: Fixes build error on master. Maybe caused by #3861?

fix(dropdown): remove duplicate prop

---

packages/react-core/src/components/Select/Select.tsx

feat(Select): add logic for disabled default options for typeahead

---

packages/react-core/src/components/EmptyState/examples/EmptyState.md

**What**: Closes #3538 
**Additional issues**: Extends #3943, moved PR to v4 branch per @tlabaj

fix(EmptyState): reorders examples, renames 'simple' to 'basic'

---

packages/react-docs/static/umd.html

**What**: Followup to #3971
**Additional issues**: Check that https://patternfly-react-pr-3982.surge.sh/umd.html works!

fix(docs): fix path to react-core UMD file

---

packages/react-icons/README.md

**What**: Closes #3936 
**Additional issues**: Extends #3937 in response to @tlabaj -- changed base repo to v4.

Updates react-icons README.md

---

package.json
packages/react-docs/RELEASE-NOTES.md
yarn.lock

Updated release notes for 2020.04.
Also add `libnpm`, which is a dependency of our promote script.

update release notes

---

packages/react-core/src/components/Drawer/Drawer.tsx
packages/react-core/src/components/Drawer/DrawerPanelContent.tsx

Drawer: Prop descriptions missing

---

packages/react-core/src/layouts/Gallery/Gallery.tsx
packages/react-core/src/layouts/Grid/Grid.tsx
packages/react-core/src/layouts/Level/Level.tsx
packages/react-core/src/layouts/Split/Split.tsx
packages/react-core/src/layouts/Stack/Stack.tsx
packages/react-core/src/styles/gutters.ts

fix(react-core): guttersize type regression

---

packages/react-core/src/components/AlertGroup/AlertGroupInline.tsx
packages/react-core/src/components/BackgroundImage/BackgroundImage.tsx
packages/react-core/src/components/Page/PageHeader.tsx
packages/react-core/src/components/Page/PageSection.tsx
packages/react-core/src/components/Pagination/ToggleTemplate.tsx
packages/react-core/src/components/Tooltip/TooltipArrow.tsx
packages/react-core/src/components/Tooltip/TooltipContent.tsx

**What**: Closes #4045
**Additional issues**: Towards #3972

Correctly type exported function components

---

packages/react-core/CONTRIBUTING.md

docs(pf4): fix broken link to react-integration in contribution guide

---

packages/react-core/src/components/Card/examples/Card.md
packages/react-core/src/components/Form/examples/Form.md
packages/react-core/src/components/Select/examples/Select.md

Makes sure that examples have unique ids for accessibility.
What: Closes #3419 #3416 #3415

fix(examples): Fix ids to resolve site axe issues

---

packages/react-core/src/components/Form/examples/Form.md

**What**: Closes #3918 
@tlabaj I opened a new pull request.

docs(form): change cancel buttons to link variant

---

packages/react-core/src/components/Card/Card.tsx
packages/react-core/src/components/Card/__tests__/Card.test.tsx
packages/react-core/src/components/Card/examples/Card.md
packages/react-integration/cypress/integration/card.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/CardDemo/CardDemo.tsx

**What**: Closes #3987 
//cc @mcoker @tlabaj

feat(card): support flat variation

---

packages/react-core/src/components/DataToolbar/DataToolbarUtils.tsx
packages/react-core/src/components/DataToolbar/index.ts
packages/react-topology/src/components/TopologyControlBar/TopologyControlBar.tsx
packages/react-topology/src/components/TopologyControlBar/__snapshots__/TopologyControlBar.test.tsx.snap
packages/react-topology/src/components/TopologyView/TopologyView.tsx
packages/react-topology/src/components/TopologyView/__snapshots__/TopologyView.test.tsx.snap
packages/react-topology/src/components/TopologyView/examples/ProjectToolbar.js
packages/react-topology/src/components/TopologyView/examples/ViewToolbar.js

chore(react-topology): replace Toolbar layout with DataToolbar

---

packages/react-core/src/components/Tooltip/examples/Tooltip.md

Closes https://github.com/patternfly/patternfly-org/issues/1791

fix(tooltip): codesandbox examples

---

packages/react-catalog-view-extension/package.json
packages/react-charts/package.json
packages/react-core/package.json
packages/react-docs/package.json
packages/react-icons/package.json
packages/react-inline-edit-extension/package.json
packages/react-styles/package.json
packages/react-table/package.json
packages/react-tokens/package.json
packages/react-topology/package.json
packages/react-virtualized-extension/package.json
scripts/verifyPatternflyVersions.js
yarn.lock

**What**: Bumps `@patternfly/patternfly` to 2.71.5.

chore(release): bump core

---

packages/react-docs/RELEASE-NOTES.md

Release notes 2020.05

---

packages/react-docs/package.json

**What**: Towards https://github.com/patternfly/patternfly-org/issues/1782

chore(react-docs): publish docs

---

packages/react-docs/RELEASE-NOTES.md

chore(Release notes): Update release note package versions

---

packages/react-integration/demo-app-ts/custom.d.ts
packages/react-integration/demo-app-ts/tsconfig.json

**What**: Closes #3925
**Master PR**: #3926

fix: fix broken image links

---

packages/react-core/src/components/EmptyState/EmptyStateIcon.tsx

chore(EmptyStateIcon): update docs to reflect suggested icons

---

packages/react-core/src/components/Select/examples/Select.md

**What**: Issue reported in Slack

fix(select): add missing import to docs

---

packages/react-core/src/components/Drawer/Drawer.tsx
packages/react-core/src/components/Drawer/DrawerPanelContent.tsx
packages/react-core/src/components/Drawer/__tests__/Generated/DrawerPanelContent.test.tsx
packages/react-core/src/components/Drawer/__tests__/Generated/__snapshots__/Drawer.test.tsx.snap
packages/react-core/src/components/Drawer/__tests__/__snapshots__/Drawer.test.tsx.snap

**What**: Closes #3984 
//cc @mattnolting

fix(drawer): remove hidden when drawer is expanded

---

packages/react-charts/src/components/Chart/Chart.tsx
packages/react-charts/src/components/ChartArea/ChartArea.tsx
packages/react-charts/src/components/ChartAxis/ChartAxis.tsx
packages/react-charts/src/components/ChartBar/ChartBar.tsx
packages/react-charts/src/components/ChartBullet/ChartBullet.tsx
packages/react-charts/src/components/ChartBullet/ChartBulletComparativeErrorMeasure.tsx
packages/react-charts/src/components/ChartBullet/ChartBulletComparativeMeasure.tsx
packages/react-charts/src/components/ChartBullet/ChartBulletComparativeWarningMeasure.tsx
packages/react-charts/src/components/ChartBullet/ChartBulletPrimaryDotMeasure.tsx
packages/react-charts/src/components/ChartBullet/ChartBulletPrimarySegmentedMeasure.tsx
packages/react-charts/src/components/ChartBullet/ChartBulletQualitativeRange.tsx
packages/react-charts/src/components/ChartDonut/ChartDonut.tsx
packages/react-charts/src/components/ChartDonutUtilization/ChartDonutThreshold.tsx
packages/react-charts/src/components/ChartDonutUtilization/ChartDonutUtilization.tsx
packages/react-charts/src/components/ChartGroup/ChartGroup.tsx
packages/react-charts/src/components/ChartLine/ChartLine.tsx
packages/react-charts/src/components/ChartPie/ChartPie.tsx
packages/react-charts/src/components/ChartScatter/ChartScatter.tsx
packages/react-charts/src/components/ChartStack/ChartStack.tsx
packages/react-charts/src/components/ChartThreshold/ChartThreshold.tsx

Update react-charts types to match Victory v34.x
https://github.com/patternfly/patternfly-react/issues/4080

Update react-charts types

---

packages/react-icons/scripts/writeIcons.js

**What**: Fixes `ts-jest` problem reported by @dlabrecq :

fix(icons): rename index.ts to index.d.ts

---

packages/react-core/src/helpers/util.ts

fix(fillTemplate): ie11 compatibility

---

packages/react-core/src/components/Select/Select.tsx
packages/react-core/src/components/Select/__tests__/Select.test.tsx
packages/react-core/src/components/Select/examples/Select.md

Users can supply a prop to pass in placeholder text for the inline filter.
Fixes #4162.

feat(Select): Added placeholder text for inline filter

---

packages/react-core/src/components/ApplicationLauncher/__tests__/__snapshots__/ApplicationLauncher.test.tsx.snap
packages/react-core/src/components/Dropdown/DropdownItem.tsx
packages/react-core/src/components/OptionsMenu/__tests__/__snapshots__/OptionsMenu.test.tsx.snap
packages/react-core/src/components/Page/Page.tsx
packages/react-core/src/components/Page/__tests__/__snapshots__/Page.test.tsx.snap
packages/react-integration/demo-app-ts/src/components/demos/ButtonDemo/ButtonDemo.tsx

fix(page): make tabIndex optional

---

packages/react-core/src/components/Drawer/examples/Drawer.md

**What**: Closes #4053 
//cc @mcoker @tlabaj

fix(drawer): add aria-expanded to the toggle button

---

packages/react-core/src/components/Tabs/Tab.tsx
packages/react-core/src/components/Tabs/Tabs.tsx
packages/react-core/src/components/Tabs/__tests__/__snapshots__/Tabs.test.tsx.snap
packages/react-core/src/components/Tabs/examples/Tabs.md

feat(tabs): allow hiding tab buttons

---

packages/react-integration/cypress/integration/emptystate.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/EmptyStateDemo/EmptyStateDemo.tsx

Added xl empty state to demo app/integration tests since they were left out of original PR.
Fixes #3934.

docs(Empty State): Added xl empty state to demo app/tests

---

packages/react-integration/cypress/integration/tabdemo.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/TabsDemo/TabsDemo.tsx

chore(tabs): add integration test for showing/hiding tab button

---

packages/react-core/src/components/Tabs/TabButton.tsx
packages/react-core/src/components/Tabs/Tabs.tsx
packages/react-core/src/components/Tabs/__tests__/Generated/__snapshots__/TabButton.test.tsx.snap
packages/react-core/src/components/Tabs/__tests__/__snapshots__/TabButton.test.tsx.snap
packages/react-core/src/components/Tabs/__tests__/__snapshots__/Tabs.test.tsx.snap
packages/react-core/src/components/Tabs/examples/Tabs.md

fix(tabs): properly handle null Tab and TabContent

---

packages/react-core/src/components/ChipGroup/Chip.tsx
packages/react-core/src/components/ChipGroup/ChipGroupToolbarItem.tsx
packages/react-core/src/components/ChipGroup/__tests__/__snapshots__/Chip.test.tsx.snap

When component is given an id use this id instead of the random created one.

fix: use id over randomId

---

packages/react-core/src/demos/MasterDetailDemo.md

feat(MasterDetailDemo): Add Master Detail Demo

---

packages/react-docs/RELEASE-NOTES.md

Release notes 2020.06

---

packages/react-docs/RELEASE-NOTES.md

**What**: Update release notes from #4234

chore(docs): update release notes for core bump

---

packages/react-core/src/components/LoginPage/LoginFooterItem.tsx
packages/react-core/src/components/Nav/NavItem.tsx
packages/react-core/src/components/Pagination/Pagination.tsx

fix(cloneElement): update NavItem and LoginFooterItem

---

packages/react-catalog-view-extension/package.json
packages/react-charts/package.json
packages/react-core/package.json
packages/react-docs/package.json
packages/react-icons/package.json
packages/react-styles/package.json
packages/react-table/package.json
packages/react-tokens/package.json
yarn.lock

chore(packages): bump core to 4.10.20 for RC1

---

packages/react-core/src/components/Switch/Switch.tsx
packages/react-core/src/components/Switch/__tests__/__snapshots__/Switch.test.tsx.snap

**What**: While looking at #3992 I decided to give the Switch some love

chore(switch): cleanup nested ternary

---

packages/react-catalog-view-extension/package.json
packages/react-charts/package.json
packages/react-core/package.json
packages/react-docs/package.json
packages/react-icons/package.json
packages/react-styles/package.json
packages/react-table/package.json
packages/react-tokens/package.json
yarn.lock

feat(packages): bump core to 4.10.21

---

packages/react-docs/package.json
packages/react-topology/package.json
packages/react-virtualized-extension/package.json
scripts/promote.js
yarn.lock

**What**: Fixes build in patternfly-org. Also bump the theme.
**Additional issues**: Also fix promote script to use prerelease versions since we're still prereleasing.

fix(topology): make required packages normal deps

---

packages/react-core/src/components/Select/Select.tsx
packages/react-core/src/components/Select/SelectOption.tsx
packages/react-core/src/components/Select/__tests__/__snapshots__/Select.test.tsx.snap
packages/react-core/src/components/Select/examples/Select.md

**What**: Closes #4263
**Additional issues**: typeahead select options are missing a class to get highlighting while using arrow keys, issue TBD

feat(Select): fix console warnings

---

packages/react-catalog-view-extension/package.json
packages/react-charts/package.json
packages/react-core/package.json
packages/react-core/src/components/Select/SelectOption.tsx
packages/react-docs/package.json
packages/react-icons/package.json
packages/react-styles/package.json
packages/react-table/package.json
packages/react-tokens/package.json
yarn.lock

Bump core version to 4.10.28 & fix select highlighting

---

packages/react-core/src/components/Progress/Progress.tsx
packages/react-core/src/components/Progress/ProgressBar.tsx
packages/react-core/src/components/Progress/ProgressContainer.tsx
packages/react-core/src/components/Progress/__tests__/Generated/__snapshots__/Progress.test.tsx.snap
packages/react-core/src/components/Progress/__tests__/Generated/__snapshots__/ProgressContainer.test.tsx.snap
packages/react-core/src/components/Progress/__tests__/__snapshots__/Progress.test.tsx.snap

**What**: Closes #3423
Also addresses https://github.com/patternfly/patternfly/issues/2539 on the react side

fix(Progress): Update to match core and fix accessibility

---

packages/react-core/src/helpers/util.ts

fix(util): 3xl and 4xl breakpoint modifiers

---

.circleci/upload-preview.js

**What**: v3 branch should upload to https://patternfly-react-v3.surge.sh

fix(surge): use patternfly-react-v3.surge.sh

---

packages/react-table/src/components/Table/ActionsColumn.tsx
packages/react-table/src/components/Table/BodyCell.tsx
packages/react-table/src/components/Table/CollapseColumn.tsx
packages/react-table/src/components/Table/EditColumn.tsx
packages/react-table/src/components/Table/EditableTextCell.tsx
packages/react-table/src/components/Table/HeaderCell.tsx
packages/react-table/src/components/Table/RowWrapper.tsx
packages/react-table/src/components/Table/Table.tsx
packages/react-table/src/components/Table/TableText.tsx

**What**:
Similiar to https://github.com/patternfly/patternfly-react/pull/4284, but opened to master branch.

fix(Table): update imports to direct imports for react table [v4]

---

packages/react-table/src/components/Table/Table.md
packages/react-table/src/components/Table/Table.tsx
packages/react-table/src/components/Table/utils/decorators/selectable.tsx

feat(table): support row checkbox disable

---

packages/react-core/src/components/InputGroup/examples/InputGroup.md

chore(InputGroup): add plain button example

---

packages/react-core/src/components/Form/examples/Form.md
packages/react-integration/demo-app-ts/src/components/demos/FormDemo/FormDemo.tsx

feat(Form): remove semicolons from docs

---

packages/react-icons/package.json
packages/react-icons/scripts/writeIcons.js
packages/react-icons/src/createIcon.tsx
packages/react-icons/tsconfig.json

fix(icons): use star import

---

packages/react-catalog-view-extension/package.json
packages/react-charts/package.json
packages/react-core/package.json
packages/react-docs/package.json
packages/react-icons/package.json
packages/react-styles/package.json
packages/react-table/package.json
packages/react-tokens/package.json
yarn.lock

**What**: Last bump for the big release!

bump core to 4.10.30

---

packages/react-core/src/components/Dropdown/DropdownToggle.tsx

**What**: Closes https://github.com/patternfly/patternfly-react/issues/4346

fix split button styling

---

packages/react-docs/RELEASE-NOTES.md

**What**: I forgot bumping core for its release notes would bump all React packages too

update versions from core bump

---

packages/react-core/src/components/Select/Select.tsx
packages/react-core/src/components/Select/selectConstants.tsx

fix(Select): fix panel issue

---

packages/react-core/src/components/Select/Select.tsx
packages/react-core/src/components/Select/__tests__/__snapshots__/Select.test.tsx.snap

**What**: Closes #4085  @redallen Please check.

fix(Select): fix filter clear button accessibility issue

---

packages/react-docs/gatsby-config.js
packages/react-docs/package.json
yarn.lock

fix(docs): remove footer

---

packages/react-core/src/components/Breadcrumb/BreadcrumbItem.tsx
packages/react-core/src/components/Breadcrumb/__tests__/BreadcrumbItem.test.tsx
packages/react-core/src/components/Breadcrumb/__tests__/__snapshots__/BreadcrumbItem.test.tsx.snap

**What**: Closes #4287 
~~Note that target branch is `v3`, let me know if should rebase or create other PR for master.~~

fix(BreadcrumbItem) Fixes console.warn when using a component 

---

packages/react-table/src/components/Table/BodyCell.tsx

**What**: Closes #4260 
Preview: https://patternfly-react-pr-4307.surge.sh/documentation/react/components/table/compact-expandable

chore(Table): remove data-label from expanded rows

---

packages/react-core/src/components/OverflowMenu/OverflowMenuDropdownItem.tsx

**What**: Now it will auto focus on the first item when pressing enter on the Kebab Dropdown in Overflow menu. Closes #3767

fix(OverflowMenu): fix accessibility issue on KebabToggle button

---

packages/react-catalog-view-extension/package.json
packages/react-charts/package.json
packages/react-core/package.json
packages/react-icons/package.json
packages/react-inline-edit-extension/package.json
packages/react-table/package.json
packages/react-tokens/package.json
packages/react-topology/package.json
packages/react-virtualized-extension/package.json
scripts/promote.js

Commit to having prereleases from master. Depends on #4354

chore(npm): publish to prerelease tag

---

packages/react-core/src/components/Nav/NavExpandable.tsx
packages/react-core/src/components/Nav/__tests__/__snapshots__/Nav.test.tsx.snap
packages/react-docs/gatsby-config.js

fix(NavExpandable): add style.modifiers.expandable

---

packages/react-core/src/components/Breadcrumb/Breadcrumb.tsx
packages/react-core/src/components/Breadcrumb/BreadcrumbHeading.tsx
packages/react-core/src/components/Breadcrumb/BreadcrumbItem.tsx
packages/react-core/src/components/Breadcrumb/__tests__/Generated/__snapshots__/BreadcrumbItem.test.tsx.snap
packages/react-core/src/components/Breadcrumb/__tests__/__snapshots__/Breadcrumb.test.tsx.snap
packages/react-core/src/components/Breadcrumb/__tests__/__snapshots__/BreadcrumbItem.test.tsx.snap
packages/react-core/src/components/Page/__tests__/__snapshots__/Page.test.tsx.snap
packages/react-docs/gatsby-config.js

**What**: Closes #4367
**Additional issues**: With this approach we should deprecate `isActive` and set the prop on the last element of `<Breadcrumb>`.

fix(breadcrumb): temp fix for spacing

---

packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/Connectors.tsx
packages/react-styles/src/css/components/Topology/topology-components.css
packages/react-topology/src/behavior/withCreateConnector.tsx
packages/react-topology/src/components/DefaultCreateConnector.tsx

For instances where some computation may be necessary, allow a promise to be returned to the create connector callback.

improvement(Topology): Allows a promise to be returned by the create connector callback

---

packages/react-core/src/components/Form/ActionGroup.tsx
packages/react-core/src/components/Form/__tests__/Generated/__snapshots__/ActionGroup.test.tsx.snap
packages/react-core/src/components/Form/__tests__/__snapshots__/ActionGroup.test.tsx.snap

fix(Form): Added .pf-c-form__group-control wrapper to .pf-c-form__actions

---

packages/react-catalog-view-extension/package.json
packages/react-charts/package.json
packages/react-core/package.json
packages/react-core/src/components/Divider/Divider.md
packages/react-core/src/components/Divider/Divider.tsx
packages/react-core/src/helpers/util.ts
packages/react-docs/package.json
packages/react-icons/package.json
packages/react-integration/cypress/integration/dividerinsetdemo.spec.ts
packages/react-integration/demo-app-ts/src/Demos.ts
packages/react-integration/demo-app-ts/src/components/demos/DividerDemo/DividerInsetDemo.tsx
packages/react-integration/demo-app-ts/src/components/demos/index.ts
packages/react-styles/package.json
packages/react-table/package.json
packages/react-tokens/package.json
yarn.lock

feat(Divider): Add support for insets to the Divider

---

packages/react-core/src/components/Banner/Banner.tsx
packages/react-core/src/components/Banner/__tests__/Banner.test.tsx
packages/react-core/src/components/Banner/__tests__/__snapshots__/Banner.test.tsx.snap
packages/react-core/src/components/Banner/examples/Banner.md
packages/react-core/src/components/Banner/index.ts
packages/react-core/src/components/index.ts
packages/react-core/src/demos/PageLayout/examples/BannerDemo.md
packages/react-integration/cypress/integration/banner.spec.ts
packages/react-integration/demo-app-ts/src/Demos.ts
packages/react-integration/demo-app-ts/src/components/demos/BannerDemo/BannerDemo.tsx
packages/react-integration/demo-app-ts/src/components/demos/index.ts

**What**: Closes #4244 
Also includes core version bump to 4.12.0 for banner styling

feat(Banner): add banner component

---

packages/react-core/src/components/ApplicationLauncher/ApplicationLauncher.tsx
packages/react-core/src/components/ApplicationLauncher/__tests__/__snapshots__/ApplicationLauncher.test.tsx.snap
packages/react-core/src/components/ApplicationLauncher/examples/ApplicationLauncher.md
packages/react-core/src/components/ContextSelector/ContextSelector.tsx
packages/react-core/src/components/Dropdown/DropdownWithContext.tsx
packages/react-core/src/components/Dropdown/examples/Dropdown.md
packages/react-core/src/components/OptionsMenu/OptionsMenu.tsx
packages/react-core/src/components/OptionsMenu/examples/OptionsMenu.md
packages/react-core/src/components/Select/Select.tsx
packages/react-core/src/helpers/Popper/Popper.tsx

**What**: Towards https://github.com/patternfly/patternfly-react/issues/4364
Makes `menuAppendTo` prop available in:

menuAppendTo prop in several more components

---

packages/react-core/src/components/Banner/examples/Banner.md

feat(Banner): add beta flag to docs

---

packages/react-catalog-view-extension/package.json
packages/react-charts/package.json
packages/react-core/package.json
packages/react-docs/package.json
packages/react-icons/package.json
packages/react-styles/package.json
packages/react-table/package.json
packages/react-tokens/package.json
yarn.lock

Core bump to update their docs

chore(docs): bump core to 4.16.7

---

packages/react-docs/RELEASE-NOTES.md

chore(release notes): Release notes for  2020.08

---

packages/react-core/src/components/Alert/AlertActionCloseButton.tsx

**What**: Closes #4415 
//cc @redallen @PanSpagetka

fix(alert): add display name to the close action button

---

packages/react-core/src/components/Button/Button.tsx
packages/react-core/src/components/Button/__tests__/Button.test.tsx
packages/react-core/src/components/Button/__tests__/__snapshots__/Button.test.tsx.snap
packages/react-core/src/components/Button/examples/Button.md
packages/react-integration/cypress/integration/button.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/ButtonDemo/ButtonDemo.tsx

**What**: Closes #4411 
//cc @mcoker

feat(button): add support to small variation

---

packages/react-docs/package.json
packages/react-table/src/components/Table/Table.md
yarn.lock

**What**: Closes #4256.
**Additional issues**: https://github.com/patternfly/patternfly-org/pull/1895

feat(table): publishes prop type interfaces in docs

---

packages/react-core/src/components/Button/__tests__/__snapshots__/Button.test.tsx.snap
packages/react-core/src/components/Select/SelectMenu.tsx
packages/react-core/src/components/Select/__tests__/Select.test.tsx
packages/react-core/src/components/Select/__tests__/__snapshots__/Select.test.tsx.snap
packages/react-core/src/components/Select/examples/Select.md

also updated a test that had an old prop
**What**: Closes #3899

feat(Select): add logic to handle SelectOptionObject in comparisons

---

packages/react-core/src/components/Toolbar/examples/Toolbar.md
packages/react-core/src/demos/CardView/examples/CardView.md

align prop doesn't exist on ToolbarItem. It's alignment prop

Fix(ToolBar): use alignment prop instead of align in ToolbarItem

---

packages/react-core/src/components/Nav/examples/Nav.md
packages/react-core/src/components/Page/examples/Page.md
packages/react-core/src/demos/CardView/examples/CardView.md
packages/react-core/src/demos/MasterDetailDemo.md
packages/react-core/src/demos/PageLayout/examples/BannerDemo.md
packages/react-core/src/demos/PageLayout/examples/PageLayout.md
packages/react-core/src/demos/StickyHeaderTable.md

**What**: Closes #4470 
Removed `theme="dark"` from PageSidebar and Nav docs, and usages of these components in other docs, as the default value is now `dark`.

docs(misc): remove theme="dark" from docs

---

packages/react-catalog-view-extension/src/components/CatalogTile/__snapshots__/CatalogTile.test.tsx.snap
packages/react-core/src/components/Card/Card.tsx
packages/react-core/src/components/Card/__tests__/Generated/__snapshots__/Card.test.tsx.snap
packages/react-core/src/components/Card/__tests__/__snapshots__/Card.test.tsx.snap
packages/react-core/src/components/Card/examples/Card.md

Adds OUIA attrs for Card component

Added Card OUIA attrs

---

packages/react-styles/scripts/generateClassMaps.js

fix(windows): fix build on windows

---

packages/react-core/src/components/DataList/DataListAction.tsx
packages/react-core/src/components/DataList/__tests__/DataList.test.tsx
packages/react-core/src/components/DataList/__tests__/__snapshots__/DataList.test.tsx.snap
packages/react-core/src/components/DataList/examples/DataList.md
packages/react-integration/cypress/integration/datalist.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/DataListDemo/DataListDemo.tsx

**What**: Closes #3860
Note: I opened an issue to clean up the unused functions and state in DataListAction component.

feat(DataList): Add support for action containers in DataList

---

packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx
packages/react-core/src/components/ExpandableSection/examples/ExpandableSection.md
packages/react-integration/demo-app-ts/src/components/demos/ExpandableSectionDemo/ExpandableSectionDemo.tsx

**What**: Closes #4412 
//cc @christianvogt

fix(expandable-section): pass expandable value to onToggle

---

packages/react-core/src/components/Select/Select.tsx

fix(select): option with description on active display only value

---

packages/react-catalog-view-extension/package.json
packages/react-charts/package.json
packages/react-core/package.json
packages/react-docs/package.json
packages/react-icons/package.json
packages/react-styles/package.json
packages/react-table/package.json
packages/react-tokens/package.json
yarn.lock

bump core version to 4.23.1

---

packages/react-core/src/components/Toolbar/ToolbarContent.tsx
packages/react-core/src/components/Toolbar/ToolbarGroup.tsx
packages/react-core/src/components/Toolbar/ToolbarItem.tsx
packages/react-core/src/components/Toolbar/ToolbarToggleGroup.tsx

Reverts patternfly/patternfly-react#4555
This was merged by mistake and needs some follow up work

Revert "fix(Toolbar*): change spelling of visiblity prop"

---

packages/react-docs/RELEASE-NOTES.md

chore(docs): 2020.09 release notes

---

packages/react-docs/RELEASE-NOTES.md

docs(chore):Fix sentence case in 2020.09 notes

---

packages/react-core/src/components/ChipGroup/ChipGroup.tsx

**What**: Closes #4522 
**Additional issues**: https://github.com/patternfly/patternfly/pull/3249

feat(ChipGroup): changes TimesIcon to TimesCircleIcon

---

packages/react-core/src/components/Select/Select.tsx

fix #4509
**What**: Closes #4509

fix(Select): use width prop in select

---

packages/react-core/src/components/Select/SelectMenu.tsx

Patch for https://github.com/patternfly/patternfly-react/issues/4602
Didn't notice any existing issues.

Fix TypeError on undefined valueToCheck.toString

---

packages/react-core/src/demos/BulkSelectTable.md
packages/react-core/src/demos/FilterTableDemo.md
packages/react-core/src/demos/PageLayout/examples/BannerDemo.md
packages/react-core/src/demos/StickyHeaderTable.md
packages/react-core/src/demos/TableColumnManagementDemo.md
packages/react-core/src/demos/TableEmptyStatesDemo.md

fix(demos): fix demo headers and imports

---

packages/react-core/src/components/Nav/NavExpandable.tsx
packages/react-core/src/components/Nav/__tests__/__snapshots__/Nav.test.tsx.snap
packages/react-integration/demo-app-ts/src/components/demos/NavDemo/NavDemo.tsx
yarn.lock

**What**: Closes #4377.
**Additional issues**: Extends https://github.com/patternfly/patternfly/pull/3250 and includes version bump to pull in those  CSS changes.

fix(NavExpandable): converts nav expandable to button

---

packages/react-catalog-view-extension/package.json
packages/react-charts/package.json
packages/react-core/package.json
packages/react-docs/package.json
packages/react-icons/package.json
packages/react-styles/package.json
packages/react-table/package.json
packages/react-tokens/package.json
yarn.lock

**What**: Need this bump for react-docs to pull in the correct version for patternfly-org

bump core to 4.24.3

---

packages/react-core/src/components/ChipGroup/Chip.tsx

**What**: Closes #4606
- conditionally add type to the overflow chip button

fix(ChipGroup): Add type button to overflow chip button

---

packages/react-core/src/components/OverflowMenu/OverflowMenuDropdownItem.tsx

**What**: Closes #4372 
//cc @jschuler

fix(overflowmenu-dropdown-item): allow to pass dropdown item props

---

packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx

**What**: Closes #4413 
//cc @christianvogt

fix(expandable-section): make children optional

---

packages/react-charts/src/components/ChartLegend/examples/ChartLegend.md
packages/react-charts/src/components/ChartScatter/examples/ChartScatter.md
packages/react-charts/src/components/ChartStack/examples/ChartStack.md
packages/react-charts/src/components/ChartTooltip/examples/ChartTooltip.md

**What**: Fixes chart imports for org refactor.

docs(charts): update chart imports

---

packages/react-tokens/scripts/writeTokens.js

fix(react-tokens): fix .d.ts typo

---

packages/react-tokens/scripts/writeTokens.js
packages/react-tokens/tests/react-tokens.test.js

**What**: Fixes https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_console/6252/pull-ci-openshift-console-master-frontend/1292998960541077504 and adds a test for it.
**Additional issues**: Fix regression from #4572

fix(react-tokens): output to correct cjs index file

---

packages/react-catalog-view-extension/package.json
packages/react-charts/package.json
packages/react-core/package.json
packages/react-core/src/components/DescriptionList/examples/DescriptionList.md
packages/react-docs/package.json
packages/react-icons/package.json
packages/react-styles/package.json
packages/react-table/package.json
packages/react-tokens/package.json

**What**: Closes #4692 
Fixes:
- change Description List and Inline Grid to sentence case
- bumps Core to 4.31.5

Fix: sentence case Description List & bump Core

---

packages/react-docs/RELEASE-NOTES.md

**What**: Closes #4694 
Updates release date to 8/17/2020, updates versions to latest versions

updated release notes date and versions

---

packages/react-core/src/components/Tabs/Tabs.tsx
packages/react-core/src/components/Tabs/__tests__/Generated/__snapshots__/Tabs.test.tsx.snap
packages/react-integration/cypress/integration/tabdemo.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/TabsDemo/TabsDemo.tsx

fix(tabs): add classNames to tab

---

packages/react-core/src/demos/PrimaryDetailDemo.md

**What:** Closes #4611 
To be more inclusive we want to replace Master detail with Primary-detail. To fix this, I removed the Master Detail demo and replaced it with an equivalent demo called Primary-detail.

fix(demo): rename master detail demo to primary-detail

---

packages/react-core/src/components/Page/Page.tsx
packages/react-core/src/components/Page/PageSection.tsx
packages/react-core/src/components/Page/__tests__/PageSection.test.tsx
packages/react-core/src/components/Page/__tests__/__snapshots__/Page.test.tsx.snap
packages/react-core/src/components/Page/__tests__/__snapshots__/PageSection.test.tsx.snap
packages/react-integration/demo-app-ts/src/components/demos/PageDemo/PageDemo.tsx

**What**: Closes #4656
@mcoker I couldn't find any use of `.pf-c-page__main-wizard`, where should I be adding the limit flag for this? Also, is my edit of the breadcrumb correct with the placement of the `div.pf-c-page__main-body`?

feat(Page): add width limit

---

packages/react-core/src/components/Label/Label.tsx
packages/react-core/src/components/Label/__tests__/Label.test.tsx
packages/react-core/src/components/Label/__tests__/__snapshots__/Label.test.tsx.snap
packages/react-core/src/components/Label/examples/Label.md
packages/react-integration/cypress/integration/label.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/LabelDemo/LabelDemo.tsx

**What**: Closes #4660
Looking for feedback on the prop name, is `isTruncated` clear or would something else like `noWrap` or `noOverflow` be better?

feat(Label): add no overflow prop

---

packages/react-core/src/components/Alert/Alert.tsx
packages/react-core/src/components/Alert/__tests__/Alert.test.tsx
packages/react-core/src/components/Alert/examples/Alert.md
packages/react-core/src/components/NotificationDrawer/NotificationDrawerGroup.tsx
packages/react-core/src/components/NotificationDrawer/NotificationDrawerListItemHeader.tsx
packages/react-core/src/components/NotificationDrawer/__tests__/Generated/__snapshots__/NotificationDrawerGroup.test.tsx.snap
packages/react-core/src/components/NotificationDrawer/__tests__/NotificationDrawerListItemHeader.test.tsx
packages/react-core/src/components/NotificationDrawer/__tests__/__snapshots__/NotificationDrawerGroup.test.tsx.snap
packages/react-core/src/components/NotificationDrawer/examples/NotificationDrawer.md

**What**: Closes #4357 
- Do not merge till `@patternfly/patternfly` is updated to `4.10.33`
//cc @mcoker

feat(alert,notificationdrawer): add support to truncate title

---

packages/react-core/src/components/Modal/Modal.tsx
packages/react-core/src/components/Modal/ModalBox.tsx
packages/react-core/src/components/Modal/ModalContent.tsx
packages/react-core/src/components/Modal/examples/Modal.md
packages/react-integration/cypress/integration/modal.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/ModalDemo/ModalDemo.tsx

**What**: Closes #4526 
//cc @mcoker

feat(modal): add medium variant

---

packages/react-core/src/components/Tile/Tile.tsx
packages/react-core/src/components/Tile/__tests__/Tile.test.tsx
packages/react-core/src/components/Tile/__tests__/__snapshots__/Tile.test.tsx.snap
packages/react-core/src/components/Tile/examples/Tile.md
packages/react-core/src/components/Tile/index.ts
packages/react-core/src/components/index.ts
packages/react-core/src/demos/TileDemo.md
packages/react-integration/cypress/integration/tile.spec.ts
packages/react-integration/demo-app-ts/src/Demos.ts
packages/react-integration/demo-app-ts/src/components/demos/TileDemo/TileDemo.tsx
packages/react-integration/demo-app-ts/src/components/demos/index.ts

feat(Tile): add tile component

---

packages/react-core/src/components/ToggleGroup/ToggleGroup.tsx
packages/react-core/src/components/ToggleGroup/ToggleGroupContext.tsx
packages/react-core/src/components/ToggleGroup/ToggleGroupItem.tsx
packages/react-core/src/components/ToggleGroup/__tests__/ToggleGroup.test.tsx
packages/react-core/src/components/ToggleGroup/__tests__/__snapshots__/ToggleGroup.test.tsx.snap
packages/react-core/src/components/ToggleGroup/examples/ToggleGroup.md
packages/react-core/src/components/ToggleGroup/examples/toggleGroup.css
packages/react-core/src/components/ToggleGroup/index.ts
packages/react-core/src/components/index.ts
packages/react-integration/cypress/integration/togglegroup.spec.ts
packages/react-integration/demo-app-ts/src/Demos.ts
packages/react-integration/demo-app-ts/src/components/demos/ToggleGroupDemo/ToggleGroupDemo.tsx
packages/react-integration/demo-app-ts/src/components/demos/index.ts

Closes #4655 
Preview: https://patternfly-react-pr-4702.surge.sh/documentation/react/components/togglegroup

feat(ToggleGroup): add new toggle group component

---

packages/react-core/src/components/Page/Page.tsx
packages/react-core/src/components/Page/examples/Page.md
packages/react-core/src/demos/Page/Page.md
packages/react-integration/cypress/integration/nav.spec.ts
packages/react-integration/cypress/integration/pagebreadcrumbandtertiarynav.ts
packages/react-integration/demo-app-ts/src/Demos.ts
packages/react-integration/demo-app-ts/src/components/demos/NavDemo/NavDemo.tsx
packages/react-integration/demo-app-ts/src/components/demos/PageDemo/PageBreadcrumbAndTertiaryNavDemo.tsx
packages/react-integration/demo-app-ts/src/components/demos/index.ts
yarn.lock

fix(Page): add missing tertiary nav demo, integration, and cypress test

---

packages/react-docs/RELEASE-NOTES.md

chore(docs): add 2020.11 release notes

---

packages/react-core/src/components/ChipGroup/Chip.tsx
packages/react-core/src/components/ChipGroup/ChipGroup.tsx
packages/react-core/src/components/ChipGroup/__tests__/ChipGroup.test.tsx
packages/react-core/src/components/ChipGroup/__tests__/__snapshots__/Chip.test.tsx.snap
packages/react-core/src/components/ChipGroup/__tests__/__snapshots__/ChipGroup.test.tsx.snap
packages/react-core/src/components/Select/__tests__/__snapshots__/Select.test.tsx.snap

**What**: Closes #4748
OUIA props have been added into ChipGroup

Added OUIA props into ChipGroup

---

packages/react-core/src/components/Tabs/TabButton.tsx
packages/react-core/src/components/Tabs/TabContent.tsx
packages/react-core/src/components/Tabs/Tabs.tsx
packages/react-core/src/components/Tabs/__tests__/Generated/__snapshots__/TabButton.test.tsx.snap
packages/react-core/src/components/Tabs/__tests__/Tab.test.tsx
packages/react-core/src/components/Tabs/__tests__/TabButton.test.tsx
packages/react-core/src/components/Tabs/__tests__/__snapshots__/Tab.test.tsx.snap
packages/react-core/src/components/Tabs/__tests__/__snapshots__/TabButton.test.tsx.snap
packages/react-core/src/components/Tabs/__tests__/__snapshots__/Tabs.test.tsx.snap

This PR adds OUIA support for TabButton and TabContent.
**What**: Closes #4742

TabButton and TabContent with OUIA

---

packages/react-docs/RELEASE-NOTES.md

chore(release notes):Fixed release notes

---

packages/react-core/src/components/Tooltip/examples/Tooltip.md

**What**: Closes #4786
**Additional issues**:#4365 (related issue)

Add aria-labels to tooltip example checkboxes

---

packages/react-core/src/components/Nav/examples/Nav.md

**What**: Closes #4784
**Additional issues**:#4365 (related issue)

Add href to nav examples

---

packages/react-core/src/components/Card/CardTitle.tsx
packages/react-core/src/components/Card/examples/Card.md
packages/react-integration/cypress/integration/card.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/CardDemo/CardDemo.tsx

feat(Card): add ability to customize card title and support heading element

---

packages/react-core/src/components/Toolbar/Toolbar.tsx
packages/react-core/src/components/Toolbar/__tests__/ToolbarToggleGroup.test.tsx
packages/react-core/src/components/Toolbar/__tests__/__snapshots__/ToolbarToggleGroup.test.tsx.snap
packages/react-core/src/components/Toolbar/examples/Toolbar.md
packages/react-integration/cypress/integration/toolbar.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/ToolbarDemo/ToolbarDemo.tsx

feat(Toolbar): add insets property

---

packages/react-core/src/components/Drawer/Drawer.tsx
packages/react-core/src/components/Drawer/__tests__/Drawer.test.tsx
packages/react-core/src/components/Drawer/__tests__/__snapshots__/Drawer.test.tsx.snap
packages/react-core/src/components/Drawer/examples/Drawer.md
packages/react-integration/cypress/integration/drawer.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/DrawerDemo/DrawerDemo.tsx

feat(Drawer): add bottom panel variation

---

packages/react-core/src/components/Skeleton/Skeleton.tsx
packages/react-core/src/components/Skeleton/__tests__/Skeleton.test.tsx
packages/react-core/src/components/Skeleton/__tests__/__snapshots__/Skeleton.test.tsx.snap
packages/react-core/src/components/Skeleton/examples/Skeleton.md
packages/react-core/src/components/Skeleton/index.ts
packages/react-core/src/components/index.ts
packages/react-integration/cypress/integration/skeleton.spec.ts
packages/react-integration/demo-app-ts/src/Demos.ts
packages/react-integration/demo-app-ts/src/components/demos/SkeletonDemo/SkeletonDemo.tsx
packages/react-integration/demo-app-ts/src/components/demos/index.ts

feat(Skeleton): add skeleton component, examples, tests

---

packages/react-topology/src/Visualization.ts
packages/react-topology/src/behavior/useAnchor.tsx
packages/react-topology/src/behavior/useDndDrag.tsx
packages/react-topology/src/behavior/useDndManager.tsx
packages/react-topology/src/components/ElementWrapper.tsx

**What**: 
Fixes an issue where dragging nodes can cause issues if the model has been updated.
Unregisters drag event handlers appropriately.

fix(Topology): Wrap drag event handlers in actions

---

packages/react-core/src/components/Dropdown/DropdownToggleCheckbox.tsx
packages/react-core/src/components/Dropdown/__tests__/__snapshots__/DropdownToggleCheckbox.test.tsx.snap

**What**: Fixes warning in https://github.com/project-koku/koku-ui/blob/master/src/pages/details/components/dataToolbar/dataToolbar.tsx
**Additional issues**: Code contributed by @jschuler

fix(DropdownToggleCheckbox): indeterminate warning

---

packages/react-docs/RELEASE-NOTES.md

release notes 2020.12

---

packages/react-docs/RELEASE-NOTES.md

Chore: Added PR #4844 to release notes

---

packages/react-core/src/components/Nav/NavItem.tsx
packages/react-core/src/components/Nav/__tests__/Generated/__snapshots__/NavItem.test.tsx.snap
packages/react-core/src/components/Nav/__tests__/__snapshots__/Nav.test.tsx.snap

**What**: #4768
This PR makes NavItem OUIA compatible.

Added OUIA support into NavItem

---

packages/react-core/src/components/NotificationDrawer/NotificationDrawerListItem.tsx
packages/react-core/src/components/NotificationDrawer/__tests__/__snapshots__/NotificationDrawerListItem.test.tsx.snap
packages/react-core/src/components/NotificationDrawer/examples/NotificationDrawer.md
packages/react-integration/cypress/integration/notificationdrawerbasic.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/NotificationDrawerDemo/NotificationDrawerBasicDemo.tsx

**What**: Closes #4659 
//cc @mcoker

feat(notificationDrawer): add default variation to notification items

---

packages/react-core/src/demos/PrimaryDetail.md

Closes #4513 
**Additional issues**: https://github.com/patternfly/patternfly-react/issues/4807

fix(primary-detail-demo): fixed component padding

---

packages/react-core/src/components/Button/Button.tsx
packages/react-core/src/components/Button/__tests__/__snapshots__/Button.test.tsx.snap
packages/react-core/src/components/Button/examples/Button.md
packages/react-integration/cypress/integration/button.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/ButtonDemo/ButtonDemo.tsx

feat(react-core-button): support warning variant

---

packages/react-charts/src/components/ChartCursorTooltip/ChartCursorFlyout.tsx
packages/react-charts/src/components/ChartDonutUtilization/ChartDonutUtilization.tsx
packages/react-charts/src/components/ChartLabel/ChartLabel.tsx
packages/react-charts/src/components/ChartLegendTooltip/ChartLegendTooltipLabel.tsx
packages/react-charts/src/components/ChartPoint/path-helpers.ts
packages/react-charts/src/components/ChartThreshold/ChartThreshold.tsx
packages/react-charts/src/components/ChartUtils/chart-legend.ts
packages/react-charts/src/components/ChartUtils/chart-padding.ts
packages/react-charts/src/components/ChartUtils/chart-theme.ts
packages/react-table/src/components/Table/base/body-row.tsx
packages/react-table/src/components/Table/base/body.tsx
packages/react-table/src/components/Table/base/columns-are-equal.ts
packages/react-table/src/components/Table/base/evaluate-transforms.ts
packages/react-table/src/components/Table/base/merge-props.ts
packages/react-table/src/components/Table/base/resolve-row-key.ts
packages/react-virtualized-extension/src/components/Virtualized/VirtualizedTable.md

**What**: Closes #4750. Reduces bundle sizes up to 500kb.

fix(charts,table): replace or use exact lodash imports

---

packages/react-core/README.md
packages/react-core/src/components/Toolbar/examples/Toolbar.md
packages/react-docs/RELEASE-NOTES.md
packages/react-docs/src/pages/icons.js

**What**: Closes #4869. Closes #4868

docs(links): fix broken links

---

packages/react-core/src/components/Select/Select.tsx
packages/react-core/src/components/Select/examples/Select.md
packages/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectDemo.tsx

**What**: Closes #4766 
//cc @mturley

feat(select): pass chip group props on typeaheadmulti variant

---

packages/react-core/src/components/Button/Button.tsx
packages/react-core/src/components/Button/__tests__/Button.test.tsx
packages/react-core/src/components/Button/__tests__/__snapshots__/Button.test.tsx.snap
packages/react-core/src/components/Button/examples/Button.md
packages/react-integration/cypress/integration/button.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/ButtonDemo/ButtonDemo.tsx

feat(react-core-button): add isLoading and spinnerAriaValueText properties

---

packages/react-core/src/components/Tabs/TabContent.tsx
packages/react-core/src/components/Tabs/Tabs.tsx
packages/react-core/src/components/Tabs/__tests__/Generated/__snapshots__/Tabs.test.tsx.snap
packages/react-core/src/components/Tabs/__tests__/Tabs.test.tsx
packages/react-core/src/components/Tabs/__tests__/__snapshots__/Tabs.test.tsx.snap
packages/react-core/src/components/Tabs/examples/Tabs.md
packages/react-integration/cypress/integration/tabdemo.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/TabsDemo/TabsDemo.tsx

feat(react-core-tabs): add support for light scheme variant in Tabs && TabContent

---

packages/react-core/src/components/Select/Select.tsx
packages/react-core/src/components/Select/__tests__/__snapshots__/Select.test.tsx.snap

(and typeaheadMulti)
**What**: Closes #4886

Removes the clearBtn button when onClear is not specified for typeahead

---

packages/react-core/src/components/Select/Select.tsx

For Select chips, return the string value.

---

packages/react-core/src/components/Page/examples/Page.md

fix(page): replace hasNoPadding property in the documentation example

---

README.md

Removes a few outdated links from the  top level readme
**What**: Closes ##4920

chore(readme): remove out of date links from the readme

---

packages/react-core/src/components/LabelGroup/LabelGroup.tsx

**What**: Closes #4827
Needs a core bump to get correct class

feat(LabelGroup): add label group main div for categories

---

packages/react-topology/src/layouts/BaseLayout.ts
packages/react-topology/src/layouts/ForceLayout.ts
packages/react-topology/src/layouts/index.ts

**What**: Just need to fix the build. I'll ask @jeff-phillips-18 and fix more later if it's not okay.

fix(topology): fix exports

---

packages/react-core/src/components/DataList/DataList.tsx
packages/react-core/src/components/DataList/DataListItem.tsx
packages/react-core/src/components/DataList/__tests__/Generated/__snapshots__/DataList.test.tsx.snap
packages/react-core/src/components/DataList/__tests__/__snapshots__/DataList.test.tsx.snap

Fix(datalist): update aria of datalist

---

packages/react-integration/cypress/integration/tableselectable.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/TableDemo/TableSelectableDemo.tsx
packages/react-table/src/components/Table/EditableSelectInputCell.tsx
packages/react-table/src/components/Table/SelectColumn.tsx
packages/react-table/src/components/Table/Table.test.tsx
packages/react-table/src/components/Table/Table.tsx
packages/react-table/src/components/Table/examples/Table.md
packages/react-table/src/components/Table/utils/__snapshots__/transformers.test.tsx.snap
packages/react-table/src/components/Table/utils/decorators/selectable.tsx
packages/react-virtualized-extension/src/components/Virtualized/__snapshots__/VirtualizedTable.test.tsx.snap

    feat(table): added support for single row radio select

---

packages/react-core/src/components/DataList/DataList.tsx
packages/react-core/src/components/DataList/DataListCell.tsx
packages/react-core/src/components/DataList/DataListItemRow.tsx
packages/react-core/src/components/DataList/DataListText.tsx
packages/react-core/src/components/DataList/__tests__/DataList.test.tsx
packages/react-core/src/components/DataList/examples/DataList.md
packages/react-core/src/components/DataList/index.ts
packages/react-datetime/src/components/DatePicker/DatePicker.tsx
packages/react-integration/cypress/integration/datalist.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/DataListDemo/DataListDemo.tsx

feat(DataList): add support for text modifiers

---

packages/react-docs/patternfly-docs.source.js

**What**: Adds Extensions -> Catalog items back.

docs(catalog-view-extension): add back

---

packages/react-core/src/components/DataList/DataList.tsx
packages/react-core/src/components/DataList/DataListItem.tsx

**What**: Fixes type error in Openshift who relied on these being function components

fix(datalist): add ref to omit list

---

packages/react-core/src/components/Nav/examples/nav.css

docs(nav): fix selectors for dark background

---

packages/react-core/src/components/EmptyState/examples/EmptyState.md

**What**: Fixes duplicate example:

fix(empty-state): remove duplicate example, use title case

---

packages/react-docs/RELEASE-NOTES.md

Added release notes for 2020.13

---

packages/react-core/src/components/FileUpload/__tests__/__snapshots__/FileUploadField.test.tsx.snap
packages/react-core/src/components/TextArea/TextArea.tsx
packages/react-core/src/components/TextArea/__tests__/Generated/__snapshots__/TextArea.test.tsx.snap
packages/react-core/src/components/TextArea/__tests__/TextArea.test.tsx
packages/react-core/src/components/TextArea/__tests__/__snapshots__/TextArea.test.tsx.snap

feat(TextArea): support passing a ref

---

packages/react-catalog-view-extension/src/components/CatalogItemHeader/examples/catalogItemHeader.css
packages/react-catalog-view-extension/src/components/CatalogTile/examples/catalogTile.css
packages/react-catalog-view-extension/src/components/VerticalTabs/examples/verticalTab.css
packages/react-docs/patternfly-docs.source.js

**What**: Fixes slack report from @christianvogt:

fix(catalog-view-extension): example css selectors

---

.github/renovate.json
packages/react-docs/package.json
yarn.lock

**What**: Bump theme and setup rennovate to bump theme in the future.
**Additional issues**: Has TOC fixes per @jschuler 's request

chore(docs): bump theme

---

packages/react-core/src/components/Tabs/Tab.tsx

fix(tab): Tab component properties don't show in the docs

---

packages/react-core/src/components/Wizard/WizardContext.ts

feat(Wizard): Making WizardContext exported

---

packages/react-core/src/components/Nav/Nav.tsx
packages/react-core/src/components/Nav/__tests__/Generated/__snapshots__/Nav.test.tsx.snap
packages/react-core/src/components/Nav/__tests__/__snapshots__/Nav.test.tsx.snap

The condition was wrong.
Fixes #4507

fix(nav): Fix ariaLabel not getting applied

---

packages/react-core/src/components/ContextSelector/__tests__/__snapshots__/ContextSelector.test.tsx.snap
packages/react-core/src/components/FileUpload/__tests__/__snapshots__/FileUploadField.test.tsx.snap
packages/react-core/src/components/InputGroup/InputGroup.tsx
packages/react-core/src/components/LoginPage/__tests__/Generated/__snapshots__/LoginForm.test.tsx.snap
packages/react-core/src/components/LoginPage/__tests__/__snapshots__/LoginForm.test.tsx.snap
packages/react-core/src/components/TextArea/TextArea.tsx
packages/react-core/src/components/TextArea/__tests__/__snapshots__/TextArea.test.tsx.snap
packages/react-core/src/components/TextInput/TextInput.tsx
packages/react-core/src/components/TextInput/__tests__/__snapshots__/TextInput.test.tsx.snap
packages/react-inline-edit-extension/src/components/TableTextInput/__snapshots__/TableTextInput.test.js.snap
packages/react-table/src/demos/Table.md
packages/react-virtualized-extension/src/components/Virtualized/examples/VirtualizedTable.md

**What**: Fixes errors when copy/pasting FilterableTableDemo

fix(inputgroup): allow string children

---

packages/react-topology/src/behavior/useDndDrag.tsx
packages/react-topology/src/behavior/useDndManager.tsx
packages/react-topology/src/behavior/useDragNode.tsx

**What**:
Fixes an issue where nodes that are recreated during a drag operation would cancel the drag operation.
https://issues.redhat.com/browse/ODC-4979

fix(topology): Fix for issue when dragging nodes that get re-created

---

packages/react-topology/src/elements/BaseGraph.ts
packages/react-topology/src/types.ts

**What**:
Adds an event notification when the graph position, scale, or scale extents change. This event is necessary to allow saving/restoring of graph layout.
cc @christianvogt

fix(topology): Add notification on graph position/scale/extent changes

---

packages/react-core/src/components/LabelGroup/LabelGroup.tsx

fix(LabelGroup): should always contain pf-c-label-group__main

---

packages/react-core/src/components/Modal/Modal.tsx
packages/react-core/src/components/Modal/ModalBoxTitle.tsx
packages/react-core/src/components/Modal/ModalContent.tsx
packages/react-core/src/components/Modal/__tests__/Generated/__snapshots__/Modal.test.tsx.snap
packages/react-core/src/components/Modal/__tests__/ModalBox.test.tsx
packages/react-core/src/components/Modal/__tests__/__snapshots__/ModalBox.test.tsx.snap
packages/react-core/src/components/Modal/__tests__/__snapshots__/ModalContent.test.tsx.snap
packages/react-core/src/components/Modal/examples/Modal.md
packages/react-core/src/components/Wizard/__tests__/Generated/__snapshots__/Wizard.test.tsx.snap
packages/react-integration/demo-app-ts/src/components/demos/ModalDemo/ModalDemo.tsx

feature(Modalbox): add alert variation

---

packages/react-core/src/components/Label/Label.tsx
packages/react-core/src/components/Label/examples/Label.md
packages/react-integration/cypress/integration/label.spec.ts
packages/react-integration/demo-app-ts/src/common/FakeRouterLink.tsx
packages/react-integration/demo-app-ts/src/components/demos/LabelDemo/LabelDemo.tsx

fix(Label): Added tooltip to truncated text

---

packages/react-core/src/components/Form/FormSection.tsx
packages/react-core/src/components/Form/__tests__/FormSection.test.tsx
packages/react-core/src/components/Form/__tests__/__snapshots__/FormSection.test.tsx.snap
packages/react-core/src/components/Form/examples/Form.md
packages/react-core/src/components/Form/index.ts
packages/react-integration/demo-app-ts/src/components/demos/FormDemo/FormDemo.tsx

feat(FormSection): Add FormSection component

---

packages/react-core/src/components/EmptyState/EmptyState.tsx
packages/react-core/src/components/EmptyState/__tests__/EmptyState.test.tsx
packages/react-core/src/components/EmptyState/__tests__/__snapshots__/EmptyState.test.tsx.snap
packages/react-core/src/components/EmptyState/examples/EmptyState.md
packages/react-integration/cypress/integration/emptystate.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/EmptyStateDemo/EmptyStateDemo.tsx

feat(Empty state): Added extra small variation

---

packages/react-table/src/demos/Table.md

**What**: Closes https://github.com/patternfly/patternfly-react/issues/4943
https://patternfly-react-pr-5030.surge.sh/components/table/react-demos#expandcollapse-all

Table - expand/collapse all demo
