.babelrc
package.json

Don't ignore tests with babel, so it is possible to run them during
development. Ignore tests only during build.

Fix transpiling tests with Babel

---

.travis.yml
package-lock.json
src/Alert/Alert.stories.js
src/Button/Button.stories.js
src/DropdownKebab/DropdownKebab.stories.js
src/MenuItem/MenuItem.stories.js
storybook/decorators/storyTemplates.js

This is an alternative PR to https://github.com/patternfly/patternfly-react/pull/35 which introduces npm5's package-lock.json for dependencies management.
* Add package-lock.json to lock dependencies
* Change travis to use only nodejs v8 to ensure npm5
* fix prettier issues
Closes #33

feat(npm5): Manage dependencies using npm5

---

CONTRIBUTING.md

**What**: Adding statement about where CSS should live relative to component contributions.
**Why**: For extra clarity. Eventually, we should clarify how css would be added to the repo, but this is something we need to test out before we know how that should happen.

adding statement about CSS relative to contribution process

---

package-lock.json
package.json
src/ListView/ListView.stories.js
src/ListView/ListView.test.js
src/ListView/ListViewItem.js
src/ListView/ListViewRow.js
src/ListView/__mocks__/mockListItems.js
src/ListView/__snapshots__/ListView.test.js.snap
src/ListView/index.js
src/index.js
storybook/preview-head.html

**What**:
This change builds up on the ListView solution introduced by https://github.com/patternfly/patternfly-react/pull/32, makes it a bit more flexible and adds a list of base components which can be used as building blocks to implement custom ListViewItem component
**How**:
There are 3 main components:
ListView - a wrapper for ListViewItems
ListViewItem - handles the logic of expanding and general ListViewItem behavior
ListViewRow - Defines structure and contents of each ListViewItem
Note: ListView and ListViewItem could be used to implement List and ListItem components (https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/list-pf.html) in future as they basically implement the desired behavior. IMHO this matches the general PatternFly goal to merge these two content …

feat(listView): add ListView components

---

package.json

**What**:
PatternFly peer dependency is incorrectly specified, so it always fails.
**Why**:
**How**:
This changes fixes it so that peer dependency is met if installed patternfly is ^3.27.4

fix(dependencies): Fix PatternFly peer dependency version

---

src/ListView/index.js

**What**:
Removes leftover console.log statement from ListViewItem definition

fix(console): Remove leftover console.log statement

---

package-lock.json
package.json

**What**:
updates React/React DOM dependency, React Bootstrap dependency, and Storybook dependency for React 16

feat(dependencies): update to React 16 and Prettier 1.7

---

package.json
src/Alert/Alert.js
src/DropdownKebab/DropdownKebab.js
src/ToastNotification/TimedToastNotification.js
src/ToastNotification/ToastNotification.js
src/ToastNotification/ToastNotification.stories.js
src/ToastNotification/ToastNotification.test.js
src/ToastNotification/ToastNotificationList.js
src/ToastNotification/__snapshots__/ToastNotification.test.js.snap
src/common/Timer.js
src/common/constants.js
src/common/helpers.js
src/index.js

Closes #47
**What**:
* adds `ToastNotification` and `ToastNotificationList` React component and toast notification stories to Storybook.
* fixes some formatting generated by prettier and updates prettier to latest
* adds optional `dropdownClass` to `DropdownKebab` component
* adds `TimedToastNotification` stateful component for consumers using a timer component
Storybook:
https://rawgit.com/priley86/patternfly-react/toast-notification/index.html

feat(toastNotification): adds toast notification component

---

src/DropdownKebab/DropdownKebab.js

The PropTypes should support a number in addition to a string
just like the react-bootstrap repo does.
**What**: Fixing the prop-types to align with the `react-bootstrap` changes found [here](https://github.com/react-bootstrap/react-bootstrap/blob/502fe0044e5edef530f944953154a85e9daaebeb/src/Dropdown.js#L36).
**Why**: To support an integer as a valid id.
**How**: Updating the prop-types object to use `oneOfType`

Changes PropTypes on `id` to match react-bootstrap

---

src/Alert/Alert.js
src/ToastNotification/ToastNotification.js

#61
**What**: Adding mouse events to the `Alert` component
**Why**: to support apps adding their own mouse events to the `Alert` component
**How**: Changed the `Alert` component to a class and added the handlers.

feat(alert): Adding mouse events to alerts

---

src/Breadcrumb/Breadcrumb.js
src/Breadcrumb/Breadcrumb.stories.js
src/index.js

**What**:
Add the Breadcrumb component
**Why**:
To reduce the need to use `react-bootstrap` together with `patternfly-react`
**How**:
Exporting the Breadcrumb component from `react-bootstrap` as it is

feat(Breadcrumb): Breadcrumb component

---

src/OverlayTrigger/OverlayTrigger.js
src/Popover/Popover.js
src/Popover/Popover.stories.js
src/index.js

**What**:
This PR adds the PatternFly popover patterns. To be used to close #20 (Popover) once done.
Storybook: https://rawgit.com/dabeng/patternfly-react/popover-storybook/.out/index.html?knob-Label=Danger%20Will%20Robinson%21&knob-Popover%20Title=Popover&knob-Popover%20Content=%3Cstrong%3EHoly%20guacamole%21%3C%2Fstrong%3E%20Check%20this%20info.&knob-Placement=right&knob-Trigger=click&knob-Root%20Close=true&selectedKind=Popover&selectedStory=Popover&full=0&down=1&left=1&panelRight=0&downPanel=storybooks%2Fstorybook-addon-knobs
**How**:
Encapsulating react-bootstrap popover as a story of patternfly-react storybook.
@priley86 , please review.

feat(popover): add the pf popover

---

src/Tooltip/Tooltip.js
src/Tooltip/Tooltip.stories.js
src/index.js

**What**:
This PR adds the PatternFly tooltip patterns. To be used to close #19 (Tooltip) once done.
Storybook: https://rawgit.com/dabeng/patternfly-react/tooltip-storybook/.out/index.html?knob-Label=Danger%20Will%20Robinson%21&knob-Tooltip=%3Cstrong%3EHoly%20guacamole%21%3C%2Fstrong%3E%20Check%20this%20info.&knob-Placement=right&knob-Trigger=hover%20focus&knob-Root%20Close=false&selectedKind=Tooltip&selectedStory=Tooltip&full=0&down=1&left=1&panelRight=0&downPanel=storybooks%2Fstorybook-addon-knobs
**How**:
Encapsulating react-bootstrap tooltip as a story of patternfly-react storybook.
@priley86 , please review.

feat(tootip): add the pf tooltip

---

package-lock.json
package.json
src/test.env.js

**What**:
Fix the requestAnimationFrame warning when running tests
**Why**:
Because we are getting warnings when running tests:
```bash
console.error node_modules/fbjs/lib/warning.js:33
Warning: React depends on requestAnimationFrame. Make sure that you load a polyfill in older browsers. http://fb.me/react-polyfills
```
**How**:
Import `raf/polyfill` before running tests as suggested by
https://reactjs.org/docs/javascript-environment-requirements.html

test(polyfill): Fix the requestAnimationFrame warning when running tests

---

src/components/Grid/Clearfix.js
src/components/Grid/Col.js
src/components/Grid/Grid.js
src/components/Grid/Grid.stories.js
src/components/Grid/Row.js
src/components/Grid/index.js
src/components/ListView/ListView.stories.js
src/components/ListView/ListView.test.js
src/index.js
storybook/less/base.less
storybook/less/show-grid.less

Add the react-bootstrap grid components to patternfly-react (Grid, Row, Col, Clearfix)
**What**:
Add gird-system components from react-bootstrap:
- Grid
- Row
- Col
- Clearfix
**Why**:
To reduce the need to import `react-bootstrap` package
**How**:
Export those components from `react-bootstrap`
**Storybook**:
https://sharvit.github.io/patternfly-react/?knob-Label=Danger%20Will%20Robinson%21&knob-ShowClearfix=true&selectedKind=Grid&selectedStory=Basic%20Grid&full=0&down=1&left=1&panelRight=0&downPanel=storybooks%2Fstorybook-addon-knobs

feat(Grid): Add the react-bootstrap grid system

---

src/components/Modal/InnerComponents/CustomModalDialog.js
src/components/Modal/Modal.js
src/components/Modal/Modal.stories.js
src/components/Modal/__mocks__/mockAboutModalManager.js
src/components/Modal/__mocks__/mockModalManager.js
src/components/Modal/index.js
src/index.js

**What**:
This PR adds the PatternFly modal patterns. To be used in #69 (Wizard) once done.
Would like to merge #74 (list-group PR) first, and then rebase this..
Storybook:
https://rawgit.com/priley86/patternfly-react/modal-storybook/index.html?knob-Label=Danger%20Will%20Robinson%21&selectedKind=Modal%20Overlay&selectedStory=Basic%20Example&full=0&down=1&left=1&panelRight=0&downPanel=storybooks%2Fstorybook-addon-knobs
**How**:
To add custom content classes to the `modal-content` div and support the [About Modal](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/about-modal.html) pattern, a `CustomModalDialog` must be introduced. I've added an example of that here.
This seems to be a better alternative than [adding more custom …

feat(modal) - adds the pf modal patterns

---

src/components/Label/Label.js
src/components/Label/Label.stories.js
src/components/Label/index.js
src/index.js

**What**:
This PR adds the PatternFly label pattern. To be used to close #18 (Label) once done.
Storybook: https://rawgit.com/dabeng/patternfly-react/label-storybook/.out/index.html?knob-Label=Danger%20Will%20Robinson%21&selectedKind=Label&selectedStory=Label&full=0&down=1&left=1&panelRight=0&downPanel=storybooks%2Fstorybook-addon-knobs
**How**:
Providing a label story of patternfly-react storybook based on react-bootstrap label component.
@priley86 , please review.

feat(label): add the pf label component

---

src/components/Chart/BarChart.js
src/components/Chart/__snapshots__/BarChart.test.js.snap
src/components/Chart/constants.js

Currently we update `BarChart` props on the global  `getComposer` method in `constatants.js`. This can be done only for the `BarChart` component, in `BarChart.js`, like we do it for the `DonutChart`.

fix(chart): move char bar specific code to bar chart file

---

package-lock.json
src/components/Button/Button.js
src/components/Button/Button.stories.js
src/components/Button/ButtonGroup.js
src/components/Button/DropdownButton.js
src/components/Button/DropdownButton.test.js
src/components/Button/SplitButton.js
src/components/Button/SplitButton.test.js
src/components/Button/__snapshots__/DropdownButton.test.js.snap
src/components/Button/__snapshots__/SplitButton.test.js.snap
src/components/Button/index.js
src/components/Modal/Modal.js

Export DropdownButton and SplitButton from react-bootstrap
re #11
**What**:
* [DropdownButton](http://rawgit.com/sharvit/patternfly-react/storybook/dropdown-buttons/index.html?knob-Label=Danger%20Will%20Robinson%21&knob-Style=default&selectedKind=Button&selectedStory=DropdownButton&full=0&down=1&left=1&panelRight=0&downPanel=storybooks%2Fstorybook-addon-knobs)
* [SplitButton](http://rawgit.com/sharvit/patternfly-react/storybook/dropdown-buttons/index.html?knob-Label=Danger%20Will%20Robinson%21&knob-Style=default&selectedKind=Button&selectedStory=SplitButton&full=0&down=1&left=1&panelRight=0&downPanel=storybooks%2Fstorybook-addon-knobs)

feat(DropdownButton): DropdownButton and SplitButton components

---

src/components/ToastNotification/TimedToastNotification.js
src/components/ToastNotification/__snapshots__/ToastNotification.test.js.snap

**What**:
Fix an issue when using the `TimedToastNotification`
[**Link to Storybook**](http://rawgit.com/sharvit/patternfly-react/storybook/fix-toast-props/?knob-Label=Danger%20Will%20Robinson%21&knob-Header=Great%20job%21&knob-Message=By%20default%2C%20a%20toast%20notification%27s%20timer%20expires%20after%20eight%20seconds.&knob-Type=success&knob-Dismiss=false&knob-Menu=true&knob-Action=true&selectedKind=ToastNotification&selectedStory=Toast%20Notification%20List&full=0&down=1&left=1&panelRight=0&downPanel=storybooks%2Fstorybook-addon-knobs)
When I tried to use the `TimedToastNotification` i received this error:
```
VM4358 preview.bundle.js:69198 Warning: Received `false` for a non-boolean attribute `paused`.
If you want to write it to the DOM, pass a string instead: paused="false" or …
```

fix(TimedToastNotification): Stop passing down all props

---

package-lock.json
package.json

lock addon-info to 3.2.12 to temporarily address 3.2.18 issues
**What**:
There is currently a bug when resizing the addon panel:
This appears to be due to some conflicts with `3.2.18` and some of the newer `3.3` packages now being pulled in semantically. 
I first attempted to update all `@storybook` packages to `3.3.3`, however it seems there a few issues which need to be resolved first. I commented on those [here](https://github.com/storybooks/storybook/pull/2345#issuecomment-354581381) and [here](https://github.com/storybooks/storybook/issues/790#issuecomment-354582743).
Locking addon-info temporarily seems to resolve the resize issue noted in the giphy above and avoids the new 3.3.3 issues presented upstream. 
Once 3.3.3 issues are resolved, we should be able to update all `@storybook` …

docs(addon-info): lock addon-info to 3.2.12

---

src/components/ListGroup/ListGroup.stories.js

**What**:
Adds storybook documentation tweaks to the list-group for custom content and linked examples.
Closes #85 (made some additional notes there)

docs(list-group): list-group custom content and linked examples

---

src/components/Form/Checkbox.js
src/components/Form/ControlLabel.js
src/components/Form/Form.js
src/components/Form/Form.stories.js
src/components/Form/FormControl.js
src/components/Form/FormGroup.js
src/components/Form/HelpBlock.js
src/components/Form/InputGroup.js
src/components/Form/Radio.js
src/components/Form/Stories/BasicForm.js
src/components/Form/Stories/HorizontalFormField.js
src/components/Form/Stories/InlineForm.js
src/components/Form/Stories/InlineFormField.js
src/components/Form/Stories/InputGroupsForm.js
src/components/Form/Stories/SupportedControlsForm.js
src/components/Form/Stories/VerticalFormField.js
src/components/Form/index.js
src/index.js

**What**:
Add form related components
closes #118, closes #117, closes #116
[**Link to Storybook**](http://rawgit.com/sharvit/patternfly-react/storybook/forms/index.html?knob-Label=Danger%20Will%20Robinson%21&knob-Disabled=false&knob-Show%20Labels=false&selectedKind=Forms&selectedStory=Inline%20Form&full=0&down=1&left=1&panelRight=0&downPanel=storybooks%2Fstorybook-addon-knobs)
**Discussion:**
1. I created some `Field` level components (e.g. `Stories/HorizontalFormField.js`), do you think those components should get exported to consumers?
2. Do you think I should get rid of some [InputGroups](http://rawgit.com/sharvit/patternfly-react/storybook/forms/index.html?knob-Label=Danger%20Will%20Robinson%21&knob-Disabled=false&knob-Show%20Labels=false&selectedKind=Forms&selectedStory=Input%20Group …

feat(Form): Add form related components

---

package-lock.json
package.json
src/components/EmptyState/EmptyState.js
src/components/EmptyState/EmptyState.stories.js
src/components/EmptyState/EmptyState.test.js
src/components/EmptyState/EmptyStateAction.js
src/components/EmptyState/EmptyStateHelp.js
src/components/EmptyState/EmptyStateIcon.js
src/components/EmptyState/EmptyStateInfo.js
src/components/EmptyState/EmptyStateTitle.js
src/components/EmptyState/__snapshots__/EmptyState.test.js.snap
src/components/EmptyState/index.js
src/index.js

What:
Adding Empty State component
[Link to Storybook](https://cdcabrera.github.io/patternfly-react/?knob-Label=Danger%20Will%20Robinson%21&selectedKind=EmptyState&selectedStory=EmptyState&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)
closes #82 related to [Patternfly PR 900](https://github.com/patternfly/patternfly/pull/900)
@serenamarie125 
- May need some input around adding this Patternfly

feat(EmptyState): Add Empty State Component

---

src/components/Alert/Alert.stories.js
src/components/Badge/Badge.stories.js
src/components/Breadcrumb/Breadcrumb.stories.js
src/components/Button/Button.stories.js
src/components/Chart/Chart.stories.js
src/components/Chart/Stories/AreaChartStory.js
src/components/Chart/Stories/BarChartStory.js
src/components/Chart/Stories/DonutChartStory.js
src/components/Chart/Stories/LineChartStory.js
src/components/Chart/Stories/PieChartStory.js
src/components/DropdownKebab/DropdownKebab.stories.js
src/components/EmptyState/EmptyState.stories.js
src/components/Filter/Filter.stories.js
src/components/Form/Form.stories.js
src/components/Grid/Grid.stories.js
src/components/Label/Label.stories.js
src/components/ListGroup/ListGroup.stories.js
src/components/ListView/ListView.stories.js
src/components/MenuItem/MenuItem.stories.js
src/components/Modal/Modal.stories.js
src/components/Popover/Popover.stories.js
src/components/Spinner/Spinner.stories.js
src/components/ToastNotification/ToastNotification.stories.js
src/components/Tooltip/Tooltip.stories.js
src/components/Wizard/Wizard.stories.js
storybook/constants.js
storybook/decorators/storyTemplates.js

**What**:
Update the default storybook templates and add an inline template for components with multiple stories/documentation links. Add constants for all base URLs to make updates in the future easier.
https://rawgit.com/priley86/patternfly-react/story-template-storybook/index.html
none
cc: @cdcabrera @jeff-phillips-18

docs(story-template): modify the default template, add inline templates

---

package.json

One of the latest changes around the NPM publish failing. This correlates (but isn't necessarily the cause) with Node 8 vs Node 6 testing. Reverted NPM script prepare back to prepublish.
Created as a "chore" but can alter to a "build" commit.

Prepare vs prepublish

---

src/components/Alert/Alert.js
src/components/Alert/Alert.stories.js
src/components/Alert/Alert.test.js
src/components/Alert/__snapshots__/helpers.test.js.snap
src/components/Alert/constants.js
src/components/Alert/helpers.js
src/components/Alert/helpers.test.js
src/components/ToastNotification/ToastNotification.stories.js
src/components/ToastNotification/ToastNotification.test.js

BREAKING CHANGE: Alert{type=danger} is deprecated, migrate to Alert{type=error}
fix #144
**What**:
Deprecating `<Alert type="danger" />`
The component will continue to function normally, you should only get a warning message in your console.
In what version we should drop the support of the `danger` type?
I think we should update this pr so the warning message will contain the version it will get dropped.
[storybook](https://rawgit.com/sharvit/patternfly-react/storybook/feature/deprecate-alert-danger-type/index.html?selectedKind=Alert&selectedStory=Alert%20types&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)

feat(Alert{type=danger}): Deprecate alert danger type

---

src/components/ListView/ListView.stories.js
src/components/ListView/ListViewItem.js
src/components/ListView/__mocks__/mockListItems.js
src/components/ListView/__snapshots__/ListView.test.js.snap

**What**: `hideCloseIcon` prop will optionally remove the closing x icon on expanded content
**Link to Storybook**: https://rawgit.com/danseethaler/patternfly-react/hide-close-icon-153-storybook/index.html
fix #153

feat(ListView): Adding hideCloseIcon prop

---

src/components/AboutModal/AboutModal.js
src/components/AboutModal/__mocks__/mockAboutModal.js

**What**:
Adds the ability to pass an image (or other node) for the product title in the about modal.
https://jeff-phillips-18.github.io/patternfly-react/
Fixes #197

feat(About): add ability to use product title image

---

src/components/FieldLevelHelp/FieldLevelHelp.js
src/components/FieldLevelHelp/FieldLevelHelp.stories.js
src/components/FieldLevelHelp/FieldLevelHelp.test.js
src/components/FieldLevelHelp/__snapshots__/FieldLevelHelp.test.js.snap
src/components/FieldLevelHelp/index.js
src/components/Form/Stories/BasicForm.js
src/components/Form/Stories/HorizontalFormField.js
src/components/Form/Stories/SupportedControlsForm.js
src/components/Form/Stories/VerticalFormField.js
src/index.js

Added a new component called `FieldLevelHelp` based on the design requirements in  http://www.patternfly.org/pattern-library/forms-and-controls/help-on-forms/
[FieldLevelHelp Storybook](https://rawgit.com/AparnaKarve/patternfly-react/add_fieldlevelhelp_component-storybook/index.html?knob-Show%20Modal=true&knob-content=Enter%20the%20hostname%20in%20a%20valid%20format%20%3Cbr%3E%20%20%3Ca%20target%3D%22_blank%22%20href%3D%22http%3A%2F%2Fwww.test.example.com%22%3EClick%20here%20for%20examples%20of%20valid%20hostnames%3C%2Fa%3E&knob-Close%20Popover=true&knob-Show%20Labels=false&knob-Show%20Help=true&knob-Show%20Loading=false&knob-Disabled=false&knob-Field%20Label=Hostname&knob-FieldLevelHelp%20Content=Please%20specify%20Country%20code%20%3Cbr%3E%20%3Ca%20target%3D%27_blank%27%20href%3D%27https …

Add `FieldLevelHelp` component

---

src/components/Pagination/Paginate.test.js
src/components/Pagination/Pagination.stories.js
src/components/Pagination/PaginationRow.js
src/components/Pagination/__mocks__/mockPaginationRow.js
src/components/Pagination/__snapshots__/Paginate.test.js.snap

**What**:
The PaginationRow component cannot be used at the top of the page because the page size selector is set to be dropup only and selections are not visible. This PR adds the property `pageSizeDropUp` which defaults to true but can be set to false so that the selections drop down instead.
https://jeff-phillips-18.github.io/patternfly-react/

fix(pagination): Allow drop down for page size selector

---

src/components/ToastNotification/ToastNotification.stories.js
src/components/ToastNotification/ToastNotification.test.js
src/components/ToastNotification/__snapshots__/ToastNotification.test.js.snap

fixes #220
yeah so here's that storybook thing, [look **LOOK** toast is no longer full view port 😏 ](https://allenbw.github.io/patternfly-react/?knob-Header=Great%20job%21&knob-Message=This%20is%20really%20working%20out.&knob-Type=success&knob-Dismiss=false&knob-Menu=true&knob-Action=true&selectedKind=ToastNotification&selectedStory=Toast%20Notification&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)
~~close your eyes, don't look, list of things I KNOW gotta happen before this can be un-wipped (really we're just walking through the motions of throwing up a wip pr, gettin' da 👣 💧, secretly stealing travis runtime to get a sense of coverage increase )~~
* ~~need storybook~~
* ~~squash all da commits~~
* ~~even mo coverage~~
* ~~clean it all up~~
* ~~add …

chore(ToastNotification) update storybook, increase test coverage

---

package-lock.json
package.json
storybook/openBrowser.js

closes #237
So there are a few ways to skin this cat, alternative approaches (to this pr) include:
1. creating a new file and doing a `node foo.js` (still have the concurrent run issue)
2. using https://www.npmjs.com/package/npm-run-all (but its less popular)
3. embed the feature into storyboard (but that was done/not done already https://github.com/storybooks/storybook/issues/546)
Thoughts on this approach all?

chore(dev): adds openurl support to dev start

---

src/components/InfoTip/InfoTip.js
src/components/InfoTip/InfoTip.stories.js
src/components/InfoTip/InfoTip.test.js
src/components/InfoTip/InfoTipMenu.js
src/components/InfoTip/InfoTipMenuFooter.js
src/components/InfoTip/InfoTipMenuItemIcon.js
src/components/InfoTip/InfoTipToggle.js
src/components/InfoTip/__snapshots__/InfoTip.test.js.snap

**What**:
Temporarily fixes build/info tip eslint rules broken to fix pf-react build.
Was not able to convert all components to stateless b/c it breaks some tests. Also removing some props would break other tests introduced. 
This is just to fix our rolling build...
Filed [247](https://github.com/patternfly/patternfly-react/issues/247) for future.
Also fixed by removing redundant role:
19:3  error  The element nav has an implicit role of navigation. Defining this explicitly is redundant and should beavoided  jsx-a11y/no-redundant-roles
https://rawgit.com/priley86/patternfly-react/infotip-lint-fixes/index.html

fix(infotip): adds some eslint fixes for infotip

---

src/components/Wizard/WizardSidebarGroup.js
src/components/Wizard/WizardSidebarGroupItem.js
src/components/Wizard/WizardStep.js
src/components/Wizard/WizardSubStep.js
src/components/Wizard/__mocks__/mockWizardItems.js
src/components/Wizard/__snapshots__/Wizard.test.js.snap

**What**:
Wizard updates to allow numbers, in addition to strings, as step identifiers. Convenience more or less since it ends up converting them to strings anyway. The advantage is in the implementation, instead of having to use string numbers for steps, they can be actual numbers.
closes #244 
[Storybook](https://rawgit.com/cdcabrera/patternfly-react/issues/244-storybook/index.html?selectedKind=Wizard&selectedStory=Modal%20wizard&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)

fix(Wizard): Allow numbers as step identifiers

---

src/components/Wizard/WizardContents.js

**What**:
`WizardContents` should not require activeSubstepIndex/subStepIndex (as some wizards do not have sub steps). This was a miss introduced in #216 
none

fix(wizard): fix wizard contents default props

---

src/components/ToastNotification/ToastNotification.stories.js
src/components/ToastNotification/ToastNotification.test.js
src/components/ToastNotification/ToastNotificationList.js
src/components/ToastNotification/__snapshots__/ToastNotification.test.js.snap

closes #172
https://AllenBW.github.io/patternfly-react/
So when you entered (before this pr) a notification list and dismiss the last notification, you exit the bounds of the list without doing a mouseLeave (which is a big deal, because without this, toast dismissal was never unpaused)  
The fix, is to unpause whenever the notificationlist changes (which it does when a toast is dismissed), BUT to not unpause while we are mouse(d)over notificationlist
🌮🥑💃

fix(ToastNotificationList): ensures timeout on dismissal and not onhover

---

src/index.js

**What**:
When I finished VerticalNav, I thought I would export the `controlled.js` state helper that I wrote for that, so we could use it in React components outside patternfly-react. I now want to use it in the ManageIQ V2V POC work, and found that it is not actually being exported due to a typo we didn't test for. This fixes that typo so we can actually use the exported helper.
**Link to Storybook**: https://rawgit.com/mturley/patternfly-react/export-controlled-fix-sb/index.html

fix(index.js): Fix broken export of controlled helper

---

less/breadcrumb.less
less/patternfly-react.less
sass/patternfly-react/_breadcrumb.scss
sass/patternfly-react/_patternfly-react.scss
src/components/Breadcrumb/Breadcrumb.js
src/components/Breadcrumb/Breadcrumb.stories.js
src/components/Breadcrumb/Breadcrumb.test.js
src/components/Breadcrumb/__snapshots__/Breadcrumb.test.js.snap

Adds breadcrumbs combined with page title as it described in the patternfly design page. 
Storybook:
https://rawgit.com/amirfefer/patternfly-react/storybook/feature/breadcrumbs-combined-with-title/index.html?selectedKind=About%20Modal&selectedStory=AboutModal&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

feat(Breadcrumb): breadcrumbs combined with page title

---

package.json
src/components/Cards/AggregateStatusCard/AggregateStatusCard.test.js
src/components/Cards/AggregateStatusCard/__snapshots__/AggregateStatusCard.test.js.snap
src/components/Cards/Cards.test.js
src/components/Cards/UtilizationTrendCard/UtilizationCard.test.js
src/components/Cards/UtilizationTrendCard/__snapshots__/UtilizationCard.test.js.snap
src/components/Cards/__snapshots__/Cards.test.js.snap
src/components/Form/Form.test.js
src/components/Form/__snapshots__/Form.test.js.snap
src/components/InfoTip/InfoTip.test.js
src/components/InfoTip/__snapshots__/InfoTip.test.js.snap
src/components/Label/DisposableLabel.test.js
src/components/Label/__snapshots__/DisposableLabel.test.js.snap
src/components/Wizard/Wizard.test.js
src/components/Wizard/__snapshots__/Wizard.test.js.snap

continuation of #258, removes `react-test-utils` dep and swaps tests that were using this dep over to enzyme

chore(testing): updates remaining tests to enzyme

---

package.json

**What**:
Babel preset should ignore `*.test.js` and `__mocks__`
See #284 
I did a filemerge diff locally...but you can check me ;)

fix(babel): fix regex to exclude only .test.js

---

.eslintrc
.vscode/settings.json
lint-rules/import-default-name.js
package.json
sass/patternfly-react/_patternfly-react.scss
src/components/Cards/AggregateStatusCard/AggregateStatusCard.test.js
src/components/Cards/AggregateStatusCard/AggregateStatusCount.js
src/components/Cards/AggregateStatusCard/AggregateStatusNotification.js
src/components/Cards/AggregateStatusCard/AggregateStatusNotifications.js
src/components/Cards/Card.js
src/components/Cards/CardBody.js
src/components/Cards/CardDropdownButton.js
src/components/Cards/CardFooter.js
src/components/Cards/CardGrid.js
src/components/Cards/CardHeading.js
src/components/Cards/CardLink.js
src/components/Cards/CardTitle.js
src/components/Cards/Cards.test.js
src/components/Cards/UtilizationTrendCard/UtilizationCard.js
src/components/Cards/UtilizationTrendCard/UtilizationCardDetails.js
src/components/Cards/UtilizationTrendCard/UtilizationCardDetailsCount.js
src/components/Cards/UtilizationTrendCard/UtilizationCardDetailsDesc.js
src/components/Cards/UtilizationTrendCard/UtilizationCardDetailsLine1.js
src/components/Cards/UtilizationTrendCard/UtilizationCardDetailsLine2.js

Added a rule to force the naming of the default import specified packages. This will fix
inconsistencies with variable names.
**What**:
Eslint rule for default imports
N/A
Piggybacks off of PR: https://github.com/patternfly/patternfly-react/pull/274

style(default-name): Added import-default-name eslint rule

---

src/components/Label/DisposableLabel.js
src/components/Label/DisposableLabel.test.js
src/components/Label/Label.js
src/components/Label/Label.test.js
src/components/Label/RemoveButton.test.js
src/components/Label/__snapshots__/DisposableLabel.test.js.snap
src/components/Label/__snapshots__/Label.test.js.snap
src/components/Label/__snapshots__/RemoveButton.test.js.snap

**What**:
* Modified tests under Label to use shallow rendering and targeted snapshots
* Removed circular dependncy for Label and DisposableLabel.  This fixes importing DisposableLabel directly.
* Added tests for Label and RemoveButton
N/A
N/A

test(Label): Refactor Label tests to use shallow rendering

---

src/common/Timer.test.js
src/common/helpers.test.js
src/components/InfoTip/InfoTipMenu.js
src/components/InfoTip/InfoTipToggle.js

**What**:
react-bootstrap's Dropdown component passes, and tries to use, a ref passed to InfoTipMenu and
InfoTipToggle. Since SFC's cannot have refs passed to them, I converted these two components back to class components.
https://rawgit.com/dmiller9911/patternfly-react/info-tip-fix-storybook/index.html
fix #297

fix(InfoTip): Fix ref errors from react-bootstrap for InfoTip components.

---

__mocks__/css-element-queries.js
src/components/Cards/CardHeightMatching.js
src/components/Cards/CardHeightMatching.test.js

**What**:
debounce needs to be passed a function.
https://rawgit.com/dmiller9911/patternfly-react/card-height-matching-debounce/index.html
fix #300

fix(CardHeightMatching): Fix debounce invocation in CardHeightMatching

---

.eslintrc
.prettierrc
package.json
yarn.lock

Running eslint against files staged should prevent any lint failures with builds. Additionally
running against fix will allow prettier and eslint to run at commit promoting consistent code.
**What**:
Running eslint against files staged should prevent any lint failures with builds. Additionally
running against fix will allow prettier and eslint to run at commit promoting consistent code.
N/A
N/A

chore(eslint): Add lint-staged and precommit script to format code on commit

---

.githooks/post-merge/check_package_json
package.json
yarn.lock

**What**:
After pulling down this change, developers will have to `yarn install` one last time to set up `git-hooks`, but thereafter anytime the `package.json` file changes in a `git merge` (and therefore in a `git pull`), this hook will automatically run `yarn install`.
No more wondering why your code doesn't work and remembering you forgot to `yarn install`.

chore(.githooks/post-merge): Add git-hooks and a post-merge yarn install

---

src/components/Wizard/Wizard.js

**What**:
expose `onExited` callback via `Wizard` now that it consumes `Modal`. This is needed for smooth exit animation.
completes v2v upgrade to `2.0` downstream:
https://github.com/priley86/miq_v2v_ui_plugin/pull/237

fix(wizard): expose onExited callback

---

src/components/VerticalNav/VerticalNav.js
src/components/VerticalNav/VerticalNav.stories.js
src/components/VerticalNav/VerticalNav.test.js
yarn.lock

**What**:
You can now pass persist={false} to VerticalNav to turn off the persistence behavior.
http://rawgit.com/mturley/patternfly-react/vert-nav-persist-sb/index.html

feat(VerticalNav): Add a prop to allow disabling persistence

---

src/components/Chart/Stories/AreaChartStory.js
src/components/Chart/Stories/BarChartStory.js
src/components/Chart/Stories/DonutChartStory.js
src/components/Chart/Stories/LineChartStory.js
src/components/Chart/Stories/PieChartStory.js
storybook/constants.js

**What**:
Added documentation to storybook of PF charts to point to c3js documentation so we have easier navigation and users of PF knows what else can be set to each chart.
https://karelhala.github.io/patternfly-react/

docs(Chart description)

---

package.json

this fixes an issue on master branch builds w/ jest importing duplicate modules from unexpected
paths in travis CI
**What**:

fix(jest-config): fix roots path for jest module imports

---

packages/core/src/components/Notification/Wrappers/NotificationDrawerPanelWrapper.js
packages/core/src/components/Notification/Wrappers/NotificationDrawerWrapper.js
packages/core/src/components/Notification/Wrappers/StatefulNotificationDrawerWrapper.js
packages/core/src/components/Notification/Wrappers/Wrappers.test.js

**What**:
Dividing `onNotificationClick` to two Functions:
- `onNotificationAsRead`
- `onNotificationClick`
Fixing an issue where unwanted `onNotificationClick` actions are called when clicking on notifications that are already seen for consumers who don't want additional functionality , while keeping the drawer generic for consumers who want to trigger an action whether the notification is seen or not.
`onNotificationAsRead` is only called if the notification is unread
`onNotificationClick` is always called (if its not null).

fix(NotificationDrawer) - Dividing onNotificationClick to two functions

---

storybook/sass/base.scss

After splitting the project to monorepo, styling of subpackages is handled independently and must be
explicitly added to storybook.
ISSUES CLOSED: #340
**Link to Storybook**: https://mareklibra.github.io/patternfly-react/

fix(storybook): add CSS styling to react-console storybook

---

packages/core/src/components/Notification/NotificationDrawer/NotificationDrawerEmptyState.js
packages/core/src/components/Notification/NotificationDrawer/index.js
packages/core/src/components/Notification/Wrappers/NotificationDrawerPanelWrapper.js
packages/core/src/components/Notification/Wrappers/NotificationDrawerWrapper.js
packages/core/src/components/Notification/Wrappers/Wrappers.test.js
packages/core/src/components/Notification/Wrappers/__snapshots__/Wrappers.test.js.snap

**What**:
Added ability to add Translations to the Drawer. Components that can be translated:
```
translations: {
title: 'Notifications',
emptyState: 'No Notifications Available',
readAll: 'Mark All Read',
clearAll: 'Clear All'
}
```
Panels and Notifications were already translatable.

fix(NotificationDrawer): add Translation capability

---

.vscode/settings.json

**What**:
the `eslint.options` rule path override is no longer needed now that all eslint rules have been moved into `eslint-plugin-patternfly-react`. Custom rules can be added into that package instead and we should get automatic eslint integration in the IDE. Prettier will also auto-fix our custom eslint rules ;)

chore(vscode): remove eslint rule path options override

---

packages/core/package.json
packages/core/src/components/Table/TablePfProvider.js
yarn.lock

**What**:
The `reactabular-table` dependency recently caused a [breaking change](https://github.com/reactabular/reactabular/blob/master/packages/reactabular-table/src/provider.js#L13) to our `Table.PfProvider` component. The `components` prop has been changed to `renderers` and the backported `components` prop no longer renders our tables at runtime. This was causing the deployed storybook tables to fail.
The `components` prop will be [deprecated](https://github.com/reactabular/reactabular/blob/master/packages/reactabular-table/CHANGELOG.md#8130--2017-04-19) in future versions it seems.
https://rawgit.com/priley86/patternfly-react/reactabular-table-storybook/index.html
Relates to #348

fix(tables): update reactabular-table, fix provider renderers prop

---

packages/console/src/SerialConsole/SerialConsole.js
packages/console/src/SerialConsole/XTerm.js

affects: @patternfly/react-console
Default font family and size can be changed for the SerialConsole.
Underlying xterm component uses html canvas to render text and seems not to support font style change via CSS.

feat(Font style for SerialConsole): allow customized font styling for the SerialConsole component

---

README.md

docs(README): Fix link to patternly-react.scss file

---

packages/console/README.md

affects: @patternfly/react-console

docs(console README): fix package name in the console README file

---

packages/core/less/field-level-help.less
packages/core/less/patternfly-react.less
packages/core/sass/patternfly-react/_field-level-help.scss
packages/core/sass/patternfly-react/_patternfly-react.scss
packages/core/src/components/FieldLevelHelp/FieldLevelHelp.js
packages/core/src/components/FieldLevelHelp/__snapshots__/FieldLevelHelp.test.js.snap

ISSUES CLOSED: [#354](https://github.com/patternfly/patternfly-react/issues/354)
**What**:
The field level help styling was inconsistent between patternfly and patternfly-react. Updated pf-react to use the same style, and added to the existing style to add space between the icon and label.
https://mfrances17.github.io/patternfly-react/?knob-content=Enter%20the%20hostname%20in%20a%20valid%20format%20%3Cbr%3E%20%20%3Ca%20target%3D%22_blank%22%20href%3D%22http%3A%2F%2Fwww.test.example.com%22%3EClick%20here%20for%20examples%20of%20valid%20hostnames%3C%2Fa%3E&knob-Field%20Label=Hostname&selectedKind=patternfly-react%2FForms%20and%20Controls%2FHelp%20On%20Forms&selectedStory=FieldLevelHelp&full=0&addons=1&stories=1&panelRight=0&addonPanel=storyboo …

fix(FieldLevelHelp): add style to align better with patternfly core

---

packages/core/package.json
packages/core/src/components/ApplicationLauncher/ApplicationLauncher.js
packages/core/src/components/ApplicationLauncher/ApplicationLauncher.stories.js
packages/core/src/components/ApplicationLauncher/ApplicationLauncher.test.js
packages/core/src/components/ApplicationLauncher/ApplicationLauncherItem.js
packages/core/src/components/ApplicationLauncher/ApplicationLauncherToggle.js
packages/core/src/components/ApplicationLauncher/Stories/NavApplicationLauncherStory.js
packages/core/src/components/ApplicationLauncher/Stories/WrapperNavApplicationLauncherStory.js
packages/core/src/components/ApplicationLauncher/Stories/index.js
packages/core/src/components/ApplicationLauncher/Wrappers/ApplicationLauncherWrapper.js
packages/core/src/components/ApplicationLauncher/Wrappers/StatefulApplicationLauncherWrapper.js
packages/core/src/components/ApplicationLauncher/Wrappers/Wrappers.test.js
packages/core/src/components/ApplicationLauncher/Wrappers/__snapshots__/Wrappers.test.js.snap
packages/core/src/components/ApplicationLauncher/__snapshots__/ApplicationLauncher.test.js.snap
packages/core/src/components/ApplicationLauncher/index.js
yarn.lock

fix #184
**What**:
Add an Application Launcher Component.
Managed to show all the launcher types in one storybook: `Grid/List Icons/No Icons` with the help of the knobs
[Storybook](https://rawgit.com/gilad215/patternfly-react/storybook/feature/applauncher/index.html?knob-Launcher%20Type=true&knob-Icons=true&knob-Label=Well%20done%21%20You%20successfully%20read%20this%20important%20alert%20message.&selectedKind=patternfly-react%2FApplication%20Framework%2FLauncher&selectedStory=Stateful%20Launcher&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)
- Figuring out the Icons names are a real pain, any easy way to do it?
e.g. - `applauncher-pf-link-icon pficon pficon-domain` - What is the name prop that i need to …

feat(ApplicationLauncher): Add Application Launcher Component

---

packages/console/less/serial-console.less
packages/console/sass/_serial-console.scss
packages/console/src/SerialConsole/SerialConsole.js
packages/console/src/SerialConsole/SerialConsole.stories.js
packages/console/src/SerialConsole/SerialConsole.test.js
packages/console/src/SerialConsole/XTerm.js
packages/console/src/SerialConsole/__snapshots__/SerialConsole.test.js.snap
packages/console/src/common/helpers.js
packages/console/src/index.js

Addresses issue https://github.com/patternfly/patternfly-react/issues/380
If the number of columns forced the console to be wider than the viewport, then the parent container was not sizing correctly. Added a min-width style that makes the parent container as wide as the console. Also saw that there were issues with resizing, added an option to auto-size using the autoFit property.
Storybook:
https://jschuler.github.io/patternfly-react/
Navigate to react-console -> SerialConsole

fix(SerialConsole): Set console width based on columns and add auto-sizing option

---

packages/react-core/package.json
packages/react-docs/package.json
yarn.lock

Relaxing this version will allow the docs to stay more aligned with what is part of the build setup,
and avoid having to update react-core manually while it is in alpha.

fix(react-docs): relax version for react-core in react-docs.

---

packages/patternfly-react/less/patternfly-react.less
packages/patternfly-react/less/verticalnavdivider.less
packages/patternfly-react/sass/patternfly-react/_patternfly-react.scss
packages/patternfly-react/sass/patternfly-react/_verticalnavdivider.scss
packages/patternfly-react/src/components/VerticalNav/VerticalNav.js
packages/patternfly-react/src/components/VerticalNav/VerticalNavDividerItem.js
packages/patternfly-react/src/components/VerticalNav/VerticalNavItemHelper.js
packages/patternfly-react/src/components/VerticalNav/VerticalNavSecondaryItem.js
packages/patternfly-react/src/components/VerticalNav/__mocks__/basicExample.js
packages/patternfly-react/src/components/VerticalNav/__mocks__/mockNavItems.js
packages/patternfly-react/src/components/VerticalNav/index.js

**What**:
Added the ability to show a divider between secondary items instead of the Tertiary approach.
This functionality is needed in Foreman's VerticalNav. I tried to keep the pattern of the code, but suggestions are welcome.
Result:
[Storybook](https://rawgit.com/gilad215/patternfly-react/storybook/feature/verticalnavdivider/index.html?selectedKind=Vertical%20Navigation&selectedStory=Items%20as%20Objects&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)

feat(VerticalNav): Add Divider as a Secondary Item

---

package.json
packages/react-docs/.npmignore
packages/react-docs/package.json

affects: @patternfly/react-docs
**What**:
Publish react-docs to avoid versioning with every change this is a workaround for the pr here: https://github.com/atlassian/lerna-semantic-release/pull/86

fix(react-docs): publish react-docs

---

packages/patternfly-react/src/components/FieldLevelHelp/FieldLevelHelp.js
packages/patternfly-react/src/components/FieldLevelHelp/FieldLevelHelp.stories.js
packages/patternfly-react/src/components/FieldLevelHelp/FieldLevelHelp.test.js
packages/patternfly-react/src/components/FieldLevelHelp/__snapshots__/FieldLevelHelp.test.js.snap

affects: `patternfly-react`
ISSUES CLOSED: #418 
**What**:
Exposes the Field Level Help overlay placement and button class. This flexibility may be desirable in certain cases downstream. Rename the `close` prop to `rootClose` to match the API surface a bit better. 
https://priley86.github.io/patternfly-react/

fix(field-level-help): expose the field level help placement

---

packages/patternfly-react/src/components/TypeAheadSelect/TypeAheadSelect.js
packages/patternfly-react/src/components/TypeAheadSelect/TypeAheadSelect.test.js
packages/patternfly-react/src/components/TypeAheadSelect/__snapshots__/TypeAheadSelect.test.js.snap
packages/patternfly-react/src/components/TypeAheadSelect/index.js

**What**: The original component is class-based and allows `ref` to be controlled and we want to preserve that behavior
**Link to Storybook**: https://shaded-enmity.github.io/patternfly-react/
(note I had to disable the console component as it failed to build due to unrelated issue?)
```
[0] ERROR in ./packages/react-console/src/SerialConsole/SerialConsole.js                                                                                                                       
[0] Module not found: Error: Can't resolve 'patternfly-react'
```
**Additional issues**: #427

Do not wrap Typeahed into functional component

---

packages/react-core/src/components/Button/Button.d.ts
packages/react-core/src/components/Title/Title.d.ts
packages/react-core/src/typeUtils.d.ts
tsconfig.json

Relaxed typings for the button so that string literals can be passed in. Corrected typings for
Title.  Added a tsconfig.json at the base to allow any errors to show up.

fix(react-core/typings): relax typings for button. Correct typings for title

---

packages/react-core/src/components/Button/Button.d.ts
packages/react-core/src/components/Title/Title.d.ts
packages/react-core/src/index.d.ts
packages/react-core/src/index.js
packages/react-core/src/internal/componentShape.js
packages/react-core/src/layouts/Bullseye/Bullseye.d.ts
packages/react-core/src/layouts/Bullseye/Bullseye.js
packages/react-core/src/layouts/Bullseye/Bullseye.test.js
packages/react-core/src/layouts/Bullseye/__snapshots__/Bullseye.test.js.snap
packages/react-core/src/layouts/Bullseye/index.d.ts
packages/react-core/src/layouts/Bullseye/index.js
packages/react-core/src/layouts/index.d.ts
packages/react-core/src/layouts/index.js
packages/react-docs/gatsby-config.js
packages/react-docs/src/pages/components/bullseye.js

Added Bullseye layout from here: https://pf-next.com/layouts/Bullseye/examples/
ISSUES CLOSED: #434

feat(react-core/bullseye): added Bullseye Layout

---

packages/react-docs/gatsby-node.js
packages/react-docs/package.json
packages/react-docs/src/components/navigation/navigation.js
packages/react-docs/src/layouts/index.js
packages/react-styles/package.json
packages/react-styles/src/utils.js
yarn.lock

affects: @patternfly/react-docs, @patternfly/react-styles
Change how navigation links are generated so that secondary components do not have links generated.

fix(react-docs/navigation): change how navigation links are generated

---

packages/patternfly-react/src/components/VerticalNav/VerticalNav.js
packages/patternfly-react/src/components/VerticalNav/VerticalNav.stories.js
packages/patternfly-react/src/components/VerticalNav/VerticalNav.test.js
packages/patternfly-react/src/components/VerticalNav/__mocks__/mockWithMastHeadComponent.js
packages/patternfly-react/src/components/VerticalNav/__snapshots__/VerticalNav.test.js.snap

ISSUES CLOSED: #429
**Navigation/Vertical Navigation/With Masthead Component**
See storybook here : [here](https://rawgit.com/aljesusg/patternfly-react/issue_429_story/index.html)

refactor(Add mathead to verticalnav):

---

packages/patternfly-react/package.json
packages/patternfly-react/src/components/Masthead/InnerComponents/CustomMastheadDropdown.js
packages/patternfly-react/src/components/Masthead/Masthead.stories.js
packages/patternfly-react/src/components/Masthead/Masthead.test.js
packages/patternfly-react/src/components/Masthead/MastheadDropdown.js
packages/patternfly-react/src/components/Masthead/__snapshots__/Masthead.test.js.snap
packages/react-console/package.json
yarn.lock

affects: patternfly-react, @patternfly/react-console
**What**:
Updates patternfly dependency to 3.52.1 and tweaks MastHead Dropdown component.
We need this upgrade to include the Sass for navbar icon. See [1084](https://github.com/patternfly/patternfly/pull/1084)
https://priley86.github.io/patternfly-react/?knob-Nav%20Toggle=true&selectedKind=patternfly-react%2FApplication%20Framework%2FMasthead&selectedStory=Vertical%20Menu&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs
fixes #462

fix(masthead dropdown): update patternfly dependency and masthead tweak

---

packages/react-core/package.json
packages/react-docs/package.json

react-core is not releasing. I assume this is because of this:
https://github.com/semantic-release/semantic-release/blob/caribou/docs/support/FAQ.md#can-i-set-the-initial-release-version-of-my-package-to-001
The previous releases were manual due to other issues which is why they worked before.

fix(react-core/release): start on v1.0.0 since 0.x is not supported by semantic release

---

packages/react-styles/package.json
packages/react-styles/src/build/jest/snapshot-serializer/serializer.js
packages/react-styles/src/build/jest/transform.js
packages/react-styles/src/inject.js
packages/react-styles/src/testUtils.d.ts
packages/react-styles/src/testUtils.js
packages/react-styles/testUtils.js
test.env.js
yarn.lock

affects: @patternfly/react-styles
Added getCacheKey to jest transformer to make caching more efficient and easier to bust. Suppress
style injection for Aphrodite to prevent the attempt in tests.

fix(react-styles/testing): fix file jest file caching. Add Aphrodite style suppression

---

packages/react-core/src/components/Alert/AlertIcon.js
packages/react-core/src/components/Alert/__snapshots__/Alert.test.js.snap
packages/react-docs/src/components/navigation/navigationItemGroup.js
packages/react-icons/build/generateIcons.js

affects: @patternfly/react-core, @patternfly/react-docs, @patternfly/react-icons
**What**:
When auto generating some icons (Map, Server) we'd cause a lot of problems because these are registered functions. Adding suffix to each icon is nice way to overcome this problem.
https://5b4ca96cc6aed6621abdbe38--zen-swanson-2d3350.netlify.com/

feat(react-icons icon suffix): add icon suffix to all autogenerated icons

---

package.json
yarn.lock

**What:**
Update major version of Semantic Release to v15. This matches PRs submitted to the other PatternFly repos, in relation to issue https://github.com/patternfly/patternfly/issues/876 relating to broken HTML in the release notes.

chore(dependency): update the semantic release dependency

---

packages/react-core/src/layouts/Alignment/Alignment.d.ts
packages/react-core/src/layouts/Alignment/Alignment.js
packages/react-core/src/layouts/Alignment/Alignment.test.js
packages/react-core/src/layouts/Alignment/__snapshots__/Alignment.test.js.snap
packages/react-core/src/layouts/Alignment/index.d.ts
packages/react-core/src/layouts/Alignment/index.js
packages/react-core/src/layouts/index.d.ts
packages/react-core/src/layouts/index.js
packages/react-docs/src/pages/layouts/alignment.js

**Affects**: @patternfly/react-core, @patternfly/react-docs
**What**: Introducing the PF4 Alignment Layout
ISSUES CLOSED:  https://github.com/patternfly/patternfly-react/issues/445
@dmiller9911 I tried to add the typescript files...being that I'm unfamiliar, please let me know if I'm missing anything.

feat(react-core/Alignment): Add PF4 Alignment Layout

---

packages/react-core/src/layouts/Split/Split.d.ts
packages/react-core/src/layouts/Split/Split.js
packages/react-core/src/layouts/Split/Split.test.js
packages/react-core/src/layouts/Split/SplitItem.d.ts
packages/react-core/src/layouts/Split/SplitItem.js
packages/react-core/src/layouts/Split/__snapshots__/Split.test.js.snap
packages/react-core/src/layouts/Split/index.d.ts
packages/react-core/src/layouts/Split/index.js
packages/react-core/src/layouts/index.d.ts
packages/react-core/src/layouts/index.js
packages/react-docs/src/pages/layouts/split.js

**What**:
Create new layout Split which allows horizontal alignment of items.
https://5b4f4db5fdd72a01b2df0c18--zen-swanson-2d3350.netlify.com/layouts/split/
ISSUES CLOSED: #476

feat(pf4-split): introduce split layout for PF 4

---

scripts/generators/patternfly-4-component/templates/component/{{componentName}}.js

Change generation of PF4 components/layouts so they include general stuff alongisde with styles and basic styling.
No storybook.

docs(pf4/generator): improve pf4 layout/component generator

---

packages/react-core/src/components/Card/Card.d.ts
packages/react-core/src/components/Card/Card.js
packages/react-core/src/components/Card/Card.test.js
packages/react-core/src/components/Card/CardBody.d.ts
packages/react-core/src/components/Card/CardBody.js
packages/react-core/src/components/Card/CardBody.test.js
packages/react-core/src/components/Card/CardFooter.d.ts
packages/react-core/src/components/Card/CardFooter.js
packages/react-core/src/components/Card/CardFooter.test.js
packages/react-core/src/components/Card/CardHeader.d.ts
packages/react-core/src/components/Card/CardHeader.js
packages/react-core/src/components/Card/CardHeader.test.js
packages/react-core/src/components/Card/__snapshots__/Card.test.js.snap
packages/react-core/src/components/Card/__snapshots__/CardBody.test.js.snap
packages/react-core/src/components/Card/__snapshots__/CardFooter.test.js.snap
packages/react-core/src/components/Card/__snapshots__/CardHeader.test.js.snap
packages/react-core/src/components/Card/index.d.ts
packages/react-core/src/components/Card/index.js
packages/react-core/src/components/index.d.ts
packages/react-core/src/components/index.js
packages/react-docs/src/pages/components/card.js

Added the Card Component from here: https://pf-next.com/components/Card/examples/
ISSUES CLOSED: #386

feat(react-core/card): added PatternFly 4 Card Component

---

packages/react-core/package.json
packages/react-core/src/components/Alert/Alert.test.js
packages/react-core/src/components/Alert/__snapshots__/Alert.test.js.snap
packages/react-core/src/components/Button/Button.d.ts
packages/react-core/src/components/Button/Button.js
packages/react-core/src/components/Button/Button.test.js
packages/react-core/src/components/Button/__snapshots__/Button.test.js.snap
packages/react-core/src/layouts/Grid/Grid.js
packages/react-core/src/layouts/Grid/__snapshots__/Grid.test.js.snap
packages/react-docs/src/components/example/example.js
packages/react-docs/src/components/example/example.styles.js
packages/react-docs/src/pages/components/button.js
packages/react-tokens/package.json
yarn.lock

affects: @patternfly/react-core, @patternfly/react-docs, @patternfly/react-tokens
Added support for using anchor tags or custom components for button.  Added aria support for
disabled buttons that are not rendered as HTML buttons.
Updated alert tests to use a string for actions.  The tests only needed to verify that the element passed is rendered in the correct place.  Using buttons will cause unnecessarily large snapshots.
See Core change here: https://github.com/patternfly/patternfly-next/pull/454

feat(react-core-button): support using a custom element or component for buttons

---

storybook/webpack.config.js

Target src within storybook to remove the requirement to build patternfly-react before running
storybook.

chore(storybook): add resolve alias for patternfly-react to target src

---

packages/patternfly-react/src/components/ToastNotification/TimedToastNotification.js
packages/patternfly-react/src/components/ToastNotification/ToastNotificationList.js
packages/patternfly-react/src/components/Toolbar/Toolbar.js
packages/patternfly-react/src/components/Toolbar/ToolbarResults.js
packages/patternfly-react/src/components/VerticalNav/VerticalNav.js
packages/patternfly-react/src/components/VerticalNav/VerticalNavItemHelper.js
packages/patternfly-react/src/components/VerticalNav/VerticalNavMasthead.js

The '===' comparision of types does not always produce a positive result.
Though the child is specified as the correct type, the comparison fails.
Checking the displayName will always produce the desired result.
There is no visual changes created by this PR.

fix(child types): update checking for child types to use the displayName field

---

packages/patternfly-react/src/components/TypeAheadSelect/GithubMenuItem.js
packages/patternfly-react/src/components/TypeAheadSelect/TypeAheadSelect.js
packages/patternfly-react/src/components/TypeAheadSelect/TypeAheadSelect.test.js
packages/patternfly-react/src/components/TypeAheadSelect/index.js

Expose inner components for external use.
The components are:
- Highlighter,
- Menu,
- MenuItem,
- Token,
- TypeaheadMenu,
- asyncContainer,
- menuItemContainer,
- tokenContainer
ISSUES CLOSED: #483

fix(TypeAheadSelect): expose inner components of "react-bootstrap-typeahead"

---

packages/react-core/src/components/Alert/Alert.js
packages/react-core/src/components/Alert/__snapshots__/Alert.test.js.snap
packages/react-docs/gatsby-node.js
packages/react-styles/src/utils.js

affects: @patternfly/react-core, @patternfly/react-docs, @patternfly/react-styles
ISSUES CLOSED: #467
**What**:
1.  ~Upgrades @patternfly/patternfly-next to make use of `pf-u-sr-only`~
2.  Removes custom `srOnly` CSS
3.  Make updates for `utilities` category

refactor([react-core] Alert): replace custom srOnly styles with pf-core class

---

package.json

**What**:
After cleaning all packages and installing them, tests will break because jsdom requires testUrl to
be set in jest config
Not needed
https://github.com/jsdom/jsdom/issues/2304

test(test URL): add test URL to jest config so we don't get errors with localStorage

---

packages/patternfly-react/src/components/Wizard/Patterns/WizardPattern.js
packages/patternfly-react/src/components/Wizard/Wizard.test.js

fix(wizard pattern): passes extra props from WizardPattern to underlying Wizard
ISSUES CLOSED: #519
**What**:  
WizardPattern was not passing extra props down to wizard.  Passing them down gives the developer the ability to control the underlying Modal with props such as `backdrop="static"`
**Link to Storybook**:  
[Storybook@WizardPattern](https://cfchase.github.io/patternfly-react/?knob-Active%20Step%20Index=0&selectedKind=patternfly-react%2FCommunication%2FWizard%2FPatterns&selectedStory=Stateless%20WizardPattern%20Example&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)

fix(wizard pattern): passes extra props from WizardPattern to underlying Wizard

---

packages/patternfly-react/less/compound-label.less
packages/patternfly-react/sass/patternfly-react.scss
packages/patternfly-react/sass/patternfly-react/_compound-label.scss
packages/patternfly-react/src/components/Label/CompoundLabel.js
packages/patternfly-react/src/components/Label/CompoundLabel.test.js
packages/patternfly-react/src/components/Label/Label.stories.js
packages/patternfly-react/src/components/Label/LabelWithTooltip.js
packages/patternfly-react/src/components/Label/LabelWithTooltip.test.js
packages/patternfly-react/src/components/Label/__mocks__/mockCompoundLabel.js
packages/patternfly-react/src/components/Label/__mocks__/mockLabelExamples.js
packages/patternfly-react/src/components/Label/__snapshots__/CompoundLabel.test.js.snap
packages/patternfly-react/src/components/Label/__snapshots__/LabelWithTooltip.test.js.snap
packages/patternfly-react/src/components/Label/index.js

In this PR I am creating component for showing `key:values` pair with delete capability. It can be used for [filters](http://www.patternfly.org/pattern-library/forms-and-controls/filter/#overview) or [tagging](https://github.com/patternfly/patternfly-react/pull/351)
https://github.com/patternfly/patternfly-react/issues/401
https://docs.google.com/document/d/19Vu9Q_lfCQDkwO3LQuwsImSH0rH9i0o9AF24Uer6WqA/edit
https://panspagetka.github.io/patternfly-react/?selectedKind=patternfly-react%2FWidgets%2FLabel&selectedStory=CompoundLabel&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs
@terezanovotna

feat(CompoundLabel) Add CompoundLabel component

---

packages/react-core/src/layouts/Split/index.js
packages/react-core/src/layouts/Stack/index.js

StackVariant and SplitVariant were removed. Removed old references to them.

fix(react-core): remove Variant Reference in Split and Stack barrel files

---

packages/patternfly-react/src/index.js

**What**:
This layout helper is used internally for the default stateful behavior of VerticalNav.
It would be useful to expose for consumers who want to override parts of that state.
Not relevant (no changes will be apparent in Storybook)
@priley86 , this is necessary for part of the fix I was writing for https://github.com/patternfly/patternfly-react-demo-app/pull/36 (https://github.com/patternfly/patternfly-react/issues/525). In order to lift `showMobileNav` state out, I want to use `layout.is('mobile')` and `layout.addChangeListener()` in the demo app, without having to pull in BreakJS directly.

feat(index.js): export the layout helper so consumers can use layout.is('mobile')

---

packages/react-console/src/SerialConsole/XTerm.js

There is a race condition, where during disconnection, certain
events can cause addMinWidth to dereference a null renderer object.
And we see an error like:
Cannot read property 'dimensions' of undefined
This has happened reproducibly in Cockpit's integration testing. See:
https://github.com/cockpit-project/cockpit/issues/9641
**What**: A Fix.
Whattafix!

fix(react-console): Fix racy null dereference in addMinWidth

---

packages/patternfly-react/src/components/Modal/__mocks__/mockModalManager.js
packages/patternfly-react/src/components/Table/Stories/InlineEditRowInModalTableStory.js
packages/patternfly-react/src/components/Table/Stories/index.js
packages/patternfly-react/src/components/Table/Table.stories.js

**What**:
This adds a new story called "Table in Modal With Inline Edit Row", which is just the "Table with Inline Edit Row" story inside the Modal example story.
This exposes a bug with the positioning of the confirm/cancel buttons after clicking the edit button on a row. The buttons appear to be positioned with JS, relative to the window, rather than relative to the modal, the table or the row.
With a large window:
With a small window:
This PR should be merged just to add the story, and then a separate PR should be used to fix the bug..
http://localhost:6006/?knob-Show%20Help=true&knob-Field%20Level%20Help%20Content=Please%20specify%20Country%20code%20%3Cbr%3E%20%3Ca%20target%3D%27_blank%27%20href%3D%27https%3A%2F%2Fcountrycode.org%2F%27%3 …

docs(Storybook): add Table In Modal With Inline Edit Row story to reproduce button position bug

---

.github/stale.yml

**What**: Add configuration for automated bot checking for stale pull requests that are greater than 90 days old
**Link to Storybook**: N/A

chore(stale): add probot stale configuration

---

packages/patternfly-react/src/components/Wizard/Patterns/StatefulWizardPattern.js
packages/patternfly-react/src/components/Wizard/Patterns/WizardPattern.js

- don't exclude `activeStepIndex` from `StatefulWizardPattern.propTypes` since this prop is still supported through `getDerivedStateFromProps`
- ensure explicit `displayName`

Small wizard pattern component fixes

---

packages/patternfly-react/src/common/helpers.js
packages/patternfly-react/src/components/LoginPage/LoginPage.test.js
packages/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardWithValidation.js

ISSUES CLOSED: #530
**What**:
Use KEYS and KEYCODE from src/common/helpers.js at handleCapsLock and toggleCapsLock in LoginPage

refactor: use keycode from src/common/helpers.js in LoginPage

---

packages/patternfly-3/patternfly-react/src/components/Wizard/Patterns/StatefulWizardPattern.js
packages/patternfly-3/patternfly-react/src/components/Wizard/Patterns/WizardPattern.js
packages/patternfly-3/patternfly-react/src/components/Wizard/Wizard.test.js
packages/patternfly-3/patternfly-react/src/components/Wizard/__snapshots__/Wizard.test.js.snap

**What**: https://github.com/patternfly/patternfly-react/issues/527 and https://github.com/patternfly/patternfly-react/issues/526
Add new property previousStepDisabled to Wizard.Pattern which disables/enables back steps

Allow disabling back button in Wizard.Pattern. Fixes #527

---

packages/patternfly-3/patternfly-react/package.json
packages/patternfly-3/patternfly-react/src/components/Filter/Filter.test.js
packages/patternfly-3/patternfly-react/src/components/Filter/FilterCategorySelector.js
packages/patternfly-3/patternfly-react/src/components/Filter/FilterCategoryValueSelector.js
packages/patternfly-3/patternfly-react/src/components/Filter/FilterValueSelector.js
packages/patternfly-3/patternfly-react/src/components/Filter/__mocks__/mockFilterExample.js
packages/patternfly-3/patternfly-react/src/components/Filter/__snapshots__/Filter.test.js.snap
yarn.lock

**What**:
Updated the filter component to latest designs outlined [here](https://patternfly.atlassian.net/browse/OSUX-740):
1. Removed placeholder text within the dropdowns
2. Placeholder are italicized, selected values are not
3. Restricted Select/Dropdown filters to single select/filter application
4. Dropdowns remember previous selection when switching between filter fields.
5. Dropdowns revert to placeholder when it's filter is removed.
6. Fixed filter unit tests
7. Removed eslint warnings from `_compound-label.scss`
@mcarrano 
Related PR: https://github.com/patternfly/patternfly-ng/pull/449
[Storybook: Filter](https://dtaylor113.github.io/patternfly-react/?selectedKind=patternfly-react%2FForms%20and%20Controls%2FFilter&selectedStory=Filter&full=0&addons=1&storie …

feat(filter): update to latest patternfly designs

---

packages/patternfly-3/patternfly-react/less/compound-label.less
packages/patternfly-3/patternfly-react/src/components/HorizontalNav/HorizontalNavMenuItem.js
packages/patternfly-3/patternfly-react/src/components/HorizontalNav/__mocks__/dropdownLevel.js
packages/patternfly-3/patternfly-react/src/components/HorizontalNav/__mocks__/singleLevel.js
packages/patternfly-3/patternfly-react/src/components/HorizontalNav/__mocks__/twoLevel.js
packages/patternfly-3/patternfly-react/src/components/HorizontalNav/__snapshots__/HorizontalNav.test.js.snap
packages/patternfly-3/patternfly-react/src/components/Wizard/Patterns/StatefulWizardPattern.js

Fixes warnings in HorizontalNav by using Dropdown.Toggle with useAnchor
Fix StatefulWizardPattern to not require activeStepIndex
Fix compilation errors in compound-label.less
ISSUES CLOSED: #575, #572

fix(warnings): fix warnings and compound-label.less

---

packages/patternfly-4/react-core/src/components/Modal/Backdrop.d.ts
packages/patternfly-4/react-core/src/components/Modal/Modal.d.ts
packages/patternfly-4/react-core/src/components/Modal/ModalBox.d.ts
packages/patternfly-4/react-core/src/components/Modal/ModalBoxBody.d.ts
packages/patternfly-4/react-core/src/components/Modal/ModalBoxCloseButton.d.ts
packages/patternfly-4/react-core/src/components/Modal/ModalBoxFooter.d.ts
packages/patternfly-4/react-core/src/components/Modal/ModalBoxHeader.d.ts
packages/patternfly-4/react-core/src/components/Modal/ModalContent.d.ts
packages/patternfly-4/react-core/src/components/Modal/index.d.ts
packages/patternfly-4/react-core/src/components/Modal/index.js
packages/patternfly-4/react-core/src/components/index.d.ts

Add missing modal typings to PF4.
Fixes: https://github.com/patternfly/patternfly-react/issues/581

PF4 Modal: Add missing modal typings

---

packages/patternfly-4/react-styles/src/index.d.ts

This restores the css function export from Stylesheet. This already exists in index.js, but is missing from index.d.ts
Fixes: https://github.com/patternfly/patternfly-react/issues/584

fix(stylesheet): restore css export

---

README.md

This PR makes a small fix to the link for patternfly-react.scss. It was previously point to.. nowhere. Now it takes users to a place where they may have a better chance at getting help from:
update path to patternfly-react.scss
https://github.com/seanforyou23/patternfly-react/tree/readme-typo

fix(docs): fix broken link in readme

---

packages/patternfly-4/react-core/src/components/Modal/Backdrop.d.ts
packages/patternfly-4/react-core/src/components/Modal/Modal.d.ts
packages/patternfly-4/react-core/src/components/Modal/ModalBox.d.ts
packages/patternfly-4/react-core/src/components/Modal/ModalBoxBody.d.ts
packages/patternfly-4/react-core/src/components/Modal/ModalBoxCloseButton.d.ts
packages/patternfly-4/react-core/src/components/Modal/ModalBoxFooter.d.ts
packages/patternfly-4/react-core/src/components/Modal/ModalBoxHeader.d.ts
packages/patternfly-4/react-core/src/components/Modal/ModalContent.d.ts

Force react-core release for missing modal typings #586.
Previous commit did not contain proper `affects` tag. Used `yarn commit` to ensure commit message contains is formatted correctly.

Force react-core release for missing modal typings

---

packages/patternfly-3/patternfly-react/src/components/VerticalNav/VerticalNav.js
packages/patternfly-3/patternfly-react/src/components/VerticalNav/VerticalNavItemHelper.js
packages/patternfly-3/patternfly-react/src/components/VerticalNav/__mocks__/mockNavItems.js

**What**:
Fix #431 
This will help Turbolinks in Foreman/Angular in Katello to better handle navigations in their own products. The default behaviour is to still prevent the default behaviour of the `href` if an `onItemClicked` function is provided. We want an option to not prevent it.
**Storybook**:
[Link to Storybook](https://rawgit.com/gilad215/patternfly-react/verticalnav-href-storybook/index.html?knob-Max%20Shown=5&knob-Leeway=2&selectedKind=patternfly-react%2FNavigation%2FVertical%20Navigation&selectedStory=Items%20as%20Objects&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)
Try `Ipsum -> Item 3-B` for demonstration

Fix #431 : Add href paths to VerticalNav menuItems

---

packages/patternfly-3/patternfly-react-extensions/less/patternfly-react-extensions.less
packages/patternfly-3/patternfly-react-extensions/less/table-grid.less
packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_patternfly-react-extensions.scss
packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_table-grid.scss
packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGrid.js
packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGrid.stories.js
packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGrid.test.js
packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGridBody.js
packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGridColumnHeader.js
packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGridHead.js
packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGridRow.js
packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/__snapshots__/TableGrid.test.js.snap
packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/_mocks_/mockItems.js
packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/_mocks_/mockTableGridExample.js
packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/index.js
packages/patternfly-3/patternfly-react-extensions/src/index.js

**What**:
The table grid component is used to create a bootstrap grid based table with headers that are able to be used for sort selection.
https://rawgit.com/jeff-phillips-18/patternfly-react/table-grid-storybook/index.html?knob-Max%20Shown=5&knob-Leeway=2&knob-Bordered=true&selectedKind=patternfly-react-extensions%2FContent%20Views%2FTableGrid&selectedStory=TableGrid&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs
**Link to Requested Design**
https://docs.google.com/document/d/1uxYtn2ekSa_QOH_Uwe0MGpPGl3woqcRfi6zvS5MMZP8/edit

feat(table-grid): add Table Grid component

---

packages/patternfly-4/react-core/src/components/Dropdown/examples/DirectionUpDropdown.js
packages/patternfly-4/react-core/src/components/Dropdown/examples/KebabDropdown.js
packages/patternfly-4/react-core/src/components/Dropdown/examples/PositionRightDropdown.js
packages/patternfly-4/react-core/src/components/Dropdown/examples/SimpleDropdown.js

PF4-React workspace Dropdown examples will now hot reload changes made to the Dropdown components
ISSUES CLOSED: #609
**What**:  Fix import statements in Dropdown examples

docs(Dropdown): fix component imports in Dropdown examples

---

package.json
packages/patternfly-3/patternfly-react-extensions/less/vertical-tabs.less
packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_vertical-tabs.scss
packages/patternfly-3/patternfly-react-extensions/src/components/VerticalTabs/VerticalTabs.js
packages/patternfly-3/patternfly-react-extensions/src/components/VerticalTabs/VerticalTabs.stories.js
packages/patternfly-3/patternfly-react-extensions/src/components/VerticalTabs/VerticalTabs.test.js
packages/patternfly-3/patternfly-react-extensions/src/components/VerticalTabs/VerticalTabsTab.js
packages/patternfly-3/patternfly-react-extensions/src/components/VerticalTabs/__snapshots__/VerticalTabs.test.js.snap
packages/patternfly-3/patternfly-react-extensions/src/components/VerticalTabs/_mocks_/mockVerticalTabsExample.js

This adds the necessary properties and css for using sub-tabs in the VerticalTabs component.
Restricted mode resticts the tabs being shown to the active tab along with its parents, sibilings,
and direct sub tabs.
https://rawgit.com/jeff-phillips-18/patternfly-react/vertical-tabs-storybook/index.html?selectedKind=patternfly-react-extensions%2FWidgets%2FVertical%20Tabs&selectedStory=Vertical%20Tabs&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs
@tlwu2013 @serenamarie125

feat(vertical-tabs): add sub-tab support, with restricted mode

---

packages/patternfly-3/patternfly-react-extensions/less/catalog-tile.less
packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_catalog-tile.scss
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/CatalogTile.js
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/CatalogTile.stories.js
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/CatalogTile.test.js
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/CatalogTileBadge.js
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/__snapshots__/CatalogTile.test.js.snap

ISSUES CLOSED: #618
https://rawgit.com/jeff-phillips-18/patternfly-react/catalog-tile-storybook/index.html?&selectedKind=patternfly-react-extensions%2FCatalog%20Components%2FCatalog%20Tile&selectedStory=Catalog%20Tile&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

fix(catalog-tile): allow icons to be used in the tile image area

---

packages/patternfly-3/patternfly-react/less/modeless-overlay.less
packages/patternfly-3/patternfly-react/less/patternfly-react.less
packages/patternfly-3/patternfly-react/sass/patternfly-react/_modeless-overlay.scss
packages/patternfly-3/patternfly-react/sass/patternfly-react/_patternfly-react.scss
packages/patternfly-3/patternfly-react/src/components/Modal/Modal.stories.js
packages/patternfly-3/patternfly-react/src/components/ModelessOverlay/ModelessOverlay.js
packages/patternfly-3/patternfly-react/src/components/ModelessOverlay/ModelessOverlay.test.js
packages/patternfly-3/patternfly-react/src/components/ModelessOverlay/ModlessOverlay.stories.js
packages/patternfly-3/patternfly-react/src/components/ModelessOverlay/__mocks__/mockModelessManager.js
packages/patternfly-3/patternfly-react/src/components/ModelessOverlay/__snapshots__/ModelessOverlay.test.js.snap
packages/patternfly-3/patternfly-react/src/components/ModelessOverlay/index.js
packages/patternfly-3/patternfly-react/src/index.js

**What**:
Built off the Bootstrap Modal classes, the modeless overlay is a non-modal version of the Bootstrap Modal
**Patternfly Design**
https://www.patternfly.org/pattern-library/forms-and-controls/modeless-overlay/#design
https://rawgit.com/jeff-phillips-18/patternfly-react/modeless-overlay-storybook/index.html?selectedKind=patternfly-react%2FForms%20and%20Controls%2FModeless%20Overlay&selectedStory=Modeless%20Overlay&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

feat(modeless-overlay): add the ModelessOverlay component

---

packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/CatalogTile.js
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/__snapshots__/CatalogTile.test.js.snap

ISSUES CLOSED: #637
https://rawgit.com/jeff-phillips-18/patternfly-react/fixes-storybook/index.html?selectedKind=patternfly-react-extensions%2FCatalog%20Components%2FCatalog%20Tile&selectedStory=Catalog%20Tile&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

fix(catalog tile): remove the default tooltip for description text

---

packages/patternfly-3/patternfly-react-extensions/less/patternfly-react-extensions.less
packages/patternfly-3/patternfly-react-extensions/less/properties-side-panel.less
packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_patternfly-react-extensions.scss
packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_properties-side-panel.scss
packages/patternfly-3/patternfly-react-extensions/src/components/PropertiesSidePanel/PropertiesSIdePanel.test.js
packages/patternfly-3/patternfly-react-extensions/src/components/PropertiesSidePanel/PropertiesSidePanel.js
packages/patternfly-3/patternfly-react-extensions/src/components/PropertiesSidePanel/PropertyItem.js
packages/patternfly-3/patternfly-react-extensions/src/components/PropertiesSidePanel/PropertySidePanel.stories.js
packages/patternfly-3/patternfly-react-extensions/src/components/PropertiesSidePanel/__snapshots__/PropertiesSIdePanel.test.js.snap
packages/patternfly-3/patternfly-react-extensions/src/components/PropertiesSidePanel/index.js
packages/patternfly-3/patternfly-react-extensions/src/index.js

**What**:
Adds the PropertiesSidePanel and PropertyItem component to patternfly-react-extensions
https://rawgit.com/jeff-phillips-18/patternfly-react/properties-sidebar-storybook/index.html?selectedKind=patternfly-react-extensions%2FForms%20and%20Controls%2FProperties%20Side%20Panel&selectedStory=PropertiesSidePanel&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs
@serenamarie125 @tlwu2013

feat(Properties Side Panel): adds the PropertiesSidePanel component

---

packages/patternfly-3/patternfly-react/less/modeless-overlay.less
packages/patternfly-3/patternfly-react/sass/patternfly-react/_modeless-overlay.scss
packages/patternfly-3/patternfly-react/src/components/Modal/Modal.stories.js
packages/patternfly-3/patternfly-react/src/components/Modal/__mocks__/mockModalManager.js
packages/patternfly-3/patternfly-react/src/components/ModelessOverlay/ModelessOverlay.js
packages/patternfly-3/patternfly-react/src/components/ModelessOverlay/__snapshots__/ModelessOverlay.test.js.snap

affects: patternfly3-react-lerna-root, patternfly-react
**What**:
Add a class `right-side-modal-pf` to allow Modal dialog component to be placed on the right side, similar to the ModelessOverlay. Refactor the ModelessOverlay to use the same class.
https://rawgit.com/jeff-phillips-18/patternfly-react/modal-storybook/index.html?selectedKind=patternfly-react%2FForms%20and%20Controls%2FModal%20Overlay&selectedStory=Modal&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

feat(modal): add class to allow Modal dialog to be placed on the right side

---

packages/patternfly-3/patternfly-react-extensions/less/table-grid.less
packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_table-grid.scss
packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGrid.js
packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGrid.stories.js
packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGrid.test.js
packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGridCol.js
packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGridRow.js
packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/__snapshots__/TableGrid.test.js.snap
packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/_mocks_/mockTableGridExample.js
packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/index.js

Updates styles for TableGrid's header to be inline with properties sidebar.
ISSUES CLOSED: #656 #652
**What**:
Adds support for Row and Cell selection to the TableGrid component in patternfly-react-extensions. This also updates the header style to be inline with the PropertiesSidePanel per UX feedback.
https://rawgit.com/jeff-phillips-18/patternfly-react/fixes-storybook/index.html?selectedKind=patternfly-react-extensions%2FContent%20Views%2FTableGrid&selectedStory=TableGrid
@serenamarie125 @tlwu2013

feat(table-grid): add Row and Cell selection support to TableGrid

---

packages/patternfly-3/patternfly-react-extensions/less/catalog-tile.less
packages/patternfly-3/patternfly-react-extensions/less/variables.less
packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_catalog-tile.scss
packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_variables.scss
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/CatalogTileViewCategory.js

https://rhamilto.github.io/patternfly-react/?selectedKind=patternfly-react-extensions%2FCatalog%20Components%2FCatalog%20Tile%20View&selectedStory=CatalogTileView&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs
ISSUES CLOSED: #668

fix(Catalog tiles): decrease the vertical spacing between catalog tiles

---

packages/patternfly-3/patternfly-react-extensions/less/vertical-tabs.less
packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_vertical-tabs.scss
packages/patternfly-3/patternfly-react-extensions/src/components/VerticalTabs/VerticalTabs.stories.js
packages/patternfly-3/patternfly-react-extensions/src/components/VerticalTabs/VerticalTabs.test.js
packages/patternfly-3/patternfly-react-extensions/src/components/VerticalTabs/VerticalTabsTab.js
packages/patternfly-3/patternfly-react-extensions/src/components/VerticalTabs/__snapshots__/VerticalTabs.test.js.snap
packages/patternfly-3/patternfly-react-extensions/src/components/VerticalTabs/_mocks_/mockVerticalTabsExample.js

Changed the tab from a button to an anchor and set the width to be 100% of the li and to wrap on
long text.
ISSUES CLOSED: #663
https://rawgit.com/jeff-phillips-18/patternfly-react/vertical-tabs-storybook/index.html?selectedKind=patternfly-react-extensions%2FWidgets%2FVertical%20Tabs&selectedStory=Vertical%20Tabs

fix(VerticalTabs): set tab text to wrap when necessary

---

packages/patternfly-3/patternfly-react-extensions/less/vertical-tabs.less
packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_vertical-tabs.scss

Prior to #664, the vertical spacing between tabs was larger.  This PR restores it to what it was.
Fixes #687

fix(VerticalTabs): restore vertical spacing between tabs

---

.github/PULL_REQUEST_TEMPLATE.md
.gitignore
.travis/after_success.sh
CONTRIBUTING.md
lerna.json
package.json
yarn.lock

**What**:
Most monorepos have now moved to consuming `lerna` directly and using the `--conventional-commits` option to handle releasing packages semantically based on [conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.2/). This means that projects like [lerna-semantic-release](https://github.com/atlassian/lerna-semantic-release) and [semantic-release](https://github.com/semantic-release/semantic-release) are no longer necessary and just abstract Lerna's core functionality.
Some additional things this will do:
* Generate package CHANGELOG.md files containing logs for every package (built in to Lerna's --conventional-commits option). These will regenerate automatically for every package lerna publishes.
* Generate a root monorepo CHANGELOG.md based on …

build(lerna): adds lerna-changelog and removes lerna-semantic-release

---

packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.d.ts

**What**:
Typescripts gives me error messages about not specifying `isDisabled`, `isValid` and `onChange?` although it's specified in the docs that they're not mandatory.
This commit is supposed to fix this problem.

fix(pf-4): checkboxProps to be consistent with Checkbox.propTypes

---

lerna.json

**What**:
Since `lerna-changelog` runs prior to `lerna publish` when generating CHANGELOG but is included w/ the [lerna publish commit](https://github.com/patternfly/patternfly-react/commit/4e2e70d51412809b30a49a26a8c4bf4cb3efa562), the log title reads `Unreleased` b/c lerna-changelog is not aware of the pending release. This was the simplest way to hook lerna-changelog w/ the current version of lerna used in this project. For this reason, we can simply change the title to something more relevant, such as "Change Log".
In the future versions of Lerna, we may be able to hook directly into the "versions" command, but setting this to something more appropriate for now.
https://github.com/lerna/lerna-changelog/issues/46

chore(lerna-changelog): set the next version attribute appropriately

---

packages/patternfly-4/react-core/.babelrc
packages/patternfly-4/react-core/src/demos/README.md
packages/patternfly-4/react-docs/gatsby-node.js
packages/patternfly-4/react-docs/src/components/navigation/navigation.js
packages/patternfly-4/react-docs/src/layouts/index.js

ISSUES CLOSED: #690
**What**:  Updates to add support to allow demo section for react documentation.
**Additional issues**:  Updated react-core so that the demo section is excluded from the distribution.

chore(react-core, react-docs): added ability to add demos to react-docs.

---

packages/patternfly-3/patternfly-react/package.json
packages/patternfly-3/patternfly-react/src/index.js
storybook/config.js
yarn.lock

fix #603
**What**: Adding automated accessibility checks for PF3 react components
**Additional issues**: https://github.com/patternfly/patternfly-react/issues/603
Is this the best place to install react-axe?
Here are some screenshots that shows what interacting with the tool looks like.

feat(a11y): add basic a11y checks with react-axe

---

packages/patternfly-4/react-core/package.json

closes #601
react-core is using an old version of react-styles which does not parse class name: "pf-u-something" to "something" but to "uSomething".
To fix this problem updating react-styles to 2.1.x in package.json solves the problem.

fix(Alert): Use the correct css class name for screen readers

---

packages/patternfly-3/patternfly-react/less/pagination.less
packages/patternfly-3/patternfly-react/less/patternfly-react.less
packages/patternfly-3/patternfly-react/sass/patternfly-react/_pagination.scss
packages/patternfly-3/patternfly-react/sass/patternfly-react/_patternfly-react.scss

Fix pagination buttons being clickable when disabled
fix #704
[Storybook](https://rawgit.com/glekner/patternfly-react/fix/pagination-storybook/index.html?knob-Page=1&knob-firstPage=First%20Page&knob-Total%20items=75&knob-of=of&knob-currentPage=Current%20Page&knob-perPage=per%20page&knob-nextPage=Next%20Page&knob-View%20Type%3A=list&knob-lastPage=Last%20Page&knob-previousPage=Previous%20Page&selectedKind=patternfly-react%2FWidgets%2FPagination&selectedStory=Pagination%20row%20w%2F%20state%20manager&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)

fix(Pagination) - buttons are clickable when disabled

---

packages/patternfly-4/react-core/build/copyStyles.js
packages/patternfly-4/react-core/package.json
packages/patternfly-4/react-core/src/components/BackgroundImage/BackgroundImage.d.ts
packages/patternfly-4/react-core/src/components/BackgroundImage/BackgroundImage.docs.js
packages/patternfly-4/react-core/src/components/BackgroundImage/BackgroundImage.js
packages/patternfly-4/react-core/src/components/BackgroundImage/BackgroundImage.test.js
packages/patternfly-4/react-core/src/components/BackgroundImage/__snapshots__/BackgroundImage.test.js.snap
packages/patternfly-4/react-core/src/components/BackgroundImage/examples/SimpleBackgroundImage.js
packages/patternfly-4/react-core/src/components/BackgroundImage/index.d.ts
packages/patternfly-4/react-core/src/components/BackgroundImage/index.js
packages/patternfly-4/react-styles/src/StyleSheet.js
packages/patternfly-4/react-tokens/package.json
yarn.lock

Since we import pf-next CSS into each component, we need a way to override the image paths generated by pf-next -- those paths are not valid for react-core. In addition, the imported CSS is wrapped by JavaScript. In order to load those image paths, each application would need to host their own images.
For pf-next, I was able to create variables to allow the image paths of `pf-c-background-image` to be overridden. See PR https://github.com/patternfly/patternfly-next/pull/776. Now the backgroundImage component can accept image paths to help override those patternfly-next styles.
Note that I've ensured the backgroundImage component works with the react-docs examples in addition to the Koku UI login page.
Koku UI Login Example:

fix(backgroundImage): import images to override css paths

---

packages/patternfly-3/patternfly-react-extensions/less/catalog-tile.less
packages/patternfly-3/patternfly-react-extensions/less/variables.less
packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_catalog-tile.scss
packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_variables.scss
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/CatalogTile.js
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/CatalogTileViewCategory.js
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/__snapshots__/CatalogTileView.test.js.snap

When a catalog was showing a limited set of tiles, the hidden tiles were still being rendered but not shown due to the height limitation on the container. This allowed the hidden tiles' text to still be considered in the browsers find component.
This PR prevents the category from rendering tiles that are not shown.

fix(CatalogTileView): Fix to not render hidden tiles in catalog tile view categories

---

packages/patternfly-4/react-core/src/components/Alert/Alert.d.ts

When adding an action button to Alert, Typescript fails to compile saying action is supposed to be a string.
This commit fixes Alert.d.ts so action accepts ReactNode.

fix(Alert): [TS] action type is string while it should've been node

---

packages/patternfly-4/react-docs/src/components/propsTable/propsTable.js

affects: @patternfly/react-docs
Closes:
#720
**What**:
For example, if a prop type is:
PropTypes.oneOfType([PropTypes.string, PropTypes.node, PropTypes.func])
For the displayed type, instead of union: , ,
would expect to see something like
string | node | object

fix(react-docs: oneoftype support):

---

packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGridHead.js

**What**:
I am having issues consuming TableGrid downstream due to the following error:
```
ERROR in ./node_modules/patternfly-react-extensions/dist/esm/components/TableGrid/TableGridHead.js
Module not found: Error: Can't resolve '../../../../patternfly-react/src/components/Tooltip' in '/Users/priley/GitHub/web-ui/frontend/node_modules/patternfly-react-extensions/dist/esm/components/TableGrid'
```
This fixes that by consuming Tooltip from `patternfly-react` instead.

fix(table-grid): use package import rather than relative path in TableGrid

---

packages/patternfly-4/react-core/README.md
packages/patternfly-4/react-docs/README.md

In pull request #625 `yarn start:docs` was removed and `yarn start:pf4` was added.
This commit updates the documents according to that change.

docs(README.md): Update docs about running the site locally

---

packages/patternfly-4/react-core/src/components/BackgroundImage/BackgroundImage.js

**What**:
There is some nasty bug when core and tokens are out of sync due to wrongly resolved dependencies loading any PF component will throw error and this library can't be used. This fixes such problem in background images.

fix(background image): fix variable map for background image so when tokens are missing do not assig them

---

packages/patternfly-4/react-core/src/components/BackgroundImage/BackgroundImage.d.ts
packages/patternfly-4/react-core/src/components/BackgroundImage/BackgroundImage.js

When the BackgroundImage component is used as a container (e.g., to wrap a component like Page layout), nothing inside it is clickable; however, works fine (clicks events can be received) as a sibling. This is due to the .pf-c-background-image selector using a z-index of -1.
Fixes https://github.com/patternfly/patternfly-react/issues/747

fix(BackgroundImage): remove children from props

---

.travis/release.sh

This fixes the broken image paths for the patternfly-4 docs hosted by surge. 
Currently, image paths are set to `/assets/images`, which works fine when running react-docs locally. However, Travis runs a script to copy the public directory for patternfly-4. This means that `/assets/images` is no longer at the root, but `/patternfly-4/assets/images`. 
This change simply copies the images to the expected location.

Fix broken image paths for patternfly-4 docs hosted by surge

---

packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.d.ts
packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.docs.js
packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.js
packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.test.js
packages/patternfly-4/react-core/src/components/Checkbox/__snapshots__/Checkbox.test.js.snap
packages/patternfly-4/react-core/src/components/Checkbox/examples/ControlledCheckbox.js
packages/patternfly-4/react-core/src/components/Checkbox/examples/CustomLabelCheckbox.js
packages/patternfly-4/react-core/src/components/Checkbox/examples/DisabledCheckbox.js
packages/patternfly-4/react-core/src/components/Checkbox/examples/UncontrolledCheckbox.js

**What**:
- adds label for checkbox
- adds validation for id, aria-label
1. checkBox must have an id
2. if label is not a string, checkBox must have an aria-label
according to https://pf-next.com/components/Check/examples/
**Link to storybook:**:
https://717-pr-patternfly-react-patternfly.surge.sh/patternfly-4/components/checkbox/
How should the component handle different additional attributes for different parts of the component?
e. g. Should we let users to add styles for wrapperDiv, label, input separately?
Right now, a consumer can add props only to input.

feat(checkBox): updated PF4 checkBox component according to PF-next

---

packages/patternfly-3/patternfly-react/less/expand-collapse.less
packages/patternfly-3/patternfly-react/less/patternfly-react.less
packages/patternfly-3/patternfly-react/sass/patternfly-react/_expand-collapse.scss
packages/patternfly-3/patternfly-react/sass/patternfly-react/_patternfly-react.scss
packages/patternfly-3/patternfly-react/src/components/ExpandCollapse/ExpandCollapse.js
packages/patternfly-3/patternfly-react/src/components/ExpandCollapse/ExpandCollapse.stories.js
packages/patternfly-3/patternfly-react/src/components/ExpandCollapse/ExpandCollapse.test.js
packages/patternfly-3/patternfly-react/src/components/ExpandCollapse/__snapshots__/ExpandCollapse.test.js.snap
packages/patternfly-3/patternfly-react/src/components/ExpandCollapse/constants.js
packages/patternfly-3/patternfly-react/src/components/ExpandCollapse/index.js
packages/patternfly-3/patternfly-react/src/index.js

**What**: introduce ExpandCollapse component
**Link to Storybook**: [https://rawgit.com/mareklibra/patternfly-react/ExpandCollapse-sb4/index.html](https://rawgit.com/mareklibra/patternfly-react/ExpandCollapse-sb4/index.html?knob-bordered=true&knob-textExpanded=Hide%20Advanced%20Options&knob-textCollapsed=Show%20Advanced%20Options&selectedKind=patternfly-react%2FForms%20and%20Controls%2FExpand%20Collapse&selectedStory=ExpandCollapse&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)
**Additional info**:
Implementation for the Expand Collapse Section is provided.
[Patternfly.org Design](https://www.patternfly.org/pattern-library/forms-and-controls/expand-collapse-section/)
The component can be farther used for the "More Information" …

feat(ExpandCollapse): introduce ExpandCollapse component

---

packages/patternfly-3/patternfly-react-extensions/less/catalog-tile.less
packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_catalog-tile.scss
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/CatalogTile.js
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/CatalogTile.stories.js
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/CatalogTile.test.js
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/__snapshots__/CatalogTile.test.js.snap

Allows applications to pass `href` or `onClick` attributes and if given creates the tile as an `<a>` for accessibility.
https://763-pr-patternfly-react-patternfly.surge.sh/patternfly-3/index.html?selectedKind=patternfly-react-extensions%2FCatalog%20Components%2FCatalog%20Tile&selectedStory=Catalog%20Tile

feat(CatalogTile): Use a link for tiles with href or onClick props

---

packages/patternfly-3/patternfly-react-extensions/less/catalog-tile.less
packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_catalog-tile.scss

Update the style on focused catalog tiles to not show underline text or outline, use the box-shadow
to indicate focus.

fix(CatalogTile): Style update for tile with focus

---

packages/patternfly-3/patternfly-react/src/components/HorizontalNav/__snapshots__/HorizontalNav.test.js.snap
packages/patternfly-3/patternfly-react/src/components/Masthead/Masthead.js

**What**:
This change fixes issue, where title is not shown when provided to `Masthead` component.
https://github.com/patternfly/patternfly-react/issues/757

Show Masthead title

---

packages/patternfly-3/patternfly-react-extensions/less/catalog-tile.less
packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_catalog-tile.scss

Remove the leftover style of bootstrap col children as it is unused and broad in scope.
#765

fix(CatalogTileView): Remove unused styling of CatalogTileViewCategory column children

---

packages/patternfly-4/react-core/src/components/Progress/index.d.ts

Resolves: #782
**What**:
Wrong attribute was exported as ProgressSize and that made it impossible to use Progress. This PR fixes such issue by exporting correct attribute.

fix(Progress): missing ProgressSize added to exported types

---

packages/patternfly-4/react-core/package.json
packages/patternfly-4/react-core/src/components/Form/ActionGroup.js
packages/patternfly-4/react-core/src/components/Form/Form.js
packages/patternfly-4/react-core/src/components/Form/FormGroup.js
yarn.lock

fix 791
**What**:
Distribution package form @patternfly/react-core 1.24.1 did not contain index.js (source of component). As a result build was not usable. More info here: https://github.com/patternfly/patternfly-react/issues/791.
The build was not passing even locally, because of some incorrect style modifier values.
CI did not catch it because the build command was `"build": "yarn build:babel; yarn build:ts"` and it should be `"build": "yarn build:babel && yarn build:ts",` (credit to @dmiller9911 for this)

fix(react-core 1.24.1 failing build): Failing build

---

packages/patternfly-4/react-core/src/components/index.d.ts

Add missing Text component to index list for typescript

fix(react-core): add missing component to index type definitions

---

packages/patternfly-3/patternfly-react/src/components/ModelessOverlay/ModelessOverlay.js

Use a 150ms delay to update show & in classes for both open and close
fixes #774

fix(ModelessOverlay): Fix for animation on open in Firefox browser

---

packages/patternfly-4/react-core/src/components/Radio/Radio.d.ts
packages/patternfly-4/react-core/src/components/Radio/Radio.docs.js
packages/patternfly-4/react-core/src/components/Radio/Radio.js
packages/patternfly-4/react-core/src/components/Radio/Radio.test.js
packages/patternfly-4/react-core/src/components/Radio/__snapshots__/Radio.test.js.snap
packages/patternfly-4/react-core/src/components/Radio/examples/ControlledRadio.js
packages/patternfly-4/react-core/src/components/Radio/examples/CustomLabelRadio.js
packages/patternfly-4/react-core/src/components/Radio/examples/DisabledRadio.js
packages/patternfly-4/react-core/src/components/Radio/examples/UncontrolledRadio.js
packages/patternfly-4/react-core/src/components/Radio/examples/common/getContainerProps.js

**What**:
This PR updates radio component according to PF-next demo (https://pf-next.com/components/Check/examples/)
- adds label
- adds more tests
It's basically same component as Checkbox (https://github.com/patternfly/patternfly-react/pull/717), but with `radio` type and required `name` prop.
https://756-pr-patternfly-react-patternfly.surge.sh/patternfly-4/components/radio

feat(radioComponent): updated according to PF-next demo

---

packages/patternfly-4/react-core/src/components/Form/ActionGroup.js

Fixes currently broken master, because there is no info modifier for FormGroup.

fix(Form): Do not add any class if action modifier is missing

---

packages/patternfly-3/patternfly-react-extensions/less/catalog-item.less
packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_catalog-item.scss
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogItemHeader/CatalogItemHeader.js
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogItemHeader/CatalogItemHeader.stories.js
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogItemHeader/CatalogItemHeader.test.js
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogItemHeader/__snapshots__/CatalogItemHeader.test.js.snap

If a vendor (displayed in the subtitle) is not provided, the component emits an empty subtitle
element, which creates a visual defect
Before:
After:
attn: @jeff-phillips-18, @dtaylor113

fix(CatalogItemHeader): Make subtitle optional

---

packages/patternfly-3/patternfly-react-extensions/less/catalog-tile.less
packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_catalog-tile.scss

Catalog tiles are supposed to have a fixed size.  If the viewport gets small, the tiles shrink.
Before:
After:
attn: @jeff-phillips-18, @dtaylor113

fix(CatalogTile): Catalog Tiles can shrink

---

packages/patternfly-4/react-core/src/components/index.d.ts
packages/patternfly-4/react-core/src/components/index.js

Forgot to include the Backdrop component in the main index files.
Fixes https://github.com/patternfly/patternfly-react/issues/802

Adds the Backdrop component to the main index files

---

packages/patternfly-4/react-core/package.json
packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.js
packages/patternfly-4/react-core/src/components/Dropdown/Toggle.js
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
yarn.lock

Fixes #557 
- Introduces `focus-trap-react` dependency [(documentation)](https://github.com/davidtheclark/focus-trap-react)
- Fixes `esc` key interaction when there are multiple `Dropdown`s on the same page.  Hitting the `esc` key will close the menu and return focus to that particular `Dropdown`'s toggle.  Previously, focus would get shifted to the last `Dropdown` on the screen
- I found `focus-trap-react` while reading the Programmatically Managing Focus section in the [React docs regarding a11y](https://reactjs.org/docs/accessibility.html#programmatically-managing-focus)
- The documentation mentions [react-aria-modal](https://github.com/davidtheclark/react-aria-modal) as as "a great focus management example," the author of which also authored `focus-trap-react`
- …

feat(PF4-Dropdown): Enhance keyboard interaction for a11y

---

packages/patternfly-4/react-core/src/components/Form/FormGroup.js

**What**:
As we discussed [here](https://github.com/patternfly/patternfly-react/pull/667#discussion_r223453507), we started using formGroup component in one of our projects, however the **checking of children props is failing**:
`demo.js:48632 Warning: Failed prop type: Cannot read property 'props' of undefined
in FormGroup (created by FinalFormField)`
The code:
```
<FormGroup
isRequired={ isRequired }
label={ label }
fieldId={ rest.id }
isValid={ !showError }
helperText={ helperText }
helperTextInvalid={ meta.error }
>
{ description && <TextContent><Text component={ TextVariants.small }>{ description }</Text></TextContent> }
{ selectComponent({ componentType, ...rest, isValid: !showError })() }
</FormGroup>
```
When I removed the selectComponent function and replace it with what it …

fix(formComponent): removes Children props checking

---

packages/patternfly-4/react-core/src/components/Progress/Progress.docs.js
packages/patternfly-4/react-core/src/components/Progress/Progress.js
packages/patternfly-4/react-core/src/components/Progress/Progress.test.js
packages/patternfly-4/react-core/src/components/Progress/ProgressBar.js
packages/patternfly-4/react-core/src/components/Progress/ProgressContainer.js
packages/patternfly-4/react-core/src/components/Progress/__snapshots__/Progress.test.js.snap
packages/patternfly-4/react-core/src/components/Progress/examples/LabeledProgress.js

#784
**What**:
To make it possible for consumers to show what indicates current progress we have to allow them pass additional label. This PR addresses such issue by adding new prop `label` to progress component.

feat(Labeled progress): allow consumers to pass additional label for progressbar

---

packages/patternfly-3/patternfly-react/src/components/ExpandCollapse/ExpandCollapse.js
packages/patternfly-3/patternfly-react/src/components/ExpandCollapse/ExpandCollapse.stories.js
packages/patternfly-3/patternfly-react/src/components/ExpandCollapse/ExpandCollapse.test.js
packages/patternfly-3/patternfly-react/src/components/ExpandCollapse/constants.js

Added the constants to ExpandCollapse rather than requiring applications to expressly import the
constants file. Fixes the storybook display of the align type values to show the values rather than
the constant.

fix(ExpandCollapse): Fix to export ALIGN_LEFT and ALIGN_CENTER constants

---

packages/react-icons/README.md

affects: @patternfly/react-icons
**What**:
Documentation about how to write custom icons as svg path.
closes: https://github.com/patternfly/patternfly-react/issues/623

docs(custom-icon): describe how to add custom icons

---

packages/patternfly-4/react-core/src/components/Select/Select.d.ts
packages/patternfly-4/react-core/src/components/TextInput/TextInput.d.ts

A small fix to the typescript check when using `TextInput` and `Select`.
There is inconsistency between PropTypes  and TypeScript checks.
For example, in `TextInput` according to PropTypes `onChange` is optional and its default value is `noop` (http://patternfly-react.surge.sh/patternfly-4/components/textinput). However, in TypeScript it's a required prop.
Another example is in `Select`, on one hand `onBlur` is not required, TS check fails saying `onBlur` is required.
I updated TS check according to what is given in http://patternfly-react.surge.sh/patternfly-4/

fix(Select/TextInput): fix components typescript interfaces

---

packages/patternfly-4/react-core/src/components/Nav/NavExpandable.js
packages/patternfly-4/react-core/src/components/Nav/NavGroup.js
packages/patternfly-4/react-core/src/components/Nav/__snapshots__/Nav.test.js.snap
packages/patternfly-4/react-core/src/components/Progress/Progress.js
packages/patternfly-4/react-core/src/internal/util.js
packages/patternfly-4/react-core/src/internal/util.test.js

To make the code more consistent, I added a method getUniqueId that is used by all components that
need a unique id. I put this id in the defaultProps object. Add also some tests for util
file.

refactor: Use the same mechanism for autogenerated component id

---

packages/patternfly-4/react-core/package.json
packages/patternfly-4/react-core/src/demos/PageLayout/PageLayoutDemo.docs.js
packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutCondensedHeader.js
packages/patternfly-4/react-core/src/internal/util.js
packages/patternfly-4/react-core/src/internal/util.test.js
packages/patternfly-4/react-core/src/layouts/Page/Page.d.ts
packages/patternfly-4/react-core/src/layouts/Page/Page.js
packages/patternfly-4/react-core/src/layouts/Page/Page.test.js
packages/patternfly-4/react-core/src/layouts/Page/PageHeader.d.ts
packages/patternfly-4/react-core/src/layouts/Page/PageHeader.js
packages/patternfly-4/react-core/src/layouts/Page/PageHeader.test.js
packages/patternfly-4/react-core/src/layouts/Page/__snapshots__/Page.test.js.snap
packages/patternfly-4/react-core/src/layouts/Page/__snapshots__/PageHeader.test.js.snap
packages/patternfly-4/react-tokens/package.json
packages/react-icons/package.json
yarn.lock

**What**:
Condensed header option for Page/PageHeader components.
This allows you to simply pass `condensedHeader` boolean to the Page component (and it will be applied automatically on scroll of the Page main contents, or if you prefer to explicitly set condensed mode via prop, you can do this as well on `PageHeader` using `condensed` prop. 
Closes #827
Demo:
https://843-pr-patternfly-react-patternfly.surge.sh/patternfly-4/demos/pagelayout/examples/page-layout-condensed-header/

feat(page layout): adds the condensed header feature to the page header

---

packages/patternfly-3/patternfly-react/src/common/helpers.js

This is preparation for the ability of extensions and console to pull in portions of
patternfly-react and allow tree shaking.

feat(helpers): Add exported helpers object containing all helper functions

---

packages/patternfly-3/patternfly-react-extensions/less/catalog-tile.less
packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_catalog-tile.scss
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/CatalogTile.js
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/CatalogTile.test.js
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/__mocks__/mockItems.js

By default, fade the text of the description rather than truncating. Truncation can still be
accomplished by setting the maxDescriptionLength parameter.

fix(CatalogTile): Fade end of description text rather than truncate

---

packages/patternfly-3/.babelrc.js
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/CatalogTileViewCategory.js
packages/patternfly-3/patternfly-react-extensions/src/components/FilterSidePanel/FilterSidePanelCategory.js
packages/patternfly-3/patternfly-react-extensions/src/components/FilterSidePanel/FilterSidePanelCategoryItem.js
packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGrid.test.js
packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGridColumnHeader.js
packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGridHead.js
packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGridRow.js

Pull in patternfly-react components individually in patternfly-react-extensions so that tree shaking
will not pull in unused patternfly-react components.

feat(Extensions): Import patternfly-react components individually

---

packages/patternfly-4/react-core/src/components/Progress/ProgressBar.js
packages/patternfly-4/react-core/src/components/Progress/ProgressContainer.js

Updating to `1.28.1` shows the following error message.
It looks like `../../@patternfly/patternfly-next/components/Progress/progress.css.js` exports a default object. However, progressBar, progressIndicator, progressMeasure, progressDescription, progressStatusIcon and progressStatus are imported.
I am not sure whether it's a problem on babeljs side or that's an innocent mistake. Nevertheless, it fixed the problem for me.

fix(Progress): import progress style object

---

packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.d.ts
packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.js
packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.test.js
packages/patternfly-4/react-core/src/components/Checkbox/examples/ControlledCheckbox.js
packages/patternfly-4/react-core/src/components/Radio/Radio.d.ts
packages/patternfly-4/react-core/src/components/Radio/Radio.js
packages/patternfly-4/react-core/src/components/Radio/Radio.test.js
packages/patternfly-4/react-core/src/components/Radio/examples/ControlledRadio.js

I think there is some inconsistency in Radio and Checkbox API.
IMHO, it's expected the `isChecked` prop to set the item as checked (the same way `isDisabled` renders the item disabled). However, to check the item the `checked` props is used.
In this PR, I am attempting to fix this behaviour/API.

refactor(Radio/Checkbox): replace checked with isChecked in API

---

packages/patternfly-4/react-core/src/components/index.d.ts
packages/patternfly-4/react-core/src/layouts/Page/PageSection.d.ts

**What**:
Export LoginBox in typescript definitions file and make PageSection props optional
Closes:
#879

fix(typescript): Export LoginBox and make PageSection props optional

---

packages/patternfly-3/patternfly-react/less/modeless-overlay.less
packages/patternfly-3/patternfly-react/sass/patternfly-react/_modeless-overlay.scss

This is a requested modification related to the OpenShift Console Catalog pr
https://github.com/openshift/console/pull/666
**What**:
Reduce offset position for right-side-modal-pf to lessen transition distance and ui movement.
@jeff-phillips-18 
Requested for OpenShift Console Catalog from pr https://github.com/openshift/console/pull/666

fix(modal transition): Reduce translate3d (right offset) positioning for right-side-modal-pf to 25%

---

packages/patternfly-3/patternfly-react/less/modeless-overlay.less
packages/patternfly-3/patternfly-react/sass/patternfly-react/_modeless-overlay.scss
packages/patternfly-3/patternfly-react/src/components/Modal/__mocks__/mockModalManager.js
packages/patternfly-3/patternfly-react/src/components/ModelessOverlay/__mocks__/mockModelessManager.js

**What**:
Modal allows scrolling when content is longer than viewport can fit.
ModelessOverlay doesn't (#795), which can make it unusable on small screens:
This PR makes the Modal.Body inside scrollable:
~~[old recording scrolling whole body](https://user-images.githubusercontent.com/273688/47089570-ce36f380-d229-11e8-89b4-966353ab16d3.gif)~~
According to https://www.patternfly.org/pattern-library/forms-and-controls/modeless-overlay/#design (emphasis mine):
> Vertical Navigation: If the content of the panel extends past the initial frame of the window a vertical scrollbar **should be enabled**.
> Horizontal Scrollbar: In the case of the modeless overlay panel, a horizontal scrollbar should not be used.
---
Modal with `.right-side-modal-pf` (#650) also has a problem:
This PR makes it …

ModelessOverlay: allow vertical scrolling

---

packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggle.d.ts
packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggle.js
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/DropdownToggle.test.js.snap
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Toggle.test.js.snap

**What**:
OpenShift needs an option to disable the caret from displaying for the DropdownToggle
Addresses:
https://github.com/patternfly/patternfly-react/issues/889#issuecomment-436458249

feat(DropdownToggle - noCaret option): Adds the noCaret option

---

packages/patternfly-4/react-charts/src/components/AreaChart/examples/common/getContainerProps.js
packages/patternfly-4/react-charts/src/components/AreaChart/examples/common/getContainerPropsDark.js
packages/patternfly-4/react-charts/src/components/BarChart/examples/common/getContainerProps.js
packages/patternfly-4/react-charts/src/components/Chart/Chart.d.ts
packages/patternfly-4/react-charts/src/components/ChartArea/ChartArea.d.ts
packages/patternfly-4/react-charts/src/components/ChartBar/ChartBar.d.ts
packages/patternfly-4/react-charts/src/components/ChartContainer/ChartContainer.d.ts
packages/patternfly-4/react-charts/src/components/ChartDonut/ChartDonut.d.ts
packages/patternfly-4/react-charts/src/components/ChartGroup/ChartGroup.d.ts
packages/patternfly-4/react-charts/src/components/ChartLabel/ChartLabel.d.ts
packages/patternfly-4/react-charts/src/components/ChartLegend/ChartLegend.d.ts
packages/patternfly-4/react-charts/src/components/ChartLine/ChartLine.d.ts
packages/patternfly-4/react-charts/src/components/ChartPie/ChartPie.d.ts
packages/patternfly-4/react-charts/src/components/ChartStack/ChartStack.d.ts
packages/patternfly-4/react-charts/src/components/ChartTooltip/ChartTooltip.d.ts
packages/patternfly-4/react-charts/src/components/ChartVoronoiContainer/ChartVoronoiContainer.d.ts
packages/patternfly-4/react-charts/src/components/LineChart/examples/common/getContainerProps.js
packages/patternfly-4/react-charts/src/components/StackChart/examples/common/getContainerProps.js

Fixed various typescript issues encountered while using charts in Koku UI. For example, we needed to add a missing title to ChartLegned.
I also cleaned up a couple unused styles from the examples.

fix(charts): address typescript issues

---

packages/patternfly-4/react-docs/src/pages/index.js
yarn.lock

**What**:
This PR adds support for react-axe so that accessibility issues are flagged and can be addressed during development. This is the same support we currently have with PF3. Unlike the PF3 implementation, here we do seem to be getting these checks ran on _state change_ rather than only on page load, so DX is much smoother.
This will give developers feedback like in the screenshot below.
further addresses https://github.com/patternfly/patternfly-react/issues/603
fixes #905
- Is there a better place to register react-axe within the code than what I have here?
- I didn't have to install react-axe for the pf4 workspace which I thought would be required, or hoisting this pkg up so it can be shared between pf3 and pf4. Is it ok?
FWIW I initially added react-axe with …

feat(a11y): add accessibility checks for pf4

---

packages/patternfly-4/react-styled-system/src/components/StyledSystem/StyledTheme.js

In some situations webpack is throwing an error that a global variable is undefined. Add checks. 
```
StyledTheme.js:216 Uncaught (in promise) TypeError: Cannot read property 'value' of undefined
at Object.../react-styled-system/src/components/StyledSystem/StyledTheme.js (StyledTheme.js:216)
at __webpack_require__ (bootstrap aba48a634d6803be6d1b:555)
at fn (bootstrap aba48a634d6803be6d1b:86)
at Object.../react-styled-system/src/components/StyledSystem/index.js (WidthStyles.js:5)
at __webpack_require__ (bootstrap aba48a634d6803be6d1b:555)
at fn (bootstrap aba48a634d6803be6d1b:86)
at Object.../react-styled-system/src/components/index.js (index.js:4)
at __webpack_require__ (bootstrap aba48a634d6803be6d1b:555)
at fn (bootstrap aba48a634d6803be6d1b:86)
at …
```

fix(styled-system): check if global variables are defined before use

---

packages/patternfly-3/patternfly-react/README.md

Today, the reference to our Storybook UI Development in the README points to the
rawgit site. This updates it to point to http://patternfly-react.surge.sh/

Updating reference link to PatternFly Storybook

---

packages/patternfly-3/patternfly-react/src/components/Button/Button.js
packages/patternfly-3/patternfly-react/src/components/Cards/Card.js
packages/patternfly-3/patternfly-react/src/components/Chart/Chart.js
packages/patternfly-3/patternfly-react/src/components/Dropdown/Dropdown.js
packages/patternfly-3/patternfly-react/src/components/HorizontalNav/HorizontalNav.js
packages/patternfly-3/patternfly-react/src/components/InlineEdit/InlineEdit.js
packages/patternfly-3/patternfly-react/src/components/Label/DisposableLabel.js
packages/patternfly-3/patternfly-react/src/components/Label/Label.js
packages/patternfly-3/patternfly-react/src/components/Label/index.js
packages/patternfly-3/patternfly-react/src/components/ListGroup/ListGroup.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/LoginPage.js
packages/patternfly-3/patternfly-react/src/components/Nav/Nav.js
packages/patternfly-3/patternfly-react/src/components/Pagination/Pagination.js
packages/patternfly-3/patternfly-react/src/components/SessionTimeout/SessionTimeout.js
packages/patternfly-3/patternfly-react/src/components/Tabs/Tabs.js
packages/patternfly-3/patternfly-react/src/components/ToastNotification/TimedToastNotification.js
packages/patternfly-3/patternfly-react/src/components/ToastNotification/ToastNotification.js
packages/patternfly-3/patternfly-react/src/components/TreeView/TreeView.js
packages/patternfly-3/patternfly-react/src/components/TypeAheadSelect/TypeAheadSelect.js

This allows all subcomponents to be available from the pf-react packages.
@mareklibra

fix(subcomponents): Make all subcomponents available from base component

---

packages/patternfly-4/react-core/src/components/Switch/Switch.d.ts
packages/patternfly-4/react-core/src/components/Switch/Switch.docs.js
packages/patternfly-4/react-core/src/components/Switch/Switch.js
packages/patternfly-4/react-core/src/components/Switch/Switch.test.js
packages/patternfly-4/react-core/src/components/Switch/__snapshots__/Switch.test.js.snap
packages/patternfly-4/react-core/src/components/Switch/examples/DisabledSwitch.js
packages/patternfly-4/react-core/src/components/Switch/examples/NoLabelSwitch.js
packages/patternfly-4/react-core/src/components/Switch/examples/SimpleSwitch.js
packages/patternfly-4/react-core/src/components/Switch/examples/UncontrolledSwitch.js
packages/patternfly-4/react-core/src/components/Switch/index.d.ts
packages/patternfly-4/react-core/src/components/Switch/index.js
packages/patternfly-4/react-core/src/components/index.d.ts
packages/patternfly-4/react-core/src/components/index.js

feat(component): introduce the pf4 switch component

---

packages/patternfly-3/react-console/package.json
packages/patternfly-3/react-console/src/AccessConsoles/AccessConsoles.js
packages/patternfly-3/react-console/src/AccessConsoles/AccessConsoles.stories.js
packages/patternfly-3/react-console/src/AccessConsoles/AccessConsoles.test.js
packages/patternfly-3/react-console/src/DesktopViewer/DesktopViewer.test.js
packages/patternfly-3/react-console/src/DesktopViewer/vvFileGenerator.js
packages/patternfly-3/react-console/src/SerialConsole/SerialConsole.js
packages/patternfly-3/react-console/src/SerialConsole/SerialConsole.stories.js
packages/patternfly-3/react-console/src/SerialConsole/SerialConsole.test.js
packages/patternfly-3/react-console/src/SerialConsole/SerialConsoleActions.js
packages/patternfly-3/react-console/src/SerialConsole/XTerm.js
packages/patternfly-3/react-console/src/SerialConsole/constants.js
packages/patternfly-3/react-console/src/VncConsole/VncActions.js
packages/patternfly-3/react-console/src/VncConsole/VncConsole.js
packages/patternfly-3/react-console/src/common/constants.js
packages/patternfly-3/react-console/src/index.js

Follow-up for 1f3411a6e708e833e48921380ae736cf5f79862b , resp #853.
Sub-components (like Grid.Col) are no more exported individually.

Fix sub-component references in react-console

---

packages/patternfly-3/react-console/src/DesktopViewer/ManualConnection.js

Follow up for a1e4d4f.
a1e4d4f fixed subcomponent references for react-console but there are some leftovers.

Fix sub-component references in react-console DesktopViewer

---

packages/patternfly-3/patternfly-react/src/components/LoginPage/LoginPage.test.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/SocialLoginPage.test.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/__snapshots__/LoginPage.test.js.snap
packages/patternfly-3/patternfly-react/src/components/LoginPage/__snapshots__/SocialLoginPage.test.js.snap
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginPageComponents/LoginPageContainer.js

As part of the [LoginPage implementation in Foreman](https://github.com/theforeman/foreman/pull/6234) 
I found that when no background URL is provided, an error will be raised.

fix(LoginPage): Fix background-image style

---

packages/patternfly-3/patternfly-react/src/components/Cards/CardDropdownButton.js
packages/patternfly-3/patternfly-react/src/components/Cards/Cards.test.js
packages/patternfly-3/patternfly-react/src/components/Cards/__snapshots__/Cards.test.js.snap

**What**:
Allow props to be passed through for CardDropdownButton

fix(CardDropdownButton): Allow props to be passed

---

packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.d.ts

This PR addresses a typescript regression encountered with the Dropdown. Retested this fix with the Koku UI.
Fixes https://github.com/patternfly/patternfly-react/issues/933

Fix Dropdown typescript issue

---

packages/patternfly-3/patternfly-react/less/login-page.less
packages/patternfly-3/patternfly-react/less/patternfly-react.less
packages/patternfly-3/patternfly-react/sass/patternfly-react/_login-page.scss
packages/patternfly-3/patternfly-react/sass/patternfly-react/_patternfly-react.scss
packages/patternfly-3/patternfly-react/src/components/LoginPage/__snapshots__/LoginPage.test.js.snap
packages/patternfly-3/patternfly-react/src/components/LoginPage/__snapshots__/SocialLoginPage.test.js.snap
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardWithValidation.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginFormError.js

As part of the [LoginPage implementation in Foreman](https://github.com/theforeman/foreman/pull/6234) 
I found that there was no style to the form-error
and it appeared only after the submit was sent, 
without any control of when to show it.

fix(LoginPage): improve form's error style and behavior

---

packages/patternfly-3/react-console/src/AccessConsoles/AccessConsoles.js
packages/patternfly-3/react-console/src/AccessConsoles/AccessConsoles.stories.js
packages/patternfly-3/react-console/src/AccessConsoles/AccessConsoles.test.js
packages/patternfly-3/react-console/src/AccessConsoles/__snapshots__/AccessConsoles.test.js.snap

**What**: introduce `preselectedType` for `AccessConsoles` component
Prior this patch, the component started "empty" (no console rendered).
The new property can be used to pre-select particular component for initial state.
As a part of this PR, fix for not-rendering unlisted console types is provided.

introduce preselectedType for AccessConsoles component

---

packages/patternfly-3/patternfly-react/src/components/LoginPage/LoginPage.stories.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/LoginPage.test.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardWithValidation.js

As part of the [LoginPage implementation in Foreman](https://github.com/theforeman/foreman/pull/6234) 
Adding submit error callback to display the form error.
Added tests and storybook update.

fix(LoginPage): Add submit error callback handling

---

packages/patternfly-4/react-core/src/components/Breadcrumb/Breadcrumb.d.ts
packages/patternfly-4/react-core/src/components/Breadcrumb/Breadcrumb.docs.js
packages/patternfly-4/react-core/src/components/Breadcrumb/Breadcrumb.js
packages/patternfly-4/react-core/src/components/Breadcrumb/Breadcrumb.test.js
packages/patternfly-4/react-core/src/components/Breadcrumb/BreadcrumbHeading.d.ts
packages/patternfly-4/react-core/src/components/Breadcrumb/BreadcrumbHeading.js
packages/patternfly-4/react-core/src/components/Breadcrumb/BreadcrumbHeading.test.js
packages/patternfly-4/react-core/src/components/Breadcrumb/BreadcrumbItem.d.ts
packages/patternfly-4/react-core/src/components/Breadcrumb/BreadcrumbItem.js
packages/patternfly-4/react-core/src/components/Breadcrumb/BreadcrumbItem.test.js
packages/patternfly-4/react-core/src/components/Breadcrumb/__snapshots__/Breadcrumb.test.js.snap
packages/patternfly-4/react-core/src/components/Breadcrumb/__snapshots__/BreadcrumbHeading.test.js.snap
packages/patternfly-4/react-core/src/components/Breadcrumb/__snapshots__/BreadcrumbItem.test.js.snap
packages/patternfly-4/react-core/src/components/Breadcrumb/examples/HeadingBreadcrumbs.js
packages/patternfly-4/react-core/src/components/Breadcrumb/examples/SimpleBreadcrumbs.js
packages/patternfly-4/react-core/src/components/Breadcrumb/examples/WithoutLinkBreadcrumbs.js
packages/patternfly-4/react-core/src/components/Breadcrumb/index.d.ts
packages/patternfly-4/react-core/src/components/Breadcrumb/index.js
packages/patternfly-4/react-core/src/components/index.d.ts
packages/patternfly-4/react-core/src/components/index.js

fix #856
**What**:
- adds breadcrumbs, breadcrumbItem, breadcrumbHeading components
https://872-pr-patternfly-react-patternfly.surge.sh/patternfly-4/components/breadcrumb/
- none

feat(breadcrumb): adds PF4 breadcrumb, breadcrumbItem, breadcrumbTitle components

---

packages/patternfly-3/react-console/src/DesktopViewer/ConnectWithRemoteViewer.js

**What**: Reference to react-console's constants is fixed via proper "import".

fix(DesktopViewer): Fix reference to constants in dist

---

packages/patternfly-3/patternfly-react/src/components/LoadingState/LoadingState.js
packages/patternfly-3/patternfly-react/src/components/LoadingState/LoadingState.stories.js
packages/patternfly-3/patternfly-react/src/components/LoadingState/LoadingState.test.js
packages/patternfly-3/patternfly-react/src/components/LoadingState/__snapshots__/LoadingState.test.js.snap
packages/patternfly-3/patternfly-react/src/components/LoadingState/index.js
packages/patternfly-3/react-console/package.json
yarn.lock

**What**: Adds new LoadingState component
**Additional issues**: none

Fixes #881 - Add LoadingState component

---

packages/patternfly-4/react-core/src/components/Alert/__snapshots__/Alert.test.js.snap
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/DropdownToggle.test.js.snap
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Toggle.test.js.snap
packages/patternfly-4/react-core/src/components/Nav/__snapshots__/Nav.test.js.snap
packages/patternfly-4/react-core/src/components/Popover/__snapshots__/Popover.test.js.snap
packages/patternfly-4/react-core/src/components/Progress/__snapshots__/Progress.test.js.snap
packages/patternfly-4/react-docs/src/components/example/liveDemo.js
packages/patternfly-4/react-docs/src/components/example/liveDemo.styles.js
packages/react-icons/src/__snapshots__/createIcon.test.js.snap
packages/react-icons/src/createIcon.js

Fix vertical icon placement
I took a look at font awesome and they also have examples of vertical alignment at -.125em for a height of 1em
https://fontawesome.com/how-to-use/on-the-web/advanced/svg-symbols
Seems to fix the vertical alignment issues we were seeing. This value is also being scaled according to icon size.
Closes: #961 #960 
Some comparisons (Before/After):

Icon alignment

---

packages/patternfly-3/patternfly-react-extensions/less/catalog-tile.less
packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_catalog-tile.scss
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/CatalogTile.js
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/__snapshots__/CatalogTile.test.js.snap
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/__snapshots__/CatalogTileView.test.js.snap

Fixes an issue with the fading out box not being positioned correctly when provide is multiple line or non-existent. Also prevents partial (height wise) lines of text from being shown.

fix(CatalogTile): Fix to correctly position fading out of description text

---

packages/patternfly-4/react-core/src/components/Progress/Progress.js
packages/patternfly-4/react-core/src/components/Progress/Progress.test.js
packages/patternfly-4/react-core/src/components/Progress/ProgressContainer.js
packages/patternfly-4/react-core/src/components/Progress/__snapshots__/Progress.test.js.snap

**What**: Change max parameter to control scaling of progress bar. Previously, it acted as a limit for the progress value.
Addresses issue: #945
Other notes:
- use floor of scaled value to prevent false 100% reports
- change internal variable name to better represent behavior
- update snapshot of Progress tests to reflect new behavior of max

feat(Progress): use max parameter to scale value of progress bar

---

packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.js
packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggle.d.ts
packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggle.js
packages/patternfly-4/react-core/src/components/Dropdown/KebabToggle.js
packages/patternfly-4/react-core/src/components/Dropdown/Toggle.js
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/DropdownToggle.test.js.snap
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Toggle.test.js.snap

Fixes https://github.com/patternfly/patternfly-react/issues/953.

fix(Dropdown): Apply `pf-m-plain` modifier to dropdown toggle element instead of wrapper

---

packages/patternfly-3/patternfly-react-extensions/less/catalog-tile.less
packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_catalog-tile.scss
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/CatalogTileView.js
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/CatalogTileView.stories.js
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/CatalogTileView.test.js
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/__mocks__/mockCatalogTileViewExample.js
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/__mocks__/mockCatalogTileViewNoCategoriesExample.js
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/__mocks__/mockItems.js
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/__snapshots__/CatalogTileView.test.js.snap

Currently if tiles are added to the tile view and are not in a category they are displayed in a single tile per row rather than wrapped as they are when they are in a category. 
This PR allows the caller to specify that categories are not used and will wrap the child tiles.

fix(CatalogTileView): Support tiles without categories.

---

packages/patternfly-3/patternfly-react-extensions/package.json
packages/patternfly-3/patternfly-react-extensions/src/common/helpers.js
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTileView/CatalogTileViewCategory.js
packages/patternfly-3/patternfly-react-extensions/src/components/FilterSidePanel/FilterSidePanelCategory.js
packages/patternfly-3/patternfly-react-extensions/src/components/FilterSidePanel/FilterSidePanelCategoryItem.js
packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGrid.test.js
packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGridColumnHeader.js
packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGridHead.js
packages/patternfly-3/patternfly-react-extensions/src/components/TableGrid/TableGridRow.js

Pulling in the patternfly-react helpers bring in more dependencies than are needed. This PR duplicates some of the small utility helpers in order to reduce the footprint of the extensions package.

fix(extensions): Create local helpers to lessen dependencies

---

packages/patternfly-3/react-console/src/AccessConsoles/AccessConsoles.js
packages/patternfly-3/react-console/src/SerialConsole/SerialConsole.js
packages/patternfly-3/react-console/src/VncConsole/VncConsole.js

In production build, names/strings are minified causing mismatch of `child.type.name`.
In this fix, the component type matching is fixed by using Ract component's displayName.
**What**: Fix AccessConsoles for child component recognition

fix(AccessConsoles): Fix child component recognition in production build

---

packages/patternfly-4/react-core/src/components/LoginPage/LoginForm.js
packages/patternfly-4/react-core/src/components/LoginPage/__snapshots__/LoginForm.test.js.snap

fixes https://github.com/patternfly/patternfly-react/issues/987
**What**:
* attribute in login form is `mame` instead of `name`
* docs for `passwordHelperText` should refer to `Password`, not `Username`

fix(LoginPage): typos

---

packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.docs.js
packages/patternfly-4/react-core/src/components/Dropdown/examples/DropdownPanel.js

**What**: Rename dropdown examples to better reflect their intended purpose. Reorganize examples so custom case is at the bottom.
Addresses: #1000

docs(Dropdown): clarify Dropdown example titles

---

packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalBoxHeader.test.js.snap
packages/patternfly-4/react-core/src/components/LoginPage/__snapshots__/LoginBoxHeader.test.js.snap
packages/patternfly-4/react-core/src/components/Title/Title.js
packages/patternfly-4/react-core/src/components/Title/Title.test.js
packages/patternfly-4/react-core/src/components/Title/__snapshots__/Title.test.js.snap
packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutDefaultNav.js
packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutExpandableNav.js
packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutGroupsNav.js
packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutHorizontalNav.js
packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutSimpleNav.js
packages/patternfly-4/react-docs/src/components/componentDocs/componentDocs.js
packages/patternfly-4/react-docs/src/components/example/example.js
packages/patternfly-4/react-docs/src/components/section/section.js

**What**: This PR enhances the Title component to allow for multiple heading levels, previously an h1 was assumed. It also tweaks some of the page layout examples to include hints about what packages need to be installed (this information isn't provided elsewhere) and cleans up some duplicate ID's.
**Additional issues**: https://github.com/patternfly/patternfly-react/issues/1004
add a headingLevel prop to the title component
use heading level passed in, or h1 as default
defined unique id's for example components
add instruction where first time users may stumble with copy/paste

fix(title): allow multiple heading levels for Title

---

packages/patternfly-4/react-core/src/components/DataList/DataList.d.ts
packages/patternfly-4/react-core/src/components/DataList/DataList.docs.js
packages/patternfly-4/react-core/src/components/DataList/DataList.js
packages/patternfly-4/react-core/src/components/DataList/DataList.test.js
packages/patternfly-4/react-core/src/components/DataList/DataListAction.d.ts
packages/patternfly-4/react-core/src/components/DataList/DataListAction.js
packages/patternfly-4/react-core/src/components/DataList/DataListCell.d.ts
packages/patternfly-4/react-core/src/components/DataList/DataListCell.js
packages/patternfly-4/react-core/src/components/DataList/DataListCheck.d.ts
packages/patternfly-4/react-core/src/components/DataList/DataListCheck.js
packages/patternfly-4/react-core/src/components/DataList/DataListContent.d.ts
packages/patternfly-4/react-core/src/components/DataList/DataListContent.js
packages/patternfly-4/react-core/src/components/DataList/DataListItem.d.ts
packages/patternfly-4/react-core/src/components/DataList/DataListItem.js
packages/patternfly-4/react-core/src/components/DataList/DataListToggle.d.ts
packages/patternfly-4/react-core/src/components/DataList/DataListToggle.js
packages/patternfly-4/react-core/src/components/DataList/__snapshots__/DataList.test.js.snap
packages/patternfly-4/react-core/src/components/DataList/examples/CheckboxActionDataList.js
packages/patternfly-4/react-core/src/components/DataList/examples/ExpandableDataList.js
packages/patternfly-4/react-core/src/components/DataList/examples/ModifiersDataList.js
packages/patternfly-4/react-core/src/components/DataList/examples/SimpleDataList.js
packages/patternfly-4/react-core/src/components/DataList/index.d.ts
packages/patternfly-4/react-core/src/components/DataList/index.js
packages/patternfly-4/react-core/src/components/index.d.ts
packages/patternfly-4/react-core/src/components/index.js

This is still work in progress. Hopefully it will be ready by next week.

feat(DataList): Add simple data list

---

packages/patternfly-3/patternfly-react/src/components/Chart/BulletChart/BulletChartAxisTic.js
packages/patternfly-3/patternfly-react/src/components/Chart/BulletChart/__snapshots__/BulletChart.test.js.snap

This PR fixes an issue with the `text` property of BulletChartAxisTic. 
The `text` property is documented, but never used in the code. It allows users to apply a custom label to the x-axis, while the given `value` property used by default.
Fixes https://github.com/patternfly/patternfly-react/issues/1028

BulletChartAxisTic: Fixed text property for custom axis tic mark

---

packages/patternfly-4/react-core/src/components/Modal/Modal.js
packages/patternfly-4/react-core/src/components/Modal/Modal.test.js
packages/patternfly-4/react-core/src/components/Modal/ModalContent.js
packages/patternfly-4/react-core/src/components/Modal/__snapshots__/ModalContent.test.js.snap
packages/patternfly-4/react-core/src/components/Modal/examples/LargeModal.js
packages/patternfly-4/react-core/src/components/Modal/examples/SimpleModal.js
packages/patternfly-4/react-core/src/internal/safeHTMLElement.js

BREAKING CHANGE: The reactRoot prop is required
Fixes #561
**What**:  Adds keyboard and screen reader focus trapping
**Notes/Resources**:
1.  [react accessible modal (github.com/reactjs)](https://github.com/reactjs/react-modal)
2.  [a11y dialog](https://github.com/edenspiekermann/a11y-dialog)
3.  The consumer must pass the react root `HTMLElement` as a prop.
4.  When the modal is opened, `aria-hidden=true` is applied to the react root element, hiding it from screen readers.
5.  When the modal is closed, the `aria-hidden` attribute is removed from the react root element

feat(PF4-Modal): Adds keyboard and screen reader focus trapping

---

packages/patternfly-3/react-console/package.json

This is a follow-up to [`kubevirt-web-ui-components` issue 136](https://github.com/kubevirt/web-ui-components/issues/136).
Main [`patternfly-react` package](https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-3/patternfly-react/package.json) declares `patternfly` and `react-bootstrap` as regular dependencies, which pulls them into the consuming application's dependency tree.
However, [`@patternfly/react-console` package](https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-3/react-console/package.json) declares `patternfly` and `react-bootstrap` as _peer dependencies_ (in addition to having a peer dependency on `patternfly-react`, which in turn pulls these two specific libraries as _regular dependencies_).
Aside from the fact that code …

@patternfly/react-console: Remove unnecessary peer dependencies

---

packages/patternfly-4/react-core/src/components/Text/examples/BodyText.js

**What**: Removing pre Text example, but leaving pre in TextVariants for now due to its usage in livedemo
**Refer to issue**: #1023

docs(Text): remove pre Text example

---

packages/patternfly-4/react-core/src/layouts/Stack/examples/common/getContainerProps.js

**What**: Flex grow is being applied but example containers are too short to display the growth. Increased example container height.
**Refer to issue**: #1025

docs(Stack): increase height of example containers to show flex grow

---

packages/patternfly-3/patternfly-react/less/dual-list-selector.less
packages/patternfly-3/patternfly-react/less/patternfly-react.less
packages/patternfly-3/patternfly-react/package.json
packages/patternfly-3/patternfly-react/sass/patternfly-react/_dual-list-selector.scss
packages/patternfly-3/patternfly-react/sass/patternfly-react/_patternfly-react.scss
packages/patternfly-3/patternfly-react/src/components/DualListSelector/DualList.js
packages/patternfly-3/patternfly-react/src/components/DualListSelector/DualList.stories.js
packages/patternfly-3/patternfly-react/src/components/DualListSelector/DualList.test.js
packages/patternfly-3/patternfly-react/src/components/DualListSelector/DualListControlled.js
packages/patternfly-3/patternfly-react/src/components/DualListSelector/DualListMocks.js
packages/patternfly-3/patternfly-react/src/components/DualListSelector/__snapshots__/DualList.test.js.snap
packages/patternfly-3/patternfly-react/src/components/DualListSelector/components/DualListArrows.js
packages/patternfly-3/patternfly-react/src/components/DualListSelector/components/DualListBody.js
packages/patternfly-3/patternfly-react/src/components/DualListSelector/components/DualListCounter.js
packages/patternfly-3/patternfly-react/src/components/DualListSelector/components/DualListFilter.js
packages/patternfly-3/patternfly-react/src/components/DualListSelector/components/DualListFooter.js
packages/patternfly-3/patternfly-react/src/components/DualListSelector/components/DualListHeading.js
packages/patternfly-3/patternfly-react/src/components/DualListSelector/components/DualListItem.js
packages/patternfly-3/patternfly-react/src/components/DualListSelector/components/DualListItems.js
packages/patternfly-3/patternfly-react/src/components/DualListSelector/components/DualListMainCheckbox.js
packages/patternfly-3/patternfly-react/src/components/DualListSelector/components/DualListSelector.js
packages/patternfly-3/patternfly-react/src/components/DualListSelector/components/DualListSort.js
packages/patternfly-3/patternfly-react/src/components/DualListSelector/constants.js
packages/patternfly-3/patternfly-react/src/components/DualListSelector/helpers.js
packages/patternfly-3/patternfly-react/src/components/DualListSelector/index.js
packages/patternfly-3/patternfly-react/src/index.js

Add DualListSelector component with storybook and tests. fix #379
[Storybook](https://rawgit.com/Laviro/patternfly-react/storybook/feature/dual-list-selector/index.html?selectedKind=patternfly-react%2FForms%20and%20Controls%2FDual%20List%20Selector&selectedStory=Dual%20List%20Selector&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)
[Design](http://www.patternfly.org/pattern-library/forms-and-controls/dual-list-selector/#design)

feat(DualListSelector): add a Dual List Selector component

---

packages/patternfly-4/react-core/src/components/Avatar/Avatar.tsx

**What**:
Updated to remove Proptypes from Avatar since we have interface for tsx
Built locally and it worked without proptypes for Jest tests.

Removed Props from avatar

---

packages/patternfly-3/react-console/less/access-consoles.less
packages/patternfly-3/react-console/less/console.less
packages/patternfly-3/react-console/sass/_access-consoles.scss
packages/patternfly-3/react-console/sass/console.scss
packages/patternfly-3/react-console/src/AccessConsoles/AccessConsoles.js
packages/patternfly-3/react-console/src/AccessConsoles/AccessConsoles.test.js
packages/patternfly-3/react-console/src/AccessConsoles/__snapshots__/AccessConsoles.test.js.snap
packages/patternfly-3/react-console/src/DesktopViewer/DesktopViewer.js
packages/patternfly-3/react-console/src/common/constants.js

**What**: Add desktop viewer to access consoles
With this patch, the DesktopViewer can be a child component of the AccessConsoles.

Add desktop viewer to access consoles

---

packages/patternfly-3/patternfly-react/src/components/Overlay/Overlay.js
packages/patternfly-3/patternfly-react/src/components/Overlay/Overlay.stories.js
packages/patternfly-3/patternfly-react/src/components/Overlay/__mocks__/mockOverlayManager.js
packages/patternfly-3/patternfly-react/src/components/Overlay/index.js
packages/patternfly-3/patternfly-react/src/index.js

**What**:
The `OverlayTrigger` component is great for most use cases, but as a higher level abstraction it can
lack the flexibility needed to build more nuanced or custom behaviors into your `Overlay`
components. For these cases it can be helpful to forgo the trigger and use the `Overlay` component
directly.
**Storybook**
https://rawgit.com/sharvit/patternfly-react/storybook/feature/overlay/index.html?knob-Placement=top&selectedKind=patternfly-react%2FWidgets%2FOverlay&selectedStory=Overlay%20story&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

feat(Overlay): Export the Overlay component from react-bootstrap

---

packages/patternfly-3/patternfly-react-extensions/less/catalog-tile.less
packages/patternfly-3/patternfly-react-extensions/sass/patternfly-react-extensions/_catalog-tile.scss
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/CatalogTile.js
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/CatalogTile.stories.js
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/CatalogTile.test.js
packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/__snapshots__/CatalogTile.test.js.snap

This PR provides the ability to have a footer to the catalog tile content.

feat(CatalogTile): Add footer option to tiles

---

packages/patternfly-3/patternfly-react/less/charts.less
packages/patternfly-3/patternfly-react/less/patternfly-react.less
packages/patternfly-3/patternfly-react/sass/patternfly-react/_charts.scss
packages/patternfly-3/patternfly-react/sass/patternfly-react/_patternfly-react.scss
packages/patternfly-3/patternfly-react/src/components/Chart/BulletChart/BulletChart.js
packages/patternfly-3/patternfly-react/src/components/Chart/BulletChart/BulletChart.test.js
packages/patternfly-3/patternfly-react/src/components/Chart/BulletChart/__snapshots__/BulletChart.test.js.snap
packages/patternfly-3/patternfly-react/src/components/Chart/Stories/BulletChartStory.js

Provides the ability to add Threshold items to the legend if either text or a function is provided.

feat(BulletChart): Add Thresholds to Legend

---

packages/patternfly-3/patternfly-react/src/components/DualListSelector/DualList.js
packages/patternfly-3/patternfly-react/src/components/DualListSelector/DualList.test.js

Reduce the events fired on filter change.
Called twice:
Instead of 6 times:

fix(DualList): Adding debounce for filter changes

---

packages/patternfly-3/patternfly-react/src/components/Chart/BulletChart/BulletChart.js

Previous travis build was failing because helpers.noop was undefined. I could reproduce this locally. We can import just noop and use that instead.

fix(pf3): fix usage of noop in BulletChart

---

packages/patternfly-3/patternfly-react/less/dual-list-selector.less
packages/patternfly-3/patternfly-react/sass/patternfly-react/_dual-list-selector.scss
packages/patternfly-3/patternfly-react/src/components/DualListSelector/DualList.js
packages/patternfly-3/patternfly-react/src/components/DualListSelector/DualList.test.js
packages/patternfly-3/patternfly-react/src/components/DualListSelector/DualListMocks.js
packages/patternfly-3/patternfly-react/src/components/DualListSelector/components/DualListItem.js
packages/patternfly-3/patternfly-react/src/components/DualListSelector/components/DualListItemTooltip.js
packages/patternfly-3/patternfly-react/src/components/DualListSelector/helpers.js

When an item is disabled,
the user won't be able to move it between the lists:

fix(DualList): Add item disability functionality.

---

packages/patternfly-3/package.json
packages/patternfly-3/patternfly-react-extensions/package.json
packages/patternfly-3/patternfly-react/package.json
packages/patternfly-3/react-console/package.json

Something broke in the pf3 build yesterday preventing the build from updating the package.json files with the correct version numbers.  This sets them back correctly

chore(pf3): fix pf3 release versions

---

packages/patternfly-4/react-core/src/components/LoginPage/examples/SimpleLoginPage.js

Updated the branding alt text in the LoginPage to "Patternfly Logo." Per @jgiardino, it should match the example in core and repeat the text/describe the image.
Fixes [#993](https://github.com/patternfly/patternfly-react/issues/993).

fix: update alt text in LoginPage

---

packages/patternfly-4/react-core/src/components/LoginPage/LoginForm.d.ts

fix #1062
Change a typo error in LoginForm component.
**What**:
Change passwordValue by passwordValue, we can't use the password field when you import this component

PF4: fix(LoginForm): LoginForm.d.ts fix typo passwordValue

---

packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.docs.js
packages/patternfly-4/react-core/src/components/Dropdown/DropdownItem.js
packages/patternfly-4/react-core/src/components/Dropdown/examples/ReactLinkDropdown.js

Prevents nesting anchor tags.
**What**: If child element of DropdownItem is a react-router Link, wrapper should be a div.
Still need to add to documentation, potentially an example as well.

fix(DropdownItem): wrap DropdownItem in div when child is a Link node

---

packages/patternfly-4/react-core/src/components/EmptyState/EmptyStateIcon.d.ts

There is a typo in `EmptyStateIcon.d.ts` - it imports `OneOf` and `Omit` from `../typeUtils` which doesn't exist. It is supposed to be `../../typeUtils`.
This is on me.

fix(EmptyState): a typo at the import path in EmptyStateIcon.d.ts

---

packages/patternfly-4/react-core/src/components/Popover/Popover.d.ts

@types/react has no default export member React.

fix(ts): fix for popover ts

---

packages/patternfly-4/react-core/src/components/TextArea/TextArea.d.ts
packages/patternfly-4/react-core/src/components/TextInput/TextInput.d.ts

**What**:
`onChange` receives two arguments: `value` and `event`.
According to `TextArea.d.ts` and `TextInput.d.ts` the value is `boolean` while it is `string` because they are text input type.
In addition, `onChange` is optional (but it is mandatory in `TextArea.d.ts`).
This patch fixes these to the correct type.

fix(TextInput/Area): update type definitions

---

packages/patternfly-4/react-core/src/components/Radio/Radio.d.ts

Made aria-label required in Radio.d.ts to match the JS error handling. Per @titani, it should be consistent.
Fixes https://github.com/patternfly/patternfly-react/issues/1048.

fix(Radio.d.ts): Made aria-label required

---

packages/patternfly-4/react-core/src/components/Dropdown/DropdownMenu.js
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.js.snap

**What**:
fixes #1113 and #1125

fix(dropdown): add focus trap option that allows  close on click

---

packages/patternfly-3/react-console/src/AccessConsoles/AccessConsoles.js

With this fix, AccessConsole's children of "undefined" or "null" values are handled
correctly by propTypes checking.
Needed for conditionally-rendered children within the higher-level calling code.
**What**: fix propTypes checking for "null" child

fix(AccessConsoles): fix propTypes checking for "null" child

---

packages/patternfly-3/react-console/src/DesktopViewer/ConnectWithRemoteViewer.js
packages/patternfly-3/react-console/src/DesktopViewer/__snapshots__/DesktopViewer.test.js.snap

Prior this fix, the Launch buttons firing file download were "btn-lg".
This looks weird in some use-cases (like OpenShift).
If the button size needs to be biger in rare cases, it can be tweaked via custom styling.
**What**: use standard button size in DesktopViewer

style(DesktopViewer): use standard button size in DesktopViewer

---

packages/patternfly-4/react-core/src/components/Avatar/index.d.ts
packages/patternfly-4/react-core/src/components/Avatar/index.ts

**What**:
Fixes #1133 
_TL/DR:_ The index.ts file for the PF4 Avatar component currently exports both the component itself and the component's props interface. It looks like the interface is compiled away, which leads to an import error when compiling apps depending on it.
```
./node_modules/@patternfly/react-core/dist/esm/components/Avatar/index.js
Attempted import error: 'AvatarProps' is not exported from './Avatar'.
```
**How:**
Splitting up the index.ts file into an index.ts and an index.d.ts file resolves the issue, while still keeping the TypeScript support. That's the approach to this that other components take as well.
**Additional Comments:**
If I missed any conventions or requirements, please let me know! 🙂

fix(Avatar): Correctly export Avatar component typings

---

packages/patternfly-4/react-core/src/components/EmptyState/EmptyStateIcon.d.ts

**What**:
Since `EmptyStateIcon` takes any props that `Icon` takes extend `EmptyStateIconProps` from` IconProps` rather than `HTMLProps<SVGElement>`.
I realized that setting the icon to `size="lg"` through `EmptyStateIcon` will print error message saying `size` is not a valid prop.
This will fix this.

fix(EmptyState): Use IconProps to define EmptyStateIconProps

---

packages/patternfly-3/patternfly-react/src/components/Toolbar/Toolbar.js

**What**:
Toolbar has an internal `<form .../>` which will be submitted (causing a screen refresh) upon Enter key press.  This PR adds a `preventSubmit` prop. which when set to `true` will prevent form submission.  Default is `false`.
Addresses OpenShift Issue: 
https://bugzilla.redhat.com/show_bug.cgi?id=1661141
Fixes #1104

Toolbar: added 'preventSubmit' prop. to allow prevention of internal form submission

---

packages/patternfly-4/react-core/src/components/Dropdown/DropdownItem.js
packages/patternfly-4/react-core/src/components/Dropdown/Toggle.js
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/DropdownItem.test.js.snap
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/DropdownToggle.test.js.snap
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Toggle.test.js.snap

**What**: Changed Dropdown button types to default to type='button'. Providing a type manually will overwrite the default.
**References issue**: #1105

fix(Dropdown): set default button type to button

---

packages/patternfly-4/react-core/src/components/ApplicationLauncher/__snapshots__/ApplicationLauncher.test.js.snap
packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.js
packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.test.js
packages/patternfly-4/react-core/src/components/Dropdown/DropdownItem.d.ts
packages/patternfly-4/react-core/src/components/Dropdown/DropdownItem.js
packages/patternfly-4/react-core/src/components/Dropdown/DropdownMenu.js
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/DropdownItem.test.js.snap
packages/patternfly-4/react-core/src/components/Dropdown/dropdownConstants.js

Issue reference: #984 
**What**: Fix focus trap disabling the dropdown toggle function. Pipe onSelect event to DropdownItem, allowing its disabled property to control if the event is fired. In our example docs, this means that clicking a disabled link will not close the dropdown.

Dropdown interaction issues

---

packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggle.test.js
packages/patternfly-4/react-core/src/components/Dropdown/Toggle.js

**What**:
Fixes #1131, correcting dropdown behavior on iOS devices.
Also fixes a broken test that was never running assertions due to setTimeout.

fix(DropdownToggle): Listen for touch events on the document to close a Toggle on mobile

---

packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.d.ts

Fix https://github.com/patternfly/patternfly-react/issues/1172
Missing attribute isPlain

PF4: Add missing attribute isPlain to Dropdown

---

packages/patternfly-4/react-core/src/components/ApplicationLauncher/__snapshots__/ApplicationLauncher.test.js.snap
packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.js
packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.test.js
packages/patternfly-4/react-core/src/components/Dropdown/DropdownItem.js
packages/patternfly-4/react-core/src/components/Dropdown/DropdownMenu.js
packages/patternfly-4/react-core/src/components/Dropdown/Item.js
packages/patternfly-4/react-core/src/components/Dropdown/Separator.js
packages/patternfly-4/react-core/src/components/Dropdown/Toggle.js
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/DropdownItem.test.js.snap
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/DropdownToggle.test.js.snap
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Toggle.test.js.snap
packages/patternfly-4/react-core/src/components/Dropdown/dropdownConstants.js

**What**: Dropdown menus should be navigable via up and down arrow keys. 
**Refers to issue**: #1002

Dropdown arrow key support

---

packages/patternfly-4/react-core/src/components/Button/Button.js

#1184
**What** :Button should not require and aria-label for pf-m-plain modifier 

fix(Button): make aria-label optional prop

---

packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardSettings.js

fixed the login card settings visibility,
show only when `rememberMe` / `forgotPassword` labels exists.

fix(Login Page): fix settings visibility

---

packages/patternfly-3/patternfly-react/src/components/DualListSelector/DualList.js
packages/patternfly-3/patternfly-react/src/components/DualListSelector/DualList.test.js
packages/patternfly-3/patternfly-react/src/components/DualListSelector/helpers.js

After items were moved between the lists,
they should not be selected as specified in the design.

fix(DualList): de-Select items after the transition between lists.

---

packages/patternfly-4/react-core/package.json

adds babel-transform-es2015-modules-umd for umd module support
fixes: #1142 
**What**:
Docs for [transform-es2015-modules-umd](https://babeljs.io/docs/en/babel-plugin-transform-es2015-modules-umd)
This will convert es2015/esm modules to umd modules so that we can support umd module consumers.
In the future, we may consider rollup-plugin-babel or rollup-plugin-typescript for further support, but this should be the shortest path to support UMD modules today. The hope is to further support teams using RequireJS/CommonJS/SystemJS build systems.

feat(umd modules): adds babel-transform-es2015-modules-umd 

---

packages/patternfly-4/react-core/src/components/Chip/Chip.d.ts
packages/patternfly-4/react-core/src/components/Chip/Chip.docs.js
packages/patternfly-4/react-core/src/components/Chip/Chip.js
packages/patternfly-4/react-core/src/components/Chip/Chip.test.js
packages/patternfly-4/react-core/src/components/Chip/ChipButton.d.ts
packages/patternfly-4/react-core/src/components/Chip/ChipButton.js
packages/patternfly-4/react-core/src/components/Chip/__snapshots__/Chip.test.js.snap
packages/patternfly-4/react-core/src/components/Chip/examples/SimpleChip.js
packages/patternfly-4/react-core/src/components/Chip/index.d.ts
packages/patternfly-4/react-core/src/components/Chip/index.js
packages/patternfly-4/react-core/src/components/index.ts

Chip component

---

packages/patternfly-4/react-core/src/components/Dropdown/DropdownItem.js
packages/patternfly-4/react-core/src/demos/Toolbar/examples/ComplexToolbarDemo.js
packages/patternfly-4/react-core/src/demos/Toolbar/examples/SimpleToolbarDemo.js

**What**:
This PR fixes problems when DropdownItem is React child, without it the ref wouldn't be assigned and was undefined when tried to access it in componentDidmount.
Fixes: #1191

fix(Dropdown): Pass down ref for dropdown item

---

lerna.json
package.json
packages/patternfly-4/verifyCoreVersions.js
scripts/generators/package/index.js
scripts/lernaHelpers.js
storybook/webpack.config.js
yarn.lock

**What**:
Helps #1158 
Adds lerna 3 support to current build scripts. We cannot move PF3's Storybook to lerna3 references until we upgrade Storybook to [v4](https://github.com/storybooks/storybook/issues/4163#issuecomment-431849120) due to async references, this however will require moving PF3 build scripts to babel7.
This is the fastest track to hopefully supporting lerna3 and prereleases/alpha tags of lerna packages along with several other lerna 3 updates. 
Still testing in a sandbox at the moment...
Some relevant lerna3 APIs discussed [here](https://github.com/lerna/lerna/issues/1848#issuecomment-451612983).
None

build(lerna3): enhances build scripts to support lerna3

---

packages/patternfly-4/react-core/src/components/Dropdown/DropdownItem.js

previous was only done for button type
**What**: Changed onClick to be passed to any child element if it is defined in the DropdownItem, instead of only to button type elements.
**Fixes issue**: #1195

fix(Dropdown): pass onClick to any dropdown item if present

---

packages/patternfly-4/react-charts/package.json
packages/patternfly-4/react-core/package.json
packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalBox.test.js.snap
packages/patternfly-4/react-core/src/components/Alert/Alert.d.ts
packages/patternfly-4/react-core/src/components/Alert/Alert.js
packages/patternfly-4/react-core/src/components/Alert/Alert.test.js
packages/patternfly-4/react-core/src/components/Alert/AlertBody.js
packages/patternfly-4/react-core/src/components/Alert/__snapshots__/Alert.test.js.snap
packages/patternfly-4/react-core/src/components/Alert/examples/DangerAlert.js
packages/patternfly-4/react-core/src/components/Alert/examples/InfoAlert.js
packages/patternfly-4/react-core/src/components/Alert/examples/SuccessAlert.js
packages/patternfly-4/react-core/src/components/Alert/examples/WarningAlert.js
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
packages/patternfly-4/react-styled-system/package.json
packages/patternfly-4/react-table/package.json
packages/patternfly-4/react-table/src/components/Table/__snapshots__/Table.test.js.snap
packages/patternfly-4/react-tokens/package.json
packages/react-icons/package.json
yarn.lock

**What**:
Fixes #1036.
In order to get the CSS for the close button, this PR upgrades `@patternfly/patternfly-next` from 1.0.120 to 1.0.126. This upgrade causes some inconsistencies with spacing in the Alert component, which I fixed by wrapping the alert description (children of `AlertBody`) in a `<p>` tag, which is consistent with the `alert-description.hbs` template in core (https://github.com/patternfly/patternfly-next/blob/master/src/patternfly/components/Alert/alert-description.hbs) and by changing the Action Button variant from "secondary" to "link", which is consistent with the changes to the core examples (https://github.com/patternfly/patternfly-next/pull/1208/files#diff-80f605f510a73d9a008b8bec47b6b75dR42). These fixes are in a separate commit to isolate them from the actual …

feat(Alert): Add optional Close button to Alert via onClose prop

---

packages/patternfly-3/patternfly-react/src/components/DualListSelector/DualList.stories.js
packages/patternfly-3/patternfly-react/src/components/DualListSelector/components/DualListHiddenSelect.js
packages/patternfly-3/patternfly-react/src/components/DualListSelector/helpers.js

Hidden inputs should reflect the whole list and not just the selected items.
The main idea of the dual list is to mimic the html select behavior into a prettier implementation
and when the consumers will choose that one side is the "selected-side", they will be able to send of all its items on submitting in a form for example.
this PR also fixes a test warning, and storybook error

fix(DualList): fix hidden inputs

---

packages/patternfly-4/react-docs/src/components/example/liveDemo.js
packages/patternfly-4/react-docs/src/components/layouts/index.js
packages/patternfly-4/react-docs/src/components/page/page.styles.js

feat(example): Add dark theme toggle button & change background color

---

packages/patternfly-4/react-core/src/components/Dropdown/DropdownMenu.js
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.js.snap

fix #1218
**What**:
- Error in runtime after clicking on Dropdown when using using children to define Dropdown items
- Styling of items was broken when using children to define Dropdown items
Had to add a list wrapper to dropdown children to fix the ser error and styling.

fix(DropdownMenu): Fixes dropdown menu when using items as children.

---

packages/patternfly-3/patternfly-react/src/components/MessageDialog/MessageDialog.js
packages/patternfly-3/patternfly-react/src/components/MessageDialog/MessageDialog.test.js

**What**:
fixes #1122 
`primaryAction` and `primaryActionButtonContent` are required unless `footer` is set.
However, currently an error message will be displayed if `footer` is set and not `primaryAction` or `primaryActionButtonContent`.
This commit fixes this conflict by checking if `footer` is set and if it does these props won't be required.

fix(MessageDialog): conflict between footer and primaryAction props

---

packages/patternfly-4/react-core/src/components/Dropdown/Toggle.js

**What**:
If user clicks anywhere on screen and dropdown is present it will automatically scroll to such dropdown even if it's not opened.
https://github.com/RedHatInsights/insights-frontend-components/issues/222

fix(Dropdown): Do not focus Dropdown if menu is not opened

---

packages/react-icons/README.md

docs(react-icons): Add props table to README.md

---

packages/patternfly-3/patternfly-react/src/components/Slider/Slider.js

Invoke onSlide when slider-input changes
Fixes #1221

fix(Slider): Update state when properties are updated.

---

packages/patternfly-4/react-core/src/components/Form/Form.js
packages/patternfly-4/react-core/src/components/Form/__snapshots__/ActionGroup.test.js.snap
packages/patternfly-4/react-core/src/components/Form/__snapshots__/Form.test.js.snap
packages/patternfly-4/react-core/src/components/Form/__snapshots__/FormGroup.test.js.snap

**What**: adding novalidate flag to form to match core. It's possible that a core update might also be required but I wasn't seeing the error anymore locally.
**Refer to issue**: #1039

feat(Form): add novalidate flag to form

---

packages/patternfly-4/react-core/src/components/Page/PageHeader.d.ts
packages/patternfly-4/react-core/src/components/Page/PageHeader.js
packages/patternfly-4/react-core/src/components/Page/PageSidebar.js
packages/patternfly-4/react-core/src/components/Page/__snapshots__/Page.test.js.snap
packages/patternfly-4/react-core/src/components/Page/__snapshots__/PageHeader.test.js.snap
packages/patternfly-4/react-core/src/components/Page/examples/VerticalPage.js
packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutDefaultNav.js
packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutExpandableNav.js
packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutGroupsNav.js
packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutSimpleNav.js

**What**:
fixes #1136 
//cc @jgiardino

fix(Page): improve a11y in sidebar and header

---

packages/patternfly-3/patternfly-react-extensions/src/components/BadgedResource/BadgedResource.js

**What**: A fix following discussion on #1238

fix(BadgedResource): don't restrict resourceName to a string

---

packages/patternfly-4/react-core/src/components/Chip/Chip.d.ts
packages/patternfly-4/react-core/src/components/Chip/Chip.js

Replaced hard-coded check with refs/check for CSS overflow. Also made children optional to allow for empty chips.
Fixes #1197.

fix(Chip): Replace check for length of chip text with refs

---

packages/patternfly-4/react-table/src/components/Table/__snapshots__/Table.test.js.snap
packages/patternfly-4/react-table/src/components/Table/utils/decorators/collapsible.js
packages/patternfly-4/react-table/src/components/Table/utils/transformers.test.js

**What**:
When row is not collapsed do not pass value down so other props will not be effected by this object. This helps to prevent accidental `title` on first cell.

fix(Table): Do not return value if table is not collapsed

---

packages/patternfly-4/react-docs/gatsby-node.js
packages/react-icons/build/generatorConfig.js

**What**:
Fixes #1246.
Windows uses backslashes instead of the Unix style forward slashes to separate file path segments.
This caused problems with the Gatsby build of the PF4 react-docs package.
These changes should resolve this by taking both types of slashes into account in the build scripts.

fix(build): Support building Gatsby app under Windows

---

packages/patternfly-4/react-docs/package.json

**What**:
Adds the suggested fix [here](https://github.com/gatsbyjs/gatsby/issues/2796#issuecomment-342017625) to increase Gatsby's memory while compiling static assets.
Bumping from [1.5ish gbs](https://github.com/nodejs/help/issues/1377#issuecomment-403801254) to 4gb. I think we can technically increase to 7.5 gb from the [Ubuntu Travis image docs](https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system), but this should be enough for now...

build(docbuild): increase gatsby build memory

---

packages/patternfly-4/react-table/src/components/Table/Body.js
packages/patternfly-4/react-table/src/components/Table/ExpandableRowContent.js
packages/patternfly-4/react-table/src/components/Table/RowWrapper.js
packages/patternfly-4/react-table/src/components/Table/SelectColumn.js
packages/patternfly-4/react-table/src/components/Table/SortColumn.js
packages/patternfly-4/react-table/src/components/Table/Table.js
packages/patternfly-4/react-table/src/components/Table/__snapshots__/Table.test.js.snap
packages/patternfly-4/react-table/src/components/Table/utils/decorators/cellActions.js
packages/patternfly-4/react-table/src/components/Table/utils/decorators/collapsible.js
packages/patternfly-4/react-table/src/components/Table/utils/decorators/selectable.js
packages/patternfly-4/react-table/src/components/Table/utils/decorators/sortable.js

**What**:
* When using react table there is tons of warnings due to missing exports in patternfly next styles. That is caused by using spread instead of default import. It is much safer (but a bit less readable) to use direct imports.
* Allow first row to be collapsible by checking undefined instead of casting Boolean.
* Do not show select in collapsed child unless show checkbox is engorced on row.

fix(Table): Use direct imports instead of spread

---

packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxHeader.js
packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalBoxHeader.test.js.snap

In PF core heading types of AboutModal were updated. This PR updates PF react with those changes.
closes #1265

fix(AboutModal): Use paragraph in heading

---

packages/patternfly-4/react-table/src/components/index.d.ts
packages/patternfly-4/react-table/src/index.d.ts

**What**: Add index.d.ts for react-table

Fix react-table not expose index.d.ts issue

---

package.json
packages/patternfly-3/patternfly-react-extensions/package.json
packages/patternfly-3/patternfly-react/package.json
packages/patternfly-3/react-console/package.json
packages/react-icons/package.json
yarn.lock

With the current setup, Patternfly's npm scripts cannot be executed in a Windows environment.
The changes proposed by this PR should make all npm scripts platform independent and runnable on both Windows and Linux/OS X environments.
- **Use  `shx` to make Unix specific commands platform independent**: Commands like `rm`, `cp` etc. that are used in PF's npm scripts are not supported by Windows command lines. The [`shx` command line tool](https://www.npmjs.com/package/shx) provides a layer of abstraction that makes basic unix commands work cross-platform with the established Unix syntax.
- **Use `cross-var` to make Unix specific command line variable syntax platform independent**: The PF3 packages use Unix style variables `$variableName` to refer to environment variables in their npm …

fix(build): Support running npm scripts under Windows

---

packages/patternfly-4/react-table/src/components/Table/ExpandableRowContent.js
packages/patternfly-4/react-table/src/components/Table/RowWrapper.js
packages/patternfly-4/react-table/src/components/Table/SortColumn.js
packages/patternfly-4/react-table/src/components/Table/utils/__snapshots__/transformers.test.js.snap
packages/patternfly-4/react-table/src/components/Table/utils/decorators/cellActions.js
packages/patternfly-4/react-table/src/components/Table/utils/decorators/collapsible.js
packages/patternfly-4/react-table/src/components/Table/utils/decorators/selectable.js
packages/patternfly-4/react-table/src/components/Table/utils/decorators/sortable.js
packages/patternfly-4/react-table/src/components/Table/utils/transformers.test.js

**What**:
Re-adds changes made in this PR https://github.com/patternfly/patternfly-react/pull/1237 because they were removed in https://github.com/patternfly/patternfly-react/pull/1304 

fix(Table): Use direct imports for styles

---

packages/patternfly-4/react-core/src/components/Tooltip/Tooltip.d.ts
packages/patternfly-4/react-core/src/components/Tooltip/Tooltip.js
packages/patternfly-4/react-core/src/components/Tooltip/__snapshots__/Tooltip.test.js.snap

I added an optional delay prop to the Tooltip component to specify the entrance delay. The external tooltip library defaults to an entrance delay of 0 ms.
The null in {[delay, null]} gets the external tooltip library to use its default exit delay (20 ms). Controlling the exit delay wasn't mentioned in the issue, so I didn't add a prop for it. Let me know if you want an extra prop for that.
I didn't make any changes to the overrides; my IDE removed the spaces at the ends of the lines. I can set it back the way it was if you want. Let me know.
Fixes #1161.

feat(Tooltip): Add optional delay prop to Tooltip

---

packages/patternfly-3/patternfly-react-extensions/package.json
packages/patternfly-3/patternfly-react/package.json
packages/patternfly-3/react-console/package.json

**What**: Fix cross-var causing babel-loader error on OSX 10.13.6:
```
$ yarn build:sass && yarn build:less
$ shx mkdir -p dist/sass && shx cp -r sass/patternfly-react-extensions/* dist/sass && cross-var node-sass --output-style compressed --include-path sass --include-path $npm_package_sassIncludes_patternfly --include-path $npm_package_sassIncludes_bootstrap --include-path $npm_package_sassIncludes_fontAwesome -o dist/css sass/patternfly-react-extensions.scss
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run prebuild stderr:
/Users/zallen/src/patternfly-react/node_modules/babel-core/lib/transformation/file/options/option-manager.js:328
throw e;
^ …
```

build(cross-var): use cross-env instead of cross-var to fix OSX 10.13.6 error

---

packages/patternfly-4/react-core/src/components/Nav/examples/NavDefaultList.js
packages/patternfly-4/react-core/src/components/Nav/examples/NavExpandableList.js
packages/patternfly-4/react-core/src/components/Nav/examples/NavExpandableTitlesList.js
packages/patternfly-4/react-core/src/components/Nav/examples/NavGroupedList.js
packages/patternfly-4/react-core/src/components/Nav/examples/NavHorizontalList.js
packages/patternfly-4/react-core/src/components/Nav/examples/NavMixedList.js
packages/patternfly-4/react-core/src/components/Nav/examples/NavSimpleList.js
packages/patternfly-4/react-core/src/components/Nav/examples/NavTertiaryList.js

**What**:
Clicking on the links in the Nav examples refresh the page itself and causing the state to be reset.
Adding `preventDefault` will prevent from refreshing the page and fix this problem.
fixes #1263 
//cc @ibolton336

fix(Nav): do not render the examples page

---

packages/patternfly-4/react-core/src/components/Popover/Popover.d.ts
packages/patternfly-4/react-core/src/components/Tooltip/Tooltip.d.ts
packages/patternfly-4/react-core/src/helpers/GenerateId/GenerateId.d.ts

**What**:
fixes #1340 
`Element` is not currently exported in the version of `@types/react` used here, so updating with `ReactElement`. Also, `Omit<Props>` is incorrectly extending the interface for these components (which internally render div's). Updating to `HTMLProps<HTMLDivElement>` respectively.

fix(types): popover, tooltip, and helper types fixes

---

packages/patternfly-4/react-core/src/components/Breadcrumb/Breadcrumb.js
packages/patternfly-4/react-core/src/components/Breadcrumb/__snapshots__/Breadcrumb.test.js.snap
packages/patternfly-4/react-core/src/components/Nav/Nav.d.ts
packages/patternfly-4/react-core/src/components/Nav/Nav.js
packages/patternfly-4/react-core/src/components/Nav/Nav.test.js
packages/patternfly-4/react-core/src/components/Nav/__snapshots__/Nav.test.js.snap
packages/patternfly-4/react-core/src/components/Nav/examples/NavDefaultList.js
packages/patternfly-4/react-core/src/components/Nav/examples/NavExpandableList.js
packages/patternfly-4/react-core/src/components/Nav/examples/NavExpandableTitlesList.js
packages/patternfly-4/react-core/src/components/Nav/examples/NavGroupedList.js
packages/patternfly-4/react-core/src/components/Nav/examples/NavHorizontalList.js
packages/patternfly-4/react-core/src/components/Nav/examples/NavMixedList.js
packages/patternfly-4/react-core/src/components/Nav/examples/NavSimpleList.js
packages/patternfly-4/react-core/src/components/Nav/examples/NavTertiaryList.js
packages/patternfly-4/react-core/src/components/Page/PageHeader.js
packages/patternfly-4/react-core/src/components/Page/__snapshots__/Page.test.js.snap
packages/patternfly-4/react-core/src/components/Page/__snapshots__/PageHeader.test.js.snap

I updated the aria labels for Nav, Breadcrumbs, and PageHeader as requested by @jgiardino. Tabs and Pagination aren't in PF4 yet, so I wasn't able to address those in this PR. (Tabs are being added by Titani in a separate PR.)
I also updated the examples, tests, and snapshots for Nav and Breadcrumbs to reflect the new aria labels.
Fixes #1182.

fix: Add consistent aria labels for <nav> elements

---

packages/patternfly-4/react-core/src/components/Alert/Alert.js
packages/patternfly-4/react-core/src/components/Alert/AlertActionCloseButton.js
packages/patternfly-4/react-core/src/components/Alert/__snapshots__/Alert.test.js.snap
packages/patternfly-4/react-core/src/components/Alert/examples/DangerAlert.js
packages/patternfly-4/react-core/src/components/Alert/examples/InfoAlert.js
packages/patternfly-4/react-core/src/components/Alert/examples/SuccessAlert.js
packages/patternfly-4/react-core/src/components/Alert/examples/WarningAlert.js

I updated the aria-label for the close button and the screen reader text to be more descriptive and removed the caret in the Danger Alert example. I also replaced all instances of "notification" with "alert" and updated the Alert snapshots.
Fixes #1286.

fix(Alert): Make Alert consistent with core

---

packages/patternfly-4/react-table/README.md
packages/patternfly-4/react-table/src/components/Table/Body.js
packages/patternfly-4/react-table/src/components/Table/BodyCell.js
packages/patternfly-4/react-table/src/components/Table/HeaderCell.js
packages/patternfly-4/react-table/src/components/Table/__snapshots__/Table.test.js.snap
packages/patternfly-4/react-table/src/components/Table/examples/SimpleTable.js
packages/patternfly-4/react-table/src/components/Table/utils/__snapshots__/transformers.test.js.snap
packages/patternfly-4/react-table/src/components/Table/utils/decorators/cellActions.js
packages/patternfly-4/react-table/src/components/Table/utils/decorators/collapsible.js
packages/patternfly-4/react-table/src/components/Table/utils/decorators/selectable.js

**What**:
Colspan is not fully supported in reactabular implementation and they ignore it. However with this implementation we will set for each cell provided as data and for custom calculated cells (select, expand, collapsed, actions) special property called `isVisible` this will eventually allow consumers to hide some columns if they want to as well.

fix(Table): allow colspan to be set in props for each cell

---

packages/patternfly-3/patternfly-react/src/components/ListView/ListViewItem.js

**What**:
Fix initExpanded being passed to children

fix(ListViewItem) - initExpanded being passed to children

---

packages/patternfly-4/react-core/src/components/Nav/NavToggle.js

fix(nav): Allow nav to expand by prop change

---

packages/patternfly-3/patternfly-react/src/components/Tabs/Tabs.stories.js
storybook/constants/siteConstants.js

**What**:
react-bootstrap's v1 release targets bootstrap v4, which is incompatible with patternfly.
The new documentation they released breaks all of our deep links into the old docs from Storybook.
This legacy URL comes from the "To find the documentation for the latest Bootstrap 3 compatible
release, go here" link at https://github.com/react-bootstrap/react-bootstrap.

docs(siteConstants.js): PF3: Link to react-bootstrap legacy docs instead of new (incompatible) docs

---

packages/patternfly-4/react-table/src/components/Table/Table.d.ts
packages/patternfly-4/react-table/src/components/Table/Table.js

**What**:
Allow different data types for row cells.
cells: [`String | Number | HTML | { title: String | Number | HTML }`]

fix(Table): Allow mixins of object, strings and numbers as row cell

---

packages/patternfly-4/react-table/src/components/Table/BodyWrapper.js
packages/patternfly-4/react-table/src/components/Table/CollapseColumn.js
packages/patternfly-4/react-table/src/components/Table/SortColumn.js
packages/patternfly-4/react-table/src/components/Table/Table.js
packages/patternfly-4/react-table/src/components/Table/__snapshots__/Table.test.js.snap
packages/patternfly-4/react-table/src/components/Table/examples/CollapsibleTable.js
packages/patternfly-4/react-table/src/components/Table/utils/headerUtils.js
packages/patternfly-4/react-table/src/components/Table/utils/headerUtils.test.js

**What**:
Because we updated to newer version of PF-next we have to update collapsible and sort implementation.

fix(Table): Update table styles based on new styling from pf-next v 175

---

packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncher.d.ts
packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncher.js
packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncherMenu.js
packages/patternfly-4/react-core/src/components/ApplicationLauncher/Toggle.js
packages/patternfly-4/react-core/src/components/ApplicationLauncher/__snapshots__/ApplicationLauncher.test.js.snap
packages/patternfly-4/react-core/src/components/ApplicationLauncher/applicationLauncherConstants.d.ts
packages/patternfly-4/react-core/src/components/ApplicationLauncher/applicationLauncherConstants.js
packages/patternfly-4/react-core/src/components/ApplicationLauncher/examples/SimpleApplicationLauncher.js
packages/patternfly-4/react-core/src/components/ApplicationLauncher/examples/TooltipApplicationLauncher.js
packages/patternfly-4/react-core/src/components/Dropdown/DropdownItem.js
packages/patternfly-4/react-core/src/components/Dropdown/Item.js
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.js.snap

Refactored ApplicationLauncher into its own component. It still uses DropdownItem and dropdown contexts so as not to break client code.
Fixes #1241.

refactor(ApplicationLauncher): Refactor so it no longer uses Dropdown

---

packages/patternfly-4/react-table/src/components/Table/Table.js
packages/patternfly-4/react-table/src/components/Table/__snapshots__/Table.test.js.snap
packages/patternfly-4/react-table/src/components/Table/examples/SelectableTable.js
packages/patternfly-4/react-table/src/components/Table/utils/decorators/selectable.js

When all rows of the table are selected, the select-all checkbox is now selected automatically. Likewise, when the select-all checkbox is selected, and I deselect one or more rows, the select-all check box is deselected automatically.
Fixes #1352

PF4 Table:  'Select All' checkbox updates

---

packages/patternfly-4/react-core/src/components/FormSelect/FormSelect.d.ts

**What**:
The `FormSelect` is not using original `onChange(event)`   
It is actually using `onChange(value, event)`
https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-4/react-core/src/components/FormSelect/FormSelect.js#L47
```
this.props.onChange(event.currentTarget.value, event);
```

fix(core): FormSelect onChange value type was missing

---

packages/patternfly-4/react-tokens/build/generateTokens.js

**What**:
This fixes bug that shows incorrect values for light theme on tokens page. Issue https://github.com/patternfly/patternfly-react/issues/1329 to allow importing dark theme values as well. Before this PR we didn't really knew which value was used and vars were not matching actual value.

fix(tokens): Use only light theme variables

---

packages/patternfly-4/react-table/src/components/Table/Body.js
packages/patternfly-4/react-table/src/components/Table/BodyWrapper.js
packages/patternfly-4/react-table/src/components/Table/Table.js
packages/patternfly-4/react-table/src/components/Table/__snapshots__/Table.test.js.snap

**What**:
React automatically checks if there were some changes in rows, help him with this by providing component instead of function to row wrapper. This will eliminate most of the re-renders if shallow data remain the same.
Parially resolves: https://github.com/patternfly/patternfly-react/issues/1399

fix(Table): Pass calculated rows to body wrapper to eliminate re-renders

---

.circleci/release.sh
packages/patternfly-3/patternfly-react-extensions/package.json
packages/patternfly-3/patternfly-react/package.json
packages/patternfly-3/react-console/package.json
packages/patternfly-4/react-core/package.json
packages/patternfly-4/react-docs/package.json
packages/patternfly-4/react-table/package.json

build(noerr): suppress error on no package changes

---

packages/patternfly-4/react-charts/src/components/ChartAxis/ChartAxis.d.ts
packages/patternfly-4/react-charts/src/components/ChartAxis/ChartAxis.js
packages/patternfly-4/react-charts/src/components/ChartAxis/ChartAxis.test.js
packages/patternfly-4/react-charts/src/components/ChartAxis/__snapshots__/ChartAxis.test.js.snap
packages/patternfly-4/react-charts/src/components/ChartAxis/index.d.ts
packages/patternfly-4/react-charts/src/components/ChartAxis/index.js
packages/patternfly-4/react-charts/src/components/LineChart/examples/SimpleChart.js
packages/patternfly-4/react-charts/src/components/index.d.ts
packages/patternfly-4/react-charts/src/components/index.js

ChartAxis is a wrapper for VictoryAxis, which allows users to customize chart tic labels along the x/y axis. 
This will allow Cost Management project to customize the tic labels as needed. For example, instead of crowding the chart with too many labels, we can limit the number and customize the label values.
Cost Management Example:
PatternFly React Example:

PF4 Charts: Add ChartAxis for custom tic labels

---

packages/patternfly-4/react-core/src/components/Modal/Modal.d.ts
packages/patternfly-4/react-core/src/components/Modal/Modal.docs.js
packages/patternfly-4/react-core/src/components/Modal/Modal.js
packages/patternfly-4/react-core/src/components/Modal/ModalBox.d.ts
packages/patternfly-4/react-core/src/components/Modal/ModalBox.js
packages/patternfly-4/react-core/src/components/Modal/ModalContent.d.ts
packages/patternfly-4/react-core/src/components/Modal/ModalContent.js
packages/patternfly-4/react-core/src/components/Modal/__snapshots__/ModalContent.test.js.snap
packages/patternfly-4/react-core/src/components/Modal/examples/SmallModal.js
packages/patternfly-4/react-core/src/components/Modal/examples/WidthModal.js

**What**:
closes #1291 and #1138 
//cc @mcoker can you take a look to make sure I didn't miss anything. Thanks.

fix(modalbox): add the small modifier to modalbox

---

packages/patternfly-4/react-table/src/components/Table/Body.js

**What**:
Is consumers has some event bound to row click (navigation for instance) they don't want to fire these events when row is selected or when clicking on button. 
Any other event prevention should be done on consumer side.

fix(Table): Disable row click when clicked on select or button

---

packages/patternfly-4/react-charts/package.json
packages/patternfly-4/react-charts/src/components/ChartLegend/ChartLegend.js
packages/patternfly-4/react-charts/src/components/ChartLegend/ChartLegend.test.js
packages/patternfly-4/react-charts/src/components/ChartPoint/ChartPoint.d.ts
packages/patternfly-4/react-charts/src/components/ChartPoint/ChartPoint.js
packages/patternfly-4/react-charts/src/components/ChartPoint/ChartPoint.test.js
packages/patternfly-4/react-charts/src/components/ChartPoint/__snapshots__/ChartPoint.test.js.snap
packages/patternfly-4/react-charts/src/components/ChartPoint/index.d.ts
packages/patternfly-4/react-charts/src/components/ChartPoint/index.js
packages/patternfly-4/react-charts/src/components/ChartPoint/path-helpers.js
packages/patternfly-4/react-charts/src/components/LineChart/examples/SimpleChart.js
packages/patternfly-4/react-charts/src/components/LineChart/examples/common/getContainerProps.js
yarn.lock

The Cost Management project needs to show charts with dotted lines. However, Victory does not support a dash symbol in the legend -- only symbols like plus, minus, star, etc.
Ultimately, my plan is to submit the new symbol upstream to Victory. However, I believe it needs to bake here for a bit. It's possible PF4 may still adjust the line heights for these symbols?
Per Kyle's high fidelity mocks:
https://redhat.invisionapp.com/share/ENPJQTBXTAC#/screens/336412758
Cost Management Charts:
PatternFly React Example:

PF4 Charts: Added ChartPoint for custom dash legend symbol

---

packages/patternfly-4/react-charts/src/components/ChartLegend/ChartLegend.js
packages/patternfly-4/react-charts/src/components/ChartLegend/__snapshots__/ChartLegend.test.js.snap
packages/patternfly-4/react-charts/src/components/ChartPoint/ChartPoint.d.ts
packages/patternfly-4/react-charts/src/components/ChartPoint/ChartPoint.js
packages/patternfly-4/react-charts/src/components/ChartPoint/__snapshots__/ChartPoint.test.js.snap
packages/patternfly-4/react-charts/src/components/ChartPoint/index.d.ts

Fixed a couple errors after testing ChartPoint with the Cost Management UI.
- ChartLegend must make use of new ChartPoint to support the 'dash' symbol
- Fixed TypeScript error encountered while building Cost Management
- Fixed invalid prop symbol warning seen with ChartLine example
TypeScript build error:
Browser invalid prop symbol warning:

Fixed ChartPoint errors

---

packages/patternfly-4/react-core/src/components/DataList/DataList.test.js
packages/patternfly-4/react-core/src/components/DataList/DataListAction.js
packages/patternfly-4/react-core/src/components/DataList/DataListCell.js
packages/patternfly-4/react-core/src/components/DataList/DataListContent.js
packages/patternfly-4/react-core/src/components/DataList/DataListItem.js
packages/patternfly-4/react-core/src/components/DataList/DataListToggle.d.ts
packages/patternfly-4/react-core/src/components/DataList/DataListToggle.js
packages/patternfly-4/react-core/src/components/DataList/examples/ExpandableDataList.js
packages/patternfly-4/react-core/src/components/DataList/examples/ModifiersDataList.js

The DataListToggle aria label now defaults to "Details." If the consumer provides an aria label, there is no aria-labelledby. If the consumer uses the default aria label, aria-labelledby will be in the
following format: aria-labelledby=`${aria-labelledby of DataListItem} ${id}`. Users can also add an id prop to DataListContent and a corresponding aria-controls prop to DataListToggle.
Affects #1163.

fix(DataList): Add aria-label and aria-labelledby improvements

---

LICENSE
package.json
packages/eslint-plugin-patternfly-react/package.json
packages/patternfly-3/patternfly-react-extensions/package.json
packages/patternfly-3/patternfly-react/package.json
packages/patternfly-3/react-console/package.json
packages/patternfly-4/react-charts/package.json
packages/patternfly-4/react-core/package.json
packages/patternfly-4/react-docs/package.json
packages/patternfly-4/react-integration/package.json
packages/patternfly-4/react-styled-system/package.json
packages/patternfly-4/react-styles/package.json
packages/patternfly-4/react-table/package.json
packages/patternfly-4/react-tokens/package.json
packages/react-codemods/package.json
packages/react-icons/package.json
scripts/generators/package/package.json.hbs

Closes http://github.com/patternfly/patternfly/issues/1093 - we've decided to move the PatternFly libraries to the MIT package to be consistent.

chore(license): update license to MIT

---

packages/patternfly-4/react-core/src/components/Nav/Nav.js
packages/patternfly-4/react-core/src/components/Nav/NavExpandable.d.ts
packages/patternfly-4/react-core/src/components/Nav/NavExpandable.js
packages/patternfly-4/react-core/src/components/Nav/NavToggle.js
packages/patternfly-4/react-core/src/components/Nav/__snapshots__/Nav.test.js.snap
packages/patternfly-4/react-core/src/components/Nav/examples/NavExpandableList.js
packages/patternfly-4/react-core/src/components/Nav/examples/NavExpandableTitlesList.js

fix(nav): Fix bug where previous was expanding on select

---

packages/patternfly-4/react-core/src/components/InputGroup/InputGroup.d.ts
packages/patternfly-4/react-core/src/components/InputGroup/InputGroup.docs.js
packages/patternfly-4/react-core/src/components/InputGroup/InputGroup.js
packages/patternfly-4/react-core/src/components/InputGroup/InputGroup.test.js
packages/patternfly-4/react-core/src/components/InputGroup/InputGroupText.d.ts
packages/patternfly-4/react-core/src/components/InputGroup/InputGroupText.js
packages/patternfly-4/react-core/src/components/InputGroup/examples/SimpleInputGroups.js
packages/patternfly-4/react-core/src/components/InputGroup/index.d.ts
packages/patternfly-4/react-core/src/components/InputGroup/index.js
packages/patternfly-4/react-core/src/components/index.ts

**What**:
Added Patternfly 4 input group to react.

feat(InputGroup): Add InputGroup to PF4

---

packages/patternfly-3/patternfly-react/sass/patternfly-react/_login-page.scss
packages/patternfly-3/patternfly-react/src/components/LoginPage/LoginPage.stories.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/LoginPageFixtures.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/__snapshots__/LoginPage.test.js.snap
packages/patternfly-3/patternfly-react/src/components/LoginPage/__snapshots__/SocialLoginPage.test.js.snap
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardForm.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardInput.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardWithValidation.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginFormError.js

Continued to the design refactoring [discussion](https://github.com/patternfly/patternfly-design/issues/671#issuecomment-457323229l)
where we decided to add an ability to pass the inputs errors to the top of the form,
**First glimpse:**

fix(LoginPage): add an option to display errors only on top of the form

---

packages/react-icons/build/generateIcons.js
packages/react-icons/build/icons.js
packages/react-icons/package.json
yarn.lock

**What**:
Because new icons were added to solid icons we should pull them and expose them for others as well.
Also add new package with regular icons (outlined solid) with prefix `outlined${IconName}` so we don't have any name clashes.
Overall adds 277 of new icons!

feat(Icons): Add fa regular icons and update solid icons

---

packages/patternfly-4/react-core/src/components/InputGroup/InputGroupText.d.ts
packages/patternfly-4/react-core/src/components/InputGroup/examples/SimpleInputGroups.js

fix(inputgroup): fix typescript and examples

---

packages/patternfly-3/patternfly-react/package.json
packages/patternfly-3/patternfly-react/src/components/TypeAheadSelect/TypeAheadSelect.stories.js
packages/patternfly-3/patternfly-react/src/components/TypeAheadSelect/TypeAheadSelect.test.js
packages/patternfly-3/patternfly-react/src/components/TypeAheadSelect/__snapshots__/AsyncTypeAheadSelect.test.js.snap
packages/patternfly-3/patternfly-react/src/components/TypeAheadSelect/__snapshots__/TypeAheadSelect.test.js.snap

fix(TypeAhead): upgrade typeahead to v3.4.1

---

packages/patternfly-4/react-core/src/components/Nav/NavExpandable.d.ts
packages/patternfly-4/react-core/src/components/Nav/NavExpandable.js
packages/patternfly-4/react-core/src/components/Nav/NavToggle.js
packages/patternfly-4/react-core/src/components/Nav/__snapshots__/Nav.test.js.snap
packages/patternfly-4/react-core/src/components/Nav/examples/NavExpandableList.js
packages/patternfly-4/react-core/src/components/Nav/examples/NavExpandableTitlesList.js

fix(navExpand): remove defaultExpand in favor of just using isExpanded

---

packages/patternfly-4/react-core/src/components/Nav/NavExpandable.js

**What**:
fix React warning introduced in #1490 
```
Warning: Unknown event handler property `onExpand`. It will be ignored.
in li (created by NavToggle)
in NavToggle
in NavExpandable (created by NavSection)
in NavSection (created by Connect(NavSection))
in Connect(NavSection) (created by Navigation)
in ul (created by NavList)
in NavList (created by Navigation)
in nav (created by Nav)
in Nav (created by Navigation)
in div (created by PageSidebar)
in PageSidebar (created by Navigation)
in Navigation (created by App)
in div (created by Page)
in Page (created by App)
in App (created by Route)
in Route
in Router
in Provider
```

fix(nav): fix React warning with onExpand prop

---

packages/patternfly-4/react-core/src/components/InputGroup/InputGroup.js
packages/patternfly-4/react-core/src/components/InputGroup/InputGroupText.d.ts
packages/patternfly-4/react-core/src/components/InputGroup/InputGroupText.js
packages/patternfly-4/react-core/src/components/InputGroup/examples/SimpleInputGroups.js
packages/patternfly-4/react-integration/demo-app-ts/src/App.tsx

closes #1492 
- Added `InputGroup` and `InputGroupText` to react-integration
- Changed the `component` prop's type to `ReactType`

chore(inputgroup): add input group to react-integration

---

packages/patternfly-3/patternfly-react/src/components/VerticalNav/VerticalNav.js
packages/patternfly-3/patternfly-react/src/components/VerticalNav/VerticalNavItemHelper.js

**What**:
add id, data-id to secondary items
Not sure if i'm missing something but I don't see an option to pass these props.
Required for QE testing

feat(VerticalNav): add id, data-id to secondary items

---

packages/patternfly-3/patternfly-react/src/components/LoadingState/LoadingState.stories.js
packages/patternfly-3/patternfly-react/src/components/LoadingState/Stories/LoadableState.js

Currently there is only one story in LoadingState which demonstrates its props.
However, it's missing an example of setting a delay and waiting for data to be sent by the server.

docs(LoadingState): Add state loading with delay to storybook

---

packages/patternfly-3/patternfly-react/less/type-ahead-select.less
packages/patternfly-3/patternfly-react/sass/patternfly-react/_type-ahead-select.scss

Fixes #1362 (replaces original fix for #413)
This TypeAheadSelect input should allow its height to expand to fit the contents, which is accomplished in the dependency's CSS by a simple `height: auto`. However, the original issue #413 was caused by our patternfly CSS overriding that height with a rule for `.form-control`.
The original fix in PR #409 used `height: fit-content`, but this value is only supported by Chrome, according to https://developer.mozilla.org/en-US/docs/Web/CSS/height.
This replacement fix uses both classes (`.form-control.rbt-input-multi`) to ensure a higher specificity and resets the height back to `auto` for this kind of input.

fix(TypeAheadSelect): Fix input height overflow issue without breaking IE11 compatibility

---

packages/patternfly-4/react-core/src/components/Avatar/Avatar.tsx
packages/patternfly-4/react-core/src/tsconfig.dts.json

**What**:
This change disables `allowSyntheticDefaultImports` and `esModuleInterop`. From a library perspective, I believe we will need to ensure that we can support Typescript consumers who have this option disabled OR enabled. This was discovered today while testing OpenShift tests downstream. 
It is generally considered good practice now to enable these flags (and from a Node JS/Common JS perspective) this is the typical path, however some consumers may not elect to enable them.
This should resolve the current issue and help us strategize for future TSX conversion.
cc: @dgutride @rhamilto @spadgett @tlabaj 
For additional detail, with this flags disabled downstream, but enabled upstream, we'll run into these:
```
ERROR in /Users/priley/GitHub/web-ui/frontend/node_modules/@patternfly/rea …
```

fix(tsconfig): avatar tsx change

---

packages/patternfly-4/react-docs/src/components/propsTable/propsTable.js
packages/patternfly-4/react-table/src/components/Table/Table.js

Fixes #1473 - a P1 issue, which is why I chose it, but it's a simple doc change.
Updated table doc to:
**Note:** The ability to now use HTML in the Description column.   This is accomplished via:
`<span dangerouslySetInnerHTML={{__html: prop.description.text}}/>`  -wondering if there is any downside/risk in using this method?

chore(TableDoc): Update Documentation for for using 'title' prop in table cells.

---

packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.docs.js
packages/patternfly-4/react-core/src/components/Dropdown/Toggle.js
packages/patternfly-4/react-core/src/components/Dropdown/examples/DisabledDropdown.js
packages/patternfly-4/react-table/src/components/Table/__snapshots__/Table.test.js.snap

**What**:
closes #1501 
//cc @mcoker

feat(Dropdown): add support for disabled dropdown menus

---

packages/patternfly-3/patternfly-react/build/node-sass-tilde-importer.js
packages/patternfly-3/patternfly-react/package.json
yarn.lock

Fixes #673.
This PR adds a step to the `build:sass` script in `packages/patternfly-3/patternfly-react` which uses a custom node-sass importer to change the tilde-based path `~react-bootstrap-typeahead/css/Typeahead.css` to a true relative path, and then calls `cleancss` to convert that local import into inlined CSS.
Details on the `--importer` option I'm passing to `node-sass`: https://github.com/sass/node-sass#importer--v200---experimental
Before writing the custom `build/node-sass-tilde-importer.js` file, I tried using https://www.npmjs.com/package/node-sass-tilde-importer, but that converts the import to an absolute path, which cleancss was refusing to resolve. Maybe a different CSS processor could handle that.
I have a feeling there is a better way, but this works. It seems something …

build(sass): Inline the CSS of imported files in patternfly-react.scss

---

packages/react-codemods/transforms/pf3-pf4.button.test.js
packages/react-codemods/transforms/pf3-pf4.test.js

**What**: Remove prettier EOL config option during tests. Tests fail whenever it is specified on *nix-based systems after #1255

fix(codemod): fix tests failing due to prettier

---

packages/patternfly-4/react-core/src/components/LoginPage/LoginForm.d.ts

HelperText need to be ReactNode
Fix #1550

fix: PF4 Fix HelperText definition in LoginForm

---

packages/patternfly-4/react-core/src/components/Modal/Modal.js
packages/patternfly-4/react-core/src/components/Modal/Modal.test.js

1. Add a test that fails because the class is not removed
2. Added the fix (remove the backdropOpen class from the body in `componentWillUnmount`)
3. Test is passing
This is not related to this fix, but having multiple modals in one screen may not be a good idea...
Closes #1531

fix(Modal): remove backdropOpen class from body when Modal is removed

---

packages/patternfly-4/react-core/src/components/DataList/DataList.docs.js
packages/patternfly-4/react-core/src/components/DataList/DataList.test.js
packages/patternfly-4/react-core/src/components/DataList/DataListAction.d.ts
packages/patternfly-4/react-core/src/components/DataList/DataListAction.js
packages/patternfly-4/react-core/src/components/DataList/__snapshots__/DataList.test.js.snap
packages/patternfly-4/react-core/src/components/DataList/examples/ActionsDataList.js

This is a follow-up to #927 
Now you can add `Dropdown` or `Button` to `DataListAction`.
Please feel free to review the API, I did it as simple as I could but if you believe it needs another abstraction or logical layer, I would like to hear.
cc @jgiardino @jschuler @christiemolloy

fix(DataList): Add dropdown and button actions to DataList

---

packages/patternfly-4/react-core/src/components/Nav/NavItem.d.ts

**What**:
fixes #1583, reverts change in #1576 
it seems we are hitting the same issue we hit in #1470 when redefining `onClick` handler for `HTMLProps`. Included explanation in [1547](https://github.com/patternfly/patternfly-react/issues/1547#issuecomment-473303861). 

fix(NavItem): fix type definition

---

packages/patternfly-4/react-core/src/components/Switch/Switch.js
packages/patternfly-4/react-core/src/components/Switch/__snapshots__/Switch.test.js.snap
packages/patternfly-4/react-core/src/components/Switch/examples/DisabledSwitch.js
packages/patternfly-4/react-core/src/components/Switch/examples/SimpleSwitch.js
packages/patternfly-4/react-core/src/components/Switch/examples/UncontrolledSwitch.js
packages/react-icons/src/createIcon.js

I added the icon to unlabeled switches, updated HTML and CSS classes to match core/avoid CSS labels, and updated the example labels to match core.
Fixes #1296 and #1546.

feat(Switch): Add icon and fix labels

---

packages/patternfly-3/patternfly-react/src/components/Modal/Modal.js
packages/patternfly-3/patternfly-react/src/components/Modal/Modal.stories.js
packages/patternfly-3/patternfly-react/src/components/Modal/Patterns/ModalPattern.js
packages/patternfly-3/patternfly-react/src/components/Modal/Patterns/StatefulModalPattern.js
packages/patternfly-3/patternfly-react/src/components/Modal/Stories/ModalExampleStory.js
packages/patternfly-3/patternfly-react/src/components/Modal/Stories/ModalPatternExample.js
packages/patternfly-3/patternfly-react/src/components/Modal/Stories/ModalPatternExampleStory.js
packages/patternfly-3/patternfly-react/src/components/Modal/Stories/index.js
packages/patternfly-3/patternfly-react/src/components/Modal/index.js

**What**: this PR adds new pattern components, `ModalPattern` and `StatefulModalPattern`.
`Modal` vs. `ModalPattern` is just like `Wizard` vs. `WizardPattern`.
`StatefulModalPattern` adds the ability to manage the `show` flag via component state, similar to how `StatefulWizardPattern` manages `activeStepIndex`. `StatefulModalPattern` also adds `open` and `close` methods to support component instance interaction (e.g. when using React refs).
There are no breaking changes. :smiley: 
This PR also contains small wizard pattern component improvements - most notably, remove exclusion of `activeStepIndex` in `StatefulWizardPattern.propTypes` since this prop is still used via `propOrState` and therefore should be part of `StatefulWizardPattern.propTypes`.
**Stories and tests are missing.** I'll …

feat(ModalPattern): Add ModalPattern and StatefulModalPattern components

---

packages/patternfly-4/react-table/src/components/Table/Table.d.ts

**What**: OpenShift uses Typescript 2, so let them still get typechecking goodness by removing the new TS3 "unknown" type.
**Additional issues**: Closes #1606

fix(table): remove Typescript 3+ "unknown" type

---

packages/patternfly-4/react-core/src/components/Switch/Switch.js
packages/patternfly-4/react-core/src/components/Switch/examples/DisabledSwitch.js
packages/patternfly-4/react-core/src/components/Switch/examples/NoLabelSwitch.js
packages/patternfly-4/react-core/src/components/Switch/examples/SimpleSwitch.js
packages/patternfly-4/react-core/src/components/Switch/examples/UncontrolledSwitch.js

I updated the examples so the aria-label is the "on" message and changed the aria-label documentation per @jgiardino's notes in #1602.
Fixes #1602.

refactor(Switch): Aria label reflects the message when on

---

packages/patternfly-4/react-table/src/components/Table/Body.js
packages/patternfly-4/react-table/src/components/Table/Table.d.ts
packages/patternfly-4/react-table/src/components/Table/Table.js
packages/patternfly-4/react-table/src/components/Table/Table.test.js
packages/patternfly-4/react-table/src/components/Table/__snapshots__/Table.test.js.snap
packages/patternfly-4/react-table/src/components/Table/examples/CollapsibleTable.js
packages/patternfly-4/react-table/src/components/Table/index.d.ts
packages/patternfly-4/react-table/src/components/Table/index.js
packages/patternfly-4/react-table/src/components/Table/utils/__snapshots__/transformers.test.js.snap
packages/patternfly-4/react-table/src/components/Table/utils/decorators/collapsible.js
packages/patternfly-4/react-table/src/components/Table/utils/index.d.ts
packages/patternfly-4/react-table/src/components/Table/utils/index.js
packages/patternfly-4/react-table/src/components/Table/utils/transformers.js
packages/patternfly-4/react-table/src/components/Table/utils/transformers.test.js
packages/patternfly-4/react-table/src/components/Table/utils/utils.js
packages/patternfly-4/react-table/src/components/Table/utils/utils.test.js
packages/patternfly-4/react-table/src/test-helpers/data-helpers.js

by using expandable cellFormatter or ExpandableRowContent component directly
- exposed isRowExpanded function for extensions to use
https://github.com/patternfly/patternfly-react/pull/1227 is dependent on this PR.

feat(Table): support custom components in expandable rows

---

packages/patternfly-4/react-core/src/components/Wizard/Wizard.tsx

**What**: Noticed this `console.log` in the Wizard component while trying it out in `2.8.2`.
I didn't find any issues related to this that I could link.
I know this is still in `prerelease` so feel free to close this if removing the `console.log` is premature.

fix (Wizard): remove console.log from save

---

packages/patternfly-4/react-table/src/components/Table/Body.js
packages/patternfly-4/react-table/src/components/Table/__snapshots__/Table.test.js.snap

Fixes issue where an error is thrown and applications crash when there is null as value in one of
the table cells.
Fix #1371

Fix(#1371): Fix for null and undefined rendering in table cell

---

packages/patternfly-4/react-table/src/components/Table/Body.js
packages/patternfly-4/react-table/src/components/Table/__snapshots__/Table.test.js.snap

https://github.com/patternfly/patternfly-react/pull/1520 already fixed https://github.com/patternfly/patternfly-react/issues/1371 with some other enhacements.
https://github.com/patternfly/patternfly-react/pull/1621 reverted these enhacements, so this PR reverts that PR
It also added 
```
`console.warn(`Cell value at [ ${rowKey}, ${key} ] should not be set to ${curr}`);` 
```
which I do not think is necessary, because there are multiple use cases when the row is represented as structured data and we render that data according to that and do not render cells. In this use case, I think it is not necessary to show warnings (especially one per each cell).

fix(Table): reverts unnecessary fix

---

packages/patternfly-4/react-core/src/components/ContextSelector/ContextSelector.d.ts
packages/patternfly-4/react-core/src/components/ContextSelector/ContextSelectorItem.d.ts
packages/patternfly-4/react-table/src/components/Table/index.d.ts
packages/patternfly-4/react-table/src/components/Table/utils/index.d.ts

**What**:
A few ts definitions out of sync today... probably easiest to remove the `extends HTMLProps<HTMLDivElement>` piece for now. There is nested element types returned so not really necessary on these.
```
ERROR in /Users/priley/GitHub/web-ui/frontend/node_modules/@patternfly/react-core/dist/js/components/ContextSelector/ContextSelector.d.ts(4,18):
TS2430: Interface 'ContextSelectorProps' incorrectly extends interface 'HTMLProps<HTMLDivElement>'.
Types of property 'onSelect' are incompatible.
Type '(event: SyntheticEvent<Element>, value: ReactNode) => void' is not assignable to type '(event: SyntheticEvent<HTMLDivElement>) => void'.
ERROR in /Users/priley/GitHub/web-ui/frontend/node_modules/@patternfly/react-core/dist/js/components/ContextSelector/ContextSelectorItem.d.ts(3,18): …
```

fix(ts-fixes): ts definition changes

---

packages/patternfly-4/react-core/README.md

**What**: The link to the PF4 page in the README.md file is broken. This PR fixes the link.

Fixed PF4 link in README

---

packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggle.d.ts

**What**:
Slight tweak to  `DropdownToggleProps` found while testing Kiali today. We currently allow passing `null` to the `iconComponent` to remove the caret icon from the dropdown. If `strictNullChecks` is set true, this will give a TypeScript error to the user. Making the slight adjustment here to the definition to allow `null`.
cc: @aljesusg 

fix(dropdown-toggle): toggle props, allow null iconComponent

---

packages/patternfly-4/react-core/src/components/Pagination/Pagination.d.ts

**What**: The TypeScript type definition for the `<Pagination>` currently define all the callbacks as simple `Function` types, giving users no clue about the actual arguments. This pull request provides more fine-grained types for these callbacks.
**Additional issues**: I'm not 100% sure about the type of the events provided to the callbacks. I just checked the components used by the `<Pagination>` component to get these types. However, this could be considered to be an implementation detail!?!
Fixes #1633

Improved function typings for PF4 <Pagination> component

---

packages/patternfly-3/patternfly-react/less/breadcrumbswitcher.less
packages/patternfly-3/patternfly-react/less/patternfly-react.less
packages/patternfly-3/patternfly-react/package.json
packages/patternfly-3/patternfly-react/sass/patternfly-react/_breadcrumbswitcher-popover.scss
packages/patternfly-3/patternfly-react/sass/patternfly-react/_patternfly-react.scss
packages/patternfly-3/patternfly-react/src/components/BreadcrumbSwitcher/BreadcrumbSwitcher.fixtures.js
packages/patternfly-3/patternfly-react/src/components/BreadcrumbSwitcher/BreadcrumbSwitcher.js
packages/patternfly-3/patternfly-react/src/components/BreadcrumbSwitcher/BreadcrumbSwitcher.stories.js
packages/patternfly-3/patternfly-react/src/components/BreadcrumbSwitcher/BreadcrumbSwitcher.test.js
packages/patternfly-3/patternfly-react/src/components/BreadcrumbSwitcher/BreadcrumbSwitcherHelper.js
packages/patternfly-3/patternfly-react/src/components/BreadcrumbSwitcher/__snapshots__/BreadcrumbSwitcher.test.js.snap
packages/patternfly-3/patternfly-react/src/components/BreadcrumbSwitcher/components/BreadcrumbSearchInput.js
packages/patternfly-3/patternfly-react/src/components/BreadcrumbSwitcher/components/BreadcrumbSwitcherPopover.js
packages/patternfly-3/patternfly-react/src/components/BreadcrumbSwitcher/components/BreadcrumbSwitcherToggler.js
packages/patternfly-3/patternfly-react/src/components/BreadcrumbSwitcher/index.js
yarn.lock

**What**:
creating a BreadcrumbSwitcher component

feat(BreadcrumbSwitcher): creating a BreadcrumbSwitcher component

---

packages/patternfly-4/react-core/src/components/Tooltip/Tooltip.d.ts
packages/patternfly-4/react-core/src/components/Tooltip/Tooltip.js
packages/patternfly-4/react-core/src/components/Tooltip/Tooltip.test.js
packages/patternfly-4/react-core/src/components/Tooltip/__snapshots__/Tooltip.test.js.snap

**What**:
closes #1564 
Adding the `trigger` props to display tooltip on mouse click.
//cc @keithjgrant

fix(tooltip): trigger tooltip by mouse click or other events

---

packages/patternfly-4/react-core/src/components/Pagination/OptionsMenu.js
packages/patternfly-4/react-core/src/components/Pagination/Pagination.d.ts
packages/patternfly-4/react-core/src/components/Pagination/Pagination.js
packages/patternfly-4/react-core/src/components/Pagination/__snapshots__/Pagination.test.js.snap

**What**:
closes #1528 
I added the "per page" suffix into the default props. Let me know if I'm missing something.
//cc @karelhala @mcarrano @tlabaj

fix(pagination): add "per page" suffix in options

---

packages/patternfly-4/react-core/src/components/Tabs/Tabs.js
packages/patternfly-4/react-core/src/components/Tabs/__snapshots__/Tabs.test.js.snap
packages/patternfly-4/react-core/src/components/Tabs/examples/AccessibleSecondaryTabs.js
packages/patternfly-4/react-core/src/components/Tabs/examples/AccessibleTabs.js
packages/patternfly-4/react-core/src/components/Tabs/index.d.ts
packages/patternfly-4/react-core/src/components/Tabs/index.js

Instead of using variant="nav," we now use variant={TabsVariant.nav} in the accessible Tabs examples. I also fixed an HTML issue where the `<nav>` and `<div>` containers were displaying the scroll button aria-label props in the HTML for the nav/div. We're now explicitly passing those props to the child that needs it so it won't show up there.
Fixes #1689.

fix(Tabs): Use TabsVariant.nav and fix a minor HTML issue

---

packages/patternfly-4/react-table/src/components/Table/Table.d.ts

Add a fix found by a user to change the type-o of property transfrom to transform
Will only break for typescript users using the type definition files.
fix #1662
**What**:

fix(Table): fix type-o in ICell Interface transform (from transfrom)

---

packages/patternfly-4/react-core/src/components/Pagination/Navigation.js
packages/patternfly-4/react-core/src/components/Pagination/__snapshots__/Pagination.test.js.snap

**What**:
closes #1676
`type="number` inputs don't have the `size` attribute. 
Nevertheless, using `width: auto` (which is the default) the browser determines the right size of the input.

fix(pagination): remove size attr from type="number" input

---

packages/patternfly-4/react-table/src/components/Table/Table.d.ts
packages/patternfly-4/react-table/src/components/Table/Table.js
packages/patternfly-4/react-table/src/components/Table/Table.md
packages/patternfly-4/react-table/src/components/Table/__snapshots__/Table.test.js.snap
packages/patternfly-4/react-table/src/components/Table/utils/decorators/collapsible.js
packages/patternfly-4/react-table/src/components/Table/utils/transformers.test.js

**What**:
Adds two optional fields to row definition
* `fullWidth` -  to span expanded row over all cells (removing first cell) fixes #1376
* `noPadding` - adds specific class `pf-m-no-padding` fixes #1678 
Fixes issue that first cell of expanded row had class `pf-c-table__toggle`, now first cell has no class at all.

fix(Table): Update expanded row to span over all cells and remove padding

---

packages/patternfly-4/react-core/src/components/EmptyState/EmptyState.d.ts
packages/patternfly-4/react-core/src/components/EmptyState/EmptyState.js
packages/patternfly-4/react-core/src/components/EmptyState/EmptyState.md
packages/patternfly-4/react-core/src/components/EmptyState/EmptyState.test.js
packages/patternfly-4/react-core/src/components/EmptyState/__snapshots__/EmptyState.test.js.snap
packages/patternfly-4/react-core/src/components/EmptyState/index.d.ts
packages/patternfly-4/react-core/src/components/EmptyState/index.js

**What**:
closes #1677 
//cc @dlabaj @mcoker 
Don't merge this yet till:

fix(emptyState): add small/large modifiers

---

packages/patternfly-4/react-core/src/components/DataList/DataList.md
packages/patternfly-4/react-core/src/components/DataList/DataList.test.js
packages/patternfly-4/react-core/src/components/DataList/DataListAction.d.ts
packages/patternfly-4/react-core/src/components/DataList/DataListAction.js
packages/patternfly-4/react-core/src/components/DataList/DataListCell.d.ts
packages/patternfly-4/react-core/src/components/DataList/DataListCell.js
packages/patternfly-4/react-core/src/components/DataList/DataListCheck.js
packages/patternfly-4/react-core/src/components/DataList/DataListContent.d.ts
packages/patternfly-4/react-core/src/components/DataList/DataListContent.js
packages/patternfly-4/react-core/src/components/DataList/DataListItem.d.ts
packages/patternfly-4/react-core/src/components/DataList/DataListItem.js
packages/patternfly-4/react-core/src/components/DataList/DataListItemCells.d.ts
packages/patternfly-4/react-core/src/components/DataList/DataListItemCells.js
packages/patternfly-4/react-core/src/components/DataList/DataListItemRow.d.ts
packages/patternfly-4/react-core/src/components/DataList/DataListItemRow.js
packages/patternfly-4/react-core/src/components/DataList/DataListToggle.js
packages/patternfly-4/react-core/src/components/DataList/__snapshots__/DataList.test.js.snap
packages/patternfly-4/react-core/src/components/DataList/index.d.ts
packages/patternfly-4/react-core/src/components/DataList/index.js

refactor(DataList): Refactor DataList based on changes in core

---

packages/patternfly-4/react-table/src/components/Table/Table.md

Added no padding example to collapsable table demo.  Fix for issue #1678

Updated collapsable table demo for issue #1678

---

packages/patternfly-4/react-core/src/components/Select/Select.js
packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.js.snap

**What**:
This change removes `width` from `defaultProps` as `width: 100%` is set in the class.
closes #1610 
//cc @christiemolloy @kmcfaul

fix(select): remove the custom override on width

---

packages/patternfly-4/react-core/src/components/Nav/Nav.d.ts

the onSelect and onToggle functions take a single js object of params rather than the same prams as
positional params to the both functions
fix #1391
**What**:

fix(Nav): change onSelect and onToggle arg types from positional to single obj

---

packages/patternfly-4/react-core/src/components/Pagination/OptionsMenu.js
packages/patternfly-4/react-core/src/components/Pagination/__snapshots__/Pagination.test.js.snap

Destructured perPageSuffix from props prior to spreading.  Updated snapshots.
fix #1784
**What**:

fix(react-core): Fixes console error with perPageSuffix (Issue #1784)

---

packages/patternfly-4/react-core/src/components/Tabs/Tab.js
packages/patternfly-4/react-core/src/components/Tabs/TabContent.js

This addresses the undefined child/children error seen with TabContent in the Cost Management UI. It also fixes a Typescript error encountered in the same UI.
Built and tested with the Cost Management UI and all is well.
Fixes https://github.com/patternfly/patternfly-react/issues/1698

Fixed TabContent errors

---

packages/patternfly-4/react-table/src/components/Table/Table.md

Fixes https://github.com/patternfly/patternfly-react/issues/1460
**What**: Add headerCol cell transform to the first column of actions, collapsible, selectable, and simple actions table examples. This makes the first cell of each row into a `th` element and wraps the content in a `div` with an id that will match the `aria-labeledby` attribute on selectable row checkboxes and/or expandable row expand buttons.

fix(Table): Fix Table component accessibility issues

---

packages/patternfly-4/react-table/src/components/Table/BodyCell.js
packages/patternfly-4/react-table/src/components/Table/HeaderCell.js
packages/patternfly-4/react-table/src/components/Table/Table.md
packages/patternfly-4/react-table/src/components/Table/__snapshots__/Table.test.js.snap
packages/patternfly-4/react-table/src/components/Table/index.js
packages/patternfly-4/react-table/src/components/Table/utils/decorators/textCenter.js
packages/patternfly-4/react-table/src/components/Table/utils/headerUtils.js
packages/patternfly-4/react-table/src/components/Table/utils/transformers.js
packages/patternfly-4/react-table/src/components/Table/utils/transformers.test.js

fix #1482
**What**:
- Add a `textCenter` transform which applies `textCenter=true` prop to header and body cells. This prop conditionally adds the `pf-m-center` css class to header and body cells. This allows the transform to be easily overridden by applying `textCenter=false` prop to an individual cell definition.
- Change the order in which transforms are applied in `components/Table/utils/headerUtils.js:generateCell` function. Previously, props that were defined at the individual cell level were used as the default, then any transforms applied at the column level were overriding those values. This is the reverse of expected behavior. Transforms applied at the column level should be considered the default, then props/transforms should override each other as specificity increases (with …

fix(Table): Add ability to center-align header and cell text

---

packages/patternfly-4/react-table/src/components/Table/Table.d.ts

**What**:
Discovered these were missed in #1227 today while testing downstream
```
ERROR in /Users/priley/GitHub/web-ui/frontend/public/components/factory/table.tsx(386,12):
TS2322: Type '{ children: Element[]; cells: any[]; rows: any; onSelect: (event: MouseEvent<Element>, isSelected...' is not assignable to type 'IntrinsicAttributes & TableProps & { children?: ReactNode; }'.
Type '{ children: Element[]; cells: any[]; rows: any; onSelect: (event: MouseEvent<Element>, isSelected...' is not assignable to type 'TableProps'.
Property 'bodyWrapper' is missing in type '{ children: Element[]; cells: any[]; rows: any; onSelect: (event: MouseEvent<Element>, isSelected...'.
```
do these work OK for now @suomiy  or did you have something else in mind? 
none

add bodyWrapper type def

---

packages/patternfly-4/react-core/src/components/ClipboardCopy/ClipboardCopy.js
packages/patternfly-4/react-core/src/components/ClipboardCopy/ClipboardCopy.md
packages/patternfly-4/react-core/src/components/ClipboardCopy/index.d.ts

build(clipboardcopy): change doc text

---

packages/patternfly-4/react-core/src/components/Tabs/Tab.d.ts
packages/patternfly-4/react-core/src/components/Tabs/Tab.js
packages/patternfly-4/react-core/src/components/Tabs/Tabs.md
packages/patternfly-4/react-core/src/components/Tabs/Tabs.test.js
packages/patternfly-4/react-core/src/components/Tabs/__snapshots__/Tabs.test.js.snap

Closes #1805
**What**: Adds a prop `href` to the `Tab` component that causes it to render `<a>` instead of `<button>`. Adds a note to the props table explaining that this should be done if the consumer is using the `"nav"` variant for their `Tabs` container.

feat(Tab): Render Tab as <a> instead of <button> if it contains an href prop

---

packages/patternfly-4/react-core/src/components/Alert/Alert.js

Allows user to specify a wider range of titles.
Fixes #1854.

fix(Alert): Change title type from string to node

---

packages/patternfly-4/react-table/src/components/Table/Table.d.ts
packages/patternfly-4/react-table/src/components/Table/Table.js
packages/patternfly-4/react-table/src/components/Table/Table.md
packages/patternfly-4/react-table/src/components/Table/index.js
packages/patternfly-4/react-table/src/components/Table/utils/decorators/classNames.js
packages/patternfly-4/react-table/src/components/Table/utils/headerUtils.js
packages/patternfly-4/react-table/src/components/Table/utils/transformers.js

**What**: Closes #1832
This PR adds:
* A new property `columnTransforms` which can be included in a column definition (object in the `cells` array of a `Table`) with an array of reactabular transform functions which will apply to every cell in the column (header and body). This complements the existing properties `transforms` (only applies to header cells) and `cellTransforms` (only applies to body cells).
* A new decorator transform called `classNames` which just applies all of its arguments as classNames to the affected cells.
* A new export `Visibility` which includes all the modifiers for column visibility as properties.
* an example of using these three together to implement hidden/visible column breakpoints in a table.

feat(Table): Add columnTransforms, classNames decorator, Visibility constants, and hidden/visible breakpoints example

---

packages/patternfly-4/react-core/src/components/AboutModal/AboutModal.d.ts
packages/patternfly-4/react-core/src/components/AboutModal/AboutModal.js
packages/patternfly-4/react-core/src/components/AboutModal/AboutModal.md
packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxContent.d.ts
packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxContent.js
packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalBoxContent.test.js.snap

Users can specify an optional prop that prevents the component from automatically nesting all content inside a  .pf-c-content div. Users can now use non-text components like Alert in the About modal.
I also fixed a messed up .d.ts file while I was in there (name and prop name were off).
Fixes #1853.

feat(About modal): Added support for more user control over content

---

packages/patternfly-3/patternfly-react-extensions/src/components/Select/Select.js

**What**:
Select doesn't work downstream, due to a ListGroupItem import error, this PR tries to fix it.

fix(Select): fix ListGroupItem import

---

packages/patternfly-4/react-core/src/components/Accordion/Accordion.d.ts
packages/patternfly-4/react-core/src/components/Accordion/AccordionContent.d.ts
packages/patternfly-4/react-core/src/components/Accordion/AccordionItem.d.ts
packages/patternfly-4/react-core/src/components/Accordion/AccordionToggle.d.ts

fix #1869
node_modules/@patternfly/react-core/dist/js/components/Accordion/Accordion.d.ts
(2,22): Cannot find module '../../typeUtils'
```typescript
import { Omit } from '../../typeUtils';
```
Fix with 
```typescript
import { Omit } from '../../helpers/typeUtils';
```

fix(Accordion): Wrong import in definition file

---

packages/patternfly-4/react-table/src/components/Table/Table.d.ts
packages/patternfly-4/react-table/src/components/Table/Table.js

**What**: Closes #1890
Passing `TableGridBreakpoint.none` (or just `null` directly) to the `gridBreakPoint` prop of a `Table` will prevent a `pf-m-grid-` modifier class from being rendered.

 feat(Table): Allow passing TableGridBreakpoint.none for gridBreakPoint prop to disable grid layout

---

packages/patternfly-4/react-core/src/components/ClipboardCopy/ClipboardCopy.d.ts
packages/patternfly-4/react-core/src/components/ClipboardCopy/ClipboardCopy.js

Fixes issue [#1871](https://github.com/patternfly/patternfly-react/issues/1871)
Note: the issue states that the onChange prop is not used in ClipboardCopy.js but it is used on line 46. It is not used in the render function.
Tested by adding component to index.tsx on patternfly-react-seed (locally)

fix(ClipboardCopy): update imports and clean up

---

packages/patternfly-3/patternfly-react/src/components/DualListSelector/components/DualListHiddenSelect.js

Using the 'value' attribute instead of 'defaultValue' updates the input values properly.

fix(DualList): fix hidden selects input values to update properly

---

packages/react-icons/build/generateIcons.js
packages/react-icons/build/icons.js
packages/react-icons/package.json
yarn.lock

**What**:
This PR adds all font awesome brands icons, icon count increased by 426.
Resolves #1666

feat(Icons): Add font awesome brands icons

---

packages/patternfly-4/react-charts/src/components/Chart/__snapshots__/Chart.test.js.snap
packages/patternfly-4/react-charts/src/components/ChartArea/__snapshots__/ChartArea.test.js.snap
packages/patternfly-4/react-charts/src/components/ChartAxis/__snapshots__/ChartAxis.test.js.snap
packages/patternfly-4/react-charts/src/components/ChartBar/__snapshots__/ChartBar.test.js.snap
packages/patternfly-4/react-charts/src/components/ChartContainer/__snapshots__/ChartContainer.test.js.snap
packages/patternfly-4/react-charts/src/components/ChartDonut/__snapshots__/ChartDonut.test.js.snap
packages/patternfly-4/react-charts/src/components/ChartGroup/__snapshots__/ChartGroup.test.js.snap
packages/patternfly-4/react-charts/src/components/ChartLegend/__snapshots__/ChartLegend.test.js.snap
packages/patternfly-4/react-charts/src/components/ChartLine/__snapshots__/ChartLine.test.js.snap
packages/patternfly-4/react-charts/src/components/ChartPie/__snapshots__/ChartPie.test.js.snap
packages/patternfly-4/react-charts/src/components/ChartPoint/__snapshots__/ChartPoint.test.js.snap
packages/patternfly-4/react-charts/src/components/ChartStack/__snapshots__/ChartStack.test.js.snap
packages/patternfly-4/react-charts/src/components/ChartTheme/theme-common.js
packages/patternfly-4/react-charts/src/components/ChartTheme/theme-dark-blue.js
packages/patternfly-4/react-charts/src/components/ChartTheme/theme-dark-green.js
packages/patternfly-4/react-charts/src/components/ChartTheme/theme-dark-multi.js
packages/patternfly-4/react-charts/src/components/ChartTheme/theme-light-blue.js
packages/patternfly-4/react-charts/src/components/ChartTheme/theme-light-green.js
packages/patternfly-4/react-charts/src/components/ChartTheme/theme-light-multi.js
packages/patternfly-4/react-charts/src/components/ChartVoronoiContainer/__snapshots__/ChartVoronoContainer.test.js.snap

Fixes #1864
**What**:
Use `global_FontFamily_sans_serif` variable for chart font stack. Also, correct misspelled 'TYPOGRAPHY' related variable names.

fix(charts): Fix chart font stack to use PatternFly core sans-serif font stack

---

packages/react-icons/README.md

fix(React Icons documentation): fix link in Icons documentation  

---

packages/patternfly-4/react-core/src/components/Tooltip/styles.js

**Previously,** cursor does turn to I-Beam (text), but cannot highlight or select the text in the Popover:
**With fix**, can now highlight and select text:
Fixes #1735

fix(popover): Enable highlighting and selecting text in popover.

---

packages/patternfly-4/react-core/src/components/Dropdown/Toggle.js

**What**:
Consumers might want to choose to override events from dropdown toggle for instance to stop propagation to parent (when dropdown located in clicable element). For this reason we should send event on toggle callback.

fix(Dropdown): Send event when clicking on dropdown toggle

---

packages/patternfly-4/react-charts/package.json
packages/patternfly-4/react-charts/src/components/Chart/__snapshots__/Chart.test.js.snap
packages/patternfly-4/react-charts/src/components/ChartArea/__snapshots__/ChartArea.test.js.snap
packages/patternfly-4/react-charts/src/components/ChartAxis/__snapshots__/ChartAxis.test.js.snap
packages/patternfly-4/react-charts/src/components/ChartBar/__snapshots__/ChartBar.test.js.snap
packages/patternfly-4/react-charts/src/components/ChartGroup/__snapshots__/ChartGroup.test.js.snap
packages/patternfly-4/react-charts/src/components/ChartLegend/ChartLegend.d.ts
packages/patternfly-4/react-charts/src/components/ChartLine/__snapshots__/ChartLine.test.js.snap
packages/patternfly-4/react-charts/src/components/ChartStack/__snapshots__/ChartStack.test.js.snap
packages/patternfly-4/react-charts/src/components/ChartVoronoiContainer/__snapshots__/ChartVoronoContainer.test.js.snap
yarn.lock

fixes #1898
**What**:
Update `@types/victory`, `victory`, `victory-core`, and `hoist-non-react-statics` to latest and remove extra type definition for the `title` prop in `ChartLegend`. The latest victory types include an accurate definition for this prop.
Victory changelog for reference:
https://github.com/FormidableLabs/victory/blob/master/CHANGELOG.md

fix(types): Update @types/victory, victory, victory-core, and hoist-non-react-statics packages to latest

---

packages/patternfly-4/react-core/src/components/AboutModal/AboutModal.d.ts
packages/patternfly-4/react-core/src/components/AboutModal/AboutModal.js
packages/patternfly-4/react-core/src/components/AboutModal/AboutModal.md
packages/patternfly-4/react-core/src/components/AboutModal/AboutModal.test.js
packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxHero.d.ts
packages/patternfly-4/react-core/src/components/AboutModal/AboutModalBoxHero.js
packages/patternfly-4/react-core/src/components/AboutModal/AboutModalContainer.d.ts
packages/patternfly-4/react-core/src/components/AboutModal/AboutModalContainer.js
packages/patternfly-4/react-core/src/components/AboutModal/AboutModalContainer.test.js
packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalBoxHero.test.js.snap
packages/patternfly-4/react-core/src/components/AboutModal/__snapshots__/AboutModalContainer.test.js.snap
packages/patternfly-4/react-core/src/components/AboutModal/examples/patternfly-orb.svg

**What**: This PR removes the `logoImageSrc` and `logoImageAlt` props from about modal as they were never actually used. Beyond removing these dead API parts, I've replaced them with a single prop, `bgImgSrc` which I believe fulfills the original intent - which is making the background graphic on the right side of the modal configurable.
I've added a new example for AboutModal, one that illustrates how to set a custom background image.
The value passed for `backgroundImageSrc` is used to set the value for the css variable "--pf-c-about-modal-box__hero--sm--BackgroundImage". This is different than how we typically set CSS vars, and the need for it is described here https://github.com/patternfly/patternfly-react/issues/1919. In a nutshell, the need is driven by having assets served by a …

fix(AboutModal): provide a way to set the background using props

---

packages/patternfly-4/react-integration/demo-app-ts/package.json
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/NavDemo/NavDemo.tsx
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TitleDemo/TitleDemo.tsx
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TooltipDemo/TooltipDemo.tsx
packages/patternfly-4/react-integration/package.json
yarn.lock

**What**: Fixes common build issues with react-demo-app. TypeChecking still happens through `tsc`, so the passed props are still getting checked (like in the Jest tests). If we really want consumers to be able to import our types easier, we should look into exporting a single types file and maybe even hosting it in [@types](https://github.com/DefinitelyTyped/DefinitelyTyped)!

fix(demo-app): remove demo-app from build

---

packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.md
packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.tsx

**What**:
closes #1959 
I first realized that the controlled Checkbox example is wrong: `event.target.name` is not set and so the state can be `{check1: false, check2: false, '': false}` or `{check1: false, check2: false, '': true}`.
After fixing it by adding the `name` attribute to the Checkbox components the first time I checked one of the boxes I got the following error/warning message:
```
Warning: A component is changing an uncontrolled input of type checkbox to be controlled.
Input elements should not switch from uncontrolled to controlled (or vice versa).
Decide between using a controlled or uncontrolled input element for 
the lifetime of the component. More info: https://fb.me/react-controlled-components
in input (created by Checkbox)
in div (created by Checkbox)
in Checkbox …
```

fix(Checkbox): Set checked value correctly

---

packages/patternfly-4/react-core/src/components/Dropdown/DropdownMenu.js

**What**: fix for handling when options are disabled. Focus should be on the first non-disabled item.
**Refer to issue**: Fixes #2017

fix(Dropdown): handle on enter focusing when options are disabled

---

packages/patternfly-3/patternfly-react/src/index.js

fix #2040
**What**:
Added `HorizontalNav` to `src/index` in PF3

fix(HorizontalNav): Horizontal nav is not exported for build.

---

packages/patternfly-4/react-core/src/components/Select/Select.js
packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.js.snap

**What**: Fix for children operations to account for a direct list of JSX children (opposed to current examples, which map an array). Also updated no results found state for Typeahead to account for console warnings.
**Refer to issue**: #2039

fix(Select): account for direct JSX children

---

packages/patternfly-4/react-core/src/components/Select/Select.d.ts

**What**: TypeScript definition file of Select component. This makes the `onSelect` prop required, and now has the correct parameters. Selections can now also take in null, which is the default value used within the Select component
From:
```js
onSelect(event: ReactEventHandler<HTMLOptionElement, Event>)
//...
selections?: string | Array<string>;
```
to
```js
onSelect(event: ReactEventHandler<HTMLOptionElement, Event>, element: string, isPlaceholder: boolean): void;
//...
selections?: string | Array<string> | null;
```

fix(Select): onSelect prop TypeScript definition

---

packages/patternfly-4/react-core/src/components/Modal/Modal.md
packages/patternfly-4/react-core/src/components/Modal/ModalBoxHeader.tsx
packages/patternfly-4/react-core/src/components/Modal/__snapshots__/ModalBoxHeader.test.tsx.snap

**What**:
In core, the no header modal doesn't have title or a screen-reader element.
This PR is supposed to be aligned to that change.
This PR closes #2056
// cc @jeff-phillips-18

fix(modal): do not render title when hideTitle is true 

---

packages/patternfly-4/react-charts/src/components/ChartTheme/ChartTheme.d.ts

Fixes #2061
**What**:
- ChartBaseTheme and ChartDonutTheme type definitions were using `const` instead of `type` or `interface`. Update to interfaces which extend VictoryThemeInterface.
- None of the types in ChartTheme.d.ts were associated with variable declarations, so module imports did not work as expected. Declare variables to associate types with instances.

fix(Charts): Fix type definitions for chart themes

---

packages/patternfly-4/react-core/src/components/Page/Page.md
packages/patternfly-4/react-core/src/components/Page/PageSection.d.ts
packages/patternfly-4/react-core/src/components/Page/PageSection.js
packages/patternfly-4/react-core/src/components/Page/PageSection.test.js
packages/patternfly-4/react-core/src/components/Page/__snapshots__/PageSection.test.js.snap

**What**:
closes #1707 
Added the `no-fill` and `fill` modifiers to the PageSection component + added an example to `Page.md`.
//cc @mcoker @mcarrano

feat(page): add fill and no-fill modifiers to page sections

---

packages/patternfly-4/react-core/src/components/Tabs/Tabs.js
packages/patternfly-4/react-core/src/components/Tabs/Tabs.md
packages/patternfly-4/react-core/src/components/Tabs/__snapshots__/Tabs.test.js.snap

Closes: #1739 
Makes the scroll buttons visible again when there is tabs overflow

Tabs: fix scrollable tabs

---

packages/patternfly-4/react-core/src/components/Pagination/Pagination.js
packages/patternfly-4/react-core/src/components/Pagination/__snapshots__/Pagination.test.js.snap

**What**:
Pagination keeps showing 0-0 items on any page because of wrong default props. This PR changes default props of `itemsStart` and `itemsEnd` to null so we don't have any lint errors and we can check if consumer actually set these props so we can calculate current page indexes.

fix(Pagination PF4): set default items start and end to null

---

packages/patternfly-4/react-docs/package.json

**What**: If you add new imports to your MDX file, rerun `yarn develop` which now clears the gatsby-mdx cache and lets you be on your merry way.

chore(react-docs): clean mdx cache before develop

---

packages/patternfly-3/patternfly-react/src/index.js

**What**:
In https://github.com/patternfly/patternfly-react/pull/1109, the new `BreadcrumbSwitcher` component was added, but it was never exported in the main `index.js` file, so it can't be imported by name from the package like `import { BreadcrumbSwitcher } from 'patternfly-react';`, instead it can only be imported from `node_modules/patternfly-react/dist/js/components/BreadcrumbSwitcher`. This PR just adds it to `index.js` so it can be imported normally.
Needed downstream for https://github.com/ManageIQ/manageiq-v2v/issues/865.

fix(index.js): [PF3] Export BreadcrumbSwitcher from patternfly-react index

---

packages/patternfly-4/react-core/src/components/Popover/Popover.tsx

Fixes https://github.com/patternfly/patternfly-react/issues/2108
There is already a default value for maxWidth, so we just need to make this optional. Tested with the Cost Management UI.

fix(popover): maxWidth typescript error

---

packages/patternfly-4/react-core/src/components/Popover/Popover.md
packages/patternfly-4/react-core/src/components/Select/Select.d.ts
packages/patternfly-4/react-core/src/components/Tooltip/Tooltip.md
packages/patternfly-4/react-core/src/demos/ToolbarDemo.md

**What**: This PR updates the SelectProps interface to avoid a type error when importing react-core into a TypeScript application. I also removed some unnecessary code in a couple of the demo's I followed recently. Copying the code as is was creating an error. I think they were safe deletions but worth double checking.
**Additional issues**: https://github.com/patternfly/patternfly-react/issues/2106

fix(Select): update SelectProps interface, clean up demos

---

packages/patternfly-4/react-core/src/components/Popover/Popover.md
packages/patternfly-4/react-core/src/components/Popover/Popover.test.tsx
packages/patternfly-4/react-core/src/components/Popover/Popover.tsx
packages/patternfly-4/react-core/src/components/Popover/__snapshots__/Popover.test.tsx.snap

**What**: This PR changes PopoverPosition from a const to an enum. This allows users to specify their choice of a string or object property for the `position` property value on Popover component. Also adds a test that exercises this method to ensure it doesn't regress going forward.
**Additional issues**: https://github.com/patternfly/patternfly-react/issues/2099

fix(popover): make PopoverPosition an enum

---

packages/patternfly-4/react-charts/src/components/ChartLegend/ChartLegend.js
packages/patternfly-4/react-charts/src/components/ChartLegend/__snapshots__/ChartLegend.test.js.snap
packages/patternfly-4/react-charts/src/components/ChartPie/ChartPie.js
packages/patternfly-4/react-charts/src/components/ChartPoint/__snapshots__/ChartPoint.test.js.snap
packages/patternfly-4/react-charts/src/components/ChartVoronoiContainer/ChartVoronoiContainer.js

This simply allows users to override props like labelComponent, containerComponent, etc.
Fixes https://github.com/patternfly/patternfly-react/issues/2102

fix(charts): Add defaults for component props

---

packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.tsx
packages/patternfly-4/react-core/src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap

**What**:
fixes #2036 
This change checks whether `onChange` is set by the user.
If it does, it means the component is controlled by the user. In this case, the input `checked` props should be set by `isChecked/checked` props passed to `Checkbox`. Otherwise, set input `checked` only if `checked` is true or false or `isChecked` is true (because `isChecked` is Boolean TS by default sets it to false).

fix(checkbox): set checked if onChanged is not the default

---

packages/patternfly-4/react-charts/CHANGELOG.md

**What**: I've solved the mystery. We use [Angular Changelog syntax](https://www.npmjs.com/package/conventional-changelog-angular#footer).

chore(charts): major bump react-charts

---

packages/patternfly-4/react-charts/src/components/ChartAxis/ChartAxis.tsx
packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/ChartDonutThreshold.tsx
packages/patternfly-4/react-charts/src/components/ChartTheme/ChartTheme.ts
packages/patternfly-4/react-charts/src/components/ChartTheme/index.ts
packages/patternfly-4/react-charts/src/components/ChartUtils/chart-theme.ts

A simple fix to remove the ChartThemeDefinition export from the ChartTheme index.ts file.
Fixes https://github.com/patternfly/patternfly-react/issues/2148

fix(charts): remove ChartThemeDefinition export from index.ts

---

packages/patternfly-4/react-charts/src/components/Chart/Chart.tsx
packages/patternfly-4/react-charts/src/components/ChartBar/examples/ChartBar.md
packages/patternfly-4/react-charts/src/components/ChartStack/ChartStack.tsx

Modifies Chart & ChartStack to use ReactNode as `children` type.
Fixes https://github.com/patternfly/patternfly-react/issues/2152

fix(charts): chart: wrong 'children' type

---

packages/patternfly-4/react-core/src/components/AboutModal/AboutModal.tsx

**What**:
Noticed this while release testing `@patternfly/react-core`  3.34.0 today. This will just ensure the about modal container exists on initial load if `isOpen` is passed `true` with children contents initially...

fix(aboutmodal): support isOpen initially set true in about modal

---

packages/patternfly-4/react-table/src/components/Table/BodyWrapper.js

fix(wrapper): revert bodywrapper conversion to stateless-function

---

packages/patternfly-4/react-table/src/components/Table/RowWrapper.d.ts
packages/patternfly-4/react-table/src/components/Table/index.d.ts

**What**:
When using react table in typescript project there is no way how to import `RowWrapper` implementation and copy pasting parts of it is bad. So this PR fixes this problem by exporting `RowWrapperProps` as interface and `RowWrapper` as implementation.
There might be problems because we are changing interface to implementation, but this is not that greatly used interface so it should be fine. @suomiy, @priley86 are you using this interface somewhere?
Fixes: https://github.com/patternfly/patternfly-react/issues/2109

fix(PF4 Table): Export RowWrapper implementation

---

package.json

Add "shx" package to root dev dependencies since it is used in the root npm scripts

chore(dependencies): Add "shx" package to root dev dependencies

---

packages/patternfly-4/react-core/src/components/Nav/Nav.test.tsx
packages/patternfly-4/react-core/src/components/Nav/NavItem.tsx
packages/patternfly-4/react-core/src/components/Nav/__snapshots__/Nav.test.tsx.snap

**What**:
Keeps classNames set on the child of a custom NavItem.
Fixes #2133

fix(NavItem): Maintain className passed to custom NavItems

---

packages/patternfly-4/react-core/src/components/Pagination/OptionsToggle.js
packages/patternfly-4/react-core/src/components/Pagination/Pagination.test.js
packages/patternfly-4/react-core/src/components/Pagination/PaginationOptionsMenu.js
packages/patternfly-4/react-core/src/components/Pagination/__snapshots__/Pagination.test.js.snap

**What**:
Per page option should be possible to hide by passing empty array of per page options.
Fixes: https://github.com/patternfly/patternfly-react/issues/2174

feat(PF4: Pagination): When empty array sent to pagination no per page should be visible

---

packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/ChartDonutThreshold.tsx
packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/ChartDonutUtilization.tsx
packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/__snapshots__/ChartDonutThreshold.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/__snapshots__/ChartDonutUtilization.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/examples/ChartDonutUtilization.md
packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/examples/chart-donut-utilization.scss

This PR is for donut utilization changes requested by @TheRealJon for use in OpenShift.
Fixes https://github.com/patternfly/patternfly-react/issues/2191
Fixes https://github.com/patternfly/patternfly-react/issues/2192
Fixes https://github.com/patternfly/patternfly-react/issues/2194
I was able to fix #2191 by setting capHeight (using a rem value) in order to help center the label vertically. I only use this when both title and subtitle are available -- not necessary for a single label. I've added a property so it may be overridden.
I was able to address #2192 by changing the default donutHeight and donutWidth properties to use the min. of the given SVG height or width. If height & width are not provided, the default theme property would be used.
With these changes, the user can just set …

fix(charts): align label vertically and add donutHeight/Width defaults

---

packages/patternfly-4/react-table/src/components/Table/BodyWrapper.js

**What**:
Remove `rows` and `onCollapse` from `..props`
The recently collapse changes added some unknown props of table
Just remove it from `..props`

fix(react-table): Fix error Unknown event handler property `onCollapse`.

---

packages/patternfly-4/react-table/src/components/Table/Table.d.ts

**What**:
Makes following props of `IRow` to optional
- isOpen
- parent
- props
https://github.com/patternfly/patternfly-react/blob/979f13f1525410f7bccc108480736d3898550333/packages/patternfly-4/react-table/src/components/Table/Table.js#L183
The `parent` props should not define anything to pass the check

fix(react-table): Some props of IRow should not required

---

scripts/hashDir.js
scripts/incrementalBuild.js

**What**: Passing `stream: true` to lerna caused it to call `process.stdout.setMaxListeners(children);` with one too few children, since our wrapper program is also listening to `process.stdout`. Since there is no way to close `stdout` in NodeJS that I know of, for now we can just not pass `stream: true` to lerna and be patient with output that doesn't flush until after 30s.
**Additional issues**: I prettied up the script files while I was debugging.

chore(build): Fix MaxEventListenersExceeded

---

packages/patternfly-4/react-core/src/components/Pagination/OptionsToggle.js
packages/patternfly-4/react-core/src/components/Pagination/PaginationOptionsMenu.js
packages/patternfly-4/react-core/src/components/Pagination/__snapshots__/Pagination.test.js.snap

fix(pagination): dropdown closes on click outside of menu area

---

packages/patternfly-4/react-charts/src/components/ChartDonut/__snapshots__/ChartDonut.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/__snapshots__/ChartDonutUtilization.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartLabel/ChartLabel.tsx
packages/patternfly-4/react-charts/src/components/ChartLabel/__snapshots__/ChartLabel.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartTheme/themes/donut-theme.ts
packages/patternfly-4/react-charts/src/components/ChartTheme/themes/donut-utilization-theme.ts
packages/patternfly-4/react-charts/src/components/ChartTheme/themes/label-theme.ts

The VictoryLabel is not part of the theme, so we must apply a default font via ChartLabel.
Fixes https://github.com/patternfly/patternfly-react/issues/2160
Fixes https://github.com/patternfly/patternfly-react/issues/2214

fix(charts): labels should use the overpass font

---

packages/patternfly-4/react-table/README.md
packages/patternfly-4/react-table/src/components/Table/Table.d.ts
packages/patternfly-4/react-table/src/components/Table/index.d.ts

**What**: This PR updates the type used in react-table to be a little more explicit. Also updates the example code in the readme, following along as-is in a TypeScript application leads to the following error
I took a stab at using better types for `transforms`, what do people think about this new type? I'd like to use something more specific than `Array<Function>` if possible as this doesn't inform of what the inputs and outputs should or can be. Might be good to wait until this is converted fully to TS to address the others, but I'm curious what others think.

Table type adjustments

---

packages/patternfly-4/react-table/src/components/Table/CollapseColumn.js
packages/patternfly-4/react-table/src/components/Table/Table.md

**What**:
fixes #1961 
> 1- For closed rows, the caret should point right, not up.
This was occurring b/c Core uses a 270 degree CSS rotation on the AngleDownIcon instead of an AngleRightIcon. In the future, this should animate the same way as the DataList expand icon in Core, but this resolves the icon issue. cc: @mcoker 
> 2- The Collapsible table example does not have the correct highlighting (blue bar on the left). The example for the Compact expandable table is correct.
This is just a miss in the docs on the Collapsible example. We should not be using `headerCol` transform on `cellTransform`.
(none)

fix(react-table): collapse column icon behavior

---

packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncher.tsx
packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.d.ts
packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.js
packages/patternfly-4/react-core/src/components/Dropdown/DropdownItem.js
packages/patternfly-4/react-core/src/components/Dropdown/DropdownMenu.js
packages/patternfly-4/react-core/src/components/Dropdown/Toggle.js
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
packages/patternfly-4/react-core/src/components/Dropdown/dropdownConstants.d.ts
packages/patternfly-4/react-core/src/components/Dropdown/dropdownConstants.js
packages/patternfly-4/react-core/src/components/Dropdown/index.d.ts
packages/patternfly-4/react-core/src/components/Dropdown/index.js
packages/patternfly-4/react-core/src/components/Pagination/__snapshots__/Pagination.test.js.snap

**What**:
Wrap dropdown with context provider so we can change classes for each part of it. Consumers can now change basic classes if they want to. With this approach we will be able to reuse dropdown component as much as possible so we don't have to deal with different classes.

feat(PF4 Dropdown): Wrap dropdown with context

---

packages/patternfly-4/react-core/src/components/Alert/Alert.test.tsx
packages/patternfly-4/react-core/src/components/Alert/Alert.tsx

**What**:
Setting `Alert` to info if not specified differently.
//cc @jgiardino @ssilvert
What: #2154

fix(Alert): set the variant prop to info by default

---

packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/ChartDonutThreshold.tsx
packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/__snapshots__/ChartDonutThreshold.test.tsx.snap

Pie chart tooltips display the x value of each slice as a tooltip label by default. Because we are
doing calculations to mutate the data, this can lead to array indices being displayed as slice labels. Change defaults so that no slice labels are displayed for the static threshold donut. Also, fix a bug where ChartDonutThreshold accessors were being used to format child ChartDonutUtilization data.
Fixes #2258 and #2259

fix(ChartDonutThreshold): Don't show static threshold donut tooltips by default.

---

packages/patternfly-4/react-core/src/components/Page/PageHeader.d.ts
packages/patternfly-4/react-integration/cypress/integration/applicationlauncher.spec.ts
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/ApplicationLauncherDemo/ApplicationLauncherDemo.tsx
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/PageDemo/PageDemo.tsx

fix(ApplicationLauncher): Adjust cypress test

---

packages/patternfly-4/react-core/src/components/Accordion/Accordion.test.tsx
packages/patternfly-4/react-core/src/components/Accordion/Accordion.tsx
packages/patternfly-4/react-core/src/components/Accordion/AccordionToggle.tsx
packages/patternfly-4/react-core/src/components/Accordion/__snapshots__/Accordion.test.tsx.snap

**What**: Closes #1881, #2273 ; adds headingLevel to prop of parent component (Accordion).

fix(accordion): adds prop to heading level of parent component

---

packages/patternfly-4/react-styles/package.json
packages/patternfly-4/react-styles/src/removeTS.js

**What**: Remove the `.ts` file output from `@patternfly/react-styles/css/*` since we already have it compiled to `.js` and `.d.ts`. Consumers (or other packages) shouldn't be transpiling the `.ts` files themselves.

chore(styles): remove TS from css/*

---

packages/patternfly-4/react-core/src/components/Popover/Popover.md
packages/patternfly-4/react-core/src/components/Popover/Popover.tsx
packages/patternfly-4/react-core/src/components/Popover/PopoverCloseButton.tsx
packages/patternfly-4/react-core/src/components/Tooltip/styles.tsx

**What**: This PR applies an inline style rule to ensure we capture pointer events for the popover close button. Without this, the target area for the close button is too small and causes usability/accessibility issues.
Looks like the tippy lib was adding this conflicting style rule.
**Additional issues**: https://github.com/patternfly/patternfly-react/issues/2275
An outstanding question is; Should this style rule be included as part of core instead?

fix(popover): reset pointer-events to capture default target bounds

---

packages/patternfly-4/react-charts/src/components/ChartDonut/ChartDonut.tsx
packages/patternfly-4/react-charts/src/components/ChartDonut/__snapshots__/ChartDonut.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartDonut/examples/ChartDonut.md
packages/patternfly-4/react-charts/src/components/ChartDonut/examples/chart-donut.scss
packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/ChartDonutThreshold.tsx
packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/ChartDonutUtilization.tsx
packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/__snapshots__/ChartDonutThreshold.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/__snapshots__/ChartDonutUtilization.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/examples/ChartDonutUtilization.md
packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/examples/chart-donut-utilization.scss
packages/patternfly-4/react-charts/src/components/ChartPie/examples/ChartPie.md
packages/patternfly-4/react-charts/src/components/ChartPie/examples/chart-pie.scss
packages/patternfly-4/react-charts/src/components/ChartTheme/themes/common-theme.ts
packages/patternfly-4/react-charts/src/components/ChartTheme/themes/donut-theme.ts
packages/patternfly-4/react-charts/src/components/ChartTheme/themes/donut-utilization-theme.ts
packages/patternfly-4/react-charts/src/components/ChartUtils/chart-label.ts
packages/patternfly-4/react-charts/src/components/ChartUtils/chart-legend.ts
packages/patternfly-4/react-charts/src/components/ChartUtils/chart-origin.ts
packages/patternfly-4/react-charts/src/components/ChartUtils/chart-theme.ts
packages/patternfly-4/react-charts/src/declarations.d.ts
packages/patternfly-4/react-core/src/declarations.d.ts

Refactored the donut, donut utilization, and donut threshold charts in order to position the subtitle to the right or below the chart, similar to the PF3 functionality for small charts (e.g., 150x150px). 
With this change, the label and legend creation has been moved from donut utilization to donut. The donut did not support legends, previously.
In addition, I've refactored the legends so that they are positioned with 16px padding (8px for labels) per the mock below.
Fixes https://github.com/patternfly/patternfly-react/issues/2213
Fixes https://github.com/patternfly/patternfly-react/issues/2183

react-charts: position subtitle center, right, bottom for small charts

---

packages/patternfly-4/react-core/src/components/Button/Button.md
packages/patternfly-4/react-core/src/components/Button/Button.test.tsx
packages/patternfly-4/react-core/src/components/Button/Button.tsx
packages/patternfly-4/react-core/src/components/Button/__snapshots__/Button.test.tsx.snap

**What**: Adds an optional icon property. When present, wraps the icon in the new margin css class and displays the icon before the text.
**Refer to issue**: #2145

feat(Button): add icon property and wrapper css

---

packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/ChartDonutThreshold.tsx
packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/ChartDonutUtilization.tsx
packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/examples/ChartDonutUtilization.md
packages/patternfly-4/react-charts/src/components/ChartUtils/chart-theme.ts

This adds an invert property to the donut utilization and threshold charts, which inverts the threshold color scale used to represent warnings, errors, etc.
Instead of showing a warning at 60% and an error at 90%; for example, this would allow users to show a warning below 60% and an error below 20%.
fixes https://github.com/patternfly/patternfly-react/issues/2254

donut-charts: add invert prop for reversing thresholds

---

packages/patternfly-4/react-virtualized-extension/src/components/Virtualized/VirtualGrid.ts
packages/patternfly-4/react-virtualized-extension/src/components/Virtualized/VirtualTableBody.ts
packages/patternfly-4/react-virtualized-extension/src/components/Virtualized/Virtualized.md
packages/patternfly-4/react-virtualized-extension/src/components/Virtualized/WindowScroller.md

**What**:
* adds the `columnCount` prop to `VirtualTableBody`. This will allow fewer renderings when the consumer is virtualizing by row (and using a `rowRenderer` instead of a `cellRenderer`). This is just an 
optional way to implement the `Grid` for the consumer by passing `rows` instead of `columns`.
* fix virtual scroll w/ `WindowScroller` example. This will now use `isScrollingOptOut` for more accurate scrolling. See React-Virtualized issue [638](https://github.com/bvaughn/react-virtualized/issues/638). 
* remove the `pf-l-grid` class. This was actually not needed before (i misinterpreted our CSS and thought that the  `pf-m-[x]-col-on-[breakpoint]` classes were scoped to `pf-l-grid`, however they are completely separate).

fix(virtual-scroll): add columnCount prop to VirtualTableBody

---

packages/patternfly-4/react-topology/src/components/TopologyControlBar/TopologyControlBar.tsx
packages/patternfly-4/react-topology/src/components/TopologyControlBar/__snapshots__/TopologyControlBar.test.tsx.snap
packages/patternfly-4/react-topology/src/components/TopologyControlBar/css/topology-controlbar-css.ts
packages/patternfly-4/react-topology/src/components/TopologyView/__snapshots__/TopologyView.test.tsx.snap
packages/patternfly-4/react-topology/src/components/TopologyView/css/topology-view-css.ts

Set specifically on control buttons
**What**:
Remove pf-u-* classes from the control bar buttons (not every project will pull these in) and set the styles specifically on the component.

fix(topology): Remove utility PF from control bar buttons

---

.circleci/config.yml
.circleci/release.sh

**What**: Restore node_modules cache to use `yarn run lerna` instead of using `npx lerna`. NPX reinstalls `lerna` each time and is slower.

chore(build): use cache instead of npx

---

packages/patternfly-4/react-core/src/components/Form/FormGroup.tsx
packages/patternfly-4/react-core/src/components/Form/__snapshots__/FormGroup.test.tsx.snap

**What**:
closes #2320 
//cc @mcoker

feat(form): wrap form label text in new element

---

packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/ChartDonutUtilization.tsx

This change simply sorts the donut utilization chart's threshold prop. Thus, ensuring the correct color scale is used when a threshold is reached.
fixes https://github.com/patternfly/patternfly-react/issues/2314

fix(charts): ensure thresholds are sorted

---

packages/patternfly-4/react-core/src/components/Label/Label.md

**What**:
Add the `TS` label to the `Label` navigation link in the documents to indicate that it's written in TypeScript.

docs(label): add typescript flag to the label docs

---

packages/patternfly-4/react-core/src/components/Expandable/Expandable.tsx
packages/patternfly-4/react-core/src/components/Expandable/__snapshots__/Expandable.test.tsx.snap

**What**: Added button type to the component, without which it acts like a submit button on a form.
Fixes: https://github.com/patternfly/patternfly-react/issues/2339

fix(expandable): Add button type to the Expandable Component

---

packages/patternfly-4/react-core/src/components/Form/Form.md

fix(form): update text in form component

---

packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.md
packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.test.tsx
packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.tsx
packages/patternfly-4/react-core/src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
packages/patternfly-4/react-core/src/components/Checkbox/examples/Checkbox.md
packages/patternfly-4/react-core/src/components/Checkbox/examples/checkbox.scss

**What**:
When using checkbox as hierarchical checkbox (parent checkbox with child checkboxes) and user selects only some of child checkboxes parent one should go to 3rd state to indicate user that only some checkboxes were selected.

feat(PF Checkbox): Add 3rd state to checkbox controlled by consumer

---

packages/patternfly-4/react-core/src/components/Dropdown/DropdownMenu.js

fix #2083
**What**:
Update DropdownMenu to focus first dropdown item on mount so that keyboard navigation will always work.

fix(dropdown): Automatically focus first dropdown item when DropdownMenu mounts

---

packages/patternfly-4/react-core/src/components/ChipGroup/ChipGroup.tsx
packages/patternfly-4/react-core/src/components/ChipGroup/ChipGroupToolbarItem.tsx
packages/patternfly-4/react-core/src/components/ChipGroup/__snapshots__/ChipGroup.test.tsx.snap

feat(chipGroup): add heading level prop to toolbar chip group label

---

packages/patternfly-4/react-core/src/components/Radio/Radio.tsx

**What**: Fixes warning re: controlled/uncontrolled switch. Also fixes warning for missing prop on uncontrolled radio.
**Refer to issue**: #2028

fix(Radio): fix warning from undefined starting params

---

packages/patternfly-4/react-charts/src/components/Chart/Chart.tsx
packages/patternfly-4/react-charts/src/components/ChartArea/examples/ChartArea.md
packages/patternfly-4/react-charts/src/components/ChartArea/examples/chart-area.scss

This adds a sparkline example and interpolation (curved lines) to other area examples.
See https://www.patternfly.org/pattern-library/data-visualization/sparkline/
fixes https://github.com/patternfly/patternfly-react/issues/2367

fix(charts): adds sparkline example and interpolation to area examples

---

packages/patternfly-4/react-core/src/components/NotificationBadge/NotificationBadge.md
packages/patternfly-4/react-core/src/components/NotificationBadge/NotificationBadge.test.tsx
packages/patternfly-4/react-core/src/components/NotificationBadge/NotificationBadge.tsx
packages/patternfly-4/react-core/src/components/NotificationBadge/__snapshots__/NotificationBadge.test.tsx.snap
packages/patternfly-4/react-core/src/components/NotificationBadge/index.ts
packages/patternfly-4/react-core/src/components/index.ts
packages/patternfly-4/react-integration/cypress/integration/notificationbadge.spec.ts
packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/NotificationBadgeDemo/NotificationBadgeDemo.tsx
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts

**What**:
Adds the notification badge component to react core.  
#2021

feat(Notification Badge): Adds the notification badge component

---

packages/patternfly-4/react-core/src/components/Tabs/Tab.tsx
packages/patternfly-4/react-core/src/components/Tabs/TabContent.tsx
packages/patternfly-4/react-core/src/components/Tabs/Tabs.tsx

**What**: Fix typescript errors and revert `TabContainer` to a component. Resolves #2359 

fix(tabs): tab container refs

---

packages/patternfly-3/patternfly-react/src/components/BreadcrumbSwitcher/components/BreadcrumbSearchInput.js

In some cases browsers try to  autocomplete the filter input

fix(BreadCrumbSwitcher): disable autocomplete

---

packages/patternfly-4/react-core/CHANGELOG.md
packages/patternfly-4/react-core/package.json
packages/patternfly-4/react-docs/package.json
packages/patternfly-4/react-inline-edit-extension/package.json
packages/patternfly-4/react-integration/demo-app-ts/package.json
packages/patternfly-4/react-table/package.json
packages/patternfly-4/react-topology/package.json
packages/patternfly-4/react-virtualized-extension/package.json

**What**: This time I moved the git `@patternfly/react-core@3.58.0` tag, so lerna should try to release 3.58.1 now!

chore(core): undo 4.0.0 release again

---

packages/patternfly-4/react-charts/src/components/Chart/Chart.tsx
packages/patternfly-4/react-charts/src/components/ChartUtils/chart-padding.ts

Add more robust logic for setting padding values in Chart component
fix #2429
**What**:
- Add new util function for getting padding values from props and falling back to the theme
- Use new util function in Chart component to get default padding values

fix(Chart): Fix runtime errors related to theme padding

---

packages/patternfly-4/react-core/src/components/Modal/Modal.tsx

**What**:
fixes #2405 
When displaying a modal both the children of the body and the modal container had `aria-hidden=true`. The problem was that the container that was compared with the children is not stored in `this.container` but in the state.
This PR fixes this problem.
//cc @jgiardino

fix(Modal): get modal container from state to set/unset aria-hidden

---

packages/patternfly-4/react-tokens/README.md

**What**:
Link to react-tokens page was broken. Updated to point to the Global CSS Variables page.

docs(react-tokens): Update link to react-tokens page in the readme

---

packages/patternfly-4/react-core/src/components/Switch/Switch.tsx
packages/patternfly-4/react-core/src/helpers/ouia.js
packages/patternfly-4/react-core/src/helpers/ouia.ts

**What**: Fixes #2303 for a Switch by conditionally adding `data-ouia-component-type` and `data-ouia-component-id` for Switch based on `window.localStorage['ouia']`. ~Do not merge until some further discussion takes place on #2303 .~
Edit: Discussion has taken place, we can merge now.

feat(react-core): add ouia compatibility to Switch

---

packages/patternfly-4/react-core/src/components/DataList/DataList.md
packages/patternfly-4/react-core/src/components/DataList/DataList.test.js
packages/patternfly-4/react-core/src/components/DataList/DataListAction.tsx
packages/patternfly-4/react-core/src/components/DataList/__snapshots__/DataList.test.js.snap
packages/patternfly-4/react-styles/src/index.d.ts
packages/patternfly-4/react-styles/src/index.js
packages/patternfly-4/react-styles/src/utils.js
packages/patternfly-4/react-table/src/components/Table/utils/decorators/classNames.js

**What**:
closes #2221 and fixes #2197

feat(datalist): add hidden and visible breakpoints

---

packages/patternfly-4/react-core/src/components/ApplicationLauncher/__snapshots__/ApplicationLauncher.test.js.snap
packages/patternfly-4/react-core/src/components/DataList/__snapshots__/DataList.test.js.snap
packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.js
packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.md
packages/patternfly-4/react-core/src/components/Dropdown/DropdownMenu.js
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
packages/patternfly-4/react-core/src/components/Pagination/__snapshots__/Pagination.test.js.snap

**What**:
Fixes Dropdown to not autofocus when custom children are given. Also provides the option to not autofocus on the first item for the case where the application wants to set autoFocus on one of the items.
Fixes #2472

fix(Dropdown): Provide option to not autofocus on first item

---

packages/patternfly-4/react-styles/src/utils.d.ts

**What**:
Adds a missing export for `pickProperties` to react-styles utils typescript
Fixes #2479

fix(styles): Add pickProperties to react-styles utils exports

---

packages/patternfly-4/react-core/src/helpers/util.test.js

**What**: Closes #1624 and fixes keyHandler tests in util.test.js -- tests are now passing.

fix(unit tests): tests now pass in util.test.js

---

packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncher.md
packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncher.test.js
packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncher.tsx
packages/patternfly-4/react-core/src/components/ApplicationLauncher/__snapshots__/ApplicationLauncher.test.js.snap

**What**:
Accept a prop (toggleIcon) to allow overriding the application launcher's toggle icon.

fix(ApplicationLauncher): Allow custom icon for application launcher toggle

---

packages/patternfly-4/react-charts/src/components/ChartDonut/ChartDonut.tsx

Previously `ChartDonut` component (in patternfly 4) for building `subTitle` used prop `titleComponent`, while prop
`subTitleComponent` was unused. So in this PR `titleComponent` in `getSubtitle` was replaced by
`subTitleComponent`.
fix #2486

fix(ChartDonut): Replaced prop `titleComponent` by `subTitleComponent`

---

packages/patternfly-4/react-charts/src/components/Chart/Chart.tsx
packages/patternfly-4/react-charts/src/components/ChartArea/examples/ChartArea.md
packages/patternfly-4/react-charts/src/components/ChartDonut/ChartDonut.tsx
packages/patternfly-4/react-charts/src/components/ChartLegend/ChartLegend.tsx
packages/patternfly-4/react-charts/src/components/ChartLegend/ChartLegendWrapper.tsx
packages/patternfly-4/react-charts/src/components/ChartPie/ChartPie.tsx
packages/patternfly-4/react-charts/src/components/ChartUtils/chart-legend.ts

Cost Management needs to align legends on the bottom-left, for its area charts. This change adds support for a bottom-left aligned legend.
fixes https://github.com/patternfly/patternfly-react/issues/2441

Chart: Add bottom-left legend position

---

packages/patternfly-4/react-core/src/components/Pagination/Navigation.tsx
packages/patternfly-4/react-core/src/components/Pagination/Pagination.test.js
packages/patternfly-4/react-core/src/components/Pagination/__snapshots__/Pagination.test.js.snap
packages/patternfly-4/react-integration/cypress/integration/pagination.spec.ts
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/PaginationDemo/PaginationDemo.tsx

Users can now enter numbers into the input field without highlighting the page number in the input field. You have to hit enter in order for the change to go through and affect the dropdown/buttons. Non-integer inputs will default to the previous page number on enter.
Fixes #2344.

feat(Pagination): Let users enter numbers into the input field

---

packages/patternfly-4/react-core/src/components/LoginPage/LoginForm.test.tsx
packages/patternfly-4/react-core/src/components/LoginPage/LoginForm.tsx
packages/patternfly-4/react-core/src/components/LoginPage/__snapshots__/LoginForm.test.tsx.snap
packages/patternfly-4/react-core/src/components/LoginPage/examples/SimpleLoginPage.js
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/LoginPageDemo/LoginPageDemo.tsx

fix(login page): removes ariaLabel from checkbox

---

packages/patternfly-4/react-core/src/components/Select/CheckboxSelectOption.test.tsx
packages/patternfly-4/react-core/src/components/Select/CheckboxSelectOption.tsx
packages/patternfly-4/react-core/src/components/Select/Select.tsx
packages/patternfly-4/react-core/src/components/Select/SelectOption.test.tsx
packages/patternfly-4/react-core/src/components/Select/SelectOption.tsx
packages/patternfly-4/react-core/src/components/Select/__snapshots__/CheckboxSelectOption.test.tsx.snap
packages/patternfly-4/react-core/src/components/Select/__snapshots__/SelectOption.test.tsx.snap
packages/patternfly-4/react-integration/cypress/integration/select.spec.ts
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectDemo.tsx

**What**: Allows custom display of options via the children param.
**Additional issues**: #2370

feat(Select): add optional display via children to option

---

packages/patternfly-4/react-charts/src/components/ChartArea/examples/ChartArea.md

Simple fix for the area chart examples.
ariaTitle="Donut chart example"
should be:
ariaTitle="Area chart example"
Fixes https://github.com/patternfly/patternfly-react/issues/2509

chore(charts): tweak aria title for area chart

---

packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenu.md
packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenuItem.tsx

**What**: need feedback on these changes -- this WIP PR is in reference to #2415. Currently, the new click event handler I added seems to work fine on the first three options menu demos, where you can click anywhere on the item to select/deselect it.
However, the last three demos don't seem to work with this new prop,  and when you click directly on the check mark of an item that's been selected, it still doesn't deselect the item. 
Why would this be happening?

fix(options menu): update examples to trigger select on the whole item

---

packages/patternfly-4/react-core/src/components/Badge/Badge.md

**What**:
closes #2520 
Add a space between two badges at the Badge example in the documents to match it to the PF4 core documents.
//cc @jschuler

docs(Badge): add space between badges in the examples

---

packages/patternfly-4/react-table/src/components/Table/Table.js

**What**:
If an empty array is passed for `rows` (along with `onSelect` for the "Selectable table" variation), currently the "all rows selection" checkbox in the top left will be set true b/c `rows.every` evaluates true with an empty array.
```
const isSelected = row => row.selected === true; 
let rowsArray = []; 
rowsArray.every(item => isSelected(row));
```
returns `true` when called.
Noted this while testing selection downstream today...

fix(react-table): check empty array in areAllRowsSelected

---

packages/patternfly-4/react-table/src/components/Table/index.d.ts
packages/patternfly-4/react-table/src/components/Table/utils/index.d.ts

**What**: Fix for issue: https://github.com/patternfly/patternfly-react/issues/1657
Add exports for compoundExpand.

fix(react-table): Add exports for compoundExpand.

---

packages/patternfly-4/react-core/src/components/Select/Select.tsx

**What**: Fixes typeahead select children not updating properly when children is changed.
**Refer to issue**: #2090

feat(Select): update typeahead filtered list when children change

---

packages/patternfly-4/react-charts/src/components/ChartArea/examples/ChartArea.md
packages/patternfly-4/react-charts/src/components/ChartBar/examples/ChartBar.md
packages/patternfly-4/react-charts/src/components/ChartDonut/examples/ChartDonut.md
packages/patternfly-4/react-charts/src/components/ChartLine/examples/ChartLine.md
packages/patternfly-4/react-charts/src/components/ChartPie/examples/ChartPie.md
packages/patternfly-4/react-charts/src/components/ChartStack/examples/ChartStack.md
packages/patternfly-4/react-charts/src/components/ChartTheme/ChartTheme.ts
packages/patternfly-4/react-charts/src/components/ChartTheme/themes/dark/multi-color-ordered-theme.ts
packages/patternfly-4/react-charts/src/components/ChartTheme/themes/dark/multi-color-unordered-theme.ts
packages/patternfly-4/react-charts/src/components/ChartTheme/themes/light/multi-color-ordered-theme.ts
packages/patternfly-4/react-charts/src/components/ChartTheme/themes/light/multi-color-unordered-theme.ts
packages/patternfly-4/react-charts/src/components/ChartUtils/chart-theme.ts

Created a new, mutil-color theme specifically for ordered charts; donut, pie, bar, & stack. The existing multi-color theme will continue to be used for unordered charts; area & line.
To avoid a breaking change, `ChartThemeColor.multi` defaults to the `ChartThemeColor.multiOrdered` theme, since area/line are the only unordered charts.
Fixes https://github.com/patternfly/patternfly-react/issues/2550

feat(charts): added new mutil-color theme for ordered charts

---

packages/patternfly-4/react-core/src/experimental/components/Badge/Badge.md
packages/patternfly-4/react-core/src/experimental/components/Badge/Badge.test.tsx
packages/patternfly-4/react-core/src/experimental/components/Badge/Badge.tsx
packages/patternfly-4/react-core/src/experimental/components/Badge/__snapshots__/Badge.test.tsx.snap
packages/patternfly-4/react-core/src/experimental/components/Badge/index.ts
packages/patternfly-4/react-core/src/experimental/components/Button/Button.md
packages/patternfly-4/react-core/src/experimental/components/Button/Button.tsx
packages/patternfly-4/react-core/src/experimental/components/Button/index.ts
packages/patternfly-4/react-core/src/experimental/components/index.ts
packages/patternfly-4/react-core/src/experimental/index.ts
packages/patternfly-4/react-docs/gatsby-node.js
packages/patternfly-4/react-docs/src/templates/mdxTemplate.js

**What**: Add `dist/esm/expiremental`, which is not exported from the main `index.js`. Add support for the docs to show them. Towards https://github.com/patternfly/patternfly-org/issues/1247 .
**Additional issues**: Fixes #2300

feat(experimental): add POC for experimental button and badge

---

packages/patternfly-3/patternfly-react/src/components/Chart/DonutChart.js
packages/patternfly-3/patternfly-react/src/components/Chart/Stories/DonutChartStory.js

donut chart rounds up the title which might lead to a falsy 100%

fix(Donut Chart): Add fixed point notation into percentage donut charts

---

packages/patternfly-4/react-core/src/components/ClipboardCopy/__snapshots__/ClipboardCopyButton.test.tsx.snap
packages/patternfly-4/react-core/src/components/Tooltip/Tooltip.tsx
packages/patternfly-4/react-core/src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
packages/patternfly-4/react-topology/src/components/TopologyControlBar/__snapshots__/TopologyControlBar.test.tsx.snap

Added aria prop for aria-describedby or aria-labelledby support from the Tippy library. Default is library default.
Fixes #1458.

feat(Tooltip): Added support for aria prop from Tippy library

---

packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/ChartDonutThreshold.tsx

The donut threshold chart generates a 'width must be a non-negative' warning when `donutWidth` values are zero.
This change ensures the dynamic chart size is never less than zero.
Fixes https://github.com/patternfly/patternfly-react/issues/2587

fix(chart): ensure dynamic chart size is never less than zero

---

packages/patternfly-4/react-docs/src/components/componentDocs/propsTable.js

**What**: Not wrapping the `type` column looks rather ugly and doesn't resize well @dlabrecq , so I hope you can settle for just not wrapping the name.
**Additional issues**: Fixes #2503

fix(docs): make name column not wrap

---

packages/patternfly-4/react-core/src/components/Pagination/Navigation.tsx
packages/patternfly-4/react-core/src/components/Pagination/OptionsToggle.tsx
packages/patternfly-4/react-core/src/components/Pagination/Pagination.md
packages/patternfly-4/react-core/src/components/Pagination/Pagination.test.js
packages/patternfly-4/react-core/src/components/Pagination/Pagination.tsx
packages/patternfly-4/react-core/src/components/Pagination/__snapshots__/Pagination.test.js.snap

**What**:
When there is 0 items or negative number for pagination show 0th page out of 0 and disable paginating.
fix #2557

fix(PF4: Pagination): When 0 or negative number is passed to Pagintion show 0 pages

---

packages/patternfly-4/react-core/src/components/Page/Page.test.tsx
packages/patternfly-4/react-core/src/components/Page/Page.tsx
packages/patternfly-4/react-core/src/components/Page/__snapshots__/Page.test.tsx.snap
packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutDefaultNav.js
packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutExpandableNav.js
packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutGroupsNav.js
packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutHorizontalNav.js
packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutManualNav.js
packages/patternfly-4/react-core/src/demos/PageLayout/examples/PageLayoutSimpleNav.js
packages/patternfly-4/react-integration/demo-app-ts/src/App.tsx
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/PageDemo/PageDemo.tsx

**What**: Currently, skip to content link sends users to an in-page anchor that sits alongside the main page content container. This generally has the desired effect for sighted keyboard users, however, for screen reader users (SRU) this basically leads to a dead end. It's a dead-end in that the target anchor doesn't contain the page content, so nothing further is announced after the element has been focused.
I think what would be better is if we allow the main content container to carry an id, which can be used as the target of the `SkipToContent` component. Doing this along with supplying a `tabindex="-1"` for the main content area gives us a solid hook for informing SRU of general route changes and informing them of what content is now available.
For sighted users, I don't think this …

fix(page): skip to content should point to primary content container

---

packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.md

**What**: Closes #1837. It appears that list item 1 of this issue has already been addressed, and an aria label already exists on the kebab example of dropdown. This PR adds an aria-label to the "icon only" example of Dropdown.

fix(Dropdown): adds aria-label for icon only example

---

packages/patternfly-4/react-core/src/components/Select/Select.md
packages/patternfly-4/react-core/src/components/Select/Select.test.tsx
packages/patternfly-4/react-core/src/components/Select/Select.tsx
packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.tsx.snap

**What**: Adds a custom callback for the filtering function used in typeahead variants. This replaces the current search entirely, so the function must handle filtering the list of children/options and return the filtered results for the internal state to update.
**Additional issues**: #2369

feat(Select): add select custom filter callback

---

packages/patternfly-4/react-core/src/components/Modal/Modal.md
packages/patternfly-4/react-core/src/components/Modal/Modal.test.tsx
packages/patternfly-4/react-core/src/components/Modal/Modal.tsx
packages/patternfly-4/react-core/src/components/Modal/ModalBoxCloseButton.tsx
packages/patternfly-4/react-core/src/components/Modal/ModalContent.test.tsx
packages/patternfly-4/react-core/src/components/Modal/ModalContent.tsx
packages/patternfly-4/react-core/src/components/Modal/__snapshots__/ModalBoxCloseButton.test.tsx.snap
packages/patternfly-4/react-core/src/components/Modal/__snapshots__/ModalContent.test.tsx.snap
packages/patternfly-4/react-integration/cypress/integration/modal.spec.ts
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/ModalDemo/ModalDemo.tsx

**What**:
Allows for custom header and/or footer in Modal component
Fixes #1545

feat(Modal): Allow custom header and footer

---

packages/patternfly-4/react-core/src/components/Accordion/Accordion.md
packages/patternfly-4/react-core/src/components/Accordion/Accordion.test.tsx
packages/patternfly-4/react-core/src/components/Accordion/Accordion.tsx
packages/patternfly-4/react-core/src/components/Accordion/AccordionContent.tsx
packages/patternfly-4/react-core/src/components/Accordion/AccordionContext.ts
packages/patternfly-4/react-core/src/components/Accordion/AccordionToggle.tsx
packages/patternfly-4/react-core/src/components/Accordion/__snapshots__/Accordion.test.tsx.snap

**What**:
closes #2390 
Added the html structure of Accordion to React.
//cc @jgiardino @christiemolloy

feat(accordion): add definition list use case

---

packages/patternfly-4/react-core/src/layouts/Stack/StackItem.tsx

**What**: Tiny adjustment for Stack layout. Updating the doc to correctly read that `isFilled` is related to the _vertical_ space occupied, not horizontal.
**Additional issues**: Closes https://github.com/patternfly/patternfly-react/issues/2603

chore(doc): fix copy pasta typo

---

packages/patternfly-4/react-topology/src/components/TopologyControlBar/__snapshots__/TopologyControlBar.test.tsx.snap
packages/patternfly-4/react-topology/src/components/TopologyControlBar/css/topology-controlbar-css.ts

**What**:
Remove css settings that override the paddings for the topology control bar buttons
Fixes #2627 
cc @christianvogt @mceledonia

fix(Topology): Fix paddings for topology control bar buttons

---

packages/patternfly-4/react-charts/src/components/Chart/__snapshots__/Chart.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartArea/__snapshots__/ChartArea.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartAxis/__snapshots__/ChartAxis.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartBar/__snapshots__/ChartBar.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartContainer/__snapshots__/ChartContainer.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartDonut/__snapshots__/ChartDonut.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/__snapshots__/ChartDonutThreshold.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/__snapshots__/ChartDonutUtilization.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartGroup/__snapshots__/ChartGroup.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartLegend/__snapshots__/ChartLegend.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartLine/__snapshots__/ChartLine.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartPie/__snapshots__/ChartPie.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartPoint/__snapshots__/ChartPoint.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartStack/__snapshots__/ChartStack.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartTheme/themes/color-theme.ts
packages/patternfly-4/react-charts/src/components/ChartTooltip/__snapshots__/ChartTooltip.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartVoronoiContainer/__snapshots__/ChartVoronoContainer.test.tsx.snap
packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.tsx.snap

fix #2624
**What**:
- Set `area.style.data.fill` to first color scale value in `colorTheme` function.
- Set `line.style.data.stroke` to first color scale value in `colorTheme` function

fix(Chart Themes): Fix missing fill and stroke colors for area and line charts

---

packages/patternfly-4/react-core/src/components/Switch/Switch.md
packages/patternfly-4/react-core/src/components/Switch/Switch.test.js
packages/patternfly-4/react-core/src/components/Switch/Switch.tsx
packages/patternfly-4/react-core/src/components/Switch/__snapshots__/Switch.test.js.snap

**What**:
closes #2435 
closes #2600 
//cc @jgiardino @tlabaj

feat(switch): add aria-labelledby to input

---

jest.config.js
packages/patternfly-4/react-table/package.json
packages/patternfly-4/react-table/src/components/Table/base/body-row.js
packages/patternfly-4/react-table/src/components/Table/base/body.js
packages/patternfly-4/react-table/src/components/Table/base/columns-are-equal.js
packages/patternfly-4/react-table/src/components/Table/base/evaluate-transforms.js
packages/patternfly-4/react-table/src/components/Table/base/merge-props.js
packages/patternfly-4/react-table/src/components/Table/base/resolve-row-key.js
packages/patternfly-4/react-virtualized-extension/package.json

**What**: Fixes #2617 Fixes #2616

chore(table): replace lodash-es with lodash

---

packages/patternfly-3/patternfly-react-extensions/package.json
packages/patternfly-3/patternfly-react/package.json
packages/patternfly-4/react-virtualized-extension/package.json
yarn.lock

**What**:
This should prevent multiple versions of `react-virtualized` being installed if using both `@patternfly/react-virtualized-extension` and `patternfly-react-extensions`, and also ensure treeshaking can occur.
fixes #2642 

fix(react-virtualized): use the same semantic version of react-virtualized globally

---

packages/patternfly-4/react-core/src/components/Pagination/Navigation.tsx
packages/patternfly-4/react-core/src/components/Pagination/Pagination.tsx
packages/patternfly-4/react-core/src/components/Pagination/__snapshots__/Pagination.test.js.snap

fix(Pagination): Fix pagination to update page count

---

packages/patternfly-4/react-core/src/components/Alert/Alert.md
packages/patternfly-4/react-core/src/components/Alert/Alert.tsx
packages/patternfly-4/react-core/src/components/Alert/AlertIcon.tsx
packages/patternfly-4/react-core/src/components/Alert/__snapshots__/Alert.test.tsx.snap
packages/patternfly-4/react-integration/cypress/integration/alert.spec.ts
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/AlertDemo/AlertDemo.tsx

**What**: Add default variant for Alert.
#2596

 feat(Alert): Add the default alert variant 

---

packages/patternfly-4/react-core/src/components/Dropdown/InternalDropdownItem.tsx

**What**: fixes missing event passthrough on internal onSelect callback
**Fixes issue**: #2658

fix(Dropdown): pass event object through onSelect

---

packages/patternfly-4/react-core/src/components/Select/SelectMenu.tsx

**What**:
It seems like Focus Trap throws exception if no children to ref. In order to avoid this error, render the component with no Focus Trap when no children is passed.
closes #2618 
//cc @SpyTec

fix(select): disable focus trap on checkbox select with no children

---

packages/patternfly-4/react-core/src/components/Select/Select.md
packages/patternfly-4/react-core/src/components/Select/Select.test.tsx
packages/patternfly-4/react-core/src/components/Select/Select.tsx
packages/patternfly-4/react-core/src/components/Select/SelectMenu.tsx
packages/patternfly-4/react-core/src/components/Select/SelectOption.test.tsx
packages/patternfly-4/react-core/src/components/Select/SelectOption.tsx
packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.tsx.snap
packages/patternfly-4/react-core/src/components/Select/__snapshots__/SelectOption.test.tsx.snap
packages/patternfly-4/react-core/src/components/Select/selectConstants.tsx
packages/patternfly-4/react-integration/demo-app-ts/src/common/State.ts
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectDemo.tsx

This enhancement allows a user to now pass in a user defined object to store additional data besides just the string value to a select option.  The object must have a toString function that is
responsible for returning the the localized string.
fix #2045
**What**:

feat(Select): Adds the ability to pass in a user defined object

---

packages/patternfly-4/react-core/src/components/Checkbox/examples/Checkbox.md

Prevents inconsistent checking behavior when labels are clicked for uncontrolled vs. controlled
examples.
Fixes #2619.

fix(Checkbox): Updated ids so none repeat

---

packages/patternfly-3/react-console/src/VncConsole/VncActions.js
packages/patternfly-3/react-console/src/VncConsole/VncActions.test.js
packages/patternfly-3/react-console/src/VncConsole/VncConsole.js
packages/patternfly-3/react-console/src/VncConsole/__snapshots__/VncActions.test.js.snap

**What**:
Added possibility to extract toolbar to any other component. Added scaling prop to VncConsole, and
enhance `textConnecting` props to use node type as well. And fixed disconnecting.
We need this features for console page in oVirt VM Portal: https://github.com/oVirt/ovirt-web-ui/pull/956
Example from oVirt VM Portal:
@mareklibra please, review

feat(VncConsole): More possibilities to customize component

---

packages/patternfly-3/patternfly-react/src/components/ExpandCollapse/ExpandCollapse.js
packages/patternfly-3/patternfly-react/src/components/ExpandCollapse/ExpandCollapse.test.js

So that state of the component can be controlled externally
This is to bring feature parity with PF4. Also this makes it possible to keep the UI consistent if
the children of ExpandCollapse trigger a rerender of the component containing the ExpandCollapse.
Fix #2610
**What**: Add onToggle callback for ExpandCollapse so that the expanded state can be controlled externally.
**Additional issues**: #2610

feat(ExpandCollapse): Add onToggle callback 

---

packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.md
packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggleCheckbox.tsx

**What**: This PR clears a couple of errors in dropdown. I suppose we could simply not allow `null` as a value for the union type for checked, but I didn't want to change the behavior so I excluded it from the `HTMLInputElement` props we're extending.
**Additional issues**: https://github.com/patternfly/patternfly-react/issues/2691
Fixes these errors

chore(dropdown): exclude checked from props, fix duplicate key error

---

packages/patternfly-3/react-console/src/VncConsole/VncActions.js
packages/patternfly-3/react-console/src/VncConsole/VncConsole.js

There was incosistent between `portalToolbarTo` prop name and same prop in VncActions.
@priley86 could you, please, take a quick look?

fix(VncConsole): Change prop name in VncActions and added needed prop to VncConsole

---

packages/patternfly-4/react-table/src/components/Table/Table.md
packages/patternfly-4/react-table/src/components/Table/utils/decorators/classNames.ts

**What**: Adds the new 2xl breakpoint to visibleOn and hiddenOn classes.
**Refer to issue**: #2436
@priley86 Is there a good way to add tests for this? I'm unfamiliar with table and unsure how it uses the Visibility object.

feat(Table): add new visibleOn and hiddenOn breakpoint

---

packages/patternfly-3/patternfly-react-extensions/src/components/CatalogTile/CatalogTile.js

Add iconAlt property to use for alt text for icon image in a CatalogTile
fix #2714

fix(CatalogTile): Add iconAlt property

---

packages/patternfly-4/react-core/src/components/Select/Select.md
packages/patternfly-4/react-core/src/components/Select/Select.test.tsx
packages/patternfly-4/react-core/src/components/Select/Select.tsx
packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.tsx.snap
packages/patternfly-4/react-core/src/components/Select/selectConstants.tsx
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectDemo.tsx

**What**: Allows user to specify the direction of the Select's menu expansion. Adds a SelectDirection enum for explicit directions. 
**Refer to issue**: #2368

feat(Select): adds direction prop to Select

---

packages/patternfly-4/react-core/src/components/BackgroundImage/BackgroundImage.tsx
packages/patternfly-4/react-core/src/components/BackgroundImage/__snapshots__/BackgroundImage.test.tsx.snap
packages/patternfly-4/react-topology/src/components/TopologyControlBar/__snapshots__/TopologyControlBar.test.tsx.snap

**What**: Take @mcoker 's advice to close #2693

change width="0" to width=""

---

packages/patternfly-4/react-core/src/components/Expandable/Expandable.md
packages/patternfly-4/react-core/src/components/Expandable/Expandable.test.tsx
packages/patternfly-4/react-core/src/components/Expandable/Expandable.tsx
packages/patternfly-4/react-core/src/components/Expandable/__snapshots__/Expandable.test.tsx.snap
packages/patternfly-4/react-integration/cypress/integration/expandable.spec.ts
packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/ExpandableDemo/ExpandableDemo.tsx
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts

feat(Expandable): Support uncontrolled expandable

---

packages/patternfly-4/react-docs/src/styles/workspace.css

Previous selector was also targeting the div appended by the [2nd Popover example](https://patternfly-react.surge.sh/patternfly-4/components/popover/)

Docs: target the container with more specificity

---

packages/patternfly-4/react-core/src/components/LoginPage/LoginForm.tsx
packages/patternfly-4/react-core/src/components/LoginPage/__snapshots__/LoginForm.test.tsx.snap

fix(loginForm): adds autoFocus to username input

---

packages/patternfly-4/react-core/src/components/EmptyState/EmptyState.tsx
packages/patternfly-4/react-core/src/components/EmptyState/__snapshots__/EmptyState.test.tsx.snap

**What**:
closes #2680 
//cc @jessiehuff can you look at this, am I missing something? :pray: 
//cc @carlosga can you look at this?

fix(emptyState): set the correct size modifier using the  variant prop

---

packages/patternfly-4/react-core/src/components/Tabs/Tabs.test.tsx
packages/patternfly-4/react-core/src/components/Tabs/Tabs.tsx
packages/patternfly-4/react-core/src/components/Tabs/__snapshots__/Tabs.test.tsx.snap

**What**: Added OUIA props to Tabs as per #2425
**Additional issues**: 2 Tabs tests are failing after this change. Any help with figuring out what's causing the issue is appreciated.

feat(Tabs): Added OUIA compatibility to Tabs component

---

packages/patternfly-4/react-charts/src/components/Chart/Chart.tsx
packages/patternfly-4/react-charts/src/components/ChartArea/examples/ChartArea.md
packages/patternfly-4/react-charts/src/components/ChartArea/examples/chart-area.scss
packages/patternfly-4/react-charts/src/components/ChartLegend/ChartLegendWrapper.tsx

In Cost Management, we want to use the chart's embedded legend, but also with an axis label. Currently, the legend and axis label occupy the same vertical position. This change simply adjusts the legend if an axis label is in use.
Fixes https://github.com/patternfly/patternfly-react/issues/2762

Adjust legend position for axis label

---

packages/patternfly-4/react-core/src/components/TextArea/TextArea.md
packages/patternfly-4/react-core/src/components/TextArea/TextArea.tsx

chore(textarea): handle uncontrolled default value

---

packages/patternfly-4/react-charts/src/components/Chart/Chart.tsx
packages/patternfly-4/react-charts/src/components/ChartArea/ChartArea.tsx
packages/patternfly-4/react-charts/src/components/ChartAxis/ChartAxis.tsx
packages/patternfly-4/react-charts/src/components/ChartBar/ChartBar.tsx
packages/patternfly-4/react-charts/src/components/ChartBullet/ChartBullet.tsx
packages/patternfly-4/react-charts/src/components/ChartBullet/ChartBulletComparativeErrorMeasure.tsx
packages/patternfly-4/react-charts/src/components/ChartBullet/ChartBulletComparativeMeasure.tsx
packages/patternfly-4/react-charts/src/components/ChartBullet/ChartBulletComparativeWarningMeasure.tsx
packages/patternfly-4/react-charts/src/components/ChartBullet/ChartBulletGroupTitle.tsx
packages/patternfly-4/react-charts/src/components/ChartBullet/ChartBulletPrimaryDotMeasure.tsx
packages/patternfly-4/react-charts/src/components/ChartBullet/ChartBulletPrimarySegmentedMeasure.tsx
packages/patternfly-4/react-charts/src/components/ChartBullet/ChartBulletQualitativeRange.tsx
packages/patternfly-4/react-charts/src/components/ChartBullet/ChartBulletTitle.tsx
packages/patternfly-4/react-charts/src/components/ChartContainer/ChartContainer.tsx
packages/patternfly-4/react-charts/src/components/ChartDonut/ChartDonut.tsx
packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/ChartDonutThreshold.tsx
packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/ChartDonutUtilization.tsx
packages/patternfly-4/react-charts/src/components/ChartGroup/ChartGroup.tsx
packages/patternfly-4/react-charts/src/components/ChartLegend/ChartLegend.tsx
packages/patternfly-4/react-charts/src/components/ChartLegend/ChartLegendWrapper.tsx
packages/patternfly-4/react-charts/src/components/ChartLine/ChartLine.tsx
packages/patternfly-4/react-charts/src/components/ChartPie/ChartPie.tsx
packages/patternfly-4/react-charts/src/components/ChartScatter/ChartScatter.tsx
packages/patternfly-4/react-charts/src/components/ChartStack/ChartStack.tsx
packages/patternfly-4/react-charts/src/components/ChartTooltip/ChartTooltip.tsx
packages/patternfly-4/react-charts/src/components/ChartVoronoiContainer/ChartVoronoiContainer.tsx

The chart `themeColor` prop documentation incorrectly recommends the wrong color.
Fixes https://github.com/patternfly/patternfly-react/issues/2793

Chart themeColor doc incorrect

---

packages/patternfly-4/react-core/src/components/Modal/Modal.tsx
packages/patternfly-4/react-core/src/components/Modal/ModalContent.tsx

**What**: Fixes FocusTrap breaking on Modal if `showClose` prop is false.
**Additional issues**: Fixes #2757
I have not been able to test this out as I cannot build PatternFly at the moment.

fix(Modal): FocusTrap works with showClose being false

---

packages/patternfly-4/react-charts/src/components/ChartStack/examples/ChartStack.md

**What**:
Refactors downstream monthly stack chart view in Subscriptions based on current discussions. This needs more review and iteration, but we'd like to tackle this problem in PatternFly!
Note: will need to test whatever solution we come up w/ here downstream before merge...
Current screenshots...
https://patternfly-react-pr-2625.surge.sh/patternfly-4/charts/chartstack/
Desktop:
Tablet:
Mobile:

feat(chart-stack): add monthly example

---

packages/patternfly-4/react-core/src/experimental/components/Drawer/Drawer.md
packages/patternfly-4/react-core/src/experimental/components/Drawer/Drawer.test.tsx
packages/patternfly-4/react-core/src/experimental/components/Drawer/Drawer.tsx
packages/patternfly-4/react-core/src/experimental/components/Drawer/DrawerContent.tsx
packages/patternfly-4/react-core/src/experimental/components/Drawer/__snapshots__/Drawer.test.tsx.snap
packages/patternfly-4/react-core/src/experimental/components/Drawer/index.ts

**What**:
Thank you @dlabaj for experimental Drawer component! Usage is nice and straight forward, what do you think about exposing DrawerContent as well? This way users can add the `DrawerPanelContent` when they want to, for instance when data in it should be loaded from server so they want to show it only when user clicks on some element to show it. Also special classes and attributes can be aplied to Content so for instance if app has some special attributes to track where user is located they can do that easilly with this.
It's essentially the same, except that content is not part of Drawer itself, but special component and Panel is not sent trough prop but as child.

feat(PF4 - Drawer): Update drawer to expose all parts

---

packages/patternfly-4/react-core/src/components/Form/ActionGroup.tsx

Removed "import { Action } from 'history'" since it's not being used.
Fixes #2745.

fix(ActionGroup): Remove unneeded Action import

---

packages/patternfly-4/react-core/src/components/Wizard/Wizard.md
packages/patternfly-4/react-core/src/components/Wizard/Wizard.tsx
packages/patternfly-4/react-core/src/components/Wizard/WizardHeader.tsx

feat(Wizard): add support for in page rendering

---

packages/patternfly-4/react-core/src/components/Modal/Modal.md
packages/patternfly-4/react-core/src/components/Modal/Modal.tsx
packages/patternfly-4/react-core/src/components/Modal/ModalBoxFooter.tsx
packages/patternfly-4/react-core/src/components/Modal/ModalContent.tsx
packages/patternfly-4/react-core/src/components/Modal/__snapshots__/ModalContent.test.tsx.snap
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/ModalDemo/ModalDemo.tsx

feat(Modal): add modifier to left align Modal footer

---

packages/patternfly-4/react-core/src/components/DataList/DataListCheck.tsx
packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggleCheckbox.tsx
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/DropdownToggleCheckbox.test.tsx.snap
packages/patternfly-4/react-core/src/components/Radio/Radio.tsx
packages/patternfly-4/react-core/src/components/Radio/__snapshots__/Radio.test.tsx.snap
packages/patternfly-4/react-core/src/components/Select/CheckboxSelectOption.tsx
packages/patternfly-4/react-core/src/components/Select/SelectOption.tsx
packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.tsx.snap
packages/patternfly-4/react-core/src/components/Switch/Switch.test.tsx
packages/patternfly-4/react-core/src/components/Switch/Switch.tsx
packages/patternfly-4/react-core/src/components/Switch/__snapshots__/Switch.test.tsx.snap

**What**: Fixes #2669 and actually changes the `<input>`'s `checked` prop in the DOM for our Switch. This is a somewhat tricky React bug, but the solution is to use `defaultChecked` instead of `checked`. Setting `checked={true}` or `checked={false}` has no effect in the DOM outside of the first render, which is semantically incorrect.

fix(switch): use defaultChecked instead of checked

---

packages/patternfly-4/react-core/src/components/Accordion/Accordion.test.tsx
packages/patternfly-4/react-core/src/components/Accordion/Accordion.tsx
packages/patternfly-4/react-core/src/components/Accordion/AccordionContent.tsx
packages/patternfly-4/react-core/src/components/Accordion/AccordionContext.ts
packages/patternfly-4/react-core/src/components/Accordion/AccordionToggle.tsx

feat(accordion): add content and toggle container props

---

packages/patternfly-4/react-core/src/components/Tabs/Tab.tsx
packages/patternfly-4/react-core/src/components/Tabs/Tabs.md
packages/patternfly-4/react-core/src/components/Tabs/Tabs.test.tsx
packages/patternfly-4/react-core/src/components/Tabs/Tabs.tsx
packages/patternfly-4/react-core/src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TabsDemo/TabsDemo.tsx

**What**:
closes #2623 
In general Tab supported JSX elements the problem is that the `title` props type was set to string. In addition, `Tab` didn't use the `title` prop at all, which was confusing, because it was passed as a child in the `Tabs` component. So what I did was removing `title` from props. 
//cc @xeviknal

feat(tab): support JSX elements in Tab title

---

packages/patternfly-3/patternfly-react/src/components/HorizontalNav/HorizontalNavMenuItem.js

Allow HorizontalNavMenuItem's title to be a node rather than just a string.
Needed by: https://github.com/ManageIQ/react-ui-components/pull/115 and https://github.com/ManageIQ/manageiq-ui-classic/pull/5997
Ping @karelhala

fix(HorizontalNavMenuItem): Allow HorizontalNavMenuItem's title to be a node

---

packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.md
packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggleCheckbox.test.tsx
packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggleCheckbox.tsx
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/DropdownToggleCheckbox.test.tsx.snap

Fixes: #2758
**What**:
Allows passing children to split button in order to allow passing number of selected to this component.

feat(Split button): Allow texts in split button

---

packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncher.tsx
packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.tsx
packages/patternfly-4/react-core/src/components/Dropdown/DropdownWithContext.tsx
packages/patternfly-4/react-core/src/components/OptionsMenu/OptionsMenu.tsx

**What**: Fixes #2871
React Docgen can't handle grabbing the props for 2 exports from the same file. Solution: extract `DropdownWithContext` to a separate file.

fix(dropdown): extract DropdownWithContext

---

packages/patternfly-4/react-core/src/components/Form/FormGroup.tsx

**What**: This fixes a regression from the conversion to TypeScript. The `className` prop is now correctly added to the root element
Regressed line: https://github.com/patternfly/patternfly-react/pull/1933/files#diff-f425f61f010b4c0b3170c953c332aba4L56
**Additional issues**: fixes #2855 
cc @keithjgrant

fix(FormGroup): Add className to element if not inline

---

packages/patternfly-4/react-charts/src/components/ChartPoint/ChartPoint.tsx
packages/patternfly-4/react-charts/src/components/ChartPoint/path-helpers.ts

Created a new legend symbol for thresholds (i.e., horizontal indicators). This is slightly different than the existing dash symbol, which is typically used to show differences between current and previous data, where the dashed symbol represents previous data.
This is to help fix: https://github.com/patternfly/patternfly-react/issues/2797
Also see: https://github.com/patternfly/patternfly-react/pull/2796
New `threshold` sybmol
Existing `dash` symbol

Chart: New symbol for threshold

---

packages/patternfly-4/react-docs/src/components/componentDocs/live-edit.scss

**What**:
Live editor caret was invisible since it was the same color as the background. Changed to white so that it is visible against the black background.

Fix live edit caret color so it is visible

---

packages/patternfly-4/react-charts/src/components/ChartStack/examples/ChartStack.md
packages/patternfly-4/react-charts/src/components/ChartStack/examples/chart-stack.scss

Added stacked area chart example, per design's request
Fixes https://github.com/patternfly/patternfly-react/issues/2853

Add stacked area chart example

---

packages/patternfly-3/patternfly-react/src/components/LoginPage/LoginPage.test.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardForm.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginCardSubmitButton.js

**What**: 
Added the ability to pass additional attributes to the login page submit button

fix(LoginPage): Add attributes to the submit button

---

packages/patternfly-4/react-core/src/components/ClipboardCopy/ClipboardCopy.md

Updated the copy clipboard examples to add one that has an array of object.  This fixes Issue #2845

Adds an example of copy clipboard with array of objects.

---

packages/patternfly-4/react-charts/src/components/ChartDonut/examples/ChartDonut.md

Simple fix for the donut chart tutorial link.
Fixes https://github.com/patternfly/patternfly-react/issues/2939

Broken link for donut chart tutorial

---

packages/patternfly-4/react-core/src/components/Switch/Switch.test.tsx
packages/patternfly-4/react-core/src/components/Switch/Switch.tsx
packages/patternfly-4/react-core/src/components/Switch/__snapshots__/Switch.test.tsx.snap

**What**:
Add a check if `label` is set but not `labelOff` - in that case display `label` on both labels.
if both `label` and `labelOff` are set display in the new format
Otherwise - display switch without labels.
Added tests to verify that if `labelOff` not given the label is shown.
fixes #2814 
//cc @SpyTec

fix(switch): backward compatibility in case labelOff is not set

---

packages/patternfly-4/react-core/src/components/Select/Select.tsx

**What**: This fixes `selections` prop being properly displayed if updated externally.
**Additional issues**: Fixes #2828

fix(Select): display selections data properly

---

packages/patternfly-4/react-core/src/components/Wizard/Wizard.tsx
packages/patternfly-4/react-core/src/components/Wizard/__snapshots__/Wizard.test.tsx.snap

**What**: This adds a default function to `onClose` so that it no longer crashes the component if left out
**Additional issues**: fixes #2831
cc @suomiy

fix(Wizard): adds default function to onClose prop

---

packages/patternfly-4/react-core/src/components/Button/Button.tsx
packages/patternfly-4/react-core/src/components/Button/__snapshots__/Button.test.tsx.snap
packages/patternfly-4/react-core/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap

**What**:
closes #2666 
If component is not `button` and `isDisabled` is true then add `pf-m-disabled` to class name.
//cc @mcoker

fix(button): set the disable modifier when component is not button

---

packages/patternfly-4/react-core/src/components/Modal/ModalContent.tsx

**What**: This removes complexity and uses FocusTrapReact's `active` prop instead of switching to Bullseye component
**Additional issues**: #2966

refactor(Modal): Simplify disabling of FocusTrap

---

packages/patternfly-4/react-charts/src/components/ChartArea/examples/ChartArea.md
packages/patternfly-4/react-charts/src/components/ChartBar/examples/ChartBar.md
packages/patternfly-4/react-charts/src/components/ChartBullet/examples/ChartBullet.md
packages/patternfly-4/react-charts/src/components/ChartDonut/examples/ChartDonut.md
packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/examples/ChartDonutUtilization.md
packages/patternfly-4/react-charts/src/components/ChartLine/examples/ChartLine.md
packages/patternfly-4/react-charts/src/components/ChartPie/examples/ChartPie.md
packages/patternfly-4/react-charts/src/components/ChartStack/examples/ChartStack.md
packages/patternfly-4/react-charts/src/components/Sparkline/examples/sparkline.md

Renamed the chart tutorials to be more readable. As a result, paths to the chart tutorials must be updated.
Fixes https://github.com/patternfly/patternfly-react/issues/2961

chore(charts): update chart tutorial paths

---

packages/patternfly-4/react-table/src/components/Table/Table.tsx

**What**:
fix the warning in #2941 - the `title` prop should allow JSX too.

fix(react-table): fix cell title warning

---

packages/patternfly-4/react-charts/src/components/Sparkline/examples/sparkline.md

The sparkline chart demonstrates how to use a ChartLabel; however, that should be wrapped with a ChartContainer. Otherwise, we output raw `tspan` tags without an SVG, resulting in a console warning.
Fixes https://github.com/patternfly/patternfly-react/issues/2972

chore(charts): add label container to sparkline chart example

---

packages/patternfly-4/react-charts/src/components/ChartVoronoiContainer/ChartVoronoiContainer.tsx

The `ChartVoronoiContainer` component is missing style and responsive props. These are simple pass-thru properties, but must be added to the `ChartVoronoiContainerProps` interface.
https://github.com/patternfly/patternfly-react/issues/2976

Add missing style and responsive props to ChartVoronoiContainer

---

packages/patternfly-4/react-charts/src/components/ChartArea/examples/ChartArea.md
packages/patternfly-4/react-charts/src/components/ChartArea/examples/chart-area.scss
packages/patternfly-4/react-charts/src/components/ChartTheme/ChartTheme.ts
packages/patternfly-4/react-charts/src/components/ChartTheme/themes/threshold-theme.ts
packages/patternfly-4/react-charts/src/components/ChartThreshold/ChartThreshold.test.tsx
packages/patternfly-4/react-charts/src/components/ChartThreshold/ChartThreshold.tsx
packages/patternfly-4/react-charts/src/components/ChartThreshold/__snapshots__/ChartThreshold.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartThreshold/index.ts
packages/patternfly-4/react-charts/src/components/ChartUtils/chart-theme.ts
packages/patternfly-4/react-charts/src/components/index.ts

**What**:
Horizontal Indicator example for Area Charts. Currently reviewing this from a UX/design perspective.
Opened PF issue [2797](https://github.com/patternfly/patternfly-react/issues/2797) for this documentation.
Demo (Multi-color chart with threshold indicators and responsive container example):
https://patternfly-react-pr-2796.surge.sh/patternfly-4/charts/chartarea/
Current Questions:
~~* What color themes do we think appropriate for indicators?~~
~~* What stroke width do we find legible for indicators?~~
~~* Should indicators be connected lines or independent line segments?~~
~~* How should we handle mobile legends gracefully?~~
~~* Do we need custom threshold tooltip behavior?~~
Desktop:
Tablet:
Mobile:

area chart - horizontal indicator example

---

packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.md
packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggleCheckbox.test.tsx
packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggleCheckbox.tsx
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/DropdownToggleCheckbox.test.tsx.snap

Fixes: #2841
**What**:
In order to allow 3rd state in checkbox of split button we have to use `Checkbox` component.

fix(Dropdown split button): Add 3rd state to split button

---

packages/patternfly-4/react-core/src/components/Tabs/Tabs.md
packages/patternfly-4/react-core/src/components/Tabs/Tabs.tsx
packages/patternfly-4/react-core/src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
packages/patternfly-4/react-integration/cypress/integration/tabdemo.spec.ts
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TabsDemo/TabsDemo.tsx

When mountOnEnter is provided as a prop, TabContents will mount on the DOM as you click the corresponding tab. When unmountOnExit is provided, TabContents will unmount from the DOM when no longer visible.
Fixes #2609 and #1448.

feat(Tab): Added two new props: mountOnEnter and unmountOnExit

---

packages/patternfly-4/react-table/src/components/Table/utils/decorators/cellHeightAuto.ts
packages/patternfly-4/react-table/src/components/Table/utils/transformers.test.tsx
packages/patternfly-4/react-table/src/components/Table/utils/transformers.tsx

**What**:
closes #2930 
//cc @mcoker @dlabrecq

feat(tables): support height auto modifier in tr

---

packages/patternfly-4/react-charts/src/components/ChartBullet/ChartBullet.tsx
packages/patternfly-4/react-charts/src/components/ChartBullet/ChartBulletGroupTitle.tsx

In ChartBullet, we're use empty <>...</> tags instead of React.Fragment. For consistency, we want to use React.Fragment. It's possible that gatsby / empty tags generate a "Minified React error" on pf.org?
Fixes https://github.com/patternfly/patternfly-org/issues/1477

fix(charts): replace empty tags with React.Fragment

---

packages/patternfly-4/react-charts/src/components/ChartStack/ChartStack.tsx

Similar to `ChartGoup`, the `ChartStack` component can be used standalone without a `Chart` component. In this case, `ChartStack` should support `ariaDesc` and `ariaTitle`, just as `ChartGroup` does.
Fixes https://github.com/patternfly/patternfly-react/issues/2974

Add ariaDesc and ariaTitle props to stack chart

---

packages/patternfly-3/patternfly-react/src/components/HorizontalNav/HorizontalNavMenuItem.js

HorizontalNavMenuItem 's onItemClick should be a function not an object.
It's getting passed as `onClick` to `<a href ...>` so it must be a bug.
Issue: https://github.com/patternfly/patternfly-react/issues/2994
Ping @rvsia, @karelhala

fix(HorizontalNavMenuItem): Fix onItemClick PropType.

---

packages/patternfly-4/react-core/src/components/Select/Select.tsx
packages/patternfly-4/react-core/src/components/Select/SelectMenu.tsx
packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.tsx.snap
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectDemo.tsx

**What**: adds a maximum height property to select menu
**Refer to issue**: #2483

feat(Select): add max height property, update tests

---

packages/patternfly-4/react-core/src/components/EmptyState/EmptyState.md
packages/patternfly-4/react-core/src/components/EmptyState/EmptyState.test.tsx
packages/patternfly-4/react-core/src/components/EmptyState/EmptyStateIcon.tsx
packages/patternfly-4/react-core/src/components/EmptyState/EmptyStatePrimary.tsx
packages/patternfly-4/react-core/src/components/EmptyState/index.ts

**What**:
closes #2929 
I wanted to add the demos (loading state table and empty state table) but I couldn't because:
1. I don't have the spinner component in react-core
2. They're relayed on the height-auto modifier which isn't in master yet: https://github.com/patternfly/patternfly-react/pull/2932
3. I am waiting on patternfly core to be upgraded to `2.31.9` (please ignore the second commit).

feat(emptyState): Support primary and icon as div elements

---

packages/patternfly-4/react-core/src/components/Dropdown/index.ts
packages/patternfly-4/react-core/src/components/Pagination/Navigation.tsx
packages/patternfly-4/react-core/src/components/Pagination/OptionsToggle.tsx
packages/patternfly-4/react-core/src/components/Pagination/Pagination.tsx
packages/patternfly-4/react-core/src/components/Pagination/PaginationOptionsMenu.tsx
packages/patternfly-4/react-core/src/components/Pagination/ToggleTemplate.tsx
packages/patternfly-4/react-core/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap

**What**: Fix differences with upstream. This makes Pagination be identical to HTML variant
**Additional issues**: Fixes #2903 
~~Note, work in progress. Trying to figure out the best approach for fixing the font size and padding of the dropdown button as well as the font color.~~ Fixed

fix(Pagination): Styling discrepancy with HTML version

---

packages/patternfly-4/react-charts/src/components/ChartBullet/ChartBullet.tsx
packages/patternfly-4/react-charts/src/components/ChartBullet/ChartBulletComparativeErrorMeasure.tsx
packages/patternfly-4/react-charts/src/components/ChartBullet/ChartBulletComparativeMeasure.tsx
packages/patternfly-4/react-charts/src/components/ChartBullet/ChartBulletComparativeWarningMeasure.tsx
packages/patternfly-4/react-charts/src/components/ChartBullet/ChartBulletPrimaryDotMeasure.tsx
packages/patternfly-4/react-charts/src/components/ChartBullet/ChartBulletPrimarySegmentedMeasure.tsx
packages/patternfly-4/react-charts/src/components/ChartBullet/ChartBulletQualitativeRange.tsx
packages/patternfly-4/react-charts/src/components/ChartBullet/__snapshots__/ChartBullet.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartBullet/__snapshots__/ChartBulletComparativeErrorMeasure.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartBullet/__snapshots__/ChartBulletComparativeWarningMeasure.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartBullet/examples/ChartBullet.md
packages/patternfly-4/react-charts/src/components/ChartDonut/ChartDonut.tsx
packages/patternfly-4/react-charts/src/components/ChartDonut/__snapshots__/ChartDonut.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartDonut/examples/ChartDonut.md
packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/ChartDonutThreshold.tsx
packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/ChartDonutUtilization.tsx
packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/__snapshots__/ChartDonutThreshold.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/__snapshots__/ChartDonutUtilization.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/examples/ChartDonutUtilization.md
packages/patternfly-4/react-charts/src/components/ChartPie/ChartPie.tsx
packages/patternfly-4/react-charts/src/components/ChartPie/__snapshots__/ChartPie.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartPie/examples/ChartPie.md

Slightly modified how chart containers are cloned and added examples. This ensures charts can be wrapped with the Tippy tooltip component as an alternate way of providing custom tooltips.
Fixes https://github.com/patternfly/patternfly-react/issues/3047

Charts: Cannot wrap chart with Tippy tooltip

---

packages/patternfly-4/react-table/src/components/Table/HeaderCell.tsx
packages/patternfly-4/react-table/src/components/Table/Table.tsx
packages/patternfly-4/react-table/src/components/Table/utils/headerUtils.test.tsx
packages/patternfly-4/react-table/src/components/Table/utils/headerUtils.tsx

fixes #2941
but just in case you don't want to read the issue....  tl;dr: when collapsed table shows a very undesired `column-foo` when jsx is used as the table header.  So lets allow for a custom data-label attribute to be passed when a dev wants to do this, so they can avoid the erum, undesired collapsed header

fix(table): Adds support for custom dataLabel prop on table header

---

packages/patternfly-4/react-core/src/components/Tabs/Tab.test.tsx
packages/patternfly-4/react-core/src/components/Tabs/Tab.tsx
packages/patternfly-4/react-core/src/components/Tabs/TabButton.test.tsx
packages/patternfly-4/react-core/src/components/Tabs/TabButton.tsx
packages/patternfly-4/react-core/src/components/Tabs/Tabs.tsx
packages/patternfly-4/react-core/src/components/Tabs/__snapshots__/Tab.test.tsx.snap
packages/patternfly-4/react-core/src/components/Tabs/__snapshots__/TabButton.test.tsx.snap
packages/patternfly-4/react-core/src/components/Tabs/__snapshots__/Tabs.test.tsx.snap

…rate component
#3032
**What**:

refactor(Tabs): move TabButton to new file

---

packages/patternfly-4/react-core/src/components/Radio/Radio.md
packages/patternfly-4/react-core/src/components/Radio/Radio.test.tsx
packages/patternfly-4/react-core/src/components/Radio/Radio.tsx
packages/patternfly-4/react-core/src/components/Radio/__snapshots__/Radio.test.tsx.snap

**What**:
closes #2568 
Radio inputs that have the same name should be grouped. One way to group them is inside a div with `role="group"` and `aria-label` to describe this group.
//cc @christiemolloy

fix(radio): group radio inputs in docs (axe-core)

---

packages/patternfly-4/react-charts/src/components/ChartArea/examples/ChartArea.md
packages/patternfly-4/react-charts/src/components/ChartArea/examples/chart-area.scss
packages/patternfly-4/react-charts/src/components/ChartBar/examples/ChartBar.md
packages/patternfly-4/react-charts/src/components/ChartBullet/examples/ChartBullet.md
packages/patternfly-4/react-charts/src/components/ChartDonut/examples/ChartDonut.md
packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/examples/ChartDonutUtilization.md
packages/patternfly-4/react-charts/src/components/ChartLine/examples/ChartLine.md
packages/patternfly-4/react-charts/src/components/ChartPie/examples/ChartPie.md
packages/patternfly-4/react-charts/src/components/ChartStack/examples/ChartStack.md
packages/patternfly-4/react-charts/src/components/ChartThreshold/examples/ChartThreshold.md
packages/patternfly-4/react-charts/src/components/ChartThreshold/examples/chart-threshold.scss
packages/patternfly-4/react-charts/src/components/Sparkline/examples/sparkline.md

Moved the ChartThreshold to its own example. This will make it easier to find the example and we could potentially add more examples later (e.g., for a bar chart).
Fixes https://github.com/patternfly/patternfly-react/issues/3014

Charts: Move ChartThreshold to its own example

---

packages/patternfly-4/react-core/src/experimental/components/Spinner/Spinner.md

docs(Spinner): Fix alert type in docs

---

packages/patternfly-4/react-core/src/components/Radio/Radio.md
packages/patternfly-4/react-core/src/components/Radio/Radio.tsx
packages/patternfly-4/react-core/src/components/Radio/__snapshots__/Radio.test.tsx.snap

Fixes: #3065 
If consumer updates `isChecked` or `chacked` other than via clicking it will not propagate correctly to input, instead it will update `defaultChecked`. This PR fixes such issue by updating `checked` either from `checked` or `isChecked`.

fix(Radio): pass checked either from isChecked or checked

---

packages/patternfly-4/react-charts/src/components/ChartArea/examples/ChartArea.md
packages/patternfly-4/react-charts/src/components/ChartBar/examples/ChartBar.md
packages/patternfly-4/react-charts/src/components/ChartBullet/examples/ChartBullet.md
packages/patternfly-4/react-charts/src/components/ChartDonut/examples/ChartDonut.md
packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/examples/ChartDonutUtilization.md
packages/patternfly-4/react-charts/src/components/ChartLine/examples/ChartLine.md
packages/patternfly-4/react-charts/src/components/ChartPie/examples/ChartPie.md
packages/patternfly-4/react-charts/src/components/ChartStack/examples/ChartStack.md
packages/patternfly-4/react-charts/src/components/ChartTooltip/examples/ChartTooltip.md
packages/patternfly-4/react-charts/src/components/ChartTooltip/examples/chart-tooltip.scss
packages/patternfly-4/react-charts/src/components/Sparkline/examples/sparkline.md

Added multiple examples of how to apply tooltips. The current examples do show tooltips, but there are several different ways they can be applied. It would be best these examples were all in one place.
- Using data labels
- Using a Voronoi container
- Wrapping a chart with a Tippy tooltip
- Adding custom tooltip component to legends
- Using CSS overflow Vs the constrainToVisibleArea prop
- Left aligned tooltips using a theme property

Charts: Tooltip examples

---

packages/patternfly-4/react-charts/src/components/ChartArea/examples/ChartArea.md
packages/patternfly-4/react-charts/src/components/ChartBar/examples/ChartBar.md
packages/patternfly-4/react-charts/src/components/ChartBullet/examples/ChartBullet.md
packages/patternfly-4/react-charts/src/components/ChartDonut/examples/ChartDonut.md
packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/examples/ChartDonutUtilization.md
packages/patternfly-4/react-charts/src/components/ChartLabel/ChartLabel.tsx
packages/patternfly-4/react-charts/src/components/ChartLine/examples/ChartLine.md
packages/patternfly-4/react-charts/src/components/ChartPie/examples/ChartPie.md
packages/patternfly-4/react-charts/src/components/ChartStack/examples/ChartStack.md
packages/patternfly-4/react-charts/src/components/ChartTheme/examples/ChartTheme.md
packages/patternfly-4/react-charts/src/components/ChartTheme/examples/chart-theme.scss
packages/patternfly-4/react-charts/src/components/ChartTheme/themes/base-theme.ts
packages/patternfly-4/react-charts/src/components/Sparkline/examples/sparkline.md

Added an example showing how to create a custom theme that overrides default padding and colors. And as an alternative, an example showing how to override those same properties via the chart's style attribute.
Fixes https://github.com/patternfly/patternfly-react/issues/3015

Charts: Add custom theme example

---

packages/patternfly-4/react-core/src/components/ChipGroup/Chip.test.tsx
packages/patternfly-4/react-core/src/components/ChipGroup/Chip.tsx
packages/patternfly-4/react-core/src/components/ChipGroup/__snapshots__/Chip.test.tsx.snap
packages/patternfly-4/react-core/src/components/ChipGroup/__snapshots__/ChipGroup.test.tsx.snap
packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.tsx.snap

What: Added OUIA props to Tabs as per #2425
~Additional issues: tests failed with these errors and I cannot figure out what I should do next:~

feat(Chip): Added OUIA compatibility to Chip component 

---

packages/patternfly-4/react-core/src/components/Button/Button.tsx

**What**:
closes #2980 
ReactNode is any of the following types: `ReactChild`, `ReactFragment`, `ReactPortal`, `boolean`, `null`, `undefined`.[1]
While `Link` is a component type: `ComponentClass` or `FunctionComponent`.[2]
This PR adds `ComponentType` to the type of `component`. I did set it to `any` to allow other router components in the future or a custom router link. But if we want to support only react-router `Link` I can add a specific type to the component type there.
[1]https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L191
[2]https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L71
//cc @AlexSCorey

fix(button): component type should accept react-router Link

---

packages/patternfly-3/patternfly-react-extensions/package.json
packages/patternfly-3/react-console/README.md
packages/patternfly-3/react-console/package.json
packages/patternfly-3/react-console/src/SerialConsole/XTerm.js
storybook/sass/base.scss
yarn.lock

**What**: Use xterm v4 in SerialConsole. Fixes #2912

SerialConsole: Use xterm v4

---

packages/patternfly-4/react-charts/src/components/ChartLabel/ChartLabel.tsx

Added missing `textAnchor`, `transform`, & `verticalAnchor` props to ChartLabel.
Fixes https://github.com/patternfly/patternfly-react/issues/3027

Charts: Add props to ChartLabel

---

packages/patternfly-4/react-charts/src/components/ChartLegend/examples/ChartLegend.md
packages/patternfly-4/react-charts/src/components/ChartLegend/examples/chart-legend.scss

Adds examples of how to apply various legend features.
The current examples do show legends, but there are a few different ways they can be applied. It would be best these examples were all in one place.
Fixes https://github.com/patternfly/patternfly-react/issues/3080

Charts: add legend examples

---

packages/patternfly-4/react-charts/src/components/ChartTheme/themes/threshold-theme.ts

Simply updated ChartThreshold theme to use pf-core variable
Fixes https://github.com/patternfly/patternfly-react/issues/3025
Threshold chart example

Charts: update ChartThreshold to use pf-core variable

---

packages/patternfly-4/react-charts/src/components/ChartScatter/ChartScatter.tsx
packages/patternfly-4/react-charts/src/components/ChartScatter/__snapshots__/ChartScatter.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartScatter/examples/ChartScatter.md
packages/patternfly-4/react-charts/src/components/ChartScatter/examples/chart-scatter.scss
packages/patternfly-4/react-charts/src/components/ChartTheme/ChartStyles.ts
packages/patternfly-4/react-charts/src/components/ChartTheme/styles/scatter-styles.ts
packages/patternfly-4/react-charts/src/components/ChartTheme/themes/threshold-theme.ts

Adds pf-core variables to the ChartScatter component and examples
Fixes https://github.com/patternfly/patternfly-react/issues/3079

Charts: Add chart scatter examples

---

packages/patternfly-4/react-charts/src/components/ChartArea/examples/ChartArea.md
packages/patternfly-4/react-charts/src/components/ChartBar/examples/ChartBar.md
packages/patternfly-4/react-charts/src/components/ChartBullet/examples/ChartBullet.md
packages/patternfly-4/react-charts/src/components/ChartDonut/examples/ChartDonut.md
packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/examples/ChartDonutUtilization.md
packages/patternfly-4/react-charts/src/components/ChartLine/examples/ChartLine.md
packages/patternfly-4/react-charts/src/components/ChartPie/examples/ChartPie.md
packages/patternfly-4/react-charts/src/components/ChartStack/examples/ChartStack.md
packages/patternfly-4/react-charts/src/components/ChartTheme/examples/ChartTheme.md
packages/patternfly-4/react-charts/src/components/ChartThreshold/examples/ChartThreshold.md
packages/patternfly-4/react-charts/src/components/ChartTooltip/examples/ChartTooltip.md
packages/patternfly-4/react-charts/src/components/ChartTooltip/examples/chart-tooltip.scss
packages/patternfly-4/react-charts/src/components/Sparkline/examples/sparkline.md

Simply replaces HTML anchors in examples with markdown links
Fixes https://github.com/patternfly/patternfly-react/issues/3071

chore(charts): Use markdown links

---

packages/patternfly-4/react-table/src/components/Table/RowWrapper.tsx
packages/patternfly-4/react-table/src/components/Table/Table.tsx
packages/patternfly-4/react-table/src/components/Table/__snapshots__/RowWrapper.test.tsx.snap

Closes #2426
What: Added OUIA props to Table component

feat(Table): Added OUIA compatibility to Table component 

---

packages/patternfly-4/react-core/src/components/Expandable/Expandable.md
packages/patternfly-4/react-core/src/components/Expandable/Expandable.tsx
packages/patternfly-4/react-integration/cypress/integration/expandable.spec.ts
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/ExpandableDemo/ExpandableDemo.tsx

Added two new props that allow user to specify collapsed and expanded toggle text for uncontrolled expandable.
Fixes #2914.

feat(Expandable): Allow for dynamic toggle text in uncontrolled version

---

packages/patternfly-4/react-core/src/components/Select/Select.test.tsx
packages/patternfly-4/react-core/src/components/Select/Select.tsx
packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.tsx.snap

What: Added OUIA props to Tabs as per #2423 
Additional issues: tests failed:
```
FAIL  packages/patternfly-4/react-core/src/components/Select/Select.test.tsx
● Test suite failed to run
TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
packages/patternfly-4/react-core/src/components/Select/Select.tsx:538:47 - error TS2345: Argument of type 'typeof Select' is not assignable to parameter of type 'ComponentClass<SelectProps & InjectedOuiaProps, any> | FunctionComponent<SelectProps & InjectedOuiaProps>'.
Type 'typeof Select' is not assignable to type 'ComponentClass<SelectProps & InjectedOuiaProps, any>'.
Types of property 'defaultProps' are incompatible.
Type '{ "children": ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | …
```

Added OUIA compatibility to Select component

---

packages/patternfly-4/react-docs/gatsby-node.js

Added `eval-source-maps` to Gatsby's webpack config. This outputs source maps so we can debug the examples via Chrome, again.
Fixes https://github.com/patternfly/patternfly-react/issues/3114

Update webpack config to output source maps

---

packages/patternfly-4/react-core/src/components/Select/Select.md
packages/patternfly-4/react-core/src/components/Select/Select.test.tsx
packages/patternfly-4/react-core/src/components/Select/Select.tsx
packages/patternfly-4/react-core/src/components/Select/SelectMenu.tsx
packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.tsx.snap

Fixes: #3117
**What**:
Do not expect filtered values to be returned from `onFilter` function.
Fix errors when opened Select menu by omiting them from spreaded props.

fix(Select): use props children if custom on filter used

---

packages/patternfly-4/react-core/src/components/ClipboardCopy/__snapshots__/ClipboardCopyButton.test.tsx.snap
packages/patternfly-4/react-core/src/components/Tooltip/Tooltip.md
packages/patternfly-4/react-core/src/components/Tooltip/Tooltip.tsx
packages/patternfly-4/react-core/src/components/Tooltip/TooltipContent.tsx
packages/patternfly-4/react-core/src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
packages/patternfly-4/react-topology/src/components/TopologyControlBar/TopologyControlBar.tsx
packages/patternfly-4/react-topology/src/components/TopologyControlBar/__snapshots__/TopologyControlBar.test.tsx.snap

feat(tooltip): allow tooltip text to be left-aligned

---

packages/patternfly-4/react-core/src/components/ApplicationLauncher/__snapshots__/ApplicationLauncher.test.js.snap
packages/patternfly-4/react-core/src/components/Dropdown/InternalDropdownItem.tsx
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
packages/patternfly-4/react-core/src/components/OptionsMenu/__snapshots__/OptionsMenu.test.js.snap
packages/patternfly-4/react-core/src/helpers/util.test.js

Applied Nicole's fix for the Options menu.
Verified that keyhandler is working as expected. Added `componentID` prop in order to fix failing unit tests on keyhandler due to the id being passed to the `<li>`.
Fixes #3029.

fix(Dropdown/Application Launcher/Options Menu): Fix unit tests and options menu

---

packages/patternfly-4/react-charts/src/components/ChartThreshold/ChartThreshold.test.tsx
packages/patternfly-4/react-charts/src/components/ChartThreshold/ChartThreshold.tsx
packages/patternfly-4/react-charts/src/components/ChartThreshold/__snapshots__/ChartThreshold.test.tsx.snap
packages/patternfly-4/react-charts/src/components/ChartThreshold/examples/ChartThreshold.md
packages/patternfly-4/react-charts/src/components/ChartUtils/chart-theme.ts

Addressed the following issues with the new `ChartThreshold` component, which prevents users from providing custom dashed line colors via the style property.
1. When users specify a `themeColor`, it rarely matches the color provided to a custom `ChartLegend`.
2. `ChartThreshold` does not allow users to provide styles. The style property is destructured, but never used.
3. Users cannot provide their own theme. `ChartThreshold` overrides the `theme` property, only applying the default threshold theme. This also prevents a theme from being inherited from a parent component.
4. No property docs are generated for `ChartThreshold` because properties are extended from `ChartLineProps`.
Fixes https://github.com/patternfly/patternfly-react/issues/3022
Depends on …

Charts: Fix ChartThreshold props

---

packages/patternfly-4/react-core/src/components/AboutModal/AboutModal.test.tsx
packages/patternfly-4/react-core/src/components/AboutModal/AboutModal.tsx
packages/patternfly-4/react-core/src/components/Wizard/Wizard.tsx
packages/patternfly-4/react-core/src/components/Wizard/__snapshots__/Wizard.test.tsx.snap

**What**:
closes #2917 
I added `appendTo` to both Wizard and AboutModal.
//ping @jschuler can you have a look?

feat(aboutmodal,wizard): append component to any element in DOM

---

packages/patternfly-4/react-table/src/components/Table/SelectColumn.tsx
packages/patternfly-4/react-table/src/components/Table/SortColumn.tsx
packages/patternfly-4/react-table/src/components/Table/Table.tsx
packages/patternfly-4/react-table/src/components/Table/utils/decorators/selectable.tsx
packages/patternfly-4/react-table/src/components/Table/utils/decorators/sortable.tsx

Fixes: #1431
**What**:  When no rows exist in the table, disable the select all checkbox if present, and disable the sortable column mouse behavior (mouse pointer, text highlight)

fix(react-table): Disable header controls with empty table

---

packages/patternfly-3/patternfly-react/src/components/Cards/Card.js
packages/patternfly-3/patternfly-react/src/components/Cards/UtilizationTrendCard/UtilizationCard.test.js
packages/patternfly-3/patternfly-react/src/components/Cards/index.js

Due to patternfly/patternfly-react#2931, rearrange the way `Card` includes the component's sub-components to match the way the `Wizard` (and all other components) does it.  The new style will allow the sub-component references to survive webpack tree shaking.

fix(Cards): refactor sub-component references

---

packages/patternfly-4/react-core/src/components/ApplicationLauncher/__snapshots__/ApplicationLauncher.test.js.snap
packages/patternfly-4/react-core/src/components/Dropdown/Dropdown.tsx
packages/patternfly-4/react-core/src/components/Dropdown/DropdownWithContext.tsx
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
packages/patternfly-4/react-core/src/components/OptionsMenu/__snapshots__/OptionsMenu.test.js.snap
packages/patternfly-4/react-core/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap

Part of #2423
What: Added OUIA props to Dropdown as per #2423

Added OUIA compatibility for Dropdown

---

packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TableDemo/TableEmptyStateDemo.tsx
packages/patternfly-4/react-table/src/components/Table/Body.tsx
packages/patternfly-4/react-table/src/components/Table/RowWrapper.test.tsx
packages/patternfly-4/react-table/src/components/Table/RowWrapper.tsx
packages/patternfly-4/react-table/src/components/Table/Table.md
packages/patternfly-4/react-table/src/components/Table/Table.test.tsx
packages/patternfly-4/react-table/src/components/Table/Table.tsx
packages/patternfly-4/react-table/src/components/Table/__snapshots__/RowWrapper.test.tsx.snap
packages/patternfly-4/react-table/src/components/Table/utils/decorators/cellHeightAuto.ts

**What**:
close #3132
I mistakenly added the `height auto` modifier to `td` element instead to `tr`.
This PR fixes this by adding the `HeightAuto` attribute to row item.
In addition to that, added a deprecation warning message to whom is using `cellHeightAuto`.
More tests and an example were added.
//cc @jenny-s51 @mcoker @karelhala @tlabaj @redallen

fix(table): set height auto modifier on table row

---

packages/patternfly-4/react-core/src/components/withOuia/withOuia.tsx

**What**:
When rendering Table the ouia context is not correctly set up. This can be fixed by using context passed from props because table components copies these context values to different context and pass them along with props.

fix(OUIA): Use consumer context if specified

---

packages/patternfly-3/patternfly-react/src/components/ClassificationBanner/ClassificationBanner.js
packages/patternfly-3/patternfly-react/src/components/LoginPage/components/LoginCardComponents/LoginLanguagePicker.js
packages/patternfly-3/patternfly-react/src/components/Pagination/Paginator.js
packages/patternfly-3/patternfly-react/src/components/Slider/BootstrapSlider.js
packages/patternfly-3/patternfly-react/src/components/Table/__mocks__/mockServerPaginationTable.js
packages/patternfly-3/patternfly-react/src/components/ToastNotification/TimedToastNotification.js
packages/patternfly-3/patternfly-react/src/components/ToastNotification/ToastNotificationList.js
packages/patternfly-3/patternfly-react/src/components/VerticalNav/VerticalNavItemHelper.js
packages/patternfly-3/patternfly-react/src/components/Wizard/Stories/mockWizardDeployContents.js
packages/patternfly-3/react-console/src/SerialConsole/XTerm.js

The above fixes where done automatically with:
$ npx react-codemod rename-unsafe-lifecycles
Relevant issue: https://github.com/patternfly/patternfly-react/issues/3170

Fix warnings about use of deprecated lifecycle methods

---

packages/patternfly-4/react-core/src/components/EmptyState/EmptyState.test.tsx

**What**:
small nitpick - removing unnecessary debug log in the empty state tests (that I added and forgot to remove :scream: )
issue: #3165 
closes #3165

chore(emptyState): remove debug message from tests

---

packages/patternfly-4/react-core/src/components/withOuia/ouia.ts

add try/catch to the ouia check since there are some environments were simply checking for window.localStorage can throw a security exception

surround ouia check with a try catch

---

packages/patternfly-4/react-core/src/components/Select/Select.tsx
packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.tsx.snap

**What**:
fixes #3167 
Typeahead doesn't filter options correctly. For example, in the `Typeahead select input` example, clicking "Ala" will display all the results even though they don't contain this substring.
The problem is that in the `defaultProps` object the `onFilter` attribute is set to a noop function which makes the `if(onFilter)` block to execute and eventually sets options to the children.
This PR fixes it by setting `onFilter` to `null` which makes the default filter function in `onChange` to be executed.

fix(Select): set onFilter to null to run the default filter

---

packages/patternfly-4/react-core/src/demos/BulkSelectTable.md

**What**: adds an interactive demo between table and toolbar for bulk select functionality.
**Refer to issue**: #2910

feat(BulkSelect demo): add bulk select demo with table and toolbar

---

packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbar.tsx
packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarChipGroupContent.tsx
packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarContent.tsx
packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarExpandableContent.tsx
packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarFilter.tsx
packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarGroup.tsx
packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarItem.tsx
packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarToggleGroup.tsx
packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarUtils.tsx
packages/patternfly-4/react-core/src/experimental/components/DataToolbar/examples/DataToolbar.md

Addresses [issue #3097](https://github.com/patternfly/patternfly-react/issues/3097)
Addresses https://github.com/patternfly/patternfly-react/issues/3046
Implements changes made to core in this PR [#2342](https://github.com/patternfly/patternfly-next/pull/2342)

fix(DataToolbar): implement changes to match PF-Core

---

.github/ISSUE_TEMPLATE/patternfly-issue-template.md

I would like to add an issue template for our contributors.
issue: #2788

Add issue template

---

packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbar.test.tsx
packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarChipGroupContent.tsx
packages/patternfly-4/react-core/src/experimental/components/DataToolbar/__snapshots__/DataToolbar.test.tsx.snap
packages/patternfly-4/react-core/src/experimental/components/DataToolbar/examples/DataToolbar.md
packages/patternfly-4/react-integration/cypress/integration/datatoolbar.spec.ts
packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/DataToolbarDemo/DataToolbarDemo.tsx
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts

chore(DataToolbar): add unit and integration tests

---

packages/patternfly-3/patternfly-react-extensions/package.json
packages/patternfly-3/patternfly-react/package.json
packages/patternfly-3/patternfly-react/src/components/AboutModal/__snapshots__/AboutModal.test.js.snap
packages/patternfly-3/patternfly-react/src/components/DropdownKebab/__snapshots__/DropdownKebab.test.js.snap
packages/patternfly-3/patternfly-react/src/components/InfoTip/__snapshots__/InfoTip.test.js.snap
packages/patternfly-3/patternfly-react/src/components/Masthead/__snapshots__/Masthead.test.js.snap
packages/patternfly-3/react-console/src/AccessConsoles/__snapshots__/AccessConsoles.test.js.snap
packages/patternfly-4/react-catalog-view-extension/package.json
yarn.lock

**What**:
Fixes #3010 
In order to prevent React's warnings about deprecated lifecycle methods, and allow consumers who use Patternfly 3 components to eventually upgrade to React 17, I am upgrading our version of react-bootstrap to take their fixes for https://github.com/react-bootstrap/react-bootstrap/issues/4398.
Once released, this will unblock https://github.com/ManageIQ/manageiq-v2v/issues/1037.
We should do a once-over to make sure all affected PF3 components are still behaving as expected, especially since some of the snapshots changed.

build(package.json): Upgrade react-bootstrap to fix React deprecated lifecycle method warnings

---

packages/patternfly-4/react-integration/demo-app-ts/tsconfig.json

**What**: This PR raises the strict checks used in react-integration package to the maximum degree possible before breaking anything. This should help prevent new issues from being introduced while we chip away at bringing the code into compliance with `strictNullChecks`, `strictFunctionTypes`, `noImplicitAny`, and `strictPropertyInitialization` compiler options.
It's a safe step toward solving https://github.com/patternfly/patternfly-react/issues/3223

chore(demo-app-ts): increase strict checks for react-integration

---

packages/patternfly-4/react-core/README.md

Temporary fix for https://github.com/patternfly/patternfly-react/issues/3154#issuecomment-545600553

PF4: fix(README.md): provides URL location of workspace 

---

packages/patternfly-4/react-catalog-view-extension/package.json

**What**: errors occur when using the extension due to @types/react...specify versions in package.json

fix(react-catalog-extension): fix @types errors when using the extension

---

packages/patternfly-4/react-catalog-view-extension/sass/react-catalog-view-extension/_filter-side-panel.scss
packages/patternfly-4/react-catalog-view-extension/src/components/FilterSidePanel/examples/filterSidePanel.css

provide a 0px left margin for cb in filter side panel (overrides the -20px defaulted in console)
**What**:

fix(react-catalog-view-extension): fix checbox margin on filter side panel

---

packages/patternfly-4/react-catalog-view-extension/sass/react-catalog-view-extension/_catalog-tile.scss

Adjusted selector for gradient effect.

fix(CatalogTile): Edit target selector

---

packages/patternfly-4/react-core/src/components/Select/Select.tsx
packages/patternfly-4/react-core/src/components/Select/SelectMenu.tsx
packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.tsx.snap

fix(Select): remove form typeahead and checkbox selects

---

packages/patternfly-3/patternfly-react/src/components/DateTimePicker/DateTimePicker.js

**What**: missing import in `DateTimePicker`: https://github.com/patternfly/patternfly-react/issues/3302

Properly import formatTime to DateTimePicker

---

packages/patternfly-4/react-styles/src/css/components/Topology/topology-view.css
packages/patternfly-4/react-topology/src/components/TopologyView/TopologyView.tsx
packages/patternfly-4/react-topology/src/components/TopologyView/__snapshots__/TopologyView.test.tsx.snap

fix(topology): Set topology container to take full height of the view

---

packages/patternfly-4/react-core/src/layouts/Flex/FlexUtils.tsx
packages/patternfly-4/react-core/src/layouts/Flex/examples/Flex.md
packages/patternfly-4/react-core/src/layouts/Flex/index.ts

**What**:
closes #3244 
closes #3248
- Set breakpoint as optional in breakpointMd
- Add FlexModifiers and FlexItemModifiers
- Update examples

fix(flex): in breakpointMods set breakpoint as optional and add enums

---

packages/patternfly-4/react-core/src/components/Dropdown/DropdownMenu.tsx
packages/patternfly-4/react-core/src/components/Dropdown/InternalDropdownItem.tsx
packages/patternfly-4/react-core/src/components/Dropdown/examples/Dropdown.md
packages/patternfly-4/react-integration/cypress/integration/dropdown.spec.ts
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/DropdownDemo/DropdownDemo.tsx

Fixed Dropdown a11y keyboard interaction and created cypress a11y/integration tests
Fixes #3210 
Fixes #1849
Preview link: http://pf4-dropdown-accessibility.surge.sh/

Update keyboard interaction for dropdown

---

packages/patternfly-3/patternfly-react/src/components/Chart/DonutChart.js

When using a percentage-type donut chart, there used to be primary title (the percentage) and secondary title, which indicated what the percentage actually means. This secondary title is not being shown anymore. I believe it was accidentally droped in https://github.com/patternfly/patternfly-react/pull/2375
**What**: Add back the secondary title for percentage-type donut charts.
Issue #3323

fix(DonutChart): Put back secondary title when showing percentage

---

packages/patternfly-4/react-core/src/components/ContextSelector/__snapshots__/ContextSelector.test.tsx.snap
packages/patternfly-4/react-core/src/components/Form/FormGroup.test.tsx
packages/patternfly-4/react-core/src/components/Form/FormGroup.tsx
packages/patternfly-4/react-core/src/components/Form/__snapshots__/FormGroup.test.tsx.snap
packages/patternfly-4/react-core/src/components/Form/examples/Form.md
packages/patternfly-4/react-core/src/components/FormSelect/FormSelect.test.tsx
packages/patternfly-4/react-core/src/components/FormSelect/FormSelect.tsx
packages/patternfly-4/react-core/src/components/FormSelect/__snapshots__/FormSelect.test.tsx.snap
packages/patternfly-4/react-core/src/components/FormSelect/examples/FormSelect.md
packages/patternfly-4/react-core/src/components/LoginPage/__snapshots__/LoginForm.test.tsx.snap
packages/patternfly-4/react-core/src/components/TextArea/TextArea.test.js
packages/patternfly-4/react-core/src/components/TextArea/TextArea.tsx
packages/patternfly-4/react-core/src/components/TextArea/__snapshots__/TextArea.test.js.snap
packages/patternfly-4/react-core/src/components/TextArea/examples/TextArea.md
packages/patternfly-4/react-core/src/components/TextInput/TextInput.test.js
packages/patternfly-4/react-core/src/components/TextInput/TextInput.tsx
packages/patternfly-4/react-core/src/components/TextInput/__snapshots__/TextInput.test.js.snap
packages/patternfly-4/react-core/src/helpers/constants.ts
packages/patternfly-4/react-inline-edit-extension/src/components/TableTextInput/__snapshots__/TableTextInput.test.js.snap
packages/patternfly-4/react-integration/cypress/integration/form.spec.ts
packages/patternfly-4/react-integration/cypress/integration/formselect.spec.ts
packages/patternfly-4/react-integration/cypress/integration/textarea.spec.ts
packages/patternfly-4/react-integration/cypress/integration/textinputdemo.spec.ts
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/FormDemo/FormDemo.tsx
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/FormSelectDemo/FormSelectDemo.tsx
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TextAreaDemo/TextAreaDemo.tsx
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TextInputDemo/TextInputDemo.tsx

**What**:
Add `validated` variant to form inputs
React follow on to: https://github.com/patternfly/patternfly-next/pull/2338
closes #3091

feat(form): Add validated variant to form inputs

---

packages/patternfly-4/react-core/src/components/Select/Select.tsx
packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.tsx.snap

**What**: Closes #3304
Defaults `typeaheadInputValue` to null and sets it accordingly when clearing selections as well

fix(Select): Display pre-selected input

---

packages/patternfly-4/react-core/src/demos/PaginationTable.md

fix(PaginationTableDemo): add Spinner and empty state to demo

---

packages/patternfly-4/react-core/src/components/Button/Button.test.tsx
packages/patternfly-4/react-core/src/components/Button/Button.tsx
packages/patternfly-4/react-integration/cypress/integration/button.spec.ts
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/ButtonDemo/ButtonDemo.tsx

**What**:
closes #3208 
//cc @petli-openshift

fix(button): support setting tab index unless not button and disabled

---

packages/patternfly-4/react-core/src/components/ApplicationLauncher/__snapshots__/ApplicationLauncher.test.js.snap
packages/patternfly-4/react-core/src/components/Dropdown/DropdownIcon.tsx
packages/patternfly-4/react-core/src/components/Dropdown/DropdownItem.tsx
packages/patternfly-4/react-core/src/components/Dropdown/DropdownItemIcon.tsx
packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggle.tsx
packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggleAction.test.tsx
packages/patternfly-4/react-core/src/components/Dropdown/DropdownToggleAction.tsx
packages/patternfly-4/react-core/src/components/Dropdown/InternalDropdownItem.tsx
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/DropdownToggleAction.test.tsx.snap
packages/patternfly-4/react-core/src/components/Dropdown/examples/Dropdown.md
packages/patternfly-4/react-core/src/components/Dropdown/index.ts
packages/patternfly-4/react-core/src/components/OptionsMenu/__snapshots__/OptionsMenu.test.js.snap
packages/patternfly-4/react-integration/cypress/integration/dropdown.spec.ts
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/DropdownDemo/DropdownDemo.tsx

feat(Dropdown): add split button action variant

---

packages/patternfly-4/react-core/src/demos/FilterTableDemo.md
packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbar.tsx
packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarChipGroupContent.tsx
packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarContent.tsx
packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarExpandableContent.tsx
packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarFilter.tsx
packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarGroup.tsx
packages/patternfly-4/react-core/src/experimental/components/DataToolbar/DataToolbarUtils.tsx
packages/patternfly-4/react-core/src/experimental/components/DataToolbar/__snapshots__/DataToolbar.test.tsx.snap
packages/patternfly-4/react-core/src/experimental/components/DataToolbar/examples/DataToolbar.md
packages/patternfly-4/react-integration/cypress/integration/datatoolbar.spec.ts
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/DataToolbarDemo/DataToolbarDemo.tsx

Fixes [#3198 ](https://github.com/patternfly/patternfly-react/issues/3198)
follow up to Core issue [#2397](https://github.com/patternfly/patternfly-next/pull/2397)

fix(DataToolbar): move and wrap chips in expandable content

---

packages/patternfly-4/react-integration/cypress/integration/select.spec.ts
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectDemo.tsx

**What**:
closes #3334 
- Add more options to show the "1 more" chip
- Update CSS selector to click the clearn button
- Workaround to Cypress unable to click the label option

fix(select): make integration tests pass

---

packages/patternfly-4/react-core/src/components/ContextSelector/__snapshots__/ContextSelector.test.tsx.snap
packages/patternfly-4/react-core/src/components/LoginPage/__snapshots__/LoginForm.test.tsx.snap
packages/patternfly-4/react-core/src/components/TextInput/TextInput.test.js
packages/patternfly-4/react-core/src/components/TextInput/TextInput.tsx
packages/patternfly-4/react-core/src/components/TextInput/__snapshots__/TextInput.test.js.snap
packages/patternfly-4/react-core/src/components/TextInput/examples/TextInput.md
packages/patternfly-4/react-core/src/helpers/index.ts
packages/patternfly-4/react-core/src/helpers/withInnerRef.tsx
packages/patternfly-4/react-inline-edit-extension/src/components/TableTextInput/__snapshots__/TableTextInput.test.js.snap

**What**:
closes #3153 
- I had to update the tests because of enzyme snapshot (TextInput -> ForwardRef)
- I added an example for react-hook-form. I am not sure we should have it.
- I added `withInnerRef` to the helpers directory. This will make it easier to add support to `ref` in other component.
//cc @kmcfaul @ia3andy

feat(textinput): support passing a ref

---

packages/patternfly-4/react-catalog-view-extension/src/components/FilterSidePanel/FilterSidePanelCategoryItem.tsx

provide remaining props to checkbox component (openshift passes testing properties to
filtersidepanel component)
**What**: Closes #3373

fix(FilterSidePanel): pass remaining props to checkbox component

---

packages/patternfly-4/react-catalog-view-extension/src/components/CatalogTile/__snapshots__/CatalogTile.test.tsx.snap
packages/patternfly-4/react-core/package.json
packages/patternfly-4/react-core/src/components/Popover/Popover.tsx
packages/patternfly-4/react-core/src/components/Popover/__snapshots__/Popover.test.tsx.snap
packages/patternfly-4/react-core/src/components/Tooltip/Tooltip.tsx
packages/patternfly-4/react-core/src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
packages/patternfly-4/react-core/src/helpers/PopoverBase/PopoverBase.js
packages/patternfly-4/react-topology/src/components/TopologyControlBar/__snapshots__/TopologyControlBar.test.tsx.snap
yarn.lock

Addresses: [#3252 ](https://github.com/patternfly/patternfly-react/issues/3252)

Update tippy.js dependency

---

packages/patternfly-4/react-charts/src/components/ChartArea/examples/ChartArea.md
packages/patternfly-4/react-charts/src/components/ChartLegend/examples/ChartLegend.md
packages/patternfly-4/react-charts/src/components/ChartScatter/examples/ChartScatter.md
packages/patternfly-4/react-charts/src/components/ChartStack/examples/ChartStack.md
packages/patternfly-4/react-charts/src/components/ChartTheme/examples/ChartTheme.md
packages/patternfly-4/react-charts/src/components/ChartThreshold/examples/ChartThreshold.md
packages/patternfly-4/react-charts/src/components/ChartTooltip/examples/ChartTooltip.md

Updated the ChartArea examples to use `interpolation="monotoneX"`.
Note: "The way curves are drawn creates misleading visualization" using `interpolation="basis"`.
Fixes: https://github.com/patternfly/patternfly-react/issues/3329

Update interpolation examples to use monotoneX

---

packages/patternfly-4/react-table/src/components/Table/Table.md
packages/patternfly-4/react-table/src/components/Table/utils/decorators/classNames.ts
packages/patternfly-4/react-table/src/components/Table/utils/transformers.test.tsx

**What**: Closes #3355 
Visibility doesn't have `hiddenOn2Xl` and `visibleOn2Xl` and that's why they are set to `undefined` and are not shown in the class prop.
Nevertheless, these two modifiers exist according to the [pf4 core documentations](https://pf4.patternfly.org/documentation/core/components/table#with-hiddenvisible-breakpoint-modifiers).
The problem is that the way react-style parses a modifier name is if it has a number, it will add `_` before it. Thus, `hidden-on-2xl` will be `hiddenOn_2xl` and not `hiddenOn2Xl`.
This patch fixes this and adds a test to verify it works.

fix(table): rename visible/hiddenOn2Xl to visible/hiddenOn_2xl

---

packages/patternfly-3/react-console/sass/_vnc-console.scss

PF3: add spacing between VncAction buttons in react-console

---

packages/patternfly-4/react-core/src/components/Pagination/Pagination.tsx

feat(Pagination): added optional offset prop

---

packages/patternfly-4/react-table/src/components/Table/ActionsColumn.tsx
packages/patternfly-4/react-table/src/components/Table/Table.md

fix(Table): Fix the ActionColumn to allow a link in the actions menu

---

packages/patternfly-4/react-core/src/components/List/List.test.js
packages/patternfly-4/react-core/src/components/List/List.tsx
packages/patternfly-4/react-core/src/components/List/examples/List.md
packages/patternfly-4/react-core/src/components/LoginPage/LoginPage.test.tsx
packages/patternfly-4/react-core/src/components/LoginPage/LoginPage.tsx
packages/patternfly-4/react-integration/cypress/integration/list.spec.ts
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/ListDemo/ListDemo.tsx
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/LoginPageDemo/LoginPageDemo.tsx

feat(list): add the ordered variant
