packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncher.tsx
packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncherContent.tsx
packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncherItem.tsx
packages/patternfly-4/react-core/src/components/ApplicationLauncher/__snapshots__/ApplicationLauncher.test.js.snap
packages/patternfly-4/react-core/src/components/ApplicationLauncher/examples/ApplicationLauncher.md
packages/patternfly-4/react-core/src/components/Dropdown/DropdownItem.tsx
packages/patternfly-4/react-core/src/components/Dropdown/DropdownMenu.tsx
packages/patternfly-4/react-core/src/components/Dropdown/InternalDropdownItem.tsx
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
packages/patternfly-4/react-core/src/components/OptionsMenu/__snapshots__/OptionsMenu.test.js.snap
packages/patternfly-4/react-core/src/components/Select/Select.tsx
packages/patternfly-4/react-core/src/helpers/constants.ts
packages/patternfly-4/react-core/src/helpers/util.test.js
packages/patternfly-4/react-core/src/helpers/util.ts
packages/patternfly-4/react-integration/cypress/integration/applicationlauncher.spec.ts
packages/patternfly-4/react-integration/demo-app-ts/src/Demos.ts
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/ApplicationLauncherDemo/ApplicationLauncherDemo.tsx
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/ApplicationLauncherDemo/ApplicationLauncherFavoritesDemo.tsx
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/index.ts

Application launcher enhancements

---

packages/patternfly-3/patternfly-react/src/components/Modal/InnerComponents/CustomModalDialog.js

**What**: Closes #3364 
As detailed in [my comment here](https://github.com/patternfly/patternfly-react/issues/3364#issuecomment-565645973), since upgrading react-bootstrap in https://github.com/patternfly/patternfly-react/pull/3249 we have had a warning appear when rendering a `<Modal>`. This is happening because we created `CustomModalDialog` based on the react-bootstrap `ModalDialog` in order to introduce a custom prop, and react-bootstrap has since made a change requiring updates to their original `ModalDialog`.
Our `CustomModalDialog` was introduced in https://github.com/patternfly/patternfly-react/commit/9b0f3d9aff2646309bc3e2708d01186c041c10c7 (Nov 13, 2017). Looking at [the history of react-bootstrap's original `ModalDialog`](https://github.com/react-bootstrap/react-bootstrap/commi …

[PF3] Update CustomModalDialog to match changes to original react-bootstrap ModalDialog

---

packages/patternfly-4/react-core/README.md
packages/react-icons/README.md

fix(docs): documented CJS tree shaking solution for icons and react-core

---

packages/patternfly-4/react-charts/src/components/ChartTheme/themes/threshold-theme.ts
packages/patternfly-4/react-charts/src/components/ChartThreshold/ChartThreshold.tsx
packages/patternfly-4/react-charts/src/components/ChartThreshold/__snapshots__/ChartThreshold.test.tsx.snap

Update default threshold stroke width and dash array props from PatternFly-core
Fixes https://github.com/patternfly/patternfly-react/issues/3369

Charts: Update threshold props

---

packages/patternfly-4/react-core/src/components/DataList/DataList.test.js
packages/patternfly-4/react-core/src/components/DataList/DataList.tsx
packages/patternfly-4/react-core/src/components/DataList/DataListCheck.tsx
packages/patternfly-4/react-core/src/components/DataList/DataListItem.tsx
packages/patternfly-4/react-core/src/components/DataList/__snapshots__/DataList.test.js.snap
packages/patternfly-4/react-core/src/components/DataList/examples/DataList.md
packages/patternfly-4/react-integration/cypress/integration/datalist.spec.ts
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/DataListDemo/DataListDemo.tsx

addresses #3233 
I have not figured out a clean way to prevent clicking the kebab (or interacting with components which have their own event handlers) from also selecting a DataListItem row. Events keep propagating up to parent components. I'd love any help people are willing to give... (@evwilkin @jschuler).
Is it possible the interaction as is would be acceptable for merging before code freeze monday? I could open an issue to figure out the last part? @mcarrano @mcoker

feat(DataList): add selectable variant

---

packages/patternfly-4/react-charts/src/components/ChartArea/examples/ChartArea.md
packages/patternfly-4/react-charts/src/components/ChartBar/examples/ChartBar.md
packages/patternfly-4/react-charts/src/components/ChartBullet/examples/ChartBullet.md
packages/patternfly-4/react-charts/src/components/ChartDonut/examples/ChartDonut.md
packages/patternfly-4/react-charts/src/components/ChartDonutUtilization/examples/ChartDonutUtilization.md
packages/patternfly-4/react-charts/src/components/ChartLine/examples/ChartLine.md
packages/patternfly-4/react-charts/src/components/ChartPie/examples/ChartPie.md
packages/patternfly-4/react-charts/src/components/ChartStack/examples/ChartStack.md
packages/patternfly-4/react-charts/src/components/Sparkline/examples/sparkline.md

The Katacoda chart tutorials have moved to a new directory. Thus, the links in the chart examples are broken.
This:
https://katacoda.com/patternfly/courses/charts/area-chart
Should be:
https://katacoda.com/patternfly/courses/react-charts/area-chart

Broken Katacoda tutorial links

---

packages/patternfly-4/react-docs/src/pages/icons.js
packages/react-icons/README.md

Added a link in the react docs icon page to react-icons docs as it is unclear how to use the icons that are shown.
And fixed the link in the react icons docs
Fixes https://github.com/patternfly/patternfly-react/issues/3459

docs(patternfly-4/react-docs/.../icons.js): Added a link to icons docs

---

packages/patternfly-4/react-core/src/components/DataList/DataList.tsx
packages/patternfly-4/react-core/src/components/DataList/DataListItem.tsx
packages/patternfly-4/react-core/src/components/DataList/__snapshots__/DataList.test.js.snap

Closes #3446
- removed default prop of onSelectDataListItem
- `isSelectable` was always true
- added check to `selectedDataListItemId`
- was always true which cause `styles.modifiers.selected` to be always assigned

fix(DataList): properly assign selectable and selected classes

---

packages/patternfly-4/react-core/.babelrc
packages/patternfly-4/react-core/babel.config.js
packages/patternfly-4/react-core/package.json

**What**: Addresses #3268
Added transform-imports for react-core to use direct paths to react-icons dependencies. This change marginally improves build sizes of libraries which depends on a library that is also using react-core package icons and then is consumed by some app.
Bundle size of an app using just PF4 Modal from a third-party library was reduced from 513kB to 27Kb 
Right now, if you use any component with an icon from react-icons (Modal for example), it sometimes bundles all react-icons even if not used.
A reproducible example can be found here: https://github.com/Hyperkid123/pf-core-icons-deps
Detailed info can be found in #3268

Use direct paths to react-icons in prod build

---

packages/patternfly-4/react-catalog-view-extension/README.md
packages/patternfly-4/react-catalog-view-extension/src/components/CatalogTile/examples/CatalogTile.md
yarn.lock

for react-catalog-view-extension
initial cleanup of linting errors on *.md files.

fix(linting): eslint for *.md file fixes

---

.github/stale.yml
packages/patternfly-4/react-docs/src/pages/icons.js

Removes listing of icons that we should not be fully supporting while the design team works out the correct approach.  These were prematurely added.
Fixes: https://github.com/patternfly/patternfly-react/issues/3484

Remove listing of icons while under construction

---

packages/patternfly-3/react-console/package.json

**What**: Update the react-console pacakage's homepage to the currently correct location.
Previously, the URL pointed to a broken link (probably before the monorepo reorganization).

react-console: Fix homepage URL

---

packages/patternfly-4/react-core/src/components/Select/Select.tsx
packages/patternfly-4/react-core/src/components/Select/__snapshots__/Select.test.tsx.snap
packages/patternfly-4/react-core/src/components/Select/examples/Select.md

fix(Select): clear button appears with any typeahead input

---

packages/patternfly-4/react-core/src/layouts/Flex/Flex.test.tsx
packages/patternfly-4/react-core/src/layouts/Flex/FlexUtils.tsx

FlexItem gave TS errors when string literals were used, e.g. `breakpoint: 'sm'`. It was working fine when used with the enum `breakpoint: FlexBreakpoints.xl`
Closes: #3547

allow string literals to be used for FlexItem modifiers

---

packages/patternfly-4/react-table/src/components/Table/Table.tsx

fix(Table): Make IAction onClick optional

---

.circleci/config.yml
.circleci/copy-docs.sh

**What**: Revert some of #3295 which aggressively cached our docs in order to show the Cypress coverage results. This PR stops uploading them to Surge for now.

fix(ci): stop caching stale doc builds

---

packages/patternfly-4/react-integration/cypress/integration/tablesimpleactions.spec.ts

fix(integration): fixed selector in tablesimpleactions

---

packages/patternfly-4/react-core/src/components/ApplicationLauncher/__snapshots__/ApplicationLauncher.test.js.snap
packages/patternfly-4/react-core/src/components/Dropdown/InternalDropdownItem.tsx
packages/patternfly-4/react-core/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
packages/patternfly-4/react-core/src/components/OptionsMenu/__snapshots__/OptionsMenu.test.js.snap

**What**: Closes #3549 
//cc @jeff-phillips-18

fix(Dropdown): Set a random id for dropdown item if id is not given

---

packages/patternfly-4/react-table/src/components/Table/base/columns-are-equal.ts

- This is important when using [React hooks](https://reactjs.org/docs/hooks-state.html)
Fixes #3620
In my case, I'm using the Table and passing a `onCollapse` method within a React component that uses hooks.
I need the columns that are a function, but a different one, to be updated, I'm using as example `onCollapse`, but this applies to any other column.
Consider below code:
```ts
interface RowState {
isOpen: boolean;
// more stuff
}
export const PolicyTable: React.FunctionComponent<PolicyTableProps> = (props) => {
const [ rowsState, setRowsState ] = React.useState<Record<string, RowState>>({});
const onCollapse = (_event, idx: number, isOpen: boolean) => {
const rowState = { ...rowsState[idx], isOpen };
const newRowsState = { ...rowsState };
newRowsState[idx] = rowState; …
```

Column functions are not always equal

---

packages/patternfly-4/react-catalog-view-extension/sass/react-catalog-view-extension/_catalog-tile.scss
packages/patternfly-4/react-catalog-view-extension/src/components/CatalogTile/examples/catalogTile.css

Fixing bug where badging wraps at two lines when you have a wider wordmark. We're just shrinking down the max width of the provided image in the header here.

fix(Catalog Tile): Adjusted max height of header image

---

packages/patternfly-4/react-core/src/components/withOuia/ouia.ts

According to OUIA spec:
> If OUIA attributes are not enabled by default there SHOULD be an HTML local storage variable ouia:enabled, to enable the usage of these attributes. Such action MAY incur a page restart.
This PR makes localStorage ouia related item to comply with the spec.
Fixes  #3625

Changed ouia variable name in localStorage in order to comply with spec

---

packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.test.tsx
packages/patternfly-4/react-core/src/components/Checkbox/Checkbox.tsx
packages/patternfly-4/react-core/src/components/Checkbox/examples/Checkbox.md
packages/patternfly-4/react-core/src/components/Radio/Radio.test.tsx
packages/patternfly-4/react-core/src/components/Radio/Radio.tsx
packages/patternfly-4/react-core/src/components/Radio/examples/Radio.md
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/CheckboxDemo/CheckboxDemo.tsx
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/RadioDemo/RadioDemo.tsx

feat(radio/check): add support for optional description

---

packages/patternfly-4/react-catalog-view-extension/src/components/CatalogItemHeader/examples/catalogItemHeader.css
packages/patternfly-4/react-catalog-view-extension/src/components/CatalogTile/examples/catalogTile.css
packages/patternfly-4/react-catalog-view-extension/src/components/VerticalTabs/examples/verticalTab.css

Many styles on examples stopped working. This change restores all styles on affected examples.
Changed classes to reflect the structure of the HTML, which appears to have changed.
Fixes #3633.

fix(Catalog view extension): Many styles on examples stopped working

---

packages/patternfly-4/react-catalog-view-extension/sass/react-catalog-view-extension/_catalog-tile.scss
packages/patternfly-4/react-catalog-view-extension/src/components/CatalogTile/examples/catalogTile.css

Reducing padding between the badge and logo to avoid text wrapping on relatively short badges in OpenShift.

fix(Catalog tile): Reduce padding between badge and logo

---

packages/patternfly-3/patternfly-react/src/components/Slider/Slider.js

When using the arrow keys to control the slider, it was possible to go below the set minimum value
on the slider. (-1 for a minimum of 0, 0 for a minimum of 1, and so on.) I added a minimum value check for the slider value.
Fixes #3187.

fix(Slider): Add limit for lowest possible value of slider

---

packages/patternfly-4/react-core/src/components/Popover/Popover.tsx
packages/patternfly-4/react-core/src/components/Popover/__tests__/Popover.test.tsx
packages/patternfly-4/react-core/src/components/Popover/__tests__/__snapshots__/Popover.test.tsx.snap

**What**: Closes #3192 . Adds in an optional `midWidth` property that will override the default and allow a custom minimum width on the popover.
Update: the default min-width property will be adjusted to match max-width, making both examples match. This PR could still be added in if we want to allow users to customize the width of a popover.

feat(Popover): add min-width override property

---

packages/patternfly-4/react-core/src/components/DataToolbar/DataToolbar.tsx
packages/patternfly-4/react-docs/src/pages/icons.js
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/TableDemo/TableEditableDemo.tsx
packages/patternfly-4/react-table/src/components/Table/Table.tsx

This PR adds a beta warning for DataToolbar and sets a heading level for one of the doc pages so there are not consecutive h1s. Work toward https://github.com/patternfly/patternfly-react/issues/3624

fix(beta): beta warning for datatoolbar, cleanup

---

packages/patternfly-4/react-core/package.json

Change version for react-icons from 3.15.1 to 3.15.0

fix(version): version updated in react-core for react-icons

---

packages/patternfly-4/react-core/src/experimental/components/DataToolbar/index.ts
packages/patternfly-4/react-core/src/experimental/components/Drawer/index.ts
packages/patternfly-4/react-core/src/experimental/components/index.ts

**What**: Towards #3624  - This PR adds the /experimental/components directory back with barrel file exports for DataToolbar and Drawer, to avoid breaking imports for users who aren't importing from /experimental but instead directly from the component directory.

Fix: Added experimental/components directory

---

packages/patternfly-4/react-core/src/components/Card/Card.tsx
packages/patternfly-4/react-core/src/components/Card/__tests__/Card.test.tsx
packages/patternfly-4/react-core/src/components/Card/examples/Card.md
packages/patternfly-4/react-core/src/helpers/constants.ts
packages/patternfly-4/react-integration/cypress/integration/card.spec.ts
packages/patternfly-4/react-integration/demo-app-ts/src/components/demos/CardDemo/CardDemo.tsx

**What**: Closes #3537 
//cc @mcoker @tlabaj

feat(card): add selectable and selected variation

---

packages/patternfly-4/react-core/src/components/Tabs/Tab.tsx
packages/patternfly-4/react-core/src/components/Tabs/__tests__/__snapshots__/Tab.test.tsx.snap
packages/patternfly-4/react-core/src/components/Tabs/examples/Tabs.md

Addresses issue #2607 
Issue (#3454) opened to address the fact that props descriptions are missing (from all docs it seems).
Note: Tab component cannot return null, or the gatsby parser does not recognize that Tab.tsx returns a component to build the props documentation for Tab. Possible alternative solution could be updating our gatsby-transformer-react-docgen-typescript plugin.

fix(Tabs): update tabs with nav examples + add Tab component to props docs

---

packages/patternfly-4/react-core/src/components/BackgroundImage/BackgroundImage.tsx
packages/patternfly-4/react-core/src/components/BackgroundImage/__tests__/Generated/__snapshots__/BackgroundImage.test.tsx.snap
packages/patternfly-4/react-core/src/components/BackgroundImage/__tests__/__snapshots__/BackgroundImage.test.tsx.snap

This PR removes the `width` attribute for the filter element in BackgroundImage. Looks like it could also be set to the default value of 120%, but omitting it also seems to work so taking that route. Should help clear console errors when using this component.
**What**: Closes https://github.com/patternfly/patternfly-react/issues/3250

Remove width attr from BackgroundImage filter element

---

packages/patternfly-4/react-core/src/layouts/Bullseye/examples/Bullseye.md
packages/patternfly-4/react-core/src/layouts/Flex/examples/Flex.md
packages/patternfly-4/react-core/src/layouts/Gallery/examples/Gallery.md
packages/patternfly-4/react-core/src/layouts/Grid/examples/Grid.md
packages/patternfly-4/react-core/src/layouts/Level/examples/Level.md
packages/patternfly-4/react-core/src/layouts/Split/examples/Split.md
packages/patternfly-4/react-core/src/layouts/Stack/examples/Stack.md
packages/patternfly-4/react-core/src/layouts/Toolbar/examples/Toolbar.md

**What**: Closes https://github.com/patternfly/patternfly-org/issues/1681 - this PR wraps the layouts examples in a function component needed for Codesandbox to render examples correctly.

fix(layouts): wrapped examples to fix codesandbox

---

README.md

**What**: Closes https://github.com/patternfly/patternfly-react/issues/3753 
Updates the parent readme for the project with new content

fix(readme): update readme to match new guidelines

---

packages/patternfly-4/react-core/src/components/InputGroup/examples/InputGroup.md
packages/patternfly-4/react-core/src/layouts/Grid/examples/Grid.md
yarn.lock

**What**:  This PR updates the examples page for InputGroup. It changes this page from being one large example code snippet with all variations together to grouping the examples logically into multiple example code snippets. The code snippets are now much leaner and easier on the eyes.
**Additional issues**: Closes https://github.com/patternfly/patternfly-react/issues/3823

chore(inputgroup): update docs to be more readable

---

packages/patternfly-4/react-docs/src/pages/icons.js
packages/patternfly-4/react-docs/src/pages/index.js

**What**: Towards https://github.com/patternfly/patternfly-org/pull/1705 - this PR adds page titles to React Docs and React Icons pages rather than browser tab simply displaying "PatternFly 4" for both pages.

Added page titles for react docs & react icons pages

---

packages/patternfly-4/react-core/src/components/Alert/__tests__/__snapshots__/Alert.test.tsx.snap
packages/patternfly-4/react-core/src/components/Button/Button.tsx
packages/patternfly-4/react-core/src/components/Button/__tests__/__snapshots__/Button.test.tsx.snap
packages/patternfly-4/react-core/src/components/Button/examples/Button.md
packages/patternfly-4/react-core/src/components/DataToolbar/__tests__/__snapshots__/DataToolbar.test.tsx.snap
packages/patternfly-4/react-core/src/components/Wizard/__tests__/__snapshots__/Wizard.test.tsx.snap

feat(Button): add link icon position for link buttons

---

packages/patternfly-4/react-core/src/components/Drawer/Drawer.tsx

**What**: Towards #3624 - this PR adds a console warning for the Drawer beta component, similar to existing implementations in the DataToolbar and SimpleList components.

added console warning to Drawer beta component

---

packages/patternfly-4/react-catalog-view-extension/src/components/CatalogTile/CatalogTile.test.tsx
packages/patternfly-4/react-catalog-view-extension/src/components/CatalogTile/CatalogTile.tsx
packages/patternfly-4/react-catalog-view-extension/src/components/CatalogTile/__snapshots__/CatalogTile.test.tsx.snap
packages/patternfly-4/react-catalog-view-extension/src/components/CatalogTile/examples/CatalogTile.md

Descriptions are now truncated via CSS, so the truncation function and maxLength props are unnecessary. The only folks using this are migrating off of it in a current PR.
Fixes #3471.

fix(CatalogTile): Removed truncation and maxLength props

---

packages/patternfly-4/react-docs/src/pages/icons.js
packages/patternfly-4/react-docs/src/pages/index.js

**What**: Towards https://github.com/patternfly/patternfly-org/pull/1645 - this PR in addition to https://github.com/patternfly/patternfly-org/pull/1703 add a banner to all site pages for GDPR compliance.  This specifically sets the `showGdprBanner` prop on the `SideNavLayout` component to enable the banner.

add GDPR banner to all pages

---

.circleci/config.yml

I temporarily disabled releasing PF3 to prevent conflicts with master's PF3. Now that PF3 is out of master, we can reenable releasing for PF3.

build(patternfly-3): enable releasing patternfly 3

---

packages/react-core/src/components/Modal/Modal.tsx
packages/react-core/src/components/Modal/ModalContent.tsx
packages/react-core/src/components/Modal/__tests__/ModalContent.test.tsx
packages/react-core/src/components/Modal/__tests__/__snapshots__/ModalContent.test.tsx.snap
packages/react-core/src/components/Modal/examples/Modal.md
packages/react-integration/cypress/integration/modal.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/ModalDemo/ModalDemo.tsx

+ move ID to description when it exists.
**What**: Closes #3777

feat(Modal): add description property

---

packages/react-docs/package.json

**What**: Publishing on master is broken because we published react-docs from our `v4` branch. This should fix it!

fix react-docs version

---

packages/react-core/src/components/DataToolbar/DataToolbarFilter.tsx

Updated code to allow for a key to be used with categoryName.  
TODO:
* Working on updating the demo wanted to get some eyes on the fix though.
**What**: Closes #3552

fix (datatoolbar):  Added support for key with categoryName.

---

.eslintrc.json
packages/react-catalog-view-extension/package.json
packages/react-charts/package.json
packages/react-core/package.json
packages/react-core/src/components/FileUpload/FileUpload.tsx
packages/react-core/src/components/FileUpload/FileUploadField.tsx
packages/react-core/src/components/FileUpload/__tests__/FileUpload.test.tsx
packages/react-core/src/components/FileUpload/__tests__/FileUploadField.test.tsx
packages/react-core/src/components/FileUpload/__tests__/__snapshots__/FileUpload.test.tsx.snap
packages/react-core/src/components/FileUpload/__tests__/__snapshots__/FileUploadField.test.tsx.snap
packages/react-core/src/components/FileUpload/examples/FileUpload.md
packages/react-core/src/components/FileUpload/index.ts
packages/react-core/src/components/index.ts
packages/react-core/src/helpers/__tests__/fileUtils.test.ts
packages/react-core/src/helpers/fileUtils.ts
packages/react-docs/package.json
packages/react-icons/package.json
packages/react-inline-edit-extension/package.json
packages/react-styled-system/package.json
packages/react-styles/package.json
packages/react-table/package.json
packages/react-tokens/package.json
packages/react-topology/package.json
packages/react-virtualized-extension/package.json
yarn.lock

**What**: Closes #3735 
Preview: https://patternfly-react-pr-3865.surge.sh/documentation/react/components/fileupload
**Additional issues**: Based on core implementation from https://github.com/patternfly/patternfly-next/pull/2681, https://github.com/patternfly/patternfly-next/pull/2731 and https://github.com/patternfly/patternfly-next/pull/2776

feat(FileUpload) Add new beta File Upload component

---

packages/react-core/src/components/AboutModal/AboutModal.tsx
packages/react-core/src/components/AboutModal/AboutModalBoxCloseButton.tsx
packages/react-core/src/components/AboutModal/AboutModalContainer.tsx
packages/react-core/src/components/AboutModal/__tests__/AboutModalBoxCloseButton.test.tsx
packages/react-core/src/components/AboutModal/__tests__/__snapshots__/AboutModalBoxCloseButton.test.tsx.snap

fix(aboutmodal): set a customize aria-label to the close button

---

packages/react-core/src/components/EmptyState/EmptyState.tsx
packages/react-core/src/components/EmptyState/examples/EmptyState.md

Added support for new size and updated examples to include extra large empty state.
Fixes #3540.

feat(EmptyState): Added support for extra-large empty state

---

packages/react-core/src/components/Select/Select.tsx
packages/react-core/src/components/Select/__tests__/__snapshots__/Select.test.tsx.snap
packages/react-core/src/components/Select/examples/Select.md

**What**: Closes #3780 
When running the tests in `Select.test.tsx` we get an error message saying children element doesn't have `sendRef` and `isSelected` in its props.
I tracked what tests cause this error message which led me to this particular test:
https://github.com/patternfly/patternfly-react/blob/692ea8492d70c7d231535f4663c565f1519da6cf/packages/patternfly-4/react-core/src/components/Select/__tests__/Select.test.tsx#L125-L130
After reading the `Select.tsx` code, I noticed that `isGrouped` is not passed to `SelectMenu` when variant is `single` -- which I fixed.
In addition, I had to add a case when `isGrouped` is true when displaying the selected value in the select box because the selected option is a grand child of the Select component.
Unfortunately, this change causes the DOM …

fix(select): fix group select options in single variant

---

packages/react-core/src/components/Alert/Alert.tsx
packages/react-core/src/components/Alert/AlertActionCloseButton.tsx
packages/react-core/src/components/Alert/AlertActionLink.tsx
packages/react-core/src/components/Alert/__tests__/Alert.test.tsx
packages/react-core/src/components/Alert/__tests__/Generated/__snapshots__/AlertActionCloseButton.test.tsx.snap
packages/react-core/src/components/Alert/__tests__/__snapshots__/Alert.test.tsx.snap
packages/react-core/src/components/Alert/examples/Alert.md
packages/react-core/src/components/AlertGroup/__tests__/__snapshots__/AlertGroup.test.tsx.snap
packages/react-core/src/components/AlertGroup/examples/AlertGroup.md

**What**: This PR fixes the `React does not recognize the "variantLabel" prop on a DOM element.` bug in Alert.
Closes https://github.com/patternfly/patternfly-react/issues/3730
**Additional issues**: https://github.com/patternfly/patternfly-react/issues/2847

fix(alert): fix console error

---

packages/react-core/src/components/EmptyState/EmptyState.tsx
packages/react-core/src/components/EmptyState/__tests__/EmptyState.test.tsx
packages/react-core/src/components/EmptyState/__tests__/Generated/__snapshots__/EmptyState.test.tsx.snap
packages/react-core/src/components/EmptyState/__tests__/__snapshots__/EmptyState.test.tsx.snap
packages/react-core/src/components/EmptyState/examples/EmptyState.md
packages/react-integration/demo-app-ts/src/components/demos/EmptyStateDemo/EmptyStateDemo.tsx
packages/react-integration/demo-app-ts/src/components/demos/TableDemo/TableEmptyStateDemo.tsx

Change the default width to full instead of large.  updated the variant name to be more consistent with other components.  Note: The variant `full` was not changed to allow for flexibility of other sizes being added that are larger than `xl`.
**What**: Closes #3221 #3873 
1. Changes the default width to `full` instead of `large`.  To maintain the previous default behaviour, set the `variant` prop to large. e.g `<EmptyState variant={EmptyStateVariant.large}> ...</EmptyState>` 
2. Variant `small` has been updated to `sm`
3. Variant `large` has been updated to `lg`

Empty state width

---

packages/react-core/src/components/Card/CardHeadMain.test.tsx
packages/react-core/src/components/Card/CardHeadMain.tsx
packages/react-core/src/components/Card/__snapshots__/CardHeadMain.test.tsx.snap
packages/react-core/src/components/Card/examples/Card.md
packages/react-core/src/components/Card/index.ts

fix(card): add wrapper to image to resize it properly

---

packages/react-integration/demo-app-ts/src/components/demos/TableDemo/TableActionsDemo.tsx
packages/react-integration/demo-app-ts/src/components/demos/TableDemo/TableSelectableDemo.tsx
packages/react-integration/demo-app-ts/src/components/demos/TableDemo/TableSimpleActionsDemo.tsx
packages/react-integration/demo-app-ts/src/components/demos/TableDemo/TableSimpleDemo.tsx
packages/react-integration/demo-app-ts/src/components/demos/TableDemo/TableSortableForCompoundExpandableDemo.tsx
packages/react-table/src/components/Table/SelectColumn.tsx
packages/react-table/src/components/Table/Table.md
packages/react-table/src/components/Table/Table.test.tsx
packages/react-table/src/components/Table/Table.tsx
packages/react-table/src/components/Table/utils/decorators/selectable.tsx
packages/react-table/src/components/Table/utils/headerUtils.tsx

**What**: This PR aligns the onSelect event type from
`React.MouseEvent` & `React.ChangeEvent<HTMLInputElement>`
to
`React.FormEvent<HTMLInputElement>`
The `target` property of the event object is what the user actually clicked on, and it can vary as the underlying implementation changes in structure. The `currentTarget` property is the element the event was bound to, and will never change.
By using FormEvent, we now correctly get assistance from the IDE. 
Before:
After:
This PR also clears all noImplicitAny errors for Table in react-integration and simplifies the Selectable Table example in the docs.
**Additional issues**: https://github.com/patternfly/patternfly-react/issues/3279 https://github.com/patternfly/patternfly-react/issues/2673 …

chore(table): update types in table

---

packages/react-core/src/components/Alert/Alert.tsx
packages/react-core/src/components/Alert/__tests__/Alert.test.tsx
packages/react-core/src/components/AlertGroup/__tests__/__snapshots__/AlertGroup.test.tsx.snap
packages/react-integration/demo-app-ts/src/components/demos/AlertDemo/AlertDemo.tsx

**What**: Closes #2646
@tlabaj `default` cannot be removed from the `variant` property union because it is now set to be the default value. Should the `variant` property accept a string instead of the specific "default" string, or should it remain accepting "default"?
1. Changes the default of the `variant` property to `default` instead of `info`. To maintain current default behavior, set the `variant` property to `info`.

feat(Alert): change default alert variant to default

---

packages/react-core/src/components/Page/Page.tsx

**What**: Closes #2597
1. Makes `mainContainerId` a required property.

feat(Page): make mainContainerId required

---

packages/react-core/src/helpers/componentShape.js
packages/react-docs/src/pages/index.js
packages/react-integration/demo-app-ts/src/components/AppSidebar/AppSidebar.tsx
scripts/generators/patternfly-4-component/templates/component/component.tsx.hbs

**What**: Towards #3836 . Biggest need is to remove `componentShape`, rest is just small cleanup.

chore(prop-types): remove a few usages

---

packages/react-core/package.json
packages/react-core/src/components/AboutModal/AboutModalContainer.tsx
packages/react-core/src/components/AboutModal/__tests__/AboutModalBoxCloseButton.test.tsx
packages/react-core/src/components/AboutModal/__tests__/__snapshots__/AboutModalContainer.test.tsx.snap
packages/react-core/src/components/Alert/__tests__/Alert.test.tsx
packages/react-core/src/components/ContextSelector/ContextSelector.tsx
packages/react-core/src/components/ContextSelector/__tests__/__snapshots__/ContextSelector.test.tsx.snap
packages/react-core/src/components/Drawer/__tests__/Drawer.test.tsx
packages/react-core/src/components/Dropdown/__tests__/Dropdown.test.tsx
packages/react-core/src/components/FileUpload/__tests__/FileUpload.test.tsx
packages/react-core/src/components/FileUpload/__tests__/FileUploadField.test.tsx
packages/react-core/src/components/Modal/ModalContent.tsx
packages/react-core/src/components/Modal/__tests__/__snapshots__/ModalContent.test.tsx.snap
packages/react-core/src/components/Popover/Popover.tsx
packages/react-core/src/components/Select/SelectMenu.tsx
packages/react-core/src/components/Select/__tests__/__snapshots__/Select.test.tsx.snap
packages/react-core/src/components/Wizard/Wizard.tsx
packages/react-core/src/components/Wizard/__tests__/__snapshots__/Wizard.test.tsx.snap
packages/react-core/src/helpers/FocusTrap/FocusTrap.tsx
packages/react-core/src/helpers/index.ts
packages/react-inline-edit-extension/package.json
packages/react-table/package.json
packages/react-virtualized-extension/package.json
scripts/verifyPatternflyVersions.js
yarn.lock

**What**: Towards #3836 .
Remove leftover requirements of `exenv`.
In-house [`focus-trap-react`](https://github.com/davidtheclark/focus-trap-react/blob/master/src/focus-trap-react.js) which is just a single component with incorrect types. I corrected the types and tweaked the implementation slightly to improve readability (the spread operator is readable!) and fix types easier.
Run prettier on a lot of files that haven't had it run because they aren't included by `eslint`.

chore(deps): in-house focusTrap

---

packages/react-charts/package.json
packages/react-charts/src/components/Chart/Chart.tsx
packages/react-charts/src/components/ChartArea/ChartArea.tsx
packages/react-charts/src/components/ChartAxis/ChartAxis.tsx
packages/react-charts/src/components/ChartBar/ChartBar.tsx
packages/react-charts/src/components/ChartBullet/ChartBulletComparativeMeasure.tsx
packages/react-charts/src/components/ChartBullet/ChartBulletPrimarySegmentedMeasure.tsx
packages/react-charts/src/components/ChartBullet/ChartBulletQualitativeRange.tsx
packages/react-charts/src/components/ChartGroup/ChartGroup.tsx
packages/react-charts/src/components/ChartLegend/ChartLegend.tsx
packages/react-charts/src/components/ChartLine/ChartLine.tsx
packages/react-charts/src/components/ChartPie/ChartPie.tsx
packages/react-charts/src/components/ChartScatter/ChartScatter.tsx
packages/react-charts/src/components/ChartStack/ChartStack.tsx
yarn.lock

As part of the v4 breaking change release, we should bump the victory and victory-core packages to 34.1.3. The @types/victory package should also be bumped to 33.1.4.
https://github.com/patternfly/patternfly-react/issues/3973

Bump Victory packages

---

packages/react-core/src/components/Modal/Modal.tsx
packages/react-core/src/components/Modal/ModalBox.tsx
packages/react-core/src/components/Modal/ModalContent.tsx
packages/react-core/src/components/Modal/__tests__/Generated/__snapshots__/Modal.test.tsx.snap
packages/react-core/src/components/Modal/__tests__/Generated/__snapshots__/ModalBox.test.tsx.snap
packages/react-core/src/components/Modal/__tests__/__snapshots__/ModalBox.test.tsx.snap
packages/react-core/src/components/Modal/__tests__/__snapshots__/ModalContent.test.tsx.snap
packages/react-core/src/components/Modal/examples/Modal.md
packages/react-integration/demo-app-ts/src/components/demos/ModalDemo/ModalDemo.tsx

**What**: Closes #3900
1. Collapses the `isLarge` and `isSmall` properties into a single `variant` property. To maintain the current behavior, set the `variant` property to `large` or `small`, or use the newly added `ModalVariant` enum as `ModalVariant.large` or `ModalVariant.small`.

Breaking modal variant

---

packages/react-core/src/components/Select/Select.tsx
packages/react-core/src/components/Select/__tests__/Select.test.tsx
packages/react-core/src/components/Select/__tests__/__snapshots__/Select.test.tsx.snap
packages/react-core/src/components/Select/examples/Select.md
packages/react-integration/cypress/integration/select.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectDemo.tsx

**What**: 
Closes #3705 
Adds a property `hideCheckboxSelectionBadge` to the select component which will prevent the selection count badge from being shown if passed as `true`.

feat(select): Allow count badge to be hidden in checkbox select

---

packages/react-core/src/components/Tooltip/examples/Tooltip.md

**What**: Closes #3961
Simple update to tooltip examples to allow them to be keyboard accessible.

Make tooltip examples keyboard accessible

---

packages/react-core/src/components/Drawer/DrawerPanelContent.tsx
packages/react-integration/cypress/integration/drawer.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/DrawerDemo/DrawerDemo.tsx

**What**: Closes #3888
**Additional issues**: Follow-up work from #3884 
This PR adds functionality for setting panel width with new props on `DrawerPanelContent`, and updates the corresponding demo & tests.

Feat/Drawer - add width props, update demo & cypress tests

---

packages/react-table/src/components/Table/Table.md

**What**: Adds a missing `p` to the title of the "Compound expandable" example of the Table documentation, which also affects the anchor on the site (I think).

Fix compound expandable table example spelling

---

packages/react-catalog-view-extension/package.json
packages/react-charts/package.json
packages/react-core/package.json
packages/react-docs/RELEASE-NOTES.md
packages/react-docs/package.json
packages/react-icons/package.json
packages/react-inline-edit-extension/package.json
packages/react-styles/package.json
packages/react-table/package.json
packages/react-tokens/package.json
packages/react-topology/package.json
packages/react-virtualized-extension/package.json
yarn.lock

For release. Depends on https://github.com/patternfly/patternfly/pull/2900 first.
Also updates release notes.

chore(packages): bump @patternfly/patternfly to 2.71.0

---

packages/react-core/src/components/ApplicationLauncher/ApplicationLauncherItem.tsx
packages/react-core/src/components/ApplicationLauncher/__tests__/__snapshots__/ApplicationLauncher.test.tsx.snap
packages/react-core/src/components/ApplicationLauncher/examples/ApplicationLauncher.md
packages/react-core/src/components/Dropdown/DropdownItem.tsx
packages/react-core/src/components/Dropdown/InternalDropdownItem.tsx
packages/react-core/src/components/Dropdown/__tests__/__snapshots__/Dropdown.test.tsx.snap
packages/react-core/src/components/Dropdown/examples/Dropdown.md
packages/react-core/src/components/OptionsMenu/__tests__/__snapshots__/OptionsMenu.test.tsx.snap

**What**: Fixes broken application launcher styles on master by choosing to support this API:
```tsx
component={<Link to="/components/alert/">Alert</Link>}
OR
component="button"
```
rather than
```tsx
<DropdownItem component="some-custom-string-that-says-just-to-render-children">
<Link to="/components/alert/">Alert</Link>
</DropdownItem>
OR
component={<Link to="/components/alert/">Alert</Link>}
OR
component="button"
```
Changes to InternalDropdownItem (affects Dropdown, OptionsMenu, and ApplicationLauncher):
- If component is a valid element, clone it rather than `children`
- Pass `href` and `id` to cloned element

fix(app-launcher): less aggressive router linking

---

packages/react-catalog-view-extension/package.json
packages/react-charts/package.json
packages/react-core/package.json
packages/react-core/src/components/ApplicationLauncher/examples/ApplicationLauncher.md
packages/react-docs/RELEASE-NOTES.md
packages/react-docs/package.json
packages/react-icons/package.json
packages/react-inline-edit-extension/package.json
packages/react-styles/package.json
packages/react-table/package.json
packages/react-tokens/package.json
packages/react-topology/package.json
packages/react-virtualized-extension/package.json
yarn.lock

**What**: For updating Core's release notes in patternfly-org

bump core to 2.71.3 in react-docs

---

packages/react-core/src/components/Modal/Modal.tsx
packages/react-core/src/components/Modal/ModalBoxFooter.tsx
packages/react-core/src/components/Modal/ModalContent.tsx
packages/react-core/src/components/Modal/__tests__/Generated/Modal.test.tsx
packages/react-core/src/components/Modal/__tests__/Generated/ModalContent.test.tsx
packages/react-core/src/components/Modal/__tests__/Generated/__snapshots__/Modal.test.tsx.snap
packages/react-core/src/components/Modal/__tests__/Generated/__snapshots__/ModalBoxFooter.test.tsx.snap
packages/react-core/src/components/Modal/__tests__/__snapshots__/ModalBoxFooter.test.tsx.snap
packages/react-core/src/components/Modal/__tests__/__snapshots__/ModalContent.test.tsx.snap
packages/react-core/src/components/Modal/examples/Modal.md
packages/react-integration/demo-app-ts/src/components/demos/ModalDemo/ModalDemo.tsx

**What**: Closes https://github.com/patternfly/patternfly-react/issues/3672
1. **Modal**: Removes prop `isFooterLeftAligned `. This prop is no longer used.
2. **Modal**: Layout change where modal footer actions are left-aligned by default.
3. **ModalBoxFooter**: Removes prop `isLeftAligned`. This prop is no longer used.
As part of this work, I've introduced the prop `isFooterRightAligned`/`isRightAligned` for those who are _not able_ to go with the new design recommendation and would like to use right-aligned actions instead. This PR also includes some minor followup/cleanup from the recent aria-prop alignment work.

fix(modal): default action alignment to left

---

packages/react-core/src/components/Dropdown/InternalDropdownItem.tsx

**What**: #3995 introduced a regression where the `href` or `id` props passed like this:
```tsx
<DropdownItem component={<a href="href" id="id" />} />
```
would be ignored. This PR makes it so that only `className` is overridden when cloning the `component` prop.

fix(dropdown): respect already passed props

---

.eslintrc.json
packages/react-integration/demo-app-ts/src/components/demos/TableDemo/TableSortableForCompoundExpandableDemo.tsx
packages/react-table/src/components/Table/demo/DemoSortableTable.js

**What**: Closes #4042 
**Additional issues**: Towards #3972 . It's not really our fault setting `project`: makes eslint take forever, see https://github.com/typescript-eslint/typescript-eslint/issues/1192 for resolution (Typescript 3.9 should fix this issue)

fix(eslint): update config to run in 1 minute instead of over 1 hour

---

packages/react-core/src/components/Popover/PopoverHeader.tsx
packages/react-core/src/components/Popover/__tests__/Generated/__snapshots__/PopoverHeader.test.tsx.snap
packages/react-integration/cypress/integration/popover.spec.ts

**What**: Closes https://github.com/patternfly/patternfly-react/issues/3986
This PR updates the default size of the popover header to be medium instead of extra-large.
1. **Popover**: PopoverHeader title now has a default size of medium. Extra large is no longer the default size.

fix(popover): update default popover header size

---

packages/react-core/src/components/EmptyState/EmptyState.tsx
packages/react-core/src/components/EmptyState/__tests__/EmptyState.test.tsx
packages/react-core/src/components/EmptyState/__tests__/Generated/__snapshots__/EmptyState.test.tsx.snap
packages/react-core/src/components/EmptyState/__tests__/__snapshots__/EmptyState.test.tsx.snap
packages/react-core/src/components/EmptyState/examples/EmptyState.md
packages/react-integration/cypress/integration/emptystate.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/EmptyStateDemo/EmptyStateDemo.tsx

**What**: Closes https://github.com/patternfly/patternfly-react/issues/3673
This PR adds a new prop `isFullHeight` to EmptyState component, along with corresponding tests.
**Additional issues**: https://github.com/patternfly/patternfly/issues/2568

fix(empty-state): add isFullHeight prop support

---

packages/react-core/src/components/Dropdown/DropdownToggleCheckbox.tsx

**Closes**: #3994 indeterminate state `-` in dropdown toggle checkbox was not displaying
@tlabaj I'm unsure why there was a `ref` property being passed in and set, so are there any issues with changing it to this?

fix(DropdownToggleCheckbox): fix ref to show indeterminate checkbox 

---

packages/react-table/src/components/Table/ActionsColumn.tsx
packages/react-table/src/components/Table/utils/transformers.test.tsx

**What**: Closes https://github.com/patternfly/patternfly-react/issues/4005
This PR updates the table actions dropdown to use `button` elements by default as we do in core. I noticed this was adjusted recently, would be good to verify this doesn't introduce any problems.
**Additional issues**: https://github.com/patternfly/patternfly-react/issues/3559
@SpyTec ping

(fix): Table actions cursor

---

packages/react-core/src/components/DataToolbar/DataToolbarFilter.tsx
packages/react-core/src/components/DataToolbar/__tests__/__snapshots__/DataToolbar.test.tsx.snap

**What**: Closes #3770
DataToolbar's state was getting updated by each DataToolbarFilter even when nothing was changed, so I added a check to only kick off the update when a filter's chips got updated.
Moving DataToolbar's internal `filterInfo` object out of its state, to a private variable, would be another way to resolve the bug.

fix(DataToolbar): fix filter context from updating unnecessarily

---

packages/react-core/src/components/Drawer/DrawerPanelContent.tsx
packages/react-core/src/components/Drawer/__tests__/__snapshots__/Drawer.test.tsx.snap
packages/react-core/src/components/Drawer/examples/Drawer.md

**What**: Closes #3988
Adjusts `hasBorder` to `hasNoBorder`, as the default of hasBorder was preventing any border or drop shadow from displaying. `hasNoBorder` is an opt-in to get the `.pf-m-no-border` class.

feat(Drawer): remove flag to add border, adjust flag for no border

---

packages/react-core/src/components/DataToolbar/DataToolbarFilter.tsx
packages/react-core/src/components/DataToolbar/examples/DataToolbar.md
packages/react-integration/cypress/integration/datatoolbar.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/DataToolbarDemo/DataToolbarDemo.tsx

Add optional prop: deleteChipGroup to remove all chips in a category as well as provide visual treatment for
the DataToolbarFilter.
fix #4059

fix(DataToolbarFilter): Add prop to enable removal of all chips in a filter category.

---

packages/react-core/src/components/Title/Title.tsx
packages/react-core/src/components/Title/__tests__/Generated/Title.test.tsx
packages/react-core/src/components/Title/__tests__/Generated/__snapshots__/Title.test.tsx.snap
packages/react-core/src/components/Title/examples/Title.md
packages/react-integration/cypress/integration/title.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/TitleDemo/TitleDemo.tsx

**What**: Closes https://github.com/patternfly/patternfly-react/issues/4079
This PR makes `size` optional and generates a default value for it (when not supplied by user) that corresponds to to closest likely size given the heading level. This should not only simplify Title usage, but also ease upgrade pains in some cases.
**Additional issues**: https://github.com/patternfly/patternfly-react/pull/3922

feat(title): supply defaults for title size property

---

packages/react-core/src/components/Alert/__tests__/__snapshots__/Alert.test.tsx.snap
packages/react-core/src/components/Button/Button.tsx
packages/react-core/src/components/Button/__tests__/__snapshots__/Button.test.tsx.snap
packages/react-core/src/components/DataToolbar/__tests__/__snapshots__/DataToolbar.test.tsx.snap
packages/react-core/src/components/Wizard/__tests__/__snapshots__/Wizard.test.tsx.snap

feat(Button): allow icon to be used in any variant, add icon css modifiers

---

packages/react-core/src/demos/TableEmptyStatesDemo.md
packages/react-table/src/components/Table/Table.md

fix(table): empty state can now scale on smaller screens

---

packages/react-core/src/components/Wizard/Wizard.tsx
packages/react-core/src/components/Wizard/WizardFooterInternal.tsx
packages/react-core/src/components/Wizard/WizardHeader.tsx
packages/react-core/src/components/Wizard/WizardNavItem.tsx
packages/react-core/src/components/Wizard/__tests__/Generated/__snapshots__/WizardNavItem.test.tsx.snap

**What**: Closes #2593
1.  `WizardNavItem`: Renamed prop `text` to `content`.  The type of the prop has been changed to React.ReactNode to allow for flexibility.

refactor(Wizard): Update string props to be React nodes.

---

packages/react-core/src/components/DataToolbar/DataToolbarFilter.tsx
packages/react-core/src/components/DataToolbar/__tests__/__snapshots__/DataToolbar.test.tsx.snap

Revert change that prevents the current state of the toolbar filters to display in chip groups, as well as
reflect clear all action.
fix #[4096](https://github.com/patternfly/patternfly-react/issues/4096) and maybe #[4094](https://github.com/patternfly/patternfly-react/pull/4094)

fix(Datatoolbar): Revert change that breaks chips associated with filters in toolbar

---

scripts/promote.js

**What**: Every release we have to list version numbers for our testers to test. This enables that via `node scripts/promote.js list`

feat(release): add list option to promote script

---

packages/react-core/src/components/DataToolbar/DataToolbar.tsx
packages/react-core/src/components/DataToolbar/__tests__/__snapshots__/DataToolbar.test.tsx.snap

**What**: Closes #3770
Alternate fix for 3770. Uses a private variable instead of state to decide if state should update in `updateNumberFilters`. The state is still used inside the function to get the proper re-rendering for chip updates (clear all button / chip group appearances).
What I think was happening was that the `filterInfo` state was being updated and overridden while all of the filters were being evaluated and updated, so the initial iteration of the filters wasn't getting completed properly and recursing.

fix(DataToolbar): max depth fix

---

packages/react-core/README.md

Closes #4118 
Issue:
Fix:
All three node version now match...

fix(version): mis-match in readme

---

packages/react-core/src/components/Form/FormGroup.tsx
packages/react-core/src/components/Form/__tests__/FormGroup.test.tsx
packages/react-core/src/components/Form/examples/Form.md
packages/react-integration/cypress/integration/form.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/FormDemo/FormDemo.tsx

**What**: Closes #3848 
//cc @mcoker @tlabaj

feat(form): support removing top spacer form from labels

---

ADVANCED-USAGE-README.md
README.md
packages/react-core/README.md

Closes https://github.com/patternfly/patternfly-react/issues/4020 and #4008 
Updates the Readme to the new format for react-core.  Contribution guidelines are being moved out to the common contribution guide and advanced usage concepts were promoted to a top level readme.

chore(readme): update react-core readme to new format

---

packages/react-core/src/components/Nav/Nav.tsx
packages/react-core/src/components/Nav/NavList.tsx
packages/react-core/src/components/Nav/__tests__/Generated/__snapshots__/Nav.test.tsx.snap
packages/react-core/src/components/Nav/__tests__/Generated/__snapshots__/NavList.test.tsx.snap
packages/react-core/src/components/Nav/__tests__/__snapshots__/Nav.test.tsx.snap
packages/react-core/src/components/Nav/examples/Nav.md
packages/react-core/src/components/Page/PageSection.tsx
packages/react-core/src/helpers/util.ts

**What**: Fix the scrolling buttons for the horizontal and tertiary navigation variants.
Closes #3200
Closes #4054 
**Additional issues**: The scrollable tertiary nav must now be in a PageSection, but @mcoker is working upstream so that it can work outside of one. Once that work is complete the following breaking change note can be removed.
-  **Nav**: The tertiary variant of NavList must now be inside a `<PageSection type="nav">` to scroll properly.

fix(nav): fix scrolling

---

packages/react-core/src/components/Wizard/Wizard.tsx
packages/react-core/src/components/Wizard/WizardBody.tsx
packages/react-core/src/components/Wizard/WizardToggle.tsx
packages/react-core/src/components/Wizard/__tests__/Generated/__snapshots__/WizardToggle.test.tsx.snap
packages/react-core/src/components/Wizard/__tests__/__snapshots__/Wizard.test.tsx.snap

**What**: Closes #4052 -- moves padding to wizard body.
**Additional issues**: #4039, renamed prop to remain consistent with @kmcfaul's `hasNoPadding` changes in #4133.

feat(Wizard): update hasBodyPadding

---

packages/react-docs/src/training.md

Closes #4139 
fixed the Training page with the new "hasGutter" prop.

fix(css): change gutter="x" to hasGutter

---

packages/react-catalog-view-extension/package.json
packages/react-charts/package.json
packages/react-core/package.json
packages/react-icons/package.json
packages/react-inline-edit-extension/package.json
packages/react-integration/package.json
packages/react-table/package.json
packages/react-topology/package.json
packages/react-virtualized-extension/package.json
scripts/generators/package/package.json.hbs

**What**: Upgrade our peer dependency from `react@^16.4.0` (2 years old) to `react@^16.8.0` (1 year old) as a part of our breaking changes. This change would allow our library code to use React hooks moving forward. Previous discussion is in the #patternfly-react channel on Slack.
Closes patternfly/patternfly-org#1712
**Additional issues**: There are some concerns with products having to upgrade React, which in turn would break other 3rd party dependencies like Redux. These products are on a timeline where upgrading is feasible in the future, and the price to pay of not upgrading to `@patternfly/react-core@^4.0.0` is only that our components with hooks will not work (which currently, there are none).
- Our packages now can possibly use hooks, which requires `react@^16.8.0` instead of …

chore(packages): bump react peer dep to 16.8.0

---

packages/react-integration/demo-app-ts/tsconfig.json

**What**:
Closes #3223 
Closes #3230 
This PR enables `strictNullChecks` and `strictPropertyInitialization`.
These were the only sub-rules of `strict` mode that were disabled, so this also cleans up `tsconfig` by removing unnecessary sub-rules in favor of simply `strict: true`:
```
noImplicitAny
noImplicitThis
alwaysStrict
strictBindCallApply
strictNullChecks
strictFunctionTypes
strictPropertyInitialization
```
Follow-up to work done in #4019 
Enabled by updates to `react-charts` in #4138

strict mode enabled, removed duplicate sub-rules from tsconfig

---

packages/react-icons/package.json
packages/react-styles/package.json
packages/react-tokens/package.json

**What**: #4158 did work, but it didn't remove the existing `index.ts` because of a stale `dist` folder. This forces ALL generated folders to be removed before new files are written to avoid stale `dist` folders in the future.

fix(icons): clean old generated files before regenerating

---

packages/react-core/src/components/Wizard/Wizard.tsx
packages/react-core/src/components/Wizard/__tests__/Generated/Wizard.test.tsx
packages/react-core/src/components/Wizard/examples/Wizard.md

**What**: Closes https://github.com/patternfly/patternfly-react/issues/3686
1. **WizardNav**: Removes prop `isCompactNav `. This prop is no longer used.
**Additional issues**: https://github.com/patternfly/patternfly/pull/2936

fix(wizard): remove old prop "isCompactNav"

---

packages/react-core/src/components/Toolbar/Toolbar.tsx
packages/react-core/src/components/Toolbar/ToolbarContent.tsx
packages/react-core/src/components/Toolbar/ToolbarUtils.tsx
packages/react-core/src/components/Toolbar/__tests__/Generated/__snapshots__/Toolbar.test.tsx.snap
packages/react-core/src/components/Toolbar/__tests__/Generated/__snapshots__/ToolbarContent.test.tsx.snap
packages/react-core/src/components/Toolbar/examples/Toolbar.md
packages/react-topology/src/components/TopologyControlBar/__snapshots__/TopologyControlBar.test.tsx.snap
packages/react-topology/src/components/TopologyView/__snapshots__/TopologyView.test.tsx.snap

**What**: Rename `DataToolbar.md` -> `Toolbar.md`. Allow passing components other than `<ToolbarContent>` to `<Toolbar>` by adding toolbar props to `<ToolbarContext>`. 
Closes https://github.com/patternfly/patternfly-org/issues/1830
Closes #3671
Closes #4149

fix(datatoolbar): finish rename in docs and fix context

---

packages/react-core/src/components/index.ts
packages/react-core/src/experimental/components/DataToolbar/index.ts
packages/react-core/src/experimental/components/Drawer/index.ts
packages/react-core/src/experimental/components/index.ts
packages/react-core/src/experimental/index.ts
packages/react-core/src/index.ts

**What**: Closes https://github.com/patternfly/patternfly-react/issues/4167
This PR removes the experimental directory and moves those exports to react-core pkg.
1. **Drawer**: Removes import path `'@patternfly/react-core/dist/js/experimental'`. The import path `'@patternfly/react-core'` should be used instead.

fix(experimental): remove experimental directory

---

.eslintrc.json
packages/eslint-plugin-patternfly-react/CHANGELOG.md
packages/eslint-plugin-patternfly-react/README.md
packages/eslint-plugin-patternfly-react/lib/config/recommended.js
packages/eslint-plugin-patternfly-react/lib/index.js
packages/eslint-plugin-patternfly-react/lib/rules/import-default-name.js
packages/eslint-plugin-patternfly-react/lib/rules/import-tokens-icons.js
packages/eslint-plugin-patternfly-react/package.json
yarn.lock

**What**: Closes #4184
**Additional issues**: When importing from the token or icon ESM index files, CJS bundles will include the entirety of react-tokens or react-icons. This rule prevents that.

chore(lint): add import-tokens-icons rule

---

packages/react-core/src/components/Divider/Divider.md
packages/react-core/src/components/Divider/Divider.tsx
packages/react-core/src/components/Divider/__tests__/Divider.test.tsx
packages/react-core/src/components/Divider/__tests__/__snapshots__/Divider.test.tsx.snap
packages/react-core/src/components/Toolbar/ToolbarItem.tsx
packages/react-core/src/components/Toolbar/examples/Toolbar.md
packages/react-integration/cypress/integration/divider.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/DividerDemo/DividerDemo.tsx

**What**: Closes #3736 and #3679
I imagine we would want to introduce as few breaking changes as possible. And just change the implementations of any components with their own separators so they render a Divider. Much of that work has already been done.
So I don't plan to make more breaking changes unless we'd prefer I remove the whole DropdownSeparator component and other component specific separators (even if they all ultimately use the Divider component). This would require consumers to replace all instances with a Divider component.

chore(Divider): add vertical dividers and use Divider in DataToolbar

---

packages/react-core/src/components/NotificationDrawer/NotificationDrawerGroup.tsx
packages/react-core/src/components/NotificationDrawer/__tests__/Generated/__snapshots__/NotificationDrawerGroup.test.tsx.snap
packages/react-core/src/components/NotificationDrawer/__tests__/__snapshots__/NotificationDrawerGroup.test.tsx.snap
packages/react-core/src/components/Tabs/Tabs.tsx

**What**: Closes #4074 . Fixes lint issue in NotificationDrawerGroup.tsx.
**Additional issues**: Verified this in cost management thanks to @dlabrecq !

fix(tabs): properly check children before setting hidden

---

.circleci/config.yml

**What**: Fixed failing builds since #4190 was merged 2 hours ago: https://circleci.com/gh/patternfly/patternfly-react/34192 https://circleci.com/gh/patternfly/patternfly-react/34126 .
Require lint to pass before publishing to be extra safe in preventing accidental major version bumps in the future.

fix(build): lint for breaking changes off v4

---

packages/react-charts/src/components/ChartDonut/ChartDonut.tsx
packages/react-charts/src/components/ChartDonutUtilization/ChartDonutUtilization.tsx
packages/react-charts/src/components/ChartUtils/chart-origin.ts

Adding documentation to describe how to override `title` and `subTitle` styles via `titleComponent`. Also ensured that the `subTitleComponent` prop of `ChartDonut` is not ignored when `title` and `subTitle` are both used.
https://github.com/patternfly/patternfly-react/issues/4172

ChartDonut subTitleComponent is ignored in some cases

---

packages/react-core/src/components/DataList/DataListContent.tsx
packages/react-core/src/components/DataList/__tests__/DataList.test.tsx
packages/react-core/src/components/DataList/__tests__/Generated/DataListContent.test.tsx
packages/react-core/src/components/DataList/__tests__/__snapshots__/DataList.test.tsx.snap
packages/react-core/src/components/DataList/examples/DataList.md
packages/react-core/src/components/Drawer/DrawerHead.tsx
packages/react-core/src/components/Drawer/DrawerPanelBody.tsx
packages/react-core/src/components/Drawer/__tests__/Generated/DrawerPanelContent.test.tsx
packages/react-core/src/components/Drawer/__tests__/__snapshots__/Drawer.test.tsx.snap
packages/react-core/src/components/Drawer/examples/Drawer.md
packages/react-core/src/components/Page/PageSection.tsx
packages/react-core/src/components/Page/__tests__/Generated/PageSection.test.tsx
packages/react-core/src/components/Page/__tests__/PageSection.test.tsx
packages/react-core/src/components/Page/__tests__/__snapshots__/PageSection.test.tsx.snap
packages/react-core/src/components/Page/examples/Page.md
packages/react-core/src/helpers/util.ts
packages/react-integration/cypress/integration/page.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/PageDemo/PageDemo.tsx

And add Page padding breakpoint logic
**What**: Closes #4013, #4039, #4040
1. Renamed `noPadding` to `hasNoPadding` for Drawer, DataList and Page components.
2. Added `hasPaddingOn` and `hasNoPaddingOn` properties to PageSection, accounting for page size breakpoints. Breakpoints are defined in the `PageSectionBreakpoints` enum.

feat(Drawer, DataList, Page): rename noPadding to hasNoPadding

---

packages/react-core/src/components/Label/Label.tsx
packages/react-core/src/components/Label/__tests__/Generated/__snapshots__/Label.test.tsx.snap
packages/react-core/src/components/Label/__tests__/Label.test.tsx
packages/react-core/src/components/Label/__tests__/__snapshots__/Label.test.tsx.snap
packages/react-core/src/components/Label/examples/Label.md
packages/react-integration/cypress/integration/label.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/LabelDemo/LabelDemo.tsx

**What**: Closes #3688
The `onClose` prop, if present, will add the close button to the label, and the `href` prop, if present, will change the <span> to an <a> element.
1. Default color changed to grey. Design also adjusted.

feat(Label): refactor for updated design and features

---

.circleci/config.yml
packages/react-core/src/components/Select/Select.tsx
packages/react-core/src/components/Select/__tests__/Generated/__snapshots__/Select.test.tsx.snap
packages/react-core/src/components/Select/__tests__/Select.test.tsx
packages/react-core/src/components/Select/__tests__/__snapshots__/Select.test.tsx.snap
packages/react-core/src/components/Select/examples/Select.md
packages/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectDemo.tsx

**What**: Closes #4151, followup to #3945
Also properly fix the CI linter for PRs and update the examples to use `isOpen` rather than `isExpanded`

fix(select): revert to single "selections" prop

---

packages/react-core/src/components/EmptyState/EmptyStateIcon.tsx

**What**: Closes #4166
Color was marked deprecated and removed (#4065) but it is a prop that is in use.  This PR reverts that change.

fix(EmptyStateIcon): Add back color prop

---

packages/react-core/src/components/DataList/DataList.tsx
packages/react-core/src/components/Drawer/DrawerPanelContent.tsx
packages/react-core/src/components/FileUpload/FileUpload.tsx
packages/react-core/src/components/FileUpload/FileUploadField.tsx
packages/react-core/src/components/FormSelect/FormSelect.tsx
packages/react-core/src/components/TextInput/TextInput.tsx

Closes #4215 
Should be using  "/**" starting tag apposed to the "/*" tag.

chore(cleanup): prop comments using wrong notation

---

packages/react-catalog-view-extension/package.json
packages/react-charts/package.json
packages/react-core/package.json
packages/react-docs/package.json
packages/react-icons/package.json
packages/react-inline-edit-extension/package.json
packages/react-styles/package.json
packages/react-table/package.json
packages/react-tokens/package.json
packages/react-topology/package.json
packages/react-virtualized-extension/package.json
yarn.lock

**What**: Version bump only for 2020.06 master release. Core has no changes for this release.

chore(packages): bump core to 2.71.6

---

packages/react-core/src/components/Tabs/Tab.tsx
packages/react-core/src/components/Tabs/TabButton.tsx
packages/react-core/src/components/Tabs/TabTitleIcon.tsx
packages/react-core/src/components/Tabs/TabTitleText.tsx
packages/react-core/src/components/Tabs/Tabs.tsx
packages/react-core/src/components/Tabs/__tests__/Generated/__snapshots__/Tabs.test.tsx.snap
packages/react-core/src/components/Tabs/__tests__/Tab.test.tsx
packages/react-core/src/components/Tabs/__tests__/TabButton.test.tsx
packages/react-core/src/components/Tabs/__tests__/Tabs.test.tsx
packages/react-core/src/components/Tabs/__tests__/__snapshots__/TabButton.test.tsx.snap
packages/react-core/src/components/Tabs/__tests__/__snapshots__/Tabs.test.tsx.snap
packages/react-core/src/components/Tabs/examples/Tabs.md
packages/react-core/src/components/Tabs/index.ts
packages/react-core/src/helpers/util.ts
packages/react-integration/cypress/integration/tabdemo.spec.ts
packages/react-integration/cypress/integration/tabinsetdemo.spec.ts
packages/react-integration/demo-app-ts/src/Demos.ts
packages/react-integration/demo-app-ts/src/components/demos/TabsDemo/TabsDemo.tsx
packages/react-integration/demo-app-ts/src/components/demos/TabsDemo/TabsInsetDemo.tsx
packages/react-integration/demo-app-ts/src/components/demos/TabsDemo/TabsStringEventKeyDemo.tsx
packages/react-integration/demo-app-ts/src/components/demos/index.ts

**What**: Closes #3951
**Tabs**:
1. Changed prop `variant` for consistency.  You will need to update all instances of `variant` prop to `component` 
2. Changed `TabVariant` enum Name to `TabComponent` for consistent naming.  You will now need to update all instances of `tabVariant` to `TabComponent`. 
**Tab**: 
1. The title should be wrapped with `<TabTitleText>` for proper styling.  If you would like to place an Icon in the Tab, it should be wrapped with `<TabTitleIcon>` for proper styling.

Tabs updates

---

packages/react-docs/package.json
yarn.lock

Closes: #4197 
With the updates in gatsby-transformer-react-docgen-typescript we are now seeing properties

updated gatsby-transformer-react-docgen-typescript version

---

packages/react-core/src/components/Form/FormGroup.tsx
packages/react-core/src/components/Form/FormHelperText.tsx
packages/react-core/src/components/Form/__tests__/FormHelperText.test.tsx
packages/react-core/src/components/Form/__tests__/Generated/__snapshots__/FormGroup.test.tsx.snap
packages/react-core/src/components/Form/__tests__/__snapshots__/FormGroup.test.tsx.snap
packages/react-core/src/components/Form/__tests__/__snapshots__/FormHelperText.test.tsx.snap
packages/react-core/src/components/Form/examples/Form.md
packages/react-core/src/components/LoginPage/LoginForm.tsx
packages/react-core/src/components/LoginPage/__tests__/Generated/__snapshots__/LoginForm.test.tsx.snap
packages/react-core/src/components/LoginPage/__tests__/__snapshots__/LoginForm.test.tsx.snap
packages/react-core/src/components/LoginPage/examples/LoginPage.md
packages/react-integration/demo-app-ts/src/components/demos/FormDemo/FormDemo.tsx

and added icon props to login and formgroup
**What**: Closes #4070
Note:
Allows icon via FormHelperText component or via additional props in FormGroup and LoginForm, which wrap FormHelperText internally. For FormGroup, helper text with icons can be implemented by passing FormHelperText components, or using the current helperText props combined with the new helperTextIcon props.
1. **LoginForm**: added `helperTextIcon` property. The example's helper text was updated to use this new property. 
2. **FormHelperText**: added `icon` property.
3. **FormGroup**: added `helperTextIcon` and `helperTextInvalidIcon` properties. `FormHelperText` components may now be passed into the `helperText` and `helperTextInvalid` properties directly.

feat(Form): added icon to form helper text

---

packages/react-core/src/demos/CardView/examples/CardView.md
yarn.lock

**What**: Closes https://github.com/patternfly/patternfly-react/issues/4253

update card demo header tools

---

.circleci/upload-preview.js
packages/react-virtualized-extension/package.json
packages/react-virtualized-extension/src/components/Virtualized/VirtualGrid.ts
packages/react-virtualized-extension/src/components/Virtualized/VirtualTableBody.tsx
packages/react-virtualized-extension/src/components/Virtualized/VirtualizedTable.md
packages/react-virtualized-extension/src/components/Virtualized/VirtualizedTable.test.tsx
packages/react-virtualized-extension/src/components/Virtualized/WindowScroller.md
yarn.lock

**What**: Closes #4261 and also cleans up a lot of code since my internet went out.
- Makes `VirtualGrid` and `VirtualTableBody`'s props that already have defaults optional
- Make `VirtualTableBodyProps` correctly extend `VirtualGridProps` since it does `<VirtualGrid {...this.props}`
- Remove `clsx`, `lodash`, `uuid`, `dom-helpers`, and `react-lifecycles-compat` since these all add to bundle size and have readily available alternatives
- clsx -> css from @patternfly/react-styles
- lodash's debounce -> debounce from @patternfly/react-core
- dom-helpers -> copy single `scrollbar` function (and it works properly now for the `actions` example!)
- uuid -> use string template + for loop's index
- react-lifecycles-compat -> add when react@17 comes out and also update the rest of our component …

fix(virtualized-props): fix required and extended props

---

packages/react-table/src/components/Table/CollapseColumn.tsx

**What**: Closes #4168
changed `<span>` to `<div>`

(Fix): Table expanded toggle icon

---

packages/patternfly-react/src/components/Cards/UtilizationTrendCard/UtilizationCard.js
packages/patternfly-react/src/components/Cards/UtilizationTrendCard/index.js
packages/patternfly-react/src/components/Notification/NotificationDrawer/NotificationDrawer.js
packages/patternfly-react/src/components/Notification/NotificationDrawer/index.js

**What**: `"sideEffects": false,` declared in `patternfly-react/package.json` was not always true because of side effects in our `index.js` files. This moves the 2 such declarations in `index.js` files to their respective component files.
**Additional issues**: This PR is in favor of #4267 . I believe it solves Zuul's issues:

fix(patternfly-react): remove side effects

---

packages/react-charts/src/components/ChartLegend/examples/ChartLegend.md

A couple teams recently asked about creating custom legends. It would be helpful to add the following to our legend examples for future reference.
1. Show how to add links in a custom legend
2. Show a legend with custom label layout and styles
Fixes https://github.com/patternfly/patternfly-react/issues/4272

chore(chart): add custom legend examples

---

packages/react-core/src/components/Drawer/DrawerPanelContent.tsx
packages/react-core/src/components/Drawer/examples/Drawer.md
packages/react-core/src/helpers/util.ts
packages/react-integration/demo-app-ts/src/components/demos/DrawerDemo/DrawerDemo.tsx

**What**: Closes #4238 
//cc @redallen

feat(drawer): use the breakpoint mods prop instead of width props

---

packages/react-core/src/components/Nav/NavExpandable.tsx
packages/react-core/src/components/Nav/__tests__/__snapshots__/Nav.test.tsx.snap
packages/react-integration/cypress/integration/nav.spec.ts

**What**: Fixes Slack reported issue. Clicking on the icon should expand the nav like in v3.

fix(nav): fix expanding on new span icon

---

packages/react-charts/src/components/Chart/Chart.tsx
packages/react-charts/src/components/ChartBar/examples/ChartBar.md
packages/react-charts/src/components/ChartGroup/ChartGroup.tsx
packages/react-integration/demo-app-ts/src/components/demos/BarChartDemo/ColorBarZoomDemo.tsx

This change uses the `VictoryZoomContainer` instead of our `allowZoom` prop. 
Ultimately, this will allow us to to combine Victory container features. For example, if a user wants both a cursor and zoom feature, they must combine containers using Victory's `createContainer` function.
Fixes https://github.com/patternfly/patternfly-react/issues/4277
Use `containerComponent` instead of `allowZoom`, for example:
```
import { VictoryZoomContainer } from 'victory-zoom-container';
<Chart containerComponent={<VictoryZoomContainer />} />
```

fix(charts): Use Victory's createContainer instead of allowZoom prop

---

packages/react-table/src/components/Table/EditColumn.tsx
packages/react-table/src/components/Table/EditableTextCell.tsx

**What**:
Fixes bloating build when using any react-table component. For some reason this file was forgotten when imports were changed to direct imports in react-table. When we used any component/util that used anything from Table component (for instance `sortable`) the build suddenly contained every icon and component. This PR fixes such issue, I've tried running build and publishing custom package that I later used. The build size went from 12 MB to 6 MB (might need a bit more investigation why it's still relatively that big).

fix(Table): update imports to direct imports for react table

---

packages/react-core/src/components/Wizard/Wizard.tsx
packages/react-core/src/components/Wizard/__tests__/Generated/__snapshots__/Wizard.test.tsx.snap
packages/react-integration/demo-app-ts/src/components/demos/DropdownDemo/DropdownDemo.tsx

**What**: This PR adds label and description for the case where a user is launching wizard in modal with isOpen. Currently, the modal example for Wizard throws an expected error about this.
Also, I see there's a `width` prop documented for Wizard, but setting it doesn't seem to have an impact. Seems like Wiz should just occupy the space of its container like most other things.. Should we remove the width prop?

fix(wiz): add missing label for wiz-in-modal

---

packages/react-core/src/components/Pagination/Pagination.tsx

**What**:
Similiar to https://github.com/patternfly/patternfly-react/pull/4286. I've updaed the versions of PF packages to latest v3 and saw the drop of build chunks from ~11MB to 4MB. That is awesome! I've checked the BundleAnalyzePlugin and saw additional 800KB to be pulled from `react-tokens` which felt ood. I've then searched for direct imports for this package and found out that paginations is still using the old way of importing files. Hopefully this should shave off significant part of this dependency.

fix(Pagination): Fix imports of tokens in pagination to direct imports

---

packages/react-charts/src/components/ChartDonut/ChartDonut.tsx

Resolves the unique key warning generated by the donut chart.
Fixes https://github.com/patternfly/patternfly-react/issues/4302

fix(charts): Donut chart unique key warning

---

packages/react-charts/package.json
packages/react-charts/src/components/ChartArea/examples/ChartArea.md
packages/react-charts/src/components/ChartLine/examples/ChartLine.md
packages/react-charts/src/components/ChartTooltip/ChartTooltip.tsx
packages/react-charts/src/components/ChartTooltip/__snapshots__/ChartTooltip.test.tsx.snap
packages/react-charts/src/components/ChartTooltip/examples/ChartTooltip.md
packages/react-charts/src/components/ChartUtils/chart-container.tsx
packages/react-charts/src/components/ChartUtils/chart-tooltip.ts
packages/react-charts/src/components/ChartUtils/index.ts
packages/react-docs/package.json

This adds examples showing how to use tooltips with a vertical cursor. This work is a prequel to adding custom legends to tooltips -- see #3219.
Insights Subscription Watch and Cost Management have already implemented this Victory feature, but wanted to add a couple utils to help make things easier.
For example, I've created a util to wrap Victory functionality when combining `cursor` and `voronoi` containers. This ensures that our theme will be applied to the default `ChartLabel` and `ChartTooltip` components.
Reviewed with @nlcwong.
Fixes https://github.com/patternfly/patternfly-react/issues/3151

Chart: Vertical cursor tooltip example

---

packages/react-core/src/components/OverflowMenu/OverflowMenu.tsx
packages/react-core/src/components/OverflowMenu/__tests__/OverflowMenu.test.tsx
packages/react-core/src/components/Toolbar/ToolbarToggleGroup.tsx
packages/react-core/src/components/Toolbar/__tests__/Generated/ToolbarToggleGroup.test.tsx
packages/react-core/src/components/Toolbar/__tests__/ToolbarToggleGroup.test.tsx
packages/react-core/src/components/Toolbar/examples/Toolbar.md
packages/react-core/src/demos/FilterTableDemo.md
packages/react-core/src/demos/MasterDetailDemo.md
packages/react-integration/demo-app-ts/src/Demos.ts
packages/react-integration/demo-app-ts/src/components/demos/ToolbarDemo/ToolbarDemo.tsx

**What**: Revert `show` to single required `breakpoint` prop. Add warning message when prop values are such that the component would be invisible. Closes #4341
**Additional issues**: Allow OverflowMenu to support 2xl.

fix(ToolbarToggleGroup): revert show to breakpoint

---

CONTRIBUTING.md
GETTING-STARTED.md
README.md
package.json
packages/react-charts/README.md
packages/react-core/CONTRIBUTING.md
packages/react-inline-edit-extension/package.json
packages/react-integration/README.md
packages/react-table/README.md
packages/react-table/src/components/Table/Table.md
packages/react-topology/README.md

When we moved away from the `packages/patternfly-3` and `packages/patternfly-4` directory structure, we left references to it in various README files. This PR fixes those broken links and removes patternfly-3-specific info from the contributing guide since it has its own contributing guide on the patternfly-3 branch.
We may also want to fix similar references on the patternfly-3 branch.

Fix broken links and references in README files caused by moving patternfly-3 packages to their own branch

---

packages/react-table/src/components/Table/SortColumn.tsx
packages/react-virtualized-extension/src/components/Virtualized/__snapshots__/VirtualizedTable.test.tsx.snap

Buttons without specified type attribute are treated as 'submit' buttons by browsers. This causes issues when a table with sortable columns is used inside a form as the form is submitted by clicking the sort buttons.
This change sets the button type to 'button' which establishes correct behaviour.
**What**: Closes #4251

fix(table): Specify button type to avoid unwanted form submits

---

packages/react-core/src/components/Modal/ModalBoxTitle.tsx
packages/react-core/src/components/Modal/ModalContent.tsx
packages/react-core/src/components/Modal/__tests__/__snapshots__/ModalContent.test.tsx.snap

**What**: Closes #3503 
Does this need to be demonstrated in an example if it happens automatically? I have not added an example at this point.

chore(Modal): add tooltip to truncated Modal titles

---

packages/react-table/src/components/Table/utils/decorators/selectable.tsx

**What**: A follow up from recent change to selectable transform for Table. Fixed the below error
The DOM was getting the correct attribute anyway, just that now we don't get the console error.
**Additional issues**: https://github.com/patternfly/patternfly-react/pull/4231

fix(table): update property name to avoid error

---

packages/react-core/src/components/NotificationDrawer/examples/NotificationDrawer.md
packages/react-integration/cypress/integration/notificationdrawerlightweight.spec.ts
packages/react-integration/demo-app-ts/src/Demos.ts
packages/react-integration/demo-app-ts/src/components/demos/NotificationDrawerDemo/NotificationDrawerLightweightDemo.tsx
packages/react-integration/demo-app-ts/src/components/demos/index.ts

Add streamlined notification drawer example to docs (examples, integration app, and integration tests).
Provide the streamlined notification drawer to patternfly that we use in openshift. IE we don't use
the read/unread notifications so all notifications in the drawer are styled unread, all category
counts are read. Also removed kebabs in all components in this new example.
fix #4160
cc: @mcarrano 
@mcoker when moving all notifications in a category to unread, I get a vertical scrollbar. Would you mind taking a look please? See image below:

docs(Notification Drawer): Add streamlined notification drawer example to docs

---

packages/react-core/src/components/Drawer/Drawer.tsx
packages/react-core/src/components/Drawer/examples/Drawer.md
packages/react-integration/cypress/integration/drawer.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/DrawerDemo/DrawerDemo.tsx

**What**: Closes #4309
This PR allows consumers to pass a function to the onMount or onUnMount prop and add their own functionality. This way allows for flexibility so, depending on the way the consumer is rendering the drawer content, they can specify where in the drawer to send focus with a ref.
An alternative way would be to manage this focus for them, but I was defaulting to flexibility first in case consumers end up using a more complex way of putting data into the drawer that I'm not considering.

fix(Drawer): opening drawer can send focus to the drawer

---

packages/react-charts/src/components/ChartLegendTooltip/ChartLegendTooltip.tsx
packages/react-charts/src/components/ChartLegendTooltip/ChartLegendTooltipContent.test.tsx
packages/react-charts/src/components/ChartLegendTooltip/ChartLegendTooltipContent.tsx
packages/react-charts/src/components/ChartLegendTooltip/__snapshots__/ChartLegendTooltip.test.tsx.snap
packages/react-charts/src/components/ChartLegendTooltip/__snapshots__/ChartLegendTooltipContent.test.tsx.snap
packages/react-charts/src/components/ChartLegendTooltip/index.ts
packages/react-charts/src/components/ChartStack/examples/ChartStack.md
packages/react-charts/src/components/ChartTooltip/ChartCursorTooltip.tsx
packages/react-charts/src/components/ChartTooltip/__snapshots__/ChartCursorFlyout.test.tsx.snap

A couple updates for the chart tooltip legend. 
- Updated the stacked area example to use a legend
- Renamed `ChartLegendTooltipLegend` (sounds weird) as `ChartLegendTooltipContent`
- Tooltip flyout should  be overridable
- Added `isCursorTooltip` prop so `ChartTooltip` can be used instead of `ChartCursorTooltip`

Chart: Tooltip legend updates

---

packages/react-charts/src/components/ChartTooltip/examples/ChartTooltip.md

Added an example showing how to embed HTML in a chart tooltip.
This example is similar to the legend tooltip feature. However, it shows how to customize the tooltip using raw HTML within an SVG.
If there is a future design that we don't support, this example should help folks implement their own custom tooltips.

chore(charts): HTML in an SVG tooltip example

---

packages/react-charts/src/components/ChartCursorTooltip/ChartCursorTooltip.tsx
packages/react-charts/src/components/ChartLegendTooltip/ChartLegendTooltip.tsx
packages/react-charts/src/components/ChartLegendTooltip/ChartLegendTooltipContent.tsx
packages/react-charts/src/components/ChartLegendTooltip/__snapshots__/ChartLegendTooltip.test.tsx.snap
packages/react-charts/src/components/ChartLegendTooltip/__snapshots__/ChartLegendTooltipContent.test.tsx.snap
packages/react-charts/src/components/ChartTooltip/ChartTooltip.tsx
packages/react-charts/src/components/ChartTooltip/examples/ChartTooltip.md
packages/react-charts/src/components/ChartUtils/chart-legend.ts
packages/react-charts/src/components/ChartUtils/chart-tooltip.ts

While testing Cost Management with the new legend tooltip feature (yet to be promoted), I noticed that the alignment is off with very long labels.
This change better aligns legend components with the tooltip flyout edge. 
**Before:**
**After:**
Related to #3219

chore(charts): align legend tooltip with flyout edge

---

packages/react-core/src/components/Modal/examples/Modal.md

**What**: Modal doesn't use size anymore 🚮
I don't think there are any issues for this.
No

Set modal size in docs -> variant

---

packages/react-core/src/layouts/Flex/examples/Flex.md

**What**: FlexModifiers no longer exists and results in a compile error if used in
a new project. Out it goes.
I don't think there are any issues for this.
No

Remove all references to FlexModifiers

---

packages/react-core/src/components/Title/examples/Title.md

**What**: Include missing import in Title docs.
No issue for this that I know of.
Side Q - has there been any thought to having CI compile doc code? Sometimes it doesn't compile and there are warnings for it like extra imports that could be removed. I've been a little spoiled by [rust docs that do it automatically](https://doc.rust-lang.org/rustdoc/documentation-tests.html). 
No

Import TitleSizes in Title demo

---

packages/react-core/src/components/Spinner/Spinner.tsx
packages/react-core/src/components/Spinner/__tests__/Generated/Spinner.test.tsx
packages/react-core/src/components/Spinner/__tests__/Generated/__snapshots__/Spinner.test.tsx.snap

Closes #4373
If we pass the className prop to the spinner, it was not getting rendered correctly: 
```tsx
import { Spinner } from '@patternfly/react-core';
SpinnerWithClass = () => (<Spinner className="apple"/>);
```
Will result in:
```
<span class="pf-c-spinner pf-m-xl" role="progressbar" aria-valuetext="Loading...">
<span class="pf-c-spinner__clipper"></span>
<span class="pf-c-spinner__lead-ball"></span>
<span class="pf-c-spinner__tail-ball"></span>
</span>
```
Fixed the issue by adding className to the class list now it will behave like this:
```tsx
<span class="pf-c-spinner pf-m-xl apple" role="progressbar" aria-valuetext="Loading...">
<span class="pf-c-spinner__clipper"></span>
<span class="pf-c-spinner__lead-ball"></span>
<span class="pf-c-spinner__tail-ball"></span>
</span>
```

fix(Spinner): className prop not getting applied properly

---

packages/react-charts/src/components/ChartLegend/examples/ChartLegend.md
packages/react-charts/src/components/ChartLegendTooltip/ChartLegendTooltip.tsx
packages/react-charts/src/components/ChartLegendTooltip/ChartLegendTooltipContent.tsx
packages/react-charts/src/components/ChartLegendTooltip/__snapshots__/ChartLegendTooltip.test.tsx.snap
packages/react-charts/src/components/ChartLegendTooltip/__snapshots__/ChartLegendTooltipContent.test.tsx.snap
packages/react-charts/src/components/ChartTooltip/examples/ChartTooltip.md
packages/react-charts/src/components/ChartUtils/chart-tooltip.ts

This takes the new legend tooltip (yet to be deployed) a step further and adds support for interactive legends. This eliminates the tedious, manual syncing of themed color scales between the legend and tooltip when data is hidden / shown.
In addition, I've made the following updates after testing with Cost Management.
- Ensures that the flyout height & width can be overridden. 
- Ensures tooltip remains within given height and width boundary.
- Flyout width should be adjusted (smaller) when values are not available
See #3219
**Example**
**Cost Management**

chore(charts): tooltip support for interactive legends

---

packages/react-core/src/components/Page/PageHeaderToolsGroup.tsx

**What**: 
In the official demos here:
https://www.patternfly.org/v4/documentation/react/demos/pagelayout
You can see from the horizontal nav example that only the default and lg
props are specified.
This is legal in JS and I assume is how it is expected to work. Set a
default and add exceptions for other sizes you'd like for other
properties.
In ts, there is a hard requirement on setting each of the properties
because it is typechecked unlike JS which is super tedious (especially
if you just want something to always be visible).
This brings the convenience of the JS examples to TS as well.
I don't think there are any issues for this.
No

Ensure PagerHeaderToolsGroup visibility mods are optional

---

packages/react-charts/src/components/ChartArea/examples/ChartArea.md
packages/react-charts/src/components/ChartCursorTooltip/ChartCursorFlyout.tsx
packages/react-charts/src/components/ChartLegend/examples/ChartLegend.md
packages/react-charts/src/components/ChartLegendTooltip/ChartLegendTooltip.tsx
packages/react-charts/src/components/ChartLegendTooltip/ChartLegendTooltipContent.tsx
packages/react-charts/src/components/ChartLegendTooltip/__snapshots__/ChartLegendTooltipContent.test.tsx.snap
packages/react-charts/src/components/ChartLine/examples/ChartLine.md
packages/react-charts/src/components/ChartStack/examples/ChartStack.md
packages/react-charts/src/components/ChartTooltip/examples/ChartTooltip.md
packages/react-charts/src/components/ChartUtils/chart-tooltip.ts

This syncs the tooltip legend (yet to be published) with the items from Victory's `activePoints` array. This is a more reliable way to hide / show interactive legends because `activePoints` only includes visible items when data points are missing / not available.
In addition, I cleaned up `ChartLegendTooltipContent`. That evolved to more than just a legend component, so I've replaced `ChartLegendProps` with a `legendComponent` prop for customization -- which eliminated unused props like `standalone`, `x`, `y`, etc.
See #3219

fix(charts): tooltip legend to use Victory's activePoints

---

packages/react-virtualized-extension/src/components/Virtualized/VirtualGrid.ts
packages/react-virtualized-extension/src/components/Virtualized/VirtualizedTable.md

**What**: fix for filtering in #4311

feat(react-virtualized-extension docs): add filterable demo, fix for filtering+scrolling

---

packages/react-charts/src/components/ChartLegendTooltip/__snapshots__/ChartLegendTooltipContent.test.tsx.snap
packages/react-charts/src/components/ChartUtils/chart-tooltip.ts

This adds a fixed line height for the labels shown in with the chart's tooltip legend. 
In Cost Management, we occasionally show a "no data" message in place of the numeric value. The line height adjusts vertically to accommodate the smaller text, but prefer the legend remain the same height.
See #3219
**Before**
**After**

Chart legend tooltip label size

---

packages/react-core/src/components/OptionsMenu/OptionsMenuToggleWithText.tsx
packages/react-core/src/components/OptionsMenu/__tests__/Generated/__snapshots__/OptionsMenuToggleWithText.test.tsx.snap
packages/react-core/src/components/OptionsMenu/__tests__/__snapshots__/OptionsMenu.test.tsx.snap

**What**: I pass the `isDisabled` value to the dropdown button so that it cannot be focused when it is disabled.
Closes #4423

fix(OptionsMenu): fix accessibility bug in plain with text disabled part

---

packages/react-core/src/components/Button/__tests__/__snapshots__/Button.test.tsx.snap
packages/react-core/src/components/Select/SelectMenu.tsx
packages/react-table/src/components/Table/Table.md

**What**: Closes #4447
If `label` is left out or set as `label=""` in `SelectGroup`, no title will be displayed in the UI. We may want to consider making the prop required later.

fix(Select): handle missing select group label

---

packages/react-core/src/components/Select/SelectOption.tsx
packages/react-core/src/components/Select/__tests__/SelectOption.test.tsx
packages/react-core/src/components/Select/__tests__/__snapshots__/SelectOption.test.tsx.snap
packages/react-core/src/components/Select/examples/Select.md
packages/react-integration/cypress/integration/select.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectDemo.tsx

**What**: Closes #4430
Applies to all variants except for `checkbox` currently due to differing structures (checkbox options are inside a label instead of a button). @mcoker Is there a design for descriptions with checkbox select?

feat(Select): add option description property

---

packages/react-core/src/components/Page/PageHeaderToolsItem.tsx

**What**:
As in `DataListAction` and `PageHeaderToolbarGroup`, prop **visibility** should be optional in `PagerHeaderToolsItem`.
From the official docs https://www.patternfly.org/v4/documentation/react/demos/pagelayout:
```jsx
/>
</PageHeaderToolsItem>
<PageHeaderToolsItem visibility={{ default: 'hidden', md: 'visible' }} />
<Dropdown
isPlain
```
Closes #4495
Nope.

PagerHeaderToolsItem visibility props should be optional

---

packages/react-topology/src/behavior/withCreateConnector.tsx

During the migration of topology to patternfly, some functionality was lost.
When creating a connector, if multiple connection choices exist, the developer had the option to provide a custom set of menu items. At some point while fixing lint errors, this code was removed.
Re-instated the missing code that will render the choice array in place if the array is a set of valid `React.ReactElement` objects. 
cc @jeff-phillips-18 
This is required for OpenShift console to adopt patternfly topology.

fix(topology): add lost support for custom menu items in withCreateConnector

---

.github/dependabot.yml

**What**: Our bot to bump core in React broke some time ago. This could possibly work instead.
**Additional issues**: Dependabot claims to [support monorepos](https://dependabot.com/javascript/) and the [config is valid.](https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#configuration-options-for-dependabotyml)

chore(dependabot): add dependabot.yml

---

packages/react-core/src/components/Drawer/DrawerPanelContent.tsx
packages/react-core/src/components/Drawer/__tests__/__snapshots__/Drawer.test.tsx.snap

**What**: Closes #4498
**Additional issues**: The animation still works since `<div className="pf-c-drawer-panel">` is always rendered.

fix(DrawerPanelContent): don't render children when hidden

---

packages/react-core/src/components/Drawer/examples/Drawer.md

**Fixes**:
#4496 
**What**:
Probably small copy&paste made mistake in the docs. Title was in both example mentioning "left" even though in the first case it's on the right side.

fix(Drawer) Small mistake in the documentation for Drawer

---

packages/react-core/src/components/Dropdown/examples/Dropdown.md

**What**: Closes https://github.com/patternfly/patternfly-react/issues/3337
This PR updates the example for "Split button action" of the Dropdown component, making the interactions trigger alerts instead of console logs so that users who are not developers can see the impacts of interacting with elements of the Dropdowns. I think it was already working as desired, just that it wasn't as obvious with the way the example was wired up.
We should probably swap all similar types of console logs in the docs to alerts for the same reason. I can do that in a separate PR if it's helpful.

fix(examples): make the interactions in the demo more life-like

---

packages/react-core/src/components/Select/SelectToggle.tsx
packages/react-core/src/components/Select/__tests__/__snapshots__/Select.test.tsx.snap

**What**: Closes #4471
Button was actually sending the event twice.
Since the input already opens/closes the menu via keyboard navigation, would it be better to remove the button from the tabIndex instead @jessiehuff ? Using the keyboard to open the menu via this button doesn't focus the input atm.

feat(Select): fix typeahead button toggle propagation

---

packages/react-core/src/components/Drawer/Drawer.tsx
packages/react-core/src/components/Drawer/DrawerPanelContent.tsx
packages/react-core/src/components/Drawer/__tests__/Generated/__snapshots__/Drawer.test.tsx.snap
packages/react-core/src/components/Drawer/__tests__/__snapshots__/Drawer.test.tsx.snap
packages/react-core/src/components/Drawer/examples/Drawer.md
packages/react-integration/cypress/integration/drawer.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/DrawerDemo/DrawerDemo.tsx

**What**: Closes #4505
**Additional issues**: I reviewed this with @mattnolting . The reason for #4505 was the animating drawer's CSS does not allowing tabbing to the drawer content because if you tab to the content during the animation the animation immediately finished and the negative margin animation leads to the jerkiness experienced in #4505. The solution is to wait for the animation.
`onMount` is not a proper name for the prop since this is not related to React lifecycles. I've renamed it to `onExpand` which is more accurate. I don't see anyone other than us using it since 30 days ago when it was added in #4328 and the drawer is still in beta, so I think this is okay.

fix(drawer): rename onMount to onExpand and add animation timeout

---

packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/Selection.tsx
packages/react-topology/src/behavior/useSelection.tsx
packages/react-topology/src/behavior/withCreateConnector.tsx
packages/react-topology/src/components/VisualizationSurface.tsx

This change addresses some missing functionality in the topology migration along with fixing types and default values.
- Add options to `withCreateConnector` to allow configuration of the drag item and operation.
- Removed unused prop from `VisualizationSurfaceProps` which was part of the old API.
- Fixed `raiseOnSelect` to default to `true` which was the old default before the selection API changes.
cc @jeff-phillips-18

fix(topology): create connector drag spec configuration

---

packages/react-core/src/components/Toolbar/ToolbarContent.tsx
packages/react-core/src/components/Toolbar/ToolbarGroup.tsx
packages/react-core/src/components/Toolbar/ToolbarItem.tsx
packages/react-core/src/components/Toolbar/ToolbarToggleGroup.tsx

- deprecate visiblity prop in ToolbarItem, ToolbarContent, ToolbarGroup, and ToolbarToggleGroup
- add visibility prop in ToolbarItem, ToolbarContent, ToolbarGroup, and ToolbarToggleGroup
fix #4501

fix(Toolbar*): change spelling of visiblity prop

---

packages/react-charts/package.json
packages/react-table/package.json
packages/react-topology/package.json
yarn.lock

**What**: Closes security vulnerability

chore(deps): bump lodash to 4.17.19

---

packages/react-core/src/components/Dropdown/examples/Dropdown.md

- update the dropdown with image example to use an Avatar instead of a UserIcon
re #4551

docs(Dropdown.md): update dropdown with image example to use an Avatar

---

packages/react-docs/package.json

**What**: Remove unneeded deps for new build system in patternfly-org. We don't need these transitive dependencies to be installed.

fix(react-docs): move non-patternfly deps to devDeps

---

packages/react-table/src/components/Table/ActionsColumn.tsx
packages/react-table/src/components/Table/examples/Table.md

If consumers would want to add custom className or specific attribute to actions dropdown they would be out of luck, this PR adds option to override any dropdown property in actions column. Meaning even dropdown direction and position, or custom classes, additional props and even ifthere is need to change the toggle or other properties they can do that.
Fixes: https://github.com/patternfly/patternfly-react/issues/4561

feat(Table actions): allow custom properties for actions

---

packages/react-topology/package.json
yarn.lock

Without this when using the package with typescript an error about
missing types is raised.
**What**: Closes #4568
https://github.com/atlasmap/atlasmap/issues/2186

chore(topology): move @types to the dependencies list

---

packages/react-core/src/components/Select/Select.tsx
packages/react-core/src/components/Select/SelectToggle.tsx
packages/react-core/src/components/Select/__tests__/Select.test.tsx
packages/react-core/src/components/Select/__tests__/__snapshots__/Select.test.tsx.snap
packages/react-integration/cypress/integration/select.spec.ts

**What**: Closes https://github.com/patternfly/patternfly-react/issues/4615
The first commit fixes the issue https://github.com/patternfly/patternfly-react/issues/4615 which is reproducible on CodeSandbox: https://codesandbox.io/s/elegant-hofstadter-omfke?file=/index.js
After fixing this I noticed that the preventDefault method was not called for an "enter" key event. Which results in the issue that the Form was automatically submitted. When the Select is open and the user presses enter this should close the select field instead of submitting the form. I added a second commit for this.
I'm not sure if this is your desired way to solve this issue. I'm open for your feedback on this fix.

Fix Maximum call stack size exceeded in a read-only typeahead Select field when pressing enter

---

packages/react-core/src/components/Modal/Modal.tsx
packages/react-core/src/components/Wizard/__tests__/Generated/__snapshots__/Wizard.test.tsx.snap

Closes #4093 
@KKoukiou could you test this change and be extra sure this addresses your specific issue?

fix(Modal): ensure getElement does not return null

---

packages/react-core/src/components/Button/Button.tsx
packages/react-core/src/components/Button/__tests__/Button.test.tsx
packages/react-core/src/components/Button/__tests__/__snapshots__/Button.test.tsx.snap
packages/react-core/src/components/Button/examples/Button.md
packages/react-integration/cypress/integration/button.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/ButtonDemo/ButtonDemo.tsx

feat(Button): add cta/large modifier

---

packages/react-core/src/components/Hint/Hint.tsx
packages/react-core/src/components/Hint/HintBody.tsx
packages/react-core/src/components/Hint/HintFooter.tsx
packages/react-core/src/components/Hint/HintTitle.tsx
packages/react-core/src/components/Hint/__tests__/Hint.test.tsx
packages/react-core/src/components/Hint/__tests__/__snapshots__/Hint.test.tsx.snap
packages/react-core/src/components/Hint/examples/Hint.md
packages/react-core/src/components/Hint/index.ts
packages/react-core/src/components/index.ts
packages/react-integration/cypress/integration/hint.spec.ts
packages/react-integration/demo-app-ts/src/Demos.ts
packages/react-integration/demo-app-ts/src/components/demos/HintDemo/HintDemo.tsx
packages/react-integration/demo-app-ts/src/components/demos/index.ts

feat(Hint): add hint components

---

packages/react-core/src/components/Page/Page.tsx
packages/react-core/src/components/Page/PageHeader.tsx
packages/react-core/src/components/Page/examples/Page.md

**What**: Closes #4549 
`PageContext.Consumer` returns a children that is a function. And that function's argument is the values set in the `PageContext`.
However, in `PageHeader` there was a mistake that assumed the function's argument is `PageHeaderProps`. Which made the `PageHeaderProps` to have `isManagedSidebar` even though it's not used and caused a confusion.
This patch fixes that mistake.
This also solves the warning that were mentioned in #4549.
//cc @dtaylor113 @redallen

fix(pageheader): use the correct type for the page context

---

packages/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx

**What**: Closes #4618
This PR allows copying to keep the line breaks/spaces in the text

fix(ClipboardCopy): maintain line breaks & spaces when copying text

---

packages/react-catalog-view-extension/package.json
packages/react-core/src/components/Wizard/Wizard.tsx
packages/react-core/src/components/Wizard/WizardBody.tsx
packages/react-core/src/components/Wizard/WizardNav.tsx
packages/react-core/src/components/Wizard/WizardNavItem.tsx
packages/react-core/src/components/Wizard/WizardToggle.tsx
packages/react-core/src/components/Wizard/__tests__/Generated/Wizard.test.tsx
packages/react-core/src/components/Wizard/__tests__/Generated/WizardBody.test.tsx
packages/react-core/src/components/Wizard/__tests__/Generated/WizardNav.test.tsx
packages/react-core/src/components/Wizard/__tests__/Generated/WizardNavItem.test.tsx
packages/react-core/src/components/Wizard/__tests__/Generated/WizardToggle.test.tsx
packages/react-core/src/components/Wizard/__tests__/Generated/__snapshots__/Wizard.test.tsx.snap
packages/react-core/src/components/Wizard/__tests__/Generated/__snapshots__/WizardBody.test.tsx.snap
packages/react-core/src/components/Wizard/__tests__/Generated/__snapshots__/WizardNav.test.tsx.snap
packages/react-core/src/components/Wizard/__tests__/Generated/__snapshots__/WizardNavItem.test.tsx.snap
packages/react-core/src/components/Wizard/__tests__/Generated/__snapshots__/WizardToggle.test.tsx.snap
packages/react-core/src/components/Wizard/__tests__/Wizard.test.tsx
packages/react-core/src/components/Wizard/__tests__/__snapshots__/Wizard.test.tsx.snap
packages/react-core/src/components/Wizard/examples/FinishedStep.js
packages/react-core/src/components/Wizard/examples/Wizard.md
packages/react-integration/cypress/integration/wizard.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/WizardDemo/WizardDemo.tsx

**What**: Closes https://github.com/patternfly/patternfly-react/issues/1588
Updates Wiz to use more descriptive labels for landmark regions and to allow for buttons as well as anchors for the main nav items. Also adds jest/cypress tests.
It would be good to start considering these accessible names and the overall strategy of how to handle label composition as part of our ongoing content strategy (it's microcopy). I created a new issue tag `microcopy review` to help identify where we need more people to weigh in on the approach in question. @abigaeljamie ping

feat(wiz): make wizard nav items more easily discoverable

---

packages/react-core/src/components/Dropdown/examples/Dropdown.md
packages/react-core/src/components/EmptyState/examples/EmptyState.md

**What**: For the patternfly.org refactor I've added proper MDX scope handling, so each file MUST import components it uses that aren't in react-core or react-table.

fix(react-docs): add missing imports

---

packages/react-core/src/components/Wizard/examples/Wizard.md

**What**: Followup to #4627. For the patternfly.org refactor we need to use the `### Example title` syntax.

fix(react-docs): title syntax

---

packages/react-topology/src/Visualization.ts

**What**: 
Fixes an issue where a node is not shown if it is no longer a child of a valid group (when it previously was)
None
Need this fix for OpenShift Console 4.6

fix(Topology): Re-parent nodes with invalid parents to graph

---

packages/react-core/src/components/Select/Select.tsx
packages/react-core/src/components/Select/SelectMenu.tsx
packages/react-core/src/components/Select/__tests__/__snapshots__/Select.test.tsx.snap
packages/react-core/src/components/Select/examples/Select.md
packages/react-core/src/helpers/util.ts

**What**: Closes #4590, #4592 + a couple related bugs found while addressing the tickets
In summary:
- Allows typeahead variants to properly use `isGrouped` and `SelectGroup`. (#4590)
- Allows mixed grouped and ungrouped SelectOptions when using `isGrouped`, as typeahead variants may add ungrouped options (such as no results, and createable options).
- Fixes bug in keyboard navigation of grouped options, where the ref collection wasn't indexed properly.
- Fixes bug in keyboard navigation of typeahead options, where disabled options weren't skipped properly.
- Fixes bug where an error occurred when a SelectGroup had only one SelectOption and wasn't defined as an array. (#4592)
- Adds handling of an edge case in typeahead keyboard navigation, where a typeahead select's options could solely …

feat(Select): allow typeahead groups, fix few bugs around groups

---

packages/react-core/src/components/Toolbar/ToolbarFilter.tsx

fix(Toolbar): deleteChip expects categoryKey as string

---

packages/react-core/src/components/Page/PageHeaderToolsItem.tsx
packages/react-integration/cypress/integration/page.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/PageDemo/PageDemo.tsx

fix(PageHeaderToolsItem): fix breakpoint typo

---

packages/react-core/src/components/SearchInput/SearchInput.tsx
packages/react-core/src/components/SearchInput/__tests__/SearchInput.test.tsx
packages/react-core/src/components/SearchInput/__tests__/__snapshots__/SearchInput.test.tsx.snap
packages/react-core/src/components/SearchInput/examples/SearchInput.md
packages/react-core/src/components/SearchInput/index.ts
packages/react-core/src/components/index.ts
packages/react-integration/cypress/integration/searchinput.spec.ts
packages/react-integration/demo-app-ts/src/Demos.ts
packages/react-integration/demo-app-ts/src/components/demos/SearchInputDemo/SearchInputDemo.tsx
packages/react-integration/demo-app-ts/src/components/demos/index.ts

feat(SearchInput): add new SearchInput component

---

packages/react-docs/UPGRADE-GUIDE.md

fix typos 

---

packages/react-catalog-view-extension/package.json
packages/react-charts/package.json
packages/react-core/package.json
packages/react-core/src/components/NotificationDrawer/NotificationDrawerHeader.tsx
packages/react-core/src/components/Page/Page.tsx
packages/react-core/src/components/Page/__tests__/__snapshots__/Page.test.tsx.snap
packages/react-core/src/demos/NotificaitonDrawer/examples/NotificationDrawerDemo.md
packages/react-docs/package.json
packages/react-icons/package.json
packages/react-styles/package.json
packages/react-table/package.json
packages/react-tokens/package.json
yarn.lock

feat(NotificationDrawer): Add notification drawer demo

---

packages/react-core/src/components/Select/SelectToggle.tsx
packages/react-integration/cypress/integration/select.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectDemo.tsx

**What**: Closes #4664
Check preventing typeahead variants' key inputs reaching the other variants' open/close logic was removed.

feat(Select): fix space/enter closing typeahead variants incorrectly

---

packages/react-core/src/components/SearchInput/examples/SearchInput.md

**What**: Titles should use camel case.

fix(search-input): use title case id

---

packages/react-core/src/components/Tile/examples/Tile.md
packages/react-core/src/components/TreeView/examples/TreeView.md

**What**: Closes #4727 
This PR updates icon imports in Tile and Tree view examples from barrel file to dist/js file.

fix(lint): fixed linting errors related to icon imports in Tile and TreeView

---

packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/TopologyPackage.tsx
packages/react-topology/src/Visualization.ts
packages/react-topology/src/components/GraphComponent.tsx
packages/react-topology/src/elements/BaseEdge.ts
packages/react-topology/src/elements/BaseElement.ts
packages/react-topology/src/elements/BaseGraph.ts
packages/react-topology/src/elements/BaseNode.ts
packages/react-topology/src/elements/__tests__/BaseGraph.spec.ts
packages/react-topology/src/layouts/BaseLayout.ts
packages/react-topology/src/layouts/ColaLayout.ts
packages/react-topology/src/layouts/ColaNode.ts
packages/react-topology/src/layouts/ForceLayout.ts
packages/react-topology/src/layouts/ForceSimulation.ts
packages/react-topology/src/layouts/LayoutNode.ts
packages/react-topology/src/layouts/LayoutOptions.ts
packages/react-topology/src/types.ts

**What**: 
This PR is aimed at allowing adopters to track the current layout of nodes so that it can be saved and restored.
Provides API for `toModel` for the current Controller/GraphElements.
Keeps track of nodes that have had their position set, do not reset positions on layout.
Adds events on individual node moves, and overall event for all node moves (debouncing individual node moves)

feat(topology): Enable saving current topology graph model

---

packages/react-core/src/components/Popover/index.ts
packages/react-core/src/components/Tooltip/index.ts
packages/react-integration/cypress/integration/tablesimple.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/TableDemo/TableSimpleDemo.tsx
packages/react-table/src/components/Table/HeaderCellInfoWrapper.tsx
packages/react-table/src/components/Table/base/header-row.tsx
packages/react-table/src/components/Table/base/types.tsx
packages/react-table/src/components/Table/examples/Table.md

**What**: Closes https://github.com/patternfly/patternfly-react/issues/3969
Example:
https://patternfly-react-pr-4778.surge.sh/documentation/react/components/table#basic
(First help button activates a tooltip on hover over, second help button activates a popover on click)
Tooltip variant:
Popover variant:

header cell information tooltip/popover

---

packages/react-core/src/demos/PrimaryDetail.md

**What**: Closes #4705 
This PR changes the double dashes in the `Primary-detail` example titles to single dashes. For one milestone this will appear correct on patternfly.org (`Primary-detail`) but incorrectly on the react workspace (`Primary detail`) until build process for react is updated and pushed live in next release.

fix(Primary-detail): Changed double dashes to single in examples

---

packages/react-core/src/components/Page/Page.tsx
packages/react-core/src/components/Page/__tests__/Generated/__snapshots__/Page.test.tsx.snap

**What**: Closes #4480. Fixes resize event listener never detaching.
**Additional issues**: Doesn't close when nav item clicked. I think that's a bit too opinionated since designs can use side navs for more than just navigation. It's also tricky to code, but can be achieved consumer-side.

fix(page): hide PageSideBar onClick on mobile when isManagedSidebar

---

packages/react-core/src/components/Drawer/__tests__/__snapshots__/Drawer.test.tsx.snap
yarn.lock

**What**: Closes #4812 
This PR updates snapshots for Drawer which are breaking CI

fix(tests): updated Drawer snapshots

---

packages/react-core/src/components/Tabs/Tabs.tsx

The "shownKeys" state array needs to be updated on props changed
Fixes #4805

fix(Tabs): Handle activeKey props update with mountOnEnter on Tabs

---

packages/react-topology/src/behavior/useDndDrag.tsx

**What**:
https://github.com/patternfly/patternfly-react/pull/4826 fixed issues with DnD however when working on the fix with Jeff, I mistakenly changed the selector for the node which is used to cancel the drag operation when escape is pressed. The result of this change does not cancel the current drag but instead prevents subsequent drags from starting.
`d3.event.view` refers to the `window` which is listening to drag move events.
`node` refers to the topology node where the drag initiates.
Reverted the line that caused the breakage.
Also updated the event selector to completely remove d3 drag event listeners on the node when the component unmounts. This is in accordance with the online documentation for d3-drag: https://github.com/d3/d3-drag which states to use `selection.on(".drag", …

fix(topology): fix selector for cancelling dnd

---

packages/react-core/src/components/Tabs/Tabs.tsx
packages/react-integration/cypress/integration/tabdemo.spec.ts

**What**: Closes #4785 
Hey @jessiehuff I took the initiative and conditionally render "aria-controls" .
I also updated its spec test to make sure it is working properly.
Would you mind looking? :pray: 
Thanks.

fix(tabs): conditionally render aria-controls when mountOnEnter

---

packages/react-core/src/demos/Banner.md
packages/react-core/src/demos/Card/Card.md
packages/react-core/src/demos/NotificationDrawer/NotificationDrawer.md
packages/react-core/src/demos/Page/Page.md
packages/react-core/src/demos/TileDemo.md
packages/react-docs/RELEASE-NOTES.md
packages/react-docs/UPGRADE-GUIDE.md
packages/react-docs/patternfly-docs.source.js
packages/react-table/src/demos/Table.md

**What**: Matches new org design: https://www.patternfly.org/v4/get-started/release-notes/react. Closes #4861

fix(react-docs): change overview to get-started

---

packages/react-core/src/components/ChipGroup/ChipGroup.tsx
packages/react-core/src/components/ChipGroup/__tests__/__snapshots__/ChipGroup.test.tsx.snap
packages/react-core/src/components/Select/__tests__/__snapshots__/Select.test.tsx.snap
yarn.lock

**What**: Closes #4404 
Adds new `<div class="pf-c-chip-group__main">` wrapper element which keeps chip group close button in top-right corner instead of wrapping to new line.

added chipGroupMain div, updated snapshots

---

packages/patternfly-react/src/components/VerticalNav/VerticalNav.js
packages/patternfly-react/src/components/VerticalNav/VerticalNavItemHelper.js

**What:** Closes #4783
VerticalNav should not prevent default and call onClick handler
when user wishes to open a link from vertical navigation in another tab
and uses ctrl+click.
**Additional issues**: https://projects.theforeman.org/issues/29020

fix: Do not handle modified clicks on VerticalNav links

---

package.json
packages/react-docs/patternfly-a11y.config.js
packages/transformer-cjs-imports/index.js
packages/transformer-cjs-imports/package.json
packages/tsconfig.base.json
yarn.lock

**What**: Closes #4562. Decreases bundle sizes in product and on our docs site ~10% by having ESM builds only import ESM files:
Notice that there are no longer any CJS imports (like `/dist/js`) for `@patternfly` in our docs build.
**Changes:**
- Add [ttypescript](https://www.npmjs.com/package/ttypescript) (transformer typescript)
- Allows hooking into `tsc` similar to babel plugins
- Add simple import transformer for `/@patternfly\/.*\/dist\/js/` following [this](https://levelup.gitconnected.com/writing-typescript-custom-ast-transformer-part-2-5322c2b1660e) tutorial
**Additional issues**: See also #4906

fix(duplicate-cjs): add transformer-cjs-imports

---

packages/react-core/src/components/Select/Select.tsx
packages/react-core/src/components/Select/SelectMenu.tsx
packages/react-core/src/components/Select/__tests__/__snapshots__/Select.test.tsx.snap
packages/react-core/src/components/Select/examples/Select.md
packages/react-core/src/helpers/util.ts
packages/react-integration/cypress/integration/select.spec.ts
packages/react-integration/cypress/integration/selectfavorites.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectDemo.tsx

**What**: Closes #4641 , #4890
See the "Single",  "Grouped single" and "Checkbox input" , "  and "Grouped typeahead"  to see the divider preview.
A check was also added to `componentDidUpdate` so that createRenderableFavorites is only called if onFavorite is provided.

feat(Select): Added support for Divider in Select

---

packages/react-datetime/package.json

**What**: Fixes build again -- react-datetime broke somewhere.

fix(build): use same patternfly versions

---

packages/react-core/src/components/Modal/Modal.tsx
packages/react-core/src/components/Modal/ModalBox.tsx
packages/react-core/src/components/Modal/ModalContent.tsx
packages/react-core/src/components/Modal/__tests__/Generated/__snapshots__/ModalBox.test.tsx.snap
packages/react-core/src/components/Modal/__tests__/ModalBox.test.tsx
packages/react-core/src/components/Modal/__tests__/__snapshots__/ModalBox.test.tsx.snap
packages/react-core/src/components/Modal/examples/Modal.md
packages/react-integration/cypress/integration/modal.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/ModalDemo/ModalDemo.tsx

**What**: Closes #4819
Adds `position` property for top aligned modals. @mcoker Let me know if this property makes sense. I could change it to something like `isTopAligned` but I wasn't sure if we wanted to add other position type alignments (bottom/left/right) later on.
Adds `distanceFromTop` property to set the custom spacer class `--pf-c-modal-box--m-align-top--spacer`.

feat(Modal): add top align to modal

---

packages/react-core/src/components/Select/SelectGroup.tsx
packages/react-core/src/components/Select/SelectMenu.tsx
packages/react-core/src/components/Select/__tests__/Generated/__snapshots__/SelectGroup.test.tsx.snap
packages/react-core/src/components/Select/__tests__/__snapshots__/Select.test.tsx.snap
packages/react-core/src/components/Select/__tests__/__snapshots__/SelectGroup.test.tsx.snap

fix(Select): grouped Select generates invalid HTML

---

packages/react-icons/src/createIcon.tsx

**What**: Fixes @jcaianirh 's problem in OpenShift which uses `<CheckIcon alt="" />`. This becomes `<svg alt="">` which is invalid ([should be `<svg aria-label="">`](https://www.scottohara.me/blog/2019/05/22/contextual-images-svgs-and-a11y.html)), but we'll continue lying that it's okay.

fix(react-icons): use lying cast

---

packages/react-core/src/components/DataList/DataList.tsx
packages/react-core/src/components/DataList/DataListCheck.tsx
packages/react-core/src/components/DataList/DataListControl.tsx
packages/react-core/src/components/DataList/DataListDragButton.tsx
packages/react-core/src/components/DataList/DataListItem.tsx
packages/react-core/src/components/DataList/__tests__/DataList.test.tsx
packages/react-core/src/components/DataList/__tests__/Generated/__snapshots__/DataList.test.tsx.snap
packages/react-core/src/components/DataList/__tests__/Generated/__snapshots__/DataListCheck.test.tsx.snap
packages/react-core/src/components/DataList/__tests__/__snapshots__/DataList.test.tsx.snap
packages/react-core/src/components/DataList/examples/DataList.md
packages/react-core/src/components/DataList/index.ts
packages/react-integration/cypress/integration/datalist.spec.ts
packages/react-integration/demo-app-ts/src/Demos.ts
packages/react-integration/demo-app-ts/src/components/demos/DataListDemo/DataListDraggableDemo.tsx
packages/react-integration/demo-app-ts/src/components/demos/index.ts

**What**: Closes #4708
Basic implementation of draggable. DataLists with nested state dependencies (like expandable) I am having trouble getting to work, because the whole list needs to be saved in the state in order to update, but you cannot access state variables inside of itself.
@mcoker The draggable ghost defaults to a copy of the whole row, and I haven't found a great way to change this yet, but it at least seems to preserve the spacing. The entire row is also draggable by default instead of just the chip button (with mouse), but it doesn't interfere with other actions so I'm not sure this is an issue.
For keyboard, hitting `space` or `enter` on a drag chip button begins the drag. Use the `up arrow` or `down arrow` to move the row (showing the ghost placeholder) and `enter` to …

feat(DataList): add draggable feature for basic list

---

packages/react-catalog-view-extension/package.json
packages/react-charts/package.json
packages/react-core/package.json
packages/react-icons/package.json
packages/react-inline-edit-extension/package.json
packages/react-table/package.json
packages/react-table/src/demos/Table.md
packages/react-topology/package.json
packages/react-virtualized-extension/package.json
scripts/generators/package/package.json.hbs
yarn.lock

**What**: Our semver of tslib was ^1.11.1, but version 1.14.0 recently released breaking changes that consumers might install if they don't have a lockfile. This PR pins it to the older version until the Typescript team fixes it or we upgrade to tslib 2.
**Additional issues**: I filed an issue upstream: https://github.com/microsoft/tslib/issues/128

fix(tslib): lock tslib to 1.13.0 for consumers

---

packages/react-charts/src/components/ChartCursorTooltip/ChartCursorFlyout.tsx
packages/react-core/src/components/TreeView/TreeView.tsx
packages/react-core/src/components/TreeView/TreeViewList.tsx
packages/react-core/src/components/TreeView/TreeViewSearch.tsx
packages/react-inline-edit-extension/src/components/ConfirmButtons/ConfirmButtons.tsx

All the remaining places where we use `import React from 'react'` are
either example code which is not typescript or tests code.
Fixes #4936

Fix typescript complaining about missing default export when importing React

---

packages/react-charts/src/components/ChartStack/examples/ChartStack.md

Fixes this example, where the chart appears much smaller than expected.
**Before**
Fixes https://github.com/patternfly/patternfly-react/issues/4989
**After**

chore(charts): fix stack chart example size

---

packages/react-charts/src/components/ChartLegend/examples/ChartLegend.md
packages/react-charts/src/components/ChartTooltip/examples/ChartTooltip.md

Fixes this example, where the "Show Tootip" button appears on top of the copy/code sandbox controls.
**Before**
Fixes https://github.com/patternfly/patternfly-react/issues/4987
**After**

chore(chart): fixed example button location

---

packages/react-charts/src/components/ChartLegend/examples/ChartLegend.md

Fixes an example, where the "Legend layout" example appears much smaller than expected.
**Before**
**After**
Fixes https://github.com/patternfly/patternfly-react/issues/4990

chore(charts): fix legend example size

---

packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/TopologyPackage.tsx
packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/layouts/defaultLayoutFactory.ts
packages/react-topology/src/layouts/LayoutNode.ts

**What**: 
Prevent layout from updating node positions when the node is fixed. Cola layout (in particular) is updating the node position even though the node is set to fixed. Ignore the updates in this case.
Added a ColaNoForce layout to the integration app to verify the fix.

fix(topology): Do not update nodes on layout when fixed

---

packages/react-core/src/components/DataList/DataList.tsx
packages/react-core/src/components/DataList/__tests__/__snapshots__/DataList.test.tsx.snap
packages/react-core/src/components/DataList/examples/DataList.md

**What**: Closes #4941. If the user tries to drag/drop with the mouse outside the `<ul>` cancel the drop altogether. If they use the keyboard and press Escape do the same.

fix(datalist): cancel moving for invalid drops

---

packages/react-charts/src/components/ChartArea/examples/ChartArea.md
packages/react-charts/src/components/ChartLegend/examples/ChartLegend.md
packages/react-charts/src/components/ChartLine/examples/ChartLine.md
packages/react-charts/src/components/ChartStack/examples/ChartStack.md
packages/react-charts/src/components/ChartTooltip/examples/ChartTooltip.md

This fixes the `createContainer` property order for the chart legend tooltip examples.
Ensures the tooltip continues to work after charts are re-rendered (e.g., when the browser window is resized).
Fixes https://github.com/patternfly/patternfly-react/issues/5005

chore(charts): Legend tooltip example: Fix createContainer property order

---

packages/react-core/src/components/Select/Select.tsx
packages/react-integration/cypress/integration/select.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectDemo.tsx

**What**: Closes #4945 
//cc @jenny-s51

fix(select): skip the divider children in getDisplay

---

packages/react-core/src/components/Nav/NavExpandable.tsx
packages/react-integration/demo-app-ts/src/components/demos/ModalDemo/ModalDemo.tsx

in https://github.com/patternfly/patternfly-react/pull/5014 the pf4 lint job fails.
It looks like it is due to a very small issue with the Nav component and the Modal demo.
```
/home/circleci/project/packages/react-core/src/components/Nav/NavExpandable.tsx
99:7  error  'id' is assigned a value but never used          @typescript-eslint/no-unused-vars
105:7  error  'groupId' is assigned a value but never used     @typescript-eslint/no-unused-vars
106:7  error  'isExpanded' is assigned a value but never used  @typescript-eslint/no-unused-vars
107:7  error  'onExpand' is assigned a value but never used    @typescript-eslint/no-unused-vars
108:7  error  'ouiaId' is assigned a value but never used      @typescript-eslint/no-unused-vars
109:7  error  'ouiaSafe' is assigned a …
```

chore(ci): fix linting errors in Nav and Modal demo

---

packages/react-core/src/components/Nav/NavExpandable.tsx
packages/react-integration/demo-app-ts/src/components/demos/ModalDemo/ModalDemo.tsx
packages/react-table/src/components/Table/BodyCell.tsx
packages/react-table/src/components/Table/Table.test.tsx
packages/react-table/src/components/Table/examples/Table.md
packages/react-table/src/components/Table/utils/headerUtils.tsx

**What**: Closes https://github.com/patternfly/patternfly-react/issues/4922
- Manually add `dataLabel` to columns with no titles so they appear in mobile view with some text
- Do not add a `data-label` to cells that are expandable

fix compound expandable data labels

---

packages/react-core/src/components/TreeView/TreeView.tsx
packages/react-core/src/components/TreeView/TreeViewListItem.tsx
packages/react-core/src/components/TreeView/__tests__/TreeView.test.tsx
packages/react-core/src/components/TreeView/__tests__/__snapshots__/TreeView.test.tsx.snap
packages/react-core/src/components/TreeView/examples/TreeView.md
packages/react-integration/demo-app-ts/src/components/demos/TreeViewDemo/TreeViewDemo.tsx

Resolves #4799.
Relevant core change: https://github.com/patternfly/patternfly/pull/3522
Allows any arbitrary JSX to be used in the `action` prop on a TreeViewListItem, wrapping it in a plain div with `.pf-c-tree-view__action` instead of a button. Replaces the existing examples which pass bare icons to this prop with buttons containing those icons.
This makes it possible to render a `<Dropdown>` in the action container of a tree view item without resulting in a button-in-a-button.
BREAKING CHANGES: existing consumers who want to keep the previous behavior must wrap the contents of their `action` in a `<Button>` and pass the values of their `actionProps` directly to the button.

TreeView: Replace button wrapper around actions with a div

---

packages/react-core/src/components/ToggleGroup/ToggleGroupItem.tsx
packages/react-core/src/components/ToggleGroup/ToggleGroupItemElement.tsx
packages/react-core/src/components/ToggleGroup/__tests__/ToggleGroup.test.tsx
packages/react-core/src/components/ToggleGroup/__tests__/ToggleGroupItemElement.test.tsx
packages/react-core/src/components/ToggleGroup/__tests__/__snapshots__/ToggleGroup.test.tsx.snap
packages/react-core/src/components/ToggleGroup/__tests__/__snapshots__/ToggleGroupItemElement.test.tsx.snap
packages/react-core/src/components/ToggleGroup/examples/ToggleGroup.md
packages/react-integration/demo-app-ts/src/components/demos/ToggleGroupDemo/ToggleGroupDemo.tsx

**What**: Closes #4716 
I am still not sure whether the text can be passed through the `children` or the `text` props.
WDYT?
//cc @mcoker

feat(toggleGroup): add suport to text + icon

---

CONTRIBUTING.md
packages/react-integration/cypress/integration/button.spec.ts
packages/react-integration/cypress/support/index.js
packages/react-integration/demo-app-ts/src/components/demos/ButtonDemo/ButtonDemo.tsx
packages/react-integration/package.json
yarn.lock

This PR integrates [cypress-tab-plugin](https://github.com/Bkucera/cypress-plugin-tab) and extends integration tests for Button component to ensure keyboard interactions work as expected. It also fixes a broken link in the contributing guidelines page.
**What**: Steps toward closing https://github.com/patternfly/patternfly-react/issues/3953

chore(tests): add keyboard interactivity test for button

---

packages/react-core/src/components/Form/Form.tsx
packages/react-core/src/components/Form/FormAlert.tsx
packages/react-core/src/components/Form/FormGroup.tsx
packages/react-core/src/components/Form/__tests__/Form.test.tsx
packages/react-core/src/components/Form/__tests__/FormAlert.test.tsx
packages/react-core/src/components/Form/__tests__/FormGroup.test.tsx
packages/react-core/src/components/Form/__tests__/__snapshots__/Form.test.tsx.snap
packages/react-core/src/components/Form/__tests__/__snapshots__/FormAlert.test.tsx.snap
packages/react-core/src/components/Form/__tests__/__snapshots__/FormGroup.test.tsx.snap
packages/react-core/src/components/Form/examples/Form.md
packages/react-core/src/components/Form/index.ts

**What**: Closes #4958 
FormAlert component - used for wrapping Alerts at the top of a form. There is no styles attached to the `.pf-c-form__alert` component. So it does not exist in react-styles.
isLimitWidth - can be put on the Form component to limit the max-width of the whole form.
the prop name could probably be better? `helperTextIsBeforeField`

feat(Form): add FormAlert, isLimitWidth, and allow helper text above field

---

packages/react-core/src/components/DataList/DataList.tsx
packages/react-core/src/components/DataList/__tests__/DataList.test.tsx
packages/react-core/src/components/DataList/__tests__/Generated/__snapshots__/DataList.test.tsx.snap
packages/react-core/src/components/DataList/__tests__/__snapshots__/DataList.test.tsx.snap
packages/react-core/src/components/DataList/examples/DataList.md

feat(DataList): expose grid modifiers as properties

---

packages/react-core/src/components/Alert/Alert.tsx
packages/react-core/src/components/NotificationDrawer/NotificationDrawerGroup.tsx
packages/react-core/src/components/NotificationDrawer/NotificationDrawerListItemHeader.tsx
packages/react-core/src/components/NotificationDrawer/examples/NotificationDrawer.md
packages/react-integration/cypress/integration/alert.spec.ts
packages/react-integration/cypress/integration/notificationdrawerbasic.spec.ts
packages/react-integration/cypress/integration/notificationdrawergroups.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/AlertDemo/AlertDemo.tsx
packages/react-integration/demo-app-ts/src/components/demos/NotificationDrawerDemo/NotificationDrawerBasicDemo.tsx
packages/react-integration/demo-app-ts/src/components/demos/NotificationDrawerDemo/NotificationDrawerGroupsDemo.tsx

**What**:   Added tooltips to truncated titles for Alert, NotificationDrawerListItemHeader and NotificationDrawerGroup.
Added truncatedTitle Prop to demo app and updated integration test
Closes #4760 
Closes #4752

fix(Alert, NotificationDrawer): Added tooltips to truncated titles

---

packages/react-core/src/components/Page/Page.tsx
packages/react-core/src/components/Page/PageBreadcrumb.tsx
packages/react-core/src/components/Page/PageGroup.tsx
packages/react-core/src/components/Page/PageNavigation.tsx
packages/react-core/src/components/Page/PageSection.tsx
packages/react-core/src/components/Page/__tests__/Page.test.tsx
packages/react-core/src/components/Page/__tests__/PageBreadcrumb.test.tsx
packages/react-core/src/components/Page/__tests__/PageGroup.test.tsx
packages/react-core/src/components/Page/__tests__/PageNavigation.test.tsx
packages/react-core/src/components/Page/__tests__/PageSection.test.tsx
packages/react-core/src/components/Page/__tests__/__snapshots__/Page.test.tsx.snap
packages/react-core/src/components/Page/__tests__/__snapshots__/PageBreadcrumb.test.tsx.snap
packages/react-core/src/components/Page/__tests__/__snapshots__/PageGroup.test.tsx.snap
packages/react-core/src/components/Page/__tests__/__snapshots__/PageNavigation.test.tsx.snap
packages/react-core/src/components/Page/__tests__/__snapshots__/PageSection.test.tsx.snap
packages/react-core/src/components/Page/examples/Page.md
packages/react-core/src/components/Page/index.ts
packages/react-core/src/demos/Page/Page.md
packages/react-integration/demo-app-ts/src/components/demos/PageDemo/PageBreadcrumbAndTertiaryNavDemo.tsx

**What**: Closes #4962
Adds two methods for grouping to prevent potentially breaking changes.
Firstly, you can group the tertiary nav and breadcrumb by using `isTertiaryNavGrouped` and `isBreadcrumbGrouped` along with `additionalGroupedContent` and `groupProps` to provide other sections to be included in that same grouping and group props respectively. The group will be the first element, and will be followed by whatever was not grouped (by leaving out its flag), followed by the Page children.
Alternatively (and maybe the 'breaking way'), you can use the new components `PageBreadcrumb` and `PageNavigation` along with `PageGroup` directly and pass everything to the `Page` via the children. This method would also let the user control the order of components in the group containing the …

Page section enhancements

---

GETTING-STARTED.md
packages/react-docs/README.md
packages/react-docs/RELEASE-NOTES.md

**What**: Update some MD files to reflect changes to the repo.
- Remove storybook section since PF3 is no longer on the `master` branch
- Remove Gatsby since react-docs no longer uses it
- Update testing to cover more Jest details as well as Cypress basics
- Generalize linting section for our different linters instead of copy/pasting ESLint documentation for out-of-date rules
- Update react-docs' README to reflect new webpack-based theme
- Remove references to Gatsby

docs(getting-started): update getting-started.md

---

packages/react-table/src/components/Table/HeaderCellInfoWrapper.tsx
packages/react-table/src/components/Table/base/header-row.tsx
packages/react-table/src/components/Table/base/merge-props.ts
packages/react-table/src/components/Table/examples/Table.md
packages/react-table/src/components/Table/utils/decorators/info.tsx
packages/react-table/src/components/Table/utils/transformers.tsx

**What**: Closes https://github.com/patternfly/patternfly-react/issues/4810
Adds the `info` transform that should be used instead of the previous `header` object to add tooltip/popover, although that will still work.
The transform will make it easier in combination with sortable to combine the classes (`pf-m-help` and `pf-m-sortable`) on the `th` and compose the children together at the same time

table info transform

---

packages/react-core/src/components/Form/examples/Form.md

This PR adds a missing prop `fieldId` from the react Form component docs page. Should improve the experience for people when copy/pasting from the docs into their source code.
Closes: #5079

fix(docs): add missing fieldId prop in sample code

---

packages/react-core/src/components/DataList/DataListItem.tsx
packages/react-core/src/components/DataList/examples/DataList.md

**What**: Closes #5048. Closes #5046. Prevents moving the row if `isDisabled` is passed to the button, but other rows can be moved which in turn move the disabled row.
I'm not sure what intended behavior is and I think it was a mistake to expose `isDisabled` on `DataListDragButton` which really should be on `DataListItem`. `isDisabled` on a button doesn't quite capture that the entire **row** shouldn't be draggable nor that other rows shouldn't be able to occupy its index.

fix(datalist): respect isDisabled for dragging

---

packages/react-core/src/components/Skeleton/examples/Skeleton.md

**What**: Closes #5071
I'm noticing that when I created the screenreaderText prop, I should have added it to all existing examples and shown the custom variations that could exist in our examples.

fix(Skeleton): Update skeleton examples

---

packages/react-core/src/components/Card/examples/Card.md
packages/react-integration/cypress/integration/card.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/CardDemo/CardDemo.tsx

**What**: Steps toward closing https://github.com/patternfly/patternfly-react/issues/3953
This PR adds keyboard interactivity test for Card component, ensuring its selectable and that the selected state can be trigger by keyboard events. It also cleans up the docs for Card by removing imported components that were not being used in a few of the examples.

chore(card): add keyboard interaction a11y test, clean up docs

---

packages/react-docs/RELEASE-NOTES.md
packages/react-docs/UPGRADE-GUIDE.md
packages/react-docs/patternfly-docs.config.js

See original issue https://github.com/patternfly/patternfly-org/issues/2200
Closes #5090 
This PR:
- removes Get Started nav section from the workspace
- adds Developer Resources nav section to the workspace
- moves Release notes & Upgrade guide to Developer Resources

remove Get Started, add Developer Resources, move release notes & upgrade guide

---

packages/react-core/src/components/Divider/examples/Divider.md
packages/react-integration/cypress/integration/form.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/FormDemo/FormDemo.tsx

**What**: Steps toward closing https://github.com/patternfly/patternfly-react/issues/3953
This PR adds more cypress tests to the Forms demo to verify basic keyboard interactions are in place. I did notice that cypress has a hard time working with our Form controls. Things like the cypress tab plugin do not successfully tab around the typeahead multiselect (and forms in general) and using trigger/type functions to press enter were also inconsistent. Despite this, I was able to add some useful tests.
For checkbox, I wanted to verify that pressing the spacebar would check/uncheck the box but support for spacebar seems incomplete in cypress. The functionality does of course work in our components, just that after spending a couple hours trying to get cypress to verify this, I had to call a …

chore(form): add more tests around keyboard interactivity in forms

---

packages/react-integration/cypress/integration/modal.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/ModalDemo/ModalDemo.tsx

**What**: Steps toward closing https://github.com/patternfly/patternfly-react/issues/3953
This PR adds adds a couple of new tests for modal which test to ensure focustrap is working as expected as well as that pressing escape key with an open modal would close it. I spent some time trying to also verify that pressing enter on the close button (or cancel/confirm) would also close the modal, but for some reason the trigger/type functions for cypress didn't actually close the modal. I tried several combinations of the following:
`....trigger('keydown', { keyCode: 13, which: 13 });`
`....type('{enter}')`
Any idea why these won't simulate the keypress event? The functionality does obviously work, just that cypress can't seem to invoke it. I could cheap out and go for `click()` which works …

chore(modal): add/update test cypress tests for modal

---

packages/react-core/src/components/Toolbar/Toolbar.tsx
packages/react-core/src/components/Toolbar/ToolbarChipGroupContent.tsx
packages/react-core/src/components/Toolbar/examples/Toolbar.md

**What**: Closes #4903 and #5117 
An actual variant is not needed to allow for a 'collapsed' toolbar. 
Toggle groups will always be collapsed if a breakpoint is not provided.
Added 'all' option for the `collapseListedFiltersBreakpoint` prop (since it's set to 'lg' by default and I'm avoiding a breaking change).
reorganized how the written text in the examples page is laid out and cleaned up the `stacked` example since on Patternfly.org, the new smaller content width was causing it to wrap. May need someone on Org to verify it wont wrap any more.

chore(Toolbar): small tweaks

---

packages/react-charts/package.json
packages/react-charts/src/components/Chart/__snapshots__/Chart.test.tsx.snap
packages/react-charts/src/components/ChartAxis/ChartAxis.tsx
packages/react-charts/src/components/ChartAxis/__snapshots__/ChartAxis.test.tsx.snap
packages/react-charts/src/components/ChartBar/__snapshots__/ChartBar.test.tsx.snap
packages/react-charts/src/components/ChartBullet/ChartBulletGroupTitle.tsx
packages/react-charts/src/components/ChartContainer/__snapshots__/ChartContainer.test.tsx.snap
packages/react-charts/src/components/ChartCursorContainer/__snapshots__/ChartCursorContainer.test.tsx.snap
packages/react-charts/src/components/ChartCursorTooltip/ChartCursorTooltip.tsx
packages/react-charts/src/components/ChartCursorTooltip/__snapshots__/ChartCursorFlyout.test.tsx.snap
packages/react-charts/src/components/ChartCursorTooltip/__snapshots__/ChartCursorTooltip.test.tsx.snap
packages/react-charts/src/components/ChartDonutUtilization/ChartDonutUtilization.tsx
packages/react-charts/src/components/ChartLegendTooltip/ChartLegendTooltip.tsx
packages/react-charts/src/components/ChartLegendTooltip/ChartLegendTooltipContent.tsx
packages/react-charts/src/components/ChartLegendTooltip/__snapshots__/ChartLegendTooltip.test.tsx.snap
packages/react-charts/src/components/ChartLine/__snapshots__/ChartLine.test.tsx.snap
packages/react-charts/src/components/ChartPie/__snapshots__/ChartPie.test.tsx.snap
packages/react-charts/src/components/ChartScatter/__snapshots__/ChartScatter.test.tsx.snap
packages/react-charts/src/components/ChartStack/__snapshots__/ChartStack.test.tsx.snap
packages/react-charts/src/components/ChartThreshold/__snapshots__/ChartThreshold.test.tsx.snap
packages/react-charts/src/components/ChartTooltip/ChartTooltip.tsx
packages/react-charts/src/components/ChartTooltip/__snapshots__/ChartTooltip.test.tsx.snap
packages/react-charts/src/components/ChartUtils/chart-theme.ts
packages/react-charts/src/components/ChartUtils/chart-tooltip.ts
packages/react-charts/src/components/ChartVoronoiContainer/__snapshots__/ChartVoronoContainer.test.tsx.snap
packages/react-console/package.json
yarn.lock

**What**: The latest release of Victory contains some accessibility function I need to use. When I tried to upgrade the version of Victory packages in `react-chart`, I found that we only need to keep the `victory` dependency in `package.json` file and we could remove all the other `victory-` dependencies. This will simplify the upgrade of `victory` package in the future.

feat(packages): bump Victory package

---

packages/react-core/src/components/Toolbar/Toolbar.tsx
packages/react-core/src/components/Toolbar/__tests__/ToolbarToggleGroup.test.tsx
packages/react-core/src/components/Toolbar/__tests__/__snapshots__/ToolbarToggleGroup.test.tsx.snap

**What**: Closes #4900
Adds a flag `usePageInsets` that indicates the toolbar should use Page's insets.

feat(Toolbar): add flag to match page insets

---

packages/react-catalog-view-extension/package.json
packages/react-charts/package.json
packages/react-console/package.json
packages/react-core/package.json
packages/react-core/src/components/ActionList/ActionListItem.tsx
packages/react-core/src/components/TreeView/TreeViewListItem.tsx
packages/react-core/src/components/TreeView/__tests__/__snapshots__/TreeView.test.tsx.snap
packages/react-datetime/package.json
packages/react-docs/package.json
packages/react-icons/package.json
packages/react-styles/package.json
packages/react-table/package.json
packages/react-tokens/package.json
yarn.lock

**What**: Bumps core and fixes broken CI build.
**Additional issues**: I believe `pf-c-action-list__item` should be hardcoded (see https://github.com/patternfly/patternfly/pull/3662) and that `pf-m-expandable` on TreeView can be removed (see https://github.com/patternfly/patternfly/pull/3661).

bump core, fix react-console version

---

packages/react-console/src/components/AccessConsoles/AccessConsoles.tsx
packages/react-console/src/components/AccessConsoles/__tests__/AccessConsole.test.tsx
packages/react-console/src/components/AccessConsoles/examples/AccessConsoles.md
packages/react-console/src/components/DesktopViewer/ConnectWithRemoteViewer.tsx
packages/react-console/src/components/DesktopViewer/__tests__/DesktopViewer.test.tsx
packages/react-console/src/components/DesktopViewer/consoleDescriptorGenerator.tsx
packages/react-console/src/components/SerialConsole/SerialConsole.tsx
packages/react-console/src/components/SerialConsole/__tests__/SerialConsole.test.tsx
packages/react-console/src/components/SpiceConsole/SpiceConsole.tsx
packages/react-console/src/components/VncConsole/VncConsole.tsx
packages/react-console/src/components/common/constants.tsx
packages/react-console/src/components/index.ts
packages/react-styles/src/css/components/Consoles/SerialConsole.css
packages/react-styles/src/css/components/Consoles/VncConsole.css
packages/react-styles/src/css/components/Consoles/xterm.css

**What**: Not all webpack loaders support CSS imports

fix(console): remove css imports

---

packages/react-core/src/components/Checkbox/Checkbox.tsx

Our Checkbox component supports a null value for `isChecked`, in order to show the indeterminate (partially-checked) state. We demonstrate this in the Controlled example of the checkbox docs page.
However, when trying to pass this null value into the prop in a TypeScript app, TS gives an error since the type of this prop is `boolean` (null is not assignable). This doesn't cause an issue in our examples since they are plain JS.
This PR simply changes the `isChecked` prop type to `boolean | null` so TS won't complain when a null value is passed.

Fix TS type for isChecked prop of Checkbox so it allows null (indeterminate)

---

packages/react-integration/cypress/integration/tableeditablecompoundexpandable.spec.ts
packages/react-integration/demo-app-ts/src/Demos.ts
packages/react-integration/demo-app-ts/src/components/demos/TableDemo/TableEditableCompoundExpandableDemo.tsx
packages/react-integration/demo-app-ts/src/components/demos/index.ts
packages/react-table/src/components/Table/Table.test.tsx
packages/react-table/src/components/Table/utils/decorators/compoundExpand.tsx

This PR fixes an issue where when selecting a compound expandable table cell, when the table is also "editable", would cause a full page refresh instead of expanding the cell as expected. It's a patch for https://github.com/patternfly/patternfly-react/issues/5118
This is happening because when the table is "editable" the table is wrapped in a form, and the compoundExpand buttons do not have a type attribute set, and the default action of selecting a button when inside of a form is to attempt to submit the form.
To reproduce the issue, add `onRowEdit={() => {}}` to a compound expandable table and then select one of the expandable cells. Notice it attempts to submit the form to the current url and a "?" query param token is added to the url.
The fix is simply to add `type="button"` to those …

fix(table): set button type on compoundExpand transform button

---

packages/react-core/src/components/TreeView/TreeViewListItem.tsx
packages/react-core/src/components/TreeView/examples/TreeView.md

Currently, in order to show an indeterminate (partially-checked) checkbox in a TreeViewListItem, the consumer has to use a ref to set the element's `indeterminate` prop. This is what we already do internally in our regular Checkbox when the consumer passes a null value for `isChecked`. This PR adds support for rendering this indeterminate state just by passing a null value for `checkProps: { checked }` on a tree item instead of using a ref. I updated the existing tree view example to use this approach instead of the ref.
This isn't a breaking change: if a consumer is already using their own ref to set this property, that will still work.
I considered refactoring the tree view to use our `<Checkbox>` component instead of a native `<checkbox>` so we wouldn't have to duplicate this logic in …

TreeView: add support for indeterminate checkboxes without requiring consumer to use refs

---

packages/react-table/src/components/Table/Body.tsx
packages/react-table/src/components/Table/examples/Table.md

**What**: Closes https://github.com/patternfly/patternfly-react/issues/4835, Closes https://github.com/patternfly/patternfly-react/issues/5076
There was a naming collision between the internal Table's rowKey which was named `id`, and tables that have an `ID` column

fixes issues related to tables with an ID column

---

packages/eslint-plugin-patternfly-react/lib/rules/import-tokens-icons.js

**What**:
Importing from `@patternfly/react-icons/createIcon` is changed to `@patternfly/react-icons/dis/js/non-existed-file` by eslint.
This patch fixes this problem by checking if there are imports from '@patternfly/react-icon/createIcon` and change their source to `@patternfly/react-icons/dis/js/createIcon`.
// cc @redallen

fix(eslint): fix @patternfly/react-icons/createIcon differently

---

packages/react-datetime/package.json
packages/react-datetime/src/components/CalendarMonth/CalendarMonth.tsx
packages/react-datetime/src/components/CalendarMonth/examples/CalendarMonth.md
packages/react-datetime/src/components/DatePicker/DatePicker.tsx
packages/react-datetime/src/components/DatePicker/__tests__/DatePicker.test.tsx
packages/react-datetime/src/components/DatePicker/__tests__/__snapshots__/DatePicker.test.tsx.snap
packages/react-datetime/src/components/DatePicker/examples/DatePicker.md
packages/react-datetime/src/helpers/index.ts
packages/react-datetime/src/helpers/locales.ts
packages/react-datetime/src/index.ts
yarn.lock

**What**: Remove `date-fns` and amend API to be more flexible given feedback from @nicolethoen and @karelhala .
- Change default formatting/parsing to `yyyy-MM-dd`.
- Allows relying on default browser formatting/parsing in DatePicker via native date methods like `date.toISOString().substring(0, 10)` and ``new Date(`${val}T00:00:00`)``.
- Allows CalendarMonth to render any ReactNodes via format functions:
```js
monthFormat = date => date.toLocaleDateString(locale, { month: 'long' }),
weekdayFormat = date => date.toLocaleDateString(locale, { weekday: 'narrow' }),
longWeekdayFormat = date => date.toLocaleDateString(locale, { weekday: 'long' }),
buttonFormat = date => date.getDate()
```
- `locale` defaults to the browser's locale giving decent i18n out of the box. We can force `en-US` to make …

fix(datepicker): remove date-fns and allow more customization

---

packages/react-core/src/components/Form/examples/Form.md

**What**: This PR updates the Form component demo page to fix a small issue in the demo where event bubbling causes the Popover to launch unexpectedly when pressing enter key while focus is on certain form controls within the form by adding `type="button"` to the button element that launches the Popover. It also adds some missing whitespace so certain words are not jumbled, and finally, updates id's to be unique across multiple form examples to clear the console warnings.
Should help close https://github.com/patternfly/patternfly-react/issues/5171
@jschuler ping - and thanks for the help nailing down that Popover issue!

fix(form-demo): tidy form demo examples

---

scripts/promote.sh

**What**: Closes #5169 
This PR adds the `react-datetime` package to the promote script.

added react-datetime to promote script

---

packages/react-datetime/package.json
packages/react-datetime/src/components/CalendarMonth/CalendarMonth.tsx
packages/react-datetime/src/components/CalendarMonth/examples/CalendarMonth.md
packages/react-datetime/src/components/DatePicker/DatePicker.tsx
packages/react-datetime/src/components/DatePicker/__tests__/__snapshots__/DatePicker.test.tsx.snap
packages/react-datetime/src/components/DatePicker/examples/DatePicker.md
packages/react-datetime/src/demos/DateRangePicker.md
packages/react-docs/patternfly-docs.source.js

**What**: Closes #4732
Bugfixes:
- Remove `'@patternfly/patternfly/patternfly-date-picker.css'` left over from `flatpickr` implementation and remove unused `@patternfly/patternfly` dependency
- Allow `value={null}` or other invalid dates in DatePicker and CalendarMonth
- Memoize weeks, days, and validity of days to only recompute when the year, month, or weekStart changes. Scrolling between months and years is noticeably faster.
- Only validate DatePicker `onBlur` per @mcarrano's suggestion
- Don't validate if field was untouched per @nicolethoen's suggestion
- Clone dates before passing them to consumers (before consumers could mutate component state since dates are mutable)
- Add `ariaLabel` props to `CalendarMonth` per @nicolethoen 
Demo …

feat(date-picker): bugfixes and add range picker demo

---

jest.config.js
packages/react-console/package.json
packages/react-console/src/components/VncConsole/VncActions.tsx
packages/react-console/src/components/VncConsole/VncConsole.tsx
packages/react-console/src/components/VncConsole/__tests__/__snapshots__/VncConsole.test.tsx.snap
packages/react-console/src/components/VncConsole/__tests__/__snapshots__/VncConsoleActions.test.tsx.snap
packages/react-console/src/declarations.d.ts
packages/react-docs/package.json
packages/react-styles/src/css/components/Consoles/VncConsole.css
yarn.lock

novnc-core does not really keep up to date with the latest releases, so
let's just keep depending on the original package.
None of the packages have correct or up to date typings so just add the
types in our declarations file.
Closes #5157

fix(VncConsole): replace novnc-core usage with the original @novnc/novnc

---

packages/react-core/src/components/Drawer/Drawer.tsx
packages/react-core/src/components/Drawer/DrawerPanelContent.tsx
packages/react-core/src/components/Drawer/__tests__/Drawer.test.tsx
packages/react-core/src/components/Drawer/__tests__/Generated/__snapshots__/Drawer.test.tsx.snap
packages/react-core/src/components/Drawer/__tests__/Generated/__snapshots__/DrawerPanelContent.test.tsx.snap
packages/react-core/src/components/Drawer/__tests__/__snapshots__/Drawer.test.tsx.snap
packages/react-core/src/components/Drawer/examples/Drawer.md
packages/react-integration/cypress/integration/drawer.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/DrawerDemo/DrawerDemo.tsx

**What**: Closes #5050 
To enable resize, `isResizable` is passed to the `DrawerPanelContent` component.
Other additions:
- `minSize` / `maxSize` properties to customize resize limits. Defaults to the bounds of the parent container.
- `increment` property to customize keyboard size jump per keystroke. Defaults to `5px`.
- `resizeAriaLabel` / `resizeAriaDescribedBy` properties to customize labelling of the splitter div.
Keyboard interaction:
Tab over to the splitter and press `space` to begin resizing using the arrow keys. Press `enter` or `escape` to stop resizing.
@mcoker I've implemented the resizing by overriding the `--pf-c-drawer__panel--FlexBasis` css variable, since it appears height/width won't change without it. Is that all right or would there be a better class/css variable? …

feat(Drawer): add splitter feature

---

packages/react-core/src/components/TextArea/TextArea.tsx
packages/react-core/src/components/TextArea/__tests__/Generated/__snapshots__/TextArea.test.tsx.snap
packages/react-core/src/components/TextArea/__tests__/TextArea.test.tsx
packages/react-core/src/components/TextArea/__tests__/__snapshots__/TextArea.test.tsx.snap
packages/react-core/src/components/TextArea/examples/TextArea.md
packages/react-integration/cypress/integration/textarea.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/TextAreaDemo/TextAreaDemo.tsx

**What**: Closes #5068 
It is a breaking change. If someone is using `disabled` in the props then after updating with this change Typescript will show an error message saying `disabled` is not a valid props of `TextArea`.

feat(textarea): support isDisabled

---

packages/react-core/src/components/TextInput/examples/TextInput.md

A small nitpick change to one of the examples in `TextInput`:
Remove redundant components: `React.Fragment` and `Button`
closes: #5220

fix(textinput): remove Button and React.Fragment from the ref example

---

packages/react-core/scripts/copyStyles.js

Update react-core's `copyStyles.js` generate script to generate both the pure PF4 `base.css` file and the PF3+PF4 no reset
`base-no-reset.css` file.  This will allow a project using both PF3-react and PF4-react on the same page without resorting to using sass or falling back to PF4's `patternfly-no-reset.css`.
Before this PR, if a project uses PF3 and PF4, and doesn't want to adopt sass, the css imports would be:
```jsx
import 'patternfly-react/dist/css/patternfly-react.css' // PF3-react
import '@patternfly/patternfly/patternfly-no-reset.css' // PF4
```
After this PR is merged, projects just using PF4 can still import the `base.css` normally:
```jsx
import '@patternfly/react-core/dist/style/base.css'
```
But, now projects using PF3 and PF4 can use the new react-core `base-no-reset.css` …

feat(react-core): Update react-core copyStyles.js

---

packages/react-core/src/components/DualListSelector/DualListSelector.tsx
packages/react-core/src/components/DualListSelector/DualListSelectorPane.tsx
packages/react-core/src/components/DualListSelector/DualListSelectorTree.tsx
packages/react-core/src/components/DualListSelector/DualListSelectorTreeItem.tsx
packages/react-core/src/components/DualListSelector/__tests__/DualListSelector.test.tsx
packages/react-core/src/components/DualListSelector/__tests__/__snapshots__/DualListSelector.test.tsx.snap
packages/react-core/src/components/DualListSelector/examples/DualListSelector.md
packages/react-core/src/components/DualListSelector/treeUtils.ts
packages/react-core/src/components/TreeView/TreeView.tsx
packages/react-core/src/components/TreeView/examples/TreeView.md
packages/react-integration/cypress/integration/duallistselectortree.spec.ts
packages/react-integration/demo-app-ts/src/Demos.ts
packages/react-integration/demo-app-ts/src/components/demos/DualListSelector/DualListSelectorTreeDemo.tsx
packages/react-integration/demo-app-ts/src/components/demos/index.ts

**What**: Closes #5102 
To swap over to using trees, add `isTree` to the `DualListSelector` and update the data structure accordingly. The data is expected to have a `text` attribute to display the content of the item, and this property is used to control selection/checking/etc. The structure is similar to TreeView, but uses `text` in place of `name`. It might be better to swap to using an `id` prop instead of `text`, I haven't decided.
The prop `hasChecks` added to `DualListSelector` will add checkboxes to every option. Alternately, adding a `hasCheck` property to an option will give the individual option a checkbox. Badges are added individually at the moment with a `hasBadge` property added to an option, but if needed a similar apply-to-all property can be added.
Keyboard interaction …

feat(DualListSelector): add support for trees and checkboxes

---

packages/react-core/src/components/CalendarMonth/CalendarMonth.tsx
packages/react-styles/scripts/generateClassMaps.js

**What**: In some cases may fix base styles being loaded incorrectly:
**Additional issues**: React-styles shouldn't reexport `base` styles because `react-core/dist/styles/base.css` already exports them. Including them from react-styles just includes the CSS twice which can cause issues.

fix(calendar-month): rely on base styles from react-core/dist/styles/base.css

---

packages/react-topology/src/layouts/BaseLayout.ts
packages/react-topology/src/layouts/ColaLayout.ts

**What**: 
Closes https://github.com/patternfly/patternfly-react/issues/5248
**Description**
Update topology cola layout to run one round of force simulation after the cola layout when nodes are added. This will slightly adjust the graph to accommodate new nodes preventing initial overlap.

fix(topology): adjust topology node layout when new nodes are added

---

packages/react-docs/RELEASE-NOTES.md

Release notes versions bump after merging https://github.com/patternfly/patternfly-react/pull/5262 to fix sentence casing issue.  Also adds release note for https://github.com/patternfly/patternfly-react/pull/5249 which was merged in the meantime.

2020.16 Release notes patch

---

packages/react-core/src/components/Select/Select.tsx

**What**: Closes #5257
When a `<Select>` has a disabled options on top of the options list,
`this.refCollection[0]` will be an array in the shape of `[null, null]`.
This means that trying to call `this.refCollection[0][0].focus()`
will fail with TypeError in this case.
This patch fixes this issue, by finding the first non-null ref in the
collection and focusing on it, instead of assuming the first ref in the
collection is valid.

fix(Select): fix crash when opened using Enter with disabled options

---

packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/TopologyPackage.tsx
packages/react-styles/src/css/components/Topology/topology-components.css
packages/react-topology/src/components/contextmenu/ContextSubMenuItem.tsx
packages/react-topology/src/components/popper/Popper.tsx

**What**:
Fixes an issue where a topology context menu's sub menus would grow the viewport causing a window scrollbar to appear when the submenu would not fit on the screen.
**Solution**:
Fix the class on the sub menu dropdown and change the overflow prevention to be on the viewport rather than window.
Added context menus to the TopologyPackage demo for testing purposes.
Also fixes the submenu indicator padding so load order is not important.

fix(topology): Prevent context sub menus from overflowing viewport

---

packages/react-charts/src/components/ChartDonut/ChartDonut.tsx
packages/react-charts/src/components/ChartDonutUtilization/ChartDonutThreshold.tsx
packages/react-charts/src/components/ChartDonutUtilization/ChartDonutUtilization.tsx
packages/react-charts/src/components/ChartGroup/ChartGroup.tsx
packages/react-charts/src/components/ChartLegend/ChartLegend.tsx
packages/react-charts/src/components/ChartPie/ChartPie.tsx
packages/react-charts/src/components/ChartStack/ChartStack.tsx
packages/react-charts/src/components/ChartUtils/chart-tooltip.ts

The chart `colorScale` props use Victory's `ColorScalePropType` type, which was previously defined as a string array. The `ColorScalePropType` type is now defined as:
`"grayscale", "qualitative", "heatmap", "warm", "cool", "red", "green", "blue" | string[]`
PatternFly charts will never use these color string types as they only have meaning for Victory's 'material' and 'grayscale' themes.
Note: `colorScale` still accepts a string array, just as before. Just not the unused strings; "grayscale", "qualitative", "heatmap" etc.
Fixes https://github.com/patternfly/patternfly-react/issues/5129

fix(charts): Incorrect colorScale prop type

---

packages/react-core/src/components/JumpLinks/JumpLinks.tsx
packages/react-core/src/components/JumpLinks/JumpLinksItem.tsx
packages/react-core/src/demos/JumpLinks.md

**What**: Closes #5218
**Additional issues**: Previously wasn't working because `id`s [can't include spaces.](https://www.quora.com/jQuery-How-can-I-select-a-div-whose-id-contains-a-space)

fix(jumplinks): allow hrefs with spaces

---

packages/react-core/src/components/ContextSelector/__tests__/ContextSelectorItem.test.tsx

**What**: closes #5309 
Fix context selector warning in unit tests.

chore(contextselector): remove isHovered from item unit tests

---

packages/react-core/src/components/ToggleGroup/ToggleGroupItem.tsx
packages/react-core/src/components/ToggleGroup/__tests__/__snapshots__/ToggleGroup.test.tsx.snap

**What**: Closes #5195 
Added `type="button"` to button in ToggleGroupItem.
Cf https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button
"If your buttons are not for submitting form data to a server, be sure to set their type attribute to button. Otherwise they will try to submit form data and to load the (nonexistent) response, possibly destroying the current state of the document."
//cc @tlabaj

fix(ToggleGroup): Fix bug with ToggleGroupItem button being clicked in form in modal closing modal

---

packages/react-core/src/components/Drawer/examples/Drawer.md
packages/react-core/src/demos/PrimaryDetail.md

**What**: Closes #4807 .
Fixed this issue in both [Primary detail simple list in card](https://www.patternfly.org/v4/demos/primary-detail/react-demos/primary-detail-simple-list-in-card) and [Primary detail data list in card](https://www.patternfly.org/v4/demos/primary-detail/react-demos/primary-detail-data-list-in-card), where we use static drawer. When on mobile view, we could use `isExpand` to control the panel. Also I add the `DrawerCloseButton`, which will only be shown on mobile view to close the panel.

fix(primary-detail-demo): enable static drawer open on mobile view

---

packages/react-core/src/components/Wizard/Wizard.tsx
packages/react-integration/cypress/integration/wizard.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/WizardDemo/WizardDemo.tsx

**What**: Closes #5254 
//cc @MariaAga

fix(Wizard): set a custom width to the wizard modal

---

packages/react-core/src/components/ChipGroup/ChipGroup.tsx
packages/react-core/src/components/ChipGroup/__tests__/__snapshots__/ChipGroup.test.tsx.snap
packages/react-core/src/components/ChipGroup/examples/ChipGroup.md
packages/react-core/src/components/Select/__tests__/__snapshots__/Select.test.tsx.snap
packages/react-integration/cypress/integration/chipgroupwithoverflowchipeventhandler.spec.ts
packages/react-integration/demo-app-ts/src/Demos.ts
packages/react-integration/demo-app-ts/src/components/demos/ChipGroupDemo/ChipGroupDefaultIsOpenDemo.tsx
packages/react-integration/demo-app-ts/src/components/demos/ChipGroupDemo/ChipGroupWithOverflowChipEventHandler.tsx
packages/react-integration/demo-app-ts/src/components/demos/index.ts

**What**: Closes #5190 
Adds an optional prop called `onOverflowChipClick` that, when used, calls the provided handler function when the overflow (toggle expand/collapse) chip is clicked.  
There is already an onClick prop, hence naming this differently.  Let me know if you have a better idea for a name for this prop.
//cc @tlabaj

feat(ChipGroup): Add event handler prop for overflow-chip click 

---

packages/react-core/src/components/Drawer/DrawerPanelContent.tsx
packages/react-core/src/components/Drawer/__tests__/Generated/__snapshots__/DrawerPanelContent.test.tsx.snap
packages/react-core/src/components/Drawer/__tests__/__snapshots__/Drawer.test.tsx.snap

**What**: Closes #5290
Removes the extra logic to not render the content when a panel is hidden. The panel is already hidden via the `hidden` attribute so the content should not have to also be un-rendered.

fix(Drawer): stop panel content unmounting before collapse

---

packages/react-core/src/components/Drawer/DrawerPanelContent.tsx
packages/react-core/src/components/Drawer/__tests__/Drawer.test.tsx
packages/react-core/src/components/Drawer/__tests__/__snapshots__/Drawer.test.tsx.snap
packages/react-core/src/components/Drawer/examples/Drawer.md
packages/react-integration/demo-app-ts/src/components/demos/DrawerDemo/DrawerDemo.tsx

**What**: Closes #5282
Adds `onResize` callback which will return the new size of the drawer after resizing as well as the ID of the panel (if it was given). Adds prop description for `id`.
Combined with #5313 a user may store a predetermined width and pass it with `defaultSize` to set the width of the panel when first opened. Using the `onResize` callback, this width may be updated and persisted if the page is refreshed. Or the width may remain the same to reset the panel width.

feat(Drawer): add resize callback

---

packages/react-core/src/components/Drawer/DrawerPanelContent.tsx
packages/react-docs/patternfly-docs.css.js
packages/react-styles/src/css/components/Drawer/DrawerIframe.css

**What**: Closes #5279 
Add a new class set all the iframe in that class to `pointer-events: none`. When dragging happens, add that class to the drawer and remove that class when dragging ends.

fix(drawer): fix dragging problem on iframe when resizing drawer

---

packages/react-charts/src/components/ChartUtils/chart-interactive-legend.ts

When hovering over an interactive legend item, all other datasets in the chart are muted (i.e., an opacity is applied to make them look slightly grayed out). When the cursor moves away from the legend item, the muted styles are removed. This works fine with line and area charts, but there is a problem with bar charts. It's more of an edge case, but under certain conditions, bars may remain muted.
Fixes https://github.com/patternfly/patternfly-react/issues/5377
Cost Management

Bar chart remains muted with interactive legend

---

packages/react-core/src/components/DatePicker/DatePicker.tsx
packages/react-core/src/demos/DatePicker.md

**What**: Closes #5368
**Additional issues**: Looks like when I originally implemented this I missed some pitfalls of `toISOString`, namely [timezones.](https://stackoverflow.com/questions/23593052/format-javascript-date-as-yyyy-mm-dd)

fix(datepicker): don't rely on toISOString

---

packages/react-core/src/components/Card/Card.tsx
packages/react-core/src/components/Card/__tests__/Card.test.tsx
packages/react-core/src/components/Card/examples/Card.md
packages/react-integration/cypress/integration/card.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/CardDemo/CardDemo.tsx

**What**: Closes #5334
**Additional issues**: I made an interactive modifiers example to showcase it

feat(card): add pf-m-display-lg and pf-m-rounded

---

packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx

no issue, cuz this was a quick n easy one, presently , users supplying empty states dont see em CUZ they're hidden by that showEmptyState toggle 
now ya'll see one if its provided

bug(codeeditor) Displays empty state if one is supplied 🥳

---

packages/react-core/src/components/TimePicker/TimeOption.tsx
packages/react-core/src/components/TimePicker/TimePicker.tsx

**What**: Closes #5398
**Reason**: The `onChange` function is only called in `onInputChange` function, which is only triggered when users input something. However, in `onSelect` function, we don't use `onChange` function.
To optimize the code structure, I called `onInputChange` function inside `onSelect` function because they did almost the same thing, and I removed those unused props and redundant setState functions. It works for both mouse events and keyboard events.

fix(timepicker): fix issue when clicking dropdown menu does not trigger onchange function

---

packages/react-core/src/components/DataList/DataList.tsx
packages/react-core/src/components/DataList/__tests__/Generated/__snapshots__/DataList.test.tsx.snap
packages/react-core/src/components/DataList/__tests__/__snapshots__/DataList.test.tsx.snap

**What**: Closes #5041 
//cc @mcoker

fix(datalist): use drag-over modifier instead of css style

---

packages/react-core/src/components/Select/Select.tsx
packages/react-core/src/components/Select/SelectMenu.tsx
packages/react-core/src/components/Select/SelectOption.tsx
packages/react-core/src/components/Select/SelectToggle.tsx
packages/react-core/src/components/Select/__tests__/__snapshots__/Select.test.tsx.snap

**What**: Closes #5430
**Additional issues**: I'm not sure why we were using FocusTrap to begin with in this component. Please make sure I wasn't missing anything @kmcfaul !

fix(selectmenu): don't use focus trap when no tabbable children

---

packages/react-core/src/components/Drawer/Drawer.tsx
packages/react-core/src/components/Drawer/DrawerPanelContent.tsx
packages/react-core/src/components/Drawer/__tests__/Generated/__snapshots__/Drawer.test.tsx.snap
packages/react-docs/patternfly-docs.css.js
packages/react-styles/src/css/components/Drawer/DrawerIframe.css

**What**: Closes #5419 , #5418 , #5412
Removes the transition from the style object on the panel and adds in the new CSS class to handle the property. 
Updates the local CSS class for iframes to the new core side CSS class.
Panel content will now unmount after the transition to close ends, and re-mount when the panel opens. This solves the splitter being in the tab order because it no longer exists when closed.

feat(Drawer): update transitions and content mounting

---

packages/react-core/src/components/TreeView/TreeView.tsx
packages/react-core/src/components/TreeView/TreeViewListItem.tsx
packages/react-core/src/components/TreeView/TreeViewRoot.tsx
packages/react-core/src/components/TreeView/__tests__/__snapshots__/TreeView.test.tsx.snap
packages/react-core/src/components/TreeView/index.ts
packages/react-integration/cypress/integration/treeview.spec.ts

**What**: Closes #4726
Keyboard interaction:
- `ArrowUp` and `ArrowDown` move through the list of displayed tree items
- `ArrowRight` and `ArrowLeft` respectively open and close expandable folders. Focus is moved to the first child item when a folder is opened, and focus is moved to the parent folder if the `ArrowLeft` is triggered while within a folder, or remains on the folder if already on the expanded folder.
- `ArrowRight` and `ArrowLeft` iterate through a node for the checkbox variant, and do not expand/collapse a folder (left to `Space`).
- `Space` acts as a click to expand/collapse a folder or select a leaf item (or checkbox for checkbox variants)
@jessiehuff Let me know if there's anything I'm missing or anything I should add for a11y!

feat(TreeView): add keyboard interaction

---

packages/react-core/src/components/Select/Select.tsx
packages/react-core/src/components/Select/examples/Select.md

* fixes the crash on typeahead select component when an empty string option was
passed (issue#4361)
* fixes the crash on typeahead select with custom objects example
(issue#5449)
Fixes #5449
Fixes #4361

Select(typeahead): remove onFilter function from example with custom objects

---

packages/react-core/src/components/DualListSelector/DualListSelector.tsx
packages/react-core/src/components/DualListSelector/DualListSelectorPane.tsx

The use case can be as seen in the linked issue, that the cunsumer might
need to use the left search bar to query an API for available options.
This is understandable as the list of available options can get
really long in some use-cases and in that case the API calls should only
fetch the options that are relevant to the user input.
Fixes #5436

DualListSelect: add onAvailableOptionsSelectInputChanged and onChosenOptionsSelectInputChanged

---

packages/react-core/src/components/DatePicker/DatePicker.tsx

fix(datepicker): only show non-whitespace error text

---

packages/react-core/src/components/TreeView/TreeView.tsx
packages/react-core/src/components/TreeView/TreeViewListItem.tsx
packages/react-core/src/components/TreeView/examples/TreeView.md
packages/react-integration/cypress/integration/treeview.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/TreeViewDemo/TreeViewDemo.tsx

**What**: Closes #4797
- Adds `allExpanded` prop to TreeView, allowing the override of default and internal flags for the expanded state. Set to `null` or do not pass in to allow the `defaultExpanded` prop to set the initial state.
- Adds a button to the default demo to showcase this prop, and updates the search demo to use the new prop (over `defaultExpanded`).

feat(TreeView): add flag for expand/collapse all

---

packages/react-core/src/components/CalendarMonth/CalendarMonth.tsx

fix(CalendarMonth): fix selecting month in Popover for React 17

---

packages/react-styles/src/css/components/Topology/topology-controlbar.css

**What**:
closes https://github.com/patternfly/patternfly-react/issues/5537

fix(topology): Use disabled background for control buttons when disabled

---

packages/react-core/src/components/Switch/Switch.tsx
packages/react-core/src/components/Switch/__tests__/Switch.test.tsx

When the user has not provided an 'id', `getUniqueId` is used to
generate a random one. That id is used after for the aria-labelled-by
property. Therefore when ensuring correct usage of accessibility
properties we need to check that a label is provided, not an id.
Closes #5521

fix(Switch): fix error message regarding accessibility usage

---

packages/react-core/src/components/Dropdown/InternalDropdownItem.tsx

**What**:
Closes https://github.com/patternfly/patternfly-react/issues/5544
**Description**
The ref for the dropdown menu items is being used internally. If the component being used for the dropdown item is already using the `ref` make sure it gets set as well.

fix(Topology): Fix for context sub menu placement

---

packages/react-core/src/components/Nav/NavItem.tsx
packages/react-core/src/components/Nav/__tests__/__snapshots__/Nav.test.tsx.snap

fix(NavItem): tabIndex should be passed to cloned children

---

packages/react-core/src/components/Alert/Alert.tsx
packages/react-core/src/components/Alert/__tests__/Generated/__snapshots__/Alert.test.tsx.snap
packages/react-core/src/components/Alert/__tests__/__snapshots__/Alert.test.tsx.snap
packages/react-core/src/components/Alert/examples/Alert.md
packages/react-core/src/components/AlertGroup/AlertGroup.tsx
packages/react-core/src/components/AlertGroup/__tests__/__snapshots__/AlertGroup.test.tsx.snap

**What**: Wait until the Alert is timed out AND the mouse is not over it AND the keyboard isn't focusing an element inside of it. After the mouse exits wait at least `timeoutAnimation` seconds. Closes #5489

feat(alert): don't timeout if isMouseOver

---

packages/react-core/src/components/TextArea/TextArea.tsx
packages/react-core/src/components/TextArea/examples/TextArea.md
packages/react-integration/cypress/integration/textarea.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/TextAreaDemo/TextAreaDemo.tsx

**What**: Closes #5497 using https://github.com/patternfly/patternfly/pull/3883 and https://gomakethings.com/automatically-expand-a-textarea-as-the-user-types-using-vanilla-javascript/
**Additional issues**: https://patternfly-react-pr-5568.surge.sh/components/text-area#auto-resizing

feat(textarea): add auto resizing

---

packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/TopologyDemo.tsx
packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/TopologyPackage.tsx
packages/react-styles/src/css/components/Topology/topology-side-bar.css
packages/react-topology/src/components/TopologySideBar/TopologySideBar.test.tsx
packages/react-topology/src/components/TopologySideBar/TopologySideBar.tsx
packages/react-topology/src/components/TopologySideBar/__snapshots__/TopologySideBar.test.tsx.snap
packages/react-topology/src/components/TopologyView/TopologyView.test.tsx
packages/react-topology/src/components/TopologyView/TopologyView.tsx
packages/react-topology/src/components/TopologyView/__snapshots__/TopologyView.test.tsx.snap

**What**:
Provides the ability to opt in for the resizable topology side bar. Some applications may not want another Drawer inside the topology view due to layouts which cause the view to scroll rather than only the side bar contents scroll.

fix(Topology): Allow applications to choose using resizable drawer for topology side bar

---

packages/react-core/src/components/Dropdown/Toggle.tsx
packages/react-core/src/components/Menu/DrilldownMenu.tsx
packages/react-core/src/components/Menu/Menu.tsx
packages/react-core/src/components/Menu/MenuItem.tsx
packages/react-core/src/components/Menu/MenuItemAction.tsx
packages/react-core/src/components/Menu/examples/Menu.md
packages/react-integration/cypress/integration/menu.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/MenuDemo/MenuDrilldownDemo.tsx

**What**: Closes #5144
First pass for keyboard interaction with the Menu component. May need further revision based on feedback/other edge cases I may have missed.
Generally speaking:
- `ArrowUp` and `ArrowDown` navigate menu items
- Disabled items are skipped
- `ArrowLeft` and `ArrowRight` navigate items within a menu (for actions and breadcrumbs)
- `Enter` and `Space` select menu items and control drill in/drill out for drilldown menus and drilldown breadcrumbs
For filterable menus, the filter box and menu are swapped between via using `Tab`.
For flyout menus, the flyout is opened from the flyout item using `Enter`, `Space` or `ArrowRight` then traversed normally with arrow keys. Flyout menus are closed with `Escape` or `ArrowLeft`.
Re: breadcrumbs @jessiehuff. I missed the blurb about …

feat(Menu): keyboard interaction first pass

---

packages/react-core/src/components/Nav/NavExpandable.tsx
packages/react-core/src/components/Nav/__tests__/Nav.test.tsx
packages/react-core/src/components/Nav/__tests__/__snapshots__/Nav.test.tsx.snap
packages/react-integration/demo-app-ts/src/components/demos/NavDemo/NavDemo.tsx

**What**: Closes #5592 
Removed unused ref so that the onExpand callback gets called.

fix(Navigation): Fixed so that the onExpand callback is fired

---

packages/react-core/src/components/Nav/Nav.tsx
packages/react-core/src/components/Nav/NavExpandable.tsx
packages/react-core/src/components/Nav/__tests__/__snapshots__/Nav.test.tsx.snap

**What**: Towards https://github.com/openshift/console/pull/8534 and releasing.
I think having both `<NavExpandable onExpand` and `<Nav onToggle` callbacks was a poor idea (and I'm in favor of removing `onExpand` for a boolean `managedExpand` in the future).

fix(nav): don't call onExpand twice

---

packages/react-virtualized-extension/src/components/Virtualized/examples/VirtualizedTable.md

**What**: Closes # https://github.com/patternfly/patternfly-react/issues/5626
Before:
After:

fix(react-virtualized): fix render of demo data so the table cells don't repeat static text

---

packages/react-core/src/components/Select/examples/Select.md
packages/react-core/src/components/Select/selectConstants.tsx

**What**: Closes #5340 .
There should not be a variant named `panel`. When user want to use the customized Select panel, they only need to pass the `customContent` into Select component.
Update the doc as well. users don't need to pass `variant` when they want to use Select Panel.

fix(select): remove panel from select variants

---

packages/react-icons/scripts/writeIcons.js
packages/react-tokens/scripts/writeTokens.js

**What**: Speed up time from making a change to seeing it by up to 3x. Towards #https://github.com/webpack/webpack/issues/13107
Before:
```js
export * from './accessible-icon-icon';
...
```
After:
```js
export { AccessibleIconIcon } from './accessible-icon-icon';
...
```

fix(icons,tokens): no star reexport

---

packages/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx
packages/react-core/src/components/ClipboardCopy/ClipboardCopyAction.tsx
packages/react-core/src/components/ClipboardCopy/ClipboardCopyButton.tsx
packages/react-core/src/components/ClipboardCopy/__tests__/Generated/__snapshots__/ClipboardCopy.test.tsx.snap
packages/react-core/src/components/ClipboardCopy/examples/ClipboardCopy.md
packages/react-core/src/components/ClipboardCopy/index.ts
packages/react-integration/cypress/integration/clipboardcopy.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/ClipboardCopyDemo/ClipboardCopyDemo.tsx

**What**: Closes #5555
- Utilizes `inline` value of `variant` property to toggle between inline/expand/default types of ClipboardCopy.
- Reuses internal `ClipboardCopyButton` for inline variant, changing the button styling from control to plain. (@mcoker so the html structure for the button differs slightly from core, since the current button has a tooltip. Let me know if I should keep/remove the tooltip).
- Exposes `ClipboardCopyAction` as a wrapper for additional actions added to inline ClipboardCopy via the `additionalActions` property.

feat(ClipboardCopy): add inline variant

---

packages/react-console/src/components/DesktopViewer/__tests__/__snapshots__/DesktopViewer.test.tsx.snap
packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx
packages/react-core/src/components/ExpandableSection/ExpandableSectionToggle.tsx
packages/react-core/src/components/ExpandableSection/__tests__/ExpandableSection.test.tsx
packages/react-core/src/components/ExpandableSection/__tests__/Generated/__snapshots__/ExpandableSection.test.tsx.snap
packages/react-core/src/components/ExpandableSection/__tests__/__snapshots__/ExpandableSection.test.tsx.snap
packages/react-core/src/components/ExpandableSection/examples/ExpandableSection.md
packages/react-core/src/components/ExpandableSection/index.ts
packages/react-integration/cypress/integration/expandablesection.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/ExpandableSectionDemo/ExpandableSectionDemo.tsx

**What**: Closes #5581
- Adds `ExpandableSectionToggle` component for detached expandable sections.
- Adds `isDetached` flag to `ExpandableSection`. This removes the built in toggle and adds the appropriate styling.
- Adds `contentId` property to both components to populate `aria-controls` label. There might be a better name for this property?
- `isExpanded` must be passed in to both components (there is no uncontrolled variation for detached section).
Also updated tests + added to integration/cypress.

feat(ExpandableSection): add detached variant, update tests

---

packages/react-core/src/components/ClipboardCopy/ClipboardCopyButton.tsx
packages/react-core/src/components/ClipboardCopy/examples/ClipboardCopy.md
packages/react-core/src/components/ClipboardCopy/index.ts
packages/react-core/src/components/CodeBlock/CodeBlock.tsx
packages/react-core/src/components/CodeBlock/CodeBlockAction.tsx
packages/react-core/src/components/CodeBlock/CodeBlockCode.tsx
packages/react-core/src/components/CodeBlock/__tests__/CodeBlock.test.tsx
packages/react-core/src/components/CodeBlock/__tests__/__snapshots__/CodeBlock.test.tsx.snap
packages/react-core/src/components/CodeBlock/examples/CodeBlock.md
packages/react-core/src/components/CodeBlock/index.ts
packages/react-core/src/components/index.ts
packages/react-integration/cypress/integration/codeblock.spec.ts
packages/react-integration/demo-app-ts/src/Demos.ts
packages/react-integration/demo-app-ts/src/components/demos/CodeBlockDemo/CodeBlockDemo.tsx
packages/react-integration/demo-app-ts/src/components/demos/index.ts

**What**: Closes #5556
- Adds `CodeBlock`, `CodeBlockAction`, `CodeBlockCode` components
- `CodeBlockAction` styles buttons for the header and multiple actions may be passed to `CodeBlock` via the `actions` property.
- `CodeBlockCode` styles code content for the `CodeBlock`. Detached expandable sections can be combined with `CodeBlockCode` to create expandable code sections (example is in, but commented out until #5643 merges).
Docs: https://patternfly-react-pr-5656.surge.sh/components/code-block
@mcoker Is `.pf-c-code-block__actions-item` a placeholder class? I couldn't find it in the styles object so I have it hardcoded atm.

feat(CodeBlock): add component

---

packages/react-catalog-view-extension/package.json
packages/react-console/package.json
packages/react-core/package.json
packages/react-docs/package.json
packages/react-icons/package.json
packages/react-styles/package.json
packages/react-table/src/components/Table/TableTypes.ts
packages/react-table/src/components/Table/TreeRowWrapper.tsx
packages/react-table/src/components/Table/examples/Table.md
packages/react-table/src/components/Table/utils/decorators/treeRow.tsx
packages/react-table/src/components/TableComposable/TableComposable.tsx
packages/react-table/src/components/TableComposable/Td.tsx
packages/react-tokens/package.json
yarn.lock

**What**: Closes #5598 and #5576
- Adds optional icons to tree table rows - demonstrated in the tree table examples
- Adds responsive layout to all tree table examples

feat(Table): Add optional icons to tree table rows, add responsive view

---

packages/react-core/src/components/Slider/Slider.tsx
packages/react-core/src/components/Slider/_tests_/Slider.test.tsx
packages/react-core/src/components/Slider/_tests_/__snapshots__/Slider.test.tsx.snap
packages/react-core/src/components/Slider/examples/Slider.md
packages/react-integration/cypress/integration/slider.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/SliderDemo/SliderDemo.tsx

**What**: Closes #5464, #5529 
- Added `min`, `max` and `step` props to match the HTML range input API 
- changed prop name `steps` to `customSteps` to be less confusing.
- renamed `currentValue` prop to `value` to match  HTML rang input
- Added `showTicks` prop so the consumer can choose to show ticks when they use the `min`, `max` and `step` props
- Removed the `isDiscrete ` prop and added `areCustomStepsContinuous` prop.  A slider with out custom steps is continuous by default.    A slider with custom steps is discrete unless the `areCustomStepsContinuous` is set to true. This allows the consumer to add labels to a continuous slider.
- Updated Slider to have only one `onChange` callback
- Fixed onChange not getting called for continuous sliders.

fix, feat(Slider): Update Slider API to be more like the range input API

---

packages/react-tokens/scripts/writeTokens.js

**What**: Should fix this error from @dtaylor113 :
```js
ERROR in ./node_modules/@patternfly/react-tokens/dist/esm/index.js 226:9
Module parse failed: Duplicate export 'global_FontFamily_sans_serif' (226:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| export { global_target_size_MinWidth } from './global_target_size_MinWidth';
| export { global_target_size_MinHeight } from './global_target_size_MinHeight';
> export { global_FontFamily_sans_serif } from './global_FontFamily_sans_serif';
| export { global_FontFamily_heading_sans_serif } from './global_FontFamily_heading_sans_serif';
| export { global_FontFamily_monospace } from './global_FontFamily_monospace';
``` …

fix(tokens): fix duplicate entries

---

packages/react-core/src/components/ApplicationLauncher/examples/ApplicationLauncher.md

**What**: Closes #5718 
This PR adds the `ApplicationLauncherContent` component to the docs.

add ApplicationLauncherContent to docs

---

packages/react-core/src/components/EmptyState/examples/EmptyState.md

**What**: Closes #5395 
This PR updates the text of the empty state "no match found" example.

updated empty state no match found example text

---

packages/react-core/src/components/Slider/Slider.tsx
packages/react-core/src/components/Slider/examples/Slider.md

Also make the new property default to true, showing boundaries is
probably what most consumers of this components want anyway.
Fixes #5709

Slider: add showBoundaries property to the min/max slider variant

---

packages/react-core/src/components/Toolbar/ToolbarItem.tsx
packages/react-core/src/components/Toolbar/__tests__/ToolbarToggleGroup.test.tsx
packages/react-core/src/components/Toolbar/__tests__/__snapshots__/ToolbarToggleGroup.test.tsx.snap
packages/react-core/src/components/Toolbar/examples/Toolbar.md
packages/react-integration/cypress/integration/toolbar.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/ToolbarDemo/ToolbarDemo.tsx

**What**: Closes #5674
- Adds `widths` property to `ToolbarItem`. Specify widths for different breakpoints using strings.

feat(ToolbarItem): add widths on breakpoints

---

packages/react-console/src/components/SerialConsole/XTerm.tsx
packages/react-core/src/components/DualListSelector/DualListSelector.tsx
packages/react-core/src/components/DualListSelector/DualListSelectorPane.tsx
packages/react-core/src/components/JumpLinks/JumpLinks.tsx
packages/react-core/src/components/Menu/Menu.tsx
packages/react-core/src/components/Nav/NavList.tsx
packages/react-core/src/components/OverflowMenu/OverflowMenu.tsx
packages/react-core/src/components/Page/Page.tsx
packages/react-core/src/components/Tabs/Tabs.tsx
packages/react-core/src/components/TextArea/TextArea.tsx
packages/react-core/src/components/TextInput/TextInput.tsx
packages/react-core/src/components/Toolbar/Toolbar.tsx
packages/react-core/src/components/Toolbar/ToolbarChipGroupContent.tsx
packages/react-core/src/components/Toolbar/ToolbarToggleGroup.tsx
packages/react-core/src/components/TreeView/TreeViewRoot.tsx
packages/react-core/src/helpers/Popper/thirdparty/react-popper/usePopper.ts
packages/react-table/src/components/Table/RowWrapper.tsx
packages/react-topology/src/behavior/useDndDrag.tsx

fix(packages): check canUseDOM before using DOM

---

packages/react-core/src/components/Accordion/AccordionToggle.tsx
packages/react-core/src/components/Accordion/__tests__/__snapshots__/Accordion.test.tsx.snap

**What**: Closes #5661
@tlabaj I'm not sure, but would this be considered a breaking change? It sets a default, but the default probably shouldn't be `submit` for this component.

fix(Accordion): set button type, update prop extension

---

packages/react-core/src/layouts/Gallery/Gallery.tsx
packages/react-core/src/layouts/Gallery/__tests__/Gallery.test.tsx
packages/react-core/src/layouts/Gallery/__tests__/__snapshots__/Gallery.test.tsx.snap
packages/react-core/src/layouts/Gallery/examples/Gallery.md
packages/react-integration/cypress/integration/gallery.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/GalleryDemo/GalleryDemo.tsx

**What**: Closes #5055
- Adds `minWidths` and `maxWidths` properties that specify their respective width modifier at different breakpoints. The `default` will set a min or max width in general (not at any breakpoint).

feat(Gallery): add min/max widths at breakpoints

---

packages/react-core/src/components/JumpLinks/JumpLinks.tsx

**What**: Closes #5753 
This PR fixes the JumpLinks component from breaking after navigating between pages. Existing code already checks that `newScrollItems` array is not empty, this PR adds a check that is does not contain `null` values.

fix(JumpLinks): added check for null scrollItems

---

packages/react-core/src/components/Card/CardHeader.tsx
packages/react-core/src/components/Card/examples/Card.md
packages/react-integration/cypress/integration/card.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/CardDemo/CardDemo.tsx

**What**: Closes #5583 
This PR adds the `isToggleRightAligned` prop to the expandable Card to move the carrot icon to the right of the `CardHeader` component. Note that spacing is to be fixed [per this comment](https://github.com/patternfly/patternfly/pull/3848/files#r591988545).
Updated the `Expandable` example allowing to toggle this prop on & off.

feat(Card): add isToggleRightAligned prop

---

packages/react-table/src/components/Table/ActionsColumn.tsx
packages/react-table/src/components/Table/Table.tsx
packages/react-table/src/components/Table/TableTypes.ts
packages/react-table/src/components/Table/examples/Table.md
packages/react-table/src/components/Table/utils/decorators/cellActions.tsx
packages/react-table/src/components/TableComposable/Td.tsx
packages/react-virtualized-extension/src/components/Virtualized/__snapshots__/VirtualizedTable.test.tsx.snap

**What**: Closes #4612
https://patternfly-react-pr-5744.surge.sh/components/table#actions-and-first-cell-in-body-rows-as-th
I added two checkboxes to demonstrate the feature:
- Use custom actions toggle
- Add extra actions
They demonstrate how to change the dropdown toggle to make it something other than a kebab toggle, and how to move some actions out of the dropdown.

feat(Table): allow for more customizable Table actions

---

packages/react-core/src/components/Dropdown/Toggle.tsx
packages/react-core/src/components/Dropdown/__tests__/DropdownToggle.test.tsx
packages/react-core/src/components/Select/SelectToggle.tsx
packages/react-core/src/components/Select/__tests__/SelectToggle.test.tsx
packages/react-integration/cypress/integration/selectfavorites.spec.ts

**What**: Closes #5703
Replaces `mousedown` event handler trigger with `click` in Dropdown and Select toggles, to prevent clicking on the scrollbar from closing the menu. 
@tlabaj The behavior otherwise should remain the same. Was there a particular reason we went with `mousedown` at the time? I can't recall.

fix(Dropdown, Select): fix scrollbar click closing menu

---

packages/react-table/src/components/TableComposable/Td.tsx

**What**: Closes #5776
Allow additional props to be passed into rowData for user customization. 

Adds a props key:value pair to the rowData for end user customization

---

packages/react-core/src/components/Dropdown/Toggle.tsx
packages/react-core/src/components/Select/SelectToggle.tsx

**What**: Closes #5788 
Focus shouldn't need to be manually set after a `click` event fires outside of an open menu, the clicked element should receive focus rather than the toggle. The menu should still close when a user clicks outside of the menu.
@jessiehuff Removing this shouldn't cause any accessibility issues right? This should be pure mouse behavior, where `click` already focuses the event target.

fix(Dropdown, Select): fix focus on toggle after click off menu

---

packages/react-charts/src/components/Chart/Chart.tsx
packages/react-charts/src/components/ChartLegend/examples/ChartLegend.md
packages/react-charts/src/components/ChartUtils/chart-interactive-legend.ts

This provides an example showing how to use a pie chart with an interactive legend. 
Note that pie charts are not typically wrapped by a `Chart` component, but in this case we need something to attach `onMouseOver` events to.
https://github.com/patternfly/patternfly-react/issues/5586

Interactive legend example for pie chart

---

packages/react-charts/src/components/Chart/Chart.tsx
packages/react-charts/src/components/ChartLegend/examples/ChartLegend.md

Cleaning up my previous commit after finding a better way to omit the Chart axis. The previous approach left empty `<g>` tags in the SVG, but now they're completely omitted.
Previous PR: "Interactive legend example for pie chart"
https://github.com/patternfly/patternfly-react/pull/5795

Interactive legend pie example (clean up)

---

packages/react-core/src/components/Card/examples/Card.md
packages/react-core/src/components/Select/examples/Select.md
packages/react-core/src/components/Toolbar/examples/Toolbar.md
packages/react-core/src/demos/Card/Card.md
packages/react-core/src/demos/PrimaryDetail.md

**What**: Closes #5759 
This PR fixes broken Codesandbox pages due to incorrect & missing import paths:
- Adds file extension to `./pf-logo-small.svg` in `Card` example
- Adds `SelectVariant` import statements in both the `Card view` and `Primary-detail inline modifier` demos and `Toolbar` examples
-Fixes `SelectVariant` typo in some `Select` demos where it was misspelled `SelectVarian`
- Adds `imgBrand` and `imgAvatar` imports that were missing in several `Primary-detail` demos

fixed incorrect/missing import statements

---

packages/react-charts/src/components/ChartPie/ChartPie.tsx

This ensures the pie chart uses a non-negative default radius.
https://github.com/patternfly/patternfly-react/issues/5821

react-charts(fix): Ensure ChartPie uses non-negative default radius

---

packages/react-core/src/components/Slider/Slider.tsx
packages/react-core/src/components/Slider/SliderStep.tsx
packages/react-core/src/components/Slider/_tests_/__snapshots__/Slider.test.tsx.snap
packages/react-core/src/components/Slider/examples/Slider.md

Add examples for the valid combinations.
Closes #5739

core(Slider): showBoundaries should be independent from showTicks

---

packages/react-core/src/components/Button/Button.tsx
packages/react-core/src/components/Button/__tests__/Button.test.tsx
packages/react-core/src/components/Button/__tests__/__snapshots__/Button.test.tsx.snap
packages/react-core/src/components/Button/examples/Button.md
packages/react-integration/cypress/integration/button.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/ButtonDemo/ButtonDemo.tsx

**What**: Closes #5578
Adds `isDanger` flag. When the button variant is `link` or `secondary`, danger styling will be added to the button with the new flag.
Should the `danger` variant be removed in the next breaking change release? 
And should the `isDanger` flag be made to add danger styling to any variant or is there a reason to limit the flag to just link/secondary?

feat(Button): add danger modifier to link/secondary buttons

---

packages/react-core/src/components/DescriptionList/DescriptionListTermHelpText.tsx
packages/react-core/src/components/DescriptionList/DescriptionListTermHelpTextButton.tsx
packages/react-core/src/components/DescriptionList/__tests__/DescriptionList.test.tsx
packages/react-core/src/components/DescriptionList/__tests__/__snapshots__/DescriptionList.test.tsx.snap
packages/react-core/src/components/DescriptionList/examples/DescriptionList.md
packages/react-core/src/components/DescriptionList/index.ts
packages/react-integration/cypress/integration/descriptionlist.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/DescriptionListDemo/DescriptionListDemo.tsx

feat(DescriptionList): Added support for help text

---

packages/react-core/src/components/Menu/MenuFooter.tsx
packages/react-core/src/components/Menu/MenuItem.tsx
packages/react-core/src/components/Menu/examples/Menu.md
packages/react-core/src/components/Menu/index.ts
packages/react-integration/cypress/integration/menu.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/MenuDemo/MenuDemo.tsx

**What**: Closes #5699 
**In this PR**:
- Adds `MenuFooter`
- Adds "view more" menu demo
**Notes**:
- In the "view more" demo, when the complete options list is displayed, the "view more" button will disappear.
- For the menu footer keyboard interaction, I followed a previous menu pattern. `Tab` shifts focus between the active menu item and footer (as in the breadcrumb drilldown interaction). The content of the footer has no pre-built keyboard handling. 
- For the "view more" menu demo keyboard interaction, `ArrowUp`/`ArrowDown` navigates through the options list and the "view more" button as usual. The demo hooks in and manages the `Space`/`Enter` keydown for the "view more" button, focusing the next valid option from where the "view more" button used to be.

feat(Menu): add footer, add view more demo

---

packages/react-core/src/components/Select/Select.tsx
packages/react-core/src/components/Select/SelectMenu.tsx
packages/react-core/src/components/Select/SelectToggle.tsx
packages/react-core/src/components/Select/__tests__/__snapshots__/Select.test.tsx.snap
packages/react-core/src/components/Select/examples/Select.md
packages/react-integration/cypress/integration/selectfiltering.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/SelectDemo/FilteringSelectDemo.tsx

**What**: Refactor `SelectMenu.tsx` to allow `hasInlineFilter` to work for non-checkbox variants.
Closes https://github.com/patternfly/patternfly/issues/4047
Closes #5764
Closes #5847
https://patternfly-react-pr-5793.surge.sh/components/select#grouped-single-with-filtering
Bug fixes:
- Stop entire page scrolling when pressing down arrow when focused on filter
- Clicking on typeahead variant's input while open now closes them
- Focus inline filter input when opening with mouse

feat(select): allow filtering in single variant

---

packages/react-core/src/demos/ComposableMenu.md

**What**: Closes #5771
Adds back in the drilldown demo for composable menus.
Needs https://github.com/patternfly/patternfly/issues/4062 for a transition fix.

docs(Menu): add drilldown composable menu demo back

---

packages/react-charts/src/components/ChartPoint/ChartPoint.tsx
packages/react-charts/src/components/ChartPoint/path-helpers.ts

For Cost Management, we want to use left pointing triangles as legend symbols. Unfortunately, Victory only supports up and down pointing triangles, not left and right. A left pointing triangle would better represent a forecast's "cone of confidence" in our tooltips.
https://github.com/patternfly/patternfly-react/issues/5867

feat(charts): Add left and right triangle legend symbols

---

packages/react-core/src/components/Menu/Menu.tsx

**What**: Closes #5915
Put the fix in the component-side as `tabIndex` was already being mapped internally, but let me know @tlabaj @mcarrano if it would make more sense for the fix to live in the example code instead because filtering is done on the app-side.
This updates the behavior of Menu such that whenever Menu's children change, Menu will remap the `tabIndex` of all options so only the first option is tabbable.

fix(Menu): update tabIndex when children change

---

packages/react-table/src/components/Table/BodyCell.tsx

**What**: Closes #5379
Removes the header cell data label if a BodyCell child is either an `EmptyState` component or a `Bullseye` component with an `EmptyState` direct child. Visually only changes the mobile view (where column headers are now unseen).

fix(Table): empty state cell should not have data-label

---

packages/react-core/src/components/DescriptionList/DescriptionList.tsx
packages/react-core/src/components/DescriptionList/__tests__/DescriptionList.test.tsx
packages/react-core/src/components/DescriptionList/__tests__/__snapshots__/DescriptionList.test.tsx.snap
packages/react-core/src/components/DescriptionList/examples/DescriptionList.md
packages/react-integration/cypress/integration/descriptionlistbreakpoints.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/DescriptionListDemo/DescriptionListBreakpointsDemo.tsx

**What**: Closes #5445
- Adds `layouts` property to specify layout orientation per breakpoint
- Adds `sm` breakpoint to `columnModifier` and `autoFitMinModifier`
- Fixes example code using `autoFitModifier` (instead of `autoFitMinModifier`)

feat(DescriptionList): add responsive layout breakpoint property

---

packages/react-console/src/components/DesktopViewer/__tests__/__snapshots__/DesktopViewer.test.tsx.snap
packages/react-core/src/components/Alert/__tests__/__snapshots__/Alert.test.tsx.snap
packages/react-core/src/components/AlertGroup/__tests__/__snapshots__/AlertGroup.test.tsx.snap
packages/react-core/src/components/Button/Button.tsx
packages/react-core/src/components/Button/__tests__/Generated/__snapshots__/Button.test.tsx.snap
packages/react-core/src/components/Button/__tests__/__snapshots__/Button.test.tsx.snap
packages/react-core/src/components/Card/__tests__/__snapshots__/CardHeader.test.tsx.snap
packages/react-core/src/components/ChipGroup/__tests__/__snapshots__/Chip.test.tsx.snap
packages/react-core/src/components/ChipGroup/__tests__/__snapshots__/ChipGroup.test.tsx.snap
packages/react-core/src/components/Drawer/__tests__/__snapshots__/Drawer.test.tsx.snap
packages/react-core/src/components/DualListSelector/DualListSelector.tsx
packages/react-core/src/components/DualListSelector/__tests__/__snapshots__/DualListSelector.test.tsx.snap
packages/react-core/src/components/DualListSelector/examples/DualListSelector.md
packages/react-core/src/components/Form/__tests__/__snapshots__/FormFieldGroup.test.tsx.snap
packages/react-core/src/components/NumberInput/__tests__/__snapshots__/NumberInput.test.tsx.snap
packages/react-core/src/components/Pagination/__tests__/__snapshots__/Pagination.test.tsx.snap
packages/react-core/src/components/SearchInput/__tests__/__snapshots__/SearchInput.test.tsx.snap
packages/react-core/src/components/Select/__tests__/__snapshots__/Select.test.tsx.snap
packages/react-core/src/components/Slider/_tests_/__snapshots__/Slider.test.tsx.snap
packages/react-core/src/components/TreeView/__tests__/__snapshots__/TreeView.test.tsx.snap
packages/react-inline-edit-extension/src/components/ConfirmButtons/__snapshots__/ConfirmButtons.test.js.snap
packages/react-integration/cypress/integration/duallistselectorbasic.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/DualListSelector/DualListSelectorBasicDemo.tsx
packages/react-topology/src/components/TopologyControlBar/__snapshots__/TopologyControlBar.test.tsx.snap
packages/react-topology/src/components/TopologySideBar/__snapshots__/TopologySideBar.test.tsx.snap

**What**: Closes #5855
- Adds tooltip/tooltipProps properties for each move action control button.
- Updates `Button` to forward a `ref` (basically all of the snapshot updates are due to this change). This update is because Tooltip requires a `ref` set on the button that triggers the tooltip, but `Button` is a functional component that doesn't allow refs by default.

feat(DualListSelector): add tooltips to control buttons

---

packages/react-core/src/components/Breadcrumb/BreadcrumbHeading.tsx

fixes https://github.com/patternfly/patternfly-react/issues/5508
updates the markup to match the core example at https://www.patternfly.org/v4/components/breadcrumb/html#with-heading

fix(breadcrumb): moved divider outside of header element

---

packages/react-core/src/components/Menu/Menu.tsx
packages/react-core/src/components/Menu/MenuContent.tsx
packages/react-core/src/components/Menu/examples/Menu.md

Closes: #5525 and #5610
- wraps all `MenuList` components in a `MenuContent` in the examples
- demonstrates how to set the `maxMenuHeight` prop in the `With drilldown breadcrumbs` example
- demonstrates how to set the `menuHeight` prop in the new `Scrollable` example

feat(Menu): add scrollable support

---

packages/react-core/src/components/HelperText/HelperText.tsx
packages/react-core/src/components/HelperText/HelperTextItem.tsx
packages/react-core/src/components/HelperText/__tests__/HelperText.test.tsx
packages/react-core/src/components/HelperText/__tests__/__snapshots__/HelperText.test.tsx.snap
packages/react-core/src/components/HelperText/examples/HelperText.md
packages/react-core/src/components/HelperText/index.ts
packages/react-core/src/components/index.ts
packages/react-integration/cypress/integration/helpertext.spec.ts
packages/react-integration/demo-app-ts/src/Demos.ts
packages/react-integration/demo-app-ts/src/components/demos/HelperText/HelperTextDemo.tsx
packages/react-integration/demo-app-ts/src/components/demos/index.ts

**What**: Closes #5818
Users should be able to update individual HelperTextItem properties (like `variant`) to reflect a validation update. Perhaps a more detailed demo showcasing a validated input field with a HelperText list would be a good follow up?

feat(HelperText): add helper text component

---

packages/react-core/src/components/Slider/Slider.tsx

**What**: Closes #5968
**Additional issues**: Try the following code in an example:
```tsx
class DiscreteInput extends React.Component {
constructor(props) {
super(props);
this.state = {
value: 50,
max: 100
};
this.onChange = (value) => {
this.setState({
value: value
});
};
}
render() {
return (
<React.Fragment>
<TextInput
onChange={(value) => this.setState({ max: value })}
value={this.state.max}
/>
<Text component={TextVariants.small}>
(min = -25, max = {this.state.max}, step = 10, boundaries shown, ticks
not shown){" "}
</Text>
<Slider
isInputVisible
value={this.state.value}
onChange={this.onChange}
min={-25}
max={this.state.max}
step={1}
/>
</React.Fragment>
);
}
}
```

fix(slider): respect props in useCallback

---

packages/react-core/src/components/Tooltip/Tooltip.tsx

If a Tooltip is unmounted while one of its animation/delay timers is still running, it will result in a console warning from React about updating state on an unmounted component:
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
```
This can be reproduced by triggering a Tooltip and then causing it to unmount while its hide animation is playing. This is easier to reproduce if you increase the animationDelay, but I have seen it in normal usage as well.
CodeSandbox to reproduce the issue: https://codesandbox.io/s/serverless-bush-0k3pi?file=/index.js
Screen capture of issue being reproduced:
This PR adds a …

fix: 🐛 Tooltip: clean up timeouts on unmount to prevent warning

---

packages/react-catalog-view-extension/README.md
packages/react-catalog-view-extension/node-sass-patternfly-importer.js
packages/react-catalog-view-extension/package.json
packages/react-catalog-view-extension/sass/react-catalog-view-extension.scss
packages/react-catalog-view-extension/sass/react-catalog-view-extension/_catalog-item.scss
packages/react-catalog-view-extension/sass/react-catalog-view-extension/_catalog-tile.scss
packages/react-catalog-view-extension/sass/react-catalog-view-extension/_filter-side-panel.scss
packages/react-catalog-view-extension/sass/react-catalog-view-extension/_variables.scss
packages/react-catalog-view-extension/src/components/CatalogTile/CatalogTileBadge.tsx
packages/react-catalog-view-extension/src/components/CatalogTile/__snapshots__/CatalogTile.test.tsx.snap
packages/react-catalog-view-extension/src/components/FilterSidePanel/FilterSidePanelCategory.tsx
packages/react-catalog-view-extension/src/components/FilterSidePanel/examples/FilterSidePanel.md
yarn.lock

**What**: 
react-catalog-view-extension includes PatternFly 3 as a dependency because of a couple of Bootstrap 3 classes that are in use as well as a dependence on some PatternFly 3 LESS variables.  As a result, any consumers of react-catalog-view-extension are resulting in PatternFly 3 installing as a dependency.  As part of https://issues.redhat.com/browse/CONSOLE-2361, we are trying to *remove* PatternFly 3 as a dependency from OpenShift, but are blocked by react-catalog-view-extension's dependence on it.  
This PR removes PatternFly 3 as a dependency from react-catalog-view-extension, but results in near-identical rendering *assuming* any consumers of the package had PatternFly 3 in use as a dependency.  If PatternFly 3 is *not* in use as a dependency, there will be one noticeable …

Remove PatternFly 3 as a dependency from react-catalog-view-extension

---

packages/react-table/src/components/Table/Body.tsx
packages/react-table/src/components/Table/base/body-row.tsx
packages/react-table/src/components/Table/base/body.tsx
packages/react-table/src/components/Table/base/header-row.tsx

This change updates the @patternfly/react-table package to remove the use of the `Object` constructor. This was used as a replacement for an empty dictionary. However, Dart libraries such as dart-sass might pollute the Object constructor, which in turn causes issues with React.
Fixes #5320

fix(table): Avoid Object constructor

---

packages/react-core/src/components/Select/Select.tsx

Select's `children` property is a collection of ReactElements and
therefore a pure JS '===' is not accurate. For this reason let's do a
one by one value comparison for the SelectOption children, to make sure
that actual changes took place. We need this in order to avoid falsely
updating the filtered list, having the assumption that children changed
when they did not.
Note:
Before this commit one could get a JS error:
'Uncaught InternalError: too much recursion
getNextIndex ...index.js
on the following scenario.
Crash Scenario:
Imagine that children on the consumer side do not need to be a constant.
The SelectOptions list can be prepared on the fly before rendering the Select component.
In this case, when the componentDidUpdate will run,
`prevProps.children !== this.props.children` would …

fix(Select): check the values of the children for possible changes on componentDidUpdate

---

packages/react-core/src/components/Select/Select.tsx

**What**: Closes #5952 
To note, the "maximum stack exceeded" could possibly still happen in other components but fixing that is not necessary for this issue.

fix(Select): Ignore arrow keys when typeahead options are empty

---

packages/react-log-viewer/src/LogViewer/LogViewer.tsx
packages/react-log-viewer/src/LogViewer/examples/realTestData.js

- Do not estimate 600 rows for empty lines => wrong priority for ‹||›
- After fixing previous bug, do not estimate 0 height for empty lines,
i.e. there is always at least one row in the log
Signed-off-by: Matej Focko <mfocko@redhat.com>
**What**: Part of #6021

fix(LogViewer): Do not overestimate size for empty lines

---

packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx

The upstream not require language type, it should be ok to use `string`
In case of help user find the support languages, add more in Language enum
The languages are coming from https://github.com/microsoft/monaco-languages

fix(code-editor): add more languages support

---

packages/react-core/src/components/TreeView/TreeView.tsx
packages/react-core/src/components/TreeView/TreeViewListItem.tsx

This fixes a bug I overlooked when I implemented https://github.com/patternfly/patternfly-react/pull/5150 last year.
In order to show an indeterminate (partially-checked) checkbox in the tree view, we allow a `null` value for the `checkProps.checked` property on a tree view item. We then [use a ref](https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/components/TreeView/TreeViewListItem.tsx#L141) to set the `indeterminate` property on the DOM element if `checkProps.checked === null`. This was modeled after [similar behavior](https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/components/Checkbox/Checkbox.tsx#L104) in the regular `Checkbox` component.
However, an `<input type="checkbox">` like these must always have a boolean …

fix(TreeView): console warning about uncontrolled inputs when checkbox swaps between determinate/indeterminate

---

packages/react-core/src/components/Alert/examples/Alert.md
packages/react-core/src/components/AlertGroup/AlertGroup.tsx
packages/react-core/src/components/AlertGroup/AlertGroupInline.tsx
packages/react-core/src/components/AlertGroup/__tests__/Generated/__snapshots__/AlertGroupInline.test.tsx.snap
packages/react-core/src/components/AlertGroup/__tests__/__snapshots__/AlertGroup.test.tsx.snap
packages/react-core/src/components/AlertGroup/examples/AlertGroup.md

**What**: Alternative approach/attempt to PR#5773
Closes #5731
This PR/POC is meant to test an alternative approach to making dynamic alerts more accessible. It turns AlertGroup into a pre-existing live region for screen readers to be notified that alerts will be rendered inside of it.

feat(AlertGroup): Make dynamic alerts more accessible

---

packages/react-core/src/components/Page/PageSection.tsx
packages/react-core/src/components/Page/__tests__/PageSection.test.tsx
packages/react-core/src/components/Page/__tests__/__snapshots__/PageSection.test.tsx.snap

This change adds a PageSection variant for tabs as demoed in the PatternFly HTML version. See https://www.patternfly.org/v4/components/tabs/html-demos#open-tabs.
I am trying to rebuild part of this tab demo in React, but currently it does not have a PageSectionVariant for tabs, so I am unable to properly reproduce the demo without using HTML components.
Fixes #6034

feat(Page): Add tabs PageSection variant

---

packages/react-core/src/components/DatePicker/DatePicker.tsx

fix(datepicker): change default parse format to y-m-d from y(-m)?(-d)?

---

packages/react-core/src/components/SearchInput/SearchInput.tsx
packages/react-core/src/components/SearchInput/__tests__/SearchInput.test.tsx
packages/react-core/src/components/SearchInput/__tests__/__snapshots__/SearchInput.test.tsx.snap
packages/react-core/src/components/SearchInput/examples/SearchInput.md

Can be used to link to docs pages for example.
This is for cockpit, we want to use it like this:
See the last item, it's basically the docs link and and CopyClipboard with the CLI command equivalent generated by the user's input.

feat(SearchInput): Allow passing custom form elements after the attributes

---

packages/react-core/src/components/Checkbox/Checkbox.tsx
packages/react-core/src/components/Checkbox/__tests__/Generated/__snapshots__/Checkbox.test.tsx.snap
packages/react-core/src/components/Checkbox/__tests__/__snapshots__/Checkbox.test.tsx.snap

This slipped in https://github.com/patternfly/patternfly-react/pull/5949

fix(Checkbox): fix warning about ouiaSafe property

---

packages/react-core/src/components/Pagination/OptionsToggle.tsx
packages/react-core/src/components/Pagination/Pagination.tsx
packages/react-core/src/components/Pagination/PaginationOptionsMenu.tsx
packages/react-core/src/components/Pagination/__tests__/__snapshots__/Pagination.test.tsx.snap
packages/react-core/src/components/Pagination/examples/Pagination.md

**What**: Closes #1882
Added the interfaces to the md file so that the props are documented for the user.  Updated a few prop descriptions @jessiehuff @jgiardino  the `titles.optionsToggle` is what sets the toggles aria label.

docs(Pagination): Export interfaces in md file so prop descriptions are documented

---

packages/react-core/src/components/SearchInput/SearchInput.tsx

In cockpit we want to use this component variant, but the 'Has words' field needs explanation. For this reason we want to use a helpicon popover as seen in the screenshot.

SearchInput: allow hasWordAttrLabel to be React.ReactNode as well

---

packages/react-core/src/components/TreeView/examples/TreeView.md
packages/react-core/src/components/TreeView/index.ts

Closes #6067
Remove unused imports
Use event handler names that more closely match prop names (for clarity)
Update which components are included in API docs at bottom
Update which components are exposed to consumers in index.ts
Remove unused references to parentItems when updating activeItems
Remove activeItems from state in checkbox example

chore(TreeView): clean up docs

---

packages/react-core/src/components/Label/Label.tsx
packages/react-core/src/components/Label/examples/Label.md
packages/react-core/src/components/LabelGroup/LabelGroup.tsx
packages/react-core/src/components/LabelGroup/examples/LabelGroup.md
packages/react-integration/cypress/integration/label.spec.ts
packages/react-integration/cypress/integration/labelgroupeditable.spec.ts
packages/react-integration/demo-app-ts/src/Demos.ts
packages/react-integration/demo-app-ts/src/components/demos/LabelDemo/LabelDemo.tsx
packages/react-integration/demo-app-ts/src/components/demos/LabelGroupDemo/LabelGroupEditableDemo.tsx
packages/react-integration/demo-app-ts/src/components/demos/index.ts

**What**: Closes #5875
Label:
- Adds `isEditable`, `onEditComplete`, `onEditCancel`, `editableProps`
- `onEditComplete` is triggered when `Enter`, `Tab` is pressed while on an active editable div, or when the mouse clicks outside of an active editable div
- `onEditCancel` is triggered when `Escape` is pressed while on on active editable div. This will also reset the editable div text to the initially passed children. The callback also passes back the previous text as a property (but it isn't be required to set the text state in this callback). 
- Optionally, passing `onInput` and/or `onBlur` to `editableProps` can let users hook directly into the changing text div
LabelGroup:
- Adds `isEditable`, `hasEditableTextArea`, `editableTextAreaProps`
- `hasEditableTextArea` will append a text …

feat(Label): add editable label

---

packages/react-log-viewer/src/LogViewer/LogViewer.tsx
packages/react-log-viewer/src/LogViewer/examples/LogViewer.md

Closes #5930 
The first log viewer example now has a checkbox for toggling dark theme.

feat(LogViewer): Add dark theme

---

packages/react-core/src/components/Form/FormGroup.tsx
packages/react-core/src/components/Form/FormHelperText.tsx
packages/react-core/src/components/Form/__tests__/FormGroup.test.tsx
packages/react-core/src/components/Form/__tests__/__snapshots__/FormGroup.test.tsx.snap
packages/react-core/src/components/Form/examples/Form.md
packages/react-core/src/components/TextInput/TextInput.tsx
packages/react-core/src/demos/PasswordStrength.md
packages/react-integration/cypress/integration/form.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/FormDemo/FormDemo.tsx

**What**: Closes #6002 & #5819
Adds `labelInfo` property to `FormGroup`.
Adds new unit test, example and integration test.
Also updates some duplicate ids in the examples.
Update: Adds password strength demo

feat(Form): add form group label info & docs(Form): add password strength demo

---

packages/react-core/src/components/Select/Select.tsx

- Allow Select.onFilter to return undefined 
- Allow Select.onFilter have a `null` event as input
`onFilter` function supports ([here](https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/components/Select/Select.tsx#L338)) to return undefined (or any falsy value) to say that we want to keep rendering the children. 
In this case `onFilter` function is responsible of updating whatever logic to ensure the children are updated.
`onFilter` function first argument can be null as seen [here](https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/components/Select/Select.tsx#L252) (`updateTypeAheadFilteredChildren` function calls `onFilter` with the second argument) 
closes: #6105

Type improvements on Select.onFilter

---

packages/react-core/src/components/ApplicationLauncher/__tests__/__snapshots__/ApplicationLauncher.test.tsx.snap
packages/react-core/src/components/ApplicationLauncher/examples/ApplicationLauncher.md
packages/react-core/src/components/Dropdown/DropdownItem.tsx
packages/react-core/src/components/Dropdown/InternalDropdownItem.tsx
packages/react-core/src/components/Dropdown/__tests__/InternalDropdownItem.test.tsx
packages/react-core/src/components/Dropdown/__tests__/__snapshots__/Dropdown.test.tsx.snap
packages/react-core/src/components/Dropdown/__tests__/__snapshots__/InternalDropdownItem.test.tsx.snap
packages/react-core/src/components/Dropdown/examples/Dropdown.md
packages/react-core/src/components/OptionsMenu/__tests__/__snapshots__/OptionsMenu.test.tsx.snap
packages/react-integration/demo-app-ts/src/components/demos/DropdownDemo/DropdownDemo.tsx

**What**: Closes #5826 
You can see it working in the very first example - one of the disabled items is now using aria-disabled with a simple tooltip.

feat(Dropdown): Allow for tooltips on aria-disabled items

---

packages/react-core/src/components/Breadcrumb/BreadcrumbHeading.tsx
packages/react-core/src/components/Breadcrumb/BreadcrumbItem.tsx
packages/react-core/src/components/Breadcrumb/__tests__/__snapshots__/Breadcrumb.test.tsx.snap
packages/react-core/src/components/Breadcrumb/__tests__/__snapshots__/BreadcrumbHeading.test.tsx.snap
packages/react-core/src/components/Breadcrumb/__tests__/__snapshots__/BreadcrumbItem.test.tsx.snap
packages/react-core/src/components/Page/__tests__/__snapshots__/Page.test.tsx.snap

BreadcrumbItem.tsx:35:3 - error TS2322: Type 'null' is not assignable to type 'string'.
35   to = null,
~~
BreadcrumbItem.tsx:39:3 - error TS2322: Type 'null' is not assignable to type 'string'.
39   target = null,
~~~~~~
BreadcrumbItem.tsx:41:3 - error TS2322: Type 'null' is not assignable to type '(props: BreadcrumbItemRenderArgs) => ReactNode'.
41   render = null,
~~~~~~
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

BreadCrumbItem: fix ts-lint errors

---

packages/react-core/src/components/Menu/Menu.tsx

**What**: Closes #6151
Blocks https://github.com/openshift/console/pull/9279, see https://github.com/openshift/console/pull/9767#issuecomment-895607590
This PR fixes that `Menu` component can crash if menuRef is null. Other code in `handleDrilldownTransition` already checks if the current value is set. The new `allowTabFirstItem` function does this with this PR as well.
Crash and call stack:
```
TypeError
Cannot read property 'querySelector' of null
Call Stack
 MenuBase.allowTabFirstItem
 MenuBase.componentDidUpdate
```

Fix menu crash if current menuRef value is not found.

---

packages/react-core/src/components/HelperText/HelperTextItem.tsx
packages/react-core/src/components/HelperText/examples/HelperText.md

**What**: Closes #6083
In this PR:
- Updates default icons for `success` and `error` variants of `HelperText`
- Updates custom icons used in examples to differ from new defaults

feat(HelperText): update default icons for success/error

---

packages/react-core/src/components/TimePicker/TimePicker.tsx
packages/react-core/src/components/TimePicker/TimePickerUtils.tsx
packages/react-core/src/components/TimePicker/__tests__/TimePicker.test.tsx
packages/react-core/src/components/TimePicker/examples/TimePicker.md

**What**: Closes #5539 & #5898 
- onChange handler returns flag indicating if current time value is valid
- 0 & 00 are no longer a valid hour values in 12 hour time.

fix(TimePicker): small fixes

---

packages/react-core/src/components/JumpLinks/JumpLinks.tsx

**What**: Fixes #6127
**Additional issues**: `|| newScrollItems[0].offsetParent !== null` was the big offender which was always true and caused a render loop. A possible solution could be to flip the condition ([per MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetParent) it's null when we can't track `offsetTop` anyway) but a similar performance penalty would be incurred for hidden elements. I've removed the condition for now.

fix(jumplinks): improve perf

---

packages/react-core/src/components/DualListSelector/DualListSelector.tsx
packages/react-core/src/components/DualListSelector/examples/DualListSelector.md
packages/react-core/src/components/DualListSelector/treeUtils.ts

**What**: Closes #6179, #6124, #5828
In this PR:
- Fix to respect initial chosen options while moving options between panes of tree DLS
- Fix to allow checking of tree DLS subfolders
- Fix to reset selected states when options are moved via add/remove all (leaving an empty pane + active move selected button). Only affected tree variant.
- Update tree DLS example to contain initial chosen options
@nicolethoen The fix for selecting subfolders is possibly a regression on #5763 but I was unable to reproduce the bug from that PR after changing the code (locally tested - selecting a child of a subfolder and then moving selected does not move other children of the same subfolder).

fix(DualListSelector): respect initial chosen opts, select subfolders, reset selected button on all button

---

packages/react-table/src/components/TableComposable/examples/ComposableTable.md

**What**: Closes #6032
Updated Composable: Selectable example to implement a `shift + select` feature to demonstrate how to allow people to select intermediate rows all at once.

chore(TableComposable): Update Selectable example to use shift + select

---

packages/react-core/src/demos/CardDemos.md

**What**: Closes #6122 and closes #6121

demos(Card): added horizontal split and details demos

---

packages/react-core/src/components/Slider/Slider.tsx
packages/react-core/src/components/Slider/examples/Slider.md

Closes #5893 
Closes #5707 
**Additional issues**: Related issue #5833 
This PR fixes the issue of being able to enter a value outside slider's min/max via the text input, by passing `setLocalInputValue` to the user through `onChange`.
Steps to recreate issue:
- Set a slider either to max value, or above-max value using the text input.
- `value` and `inputValue` are correctly set to the max value, component state updates & internally updates `localInputValue` variable which controls the value displayed in the text input.
- Immediately enter another value above the max, `value` and `inputValue` remain at the max value so `setState` has no effect and the `localInputValue` is not updated causing above-max value to remain.
This PR also fixes the issue of tabbing through the first two "Value …

fix(Slider): update slider to respect min/max constraints

---

packages/react-code-editor/package.json

**What**: Closes #6240. [react-monaco-editor](https://www.npmjs.com/package/react-monaco-editor) already depends on [monaco-editor](https://www.npmjs.com/package/monaco-editor), so we don't need to ask consumers to specify it manually.

fix(code-editor): remove uneeded peer dep

---

packages/react-log-viewer/package.json

Add dependency that needs to be included for successful build of log
viewer.
Signed-off-by: Matej Focko <mfocko@redhat.com>
**What**: I tried to incorporate `@patternfly/react-log-viewer@4.5.1` into our dashboard, but I couldn't build it locally because of missing dependency, after adding it, builds fine.
**Additional issues**: I'm going to commit changes on my side and verify that build is failing just because of the log viewer related changes, since I have upgraded multiple of your packages.
_Edit_: Yeah, it's that dependency, have no clue how it got built in the CI here though. :thinking:

fix(LogViewer): add required dependency

---

packages/react-core/src/components/Slider/Slider.tsx

**What**: Closes #5833 
Related issues: #5707 & #5893 
This PR fixes the spacing of `customSteps` by respecting the min/max values when calculating the `value` prop for each `SliderStep`.
This PR also fixes `customSteps` allowing higher than `max` value by accurately calculating `customStepPercentage` based on the number of custom steps.

fix(Slider): fixed customSteps spacing to respect min/max

---

packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx

**What**: Closes #6195 
This PR replaces the hard coded empty state text with props and updates the default microcopy.

fix(code-editor): replace hardcoded text with props, update microcopy

---

packages/react-core/src/components/Select/Select.tsx

**What**: Closes https://github.com/patternfly/patternfly-react/issues/6243
- added string value to key instead of `0` for the `No Results found` & `Create <text>` Select options
- added check for duplicate entries. If the option already exists for the entered text then the Create option will not be shown
GIF:

fix(Select): fixed issues in Select typeaheadmulti

---

CONTRIBUTING.md

`yarn test` doesn't work without `yarn build`

docs(CONTRIBUTING) - add yarn build before test

---

packages/react-table/src/demos/Table.md

**What**: Closes #6275 
This PR fixes the "Empty state component" and "Table" links in the ["Empty states" table demo](https://www.patternfly.org/v4/components/table/react-demos#empty-states).

fix(Table): fix broken links in table's empty state demo

---

packages/react-log-viewer/src/LogViewer/LogViewer.tsx
packages/react-log-viewer/src/LogViewer/LogViewerContext.tsx
packages/react-log-viewer/src/LogViewer/LogViewerRow.tsx
packages/react-log-viewer/src/LogViewer/demos/LogViewer.md
packages/react-log-viewer/src/LogViewer/examples/LogViewer.md
packages/react-log-viewer/src/LogViewer/index.ts
packages/react-log-viewer/src/react-window/createListComponent.ts

**What**: Closes #6237 
This PR includes:
1. Add a prop named `onScroll`, users could pass a callback function into it which takes 4 parameters: `scrollDirection`, `scrollOffset`, `scrollOffsetToBottom`, `scrollUpdateWasRequested`, the callback function will be called when scrolling the log window.
2. Add a prop named `footer` to allow users to set a footer at the bottom of the log viewer window and add an example about how to use the `footer` prop.
3. Update the demo, show how to use `onScroll` callback function and how to use the context of the log viewer to scroll to the bottom.

feat(LogViewer): add onScroll and footer props

---

packages/react-core/src/components/DescriptionList/DescriptionList.tsx
packages/react-core/src/components/DescriptionList/__tests__/DescriptionList.test.tsx
packages/react-core/src/components/DescriptionList/__tests__/__snapshots__/DescriptionList.test.tsx.snap
packages/react-core/src/components/DescriptionList/examples/DescriptionList.md
packages/react-integration/cypress/integration/descriptionlist.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/DescriptionListDemo/DescriptionListDemo.tsx

**What**: Closes #6181
In this PR:
- Adds `isCompact` property to `DescriptionList`
- Adds `isFluid` property to `DescriptionList`. The property description indicates this only applies to horizontal description lists, but I've also made it so that if only `isFluid` is passed to `DescriptionList`, the `isHorizontal` styling is also applied.

feat(DescriptionList): add compact and fluid modifiers

---

packages/react-core/src/components/Alert/Alert.tsx
packages/react-core/src/components/Alert/AlertToggleExpandButton.tsx
packages/react-core/src/components/Alert/__tests__/Alert.test.tsx
packages/react-core/src/components/Alert/__tests__/__snapshots__/Alert.test.tsx.snap
packages/react-core/src/components/Alert/examples/Alert.md
packages/react-integration/cypress/integration/alert.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/AlertDemo/AlertDemo.tsx

Alert: Add plain variant, add expandable inline

---

packages/react-console/src/components/AccessConsoles/__tests__/__snapshots__/AccessConsole.test.tsx.snap
packages/react-core/src/components/Select/SelectToggle.tsx
packages/react-core/src/components/Select/__tests__/Generated/__snapshots__/SelectToggle.test.tsx.snap
packages/react-core/src/components/Select/__tests__/__snapshots__/Select.test.tsx.snap
packages/react-core/src/components/Select/__tests__/__snapshots__/SelectToggle.test.tsx.snap

When the select toggle isn't for typeahead the aria-label prop is ignored. So when using `toggleAriaLabel` in the `Select` component that prop is ignored.

fix(SelectToggle): use aria-label prop

---

packages/react-table/src/components/TableComposable/Tbody.tsx
packages/react-table/src/components/TableComposable/Thead.tsx

**What**: a couple of props documentation comments on `Thead` and `Tbody` were incorrectly referring to `<tr>` (copy-pasted from `Tr` props).

Tbody, Thead: correct some copy-pasted prop comments

---

packages/react-core/src/components/Page/PageToggleButton.tsx
packages/react-core/src/components/Page/examples/Page.md
packages/react-core/src/components/Page/index.ts
packages/react-core/src/demos/NotificationDrawer/NotificationDrawer.md
packages/react-core/src/demos/Wizard/WizardDemo.md
packages/react-core/src/demos/examples/DashboardHeader.js

**What**: Closes #6174
Refactors:
`PageHeader` is integrated with a `Page` context to provide the managed nav toggle trigger / aria-expanded state. To maintain this functionality I added a `PageToggleButton` component that extends our `Button` component and contains the context consumer.

docs: refactor demos to use Masthead

---

packages/react-core/src/demos/examples/DashboardWrapper.js

Adds hrefs to `Nav` in `DashboardWrapper` to make it tabbable.

fix: wrapper nav should have hrefs

---

packages/react-core/src/components/Tabs/Tab.tsx
packages/react-core/src/components/Tabs/Tabs.tsx
packages/react-core/src/components/Tabs/TabsContext.ts
packages/react-core/src/components/Tabs/__tests__/Generated/__snapshots__/Tabs.test.tsx.snap
packages/react-core/src/components/Tabs/__tests__/__snapshots__/Tab.test.tsx.snap
packages/react-core/src/components/Tabs/__tests__/__snapshots__/Tabs.test.tsx.snap
packages/react-core/src/components/Tabs/examples/Tabs.md
packages/react-integration/cypress/integration/tabdisbleddemo.spec.ts
packages/react-integration/demo-app-ts/src/Demos.ts
packages/react-integration/demo-app-ts/src/components/demos/TabsDemo/TabsDisabledDemo.tsx
packages/react-integration/demo-app-ts/src/components/demos/index.ts

**What**: Closes #6162 
- Refactored Tab into it's own component in order to forwardRef for `Tooltip` in `aria-disabled` case re: [Original Request](https://github.com/patternfly/patternfly-design/issues/1066)
- Added disabled state examples to match core PR for same issue

Add Support for disabled state tabs

---

packages/react-integration/demo-app-ts/src/components/demos/TableDemo/TableRowClickDemo.tsx
packages/react-table/src/components/Table/Body.tsx
packages/react-table/src/components/Table/RowWrapper.tsx
packages/react-table/src/components/Table/TableTypes.ts
packages/react-table/src/components/Table/examples/Table.md
packages/react-table/src/components/Table/utils/decorators/treeRow.tsx
packages/react-table/src/components/TableComposable/Tr.tsx
packages/react-table/src/components/TableComposable/examples/ComposableTable.md

**What**: Closes #5444 
Changes:
- I removed the rowClickHandler piece from a different TableComposable example
- I added a new `Composable: Row click handler, hoverable & selected rows` example to TableComposable
- I updated the Legacy Table's `Row click handler and header cell tooltips/popovers` example to include hoverable/selectable features.
- I added keyboard handling to the `onRowClick` prop so that the event can be triggered using keyboard and not just mouse click

feat(Table): Add hoverable and selectable rows

---

packages/react-core/src/components/DragDrop/DragDrop.tsx
packages/react-core/src/components/DragDrop/Draggable.tsx
packages/react-core/src/components/DragDrop/Droppable.tsx
packages/react-core/src/components/DragDrop/DroppableContext.ts
packages/react-core/src/components/DragDrop/__tests__/DragDrop.test.tsx
packages/react-core/src/components/DragDrop/__tests__/__snapshots__/DragDrop.test.tsx.snap
packages/react-core/src/components/DragDrop/examples/DragDrop.md
packages/react-core/src/components/DragDrop/index.ts
packages/react-core/src/components/index.ts
scripts/generators/patternfly-4-component/templates/component/component.md.hbs
scripts/generators/patternfly-4-component/templates/component/component.tsx.hbs

**What**: Reimplement the parts we're interested in from react-beautiful-dnd while applying our own styling. Closes #6167
What this does:
- Adds `DragDrop`, `Draggable`, and `Droppable` components
- Animates dropping in invalid zone
- Add styles for hovering over invalid zone
- Animates items moving out of the way for draggable item
- Allow draggable item to be dropped into other lists
- Natural movement offset by where item is picked up
- Provides drop API for moving dropped items
**Additional issues**: Will need integration tests and to be used in Draggable datalist

Add Drag and Drop

---

packages/react-core/src/components/DataList/DataList.tsx
packages/react-core/src/components/DataList/examples/DataList.md
packages/react-core/src/components/DragDrop/DragDrop.tsx
packages/react-core/src/components/DragDrop/Draggable.tsx
packages/react-core/src/components/DragDrop/Droppable.tsx
packages/react-core/src/components/DragDrop/__tests__/__snapshots__/DragDrop.test.tsx.snap
packages/react-integration/cypress/integration/drawer.spec.ts

**What**: Putting data list rows (or any arbitrary list items that expect style based on a parent) leads to a situation where when moved into a portal it's styled completely differently. For this reason dragging from the main content to Sidebars, Drawers, and PageHeaders has been removed.
The `noWrap` prop was also added so that `<div>`s need not wrap the component. This was accomplished by using event targets instead of refs to the div and passing event handlers via `React.cloneElement`.
Towards https://github.com/patternfly/patternfly/issues/4376

fix(dragdrop): remove React.createPortal, add noWrap

---

packages/react-charts/src/components/ChartTheme/examples/ChartTheme.md

A user recently asked how to override the color of a single chart. We have several examples demonstrating custom color scales, themes, etc. However, we don't have any examples specifically showing how to override the stroke color of individual charts.
Fixes https://github.com/patternfly/patternfly-react/issues/6352

chore(charts): Add custom stroke color example

---

packages/react-charts/src/components/ChartBullet/examples/ChartBullet.md

A user recently asked how to override the labels for a bullet chart. We have several bullet chart examples, but nothing to show how to customize your labels.
Fixes https://github.com/patternfly/patternfly-react/issues/6355

chore(charts): Add custom labels example for bullet chart

---

packages/react-core/src/components/TreeView/TreeViewListItem.tsx

**What**: Closes #6314, #4395
`allExpanded` (TreeView) and `isExpanded` (TreeViewListItem) should override `defaultAllExpanded`/`defaultExpanded`.

fix(TreeView): isExpanded should override defaultExpanded

---

packages/react-core/src/components/TreeView/TreeViewListItem.tsx

The proposed usage would allow for the onSelect method to call `evt.preventDefault()` to prevent the nodes from toggling. This is useful for determining programmatically whether a node should be collapsed. Further, it allows for the tree to be expanded and locked by the integrator.
**What**: Closes #6350 

[ISSUE-6350] - allow onSelect to prevent the default behavior of toggling node collapse

---

packages/react-core/src/components/Wizard/WizardNavItem.tsx

**What**: Closes #6361 
After talking to @jgiardino and @seanforyou23, I think the wizard steps should be set to `aria-current="step"`. I'm not sure there's a scenario with wizard that clicking the wizard's step would entirely change what current page you're on. I think that likely all use cases make the most sense with step, as you are moving through wizard steps.

fix(Wizard): Update aria-current on wizard steps

---

packages/react-core/src/components/Dropdown/DropdownGroup.tsx

**What**: From issue #6454, I `forward DropdownGroup` custom props to the DOM. Now custom props can also be given to `ApplicationLauncherGroup`.
**Additional issues**: This is a simple change, should not create any issues

fix(DropdownGroup): Forward custom props to the DOM

---

packages/react-core/src/components/TextInput/TextInput.tsx
packages/react-core/src/helpers/resizeObserver.tsx

If the TextInput has the isLeftTruncated prop set to true, other page elements push on the input and change the dimensions. In this scenario, the recalculation for trimming the text won’t always happen.
This fix uses the `ResizeObserver` from https://github.com/patternfly/patternfly-react/pull/6528
Fixes https://github.com/patternfly/patternfly-react/issues/4710
After
https://user-images.githubusercontent.com/17481322/139476571-f32e19bd-0148-450d-b510-05d9a9aa4ee9.mov

react-core(fix): Use resizeObserver to trigger trimLeft calculation

---

packages/react-topology/src/behavior/withCreateConnector.tsx

**What**:
Currently the only way to manually hide connector context menu on drag end in topology is by returning null/empty array from the `onCreate` callback. But it is not possible to do so when rendering custom react elements (i.e. not using `ContextMenuItem`) for the choices.
The PR adds an additional option to the connector options which hides the connector menu on drag end when the option is set.

Add option to hide topology connector menu on drag end

---

packages/react-charts/src/components/ChartUtils/chart-resize.tsx
packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx
packages/react-core/src/helpers/index.ts
packages/react-core/src/helpers/resizeObserver.tsx

**What**: Closes #6227
This also fixes a type discrepancy in the resizeObserver and chart-resize functions
@dlabrecq, I'd love if you'd make sure I didn't create more problems by fixing the issue I found.

fix(CodeEditor): add resizeobserver to code editor

---

packages/react-console/src/components/AccessConsoles/AccessConsoles.tsx
packages/react-console/src/components/AccessConsoles/__tests__/__snapshots__/AccessConsole.test.tsx.snap

Commit 7be4bc4a92e208073ca3e38415df1f64a89506ee introduced a bug where
the displayed SelectOption label is the key and not the expected text
after changing option.

fix(acccessconsoles): use object type Select options values in order to not mix displayed text with the option keys

---

packages/react-core/package.json
packages/react-core/src/components/FileUpload/FileUpload.tsx
packages/react-core/src/components/FileUpload/FileUploadField.tsx
packages/react-core/src/components/FileUpload/__tests__/__snapshots__/FileUpload.test.tsx.snap
packages/react-core/src/components/FileUpload/examples/FileUpload.md
packages/react-integration/demo-app-ts/src/components/demos/FileUploadDemo/FileUploadDemo.tsx
yarn.lock

**What**: Closes #5545
* `onChange` is now split in more events, old event remain there for the compatibility
* `onTextChange` - when text area changes (@mturley edit: renamed from `onTextChanged`)
* `onFileInputChange` - called when internal `<input>` field emits its own `onChange` DOM event (@mturley edit: renamed from `onInputChange`)
* `onDataChange` - when data is loaded in the component (@mturley edit: renamed from `onDataChanged`)
* `onClearClick` - when clear button is clicked (@mturley edit: renamed from `onClearClicked`)
* react-dropzone upgraded to the `10.2.2`

fix(FileUpload): Improving events in the FileUpload

---

packages/react-table/src/components/Table/TableTypes.ts
packages/react-table/src/components/Table/TableTypes.tsx
packages/react-table/src/components/Table/examples/Table.md
packages/react-table/src/components/Table/utils/decorators/sortable.tsx
packages/react-table/src/components/TableComposable/examples/ComposableTable.md

**What**: Closes #5329
For both `Table` and `TableComposable` - the default sort direction can now be changed by setting `sortBy.defaultDirection` and will continue to default to ascending order.
Edit: updated to use a separate prop because using `sortBy.direction` meant that the starting sort order would change when toggling sort between different columns.

feat(Table): set default sort direction

---

packages/react-core/src/components/Menu/DrilldownMenu.tsx

fix(Menu): stop passing disableHover to DrilldownMenu DOM

---

packages/react-core/src/components/JumpLinks/JumpLinks.tsx

**What**: Closes #6156 
This PR updates the JumpLinks to always set the clicked JumpLink as active when clicked.
- calls `setActiveIndex` in each JumpLink's `onClick` to set that link as active.
- adds `isLinkClicked` boolean variable which disables the scroll listener from also calling `setActiveIndex` and overriding the clicked link's active state when the linked section scrolls into place.
- this fixes the issue of the last JumpLink never showing as active when the linked section doesn't reach the top of the page.

fix(jumplinks): fixed to always set clicked item as active

---

packages/react-core/src/components/ContextSelector/ContextSelectorItem.tsx
packages/react-core/src/components/ContextSelector/__tests__/__snapshots__/ContextSelector.test.tsx.snap
packages/react-core/src/components/ContextSelector/__tests__/__snapshots__/ContextSelectorMenuList.test.tsx.snap
packages/react-core/src/components/ContextSelector/examples/ContextSelector.md
packages/react-core/src/components/Menu/MenuItem.tsx
packages/react-core/src/demos/ComposableMenu.md

**What**: 
Closes #5635 
Closes #6573 
This PR:
Adds support for context selector items as links:
- Adds new `href` string prop, which when provided renders `<a>` tag instead of `<button>`
- Updates existing `disabled` functionality by checking for `href` prop:
- If `href` prop is not provided, no change to `disabled` attribute on rendered `<button>`
- If `href` prop is passed, do not add `disabled` attribute (invalid on `<a>` tag that will be rendered), instead set `aria-disabled=true` and `tabindex=-1`
Fixes `disabled` attribute being added to `MenuItem` anchor tags, which is invalid.
Updated composable menu context selector demo to include MenuItem as links.

feat(contextselector): added support for context selector items as links

---

packages/react-table/src/components/TableComposable/InnerScrollContainer.tsx
packages/react-table/src/components/TableComposable/OuterScrollContainer.tsx
packages/react-table/src/components/TableComposable/TableComposable.tsx
packages/react-table/src/components/TableComposable/Th.tsx
packages/react-table/src/components/TableComposable/Thead.tsx
packages/react-table/src/components/TableComposable/Tr.tsx
packages/react-table/src/components/TableComposable/examples/ComposableTable.md
packages/react-table/src/components/TableComposable/index.ts

**What**: Closes #6163 and #6463
Sticky columns:
- Adds `isStickyColumn`, `hasRightBorder`, `stickyMinWidth`, `stickyLeftOffset` (all Th) properties
- Adds `OuterScrollContainer` and `InnerScrollContainer` wrapper components to use for scrollable tables
- Adds new examples showing a single sticky column, multiple sticky columns, and sticky columns with a sticky header + descriptions in each example for prop usage
Nested headers:
- Adds `nestedHeaderColumnSpans` (TableComposable), `isSubheader` (Th), `hasNestedHeader` (Thead), `resetOffset` (Tr) properties
- Adds new examples showing a basic nested header and a nested header with expandable rows + descriptions for prop usage
Update - added nested header support as it builds on top of properties added by sticky columns

feat(ComposableTable): add sticky columns and nested headers

---

packages/react-core/src/demos/TextInputGroupDemo.md

**What**: Closes #6393
**Additional issues**: patternfly/patternfly-design#1088
Interaction proposal:

Add text input group demo

---

packages/react-core/src/demos/DateTimePicker.md

**What**: Closes #5858
Adding new demo DateTimePicker using CalendarMonth.
https://patternfly-react-pr-6545.surge.sh/demos/datetimepicker
Just a PoC, totally up for any debate, it is very simple for now.

feat(CalendarMonth): Added DateTimePicker demo

---

packages/react-core/package.json
packages/react-core/src/components/FileUpload/FileUpload.tsx
packages/react-core/src/components/FileUpload/__tests__/__snapshots__/FileUpload.test.tsx.snap
packages/react-core/src/components/FileUpload/examples/FileUpload.md
yarn.lock

Closes #6609
In order to keep the changes from #6139 without any breaking TypeScript changes, this reverts react-dropzone to 9.0.0 and makes some tweaks so the new refs/events still work:
* The Browse button had broken because #6139 sets a `ref` on the hidden `<input>` in order to make its `onClearClick` handler work. This ref overrode the internal ref set by react-dropzone and used for the manual browse functionality. This PR sets both refs (using some tricky legacy callback ref stuff) so that both the Browse button and the `onClearClick` prop can work. The callback refs are not ideal, but can be reverted if we ever end up upgrading to react-dropzone 11+.
* Note: the `getInputProps()` function used here does in fact return a `ref` function that we need for this, even though its …

fix(FileUpload): Downgrade react-dropzone back to 9.0.0 to avoid a breaking type change, fix behavior regressions

---

packages/react-core/src/components/Pagination/Pagination.tsx

**What**: Closes #6620 
This PR just updates the prop description for `toggleTemplate` to include the new `ofWord` prop added in https://github.com/patternfly/patternfly-react/pull/6500.

fix(pagination): updated toggleTemplate description to include ofWord prop

---

packages/react-core/src/components/Select/Select.tsx
packages/react-core/src/components/Select/__tests__/__snapshots__/Select.test.tsx.snap

**What**: 
Fixes https://github.com/patternfly/patternfly-react/issues/6625
Fix to not show the auto complete form for the TypeAhead Select component on Chrome

Fix for no autocomplete for Typeahead Select

---

package.json
packages/react-core/src/components/Select/Select.tsx
packages/react-docs/package.json
packages/react-integration/demo-app-ts/package.json
yarn.lock

Updates the types for `react` and `react-dom` to version 17 to align with the actual versions being used. Ran into this as I needed to use some updated types for another PR and these older versions were getting in the way.

chore: update react and react-dom types

---

packages/react-core/src/components/FileUpload/FileUpload.tsx
packages/react-core/src/components/Toolbar/ToolbarContent.tsx
packages/react-core/src/components/Toolbar/ToolbarGroup.tsx
packages/react-core/src/components/Toolbar/ToolbarItem.tsx
packages/react-core/src/components/Toolbar/ToolbarToggleGroup.tsx
packages/react-table/src/components/Table/TableTypes.tsx

Replaces comments for deprecations with proper JSDoc syntax which allows IDEs like VSCode to [highlight this](https://code.visualstudio.com/updates/v1_49#_deprecated-tag-support-for-javascript-and-typescript) this to the developer.
closes #6617

Use JSDoc comments for all deprecations

---

packages/react-core/src/components/Slider/Slider.tsx
packages/react-core/src/components/Slider/_tests_/__snapshots__/Slider.test.tsx.snap
packages/react-core/src/components/Slider/examples/Slider.md
packages/react-integration/cypress/integration/slider.spec.ts

**What**: Closes #5939
The changes I made makes the input resize every time the input value changes by setting the `--pf-c-slider__value--c-form-control--width-chars`. It was by default set to 3, now it is dynamic. Do we want to keep the width set to 3 and only when it is bigger change it?

fix(Slider): Input resizing

---

packages/react-core/src/components/ContextSelector/ContextSelector.tsx

**What**: Closes #6494 
I made some simple change followed the `Modal` module where I declare `disableFocusTrap` as a prop and use it 
```tsx
<FocusTrap 
active={!disableFocusTrap}
focusTrapOptions={{ clickOutsideDeactivates: true }}>
```
**Additional issues**: 
I could not use `yarn lint` and `pre-commit` hook also keep failing on me, I'm using Window 11. But when I try to use Gitpod, yarn lint ran smoothly 
Error log:
```bash
$ node --max-old-space-size=4096 node_modules/.bin/eslint --ext js,jsx,ts,tsx --cache
C:\Users\Administrator\Desktop\repo\patternfly-react\node_modules\.bin\eslint:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
^^^^^^^
SyntaxError: missing ) after argument list
at wrapSafe (internal/modules/cjs/loader.js:1001:16)
at Module._compile …
```

Feat FocusTrap to be made inactive in ContextSelector.tsx

---

packages/react-core/src/components/Slider/Slider.tsx
packages/react-core/src/components/Slider/examples/Slider.md

**What**: Closes #6644
I can't think of a quicker fix...
I also added one more example, I don't know if it is necessary, it is the example from the original issue https://github.com/patternfly/patternfly-react/issues/5833

fix(Slider): fixed examples with custom steps and input

---

packages/react-core/src/components/Alert/examples/Alert.md
packages/react-core/src/components/Alert/examples/AlertAsyncLiveRegion.tsx
packages/react-core/src/components/Alert/examples/AlertDynamicLiveRegion.tsx

chore(Alert): Convert examples to functional with typescript

---

packages/react-core/src/demos/CardDemos.md

chore(Card): Updated Card demos to use Select instead of Dropdown

---

packages/react-core/src/components/Popover/Popover.tsx
packages/react-core/src/components/Popover/__tests__/Generated/__snapshots__/Popover.test.tsx.snap
packages/react-core/src/components/Popover/__tests__/__snapshots__/Popover.test.tsx.snap

**What**: Closes #4210 
This PR:
- Forwards focus to close button within popover when triggering with VoiceOver click
- `cmd+F5` on a Mac to enable VO, then `ctrl+option+space` on button to trigger Popover (see [Activate a link or form control](https://dequeuniversity.com/screenreaders/voiceover-keyboard-shortcuts#vo-mac-navigation))
- Removes the optional `onTriggerEnter` function passed as a prop to Popper
- This function was duplicating the `onTriggerClick` functionality but targeted only at the `Enter` key, but that key press was triggering both functions so this seems to be unnecessary.

fix(popover): forwarded focus to close button with VoiceOver click

---

packages/react-core/src/components/MenuToggle/MenuToggle.tsx
packages/react-core/src/components/MenuToggle/__tests__/MenuToggle.test.tsx
packages/react-core/src/components/MenuToggle/__tests__/__snapshots__/MenuToggle.test.tsx.snap
packages/react-core/src/components/MenuToggle/examples/MenuToggle.md

**What**: Closes #6561
Added a new Menu Toggle example.

feat(MenuToggle): add plain with text variant

---

packages/react-catalog-view-extension/src/components/CatalogTile/CatalogTile.tsx
packages/react-catalog-view-extension/src/components/CatalogTile/__snapshots__/CatalogTile.test.tsx.snap
packages/react-core/src/components/Card/Card.tsx
packages/react-core/src/components/Card/__tests__/Card.test.tsx
packages/react-core/src/components/Card/__tests__/__snapshots__/Card.test.tsx.snap
packages/react-core/src/components/Card/examples/Card.md
packages/react-core/src/components/DragDrop/examples/DragDrop.md
packages/react-core/src/demos/Card/Card.md
packages/react-integration/cypress/integration/card.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/CardDemo/CardDemo.tsx

feat(Card): Add disabled card and clean up props

---

.eslintrc.json
packages/react-core/src/components/DualListSelector/DualListSelectorTree.tsx
packages/react-core/src/components/DualListSelector/DualListSelectorTreeItem.tsx
packages/react-core/src/components/DualListSelector/__tests__/__snapshots__/DualListSelector.test.tsx.snap
packages/react-core/src/components/DualListSelector/examples/ComposableTree.tsx
packages/react-core/src/components/DualListSelector/examples/DualListSelector.md

**What**: Closes #6401, Closes #6424

feat(DualListSelector): add composable tree example

---

packages/react-core/src/components/Toolbar/examples/Toolbar.md

fixes https://github.com/patternfly/patternfly-react/issues/6656

docs(toolbar): fixed toolbar link under props in jump links

---

packages/react-log-viewer/src/LogViewer/LogViewer.tsx
packages/react-log-viewer/src/LogViewer/LogViewerRow.tsx
packages/react-log-viewer/src/react-window/createListComponent.ts

**What**: Closes #6701 
Use a small trick to prevent list width from changing when user changes setting of showing scrollbar from 'Always' to 'Automatically'.

fix(LogViewer): fix the issue that scrollbar could compress the content of the logs

---

packages/react-core/src/components/Toolbar/Toolbar.tsx
packages/react-core/src/components/Toolbar/ToolbarChipGroupContent.tsx
packages/react-core/src/components/Toolbar/__tests__/Generated/__snapshots__/Toolbar.test.tsx.snap
packages/react-core/src/components/Toolbar/__tests__/__snapshots__/ToolbarToggleGroup.test.tsx.snap
packages/react-integration/cypress/integration/toolbar.spec.ts
packages/react-integration/demo-app-ts/src/components/demos/ToolbarDemo/ToolbarDemo.tsx
packages/react-topology/src/components/TopologyControlBar/__snapshots__/TopologyControlBar.test.tsx.snap
packages/react-topology/src/components/TopologyView/__snapshots__/TopologyView.test.tsx.snap

feat(Toolbar): support customizing text in ToolbarChipGroupContent

---

packages/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx

fix(ClipboardCopy): clear timer on unmount

---

packages/react-core/src/components/TimePicker/TimePicker.tsx
packages/react-core/src/components/TimePicker/TimePickerUtils.tsx
packages/react-core/src/components/TimePicker/examples/TimePicker.md

**What**: Closes #5853 and closes #6665
This PR:
- adds `minTime`, `maxTime`, and `invalidMinMaxErrorMessage` props which enable restricting the options shown to a user and throwing an error if the user inputs a time outside the constraints.
- adds an example to the time picker showing these new features.
- fixes bug from #6665 where custom delimiter is always changed to uppercase upon time selection/entry when `is24Hour` prop is not present.

feat(time picker): added min/max time constraints

---

packages/react-core/src/components/Slider/Slider.tsx
packages/react-core/src/components/Slider/_tests_/Slider.test.tsx
packages/react-core/src/components/Slider/_tests_/__snapshots__/Slider.test.tsx.snap
packages/react-core/src/components/Slider/examples/Slider.md

feat(Slider): add option to add Tooltip over thumb

---

packages/react-core/src/demos/JumpLinks.md

**What**: Closes #6580
Also updated offset to be dynamic based on the current height of the masthead and the jump links nav, since the page is responsive and the height varies on window size.

fix(jumplinks): Updated JumpLinks demo to allow for horizontal display

---

packages/react-core/src/components/JumpLinks/JumpLinks.tsx

**What**: Closes #6749 
This PR adds the `offset` prop to the dependencies array of the `scrollSpy` function's `useCallback`, fixing a bug where the scrollspy would never update if the `offset` prop changed.
In our previous demo the `offset` was hard coded so the bug didn't present itself, but the bug can be seen in https://github.com/patternfly/patternfly-react/pull/6731 where the `offset` prop defaults to `10` but then is set dynamically when rendered.

fix(jumplinks): fixed scrollspy breakpoints are incorrect if offset prop changes

---

packages/react-log-viewer/src/LogViewer/LogViewer.tsx
packages/react-log-viewer/src/react-window/createListComponent.ts

fix(log-viewer): update text selection behavior

---

packages/react-log-viewer/src/LogViewer/LogViewer.tsx

**What**: Closes #6758 
A simple revert to fix the build error in https://github.com/patternfly/patternfly-react/pull/6757

fix(LogViewer): remove footer classname

---

packages/react-integration/cypress/integration/tableselectable.spec.ts
packages/react-table/src/components/Table/SelectColumn.tsx
packages/react-virtualized-extension/src/components/Virtualized/__snapshots__/VirtualizedTable.test.tsx.snap

**What**: Closes #6695
This change does not currently apply to the tree view variant of Table. Adding in the `<label>` tag does not provide the correct padding (instead pushing out the checkbox such that the expand toggle is on top of it) and prevents the checkbox from being clicked. @mattnolting Am I missing a change here beyond adding label?

feat(Table): update clickable area for checks/radios

---

packages/react-core/src/components/ToggleGroup/ToggleGroup.tsx
packages/react-core/src/components/ToggleGroup/__tests__/__snapshots__/ToggleGroup.test.tsx.snap
packages/react-core/src/components/ToggleGroup/examples/ToggleGroup.md

feat(ToggleGroup): support disabling all items under the parent

---

packages/react-core/src/components/Select/Select.tsx
packages/react-core/src/components/Select/examples/Select.md

**What**: Closes #6629
Using a deep equality check to identify when typeahead Select children should be updated as a part of the Select's lifecycle (when the component updates).
The issue only existed for typeahead updates, and an example has been added for verification purposes (Select - Multiple).

fix(Select): update typeahead Select children when any option attribute changes

---

packages/react-table/src/components/Table/ActionsColumn.tsx
packages/react-table/src/components/Table/TableTypes.tsx
packages/react-table/src/components/TableComposable/examples/ComposableTable.md

`IAction` type is hard to use if you haven't seen the code (I don't think I found a lot of documentation regarding it as well).
Reason is that it cover 4 different things:
- An action Separator, where the `isSeparator` property is always true. 
- DropdownItem
- Button
- Custom component
I tried making it easier to consume by split into 4 different types (with the main features of each one) so that the types don't mix and is clear what properties will be used.
- `IActionSeparator` where `isSeparator` is *always* true (always false or undefined on the other types). 
- `IActionDropdownItem` where the `title` is a `ReactNode`, has the `onClick` and any property from `DropdownItemProps`
- `IActionOutsideItemButton` where the `title` is a string, has the `onClick`, `isOutsideDropdown` is true …

Improve IAction type

---

packages/react-table/src/components/Table/Body.tsx

**What**: Closes #6525
Only explicitly preventDefault when the spacebar is hit on a hoverable row, so avoid default scrolling behavior.

fix(Table): narrow logic for preventing event default onKeyDown

---

packages/react-core/src/components/Tabs/Tabs.tsx

feat(Tabs): enforce restricted type for children

---

packages/react-topology/src/elements/BaseNode.ts

**What**: Fixes #6814. Don't update the internal `this.dimensions` and `this.position` updates if the `width`, `height`, `x` and `y` attributes of the model doesn't change.
This might improve the performance of the topology a little bit. In the mobx dev tools on Firefox I found this "rerender reason" and found via logging that this case (mode.width === this.dimensions.width) was true for some rerenders. But for sure, this doesn't solve the biggest performance reason.
See also https://github.com/patternfly/patternfly-react/blob/main/packages/react-topology/src/elements/BaseNode.ts#L33-L42
None

Fixes #6814: Don't trigger mobx update when node dimension or position doesn't change

---

packages/react-core/src/components/Tabs/Tabs.tsx
packages/react-core/src/helpers/util.ts

**What**: Closes #5175 
This issue is because there the button only scrolls left or right when the tab is totally inside the view. However, when the window is small, the tab content could even be longer than the list width, which makes it can never find the element in the view. To solve the problem, I created a new optional prop named `strict` and made a judgment on the element width and the container width, if the container width is smaller than the element width and the `strict` is not set, we treat it as part in view. Only when strict mode is set, we will not take the element width and container width into consideration, which brings more flexibility to the function.
Also, I update the bounding to make it more precise to judge whether an element is in view when the element width is not …

fix(Tabs): enable tabs scroll button for small window

---

packages/react-table/src/components/Table/examples/LegacyTableTree.tsx
packages/react-table/src/components/TableComposable/examples/ComposableTableTree.tsx

correct the row index calculation by appending the child row offset for each level, for both `ComposableTableTree` and `LegacyTableTree`.
see [this POC][1] for an illustration (with visible row indices).
fixes: #6719
[1]: https://codesandbox.io/s/eager-golick-0jzpc

fix row index in tree table examples

---

packages/react-core/src/components/Button/examples/Button.md
packages/react-core/src/components/Button/examples/ButtonAriaDisabled.tsx
packages/react-core/src/components/Button/examples/ButtonAriaDisabledLinkTooltip.tsx
packages/react-core/src/components/Button/examples/ButtonAriaDisabledTooltip.tsx
packages/react-core/src/components/Button/examples/ButtonBlock.tsx
packages/react-core/src/components/Button/examples/ButtonCallToAction.tsx
packages/react-core/src/components/Button/examples/ButtonDisabled.tsx
packages/react-core/src/components/Button/examples/ButtonInlineSpanLink.tsx
packages/react-core/src/components/Button/examples/ButtonLinks.tsx
packages/react-core/src/components/Button/examples/ButtonProgress.tsx
packages/react-core/src/components/Button/examples/ButtonRouterLink.tsx
packages/react-core/src/components/Button/examples/ButtonSmall.tsx
packages/react-core/src/components/Button/examples/ButtonTypes.tsx
packages/react-core/src/components/Button/examples/ButtonVariations.tsx

chore(Button): Convert examples to typescript

---

packages/react-topology/src/behavior/useAnchor.tsx
packages/react-topology/src/behavior/useBendpoint.tsx
packages/react-topology/src/behavior/useDndDrag.tsx
packages/react-topology/src/behavior/useDndDrop.tsx
packages/react-topology/src/behavior/useDragNode.tsx
packages/react-topology/src/behavior/usePanZoom.tsx
packages/react-topology/src/behavior/useReconnect.tsx
packages/react-topology/src/behavior/useSelection.tsx
packages/react-topology/src/behavior/useSvgAnchor.tsx
packages/react-topology/src/behavior/withContextMenu.tsx
packages/react-topology/src/behavior/withCreateConnector.tsx
packages/react-topology/src/behavior/withRemoveConnector.tsx

**What**: Closes #6828
When using the `with...` HOC/wrappers, it's really difficult to understand the rendered React component tree in the react dev tools.
<br/>
**Without this PR** all components are just called "Component" and there is no indicator why we have so many nested components.
<br/>
**With this PR** it shows at least the component name again and the `with....` is rendered as small "badge" when selecting one component.
<br/>
These nodes are created with code like this, but it's currently not possible for me to create a CodeSandbox with this.
```tsx
return withCreateConnector(...)(
withDndDrop<...>(nodeDropTargetSpec)(
withEditReviewAccess('patch')(
withDragNode(nodeDragSourceSpec(type))(
withSelection({ controlled: true })(
withContextMenu(contextMenuActions)(WorkloadNode),
), …
```

Add component displayNames to topology with* HOC/wrappers

---

packages/react-core/src/components/TextInputGroup/TextInputGroupMain.tsx
packages/react-core/src/components/TextInputGroup/__tests__/__snapshots__/TextInputGroup.test.tsx.snap
packages/react-core/src/components/TextInputGroup/examples/TextInputGroupFilters.tsx
packages/react-core/src/components/TextInputGroup/examples/TextInputGroupUtilitiesAndIcon.tsx
packages/react-core/src/demos/examples/TextInputGroup/AttributeValueFiltering.tsx
packages/react-core/src/demos/examples/TextInputGroup/AutoCompleteSearch.tsx

On auto complete search:
- undoes default tab behavior prevention
- undoes input clearing on escape when focused on menu
- adds input clearing on tab when focused on menu
- adds placeholder text and custom aria label
- clarifies reasoning for conditionally rendered search icon
On text input group main:
- sets falsy input values as an empty string
- exposes value and placeholder props
**What**: Closes #6697
[Direct link to the auto complete search preview](https://patternfly-react-pr-6774.surge.sh/components/text-input-group/react-demos#auto-complete-search)

fix(TextInputGroup): address various issues

---

packages/react-core/src/components/Truncate/Truncate.tsx
packages/react-core/src/components/Truncate/__tests__/Truncate.test.tsx
packages/react-core/src/components/Truncate/__tests__/__snapshots__/Truncate.test.tsx.snap
packages/react-core/src/components/Truncate/examples/Truncate.md
packages/react-core/src/components/Truncate/examples/TruncateExamples.css
packages/react-core/src/components/Truncate/index.ts
packages/react-core/src/components/index.ts

feat(Truncate): added Truncate component

---

packages/react-core/src/demos/Tabs.md
packages/react-core/src/demos/Tabs/NestedTabsDemo.js
packages/react-core/src/demos/examples/Tabs/GrayTabs.tsx

docs(Tabs): add gray tabs demo (patternfly#6810)

---

packages/react-core/index.d.ts
packages/react-core/src/components/BackToTop/examples/BackToTop.css
packages/react-core/src/components/BackToTop/examples/BackToTop.md
packages/react-core/src/components/BackToTop/examples/BackToTopBasic.tsx
packages/react-core/src/components/Backdrop/examples/Backdrop.md
packages/react-core/src/components/Backdrop/examples/BackdropBasic.tsx
packages/react-core/src/components/Backdrop/examples/BackdropSpinner.tsx
packages/react-core/src/components/BackgroundImage/examples/BackgroundImage.md
packages/react-core/src/components/BackgroundImage/examples/BackgroundImageBasic.tsx
packages/react-core/src/components/Badge/examples/Badge.md
packages/react-core/src/components/Badge/examples/BadgeRead.tsx
packages/react-core/src/components/Badge/examples/BadgeUnread.tsx
packages/react-core/src/components/Banner/examples/Banner.md
packages/react-core/src/components/Banner/examples/BannerBasic.tsx
packages/react-core/src/components/Brand/examples/Brand.md
packages/react-core/src/components/Brand/examples/BrandBasic.tsx
packages/react-core/src/components/Breadcrumb/examples/Breadcrumb.md
packages/react-core/src/components/Breadcrumb/examples/BreadcrumbBasic.tsx
packages/react-core/src/components/Breadcrumb/examples/BreadcrumbDropdown.tsx
packages/react-core/src/components/Breadcrumb/examples/BreadcrumbWithHeading.tsx
packages/react-core/src/components/Breadcrumb/examples/BreadcrumbWithoutHomeLink.tsx
packages/react-core/src/components/Button/examples/ButtonAriaDisabled.tsx
packages/react-core/src/components/Button/examples/ButtonCallToAction.tsx
packages/react-core/src/components/Button/examples/ButtonDisabled.tsx
packages/react-core/src/components/Button/examples/ButtonInlineSpanLink.tsx
packages/react-core/src/components/Button/examples/ButtonLinks.tsx
packages/react-core/src/components/Button/examples/ButtonProgress.tsx
packages/react-core/src/components/Button/examples/ButtonSmall.tsx
packages/react-core/src/components/Button/examples/ButtonTypes.tsx
packages/react-core/src/components/Button/examples/ButtonVariations.tsx

**What**: Closes:
- #6785
- #6786
- #6787
- #6788
- #6778
- #6789
- #6790

chore: Convert examples to typescript

---

packages/react-core/src/components/DatePicker/DatePicker.tsx
packages/react-core/src/components/DatePicker/examples/DatePicker.md

**What**: Closes #6806 
1. Set the state of the date picker to pristine when the value is empty, so it will not trigger the validation check.
2. Add `onBlur` prop on the input so that users could define their own events when the input loses focus.
3. Fix the `displayName` of the component to make the props shown in the doc.

fix(DatePicker): update empty state validation and add onblur event

---

packages/react-core/src/components/Label/Label.tsx
packages/react-core/src/components/Label/__tests__/Label.test.tsx
packages/react-core/src/components/Label/__tests__/__snapshots__/Label.test.tsx.snap
packages/react-core/src/components/Label/examples/Label.md
packages/react-core/src/components/Label/examples/LabelEditable.tsx

**What**: Closes #6096
This changes the editable label div to go between being a button and an input, allowing the elements to be more semantic and more accessible in a screen reader. Core updates likely needed to fix the styling.

fix(Label): Make editable label more screen reader accessible

---

packages/react-table/src/components/Table/examples/LegacyTableActions.tsx
packages/react-table/src/components/Table/utils/decorators/cellActions.tsx
packages/react-table/src/components/TableComposable/Td.tsx
packages/react-table/src/components/TableComposable/examples/ComposableTableActions.tsx

closes #6799 
relates to: #https://github.com/patternfly/patternfly/issues/4607
Action cells should be populated either by overflow menus or single dropdowns. Extra buttons shouldn't appear there.

fix(table): fixed action example

---

packages/react-integration/cypress/integration/overflowmenu.spec.ts

**What**: Closes #6853
**Additional issues**: For now lets ignore this error. I think it's related to the sidebar being opened and over shadows the items in the page when size is small.

fix(OverflowMenu): ignore menu being covered in intg. tests

---

packages/react-docs/patternfly-docs.source.js

**What**: Closes #6855 enabling windows to hot refresh with changes on md files

fix: windows issue listening on md changes to refresh

---

packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx

**What**: Closes #6501 
The reason that causes this issue is that when the user defines their own `onChange` function, they will call `setState` to set the `value`, and the `value` will be passed as a prop to the CodeEditor. At the same time, in the CodeEditor component, it will first call `componentDidUpdate` to set the code to the new value, then it will also call the `onChange` function inside the CodeEditor component, where it will use `this.setState` (https://github.com/patternfly/patternfly-react/blob/main/packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx#L279) to set the changed value to the state even the value is already changed, which causes the unnecessary re-renders (Unlike functional component, every time `this.setState` is called, the component will be …

fix(CodeEditor): compare props and state to prevent re-renders

---

packages/react-core/src/components/TimePicker/TimePicker.tsx
packages/react-core/src/components/TimePicker/__tests__/TimePicker.test.tsx

**What**: Closes #6838 
When the focus is back on the time input, I disable the validation, I am not sure whether it makes more sense not to do any validation when the user is inputting the time.

fix(TimePicker): remove automatically validation from onChange event

---

packages/react-core/src/components/Select/Select.tsx

**What**: Closes #6871
Upon further investigation as part of this regression, it appears that `navigator` isn't always reliable when it comes to browser detection so I've removed the check. `inputAutoComplete` will always default to `off` and may still be passed in manually to target specific browsers or behaviors.

fix(Select): remove logic from default inputAutoComplete

---

packages/react-charts/src/components/ChartBar/examples/ChartBar.md

Updated bar chart example to show tooltips with data labels.
Closes https://github.com/patternfly/patternfly-react/issues/6816

chore(charts): Update bar chart example

---

packages/react-core/src/demos/PrimaryDetail.md

**What**: Closes #5130 
Per discussion with @mattnolting , part of this issue had previously been completed. What remained was updating examples/demos using the `pf-m-page-insets` class hardcoded, to instead use the `usePageInsets` prop. In this case only the Primary-detail demo had instances of the hardcoded class.
N/A

refactor(Primary-detail): replace hardcoded class with usePageInsets

---

packages/react-core/src/components/TimePicker/TimePicker.tsx
packages/react-core/src/components/TimePicker/TimePickerUtils.tsx
packages/react-core/src/components/TimePicker/examples/TimePicker.md

**What**: Closes #6837
When making time options for the dropdown menu, the `includeSeconds` props in not set. Which makes some errors when comparing option 00:00 with the min time 00:00:00 because they are not the same format.
Also, update the doc to prevent some building warnings.

fix(TimePicker): apply includeSeconds when making options

---

packages/react-catalog-view-extension/src/components/VerticalTabs/VerticalTabsTab.tsx

**What**: Closes #6805
The community developed `react-catalog-view` extension includes a component `VerticalTabsTab` which handles the `onClick` event oddly. This pr implements the fix which was outlined in https://github.com/patternfly/patternfly-react/issues/6805 by me.

VerticalTabsTab takes a custom base component now

---

packages/react-docs/UPGRADE-GUIDE.md

Closes #6910 
This PR adds additional context to the upgrade guide, clarifying that it details upgrading from V3 to V4 and linking to the relevant release notes.

chore(docs): added details to upgrade guide:

---

packages/react-core/src/components/Menu/MenuItem.tsx
packages/react-core/src/components/Menu/examples/Menu.md
packages/react-core/src/components/Menu/examples/MenuDrilldownSubmenuFunctions.tsx

**What**: Closes #5534
Allows `drilldownMenu` to accept a function returning a ReactNode. 
I've tested by wrapping the current example's drilldownMenus in function statements which works, but I'm not sure how well the component will respond to delays - primarily because the `MenuItem` needs to know the to-be-drilled-in menu's ID before the drilldownMenu would necessarily be returned/rendered. At present, I've invoked the drilldownMenu function in this drill in call to get the ID, but I'm wondering if it would be better to have a separate property for drilldownMenuId? Any thoughts?

feat(Menu): allow drilldown menu functions

---

packages/react-topology/src/components/groups/DefaultGroupExpanded.tsx
packages/react-topology/src/components/nodes/shapes/shapeUtils.ts
packages/react-topology/src/types.ts

**What**: 
Closes https://github.com/patternfly/patternfly-react/issues/6959
Adds NodeShape.circle back, treat NodeShape.circle as equivalent to NodeShape.ellipse.

fix(topology): Revert removal of NodeShape.circle, allow for either circle or ellipse

---

packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/TopologyPackage.tsx
packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/layouts/defaultLayoutFactory.ts
packages/react-topology/src/layouts/GridGroup.ts
packages/react-topology/src/layouts/GridLayout.ts
packages/react-topology/src/layouts/GridLink.ts
packages/react-topology/src/layouts/GridNode.ts
packages/react-topology/src/layouts/index.ts

Closes https://github.com/patternfly/patternfly-react/issues/6975
This PR adds a basic grid layout to the topology component:
It's basic, but it offers an "id" ordered grid that may be useful at scale scenarios:
I used it as a learning exercise to get familiar with the topology model, but I think it could be useful in the "demo-app" for layout comparisons.
I'd like to add a couple of more algorithms (in the following/separated PRs) that have good results at scale, like the concentric and breadth-first.
The rationale of this approach is that layout algorithms can introduce performance penalties at scale, so, having "basic" layouts with some tradeoffs could be a good starting point for alternatives.
P.S.: I'm not familiar with the code style of the Patternfly project, please, feel free to …

feature(topology): Add basic Grid layout to Topology component

---

packages/react-core/src/components/Select/Select.tsx
packages/react-core/src/components/Select/SelectToggle.tsx
packages/react-integration/cypress/integration/select.spec.ts

**What**: Closes #6245 & #6756
#6245 - the `enter` selection behavior is now prevented for typeahead until the arrow keys are used to move to an option.
#6756 - added additional `onClose` behaviors to two cases (when input div is manually clicked closed, and when tab is used to navigate off the input div) where the menu is closed but the internal state isn't reset.

fix(Select): prevent double enter, cover additional onclose cases

---

packages/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx

**What**: Closes #6863
Check the type of the `props.children`, if it's an array then concat it and convert to a string.

fix(ClipboardCopy): fix rendering comma issue in some situation

---

packages/react-core/src/components/Nav/NavGroup.tsx
packages/react-core/src/components/Nav/examples/Nav.md

**What**: Closes #6770
I chose to proceed with the second option I suggested, and implemented the suggestions of @thatblindgeye and @mcoker in that solution.

refactor(Nav): make nav group titles optional

---

packages/react-core/src/demos/Nav.md
packages/react-core/src/demos/NotificationDrawer/NotificationDrawer.md
packages/react-core/src/demos/Page/Page.md
packages/react-core/src/demos/examples/DashboardHeader.js
packages/react-integration/demo-app-ts/src/components/demos/PageDemo/PageDemo.tsx
packages/react-table/src/demos/Table.md

refactor(demo-masthead): use QuestionCircleIcon instead of HelpIcon in Masthead

---

packages/react-core/src/components/Menu/MenuItem.tsx
packages/react-core/src/components/Menu/examples/Menu.md

**What**: Closes #5840 
In addition to resolving the linked issue, this PR also fixes an issue with the View More example where using keyboard to "click" the view more button did not work correctly (essentially resulting in an error).

fix(Menu): screen reader correctly announces on view more

---

packages/react-table/src/components/TableComposable/examples/ComposableTable.md
packages/react-table/src/components/TableComposable/examples/ComposableTableActionsOverflow.tsx

docs(table): 6776 table example with overflow menu action

---

packages/react-core/src/components/NotificationDrawer/NotificationDrawer.tsx
packages/react-core/src/components/NotificationDrawer/__tests__/Generated/__snapshots__/NotificationDrawer.test.tsx.snap
packages/react-core/src/components/NotificationDrawer/__tests__/__snapshots__/NotificationDrawer.test.tsx.snap
packages/react-core/src/demos/NotificationDrawer/NotificationDrawer.md

**What**: Closes #5888 
- Updated the NotificationDrawer component to be similar to the Tab component by using forwardRef to handle placing focus on the NotificationDrawer
- Added instructions on the React Demos page for how to manage focus

fix(NotificationDrawer): Drawer receives focus after opening

---

packages/react-core/src/components/Tabs/Tab.tsx
packages/react-core/src/components/Tabs/TabButton.tsx
packages/react-core/src/components/Tabs/examples/Tabs.md

**What**: Closes #6311
Due to it seeming like there are issues when utilizing React refs to add aria attributes, I opted to include another way for linking a tooltip with a Tab component. The issue with React refs + Tooltip component seems to be that a) depending on the structure, a Tooltip may not render unless a user presses Enter on their keyboard (which this issue mentions), and b) Voice Over may not immediately announce the Tooltip (I've found that you have to focus the Tab, leave the Tab, then focus the same Tab again just to get VO to announce the Tooltip text contents, *despite* the fix to refs introduced here).
The original way of using a React ref + the Tooltip's `reference` prop will still work (with instructions indicating that an ID must be manually passed into the Tooltip, …

fix(Tabs): make tooltips more accessible

---

packages/react-core/src/demos/ComposableMenu/ComposableMenu.md
packages/react-core/src/demos/ComposableMenu/examples/ComposableDateSelect.tsx

**What**: Closes #6460
Adds a new date select demo to the composable menu demos page (can be moved if it's better in another place).
@mcarrano @mmenestr Does this match the design well enough re: the lighter/smaller grey text for the date? Also is the "custom" option supposed to function differently for this specific demo or will that be a follow up?

demo: date select dropdown

---

packages/react-core/src/components/AlertGroup/AlertGroup.tsx
packages/react-core/src/components/AlertGroup/AlertGroupInline.tsx
packages/react-core/src/components/AlertGroup/__tests__/AlertGroup.test.tsx
packages/react-core/src/components/AlertGroup/__tests__/__snapshots__/AlertGroup.test.tsx.snap
packages/react-core/src/components/AlertGroup/examples/AlertGroup.md

**What**: Closes #6890 - ability to add an overflow alert which can be clicked, examples using this to limit number of displayed alerts and the ability to click to see those that are hidden

Feat(AlertGroup): 6890 alert group overflow

---

packages/react-core/src/components/ChipGroup/examples/ChipGroup.md
packages/react-core/src/components/ChipGroup/examples/ChipGroupInline.tsx
packages/react-core/src/components/ChipGroup/examples/ChipGroupRemovableCategories.tsx
packages/react-core/src/components/ChipGroup/examples/ChipGroupWithCategories.tsx

**What**: Closes #7025 
Also renamed the examples to be more consistent with other example names ("With [feature]" as opposed to "[component] with [feature]")

chore(ChipGroup): convert examples to TypeScript/functional components

---

packages/react-core/src/components/Checkbox/examples/Checkbox.md
packages/react-core/src/components/Checkbox/examples/CheckboxControlled.tsx
packages/react-core/src/components/Checkbox/examples/CheckboxDisabled.tsx
packages/react-core/src/components/Checkbox/examples/CheckboxStandaloneInput.tsx
packages/react-core/src/components/Checkbox/examples/CheckboxUncontrolled.tsx
packages/react-core/src/components/Checkbox/examples/CheckboxWithBody.tsx
packages/react-core/src/components/Checkbox/examples/CheckboxWithDescription.tsx
packages/react-core/src/components/Checkbox/examples/CheckboxWithDescriptionBody.tsx

**What**: Closes #7022 
I also removed the`aria-label`s from various examples except for the standalone example (as that one was the only one that needs it). Otherwise screen readers wouldn't announce the label for the checkbox.

chore(Checkbox): convert examples to TypeScript/functional components

---

packages/react-core/src/components/ClipboardCopy/examples/ClipboardCopy.md
packages/react-core/src/components/ClipboardCopy/examples/ClipboardCopyBasic.tsx
packages/react-core/src/components/ClipboardCopy/examples/ClipboardCopyExpanded.tsx
packages/react-core/src/components/ClipboardCopy/examples/ClipboardCopyExpandedWithArray.tsx
packages/react-core/src/components/ClipboardCopy/examples/ClipboardCopyInlineCompact.tsx
packages/react-core/src/components/ClipboardCopy/examples/ClipboardCopyInlineCompactCode.tsx
packages/react-core/src/components/ClipboardCopy/examples/ClipboardCopyInlineCompactInSentence.tsx
packages/react-core/src/components/ClipboardCopy/examples/ClipboardCopyInlineCompactWithAdditionalAction.tsx
packages/react-core/src/components/ClipboardCopy/examples/ClipboardCopyJSONObject.tsx
packages/react-core/src/components/ClipboardCopy/examples/ClipboardCopyReadOnly.tsx
packages/react-core/src/components/ClipboardCopy/examples/ClipboardCopyReadOnlyExpanded.tsx
packages/react-core/src/components/ClipboardCopy/examples/ClipboardCopyReadOnlyExpandedByDefault.tsx

chore(Clipboard copy): convert examples to TypeScript/functional components

---

packages/react-core/src/components/Tooltip/examples/Tooltip.md
packages/react-core/src/components/Tooltip/examples/TooltipExamples.css

**What**: Closes #6972
The update was made to fix the last example on the tooltip docs.
sometimes the horizontal scrollbar was visible, and sometimes it wasn't... when it was visible, it cause the tooltip to misalign.
I made it so that in this example, the horizontal scrollbar is always visible.

fix(Tooltip): horizontal scroll bar causing misaligned tooltip

---

packages/react-core/src/components/CalendarMonth/CalendarMonth.tsx

**What**: Closes #7026 
Added internal state to the component so that an optional date prop works as intended whether it is passed in or not.
Also updated internal variables for the `buildCalendar` function, just to differentiate it from the `selectedDate` state.
Part of the #6654 epic

feat(CalendarMonth): make date prop optional

---

packages/react-core/src/components/TimePicker/TimePicker.tsx
packages/react-core/src/components/TimePicker/examples/TimePicker.md

**What**: Closes #6942 
I also updated how the TimePicker gets appended to its parent by passing in a `parent` value to the `menuAppendTo` prop. This should work more similarly to the Dropdown component, and should both resolve the issue of scrollbars appearing in Modals and also allow access to the TimePicker menu via Voice Over. This can be tested by going to the the below page on the build workspace and adding the following snippets of code as instructed.
Link: [PatternFly Modal](https://patternfly-react-pr-7043.surge.sh/components/modal)
On line 2, import TimePicker:
```js
import { Modal, Button, TimePicker } from '@patternfly/react-core';
```
To test appending to a parent, before line 43 (this should come before the closing `</Modal>` tag) add:
```js
<div>
<TimePicker …
```

fix(TimePicker): re-add ability to append to document body

---

packages/react-core/src/components/Menu/MenuContent.tsx

**What**: Closes #6842
unfortunately, the top/bottom padding for the MenuContent is = 0.5rem, so it makes the calculation complicated and dependent on font size. And when I try to load the value of the variable into react for possible calcluations, even that 0.5rem value is overridden by a subsequent rule so I cannot import the variable value directly into the component using react-tokens.
(i.e. `import c_menu__list_PaddingTop from '@patternfly/react-tokens/dist/esm/c_menu__list_PaddingTop';` returns the wrong value).
so for now, I use the default value of 16px, which is what the padding top and bottom defaults to with no custom overrides. Not sure if there is an alternate option right now...

fix(Menu): remove rogue scrollbar from drilldown menus

---

packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/TopologyPackage.tsx
packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/layouts/defaultLayoutFactory.ts
packages/react-topology/src/layouts/ConcentricGroup.ts
packages/react-topology/src/layouts/ConcentricLayout.ts
packages/react-topology/src/layouts/ConcentricLink.ts
packages/react-topology/src/layouts/ConcentricNode.ts
packages/react-topology/src/layouts/index.ts

This PR adds a new Concentric layout to the topology component.
Grid layouts work well to distribute nodes without taking into consideration edges,
but Concentric layouts have better results focused on high connectivity:
It's still experimental as there may be some corner cases not yet implemented, but it could be ready to have some feedback.
cc @jeff-phillips-18 @andrew-ronaldson
P.S: I have a pending optimized BreadthFirst algorithm that we're implementing in Kiali that will come in a future PR.

feature(Topology): Add Concentric layout to Topology component

---

packages/react-core/src/components/DescriptionList/DescriptionList.tsx
packages/react-core/src/components/DescriptionList/examples/DescriptionList.md
packages/react-core/src/components/Popover/Popover.tsx

Feat(DescriptionList): 6866 set width of term column

---

packages/react-table/src/components/Table/base/types.tsx
packages/react-table/src/components/TableComposable/Td.tsx
packages/react-table/src/components/TableComposable/examples/ComposableTable.md

**What**: Closes #7007, #6925
Adds description regarding potential z-index clashes for sticky table headers/columns, and broke out a few table examples into sections to put that blurb on top of all the sticky examples rather than just in the first example. LMK if it would be better inside the first sticky example and remove the sections.
Also addresses the rowIndex in the composable actions table callback. We've updated our example recently and the new example doesn't have this issue, but the old example method should now also work after adding `rowIndex` to the `Td` - `actions` object.

fix/docs(Table): add zindex docs, fix old rowIndex callback

---

packages/react-core/src/components/Dropdown/examples/Dropdown.md

**What**: Closes #6824 
Similar to PR #7087, this does not resolve the issue with appending to `document.body`, but rather cautions against it and provides the alternative of appending to `"parent"`. Appending to `"parent"` should offer the same benefits of `document.body`, but also allow assistive technologies to navigate into the component's contents and also keep things in a more proper DOM order.
I also created another codesandbox to show both variants being used inside of a Modal: [Dropdown appended inside Modal](https://codesandbox.io/s/dropdown-appended-inside-modal-zfluqj). This shows the similarity between them when opened inside a Modal, and also the difference if using Voice Over to try and navigate inside the Dropdown contents.

chore(Dropdown): update examples to show different appends

---

packages/react-core/src/components/Select/examples/Select.md

**What**: Closes #6150 
While this PR does not actually fix the issue of the Select component appended to `document.body` not working with screen readers, I think the best option instead is utilizing the `"parent"` value for `menuAppendTo` props across components (if we're able). While it isn't *as* evident in the updated example ([Appending document body vs parent](https://patternfly-react-pr-7087.surge.sh/components/select#appending-document-body-vs-parent)), I think the results are better seen in the below codesandbox link in which I utilized Modals (as I believe this was one of the major reasons for utilizing `document.body`).
I also added some instructions/warnings about appending the Select component to the `document.body`, to help make it clearer why it should be avoided and …

chore(Select): update examples to show different appends

---

packages/react-core/src/components/TextInput/TextInput.tsx

**What**: Closes #5324
when using `ClipboardCopy`, and passing an input text which contains newlines as a template string variable, they are omitted from the input value.
fix this in `TextInputBase` by replacing incoming newlines with whitespace characters, right before setting the input `value` (when the value is of `string` type).

fix newline interpolation of text input values

---

packages/react-code-editor/README.md

**What**: Hey guys, I've spent a lot of time figuring out why I haven't had the syntax highlighting in the code editor. I've forgotten to add the plugin to my webpack configuration.  Maybe specifying this in the readme can help others :-). What do you think? 
closes: #7141

Code Editor webpack plugin instructions

---

packages/react-core/src/components/Divider/examples/Divider.md
packages/react-core/src/components/Divider/examples/DividerInsetMedium.tsx
packages/react-core/src/components/Divider/examples/DividerInsetVariousBreakpoints.tsx
packages/react-core/src/components/Divider/examples/DividerUsingDiv.tsx
packages/react-core/src/components/Divider/examples/DividerUsingHr.tsx
packages/react-core/src/components/Divider/examples/DividerUsingLi.tsx
packages/react-core/src/components/Divider/examples/DividerVerticalFlex.tsx
packages/react-core/src/components/Divider/examples/DividerVerticalFlexInsetMedium.tsx
packages/react-core/src/components/Divider/examples/DividerVerticalFlexInsetVariousBreakpoints.tsx

**What**: Closes #7148 
Also made minor updates to two example names

chore(Divider): convert examples to TypeScript

---

packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/TopologyPackage.tsx
packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/layouts/defaultLayoutFactory.ts
packages/react-topology/src/layouts/BreadthFirstGroup.ts
packages/react-topology/src/layouts/BreadthFirstLayout.ts
packages/react-topology/src/layouts/BreadthFirstLink.ts
packages/react-topology/src/layouts/BreadthFirstNode.ts
packages/react-topology/src/layouts/index.ts

Fixes https://github.com/patternfly/patternfly-react/issues/7152
This is another useful algorithm to provide a BreadthFirst layout to the Patternfly Topology component.
Algorithms like "cola" and "dagre" have typically a cost to calculate the best visualization of a connected graph, but in the domain sometimes with not good results in terms of clarity and hierarchy of the relations:
A BreadthFirst layout may help in these cases, providing a natural "levels" approach that can be combined with other algorithms to help users to identify the dependencies between elements:
Note, this first version doesn't manage the overflow of a row. That's an optimization that can be added in follow-up work.
In Kiali, the algorithm may detect when a row is pretty large compared with others and can combine a …

feature(topology): Add BreadthFirst layout to the Topology component

---

packages/react-core/src/components/NumberInput/NumberInput.tsx
packages/react-core/src/components/NumberInput/examples/NumberInput.md

fix(NumberInput): Custom increment/decrement and thresholds

---

packages/react-core/src/components/DataList/DataListCheck.tsx

**What**: Closes #6762 
Based on the latest update to the DataListCheck component, I changed the attribute to which the `checked` prop was assigned. Having the `checked` attribute on the input element be _either_ of the `isChecked` or `checked` props was causing the behavior seen in the linked issue (a console warning of changing from uncontrolled to controlled, or vice versa). 
With this update, a console warning should only occur if *both* `checked` and `isChecked` props are passed in (which I've noted not to do in the prop descriptions). EDIT: this warning may only appear when testing in a local workspace and may not appear in the preview build.
If `checked` is passed in, then it's assigned to the correct `defaultChecked` attribute (previously being assigned to the checked attribute …

fix(DataListCheck): assign checked prop to correct attribute

---

packages/react-core/src/components/Select/SelectToggle.tsx

**What**: Closes #6983
Adds an extra check which prevents a click on the footer or footer item from toggling an open menu closed, for Selects that use `menuAppendTo` (the default inline select will already prevent this toggle). If a footer item should close the menu that should be handled in its event handler.

fix(Select): prevent footer clicks from toggling

---

packages/react-integration/demo-app-ts/src/index.tsx

fix(demo-app): reorder css imports to load in dark theme correctly

---

packages/react-core/src/helpers/Popper/Popper.tsx
packages/react-topology/src/behavior/useBendpoint.tsx
packages/react-topology/src/components/popper/Popper.tsx

Adds correct type information to instances of `useCallback` to prevent implicit `any` errrors. This type has [been tightened](https://github.com/eps1lon/types-react-codemod#usecallback-implicit-any) in React 18 so this is needed to land #7142.

Add correct types to instances of useCallback

---

packages/react-styles/src/css/components/Topology/topology-components.css

**What**: 
Closes https://github.com/patternfly/patternfly-react/issues/7135
Sets the hover state of a selected edge to show the edge line and arrow selected with the background as hover.
**Additional issues**: 
None
**Screen Shot**
/cc @mceledonia

Fix for edge style on hover of a selected edge

---

packages/react-core/src/components/Wizard/Wizard.tsx
packages/react-core/src/components/Wizard/WizardHeader.tsx
packages/react-core/src/components/Wizard/examples/Wizard.md

**What**: Closes #7122
Adds `descriptionComponent` property that controls the component wrapper of the description. Defaults to `'p'` and may be removed in a future breaking change release (leaving as `'div'`).

feat(Wizard): add description component type

---

packages/react-core/src/components/ApplicationLauncher/ApplicationLauncher.tsx
packages/react-core/src/components/ContextSelector/ContextSelector.tsx
packages/react-core/src/components/Dropdown/Dropdown.tsx
packages/react-core/src/components/OptionsMenu/OptionsMenu.tsx
packages/react-core/src/components/Select/Select.tsx
packages/react-core/src/helpers/Popper/Popper.tsx

docs(Dropdown): expose menuAppendTo in Dropdown prop docs

---

packages/react-core/src/components/ContextSelector/ContextSelector.tsx
packages/react-core/src/components/ContextSelector/ContextSelectorToggle.tsx

**What**: Closes #7104 
The issue here is that the menu closes because of ContextSelectorToggle's `mousedown` listener, since the menu is detached we need a separate reference for the detached container. 
The other problem is that with Popper `parentRef.current` is null because the menu isn't rendered and re-rendering it doesn't update the reference.

fix(ContextSelector): fix listener handling when using popper

---

packages/react-core/src/components/Tabs/Tabs.tsx
packages/react-core/src/components/Tabs/__tests__/Tabs.test.tsx
packages/react-core/src/components/Tabs/__tests__/__snapshots__/Tabs.test.tsx.snap
packages/react-core/src/demos/Tabs.md
packages/react-core/src/demos/examples/Tabs/TabsAndTablesAutoWidthTabs.tsx

**What**: Closes #6860
This PR also adds a prop to apply the `noBorderBottom` styling as needed by the associated demo, and a test to verify that prop works as expected.
Convenience link directly to the added demo: https://patternfly-react-pr-7183.surge.sh/components/tabs/react-demos/tables-and-tabs-auto-width-tabs/

docs(Tabs): add tables and tabs auto width tabs demo

---

packages/react-topology/src/components/groups/DefaultGroupCollapsed.tsx
packages/react-topology/src/components/groups/DefaultGroupExpanded.tsx
packages/react-topology/src/components/nodes/DefaultNode.tsx

**What**: 
Fixes #7220 
Fixes #7221 
Adds appropriate modifiers on groups and nodes based on the current drag operation.
Don't update group label when a drag operation is in process.

Fix for drop target highlight, group label position on drag

---

packages/react-core/src/components/Form/Form.tsx

fixes https://github.com/patternfly/patternfly-react/issues/7226
@tlabaj just to confirm from our convo the other day, if we end up adding breakpoint support for this var/prop later on, we can use this existing prop to either accept a string (a static max-width), or an object with default, sm, md, lg, etc values for max-widths at different breakpoints without introducing a breaking change? Or there may be another way to do it without a breaking change?

feat(form): added maxWidth prop

---

packages/react-core/src/components/ProgressStepper/ProgressStep.tsx
packages/react-core/src/components/ProgressStepper/__tests__/ProgressStepper.test.tsx
packages/react-core/src/components/ProgressStepper/examples/ProgressStepper.md
packages/react-integration/cypress/integration/progressstepper.spec.ts
packages/react-integration/demo-app-ts/src/Demos.ts
packages/react-integration/demo-app-ts/src/components/demos/ProgressStepperDemo/ProgressStepperDemo.tsx
packages/react-integration/demo-app-ts/src/components/demos/index.ts

feat(Progress stepper): Updated to use render prop for popover

---

packages/react-core/src/components/HelperText/HelperText.tsx
packages/react-core/src/components/HelperText/HelperTextItem.tsx
packages/react-core/src/demos/HelperText.md
packages/react-core/src/demos/examples/HelperText/HelperTextDynamicVariantDynamicText.tsx
packages/react-core/src/demos/examples/HelperText/HelperTextDynamicVariantStaticText.tsx
packages/react-core/src/demos/examples/HelperText/HelperTextStaticVariantDynamicText.tsx
packages/react-core/src/demos/examples/HelperText/HelperTextStaticVariantStaticText.tsx

**What**: Closes #5941 
[Helper text React demos](https://patternfly-react-pr-7250.surge.sh/components/helper-text/react-demos) for convenience.
These demos are based on conversation from the original issue/PR when Helper Text was created ( #5903 ), including design files, as well as some other component examples/demos on the PF site. The original issue this closes mentioned only the dynamic variant of the Helper Text component, but I think it is worth including additional demos to go over making the component accessible in other common use cases.
I also created an issue in org https://github.com/patternfly/patternfly-org/issues/2917 for a11y docs for the component. Depending on any feedback for this PR, I can transfer some of the repeated verbiage between demos to that a11y doc instead …

feat(HelperText): add react demos

---

packages/react-core/src/components/DataList/DataListCheck.tsx

**What**: Closes #7283 
This PR somewhat reverts the component to before PR #7163 while retaining the `defaultChecked` behavior.

fix(DataListCheck): revert checked prop

---

packages/react-docs/package.json

Removes React dependencies from the `react-docs` package, as this dependency is already present in the root of the workspace. Found this [during](https://github.com/patternfly/patternfly-react/pull/7146#discussion_r837760838) the React 18 upgrade so this can be considered part of landing #7142.

Use workspace version of React for documentation

---

packages/react-catalog-view-extension/buildSass.js
packages/react-catalog-view-extension/package.json
packages/react-catalog-view-extension/sass/react-catalog-view-extension/_filter-side-panel.scss
packages/react-catalog-view-extension/src/components/FilterSidePanel/examples/filterSidePanel.css

**What**: Closes #7059
Add a small spacing between the catalog sidebar filter title and items.
WHY no variable for this? Because the catalog uses hardcoded px everywhere.
In OpenShift console before:
With this PR:
In the documentation example before:
With this PR:
You can try this out in this PR codesandbox: https://codesandbox.io/s/react-catalog-sample-ik0m1v?file=/index.js

Catalog extension: Add a little bit spacing between title and items

---

packages/react-core/src/components/CodeBlock/CodeBlockCode.tsx

**What**: Closes #7156
Added a class to both the wrapper and the actual code component, though I'm unsure if just the wrapper className prop would suffice. LMK if it would be clearer to remove the code classname.

feat(CodeBlock): add class to code component

---

packages/react-styles/src/css/components/Topology/topology-components.css
packages/react-topology/src/components/groups/DefaultGroupExpanded.tsx

Also small fix for flickering cursor on edge drag.
**What**:
Closes https://github.com/patternfly/patternfly-react/issues/7300

Fix(topology): Fix error when a group has no visible children

---

packages/react-core/src/components/Page/examples/Page.md

**What**: Closes #6977 
[Centered section page example](https://patternfly-react-pr-7269.surge.sh/components/page#centered-section) for convenience.

chore(Page): update centered example to match Core

---

packages/react-integration/demo-app-ts/src/App.tsx
packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/TopologyPackage.tsx
packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/StyleNode.tsx
packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/data/generator.ts
packages/react-styles/src/css/components/Topology/topology-components.css

Adds dark styling adjustments.
Closes #7181 
Note:
As part of this PR, I added Patternfly-style variables for all color variables, since a large number of them needed to be overridden in dark theme. However, it does not exactly match Patternfly conventions because the associated classnames are slightly different that the Patternfly convention, and it seemed better to match the class names for clarity.
Also, the edges already had a variable system in place, so I did not bring this into the same convention either, but instead left it as is and initialized its values with values matching the convention above.
Exceptions to dark styling as spec'd in https://marvelapp.com/prototype/i195ic1/screen/85808125:
- Node badge colors are currently set directly on the rect, not in CSS, so this will …

Topology dark theme

---

ADVANCED-USAGE-README.md
packages/react-core/README.md

chore(docs):cleanup dead link

---

packages/react-core/src/components/Dropdown/DropdownMenu.tsx
packages/react-core/src/components/Menu/Menu.tsx
packages/react-core/src/components/Nav/NavList.tsx
packages/react-core/src/components/Toolbar/ToolbarExpandableContent.tsx
packages/react-core/src/components/Toolbar/ToolbarFilter.tsx
packages/react-core/src/components/Toolbar/ToolbarUtils.tsx
packages/react-topology/src/components/defs/SVGDefsSetter.tsx

In React 18 the default type for `context` is `unknown`, meaning that unless proper types are added the build will fail. This adds the correct types to these contexts when used in class component.
Needed to land #7142.

Add correct types for class components using context API

---

packages/react-charts/src/components/ChartCursorContainer/ChartCursorContainer.tsx
packages/react-charts/src/components/ChartUtils/chart-container.tsx

To support the dark theme, we need to style the vertical cursor used with tooltips. In order to do that, we must override Victory's cursor component.
https://github.com/patternfly/patternfly-react/issues/7360
Testing: Changed stroke style to red

fix(charts): Add style for tooltip cursor

---

packages/react-core/src/components/Tabs/Tabs.tsx
packages/react-core/src/components/Tabs/__tests__/Tabs.test.tsx
packages/react-core/src/demos/Tabs.md

**What**: Closes #7259
Convenience link to the updated demo:
https://patternfly-react-pr-7311.surge.sh/components/tabs/react-demos/open-tabs-with-secondary-tabs/

feat(tabs): add secondary border-bottom variation, update demos

---

packages/react-core/src/components/Wizard/Wizard.tsx
packages/react-core/src/components/Wizard/WizardNavItem.tsx
packages/react-core/src/components/Wizard/__tests__/Wizard.test.tsx
packages/react-core/src/components/Wizard/__tests__/__snapshots__/Wizard.test.tsx.snap

fix(Wixard): Fixed id not being applied to wizard step

---

packages/react-core/src/components/Select/SelectMenu.tsx
packages/react-topology/src/components/ComputeElementDimensions.tsx
packages/react-topology/src/components/contextmenu/ContextMenu.tsx
packages/react-topology/src/components/decorators/Decorator.tsx
packages/react-topology/src/components/edges/DefaultEdge.tsx
packages/react-topology/src/components/groups/DefaultGroupCollapsed.tsx
packages/react-topology/src/components/nodes/DefaultNode.tsx
packages/react-topology/src/components/popper/Popper.tsx
packages/react-topology/src/components/popper/Portal.tsx

Adds 'children' prop to the types of various components where they were missing.  In React 18 a component type (e.g. `FunctionComponent`) [no longer has](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210) an implicit `children` prop. 
This is needed to land #7142.

Add missing 'children' prop in several places

---

packages/react-core/src/components/ClipboardCopy/ClipboardCopyButton.tsx

**What**: Closes #1655 and closes #7096
Convenience links:
[Clipboard copy component](https://patternfly-react-pr-7335.surge.sh/components/clipboard-copy)
[Code block component](https://patternfly-react-pr-7335.surge.sh/components/code-block)
This follows the pattern introduced in PR #7332 

fix(ClipboardCopy): dynamic tooltip updates get announced

---

packages/react-core/src/components/Menu/Menu.tsx
packages/react-core/src/components/Panel/Panel.tsx
packages/react-core/src/demos/ComposableMenu/ComposableMenu.md
packages/react-core/src/demos/ComposableMenu/examples/ComposableTreeViewMenu.tsx
packages/react-core/src/helpers/KeyboardHandler.tsx

**What**: Closes #7083
The demo looks like it was broken when I added the KeyboardHandler to Menu, which expects the typical menu structure with menu components. I've added a property to allow a user to override the handler for custom menus and updated the demo accordingly.
There's a minor issue I'm still tracking down where toggling a tree folder somehow adds a tabindex to the group header and focuses it instead. If anyone has any ideas about this LMK.

fix: tree view menu keyboard handling

---

packages/react-core/src/components/Page/PageBreadcrumb.tsx
packages/react-core/src/components/Page/PageGroup.tsx
packages/react-core/src/components/Page/PageNavigation.tsx
packages/react-core/src/components/Page/PageSection.tsx
packages/react-core/src/components/Page/__tests__/__snapshots__/PageBreadcrumb.test.tsx.snap
packages/react-core/src/components/Page/__tests__/__snapshots__/PageGroup.test.tsx.snap
packages/react-core/src/components/Page/__tests__/__snapshots__/PageNavigation.test.tsx.snap
packages/react-core/src/components/Page/__tests__/__snapshots__/PageSection.test.tsx.snap

**What**: Closes #7078 
Also added a tabindex to other Page components that are able to have a `hasOverflowScroll` prop passed in.

fix(Page): add tabindex to components with hasOverflowScroll

---

packages/react-core/src/components/Tabs/examples/Tabs.md
packages/react-core/src/components/Tooltip/Tooltip.tsx
packages/react-core/src/components/Tooltip/examples/Tooltip.md

**What**: Closes #7331
Convenience links:
[Tooltip component](https://patternfly-react-pr-7332.surge.sh/components/tooltip)
[Tabs component](https://patternfly-react-pr-7332.surge.sh/components/tabs)
This PR also updates the Tab component that was previously updated in PR #6940.
Additionally, this PR could also resolve issues #7021 and #4446, but only when using the React or selector ref variants (or by using `aria="none"` and `aria-live="polite"` props). So this could potentially require altering how the Tooltip prop is setup or just a larger discussion, depending on if another solution can be found when not using a ref. This I believe was alluded to in another issue in this epic #1655: "One possible alternative is to render the tooltip as an aria-live region." …

fix(Tooltip): make ref variant announced by assistive tech

---

packages/react-log-viewer/src/LogViewer/LogViewer.tsx
packages/react-log-viewer/src/LogViewer/LogViewerRow.tsx
packages/react-log-viewer/src/ansi_up/ansi_up.ts
packages/react-log-viewer/src/react-window/createListComponent.ts

**What**: Closes #7354 
Reset ANSI styles every time when the container changes in case of ANSI style caching.

fix(LogViewer): clear ANSI cache when resetting the log window

---

packages/react-core/src/components/Modal/Modal.tsx
packages/react-core/src/components/Modal/ModalContent.tsx
packages/react-core/src/components/Modal/__tests__/Modal.test.tsx
packages/react-core/src/components/Modal/examples/Modal.md
packages/react-core/src/components/Modal/examples/ModalWithOverflowingContent.tsx

**What**: Closes #7079
Convenience link to the added example: https://patternfly-react-pr-7293.surge.sh/components/modal/#with-overflowing-content

docs(Modal): add example preserving a11y when content overflows

---

packages/react-core/src/helpers/Popper/Popper.tsx

**What**: Closes #7162 
With the help of @mturley, we identified that the contents of openshift's popover were being lazy loaded and stealthily swapping out the 'loading' indicator from their popover without triggering a state change or rerender.
We added a new observer to Popper (on which Popover is built) which will watch the entire contents of the Popper for any DOM tree mutations or updates. Whenever a mutation is detected, we will call Popper's 'update' function which reruns all of Popper's modifiers to make sure it's positioned appropriately. Popper's 'update' function uses debounce and is already being used to check Popper's position everytime the user scrolls or resizes the page, so it shouldn't introduce a performance problem. 
Also, I removed the `useEffect` which watches for …

fix(Popper): update Popper modifiers when child DOM changes

---

packages/react-catalog-view-extension/src/components/CatalogTile/__snapshots__/CatalogTile.test.tsx.snap
packages/react-core/src/components/Card/Card.tsx
packages/react-core/src/components/Card/CardTitle.tsx
packages/react-core/src/components/Card/__tests__/Card.test.tsx
packages/react-core/src/components/Card/__tests__/CardTitle.test.tsx
packages/react-core/src/components/Card/examples/Card.css
packages/react-core/src/components/Card/examples/Card.md
packages/react-core/src/components/Card/examples/CardLegacySelectable.tsx
packages/react-core/src/components/Card/examples/CardSelectable.tsx
packages/react-core/src/components/Card/examples/CardSelectableA11yHighlight.tsx
packages/react-core/src/demos/Card/Card.md
packages/react-core/src/demos/PrimaryDetail.md
packages/react-core/src/demos/examples/Tabs/ModalTabs.tsx

**What**: Closes #6798 
See PR #7091 for the previous attempt to resolve this issue and the issues identified with that approach.
This draft PR demonstrates a potential approach to improving Card accessibility by including hidden inputs for the purpose of screen reader navigation, this approach is similar to the one used for our [switch component](https://www.patternfly.org/v4/components/switch/html).
I believe this approach has been done in such a way that it is opt-in only and doesn't require a breaking change. The new structure is only rendered when a 'hasHiddenInput' prop is passed.
Currently, the checkboxes are all positioned at the top left corner of the page and there is no visual indication that the actual card is focused when its associated checkbox is …

fix(Card): indicate card selectivity and status if using a screen reader

---

packages/react-charts/src/components/ChartTheme/themes/base-theme.ts

fixes https://github.com/patternfly/patternfly-react/issues/7392
@dlabrecq I'm using the var for a border width here - as far as I can tell, everything still seems to be positioned correctly. Is this OK or should we try and make this change some other way?

fix(charts): support customizing tooltip border for dark theme

---

packages/react-topology/src/layouts/BaseLayout.ts
packages/react-topology/src/layouts/BreadthFirstLayout.ts
packages/react-topology/src/layouts/ColaGroupsLayout.ts
packages/react-topology/src/layouts/ColaLayout.ts
packages/react-topology/src/layouts/ConcentricLayout.ts
packages/react-topology/src/layouts/DagreLayout.ts
packages/react-topology/src/layouts/ForceLayout.ts
packages/react-topology/src/layouts/GridLayout.ts

**What**: 
Closes https://github.com/patternfly/patternfly-react/issues/7406
Changes the BaseLayout.startLayout method back to protected. Added an interim public method that can be used to access the startLayout method.

Revert BaseLayout startLayout method back to protected.

---

packages/react-core/src/components/TextArea/TextArea.tsx

The reference to the element of `TextArea` was incorrectly set to `HTMLInputElement`, this changes it to the correct type of `HTMLTextAreaElement`.
Closes #7432

Use correct type for TextArea ref

---

packages/react-core/src/components/Checkbox/Checkbox.tsx
packages/react-core/src/components/Checkbox/__tests__/Checkbox.test.tsx
packages/react-core/src/components/Menu/MenuItem.tsx
packages/react-core/src/components/Menu/__tests__/Menu.test.tsx
packages/react-core/src/components/Menu/examples/Menu.md
packages/react-core/src/components/Menu/examples/MenuWithCheckbox.tsx
packages/react-core/src/demos/ComposableMenu/ComposableMenu.md
packages/react-core/src/demos/ComposableMenu/examples/ComposableSimpleCheckboxSelect.tsx

**What**: Closes #7166  #7367 #7433
link to checkbox menu example:https://patternfly-react-pr-7368.surge.sh/components/menu#with-checkbox
A new demo was added to composable menus: https://patternfly-react-pr-7368.surge.sh/demos/composable-menu#composable-simple-checkbox-select
Issue to track  keyboard interactions #7382.

feat(Menu): Added support for checkbox menu

---

packages/react-core/src/components/HelperText/HelperTextItem.tsx
packages/react-core/src/components/HelperText/__tests__/__snapshots__/HelperText.test.tsx.snap

**What**: Closes #7263 
[HelperText dynamic demo preview build](https://patternfly-react-pr-7426.surge.sh/components/helper-text/react-demos#dynamic-variant-with-static-text)
Rather than utilizing `aria-live`, I instead added an element to the HelperTextItem with the `pf-u-screen-reader` class. That plus `aria-describedby` does seem to work with VO (would have to test with JAWS and NVDA). I wasn't sure whether we would want to expose the ability to customize this message for screen readers so I opted to not include that right now.
Another option could be using the `output` element which does work nicely with its implicit live region, but the issue then becomes repetitive text being announced from the live region and `aria-describedby` when a user begins typing in the input field. …

feat(HelperText): add screenreader text for dynamic variant

---

packages/react-core/src/components/Select/Select.tsx

**What**: Closes #7260
This issue was caused by #6966 which prevents enter from selecting an option in typeahead until `ArrowDown` is pressed to navigate into the menu. Creating still works with `ArrowDown` + `Enter`, and I'm not sure if this is a pattern we want to hold for all cases in typeahead. This PR will add an exception for `isCreatable` typeaheads where the create option is the only option in the list (creating a new option where there are still multiple options shown will still require arrow navigation to the create button).

fix(Select): allow enter to create when there is a single option

---

packages/react-core/src/components/ContextSelector/ContextSelector.tsx
packages/react-core/src/components/Dropdown/Dropdown.tsx
packages/react-core/src/components/Dropdown/DropdownWithContext.tsx
packages/react-core/src/components/Select/Select.tsx

**What**: Closes #7286 
This PR does not resolve issue #7398 as the Overflow Menu component itself doesn't use Popper or `menuAppendTo`
[Context selector](https://patternfly-react-pr-7434.surge.sh/components/context-selector/)
[Dropdown](https://patternfly-react-pr-7434.surge.sh/components/dropdown)
[Select](https://patternfly-react-pr-7434.surge.sh/components/select)
To test, copy+paste the following to the returned component in an example from the above links:
```
menuAppendTo="parent"
isFlippable
```

fix(Select): popper menu flips correctly

---

packages/react-core/src/components/Switch/Switch.tsx
packages/react-core/src/components/Switch/examples/Switch.md

**What**: Closes #7255
@tlabaj Did these work before? Uncontrolled inputs shouldn't be setting `isChecked`, and half of the example switches are redundant now that it works. I'm curious if this was meant as a static demo initially.

fix/docs(Switch): fix uncontrolled examples

---

packages/react-core/src/components/FileUpload/FileUploadField.tsx
packages/react-core/src/components/FileUpload/__tests__/__snapshots__/FileUpload.test.tsx.snap
packages/react-core/src/components/FileUpload/__tests__/__snapshots__/FileUploadField.test.tsx.snap
packages/react-core/src/components/FileUpload/examples/FileUpload.md

Adds placeholder and onBlur event to the TextArea within the FileUploadField component
Signed-off-by: Tomas Psota <tpsota@redhat.com>
**What**: Closes #7004 

feat(FileUploadField): forward more props to the TextArea

---

packages/react-core/src/components/Tooltip/Tooltip.tsx
packages/react-core/src/helpers/Popper/Popper.tsx

**What**: Closes #1457 
[Preview build - Tooltip](https://patternfly-react-pr-7399.surge.sh/components/tooltip)
Two new mouse events were added to the Popper component, both to resolve the above issue and for other components that use Popper to potentially utilize these events.
I also updated the default `exitDelay` for the tooltip with an explanation. Below is a video for the behavior when `exitDelay={0}` (_technically_ it works). I only chose a value of "300" to match the `entryDelay`, but if anyone has a default they'd prefer it can be tweaked.
https://user-images.githubusercontent.com/70952936/167679634-966e7641-6b79-48f6-ad1d-d94f83d3a50b.mov

feat(Popper): add mouse events for popper content

---

packages/react-core/src/components/Modal/ModalBoxTitle.tsx

**What**: Closes #7112 
While this PR resolves the issue linked, this does potentially produce a problem for keyboard users as they will be unable to display the tooltip since the title can't be focused. If this would be considered an issue (which if tooltips are being utilized, there's argument that the modal title *is* important), one solution to this would be to add `{...(hasTooltip && { tabIndex: 0 })}` on the ModalBoxTitle component so that keyboard users can tab to the title. This, however, a) goes against recommendations of not using tooltip on static elements (*this* could be resolved with a quick "don't use tooltips on static elements, except in cases of truncation"), and b) could also affect tests, as whether the title is focusable would have to be determined (though this might …

fix(Modal): tooltip visibility on modal open

---

packages/react-core/src/demos/ComposableMenu/examples/ComposableActionsMenu.tsx
packages/react-core/src/demos/ComposableMenu/examples/ComposableContextSelector.tsx
packages/react-core/src/demos/ComposableMenu/examples/ComposableDateSelect.tsx
packages/react-core/src/demos/ComposableMenu/examples/ComposableDrilldownMenu.tsx
packages/react-core/src/demos/ComposableMenu/examples/ComposableDropdwnVariants.tsx
packages/react-core/src/demos/ComposableMenu/examples/ComposableFlyout.tsx
packages/react-core/src/demos/ComposableMenu/examples/ComposableOptionsMenuVariants.tsx
packages/react-core/src/demos/ComposableMenu/examples/ComposableSimpleDropdown.tsx
packages/react-core/src/demos/ComposableMenu/examples/ComposableSimpleSelect.tsx
packages/react-core/src/demos/ComposableMenu/examples/ComposableTreeViewMenu.tsx

**What**: Closes #7291
For the demos I followed how the application launcher demo had it setup by wrapping the returned Popper component in a `div`. It looked to work well for all demos, though the flyout one rendered flyout menus incorrectly (this behavior also appears in the React workspace without this wrapper `div` however).
[Composable menu preview build](https://patternfly-react-pr-7417.surge.sh/demos/composable-menu) 

fix(ComposableMenu): update appendTo in demos

---

packages/react-core/src/components/Select/Select.tsx

The aria-describedby field is now added regardless of state of validation
Signed-off-by: Tomas Psota <tpsota@redhat.com>
**What**: Closes #7251

fix(Select): aria-describedby is added properly

---

packages/react-core/src/components/Select/Select.tsx

**What**: Closes #7132 
[Select view more example](https://patternfly-react-pr-7505.surge.sh/components/select#view-more-with-checkboxes) (can also copy+paste the code mentioned in the linked issue)

fix(Select): retain focus on correct checkbox after view more

---

packages/react-core/src/components/Drawer/Drawer.tsx
packages/react-core/src/components/Drawer/DrawerContent.tsx
packages/react-core/src/components/Drawer/DrawerPanelContent.tsx
packages/react-core/src/components/Drawer/__tests__/Drawer.test.tsx
packages/react-core/src/components/Drawer/__tests__/Generated/__snapshots__/DrawerContent.test.tsx.snap

**What**: Closes #7421
The root cause of the bug here is that `DrawerPanelContent` currently expects to be a direct child of `DrawerMain` and receive `drawerContentRef` from `DrawerContent`, but if the panel content is wrapped in a context that prop gets added to the context rather than `DrawerPanelContent`.
This resolution adds `DrawerContentRef` to the context for the drawer so that its value can be accessed by `DrawerPanelContent` regardless of what it may be wrapped in.
<details>
<summary>Easy way to test:</summary>
1. Open the [drawer examples on the live site](https://www.patternfly.org/v4/components/drawer/) and the [drawer examples on the preview for this branch](https://patternfly-react-pr-7531.surge.sh/components/drawer/) in separate tabs
2. Paste the …

Drawer bug typeerror on resize

---

packages/react-charts/src/components/Chart/Chart.tsx
packages/react-charts/src/components/ChartDonut/ChartDonut.tsx
packages/react-charts/src/components/ChartDonutUtilization/ChartDonutThreshold.tsx
packages/react-charts/src/components/ChartDonutUtilization/ChartDonutUtilization.tsx
packages/react-charts/src/components/ChartGroup/ChartGroup.tsx
packages/react-charts/src/components/ChartLegend/ChartLegend.tsx
packages/react-charts/src/components/ChartLegend/examples/ChartLegend.md
packages/react-charts/src/components/ChartLegendTooltip/ChartLegendTooltip.tsx
packages/react-charts/src/components/ChartLegendTooltip/ChartLegendTooltipContent.tsx
packages/react-charts/src/components/ChartPie/ChartPie.tsx
packages/react-charts/src/components/ChartStack/ChartStack.tsx
packages/react-charts/src/components/ChartTheme/examples/ChartTheme.md
packages/react-charts/src/components/ChartTooltip/examples/ChartTooltip.md
packages/react-charts/src/components/ChartUtils/chart-domain.ts
packages/react-charts/src/components/ChartUtils/chart-interactive-legend.ts
packages/react-charts/src/components/ChartUtils/chart-legend.ts
packages/react-charts/src/components/ChartUtils/chart-padding.ts
packages/react-charts/src/components/ChartUtils/chart-patterns.tsx
packages/react-charts/src/components/ChartUtils/chart-theme.ts
packages/react-charts/src/components/ChartUtils/chart-tooltip.ts
packages/react-charts/src/components/ChartUtils/index.ts
packages/react-charts/src/components/Patterns/examples/patterms.md

Added support for patterns. For examples, please see https://patternfly-react-pr-7390.surge.sh/charts/patterns.
Reviewed with @mceledonia, @heyethankim, & @mcarrano.
Design issue: https://github.com/patternfly/patternfly-design/issues/1136
Closes: https://github.com/patternfly/patternfly-react/issues/7537

Charts: Added support for patterns

---

packages/react-core/src/components/FileUpload/examples/FileUpload.md
packages/react-core/src/components/FileUpload/examples/FileUploadCustomPreview.tsx
packages/react-core/src/components/FileUpload/examples/FileUploadCustomUpload.tsx
packages/react-core/src/components/FileUpload/examples/FileUploadSimpleFile.tsx
packages/react-core/src/components/FileUpload/examples/FileUploadSimpleText.tsx
packages/react-core/src/components/FileUpload/examples/FileUploadTextWithEdits.tsx
packages/react-core/src/components/FileUpload/examples/FileUploadTextWithRestrictions.tsx

**What**: Closes #7465 -- All examples for the File Upload component have been converted from JavaScript to TypeScript. Additionally, all class components have been converted into functional components.

chore(FileUpload): convert examples to TypeScript/functional components

---

packages/react-core/src/components/CalendarMonth/CalendarMonth.tsx

**What**: Closes #7459 
[Calendar month preview build](https://patternfly-react-pr-7503.surge.sh/components/calendar-month)
@mcarrano It looks like there's another discrepancy between Core and React where the Core version shows 5 weeks and React shows 6. A comment in the React code mentions, "We will always show 6 weeks like google calendar," though it looks like Google calendar shows 5 weeks at a time (unsure if this is the default). Do you think this should also be updated in React to match Core's 5 week view?
N/A

fix(Calendar month): update to match Core

---

packages/react-core/src/components/AboutModal/AboutModal.tsx
packages/react-core/src/components/DualListSelector/DualListSelector.tsx
packages/react-core/src/components/DualListSelector/DualListSelectorPane.tsx
packages/react-core/src/components/Menu/MenuItem.tsx
packages/react-core/src/components/MenuToggle/MenuToggle.tsx
packages/react-core/src/components/Modal/Modal.tsx
packages/react-core/src/components/Select/Select.tsx
packages/react-core/src/components/Toolbar/ToolbarToggleGroup.tsx
packages/react-table/src/components/Table/Body.tsx
packages/react-table/src/components/Table/utils/decorators/cellActions.tsx
packages/react-table/src/components/Table/utils/decorators/collapsible.tsx
packages/react-table/src/components/Table/utils/decorators/info.tsx
packages/react-table/src/components/Table/utils/decorators/selectable.tsx
packages/react-table/src/components/Table/utils/decorators/sortable.tsx
packages/react-table/src/components/Table/utils/decorators/treeRow.tsx
packages/react-table/src/components/Table/utils/formatters.tsx

Since React 18 has stricter types than before some type-casts need to be added and expanded in order for the code to compile successfully.
Needed to land #7142

Add additional type-casts for React nodes

---

packages/react-core/src/components/ApplicationLauncher/__tests__/Generated/__snapshots__/ApplicationLauncherSeparator.test.tsx.snap
packages/react-core/src/components/ApplicationLauncher/__tests__/__snapshots__/ApplicationLauncher.test.tsx.snap
packages/react-core/src/components/Dropdown/InternalDropdownItem.tsx
packages/react-core/src/components/Dropdown/__tests__/Generated/__snapshots__/DropdownSeparator.test.tsx.snap
packages/react-core/src/components/Dropdown/__tests__/__snapshots__/Dropdown.test.tsx.snap
packages/react-core/src/components/Dropdown/__tests__/__snapshots__/InternalDropdownItem.test.tsx.snap
packages/react-core/src/components/Dropdown/examples/DropdownBasic.tsx
packages/react-core/src/components/OptionsMenu/__tests__/Generated/__snapshots__/OptionsMenuItem.test.tsx.snap
packages/react-core/src/components/OptionsMenu/__tests__/__snapshots__/OptionsMenu.test.tsx.snap
packages/react-core/src/components/OverflowMenu/__tests__/Generated/__snapshots__/OverflowMenuDropdownItem.test.tsx.snap

**What**: Closes #6109
it seems to work also adding the aria-labelledby prop, but the screen reader announces the tooltip before the item.
I tested the voice using the screen reader chrome plugin

Tooltip examples are not accessible on dropdown items

---

packages/react-core/src/components/LabelGroup/examples/LabelGroup.md
packages/react-core/src/components/LabelGroup/examples/LabelGroupBasic.tsx
packages/react-core/src/components/LabelGroup/examples/LabelGroupCategory.tsx
packages/react-core/src/components/LabelGroup/examples/LabelGroupCategoryRemovable.tsx
packages/react-core/src/components/LabelGroup/examples/LabelGroupEditableLabels.tsx
packages/react-core/src/components/LabelGroup/examples/LabelGroupOverflow.tsx
packages/react-core/src/components/LabelGroup/examples/LabelGroupVerticalCategoryOverflowRemovable.tsx

chore(LabelGroup): convert to TypeScript

---

packages/react-core/src/components/JumpLinks/examples/JumpLinks.md
packages/react-core/src/components/JumpLinks/examples/JumpLinksBasic.tsx
packages/react-core/src/components/JumpLinks/examples/JumpLinksExpandableVerticalWithSubsection.tsx
packages/react-core/src/components/JumpLinks/examples/JumpLinksVertical.tsx
packages/react-core/src/components/JumpLinks/examples/JumpLinksVerticalWithLabel.tsx
packages/react-core/src/components/JumpLinks/examples/JumpLinksWithCenteredList.tsx
packages/react-core/src/components/JumpLinks/examples/JumpLinksWithLabel.tsx

Signed-off-by: Tomas Psota <tpsota@redhat.com>
**What**: Closes #7494

chore(JumpLinks): convert examples to TypeScript

---

packages/react-core/src/components/List/examples/List.md
packages/react-core/src/components/List/examples/ListBasic.tsx
packages/react-core/src/components/List/examples/ListHorizontalRules.tsx
packages/react-core/src/components/List/examples/ListIcons.tsx
packages/react-core/src/components/List/examples/ListInline.tsx
packages/react-core/src/components/List/examples/ListLargeIcons.tsx
packages/react-core/src/components/List/examples/ListOrdered.tsx
packages/react-core/src/components/List/examples/ListPlain.tsx

**What**: Closes #7549 . List examples have all been converted from JS to TS.
**Additional issues**: This is not a critical issue. However, when writing out the TS examples for **ListIcons.tsx** and **ListLargeIcons.tsx**, there was an error on line 6110 of `node_modules/typescript/lib/typescript.js` regarding `replace` being undefined in the `normalizeSlashes` function. This was solved by changing the name of the imports of the icons from `BookOpen` to `BookOpenIcon` in both the markdown and the TS file, which works since the icons are export default. I'm not entirely sure as to what was going on but this issue was resolved with that solution.

chore(List): converted all examples to typescript

---

packages/react-core/src/demos/JumpLinks.md
packages/react-core/src/demos/examples/JumpLinks/JumpLinksWithDrawer.js

**What**: Closes #6582 
One item on this that I'm not sure about: I didn't see how the drawer was to be toggled in the core demo. I took a similar approach to the switch used to demonstrate vertical vs horizontal capabilities in the other JumpLinks demo, but am more than happy to change it.
Convenience link to the jump links demos page: https://patternfly-react-pr-7520.surge.sh/components/jump-links/react-demos
And the new demo itself: https://patternfly-react-pr-7520.surge.sh/components/jump-links/react-demos/with-drawer/

docs(JumpLinks): add jump links with drawer demo

---

packages/react-table/src/demos/Table.md

**What**: Fixed bug where icon and text for Filterable Table Demos was too close. Passed icon in as `icon` prop as suggested. Closes #6262

fix(Table): filterable table demo icon text spacing fix

---

packages/react-table/src/components/Table/utils/decorators/collapsible.tsx
packages/react-table/src/components/Table/utils/headerUtils.tsx
packages/react-table/src/components/TableComposable/examples/ComposableTableExpandable.tsx

**What**: Closes #3613
Updates collapsible transform logic to account for additional added columns (actions, selectable, etc). Currently using the internal `firstUserColumnIndex` flag but more fine grained control can be added by checking each feature flag individually instead.

fix(Table): account for added columns with expandable

---

packages/react-core/src/components/OverflowMenu/examples/OverflowMenu.md
packages/react-core/src/components/Toolbar/examples/Toolbar.md
packages/react-core/src/demos/Card/Card.md
packages/react-core/src/demos/PrimaryDetail.md
packages/react-integration/demo-app-ts/src/components/demos/OverflowMenuDemo/OverflowMenuDemo.tsx
packages/react-table/src/demos/Table.md

Addresses #7398 
Update various examples to pass `menuAppendTo='parent'` and `isFlipEnabled` to Dropdowns housed in OverflowMenus when it makes sense.
Examples updated:
- OverflowMenu
- Toolbar
- Card view demo
- Primary detail demo
- Sortable table demo
*note: the Dropdown menu has been configured so that isFlipEnabled flips the menus up/down depending on the available vertical space. The consumer can use the `position` prop to right align the menu when appropriate. That is the recommendation made to the issue reporter in this case.

chore(OverflowMenu): use position and isFlipEnabled props correctly in docs

---

packages/react-core/src/components/Label/Label.tsx
packages/react-core/src/components/LabelGroup/LabelGroup.tsx
packages/react-core/src/components/LabelGroup/examples/LabelGroup.md
packages/react-core/src/components/LabelGroup/examples/LabelGroupEditableAdd.tsx
packages/react-core/src/components/LabelGroup/examples/LabelGroupEditableAddDropdown.tsx
packages/react-core/src/components/LabelGroup/examples/LabelGroupEditableAddModal.tsx
packages/react-core/src/demos/LabelGroupDemos.md

**What**: Closes #7351
@mcarrano LMK if there are any adjustments I should make to the new examples and whether these should live in a demo page or remain on the examples page. I followed the scenarios pretty closely but didn't cover every shown variation (re: label colors, within groups or out, etc).
Added a new property `addLabel` to `LabelGroup` which puts the label within the label group but not included in the overflow list.

feat(LabelGroup): add editable label examples

---

packages/react-core/src/components/Masthead/MastheadToggle.tsx
packages/react-core/src/components/Masthead/__tests__/__snapshots__/Masthead.test.tsx.snap
packages/react-core/src/components/Page/PageSidebar.tsx
packages/react-core/src/components/Page/__tests__/Generated/__snapshots__/PageSidebar.test.tsx.snap
packages/react-core/src/components/Page/__tests__/__snapshots__/Page.test.tsx.snap
packages/react-core/src/demos/examples/DashboardHeader.js
packages/react-core/src/demos/examples/DashboardWrapper.js

chore(DashboardHeader): align DashboardHeader with core

---

packages/react-core/src/components/Popover/Popover.tsx
packages/react-core/src/components/ProgressStepper/ProgressStep.tsx
packages/react-core/src/components/ProgressStepper/__tests__/__snapshots__/ProgressStepper.test.tsx.snap

**What**: Closes #7200 . The `Popover` for the `ProgressStepper` component can now be accessed via the keyboard using **Space** and **Enter** keys. The issue was due to the `Popover` component not utilizing the `onTriggerEnter` prop in **Popover.tsx**. It now works like a native button but in a discussion with @thatblindgeye , this issue could be resolved in core by changing the `span` element to a `button` element.
**Additional issues**: No issues but read above. There are alternative solutions that may be easier resolutions. Another point to consider is simplifying the code for the `onTriggerEnter` cases.

fix(ProgressStepper): added onTriggerEnter prop to Popover

---

packages/react-charts/src/components/ChartLegend/examples/ChartLegend.md
packages/react-charts/src/components/Patterns/examples/patterms.md
packages/react-charts/src/components/ResizeObserver/examples/resizeObserver.md

Created a charts page showing how to resize charts using a `ResizeObserver`.
Although we have many examples showing how to resize charts, it seems some folks are not aware they're available. Creating dedicated examples should help make that more clear, similar to the pages for legends, themes, and tooltips.
Example: https://patternfly-react-pr-7587.surge.sh/charts/resize-observer
Closes https://github.com/patternfly/patternfly-react/issues/7585

Charts: Add ResizeObserver examples

---

packages/react-core/src/components/NotificationDrawer/NotificationDrawerGroup.tsx
packages/react-core/src/components/NotificationDrawer/NotificationDrawerListItemHeader.tsx
packages/react-core/src/components/NotificationDrawer/__tests__/NotificationDrawerGroup.test.tsx
packages/react-core/src/components/NotificationDrawer/__tests__/NotificationDrawerListItemHeader.test.tsx
packages/react-core/src/components/NotificationDrawer/__tests__/__snapshots__/NotificationDrawerGroup.test.tsx.snap
packages/react-core/src/components/NotificationDrawer/__tests__/__snapshots__/NotificationDrawerListItemHeader.test.tsx.snap
packages/react-core/src/components/Tabs/examples/Tabs.md
packages/react-core/src/components/Tabs/examples/TabsDynamic.tsx
packages/react-core/src/components/Toolbar/examples/Toolbar.md
packages/react-core/src/components/Toolbar/examples/ToolbarCustomChipGroupContent.tsx
packages/react-core/src/components/Wizard/examples/Wizard.md
packages/react-core/src/demos/CardDemos.md
packages/react-core/src/demos/Masthead.md
packages/react-core/src/demos/TileDemo.md
packages/react-core/src/layouts/Grid/examples/Grid.md

**What**: Closes #7581 
Cleans up duplicate ids and labels, as well as proper heading levels across the following docs:
- Tile react demos
- Masthead react demos
- Card react demos
- Grid layout examples
- Wizard examples
- Toolbar examples
- Tabs examples

chore: clean up docs a11y violations

---

packages/react-catalog-view-extension/package.json
packages/react-charts/package.json
packages/react-code-editor/package.json
packages/react-console/package.json
packages/react-core/package.json
packages/react-icons/package.json
packages/react-inline-edit-extension/package.json
packages/react-integration/demo-app-ts/package.json
packages/react-integration/package.json
packages/react-log-viewer/package.json
packages/react-styles/package.json
packages/react-table/package.json
packages/react-topology/package.json
packages/react-virtualized-extension/package.json
yarn.lock

In order to update Victory chart packages for https://github.com/patternfly/patternfly-react/issues/7614, PatternFly must first update TypeScript from 4.3.5 to 4.7.4.
Closes https://github.com/patternfly/patternfly-react/issues/7662

Update TypeScript dependencies

---

packages/react-charts/src/components/ChartCursorTooltip/ChartCursorTooltip.tsx
packages/react-charts/src/components/ChartLegendTooltip/ChartLegendTooltip.tsx
packages/react-charts/src/components/ChartTooltip/examples/ChartTooltip.md
packages/react-charts/src/components/ChartUtils/chart-tooltip.ts

Ensures style props are applied (merged) properly to `ChartLegendTolltip` components. Also added an example showing how to override sub-component styles.
Example:
https://patternfly-react-pr-7666.surge.sh/charts/tooltips#embedded-legend-with-custom-font-size
Closes https://github.com/patternfly/patternfly-react/issues/7633

fix(charts): Style prop fix for ChartLegendTooltip

---

packages/react-core/src/components/SearchInput/SearchInput.tsx
packages/react-core/src/components/SearchInput/__tests__/SearchInput.test.tsx
packages/react-core/src/components/SearchInput/__tests__/__snapshots__/SearchInput.test.tsx.snap

fix(Search Input): use popper to control the popup in advanced search

---

packages/react-code-editor/package.json

The `monaco-editor-webpack-plugin` dependency is never used directly by any of the code in PatternFly, so it is not required to specify it as a peer dependency.
This also helps projects that do not use WebPack (such as [ours](https://github.com/keycloak/keycloak-admin-ui/)) since NPM installs peer dependencies [by default](https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies). This change prevents unnecessary packages from getting installed by accident.
Closes #7676

fix(CodeEditor): remove monaco-editor-webpack-plugin as peer dependency

---

packages/react-table/src/components/Table/__tests__/__snapshots__/Table.test.tsx.snap
packages/react-table/src/components/Table/base/types.tsx
packages/react-table/src/components/Table/examples/LegacyTableActions.tsx
packages/react-table/src/components/Table/examples/LegacyTableCompoundExpandable.tsx
packages/react-table/src/components/Table/examples/LegacyTableExpandable.tsx
packages/react-table/src/components/Table/examples/LegacyTableSelectableRadio.tsx
packages/react-table/src/components/Table/examples/Table.md
packages/react-table/src/components/Table/utils/decorators/compoundExpand.tsx
packages/react-table/src/components/Table/utils/headerUtils.tsx
packages/react-table/src/components/TableComposable/Td.tsx
packages/react-table/src/components/TableComposable/examples/ComposableTableCompoundExpandable.tsx
packages/react-table/src/components/TableComposable/examples/ComposableTableExpandable.tsx
packages/react-table/src/components/TableComposable/examples/ComposableTableNestedExpandable.tsx
packages/react-table/src/components/TableComposable/examples/ComposableTableNestedTableExpandable.tsx
packages/react-table/src/demos/Table.md
packages/react-table/src/demos/table-demos/CompoundExpansion.jsx
packages/react-table/src/demos/table-demos/ExpandCollapseAll.jsx

**What**: Closes #7578 
Cleans up `id` props duplicated across demos/examples
Cleans up non-unique aria-labels on similar elements across demos/examples

chore(Table): clean up a11y violations in table docs

---

packages/react-core/src/components/DualListSelector/DualListSelector.tsx
packages/react-core/src/components/DualListSelector/DualListSelectorControl.tsx
packages/react-core/src/components/DualListSelector/DualListSelectorControlsWrapper.tsx
packages/react-core/src/components/DualListSelector/DualListSelectorList.tsx
packages/react-core/src/components/DualListSelector/DualListSelectorListItem.tsx
packages/react-core/src/components/DualListSelector/DualListSelectorPane.tsx
packages/react-core/src/components/DualListSelector/DualListSelectorTree.tsx
packages/react-core/src/components/DualListSelector/examples/DualListSelector.md
packages/react-core/src/components/MultipleFileUpload/MultipleFileUpload.tsx
packages/react-core/src/components/MultipleFileUpload/MultipleFileUploadMain.tsx
packages/react-core/src/components/MultipleFileUpload/MultipleFileUploadStatus.tsx
packages/react-core/src/components/MultipleFileUpload/MultipleFileUploadStatusItem.tsx
packages/react-core/src/components/MultipleFileUpload/examples/MultipleFileUpload.md

**What**: Closes #7691, closes #7692 This is a proposed template for composable components, which includes the general structure and purpose of sub-components.
[Dual list selector](https://patternfly-react-pr-7603.surge.sh/components/dual-list-selector/)
[File upload - multiple](https://patternfly-react-pr-7603.surge.sh/components/file-upload---multiple)
The two components updated in this PR show how two of the different composable components could look. One being a component that is only composable (file upload multi) or one that has a non-composable and a composable structure (dual list selector).
For the dual list selector, I created a new level 2 heading for the "Composable structure" section to separate it out a little more. I'm not sure if this would end up causing any confusion, …

chore(DualListSelector/MultipleFileUpload): add composable structure and component descriptions

---

packages/react-core/src/components/Alert/Alert.tsx
packages/react-core/src/components/Alert/__tests__/__snapshots__/Alert.test.tsx.snap
packages/react-core/src/components/Masthead/examples/Masthead.md
packages/react-core/src/components/Menu/MenuGroup.tsx
packages/react-core/src/components/Menu/examples/Menu.md
packages/react-core/src/components/Menu/examples/MenuDrilldown.tsx
packages/react-core/src/components/Menu/examples/MenuDrilldownInitialState.tsx
packages/react-core/src/components/Menu/examples/MenuDrilldownSubmenuFunctions.tsx
packages/react-core/src/components/Nav/Nav.tsx
packages/react-core/src/components/Nav/examples/Nav.md
packages/react-core/src/components/Nav/examples/NavDrilldown.tsx
packages/react-core/src/components/OptionsMenu/OptionsMenuItemGroup.tsx
packages/react-core/src/components/OptionsMenu/OptionsMenuToggleWithText.tsx
packages/react-core/src/components/OptionsMenu/__tests__/Generated/__snapshots__/OptionsMenuItemGroup.test.tsx.snap
packages/react-core/src/components/OptionsMenu/__tests__/__snapshots__/OptionsMenu.test.tsx.snap
packages/react-core/src/components/OptionsMenu/examples/OptionsMenu.md
packages/react-core/src/components/Page/PageHeader.tsx
packages/react-core/src/components/Page/PageSidebar.tsx
packages/react-core/src/components/Page/PageToggleButton.tsx
packages/react-core/src/components/Page/examples/Page.md
packages/react-core/src/components/Page/examples/page.css
packages/react-core/src/components/Select/examples/Select.md
packages/react-core/src/components/Tabs/TabContent.tsx
packages/react-core/src/components/Tabs/examples/Tabs.md
packages/react-core/src/components/Tabs/examples/TabsDynamic.tsx
packages/react-core/src/components/ToggleGroup/examples/ToggleGroup.md
packages/react-core/src/components/TreeView/examples/TreeView.md

**What**: Closes #7596 
- Tree view examples
- Select examples
- Navigation examples
- Toggle group examples
- Tab content examples
- Page examples
- Menu examples
- Options menu examples
- Masthead examples
Notes:
- Page example pages include color contrast violations for which I implemented a quick fix, but also opened core issues to fix more permanently.
- I noticed the `Beta feature` alert on beta components was throwing an a11y error about heading level and aria-labels on divs. I don't believe that Alerts need the generated aria-label on divs, since that aria label programmatically matches the `pf-u-screen-reader` text in the Alert title. I will address the heading level violation in the beta tag in org after this PR merges.

chore: fix various a11y violations in examples (2)

---

packages/react-log-viewer/src/LogViewer/LogViewer.tsx
packages/react-log-viewer/src/LogViewer/utils/utils.tsx

**What**: Closes #7673 
The log viewer only processed the string data before and split them if there are `\n` in it. Now it also checks the string array data and splits them if needed.

fix(LogViewer): render correctly when there is '\n' in the string array

---

packages/react-core/src/demos/NotificationDrawer/NotificationDrawer.md

Closes #7723
Clean up unused imports
Add missing imports - now the demos should open up correctly in the codesandbox

chore(NotificationDrawer): Clean up demo imports

---

packages/react-topology/package.json
packages/react-topology/src/components/VisualizationSurface.tsx
yarn.lock

Replaces [`react-measure`](https://www.npmjs.com/package/react-measure) with [`react-resize-detector`](https://www.npmjs.com/package/react-resize-detector) due to lack of support for React 18. The `react-resize-detector` package is also a lot more popular and actively maintained, and comes with built-in functionality to debounce events.
This is needed to help close #7142

feat(VisualizationSurface): replace react-measure with react-resize-detector

---

packages/react-core/src/demos/PrimaryDetail.md

**What**: Closes #7312 
Added some work here that applies towards #7657 - this demo now supports bulk select, and the ability to delete cards. 
However in order to fully align this demo with core, a lot of additional logic/functionality is required, which is out of scope of the original issue to use the new raised variant for the card. For that reason I opened #7657
**Additional issues**: #7657

Primary Detail: use new raised card variant in demo, add bulk select

---

packages/react-core/src/components/CalendarMonth/CalendarMonth.tsx
packages/react-core/src/components/CalendarMonth/__tests__/CalendarMonth.test.tsx

**What**: Closes #7718
There was same issue with years in aria label. 31 December 2023 date had "31 January 2024" aria label. This should be also resolved by this pull request.

fix(Calendar month) aria labels for dates outside of the selected month are inaccurate

---

packages/react-core/src/components/Select/Select.tsx

**What**: Closes #7722
Fixes the update function to apply to all select variants. Even though this particular block was designed for typeahead selects initially its logic still applies to all variants as it recalculates options without a filter if none exists.

fix(Select): remove variant check from update logic

---

packages/react-core/src/components/Truncate/__tests__/Truncate.test.tsx
packages/react-core/src/components/Truncate/__tests__/__snapshots__/Truncate.test.tsx.snap

**What**: Closes #7643 . Unit tests revamp -- note that there was an issue with the `position` prop where if `position=start`, then only `pf-c-truncate__end` would render. However, `getByText` could not detect the inputted text as a result of `&lrm;` so a snapshot test was performed instead.
**Additional issues**: N/A.

chore(Truncate): component unit test revamp

---

packages/react-core/src/components/Wizard/Wizard.tsx
packages/react-core/src/components/Wizard/__tests__/Wizard.test.tsx

bug(Wizard): keep currentStep state aligned with startAtStep prop

---

packages/react-core/src/components/CalendarMonth/CalendarMonth.tsx
packages/react-core/src/components/CalendarMonth/examples/CalendarMonth.md
packages/react-core/src/components/CalendarMonth/examples/CalendarMonthDefault.tsx
packages/react-core/src/components/CalendarMonth/examples/CalendarMonthSelectableDate.tsx

**What**: Closes #6654 
Adds onMonthChange callback and updates the default calendar to make dates selectable and log month change events.

feat(CalendarMonth): add onMonthChange callback

---

packages/react-core/src/components/Dropdown/DropdownToggle.tsx
packages/react-core/src/components/Dropdown/__tests__/DropdownToggle.test.tsx
packages/react-core/src/components/Dropdown/__tests__/__snapshots__/DropdownToggle.test.tsx.snap
packages/react-core/src/components/Dropdown/examples/Dropdown.md
packages/react-core/src/components/Dropdown/examples/DropdownSplitButtonActionSecondary.tsx

**What**: Closes #7536 . Secondary styling option has been added to `DropdownToggle` component for split action button. An example was created and a unit test/snapshot was added.

feat(Dropdown): added secondary styling to split action button

---

packages/react-core/src/components/Radio/examples/Radio.md
packages/react-core/src/components/Radio/examples/RadioControlled.tsx
packages/react-core/src/components/Radio/examples/RadioDisabled.tsx
packages/react-core/src/components/Radio/examples/RadioLabelWraps.tsx
packages/react-core/src/components/Radio/examples/RadioReversed.tsx
packages/react-core/src/components/Radio/examples/RadioStandaloneInput.tsx
packages/react-core/src/components/Radio/examples/RadioUncontrolled.tsx
packages/react-core/src/components/Radio/examples/RadioWithBody.tsx
packages/react-core/src/components/Radio/examples/RadioWithDescription.tsx
packages/react-core/src/components/Radio/examples/RadioWithDescriptionAndBody.tsx

chore(Radio): convert examples to TypeScript

---

packages/react-core/src/components/Spinner/examples/Spinner.md
packages/react-core/src/components/Spinner/examples/SpinnerBasic.tsx
packages/react-core/src/components/Spinner/examples/SpinnerCustomSize.tsx
packages/react-core/src/components/Spinner/examples/SpinnerSizeVariations.tsx

chore(Spinner): converted examples to TypeScript

---

packages/react-table/src/components/Table/examples/LegacyTableHoverable.tsx
packages/react-table/src/components/TableComposable/Tr.tsx
packages/react-table/src/components/TableComposable/examples/ComposableTableHoverable.tsx

**What**: Closes #7689 
Updated the text that gets announced in the `output` element on the Tr component to either be "Row selected" or an empty string, as otherwise both the unselected row and the new selected row would have the text announced ("Unselected row" followed immediately by "Selected row").

fix(Table): update hoverable example to single select

---

packages/react-core/src/components/Menu/MenuItem.tsx
packages/react-core/src/components/MenuToggle/MenuToggle.tsx
packages/react-core/src/components/TextInputGroup/TextInputGroup.tsx
packages/react-core/src/components/TextInputGroup/TextInputGroupMain.tsx
packages/react-core/src/demos/ComposableMenu/ComposableMenu.md
packages/react-core/src/demos/ComposableMenu/examples/ComposableTypeaheadSelect.tsx

**What**: Closes #6888
As a part of this, the MenuToggle was switched from a `button` to a `div` since we cannot have a button within a button, and we want the Icon to clear typeahead input values to be inside of a button.
The build will fail and styling of this should not be tested until this core PR is merged: https://github.com/patternfly/patternfly/pull/4673

docs(Menu/MenuToggle): Composable Menu - Typeahead Select Demo

---

packages/react-core/src/components/TreeView/TreeView.tsx
packages/react-core/src/components/TreeView/TreeViewListItem.tsx
packages/react-core/src/components/TreeView/__tests__/__snapshots__/TreeView.test.tsx.snap
packages/react-core/src/components/TreeView/examples/TreeView.md

**What**: Closes #7378
Adds `hasSelectableNodes` prop that separates expansion & selection behaviors - clicking the row will select it while clicking the toggle button will trigger the expansion. This flag will also allow parent nodes to be selected (in addition to leaf nodes) and apply the current style modifier to them.

feat(TreeView): allow selection without expansion

---

packages/react-core/src/components/Page/Page.tsx
packages/react-core/src/components/Page/PageBreadcrumb.tsx
packages/react-core/src/components/Page/PageGroup.tsx
packages/react-core/src/components/Page/PageNavigation.tsx
packages/react-core/src/components/Page/PageSection.tsx
packages/react-core/src/components/Page/__tests__/Page.test.tsx
packages/react-core/src/components/Page/__tests__/__snapshots__/Page.test.tsx.snap
packages/react-core/src/demos/Page/Page.md
packages/react-core/src/helpers/constants.ts
packages/react-core/src/helpers/util.ts

**What**: Closes #7628 
**Link to new demo for convenience:** https://patternfly-react-pr-7764.surge.sh/components/page/react-demos/sticky-section-breadcrumb-with-breakpoints/
Adds vertical breakpoint support for the `sticky` prop -> renamed to `stickyOnBreakpoint`! 
Added new sticky breadcrumb react demo to align with the core demo: https://pf4.patternfly.org/components/page/html-demos/sticky-breadcrumb-on-medium/

feat(Page): add support for vertical breakpoints, add sticky breadcrumb demo

---

packages/react-core/src/components/MenuToggle/MenuToggle.tsx
packages/react-core/src/components/MenuToggle/MenuToggleAction.tsx
packages/react-core/src/components/MenuToggle/MenuToggleCheckbox.tsx
packages/react-core/src/components/MenuToggle/__tests__/__snapshots__/MenuToggle.test.tsx.snap
packages/react-core/src/components/MenuToggle/examples/MenuToggle.md
packages/react-core/src/components/MenuToggle/examples/MenuToggleSplitButtonAction.tsx
packages/react-core/src/components/MenuToggle/examples/MenuToggleSplitButtonActionPrimary.tsx
packages/react-core/src/components/MenuToggle/examples/MenuToggleSplitButtonActionSecondary.tsx
packages/react-core/src/components/MenuToggle/examples/MenuToggleSplitButtonCheckbox.tsx
packages/react-core/src/components/MenuToggle/examples/MenuToggleSplitButtonCheckboxPrimary.tsx
packages/react-core/src/components/MenuToggle/examples/MenuToggleSplitButtonCheckboxSecondary.tsx
packages/react-core/src/components/MenuToggle/examples/MenuToggleSplitButtonCheckboxWithText.tsx
packages/react-core/src/components/MenuToggle/index.ts

**What**: Closes #7085 
The toggle button is a little bit wider than in html demos, it's because I used `<CaretDownIcon />` instead of `<i class="fas fa-caret-down" aria-hidden="true"></i>`. I'm not sure if this will be a problem since the difference is just a couple of pixels. Would appreciate if someone could review also this fact.

feat(MenuToggle): add split button variants

---

packages/react-core/src/components/Menu/Menu.tsx
packages/react-core/src/demos/ComposableMenu/examples/ComposableSimpleCheckboxSelect.tsx

**What**: Closes #7382
[Menu with checkbox example](https://patternfly-react-pr-7743.surge.sh/components/menu#with-checkbox)
[Composable menu simple checkbox select](https://patternfly-react-pr-7743.surge.sh/demos/composable-menu#composable-simple-checkbox-select)
Updated the menu component logic as well as the composable menu with checkboxes demo

fix(Menu): can navigate via keyboard for checkbox variant

---

packages/react-charts/src/components/ChartAxis/ChartAxis.tsx
packages/react-charts/src/components/ChartLabel/ChartLabel.tsx
packages/react-charts/src/components/ChartLegend/ChartLegend.tsx
packages/react-docs/patternfly-a11y.config.js

This will prevent snapshot tests from generating new ids every time they run.
I will need to go back and generate unique ids in each of the charts examples that don't specify them as a follow up to this PR, but that should not block the release.

fix(charts): remove uniqueId generation for labels and axis ticks

---

packages/react-core/src/components/MenuToggle/MenuToggle.tsx

This should fix a type error reported in our latest release candidate.

fix(MenuToggle): undo type change causing errors

---

packages/react-charts/src/components/Chart/Chart.tsx
packages/react-charts/src/components/ChartArea/examples/ChartArea.md
packages/react-charts/src/components/ChartAxis/ChartAxis.tsx
packages/react-charts/src/components/ChartBar/examples/ChartBar.md
packages/react-charts/src/components/ChartBullet/ChartBullet.tsx
packages/react-charts/src/components/ChartBullet/examples/ChartBullet.md
packages/react-charts/src/components/ChartDonut/ChartDonut.tsx
packages/react-charts/src/components/ChartDonut/examples/ChartDonut.md
packages/react-charts/src/components/ChartDonutUtilization/ChartDonutThreshold.tsx
packages/react-charts/src/components/ChartDonutUtilization/ChartDonutUtilization.tsx
packages/react-charts/src/components/ChartDonutUtilization/examples/ChartDonutUtilization.md
packages/react-charts/src/components/ChartLegend/ChartLegend.tsx
packages/react-charts/src/components/ChartLegend/examples/ChartLegend.md
packages/react-charts/src/components/ChartLine/examples/ChartLine.md
packages/react-charts/src/components/ChartPie/ChartPie.tsx
packages/react-charts/src/components/ChartPie/examples/ChartPie.md
packages/react-charts/src/components/ChartScatter/examples/ChartScatter.md
packages/react-charts/src/components/ChartStack/examples/ChartStack.md
packages/react-charts/src/components/ChartTheme/examples/ChartTheme.md
packages/react-charts/src/components/ChartTooltip/examples/ChartTooltip.md
packages/react-charts/src/components/Patterns/examples/patterms.md
packages/react-charts/src/components/ResizeObserver/examples/resizeObserver.md
packages/react-charts/src/components/Sparkline/examples/sparkline.md
packages/react-docs/patternfly-a11y.config.js

This adds an `name` prop to `Chart` in order to resolve the docs a11y violations, related to duplicate IDs.
Victory uses the `name` prop as a prefix when creating child element IDs. This mimics that behavior so we don't need to create a new prop for `ChartAxis`, `ChartLegend`, etc.
https://github.com/patternfly/patternfly-react/issues/7675
Example:
When the top `Chart` component uses `name="chart1"`, axis tick label IDs are output as:
```
"chart1-ChartAxis-0-ChartLabel-0"
"chart1-ChartAxis-0-ChartLabel-1"
...
```
Dependent axis tick label IDs are output as:
```
"chart1-ChartAxis-1-ChartLabel-0"
"chart1-ChartAxis-1-ChartLabel-1"
...
```
And legend label IDs are output as:
```
"chart1-ChartLegend-ChartLabel-0"
"chart1-ChartLegend-ChartLabel-1"
...
```
This covers all the main `Chart` …

Add id prop to fix docs a11y violations

---

packages/react-integration/demo-app-ts/src/components/demos/DualListSelectorDemo/DualListSelectorTreeDemo.tsx
packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/DefaultGroup.tsx
packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/GroupHull.tsx

Works towards closing #7142. Fixes the types for the demo app so they match the expectations for React 18.

Correct types for demo app

---

packages/react-core/src/components/Select/Select.tsx
packages/react-core/src/components/Select/__tests__/Select.test.tsx

**What**: Closes #7452
I also converted the usage of `.innerText` in this component to instead use `.textContent` due to [an issue with JSDOM](https://github.com/jsdom/jsdom/issues/1245) that impacted my ability to add a test for this fix. I don't see this causing any errors based on my testing, but if there are any issues with it I have alternative approaches I can take to the issue.
Convenience link to the typeahead select example in this PR's preview: https://patternfly-react-pr-7800.surge.sh/components/select/#typeahead

fix(Select): apply focus styling to the "create" option

---

packages/react-integration/demo-app-ts/package.json
yarn.lock

Works towards closing #7142. Updates React Router to version 5 for the demo app to ensure compatibility with React 18. This change is completely [backwards compatible](https://reacttraining.com/blog/react-router-v5/).

Update to React Router v5 for the demo app

---

packages/react-core/src/components/Progress/examples/Progress.md
packages/react-core/src/components/Progress/examples/ProgressBasic.tsx
packages/react-core/src/components/Progress/examples/ProgressFailure.tsx
packages/react-core/src/components/Progress/examples/ProgressFailureWithoutMeasure.tsx
packages/react-core/src/components/Progress/examples/ProgressFiniteStep.tsx
packages/react-core/src/components/Progress/examples/ProgressInside.tsx
packages/react-core/src/components/Progress/examples/ProgressInsideSuccess.tsx
packages/react-core/src/components/Progress/examples/ProgressLarge.tsx
packages/react-core/src/components/Progress/examples/ProgressOutside.tsx
packages/react-core/src/components/Progress/examples/ProgressOutsideFailure.tsx
packages/react-core/src/components/Progress/examples/ProgressSingleLine.tsx
packages/react-core/src/components/Progress/examples/ProgressSmall.tsx
packages/react-core/src/components/Progress/examples/ProgressStepInstruction.tsx
packages/react-core/src/components/Progress/examples/ProgressSuccess.tsx
packages/react-core/src/components/Progress/examples/ProgressTitleOutsideOfProgressBar.tsx
packages/react-core/src/components/Progress/examples/ProgressTruncateTitle.tsx
packages/react-core/src/components/Progress/examples/ProgressWarning.tsx
packages/react-core/src/components/Progress/examples/ProgressWithoutMeasure.tsx

chore(Progress) convert examples to TypeScript

---

packages/react-core/src/components/Popover/examples/Popover.md
packages/react-core/src/components/Popover/examples/PopoverAdvanced.tsx
packages/react-core/src/components/Popover/examples/PopoverAlert.tsx
packages/react-core/src/components/Popover/examples/PopoverBasic.tsx
packages/react-core/src/components/Popover/examples/PopoverCloseControlled.tsx
packages/react-core/src/components/Popover/examples/PopoverCloseUncontrolled.tsx
packages/react-core/src/components/Popover/examples/PopoverReactRef.tsx
packages/react-core/src/components/Popover/examples/PopoverSelectorRef.tsx
packages/react-core/src/components/Popover/examples/PopoverWidthAuto.tsx
packages/react-core/src/components/Popover/examples/PopoverWithIconInTheTitle.tsx
packages/react-core/src/components/Popover/examples/PopoverWithoutHeaderFooterCloseNoPadding.tsx

chore(Popover) convert examples to TypeScript

---

packages/react-core/src/components/Page/Page.tsx

fix(Page): remove unecessary onPageResize default prop

---

packages/react-core/src/components/Page/PageBreadcrumb.tsx
packages/react-core/src/components/Page/PageGroup.tsx
packages/react-core/src/components/Page/PageNavigation.tsx
packages/react-core/src/components/Page/PageSection.tsx
packages/react-core/src/components/Page/__tests__/PageBreadcrumb.test.tsx
packages/react-core/src/components/Page/__tests__/PageGroup.test.tsx
packages/react-core/src/components/Page/__tests__/PageNavigation.test.tsx
packages/react-core/src/components/Page/__tests__/PageSection.test.tsx
packages/react-core/src/demos/JumpLinks.md
packages/react-core/src/demos/examples/BackToTop/BackToTopNameDemo.tsx

chore(Page): add aria label prop to page subcomponents explicitly
