patternfly/patternfly-react

packages/react-core/src/components/Alert/Alert.tsx, packages/react-integration/cypress/integration/alertcustomtimeout.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/AlertDemo/AlertCustomTimeoutDemo.tsx
**What**: Closes #4982 
//cc @QasimRRizvi
=> feat(alert): support callback on alert timeout

packages/react-core/src/components/Select/Select.tsx, packages/react-integration/cypress/integration/select.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectDemo.tsx
**What**: Closes #4448
~~**DO NOT MERGE**~~ READY FOR MERGE
=> fix(select): display label and not value in typeahead

packages/react-core/src/components/Select/Select.tsx, packages/react-core/src/components/Select/__tests__/__snapshots__/Select.test.tsx.snap, packages/react-core/src/components/Select/examples/Select.md
**What**: Closes # https://github.com/patternfly/patternfly-react/issues/5027
**Additional issues**: It is improvement and added new props.
=> #5027 - custom Chip render props in the multi Typehead select .

packages/react-core/src/components/Button/examples/Button.md
=> chore(Button): Fix sandbox for Button examples with tooltips

packages/react-datetime/src/components/DatePicker/DatePicker.tsx, packages/react-datetime/src/components/DatePicker/__tests__/__snapshots__/DatePicker.test.tsx.snap, packages/react-datetime/src/components/DatePicker/examples/DatePicker.md
=> fix(DatePicker): Expose date picker input

packages/react-core/src/components/Skeleton/Skeleton.tsx, packages/react-core/src/components/Skeleton/__tests__/__snapshots__/Skeleton.test.tsx.snap, packages/react-core/src/components/Skeleton/examples/Skeleton.md
=> fix(Skeleton): Add screen reader text to skeleton

packages/react-core/src/components/ContextSelector/ContextSelector.tsx, packages/react-core/src/components/ContextSelector/ContextSelectorFooter.tsx, packages/react-core/src/components/ContextSelector/__tests__/ContextSelectorFooter.test.tsx, packages/react-core/src/components/ContextSelector/__tests__/__snapshots__/ContextSelectorFooter.test.tsx.snap, packages/react-core/src/components/ContextSelector/examples/ContextSelector.md, packages/react-core/src/components/ContextSelector/index.ts, packages/react-integration/demo-app-ts/src/components/demos/ContextSelectorDemo/ContextSelectorDemo.tsx
=> feat(ContextSelector): add footer to selector

packages/react-core/src/components/Modal/Modal.tsx, packages/react-core/src/components/Modal/ModalBoxHeader.tsx, packages/react-core/src/components/Modal/ModalContent.tsx, packages/react-core/src/components/Modal/__tests__/ModalBoxHeader.test.tsx, packages/react-core/src/components/Modal/__tests__/__snapshots__/ModalBoxHeader.test.tsx.snap, packages/react-core/src/components/Modal/__tests__/__snapshots__/ModalContent.test.tsx.snap, packages/react-core/src/components/Modal/examples/Modal.md, packages/react-integration/cypress/integration/modal.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/ModalDemo/ModalDemo.tsx
=> feat(Modal): add help section to the modal header

packages/react-core/src/components/DataList/DataListAction.tsx
=> DataListAction: convert to Functional Component

packages/react-core/src/components/DataList/examples/DataList.md
=> fix(DataList): add documentation for properties of DataListDragButton

packages/react-core/src/components/Splitter/Splitter.tsx, packages/react-core/src/components/Splitter/__tests__/Splitter.test.tsx, packages/react-core/src/components/Splitter/__tests__/__snapshots__/Splitter.test.tsx.snap, packages/react-core/src/components/Splitter/examples/Splitter.md, packages/react-core/src/components/Splitter/examples/splitter.css, packages/react-core/src/components/Splitter/index.ts, packages/react-core/src/components/index.ts, packages/react-integration/demo-app-ts/src/components/demos/SplitterDemo/SplitterDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/index.ts
**What**: Closes #4715 
New issues created:
- Create examples which incorporate sliding interaction using mouse or keyboard to slide the splitter. - #5049
-- _We may decide we need to address #5049 before we can close this PR_
- Add Drawer and MasterDetails demos(?)/variants(?) which incorporate a sliding splitter. - #5050
=> feat(Splitter): add Splitter component

packages/react-core/src/components/DataList/examples/DataList.md, packages/react-core/src/components/Toolbar/ToolbarExpandIconWrapper.tsx, packages/react-core/src/components/Toolbar/ToolbarItem.tsx, packages/react-core/src/components/Toolbar/index.ts, packages/react-core/src/demos/DataListDemo.md, packages/react-table/src/demos/Table.md
=> feat(DataList): add expand/collapse all

packages/react-core/src/components/Pagination/Pagination.tsx, packages/react-core/src/components/Pagination/__tests__/Pagination.test.tsx, packages/react-core/src/components/Pagination/__tests__/__snapshots__/Pagination.test.tsx.snap, packages/react-core/src/components/Pagination/examples/Pagination.md, packages/react-integration/cypress/integration/pagination.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/PaginationDemo/PaginationDemo.tsx
=> feat(Pagination): add sticky modifier flag

packages/react-docs/RELEASE-NOTES.md
=> chore(release notes): Updated release notes for 2020.14

packages/react-core/src/components/ApplicationLauncher/__tests__/__snapshots__/ApplicationLauncher.test.tsx.snap, packages/react-core/src/components/Dropdown/DropdownItem.tsx, packages/react-core/src/components/Dropdown/DropdownMenu.tsx, packages/react-core/src/components/Dropdown/InternalDropdownItem.tsx, packages/react-core/src/components/Dropdown/__tests__/__snapshots__/Dropdown.test.tsx.snap, packages/react-core/src/components/Dropdown/examples/Dropdown.md, packages/react-core/src/components/OptionsMenu/__tests__/__snapshots__/OptionsMenu.test.tsx.snap, packages/react-core/src/helpers/__tests__/util.test.js, packages/react-core/src/helpers/util.ts, packages/react-integration/cypress/integration/dropdown.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/DropdownDemo/DropdownDemo.tsx
**What**: Closes #5039
Updates to determine what will allow disabled dropdown items to be announced by JAWS
=> Update disabled dropdown items

packages/react-table/src/test-helpers/data-helpers.tsx, packages/react-virtualized-extension/src/components/Virtualized/VirtualTableBody.tsx, packages/react-virtualized-extension/src/components/Virtualized/examples/VirtualizedTable.md, packages/react-virtualized-extension/src/components/Virtualized/examples/WindowScroller.md
Add an example each for virtualized table and window scrolling virtualized table using the composable table components
https://patternfly-react-pr-5122.surge.sh/extensions/virtual-scroll-table#using-composable-table-components
https://patternfly-react-pr-5122.surge.sh/extensions/virtual-scroll-window-scroller/#using-composable-table-components
=> add virtualized examples with composable components

packages/react-core/src/demos/Card/Card.md, packages/react-core/src/demos/PrimaryDetail.md
**What**: Closes #4884 
//cc @mcarrano to see this go to "Demo" and choose the primary detail card view demo.
=> feat(demo): add sticky bottom pagination to the card demo

packages/react-core/src/components/ActionList/ActionList.tsx, packages/react-core/src/components/ActionList/ActionListGroup.tsx, packages/react-core/src/components/ActionList/ActionListItem.tsx, packages/react-core/src/components/ActionList/__tests__/ActionList.test.tsx, packages/react-core/src/components/ActionList/__tests__/ActionListGroup.test.tsx, packages/react-core/src/components/ActionList/__tests__/ActionListItem.test.tsx, packages/react-core/src/components/ActionList/__tests__/__snapshots__/ActionList.test.tsx.snap, packages/react-core/src/components/ActionList/__tests__/__snapshots__/ActionListGroup.test.tsx.snap, packages/react-core/src/components/ActionList/__tests__/__snapshots__/ActionListItem.test.tsx.snap, packages/react-core/src/components/ActionList/examples/ActionList.md, packages/react-core/src/components/ActionList/index.ts, packages/react-core/src/components/index.ts, packages/react-integration/cypress/integration/actionlist.spec.ts, packages/react-integration/demo-app-ts/src/Demos.ts, packages/react-integration/demo-app-ts/src/components/demos/ActionListDemo/ActionListDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/index.ts
**What**: Closes #4880 
Adds `ActionList`, `ActionListGroup`, `ActionListItem` components.
`ActionList` allows a `hasIcons` property to indicate if the children are icons.
=> add action list

packages/react-core/src/components/Touchspin/Touchspin.tsx, packages/react-core/src/components/Touchspin/__tests__/Touchspin.test.tsx, packages/react-core/src/components/Touchspin/__tests__/__snapshots__/Touchspin.test.tsx.snap, packages/react-core/src/components/Touchspin/examples/Touchspin.md, packages/react-core/src/components/Touchspin/index.ts, packages/react-core/src/components/index.ts, packages/react-integration/cypress/integration/touchspin.spec.ts, packages/react-integration/demo-app-ts/src/Demos.ts, packages/react-integration/demo-app-ts/src/components/demos/TouchspinDemo/TouchspinDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/index.ts
=> feat(Touchspin): add touchspin component

packages/react-datetime/src/components/CalendarMonth/CalendarMonth.tsx, packages/react-datetime/src/components/CalendarMonth/examples/CalendarMonth.md, packages/react-datetime/src/components/DatePicker/DatePicker.tsx, packages/react-datetime/src/components/DatePicker/examples/DatePicker.md
**What**: Addresses @tlabaj 's feedback from #5026.
Temporary preview: http://patternfly-org-preview.s3-website.us-east-2.amazonaws.com/components/calendar-month
=> fix(calendarmonth): handle undefined onToggle and add docs note

packages/react-catalog-view-extension/src/components/FilterSidePanel/FilterSidePanelCategoryItem.tsx
=> fix(FilterSidePanelCategoryItem): fix typings

packages/react-table/src/components/Table/TableTypes.ts
=> revert table type definitions

packages/react-datetime/src/components/DatePicker/DatePicker.tsx
=> fix(datepicker): forward popoverprops

packages/react-charts/src/components/ChartLine/examples/ChartLine.md, packages/react-integration/demo-app-ts/package.json, packages/react-integration/demo-app-ts/src/components/demos/LineChartDemo/LineChartColorDemo.tsx, yarn.lock
=> fix(charts): replace victory with victory-zoom-container

packages/react-core/src/components/ClipboardCopy/ClipboardCopyToggle.tsx
=> bug: fix arrow orientation for expanded ClipboardCopy

packages/react-integration/cypress/integration/menu.spec.ts, packages/react-integration/demo-app-ts/src/Demos.ts, packages/react-integration/demo-app-ts/src/components/demos/MenuDemo/MenuDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/index.ts
=> Menu: Adds cypress tests and integration demos

packages/react-core/src/components/DescriptionList/DescriptionList.tsx, packages/react-core/src/components/DescriptionList/__tests__/DescriptionList.test.tsx, packages/react-core/src/components/DescriptionList/__tests__/__snapshots__/DescriptionList.test.tsx.snap, packages/react-core/src/components/DescriptionList/examples/DescriptionList.md, packages/react-integration/cypress/integration/descriptionlist.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/DescriptionListDemo/DescriptionListDemo.tsx
**What**: Closes #5054 
// cc @mcoker
=> feat(descriptionList): add suport to auto fit

packages/react-charts/src/components/ChartLegend/examples/ChartLegend.md
When a data series is hidden via the interactive legend example, the tooltip stops working. The tooltips will begin working again if the user moves the cursor away from the chart.
In order to fix the example, the chart's container should not be recreated from scratch each time the chart is rendered.
https://github.com/patternfly/patternfly-react/issues/5203
**Before**
**After**
=> charts(chore): Interactive legend example tooltips stop working

packages/react-core/src/components/Alert/Alert.tsx, packages/react-core/src/components/Alert/AlertIcon.tsx, packages/react-core/src/components/Alert/__tests__/Alert.test.tsx, packages/react-core/src/components/Alert/__tests__/__snapshots__/Alert.test.tsx.snap, packages/react-core/src/components/Alert/examples/Alert.md, packages/react-integration/cypress/integration/alert.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/AlertDemo/AlertDemo.tsx
**What**: Closes #5125 
//cc @mcoker
=> feat(alert): add support to custom icon

packages/react-core/src/components/DescriptionList/DescriptionList.tsx, packages/react-core/src/components/DescriptionList/__tests__/DescriptionList.test.tsx, packages/react-integration/demo-app-ts/src/components/demos/DescriptionListDemo/DescriptionListDemo.tsx
**What**: Closes #5226 
~~I hope this will be merged before we will release this.~~ 
**Edit**: I just realized it is too late because this mistake was already released. So my question is what should we do now?
Thanks
//cc @mattnolting
=> fix(descriptionList): change autoMinFitModifier to autoFitMinModifier

packages/react-integration/cypress/integration/menu.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/MenuDemo/MenuDemo.tsx
**What**: Closes #5224 
**Additional issues**: Follows #5211
=> fix(menu): update cypress tests

packages/react-core/src/components/JumpLinks/JumpLinks.tsx
**What**: Fixes issue in keycloak on https://github.com/srambach/keycloak-admin-ui .
=> fix(jumplinks): add offset prop

packages/react-charts/src/components/ChartCursorTooltip/ChartCursorTooltip.tsx, packages/react-charts/src/components/ChartLegendTooltip/ChartLegendTooltip.tsx, packages/react-charts/src/components/ChartLegendTooltip/ChartLegendTooltipContent.tsx, packages/react-charts/src/components/ChartUtils/chart-tooltip.ts
This resolves a type issue with the tooltip pointerLength.
Fixes https://github.com/patternfly/patternfly-react/issues/5244
=> Charts: Tooltip pointerLength error

packages/react-docs/RELEASE-NOTES.md
=> Chore: release notes for 2020.16

packages/react-core/src/components/Menu/examples/Menu.md
**What**: Closes #5261 
Fixes sentence casing of Menu example
=> fixed sentence case for Menu example

packages/react-core/src/components/Breadcrumb/BreadcrumbItem.tsx, packages/react-integration/cypress/integration/breadcrumb.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/BreadcrumbDemo/BreadcrumbDemo.tsx
**What**: Closes #5121 
//cc @SpyTec
=> feat(breadcrumb): add render prop to breadcrumb item

packages/react-core/src/components/DualListSelector/DualListSelectorListItem.tsx, packages/react-core/src/components/DualListSelector/__tests__/__snapshots__/DualListSelector.test.tsx.snap
=> fix(DualListSelector): Add type=button to DualListSelectorListItem button

packages/react-styles/src/css/components/Consoles/DesktopViewer.css, packages/react-styles/src/css/components/Consoles/VncConsole.css
=> react-console: some minor CSS improvements

packages/react-table/src/components/Table/HeaderCell.tsx, packages/react-table/src/components/TableComposable/Th.tsx, packages/react-virtualized-extension/src/components/Virtualized/__snapshots__/VirtualizedTable.test.tsx.snap
=> fix(Table): scope axe issue

packages/react-core/src/components/DualListSelector/DualListSelector.tsx
=> fix(dualListSelector): do not pass custom handlers to root div

packages/react-core/src/components/Checkbox/Checkbox.tsx, packages/react-core/src/components/Checkbox/__tests__/Checkbox.test.tsx, packages/react-core/src/components/Radio/Radio.tsx, packages/react-core/src/components/Radio/__tests__/Radio.test.tsx
=> fix(radio/checkbox): show error message if id is missing

.eslintrc.json, packages/react-charts/src/components/ChartBullet/ChartBullet.tsx, packages/react-charts/src/components/ChartBullet/ChartBulletTitle.tsx, packages/react-charts/src/components/ChartBullet/utils/chart-bullet-size.ts, packages/react-console/src/components/AccessConsoles/AccessConsoles.tsx, packages/react-core/src/components/Drawer/DrawerPanelContent.tsx, packages/react-core/src/components/Label/Label.tsx, packages/react-core/src/components/NotificationBadge/NotificationBadge.tsx, packages/react-core/src/components/Page/Page.tsx, packages/react-core/src/components/Radio/Radio.tsx, packages/react-core/src/components/Select/Select.tsx, packages/react-core/src/components/TimePicker/TimePicker.tsx, packages/react-core/src/components/TimePicker/TimePickerUtils.tsx, packages/react-core/src/components/Toolbar/ToolbarChipGroupContent.tsx, packages/react-integration/demo-app-ts/src/components/demos/TableDemo/TableComposableDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/TableDemo/TableFavoritesDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/TableDemo/TableSortableDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/DefaultGroup.tsx, packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/DefaultNode.tsx, packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/GroupHull.tsx, packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/NodePath.tsx, packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/NodePolygon.tsx, packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/NodeRect.tsx, packages/react-table/src/components/Table/Body.tsx, packages/react-table/src/components/Table/utils/decorators/selectable.tsx, packages/react-table/src/components/Table/utils/headerUtils.tsx, packages/react-topology/src/behavior/useDndDrag.tsx, packages/react-topology/src/behavior/useDndDrop.tsx, packages/react-topology/src/components/DefaultRemoveConnector.tsx, packages/react-topology/src/components/layers/Layer.tsx
**What**: Closes #5238 
//cc @redallen
=> chore(eslint): Add linting rule to disallow nested ternaries

packages/react-core/src/components/SearchInput/SearchInput.tsx, packages/react-core/src/components/SearchInput/__tests__/SearchInput.test.tsx
=> fix(SearchInput): hide clear button when onClear function is not set

packages/react-core/src/components/Nav/NavExpandable.tsx, packages/react-core/src/components/Nav/NavItem.tsx, packages/react-core/src/components/Nav/NavList.tsx, packages/react-core/src/components/Nav/__tests__/__snapshots__/Nav.test.tsx.snap, packages/react-core/src/components/Page/PageSidebar.tsx, packages/react-core/src/components/Page/__tests__/Generated/__snapshots__/PageSidebar.test.tsx.snap, packages/react-core/src/components/Page/__tests__/__snapshots__/Page.test.tsx.snap, packages/react-core/src/demos/Nav.md
=> fix(Nav): Make nav items keyboard and screen reader accessible

packages/react-table/src/components/Table/examples/Table.md, packages/react-table/src/demos/Table.md
=> fix(table): empty state should be consistent across demos and examples

packages/react-core/src/components/Nav/NavItem.tsx, packages/react-core/src/components/Nav/__tests__/__snapshots__/Nav.test.tsx.snap, packages/react-core/src/components/Page/__tests__/__snapshots__/Page.test.tsx.snap
**What**: Fixes issue from @mfrances17 
=> fix(nav): fix navitem tabindex casing

packages/react-docs/RELEASE-NOTES.md
=> Chore: Release notes 2021.01

packages/react-catalog-view-extension/src/components/CatalogTile/__snapshots__/CatalogTile.test.tsx.snap, packages/react-core/src/components/Tooltip/Tooltip.tsx, packages/react-core/src/components/Tooltip/__tests__/Generated/__snapshots__/Tooltip.test.tsx.snap, packages/react-core/src/components/Tooltip/__tests__/__snapshots__/Tooltip.test.tsx.snap, packages/react-topology/src/components/TopologyControlBar/__snapshots__/TopologyControlBar.test.tsx.snap
=> fix(Tooltip): only add aria when tooltip is visible/in the DOM

packages/react-core/src/components/Wizard/WizardFooterInternal.tsx, packages/react-core/src/components/Wizard/__tests__/Generated/__snapshots__/WizardFooterInternal.test.tsx.snap
=> fix(wizard): add cancel button class

packages/react-core/src/components/Spinner/Spinner.tsx, packages/react-core/src/components/Spinner/examples/Spinner.md, packages/react-integration/cypress/integration/spinner.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/SpinnerDemo/SpinnerDemo.tsx
=> feat(spinner): add isSVG

packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx
=> bug(codeeditor): copy to clipboard button can now be enabled solo

packages/react-table/src/components/Table/utils/decorators/index.ts, packages/react-table/src/components/Table/utils/headerUtils.tsx, packages/react-table/src/components/Table/utils/index.ts, packages/react-table/src/components/Table/utils/transformers.test.tsx, packages/react-table/src/components/Table/utils/transformers.tsx
**What**: Towards https://github.com/RedHatInsights/insights-rbac-ui/pull/651
=> fix(react-table): add decorators index file

packages/react-core/src/components/SearchInput/SearchInput.tsx, packages/react-core/src/components/SearchInput/__tests__/SearchInput.test.tsx, packages/react-core/src/components/SearchInput/examples/SearchInput.md, packages/react-integration/cypress/integration/searchinput.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/SearchInputDemo/SearchInputDemo.tsx
**What**: Closes #5168 
//cc @rohitkrai03
=> feat(searchInput): add support to passing a ref

packages/react-virtualized-extension/src/components/Virtualized/VirtualTableBody.tsx, packages/react-virtualized-extension/src/components/Virtualized/examples/VirtualizedTable.md
**What**: Closes https://github.com/patternfly/patternfly-react/issues/5433
Credits to @evwilkin for finding the cause of the bug :)
=> revert some changes to VirtualTableBody

packages/react-core/src/components/SearchInput/SearchInput.tsx
**What**: Closes #5416
**Additional issues**: Looks like adding the class in https://github.com/patternfly/patternfly/pull/3783/files#diff-a815fde0bcde7fe9be48ba78cba5a24b5691b889e8f5c9692c3fe9ab2a555acaR112 broke us.
=> fix(searchinput): add bar class

packages/react-core/src/components/Progress/Progress.tsx, packages/react-core/src/components/Progress/ProgressBar.tsx, packages/react-core/src/components/Progress/__tests__/Generated/__snapshots__/Progress.test.tsx.snap, packages/react-core/src/components/Progress/__tests__/Progress.test.tsx, packages/react-core/src/components/Progress/__tests__/__snapshots__/Progress.test.tsx.snap, packages/react-core/src/components/Progress/examples/Progress.md
=> feat(Progress): Add warning when title and aria-label not present

packages/react-core/src/components/FormSelect/FormSelect.tsx, packages/react-core/src/components/FormSelect/FormSelectOption.tsx, packages/react-core/src/components/FormSelect/examples/FormSelect.md, packages/react-integration/cypress/integration/formselect.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/FormSelectDemo/FormSelectDemo.tsx
=> feat(FormSelect): added support for placeholder styled option

packages/react-core/src/components/TreeView/TreeViewListItem.tsx, packages/react-core/src/components/TreeView/examples/TreeView.md
=> fix(TreeView): expand/collapse on filtering

packages/react-integration/demo-app-ts/src/components/demos/TableDemo/TableComposableDemo.tsx, packages/react-table/src/components/TableComposable/Th.tsx
=> bug(TableComposable): add dataLabel property

packages/react-table/src/demos/Table.md
=> feat(Table): update column management demo to include label

packages/react-core/src/components/SearchInput/SearchInput.tsx, packages/react-core/src/components/SearchInput/__tests__/SearchInput.test.tsx, packages/react-core/src/components/SearchInput/__tests__/__snapshots__/SearchInput.test.tsx.snap, packages/react-core/src/components/SearchInput/examples/SearchInput.md, packages/react-integration/cypress/integration/searchinput.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/SearchInputDemo/SearchInputDemo.tsx
Closes: #5332 
Note: tests coming very soon - just wanted to get the PR up for review
=> feat(SearchInput): add advanced search feature

packages/react-catalog-view-extension/package.json, packages/react-charts/package.json, packages/react-console/package.json, packages/react-core/package.json, packages/react-core/src/components/Slider/Slider.tsx, packages/react-core/src/components/Slider/_tests_/__snapshots__/Slider.test.tsx.snap, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-styles/package.json, packages/react-table/package.json, packages/react-tokens/package.json, yarn.lock
=> feat(Slider): Added touch support

packages/react-docs/RELEASE-NOTES.md
=> chore: Release notes 2021.02

packages/react-docs/RELEASE-NOTES.md
=> chore(release-notes): bump versions

packages/react-core/src/components/LoginPage/LoginForm.tsx, packages/react-core/src/components/LoginPage/__tests__/LoginForm.test.tsx, packages/react-core/src/components/LoginPage/__tests__/__snapshots__/LoginForm.test.tsx.snap, packages/react-core/src/components/LoginPage/examples/LoginPage.md, packages/react-integration/cypress/integration/login-page.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/LoginPageDemo/LoginPageDemo.tsx
=> feat(LoginPage): enable show or hide password

packages/react-core/src/components/TimePicker/TimePicker.tsx, packages/react-core/src/components/TimePicker/TimePickerUtils.tsx, packages/react-core/src/components/TimePicker/examples/TimePicker.md
=> fix(timepicker): use different am/pm suffixes

packages/react-core/src/components/Dropdown/InternalDropdownItem.tsx
**What**: Closes #3765 
Props to @kmcfaul for helping me figure this out!!! 🙂
=> fix(ApplicationLauncher): enable keyboard accessibility when using component prop

packages/react-core/src/components/Progress/Progress.tsx, packages/react-core/src/components/Progress/__tests__/Generated/__snapshots__/Progress.test.tsx.snap, packages/react-core/src/components/Progress/__tests__/__snapshots__/Progress.test.tsx.snap, packages/react-core/src/components/Progress/examples/Progress.md
=> fix(Progress): make proper usage of accessibility properties     

packages/react-core/src/components/InputGroup/InputGroupText.tsx, packages/react-core/src/components/InputGroup/__tests__/InputGroup.test.tsx, packages/react-core/src/components/InputGroup/examples/InputGroup.md, packages/react-integration/demo-app-ts/src/components/demos/InputGroupDemo/InputGroupDemo.tsx
=> feat(InputGroup): add plain input group text variant

packages/react-core/src/components/Drawer/Drawer.tsx, packages/react-core/src/components/Drawer/DrawerContent.tsx, packages/react-core/src/components/Drawer/DrawerPanelContent.tsx, packages/react-core/src/components/Drawer/DrawerSection.tsx, packages/react-core/src/components/Drawer/__tests__/Drawer.test.tsx, packages/react-core/src/components/Drawer/__tests__/__snapshots__/Drawer.test.tsx.snap, packages/react-core/src/components/Drawer/examples/Drawer.md, packages/react-integration/cypress/integration/drawer.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/DrawerDemo/DrawerDemo.tsx
=> feat(Drawer): add gray and white panel background variants

packages/react-core/src/components/Form/examples/Form.md
=> Form: add grid form example

packages/react-core/src/components/TreeView/TreeView.tsx, packages/react-core/src/components/TreeView/TreeViewListItem.tsx, packages/react-core/src/components/TreeView/examples/TreeView.md, packages/react-integration/cypress/integration/treeview.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/TreeViewDemo/TreeViewDemo.tsx
=> feature(Tree view): Added support for custom badge content

packages/react-core/src/components/SearchInput/SearchInput.tsx, packages/react-core/src/components/SearchInput/__tests__/__snapshots__/SearchInput.test.tsx.snap, packages/react-integration/cypress/integration/searchinput.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/SearchInputDemo/SearchInputDemo.tsx
**What**: Closes #5463 and Closes #5462
=> feat(SearchInput): add isDisabled and clean up focus handling

packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx, packages/react-integration/cypress/integration/codeeditor.spec.ts, packages/react-integration/demo-app-ts/src/Demos.ts, packages/react-integration/demo-app-ts/src/components/demos/CodeEditorDemo/CodeEditorDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/index.ts, packages/react-integration/package.json, packages/react-integration/webpack.config.js, yarn.lock
=> feat(CodeEditor): Make 'code' prop controlled

packages/react-integration/cypress/integration/codeeditor.spec.ts
=> fix(CodeEditor): fix flaky integration test

packages/react-integration/cypress/integration/codeeditor.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/TopologyPackage.tsx, packages/react-styles/src/css/components/Topology/topology-side-bar.css, packages/react-topology/src/components/TopologySideBar/TopologySideBar.test.tsx, packages/react-topology/src/components/TopologySideBar/TopologySideBar.tsx, packages/react-topology/src/components/TopologySideBar/__snapshots__/TopologySideBar.test.tsx.snap, packages/react-topology/src/components/TopologyView/TopologyView.test.tsx, packages/react-topology/src/components/TopologyView/TopologyView.tsx, packages/react-topology/src/components/TopologyView/__snapshots__/TopologyView.test.tsx.snap
**What**: Addresses portions of #5291
=> feat(topology): Use Drawer for topology side panel and allow resizing

packages/react-core/src/components/Drawer/DrawerPanelContent.tsx, packages/react-core/src/components/Drawer/__tests__/Generated/__snapshots__/DrawerPanelContent.test.tsx.snap, packages/react-core/src/components/Drawer/__tests__/__snapshots__/Drawer.test.tsx.snap, packages/react-topology/src/components/TopologyView/__snapshots__/TopologyView.test.tsx.snap
=> fix(drawer): dont initially render DrawerPanelContent

packages/react-core/src/components/JumpLinks/JumpLinks.tsx, packages/react-core/src/components/JumpLinks/JumpLinksItem.tsx
=> fix(jumplinks): add className prop

packages/react-core/src/components/BackgroundImage/BackgroundImage.tsx
=> fix(backgroundimage): useEffect for id

packages/react-integration/demo-app-ts/src/components/demos/ApplicationLauncherDemo/ApplicationLauncherDemo.tsx
=> fix(AppLauncher Demo): make app launcher demo keyboard accessible

packages/react-core/src/components/Pagination/Navigation.tsx, packages/react-core/src/components/Pagination/Pagination.tsx, packages/react-core/src/components/Pagination/ToggleTemplate.tsx, packages/react-core/src/components/Pagination/__tests__/Generated/__snapshots__/Navigation.test.tsx.snap, packages/react-core/src/components/Pagination/__tests__/Generated/__snapshots__/Pagination.test.tsx.snap, packages/react-core/src/components/Pagination/__tests__/Generated/__snapshots__/ToggleTemplate.test.tsx.snap, packages/react-core/src/components/Pagination/__tests__/__snapshots__/Pagination.test.tsx.snap
=> fix(pagination): add titles.ofWord

packages/react-core/src/components/Breadcrumb/BreadcrumbItem.tsx, packages/react-core/src/components/Breadcrumb/examples/Breadcrumb.md, packages/react-core/src/components/Dropdown/BadgeToggle.tsx, packages/react-core/src/components/Dropdown/DropdownItem.tsx, packages/react-core/src/components/Dropdown/examples/Dropdown.md, packages/react-core/src/components/Dropdown/index.ts, packages/react-core/src/components/Menu/examples/Menu.md, packages/react-integration/cypress/integration/breadcrumb.spec.ts, packages/react-integration/cypress/integration/dropdown.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/BreadcrumbDemo/BreadcrumbDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/DropdownDemo/DropdownDemo.tsx
**What**: Closes #5361, #5506, #5333
Adds badge toggle variant to Dropdown.
Adds badge dropdown demo to Breadcrumb + wrapper.
Adds Breadcrumb dropdown to Drilldown Menu demo.
=> feat(Dropdown): add badge toggle variant

packages/react-core/src/components/Alert/Alert.tsx, packages/react-core/src/components/Alert/examples/Alert.md
**What**: Fixes issue @jeff-phillips-18 reported in openshift.
=> fix(alert): do not return false in useEffect

packages/react-core/src/components/Checkbox/Checkbox.tsx, packages/react-core/src/components/Checkbox/__tests__/Checkbox.test.tsx, packages/react-core/src/components/Checkbox/__tests__/Generated/__snapshots__/Checkbox.test.tsx.snap, packages/react-core/src/components/Checkbox/examples/Checkbox.md, packages/react-core/src/components/Radio/Radio.tsx, packages/react-core/src/components/Radio/__tests__/Generated/__snapshots__/Radio.test.tsx.snap, packages/react-core/src/components/Radio/__tests__/Radio.test.tsx, packages/react-core/src/components/Radio/examples/Radio.md, packages/react-integration/cypress/integration/checkbox.spec.ts, packages/react-integration/cypress/integration/radio.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/CheckboxDemo/CheckboxDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/RadioDemo/RadioDemo.tsx, packages/react-topology/src/components/TopologyView/__snapshots__/TopologyView.test.tsx.snap
=> feat(Checkbox, Radio): Added support for custom body content

packages/react-core/src/components/Slider/Slider.tsx, packages/react-core/src/components/Slider/_tests_/Slider.test.tsx, packages/react-core/src/components/Slider/_tests_/__snapshots__/Slider.test.tsx.snap, packages/react-core/src/components/Slider/examples/Slider.md
=> feat(Slider): add isDisabled property

packages/react-core/src/components/Tooltip/examples/Tooltip.md
=> fix(Tooltip): make icon example accessible

packages/react-docs/RELEASE-NOTES.md
=> Updated the 2021.04 release notes

packages/react-code-editor/package.json
=> fix(code-editor): react peer dep

packages/react-core/src/components/TreeView/TreeView.tsx, packages/react-core/src/components/TreeView/TreeViewRoot.tsx
=> fix(treeview): add classname

packages/react-core/src/components/Wizard/WizardFooterInternal.tsx, packages/react-core/src/components/Wizard/__tests__/Generated/__snapshots__/WizardFooterInternal.test.tsx.snap
=> fix(Wizard): disable back button on first step for keyboard users

packages/react-core/src/components/Select/Select.tsx, packages/react-core/src/components/Select/__tests__/Select.test.tsx, packages/react-core/src/components/Select/examples/Select.md, packages/react-integration/demo-app-ts/src/Demos.ts, packages/react-integration/demo-app-ts/src/components/demos/SelectDemo/FilteringSelectDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/SelectDemo/FilteringSelectLiveUpdateDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/index.ts
When the children of the select are updated while the component is
mounted make sure to apply the filter as well.
Add a demo to demostrate the new functionality.
Fixes #5625
=> Select: change arguments of the onFilter callback

packages/react-core/src/demos/Card/Card.md
**What**: Closes #5337 
Also change all cards to `compact` to make it the same as HTML demo.
=> fix(card): add empty state to card demo

packages/react-inline-edit-extension/package.json, yarn.lock
**What**: Just noticed an unused dep laying around. Related to #5644
=> fix(inline-edit): remove unused dep

packages/react-core/src/components/Toolbar/examples/Toolbar.md
Closes # [5664](https://github.com/patternfly/patternfly-react/issues/5664)
You can see the updated doc that this PR adds below:
=> added 'ToolbarGroup' to docs

.github/stale.yml
**What**: Closes #3992. Should fix the bot which I don't think is running. Not sure why it was [added](https://probot.github.io/apps/stale/) on Probot's side.
=> fix(stalebot): add closeComment

packages/react-core/src/components/Tooltip/examples/Tooltip.md, packages/react-integration/cypress/integration/tablecomposable.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/TableDemo/TableComposableDemo.tsx, packages/react-table/src/components/Table/TableText.tsx
**What**: Allows greater tooltip customization needed for @mmenestr. Closes #5658
=> feat(TableText): allow passing tooltipProps

packages/react-core/src/components/Card/Card.tsx, packages/react-core/src/components/Card/examples/Card.md, packages/react-integration/demo-app-ts/src/components/demos/CardDemo/CardDemo.tsx
=> feat(Card): add full-height and plain variation

packages/react-core/src/components/ContextSelector/examples/ContextSelector.md
fixes https://github.com/patternfly/patternfly-react/issues/5673
=> chore(context-selector): updated footer button to inline

packages/react-core/src/components/Select/SelectOption.tsx, packages/react-core/src/components/Select/__tests__/SelectOption.test.tsx, packages/react-core/src/components/Select/__tests__/__snapshots__/SelectOption.test.tsx.snap, packages/react-core/src/components/Select/examples/Select.md, packages/react-integration/cypress/integration/select.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectDemo.tsx
**What**: Closes #5557 
See the `Checkbox input with counts` example
=> feat(Select): Added optional item count

packages/react-core/src/components/Form/FormGroup.tsx, packages/react-core/src/components/Form/FormSection.tsx, packages/react-core/src/components/Form/__tests__/FormGroup.test.tsx, packages/react-core/src/components/Form/__tests__/FormSection.test.tsx, packages/react-core/src/components/Form/__tests__/__snapshots__/FormGroup.test.tsx.snap, packages/react-core/src/components/Form/__tests__/__snapshots__/FormSection.test.tsx.snap, packages/react-core/src/components/Form/examples/Form.md, packages/react-integration/cypress/integration/form.spec.ts, packages/react-integration/cypress/integration/formhorizontal.spec.ts, packages/react-integration/demo-app-ts/src/Demos.ts, packages/react-integration/demo-app-ts/src/components/demos/FormDemo/FormDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/FormDemo/FormHorizontalDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/index.ts
Closes #5286
Add isStacked to FormGroup so the FormGroupControls can be stacked.
Add title to FormSection
=> feat(Form): Add stacked variant and section title

packages/react-core/src/components/DatePicker/DatePicker.tsx, packages/react-core/src/components/TimePicker/TimePicker.tsx, packages/react-core/src/components/TimePicker/TimePickerUtils.tsx, packages/react-core/src/components/TimePicker/examples/TimePicker.md, packages/react-core/src/demos/DatePicker.md
**What**: Closes #4737
@redallen Do you know why the rangeStart value is not updating on the second Date picker in my new demo? 
After I figure this out, I just need to make sure the error message is displayed at the right time - other than that, it's ready for review
=> feat(DatePicker): Add date and time range demo

packages/react-core/src/components/Toolbar/Toolbar.tsx
=> fix(Toolbar): Collapse expandable content when crossing breakpoint

packages/react-catalog-view-extension/package.json, packages/react-console/package.json, packages/react-core/package.json, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
=> chore: bump core version

packages/react-integration/cypress/integration/tablestickyheader.spec.ts
…n test
**What**: Closes #5712 
=> chore(integration test): added delay to table sticky header integration test

packages/react-docs/RELEASE-NOTES.md
=> chore(release notes): update release notes

packages/react-core/src/components/Select/examples/Select.md
**What**: Closes #5720 
Fixes capitalization in example.
=> fix(docs): Fixed example capitalization

packages/react-core/src/components/TreeView/TreeView.tsx, packages/react-core/src/components/TreeView/__tests__/__snapshots__/TreeView.test.tsx.snap
Since name is of type Reac.ReactNode, I propose we use the item.id to generate the key. 
**What**: Closes #5558
=> Bug fix: change key generation field for tree view

packages/react-core/src/components/FileUpload/FileUpload.tsx, packages/react-core/src/components/FileUpload/FileUploadField.tsx, packages/react-integration/demo-app-ts/src/Demos.ts, packages/react-integration/demo-app-ts/src/components/demos/FileUploadDemo/FileUploadDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/index.ts
=> fix(FileUpload): allow user to override onClick

packages/react-core/src/components/DualListSelector/treeUtils.ts
=> fix(DualListSelector): fix bug with selecting single node in nested folder

packages/react-docs/RELEASE-NOTES.md
=> release notes 2021.06

packages/react-docs/RELEASE-NOTES.md, packages/react-docs/package.json, scripts/promote.sh
=> update release notes and add log viewer to promote script

packages/react-core/src/components/JumpLinks/JumpLinks.tsx
=> fix(jumplinks): check for stale DOM node

packages/react-core/src/components/List/List.tsx, packages/react-core/src/components/List/ListItem.tsx, packages/react-core/src/components/List/__tests__/Generated/__snapshots__/ListItem.test.tsx.snap, packages/react-core/src/components/List/__tests__/List.test.tsx, packages/react-core/src/components/List/__tests__/__snapshots__/List.test.tsx.snap, packages/react-core/src/components/List/examples/List.md, packages/react-integration/cypress/integration/list.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/ListDemo/ListDemo.tsx
**What**: Closes https://github.com/patternfly/patternfly-react/issues/5336
=> feat(list): added icons, plain, bordered

packages/react-core/src/components/DataList/examples/DataList.md
This is an identical example, but converted from a class component to a functional component that uses the useState hook. It has been tested in the analytics codebase and I can confirm it works.
closes: #5784
=> Update DraggableDataList example to functional component

scripts/generators/patternfly-4-component/index.js, scripts/generators/patternfly-4-component/templates/component/component.md.hbs, scripts/generators/patternfly-4-component/templates/component/component.test.tsx.hbs, scripts/generators/patternfly-4-component/templates/component/component.tsx.hbs
=> fix(generator): update component scaffolding

packages/react-core/src/components/TimePicker/TimePicker.tsx
=> fix(timepicker): use exact match instead of includes

packages/react-core/src/components/TimePicker/TimePicker.tsx
=> fix(timepicker): don't spread validateTime

packages/react-core/src/helpers/util.ts, packages/react-core/src/layouts/Flex/Flex.tsx, packages/react-core/src/layouts/Flex/FlexItem.tsx, packages/react-core/src/layouts/Flex/examples/Flex.md, packages/react-core/src/layouts/Grid/Grid.tsx, packages/react-core/src/layouts/Grid/GridItem.tsx, packages/react-core/src/layouts/Grid/examples/Grid.md
=> feat(grid+flex): add ability to specify order

packages/react-core/src/components/Tabs/Tabs.tsx, packages/react-core/src/components/Tabs/__tests__/Tabs.test.tsx, packages/react-core/src/components/Tabs/__tests__/__snapshots__/Tabs.test.tsx.snap, packages/react-core/src/components/Tabs/examples/Tabs.md, packages/react-integration/cypress/integration/tabuncontrolleddemo.spec.ts, packages/react-integration/demo-app-ts/src/Demos.ts, packages/react-integration/demo-app-ts/src/components/demos/TabsDemo/TabsUncontrolledDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/index.ts
=> feat(Tabs): Added support for uncontrolled tabs

packages/react-catalog-view-extension/package.json, packages/react-console/package.json, packages/react-core/package.json, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-integration/cypress/integration/drawer.spec.ts, packages/react-integration/cypress/integration/drawerresize.spec.ts, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
=> Core bump with cypress fix

packages/react-core/src/components/Select/examples/Select.md
**What**: Fix Select's Custom Filtering demo
closes: #5852
=> docs(Select): fix Custom Filtering demo

packages/react-table/src/components/Table/BodyCell.tsx
=> fix(Table): remove data-label from expanded row 0

packages/react-table/src/components/Table/examples/Table.md
Closes: #5597
Also fixes a console warning coming from the Composable actions example.
=> fix(Table): change checkbox behavior in tree table examples

packages/react-core/src/components/Wizard/Wizard.tsx, packages/react-core/src/components/Wizard/WizardNavItem.tsx, packages/react-core/src/components/Wizard/__tests__/Wizard.test.tsx, packages/react-core/src/components/Wizard/__tests__/__snapshots__/Wizard.test.tsx.snap, packages/react-core/src/components/Wizard/examples/Wizard.md, packages/react-integration/demo-app-ts/src/components/demos/WizardDemo/WizardDemo.tsx
**What**: Closes #5580
Allows for expandable nav items
Creates new example for wizard component
=> feat(Wizard): allow for expandable nav items

packages/react-core/src/demos/PrimaryDetail.md
**What**: Closes https://github.com/patternfly/patternfly-react/issues/5742
https://patternfly-react-pr-5790.surge.sh/demos/primary-detail/react-demos/primary-detail-card-view/
=> chore(primary-detail): fixed card shadow on hover

packages/react-docs/RELEASE-NOTES.md
=> chore(docs): added release notes 2021.07

packages/react-core/src/components/Select/Select.tsx, packages/react-core/src/components/Select/SelectMenu.tsx, packages/react-core/src/components/Select/SelectOption.tsx
=> fix(select): add some safety accessors

packages/react-core/src/components/DatePicker/DatePicker.tsx, packages/react-core/src/components/TimePicker/TimePicker.tsx
=> fix(DatePicker, TimePicker): Pass additional props to input

packages/react-catalog-view-extension/src/components/PropertiesSidePanel/__snapshots__/PropertiesSidePanel.test.tsx.snap, packages/react-core/src/components/Text/Text.tsx, packages/react-core/src/components/Text/__tests__/Generated/__snapshots__/Text.test.tsx.snap, packages/react-core/src/components/Text/__tests__/__snapshots__/Text.test.tsx.snap, packages/react-core/src/helpers/OUIA/OUIA.md
=> Added OUIA props into Text component

packages/react-core/src/components/TimePicker/TimePicker.tsx, packages/react-core/src/components/TimePicker/TimePickerUtils.tsx, packages/react-core/src/components/TimePicker/__tests__/TimePicker.test.tsx
**What**: Closes https://github.com/patternfly/patternfly-react/issues/5861
Hi there. It's my first time contributing to this repository, so if I'm doing something wrong, please let me know. :grin:
I've opened https://github.com/patternfly/patternfly-react/issues/5861 today, and already have a solution for it. Also, I've add some tests to check if it's working correctly.
=> fix(TimePicker): fix the returned values of the onChange method.

packages/react-core/src/components/Text/Text.tsx, packages/react-core/src/components/Text/TextContent.tsx, packages/react-core/src/components/Text/examples/Text.md, packages/react-integration/cypress/integration/text.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/TextDemo/TextDemo.tsx
=> feat(Text): Added support for visited link styling

packages/react-core/src/layouts/Split/Split.tsx, packages/react-core/src/layouts/Split/__tests__/Split.test.tsx, packages/react-core/src/layouts/Split/__tests__/__snapshots__/Split.test.tsx.snap, packages/react-core/src/layouts/Split/examples/Split.md, packages/react-integration/cypress/integration/split.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/SplitDemo/SplitDemo.tsx
**What**: Closes https://github.com/patternfly/patternfly-react/issues/5636
=> feat(split): added prop to allow children to wrap

packages/react-core/src/components/Banner/examples/Banner.md, packages/react-core/src/components/Button/Button.tsx, packages/react-core/src/components/DescriptionList/examples/DescriptionList.md, packages/react-core/src/components/FileUpload/examples/FileUpload.md, packages/react-core/src/components/Hint/examples/Hint.md, packages/react-core/src/components/SimpleList/examples/SimpleList.md
=> chore: promote beta components

.eslintrc.json, packages/eslint-plugin-patternfly-react/lib/index.js, packages/eslint-plugin-patternfly-react/lib/rules/no-layout-effect.js, packages/react-core/src/components/Label/Label.tsx, packages/react-core/src/components/Modal/ModalBoxTitle.tsx, packages/react-core/src/helpers/Popper/thirdparty/react-popper/usePopper.ts, packages/react-core/src/helpers/index.ts, packages/react-core/src/helpers/useIsomorphicLayout.ts, packages/react-topology/src/components/popper/Portal.tsx
https://github.com/patternfly/patternfly-react/issues/5953
None
=> Changed useLayoutEffect to useIsomorphicLayoutEffect

packages/react-core/src/components/TimePicker/TimePicker.tsx
=> fix(TimePicker): Apply proper styles on Popper container

packages/react-core/src/components/Button/Button.tsx, packages/react-core/src/components/SimpleList/SimpleList.tsx
=> chore: Remove beta component console warnings from promoted components

packages/react-core/src/components/Nav/NavItem.tsx
**What**: Closes #5593
@KKoukiou I updated the descriptions on the props to reflect what the code is doing.
=> docs(Nav):  Updated incorrect prop descriptions

packages/react-console/src/components/DesktopViewer/__tests__/__snapshots__/DesktopViewer.test.tsx.snap, packages/react-core/src/components/Title/Title.tsx, packages/react-core/src/components/Title/__tests__/Generated/__snapshots__/Title.test.tsx.snap, packages/react-core/src/components/Title/__tests__/__snapshots__/Title.test.tsx.snap, packages/react-core/src/helpers/OUIA/OUIA.md
**What**: adds OUIA props into `Title` component. Closes #5942 .
=> Added OUIA props into Title

packages/react-core/src/components/Checkbox/Checkbox.tsx, packages/react-core/src/components/Checkbox/__tests__/Generated/__snapshots__/Checkbox.test.tsx.snap, packages/react-core/src/components/Checkbox/__tests__/__snapshots__/Checkbox.test.tsx.snap, packages/react-core/src/components/LoginPage/__tests__/Generated/__snapshots__/LoginForm.test.tsx.snap, packages/react-core/src/components/LoginPage/__tests__/__snapshots__/LoginForm.test.tsx.snap, packages/react-core/src/helpers/OUIA/OUIA.md
=> Added OUIA props into Checkbox

packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx
**What**: Needed for patternfly.org. Towards #2543
=> feat(code-editor): add showEditor prop

packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx
=> fix(codeeditor): show toolbar if there are custom controls

packages/react-console/src/components/VncConsole/VncConsole.tsx
In the VncConsole component, the 'Disconnect' button and the 'Ctrl+Alt+Del' option in the 'Send Keys' drop down menu do nothing when clicked. This is because the `rfb` instance wasn't persisting properly and was `undefined` when these elements were being clicked. 
This PR stores the `rfb` instance in a ref to ensure it is persisted until the component is unmounted.
Closes # https://github.com/patternfly/patternfly-react/issues/6007
=> fix(VncConsole): persist rfc instance in VncConsole

packages/react-core/src/components/ContextSelector/ContextSelectorItem.tsx
=> chore(ContextSelector): hide internal prop

packages/react-core/src/components/Toolbar/Toolbar.tsx, packages/react-core/src/components/Toolbar/__tests__/Generated/__snapshots__/Toolbar.test.tsx.snap, packages/react-core/src/components/Toolbar/__tests__/__snapshots__/ToolbarToggleGroup.test.tsx.snap, packages/react-core/src/helpers/OUIA/OUIA.md, packages/react-topology/src/components/TopologyControlBar/__snapshots__/TopologyControlBar.test.tsx.snap, packages/react-topology/src/components/TopologyView/__snapshots__/TopologyView.test.tsx.snap
=> Added OUIA props into Toolbar

packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx
=> feat(codeeditor): allow passing options and overrideServices

README.md, packages/react-log-viewer/src/LogViewer/examples/LogViewer.md
=> chore(LogViewer): move to extensions

packages/react-core/src/components/Avatar/Avatar.tsx, packages/react-core/src/components/Avatar/__tests__/Avatar.test.tsx, packages/react-core/src/components/Avatar/__tests__/__snapshots__/Avatar.test.tsx.snap, packages/react-core/src/components/Avatar/examples/Avatar.md, packages/react-core/src/components/Avatar/examples/example.css, packages/react-integration/cypress/integration/avatar.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/AvatarDemo/AvatarDemo.tsx
=> feat(avatar): add border prop

packages/react-core/src/components/Select/Select.tsx
=> fix(Select): check children have props before comparing them

packages/react-core/src/components/Button/Button.tsx, packages/react-core/src/components/Button/examples/Button.md, packages/react-integration/demo-app-ts/src/components/demos/ButtonDemo/ButtonDemo.tsx
=> feat(button): allow router link component

packages/react-core/src/components/NotificationDrawer/NotificationDrawerHeader.tsx
=> fix(NotifcationDrawer): show close button

packages/react-core/src/components/DatePicker/DatePicker.tsx
=> fix(datepicker): clear parse error on type

packages/react-core/src/components/Switch/Switch.tsx, packages/react-core/src/components/Switch/__tests__/Switch.test.tsx, packages/react-core/src/components/Switch/__tests__/__snapshots__/Switch.test.tsx.snap, packages/react-core/src/components/Switch/examples/Switch.md
=> feat(Switch): add isReversed prop/layout

packages/react-core/src/components/Drawer/examples/Drawer.md, packages/react-table/src/components/Table/examples/Table.md, packages/react-table/src/components/TableComposable/examples/ComposableTable.md
Closes #6076
remove Drawer example unused imports
add official recommendation to use composable table to table docs
=> More table doc updates

packages/react-core/src/components/Tabs/Tabs.tsx, packages/react-core/src/components/Tabs/examples/Tabs.md
=> feat(Tabs): support page insets

packages/react-core/src/components/Sidebar/Sidebar.tsx, packages/react-core/src/components/Sidebar/SidebarContent.tsx, packages/react-core/src/components/Sidebar/SidebarPanel.tsx
=> fix(Sidebar): custom className override fix

packages/react-core/src/components/Select/SelectMenu.tsx, packages/react-core/src/components/Select/__tests__/__snapshots__/Select.test.tsx.snap
**What**: Closes https://github.com/patternfly/patternfly-react/issues/6146
=> fix(SelectMenu): omit isLastOptionBeforeFooter from props

packages/react-core/src/components/Toolbar/ToolbarFilter.tsx
=> fix(ToolbarFilter): Add props for customizing ChipGroup text

packages/react-core/src/components/Toolbar/ToolbarFilter.tsx, packages/react-core/src/components/Toolbar/examples/Toolbar.md
=> fix(Toolbar): use categoryName.key as filter counter index

packages/react-core/src/components/TreeView/TreeView.tsx, packages/react-core/src/components/TreeView/TreeViewList.tsx, packages/react-core/src/components/TreeView/TreeViewSearch.tsx, packages/react-core/src/components/TreeView/__tests__/TreeView.test.tsx, packages/react-core/src/components/TreeView/__tests__/__snapshots__/TreeView.test.tsx.snap, packages/react-core/src/components/TreeView/examples/TreeView.md, packages/react-core/src/components/TreeView/index.ts, packages/react-integration/demo-app-ts/src/components/demos/TreeViewDemo/TreeViewDemo.tsx
Closes: #5933
- Updated the TreeView example with search to consume a toolbar
- exposed the TreeViewSearch
- updated unit and integration tests
=> feat(TreeView): Update treeview to consume toolbar

packages/react-core/src/components/Popover/Popover.tsx
=> fix(Popover): call setVisible before animation

packages/react-catalog-view-extension/src/components/VerticalTabs/VerticalTabsTab.tsx, packages/react-catalog-view-extension/src/components/VerticalTabs/__snapshots__/VerticalTabs.test.tsx.snap, packages/react-catalog-view-extension/src/components/VerticalTabs/examples/VerticalTabs.md, packages/react-integration/cypress/integration/verticaltabs.spec.ts, packages/react-integration/demo-app-ts/src/Demos.ts, packages/react-integration/demo-app-ts/src/components/demos/VerticalTabsDemo/VerticalTabsDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/index.ts
**What**: Eventually closes #5957, some additional changes may be necessary.
**Additional issues**: Solves the issue being addressed. However, when a tab is also a link, there is no additional styling applied. Seems there should be some indication.
=> fix(VerticalTabs): expose href to allow links

packages/react-core/src/components/Avatar/examples/Avatar.md, packages/react-core/src/components/Avatar/examples/avatarImgDark.svg
=> chore(Avatar): update example image to match core

packages/react-core/src/components/Popover/Popover.tsx, packages/react-core/src/components/Popover/__tests__/Generated/__snapshots__/Popover.test.tsx.snap, packages/react-core/src/components/Popover/__tests__/__snapshots__/Popover.test.tsx.snap, packages/react-core/src/components/Popover/examples/Popover.md, packages/react-core/src/helpers/Popper/Popper.tsx, packages/react-integration/cypress/integration/popover.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/PopoverDemo/PopoverDemo.tsx
**What**: Closes #6075
New positioning can be seen in Advanced section of examples
=> feat(Popover): support diagonal positions

packages/react-log-viewer/src/LogViewer/LogViewer.tsx
=> fix(LogViewer): remove unused props

packages/react-core/src/components/Select/Select.tsx
=> fix(Select): correct typeahead children check

packages/react-core/src/components/SearchInput/SearchInput.tsx, packages/react-core/src/components/SearchInput/examples/SearchInput.md
=> feat(Search input): Added support for submit button

packages/react-table/src/components/TableComposable/examples/ComposableTable.md
=> add ThSortType to docs

packages/react-core/src/components/DualListSelector/DualListSelector.tsx
=> feat(DualListSelector): add arguments to onOptionsSelect (#6224)

packages/react-table/src/components/TableComposable/examples/ComposableTable.md
=> docs(table): add missing styles import

packages/react-core/src/components/Spinner/__tests__/Spinner.test.tsx, packages/react-core/src/components/Spinner/__tests__/__snapshots__/Spinner.test.tsx.snap
=> Spinner: fix spinner tests to check all component sizes

packages/react-catalog-view-extension/package.json, packages/react-console/package.json, packages/react-core/package.json, packages/react-core/src/components/DualListSelector/DualListSelectorListItem.tsx, packages/react-core/src/components/DualListSelector/DualListSelectorTreeItem.tsx, packages/react-core/src/components/DualListSelector/__tests__/__snapshots__/DualListSelector.test.tsx.snap, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
fixes https://github.com/patternfly/patternfly-react/issues/6291
=> fix(dual-list-selector): added support for list item row, bumped core

packages/react-core/src/demos/ComposableMenu.md
**What**: Closes #6019 
link to demo: https://patternfly-react-pr-6283.surge.sh/demos/composable-menu#context-selector-using-menu-components
=> (Menu): Added context selector demo using Menu

packages/react-core/src/components/Nav/Nav.tsx, packages/react-core/src/components/Nav/NavItem.tsx, packages/react-core/src/components/Nav/__tests__/Generated/__snapshots__/Nav.test.tsx.snap, packages/react-core/src/components/Nav/__tests__/Generated/__snapshots__/NavItem.test.tsx.snap, packages/react-core/src/components/Nav/__tests__/__snapshots__/Nav.test.tsx.snap, packages/react-core/src/components/Nav/examples/Nav.md, packages/react-core/src/components/Nav/examples/nav.css, packages/react-core/src/components/Page/__tests__/__snapshots__/Page.test.tsx.snap, packages/react-integration/cypress/integration/nav.spec.ts, packages/react-integration/cypress/integration/tablecomposable.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/NavDemo/NavDemo.tsx
**What**: Closes #6161
In this PR:
- Adds `subnav` variant to `Nav`
- Adds `flyout` property to `NavItem`. `flyout` is a full `Nav` component with the `subnav` variant.
Still have some questions about architecture and interaction so marking as draft for now.
=> feat(Nav): add flyout

packages/react-core/src/layouts/Flex/Flex.tsx, packages/react-core/src/layouts/Flex/FlexItem.tsx, packages/react-core/src/layouts/Flex/__tests__/Flex.test.tsx, packages/react-core/src/layouts/Flex/__tests__/__snapshots__/Flex.test.tsx.snap, packages/react-core/src/layouts/Flex/examples/Flex.md, packages/react-core/src/layouts/Gallery/Gallery.tsx, packages/react-core/src/layouts/Gallery/GalleryItem.tsx, packages/react-core/src/layouts/Gallery/__tests__/Gallery.test.tsx, packages/react-core/src/layouts/Gallery/__tests__/__snapshots__/Gallery.test.tsx.snap, packages/react-core/src/layouts/Gallery/examples/Gallery.md, packages/react-core/src/layouts/Grid/Grid.tsx, packages/react-core/src/layouts/Grid/GridItem.tsx, packages/react-core/src/layouts/Grid/__tests__/Grid.test.tsx, packages/react-core/src/layouts/Grid/__tests__/__snapshots__/Grid.test.tsx.snap, packages/react-core/src/layouts/Grid/examples/Grid.md
=> Add component property to Flex, Gallery and Grid and the subitems. 

packages/react-core/src/components/DatePicker/DatePicker.tsx, packages/react-core/src/components/SearchInput/AdvancedSearchMenu.tsx, packages/react-core/src/components/SearchInput/SearchInput.tsx, packages/react-core/src/components/SearchInput/examples/SearchInput.md, packages/react-core/src/demos/SearchInput.md
**What**: Closes #6212 
I pulled out the dynamically built advanced search into a separate (unexposed) component.
I updated the docs for the dynamically built advanced search example for clarity.
I added a demo to demonstrate building a custom composable advanced search form.
=> Composable search with form

packages/react-core/src/demos/CardDemos.md
**What**: Closes #6287 
Closes #6288
=> Card: Added demos for log and event views

packages/react-core/src/components/CalendarMonth/CalendarMonth.tsx, packages/react-inline-edit-extension/src/components/Body/Body.tsx
=> fix(calendarmonth): make useEffect respect validators

packages/react-docs/RELEASE-NOTES.md
=> Chore: release notes 2021.12

packages/react-docs/RELEASE-NOTES.md
=> Update versions on release notes

packages/react-core/src/components/Sidebar/Sidebar.tsx, packages/react-core/src/components/Sidebar/SidebarContent.tsx, packages/react-core/src/components/Sidebar/SidebarPanel.tsx, packages/react-core/src/components/Sidebar/examples/Sidebar.md
fixes https://github.com/patternfly/patternfly-react/issues/6312
=> chore(sidebar): fix sidebar docs

packages/react-catalog-view-extension/package.json, packages/react-console/package.json, packages/react-core/package.json, packages/react-core/src/components/JumpLinks/JumpLinks.tsx, packages/react-core/src/components/JumpLinks/__tests__/JumpLinks.test.tsx, packages/react-core/src/components/JumpLinks/__tests__/__snapshots__/JumpLinks.test.tsx.snap, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
**What**: Closes #6306 
- Added text to expandable toggle and only shoe label when `alwaysShowLabel` is true.
- Bumped core version (pf-c-jump-links__header removed from core)
=> feat(JumpLinks): Added toggle text

packages/react-core/src/layouts/Grid/__tests__/GridItem.test.tsx, packages/react-core/src/layouts/Grid/__tests__/__snapshots__/GridItem.test.tsx.snap
=> Fix tests for size offsets of GridItem

packages/react-catalog-view-extension/package.json, packages/react-console/package.json, packages/react-core/package.json, packages/react-core/src/components/DragDrop/Draggable.tsx, packages/react-core/src/components/DragDrop/Droppable.tsx, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
=> chore(drag-drop): consume core classes

packages/react-core/src/components/Sidebar/examples/Sidebar.md
=> Sidebar(docs): added tabindex to scrollable examples

packages/react-core/src/demos/CardDemos.md
**What**: Closes #6382 Closes #6381
=> docs(Card): Added nested card demo

packages/react-core/src/components/Page/examples/Page.md
**What**: Follow up from #6388
This PR is simply addressing [one comment](https://github.com/patternfly/patternfly-react/pull/6388#discussion_r722304987) made on #6388 which wasn't addressed in that PR.
=> docs(page): update horizontal nav example to not be forced stacked

packages/react-tokens/scripts/generateTokens.js
=> fix(react-tokens): parse var(--pf, initialValue)

packages/react-core/src/components/Banner/Banner.tsx, packages/react-core/src/components/Banner/__tests__/__snapshots__/Banner.test.tsx.snap
=> fix(Banner): forward props

packages/react-core/src/components/AboutModal/AboutModal.tsx, packages/react-core/src/components/AboutModal/AboutModalContainer.tsx
=> fix(AboutModal): allow to disable FocusTrap

packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx
=> feat(CodeEditor): improve type-safety for onChange prop

packages/react-core/src/components/Popover/Popover.tsx, packages/react-core/src/components/Popover/PopoverContext.tsx, packages/react-core/src/components/Popover/PopoverHeader.tsx, packages/react-core/src/components/Popover/__tests__/Generated/__snapshots__/Popover.test.tsx.snap, packages/react-core/src/components/Popover/__tests__/Generated/__snapshots__/PopoverHeader.test.tsx.snap, packages/react-core/src/components/Popover/__tests__/__snapshots__/Popover.test.tsx.snap, packages/react-integration/cypress/integration/popover.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/PopoverDemo/PopoverDemo.tsx
fixes https://github.com/patternfly/patternfly-react/issues/6508
=> fix(popover): allow user to change heading level

packages/react-core/src/components/Modal/examples/Modal.md
=> docs(Modal): Added example of modal with form

packages/react-core/src/components/TextInputGroup/TextInputGroup.tsx, packages/react-core/src/components/TextInputGroup/TextInputGroupMain.tsx, packages/react-core/src/components/TextInputGroup/__tests__/TextInputGroup.test.tsx, packages/react-core/src/components/TextInputGroup/__tests__/__snapshots__/TextInputGroup.test.tsx.snap, packages/react-core/src/components/TextInputGroup/examples/TextInputGroup.md
=> Added requested text input group props

packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx
=> feat: enhance type correctness of CodeEditor

packages/react-core/src/components/Nav/examples/Nav.md, packages/react-core/src/components/Nav/examples/nav.css
**What**: Closes #6498
Adding just a demo
=> feat(Navigation): Added example for third level nested expansion

packages/react-core/src/components/TextInputGroup/examples/TextInputGroup.md
**What**: Closes #6587 
**Additional issues**:N/A
=> fix(TextInputGroup): updated examples to use revised onChange prop

packages/react-log-viewer/src/LogViewer/LogViewer.tsx, packages/react-log-viewer/src/LogViewer/LogViewerContext.tsx, packages/react-log-viewer/src/LogViewer/LogViewerRow.tsx, packages/react-log-viewer/src/LogViewer/LogViewerSearch.tsx, packages/react-log-viewer/src/LogViewer/examples/LogViewer.md, packages/react-log-viewer/src/LogViewer/utils/constants.ts, packages/react-log-viewer/src/LogViewer/utils/utils.tsx
**What**: Closes #6590 
Only highlight the searched keyword, but not the keywords on the same row.
=> fix(LogViewer): update search function

packages/react-core/src/components/Menu/Menu.tsx, packages/react-core/src/components/Menu/MenuContent.tsx, packages/react-core/src/components/Menu/MenuContext.ts
=> fix(Menu): allow maxMenuHeight with Scrollabe

packages/react-docs/RELEASE-NOTES.md
=> (Chore): fix release notes

packages/react-core/src/components/Alert/Alert.tsx, packages/react-core/src/components/Alert/__tests__/Alert.test.tsx, packages/react-core/src/components/Alert/__tests__/__snapshots__/Alert.test.tsx.snap, packages/react-core/src/components/Alert/examples/Alert.md
**What**: Closes #6444
Added new alerts under 'Variations' example
=> feat(Alert): Allow all heading levels for title

packages/react-core/src/components/ActionList/ActionList.tsx, packages/react-core/src/components/ActionList/ActionListGroup.tsx, packages/react-core/src/components/ActionList/ActionListItem.tsx
fixes https://github.com/patternfly/patternfly-react/issues/6646
=> fix(action-list): added support for classname

packages/react-core/src/components/Card/examples/Card.md, packages/react-core/src/demos/TileDemo.md
**What**: Closes #6637
Also cleans up some unused imports in the Card examples
=> fix(Tile): fix selecting tile in tile demo

packages/react-core/src/components/DragDrop/Droppable.tsx
=> fix(DragDrop): don't overwrite children class with Droppable class

packages/react-docs/RELEASE-NOTES.md
=> update version/date on release notes

packages/react-docs/RELEASE-NOTES.md
=> fix popover release note

packages/react-core/src/components/OverflowMenu/OverflowMenuControl.tsx, packages/react-core/src/components/OverflowMenu/OverflowMenuGroup.tsx
=> fix(OverflowMenu): pass HTMLDivElements props to group and control divs

packages/react-core/src/components/Pagination/Navigation.tsx, packages/react-core/src/components/Pagination/Pagination.tsx, packages/react-core/src/components/Pagination/__tests__/Generated/__snapshots__/Pagination.test.tsx.snap, packages/react-core/src/components/Pagination/__tests__/__snapshots__/Pagination.test.tsx.snap
**What**: Closes #6707 
//cc @Ron-Lavi @MariaAga @tlabaj
=> fix(Pagination): Allow set plural title in Navigation

packages/react-docs/README.md
closes https://github.com/patternfly/patternfly-react/issues/6734
=> fix(docs): fix broken theme-patternfly-org link

packages/react-table/src/components/Table/TableTypes.tsx
=> feat(Table): allow a generic to be passed for cell props

packages/react-topology/src/components/TopologyControlBar/TopologyControlBar.tsx, packages/react-topology/src/components/TopologyControlBar/__snapshots__/TopologyControlBar.test.tsx.snap
=> fix(TopologyControlBar): Update screen reader className to latest

packages/react-core/src/components/Tabs/Tabs.tsx, packages/react-core/src/components/Tabs/examples/Tabs.md
=> fix(Tabs): allow href navigation from tabs

packages/react-console/src/components/DesktopViewer/__tests__/__snapshots__/DesktopViewer.test.tsx.snap, packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx, packages/react-core/src/components/ExpandableSection/__tests__/ExpandableSection.test.tsx, packages/react-core/src/components/ExpandableSection/__tests__/__snapshots__/ExpandableSection.test.tsx.snap, packages/react-core/src/components/ExpandableSection/examples/ExpandableSection.md, packages/react-integration/demo-app-ts/src/components/demos/ExpandableSectionDemo/ExpandableSectionDemo.tsx
fixes https://github.com/patternfly/patternfly-react/issues/6705
=> feat(expandable-section): added indented variation

packages/react-core/src/demos/PasswordGenerator.md
**What**: Closes https://github.com/patternfly/patternfly-react/issues/6686
=> feat(demos): adds a password generator demo

packages/react-core/src/components/Toolbar/examples/Toolbar.md
**What**: Closes https://github.com/patternfly/patternfly-react/issues/6655
=> docs(Toolbar):  Add demo with sticky toolbar

packages/react-core/src/components/DescriptionList/DescriptionList.tsx, packages/react-core/src/components/DescriptionList/examples/DescriptionList.md
=> feat(DescriptionList): add option to fill columns first

packages/react-topology/src/utils/useHover.ts
**What**: Fixes an issue that the `useHover` triggers a react warning when the topology component is left and a hover effect is not completely "finished".
Also inverted "unmounted=false" to "mounted=true", at least for me its easier to read. :)
In OpenShift Developer Console this always when leaving the topology page.
Stack trace:
```
  | printWarning | @ | react-dom.development.js:67
  | error | @ | react-dom.development.js:43
  | warnAboutUpdateOnUnmountedFiberInDEV | @ | react-dom.development.js:23914
  | scheduleUpdateOnFiber | @ | react-dom.development.js:21840
  | dispatchAction | @ | react-dom.development.js:16139
  | (anonymous) | @ | useHover.js:46
  | setTimeout (async) |   |  
  | (anonymous) | @ | useHover.js:46
  | (anonymous) | @ | useCallbackRef.js:9
...
``` …
=> fix(Topology) Fix react warning: state update on an unmounted component

CONTRIBUTING.md
=> docs(CONTRIBUTING) - add note for windows users using lint (patternfly#6817)

packages/react-core/src/components/TimePicker/TimePicker.tsx, packages/react-core/src/components/TimePicker/TimePickerUtils.tsx, packages/react-core/src/components/TimePicker/__tests__/TimePicker.test.tsx, packages/react-core/src/components/TimePicker/examples/TimePicker.md
=> feat(TimePicker): Allow for seconds via new prop; includeSeconds

packages/react-core/src/components/NumberInput/NumberInput.tsx, packages/react-core/src/components/NumberInput/__tests__/__snapshots__/NumberInput.test.tsx.snap, packages/react-core/src/components/NumberInput/examples/NumberInput.md
=> feat(NumberInput): call onMinus/onPlus on arrow-up/down pressed

packages/react-core/src/demos/Button.md
**What**: Closes https://github.com/patternfly/patternfly-react/issues/6684
=> docs(button): adds demo for progress button completion state

packages/react-core/src/demos/Tabs.md, packages/react-core/src/demos/examples/Tabs/ModalTabs.tsx
=> chore(Tabs): Add demo for Tabs within Modals

packages/react-core/src/components/DataList/DataListCheck.tsx
=> fix(DataList): better comments for isChecked and checked props

packages/react-core/src/components/Select/Select.tsx, packages/react-core/src/components/Select/SelectOption.tsx, packages/react-integration/cypress/integration/selectviewmoregrouped.spec.ts, packages/react-integration/demo-app-ts/src/Demos.ts, packages/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectViewMoreGroupedDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/index.ts
=> fix(Select): Fixed dot next to the spinner in grouped view more variant

packages/react-core/src/components/TimePicker/TimePicker.tsx, packages/react-core/src/components/TimePicker/examples/TimePicker.md
**What**: Closes #6616  
@KKoukiou Can you let me know whether this resolves the issue you were facing with the TimePicker component? The DatePicker component looks to already have this auto-set functionality so I have not touched it for this.
=> feat(TimePicker): auto-set direction based on space

packages/react-core/src/components/Tabs/Tabs.tsx
Reverts patternfly/patternfly-react#6767
=> Revert "feat(Tabs): enforce restricted type for children"

packages/react-table/src/components/Table/ActionsColumn.tsx, packages/react-table/src/components/Table/TableTypes.tsx, packages/react-table/src/components/TableComposable/examples/ComposableTable.md
Reverts patternfly/patternfly-react#6108
=> Revert "Improve IAction type"

GETTING-STARTED.md
=> chore(whitespace): Add whitespace change to readme

packages/react-core/src/components/Button/Button.tsx, packages/react-core/src/components/Button/__tests__/Button.test.tsx, packages/react-core/src/components/Button/__tests__/__snapshots__/Button.test.tsx.snap, packages/react-core/src/components/Button/examples/Button.md, packages/react-core/src/components/Button/examples/ButtonProgress.tsx
=> Add icon only variant for progress button

packages/react-core/src/components/Progress/Progress.tsx
=> fix(Progress): NaN not returned when max and value are zero

packages/react-core/src/components/DescriptionList/DescriptionListTerm.tsx, packages/react-core/src/components/DescriptionList/examples/DescriptionList.md
=> feat(DescriptionList): add icon variant

packages/react-table/src/components/TableComposable/TableComposable.tsx, packages/react-table/src/components/TableComposable/examples/ComposableTableNestedExpandable.tsx, packages/react-table/src/components/TableComposable/examples/ComposableTableNestedHeaders.tsx
=> fix(Table): use colgroup and nested cols in composable table

packages/react-core/src/components/MenuToggle/MenuToggle.tsx, packages/react-core/src/components/MenuToggle/__tests__/__snapshots__/MenuToggle.test.tsx.snap, packages/react-core/src/components/MenuToggle/examples/MenuToggle.md
=> feat(MenuToggle): add full height variation

packages/react-core/src/demos/CardDemos.md
fixes https://github.com/patternfly/patternfly-react/issues/6823
to match https://github.com/patternfly/patternfly/pull/4667
=> chore(card): updated header alignment with select in demos

packages/react-core/src/components/TextInputGroup/TextInputGroupMain.tsx, packages/react-core/src/demos/TextInputGroupDemo.md, packages/react-core/src/demos/examples/TextInputGroup/AutoCompleteSearch.tsx
**What**: Closes #6671 - adding typeahead feature to text input group. adding a demo where we use typeahead if there is a single match in the autocomplete list.
=> feat(TextInputGroup): add ability to do typehead with textinputgroup, add to autocomplete demo

packages/react-catalog-view-extension/src/components/CatalogTile/__snapshots__/CatalogTile.test.tsx.snap, packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx, packages/react-code-editor/src/components/CodeEditor/CodeEditorControl.tsx, packages/react-core/src/components/Alert/Alert.tsx, packages/react-core/src/components/ChipGroup/Chip.tsx, packages/react-core/src/components/ChipGroup/ChipGroup.tsx, packages/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx, packages/react-core/src/components/ClipboardCopy/ClipboardCopyButton.tsx, packages/react-core/src/components/Label/Label.tsx, packages/react-core/src/components/LabelGroup/LabelGroup.tsx, packages/react-core/src/components/NotificationDrawer/NotificationDrawerGroup.tsx, packages/react-core/src/components/NotificationDrawer/NotificationDrawerListItemHeader.tsx, packages/react-core/src/components/Popover/Popover.tsx, packages/react-core/src/components/Progress/ProgressContainer.tsx, packages/react-core/src/components/Tooltip/Tooltip.tsx, packages/react-core/src/components/Tooltip/__tests__/Generated/__snapshots__/Tooltip.test.tsx.snap, packages/react-core/src/components/Tooltip/__tests__/__snapshots__/Tooltip.test.tsx.snap, packages/react-core/src/components/Tooltip/examples/Tooltip.md, packages/react-core/src/components/Truncate/Truncate.tsx, packages/react-topology/src/components/TopologyControlBar/__snapshots__/TopologyControlBar.test.tsx.snap
**What**: Closes #6568 adding support for diagonal tooltips, update other components that use tooltips
=> feat(ToolTip): Diagonal tooltip placement

packages/react-core/src/components/InputGroup/examples/InputGroup.md, packages/react-core/src/components/Toolbar/examples/Toolbar.md, packages/react-core/src/demos/DataListDemo.md, packages/react-table/src/demos/Table.md
**What**: Closes https://github.com/patternfly/patternfly-react/issues/6682
=> refactor(Toolbar-docs): use SearchInput in Toolbar demos

packages/react-core/src/components/Toolbar/examples/Toolbar.md
=> fix(Toolbar): fix docs build error

packages/react-core/src/components/Page/PageSection.tsx, packages/react-core/src/components/Page/__tests__/PageSection.test.tsx, packages/react-core/src/components/Page/__tests__/__snapshots__/PageSection.test.tsx.snap, packages/react-core/src/components/Page/examples/Page.md
=> feat(Page): Added center alignment for page sections

packages/react-core/src/components/Select/Select.tsx, packages/react-core/src/components/Select/SelectOption.tsx, packages/react-core/src/components/Select/SelectToggle.tsx
**What**: Closes #6693
To test change the variant of the view more variant to "typeahead"
Also fixed focus issue and keyboard regression.
=> fix(Select): Do not filter out view more button on filter

packages/react-integration/cypress/integration/chipgroup.spec.ts, packages/react-integration/cypress/integration/chipgroupdefaultisopen.spec.ts, packages/react-integration/cypress/integration/chipgroupwithcategory.spec.ts, packages/react-integration/cypress/integration/labelgroupwithcategory.spec.ts, packages/react-integration/cypress/integration/selectvalidated.spec.ts, packages/react-integration/demo-app-ts/src/App.tsx, packages/react-integration/demo-app-ts/src/components/demos/ChipGroupDemo/ChipGroupDefaultIsOpenDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/ChipGroupDemo/ChipGroupDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/ChipGroupDemo/ChipGroupWithCategoryDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/LabelGroupDemo/LabelGroupWithCategoryDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectValidatedDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/CollapsibleGroups.tsx, packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/TopologyDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/TopologyPackage.tsx, packages/react-integration/demo-app-ts/src/index.tsx
**What**: 
Closes https://github.com/patternfly/patternfly-react/issues/6956
None
**Screen shots**
=> chore(Dark Theme): Add dark theme option to integration demo app

packages/react-core/src/components/Label/Label.tsx
=> fix(Label): editable label should have a tooltip

packages/react-core/src/components/Toolbar/__tests__/ToolbarToggleGroup.test.tsx, packages/react-core/src/components/Toolbar/__tests__/__snapshots__/ToolbarToggleGroup.test.tsx.snap
**What**: Fixes jest error caused by merging #6955 - new test was not updated to use the new library.
=> fix(Toolbar): update test

packages/react-core/src/components/Tile/Tile.tsx, packages/react-core/src/components/Tile/__tests__/__snapshots__/Tile.test.tsx.snap, packages/react-core/src/components/Tile/examples/Tile.md, packages/react-core/src/demos/TileDemo.md
=> fix(Tile): add aria-selected to indicate selection state

packages/react-core/src/components/Form/FormFieldGroup.tsx, packages/react-core/src/components/Form/FormFieldGroupExpandable.tsx, packages/react-core/src/components/Form/FormFieldGroupHeader.tsx, packages/react-core/src/components/Form/InternalFormFieldGroup.tsx, packages/react-core/src/components/Form/__tests__/FormFieldGroup.test.tsx, packages/react-core/src/components/Form/__tests__/__snapshots__/FormFieldGroup.test.tsx.snap, packages/react-core/src/components/Form/examples/Form.md
=> chore(Form): Fix 'filed' type in 'field group' docs

packages/react-core/src/components/NumberInput/NumberInput.tsx, packages/react-core/src/components/NumberInput/__tests__/__snapshots__/NumberInput.test.tsx.snap, packages/react-core/src/components/NumberInput/examples/NumberInput.md
=> fix(NumberInput): better support for min/max

packages/react-core/src/components/ChipGroup/examples/ChipGroup.md
=> docs(Chip group): Added chip props back to the chip group page

packages/react-core/src/layouts/Flex/examples/Flex.md
fixes https://github.com/patternfly/patternfly-react/issues/7080
=> chore(flex): fixed spacing xl example

packages/react-core/src/components/Avatar/Avatar.tsx, packages/react-core/src/components/Avatar/examples/Avatar.md
=> feat(Avatar): add new size prop and demo

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
=> chore(template): Updated issue template to match patternfly/patternfly

packages/react-table/src/components/Table/Table.tsx, packages/react-table/src/components/Table/__snapshots__/Table.test.tsx.snap
=> fix(Table): make new canCollapseAll on collapsable rows opt-in

packages/react-console/src/components/AccessConsoles/__tests__/__snapshots__/AccessConsole.test.tsx.snap, packages/react-core/src/components/Select/Select.tsx, packages/react-core/src/components/Select/SelectOption.tsx, packages/react-core/src/components/Select/SelectToggle.tsx, packages/react-core/src/components/Select/__tests__/__snapshots__/Select.test.tsx.snap, packages/react-core/src/components/Select/examples/Select.md, packages/react-core/src/components/Select/selectConstants.tsx, packages/react-integration/cypress/integration/select.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectDemo.tsx
**What**: Closes #6641 & #6835
=> feat(Select): add flag to not reset on select, add event to toggle callback

GETTING-STARTED.md
=> docs(getting-started): link react testing library documentation

packages/react-core/src/components/CalendarMonth/CalendarMonth.tsx
=> fix(CalendarMonth): resolve regression for selecting a date

packages/react-core/src/components/Card/examples/Card.md
The CardActions component's properties are currently not shown in the Card documentation.
=> Document CardActions properties

packages/react-core/src/components/Drawer/Drawer.tsx, packages/react-core/src/components/Drawer/DrawerContent.tsx, packages/react-core/src/components/Drawer/DrawerPanelContent.tsx, packages/react-core/src/components/Drawer/__tests__/Generated/DrawerContent.test.tsx, packages/react-core/src/components/Drawer/__tests__/Generated/__snapshots__/DrawerContent.test.tsx.snap, packages/react-core/src/components/Drawer/__tests__/Generated/__snapshots__/DrawerPanelContent.test.tsx.snap, packages/react-core/src/components/Drawer/__tests__/__snapshots__/Drawer.test.tsx.snap, packages/react-topology/src/components/TopologyView/__snapshots__/TopologyView.test.tsx.snap
=> fix(Drawer): Updated resizable drawer to make it more accessible

packages/react-core/src/components/Drawer/DrawerContent.tsx
=> Fix regression with drawer

packages/react-styles/src/css/components/Topology/topology-components.css, packages/react-topology/src/behavior/withCreateConnector.tsx, packages/react-topology/src/components/DefaultCreateConnector.tsx
**What**:
Closes https://github.com/patternfly/patternfly-react/issues/7186
Reverts class name changes.
None
=> Revert topology class name changes

packages/react-code-editor/src/components/CodeEditor/examples/CodeEditor.md, packages/react-code-editor/src/components/CodeEditor/examples/CodeEditorBasic.tsx, packages/react-code-editor/src/components/CodeEditor/examples/CodeEditorCustomControl.tsx, packages/react-code-editor/src/components/CodeEditor/examples/CodeEditorShortcutMainHeader.tsx, packages/react-code-editor/src/components/CodeEditor/examples/CodeEditorSizeToFit.tsx, packages/react-code-editor/src/components/CodeEditor/examples/CodeEditorWithActions.tsx
=> chore(code editor): Convert examples to TypeScript/Functional components 

packages/react-core/src/components/CalendarMonth/CalendarMonth.tsx, packages/react-core/src/components/CalendarMonth/examples/CalendarMonth.md, packages/react-core/src/components/CalendarMonth/examples/CalendarMonthDateRange.tsx
=> chore(CalendarMonth): add date range example

packages/react-core/src/components/DescriptionList/examples/DescriptionList.md, packages/react-core/src/components/DescriptionList/examples/DescriptionListAutoFitBasic.tsx, packages/react-core/src/components/DescriptionList/examples/DescriptionListAutoFitMinWidthModified.tsx, packages/react-core/src/components/DescriptionList/examples/DescriptionListAutoFitMinWidthResponsive.tsx, packages/react-core/src/components/DescriptionList/examples/DescriptionListBasic.tsx, packages/react-core/src/components/DescriptionList/examples/DescriptionListColumnFill.tsx, packages/react-core/src/components/DescriptionList/examples/DescriptionListCompact.tsx, packages/react-core/src/components/DescriptionList/examples/DescriptionListCompactHorizontal.tsx, packages/react-core/src/components/DescriptionList/examples/DescriptionListDefaultAutoColumn.tsx, packages/react-core/src/components/DescriptionList/examples/DescriptionListDefaultInlineGrid.tsx, packages/react-core/src/components/DescriptionList/examples/DescriptionListDefaultResponsiveColumns.tsx, packages/react-core/src/components/DescriptionList/examples/DescriptionListDefaultThreeColLg.tsx, packages/react-core/src/components/DescriptionList/examples/DescriptionListDefaultTwoCol.tsx, packages/react-core/src/components/DescriptionList/examples/DescriptionListFluidHorizontal.tsx, packages/react-core/src/components/DescriptionList/examples/DescriptionListHorizontal.tsx, packages/react-core/src/components/DescriptionList/examples/DescriptionListHorizontalAutoColumn.tsx, packages/react-core/src/components/DescriptionList/examples/DescriptionListHorizontalCustomTermWidth.tsx, packages/react-core/src/components/DescriptionList/examples/DescriptionListHorizontalResponsiveColumns.tsx, packages/react-core/src/components/DescriptionList/examples/DescriptionListHorizontalThreeColLg.tsx, packages/react-core/src/components/DescriptionList/examples/DescriptionListHorizontalTwoCol.tsx, packages/react-core/src/components/DescriptionList/examples/DescriptionListIconsOnTerms.tsx, packages/react-core/src/components/DescriptionList/examples/DescriptionListResponsiveHoriVertGroup.tsx, packages/react-core/src/components/DescriptionList/examples/DescriptionListWithTermHelpText.tsx
=> chore(DescriptionList): convert examples to TypeScript

packages/react-table/src/components/Table/utils/decorators/treeRow.tsx, packages/react-table/src/components/TableComposable/examples/ComposableTableTree.tsx
**What**: Closes #6908 
[Tree table example convenience link](https://patternfly-react-pr-7170.surge.sh/components/table)
=> fix(Table): increase clickable area of tree table checkboxes

packages/react-table/src/components/TableComposable/examples/ComposableTable.md
=> chore(Table): fix broken link in docs

packages/react-integration/cypress/integration/select.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectDemo.tsx
**What**: Follow up for #7193 adding an integration test
=> test(Select): add test for footer/menuAppendTo interaction

packages/react-catalog-view-extension/sass/react-catalog-view-extension/_catalog-item.scss, packages/react-catalog-view-extension/sass/react-catalog-view-extension/_catalog-tile.scss, packages/react-catalog-view-extension/sass/react-catalog-view-extension/_variables.scss, packages/react-catalog-view-extension/sass/react-catalog-view-extension/_vertical-tabs.scss, packages/react-catalog-view-extension/src/components/CatalogTile/examples/CatalogTile.md, packages/react-catalog-view-extension/src/components/PropertiesSidePanel/examples/PropertiesSidePanel.md
fixes https://github.com/patternfly/patternfly-react/issues/7174
=> fix(catalog-view): updated colors to use dark theme friendly css vars

packages/react-table/src/demos/Table.md
**What**: Closes #7248
**Additional issues**: towards #6792
=> docs(Table): Cleaned up unused imports for InputGroup

packages/react-core/src/components/MenuToggle/MenuToggle.tsx, packages/react-core/src/components/MenuToggle/examples/MenuToggle.md
=> feat(MenuToggle): Add full width modifier

packages/react-core/src/components/Switch/Switch.tsx, packages/react-core/src/components/Switch/examples/Switch.md
=> Feat(Switch): Adds check + label functionality and demo

packages/react-core/src/demos/Tabs.md, packages/react-core/src/demos/examples/DashboardWrapper.js, packages/react-core/src/demos/examples/Tabs/GrayTabs.tsx, packages/react-core/src/demos/examples/Tabs/ModalTabs.tsx, packages/react-core/src/demos/examples/Tabs/NestedTabs.tsx, packages/react-core/src/demos/examples/Tabs/NestedUnindentedTabs.tsx, packages/react-core/src/demos/examples/Tabs/TabsAndTable.tsx
=> feat(Tabs): Add nested, unindented demo

packages/react-table/src/components/TableComposable/examples/ComposableTable.md
=> fix(Table): fix broken link in example docs

packages/react-core/src/demos/DateTimePicker.md
**What**: Closes #7127 
[Date and time picker demo](https://patternfly-react-pr-7266.surge.sh/demos/date-and-time-picker) for convenience
=> fix(DateTimePicker): update date placeholder

packages/react-core/src/components/DataList/examples/DataListExpandable.tsx
=> fix(DataList): Remove primary button from expandable demo

packages/react-core/src/components/DragDrop/examples/DragDrop.md, packages/react-core/src/components/DragDrop/examples/DragDropBasic.tsx, packages/react-core/src/components/DragDrop/examples/DragDropMultipleLists.tsx
=> chore(DragAndDrop): convert examples to TS 

packages/react-core/src/components/Wizard/examples/Wizard.md
=> Wizard step docs

packages/react-core/src/components/Tabs/Tabs.tsx
=> fix(Tabs): update key to not use index

packages/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx, packages/react-core/src/components/ClipboardCopy/ClipboardCopyButton.tsx
=> chore(ClipboardCopy): update types used for tooltip positioning

packages/react-table/src/demos/Table.md
**What**: Closes #7262 - tracked in https://github.com/patternfly/patternfly-react/issues/4779
=> Feat(Table): Adds full screen demo for basic/bulk select

packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/TopologyPackage.tsx, packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/data/generator.ts, packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/layouts/defaultLayoutFactory.ts, packages/react-topology/src/elements/BaseNode.ts, packages/react-topology/src/layouts/BaseLayout.ts, packages/react-topology/src/layouts/BreadthFirstLayout.ts, packages/react-topology/src/layouts/ColaGroupsLayout.ts, packages/react-topology/src/layouts/ColaGroupsNode.ts, packages/react-topology/src/layouts/ColaLayout.ts, packages/react-topology/src/layouts/ConcentricLayout.ts, packages/react-topology/src/layouts/DagreLayout.ts, packages/react-topology/src/layouts/ForceLayout.ts, packages/react-topology/src/layouts/GridLayout.ts, packages/react-topology/src/layouts/index.ts
**What**:
Closes https://github.com/patternfly/patternfly-react/issues/7307
One known issue with the layout stacking vertically. This should be addressed in a follow up.
=> feat(Topology): Add ColaGroupsLayout

packages/react-core/src/components/ApplicationLauncher/ApplicationLauncher.tsx, packages/react-core/src/components/ContextSelector/ContextSelector.tsx, packages/react-core/src/components/Dropdown/Dropdown.tsx, packages/react-core/src/components/OptionsMenu/OptionsMenu.tsx, packages/react-core/src/components/Select/Select.tsx, packages/react-core/src/helpers/Popper/Popper.tsx
Reverts patternfly/patternfly-react#7173
=> Revert "docs(Dropdown): expose menuAppendTo in Dropdown prop docs"

packages/react-table/src/demos/Table.md, packages/react-table/src/demos/table-demos/ExpandCollapseAll.jsx
=> feat(table): expandable table demo

packages/react-core/src/components/Tabs/TabsContext.ts
Fixes build issue by making context close handler optional.
=> fix(Tabs): make close handler optional

packages/react-core/src/components/Banner/Banner.tsx, packages/react-core/src/components/Banner/__tests__/Banner.test.tsx, packages/react-core/src/components/Banner/__tests__/__snapshots__/Banner.test.tsx.snap, packages/react-core/src/components/Banner/examples/BannerBasic.tsx
=> fix(Banner): add screen reader text

packages/react-table/src/demos/Table.md
=> fix(Table): Removed duplicate import from md file

packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/StyleNode.tsx, packages/react-topology/src/components/nodes/DefaultNode.tsx
**What**: 
Closes https://github.com/patternfly/patternfly-react/issues/7436
**Screen Shot**:
=> feat(Topology): Add node scaling on hover at low details scale level

packages/react-core/src/components/Slider/Slider.tsx, packages/react-core/src/components/Slider/examples/Slider.md, packages/react-integration/demo-app-ts/src/components/demos/SliderDemo/SliderDemo.tsx
**What**: Closes #7180 
this is the formula we apply
``` percentage = (newPercentage * (max - min)) / 100 + min```;
-  normalize  '**new percentage**' : from 100% to max %
- **+ min**: start offset in case the first value is not 0%
=> fix(Slider): use slider with no linear data

packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx
**What**: Closes #7341
I will create a follow-up issue shortly for figuring out how to effectively test components using Monaco and/or React Dropzone in accordance with our new testing guidelines.
=> fix(CodeEditor): enable external updating of editor value on file upload

packages/react-docs/patternfly-docs.css.js
fixes https://github.com/patternfly/patternfly-react/issues/7484
=> chore(react-docs): remove dark theme stylesheet

packages/react-core/src/components/InputGroup/InputGroup.tsx, packages/react-core/src/components/SearchInput/AdvancedSearchMenu.tsx, packages/react-core/src/components/SearchInput/SearchInput.tsx, packages/react-core/src/components/SearchInput/__tests__/SearchInput.test.tsx, packages/react-core/src/components/SearchInput/__tests__/__snapshots__/SearchInput.test.tsx.snap, packages/react-core/src/components/SearchInput/examples/SearchInput.md, packages/react-core/src/components/TextInputGroup/TextInputGroup.tsx, packages/react-core/src/components/TextInputGroup/TextInputGroupMain.tsx, packages/react-integration/cypress/integration/searchinput.spec.ts
=> refactor(Search Input): use TextInputGroup instead native HTML elements

packages/react-table/src/components/TableComposable/TableComposable.tsx, packages/react-table/src/components/TableComposable/Tr.tsx, packages/react-table/src/components/TableComposable/examples/ComposableTableHoverable.tsx
**What**: Addresses part of #6295 
Convenience link: https://patternfly-react-pr-7447.surge.sh/components/table/react-composable/composable-row-click-handler-hoverable--selected-rows/
=> fix(Table): improve a11y for selectable table rows

packages/react-core/src/components/DataList/DataList.tsx, packages/react-core/src/components/DataList/DataListItem.tsx, packages/react-core/src/components/DataList/__tests__/DataList.test.tsx, packages/react-core/src/components/DataList/examples/DataList.md, packages/react-core/src/components/DataList/examples/DataListSelectableRows.tsx, packages/react-core/src/demos/PrimaryDetail.md
**What**: Closes #7472
Convenience link: https://patternfly-react-pr-7474.surge.sh/components/data-list/react/selectable-rows/
=> fix(DataList): improve a11y for selectable data list items

packages/react-core/src/components/EmptyState/examples/EmptyState.md, packages/react-core/src/components/EmptyState/examples/EmptyStateBasic.tsx, packages/react-core/src/components/EmptyState/examples/EmptyStateExtraLarge.tsx, packages/react-core/src/components/EmptyState/examples/EmptyStateExtraSmall.tsx, packages/react-core/src/components/EmptyState/examples/EmptyStateLarge.tsx, packages/react-core/src/components/EmptyState/examples/EmptyStateNoMatchFound.tsx, packages/react-core/src/components/EmptyState/examples/EmptyStateSmall.tsx, packages/react-core/src/components/EmptyState/examples/EmptyStateSpinner.tsx
=> chore(Empty State): convert empty state demos to TS

packages/react-core/src/components/Label/Label.tsx, packages/react-core/src/components/Label/examples/Label.md
Signed-off-by: Tomas Psota <tpsota@redhat.com>
**What**: Closes #7449
=> feat(Label): add Gold color for Label

packages/react-core/src/components/Select/Select.tsx, packages/react-integration/cypress/integration/select.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectDemo.tsx
**What**: Closes #7134
Adds logic to Select update function to account for select option groups.
=> fix(Select): check for updates in grouped select options

packages/react-core/src/demos/Wizard/WizardDemo.md
=> chore(Wizard): wrap Wizard modal example in page

packages/react-core/src/demos/Card/Card.md
=> fix(CardViewDemo): remove highlight select cards (use checkboxes only), include some checked indicator

packages/react-topology/src/elements/BaseNode.ts
**What**: 
Fixes an issue where groups with no children cannot be positioned.
Closes https://github.com/patternfly/patternfly-react/issues/7572
None
=> fix(Topology): Fix for group position when it has no children

packages/react-table/src/components/TableComposable/Tr.tsx, packages/react-table/src/components/TableComposable/examples/ComposableTable.md, packages/react-table/src/components/TableComposable/examples/ComposableTableCompoundExpandable.tsx, packages/react-table/src/components/TableComposable/examples/ComposableTableExpandable.tsx, packages/react-table/src/components/TableComposable/examples/ComposableTableNestedExpandable.tsx, packages/react-table/src/components/TableComposable/examples/ComposableTableNestedTableExpandable.tsx, packages/react-table/src/components/TableComposable/examples/ComposableTableStripedExpandable.tsx, packages/react-table/src/components/TableComposable/examples/ComposableTableTree.tsx
=> fix(Table): update expandable examples to set column widths

packages/react-core/src/components/NotificationBadge/examples/NotificationBadge.md, packages/react-core/src/components/NotificationBadge/examples/NotificationBadgeBasic.tsx, packages/react-core/src/components/NotificationBadge/examples/NotificationBadgeWithCount.tsx
=> chore(NotificationBadge):convert examples to typescript

packages/react-core/src/components/DragDrop/DragDrop.tsx
=> export type so it can be used by implementations

packages/react-core/src/components/Hint/__tests__/Hint.test.tsx, packages/react-core/src/components/Hint/__tests__/HintBody.test.tsx, packages/react-core/src/components/Hint/__tests__/HintFooter.test.tsx, packages/react-core/src/components/Hint/__tests__/HintTitle.test.tsx, packages/react-core/src/components/Hint/__tests__/__snapshots__/Hint.test.tsx.snap, packages/react-core/src/components/Hint/__tests__/__snapshots__/HintBody.test.tsx.snap, packages/react-core/src/components/Hint/__tests__/__snapshots__/HintFooter.test.tsx.snap, packages/react-core/src/components/Hint/__tests__/__snapshots__/HintTitle.test.tsx.snap
**What**: Closes #7616 . Added new tests for the Hint component (and subcomponents).
=> chore(Hint): react testing library test revamps

packages/react-core/src/components/Wizard/Wizard.tsx, packages/react-core/src/components/Wizard/__tests__/Wizard.test.tsx, packages/react-core/src/components/Wizard/examples/Wizard.md
**What**: Closes #7302
Note: modify  the prop **canJumpTo** creates conflict with the progressive wizard, so I added a new prop called **isDisabled**
=> feat(Wizard): allow for an optional step in the wizard

packages/react-core/src/helpers/OUIA/ouia.ts
=> Fix conditional call of useMemo hook when getting OUIAId

packages/react-docs/patternfly-docs/patternfly-docs.config.js
**What**: Closes #7278 
**Additional issues**: Depends on https://github.com/patternfly/patternfly-org/pull/3014
=> Enable dark theme switch in workspace

packages/react-core/src/components/Button/examples/ButtonProgress.tsx
fixes https://github.com/patternfly/patternfly-react/issues/7715
=> chore(button): fixed progress animation in example code

packages/react-core/src/components/TreeView/TreeView.tsx, packages/react-core/src/components/TreeView/TreeViewListItem.tsx
=> feat(TreeView): add generic HTML element type for 'onCheck'

packages/react-core/src/components/Switch/Switch.tsx, packages/react-core/src/components/Switch/__tests__/__snapshots__/Switch.test.tsx.snap, packages/react-core/src/components/Switch/examples/Switch.md
=> fix(Switch): aria labelledby to update with change

packages/react-integration/demo-app-ts/src/App.tsx, packages/react-integration/demo-app-ts/src/Demos.ts, packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/PipelineLayout.tsx, packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/PipelineTasks.tsx, packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/TopologyDemo.css, packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/TopologyPipelineDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/DemoTaskNode.tsx, packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/pipelineComponentFactory.tsx, packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/utils/pipelineUtils.ts, packages/react-styles/src/css/components/Topology/topology-components.css, packages/react-styles/src/css/components/Topology/topology-pipelines.css, packages/react-topology/src/pipelines/components/anchors/TaskNodeSourceAnchorSave.ts, packages/react-topology/src/pipelines/components/edges/TaskEdge.tsx, packages/react-topology/src/pipelines/components/nodes/TaskBadge.tsx, packages/react-topology/src/pipelines/components/nodes/TaskNode.tsx, packages/react-topology/src/pipelines/decorators/WhenDecorator.tsx, packages/react-topology/src/pipelines/utils/draw-utils.ts
**What**: 
Closes https://github.com/patternfly/patternfly-react/issues/7696
Adds badges and icon support to pipeline task nodes
Makes task nodes variable width.
/cc @karthikjeeyar
=> feat(topology): Pipelines support for badges/icons variable task node width

packages/react-core/src/components/Pagination/examples/Pagination.md, packages/react-core/src/components/Toolbar/examples/Toolbar.md
=> fix(Pagination): fix per-page selection handling in examples

packages/react-core/src/components/Page/examples/Page.md
=> fix(Page) group section example not keyboard accesible

packages/react-core/src/components/DataList/DataList.tsx, packages/react-core/src/components/DataList/DataListItem.tsx, packages/react-core/src/components/DataList/__tests__/DataList.test.tsx, packages/react-core/src/components/DataList/examples/DataListSelectableRows.tsx
**What**: Closes #7688 
Related to #7491
=> bug(DataList): remove multiple select support

packages/react-core/src/components/Switch/examples/Switch.md, packages/react-core/src/components/Switch/examples/SwitchBasic.tsx, packages/react-core/src/components/Switch/examples/SwitchCheckedWithLabel.tsx, packages/react-core/src/components/Switch/examples/SwitchDisabled.tsx, packages/react-core/src/components/Switch/examples/SwitchReversed.tsx, packages/react-core/src/components/Switch/examples/SwitchUncontrolled.tsx, packages/react-core/src/components/Switch/examples/SwitchWithoutLabel.tsx
=> chore(Switch): converted examples to TypeScript

packages/react-core/src/components/ContextSelector/ContextSelector.tsx, packages/react-core/src/components/ContextSelector/ContextSelectorToggle.tsx
Signed-off-by: Adithya Krishna <adikrish@redhat.com>
**What**: Closes #7457
=> Bug(ContextSelector) - Updated Param Type of toggleText in ContentSelector

packages/react-catalog-view-extension/package.json, packages/react-console/package.json, packages/react-core/package.json, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
=> chore(deps): update dependency @patternfly/patternfly

packages/react-core/src/components/MenuToggle/MenuToggle.tsx
Implements @jeffpuzzo's suggestion in https://github.com/patternfly/patternfly-react/pull/7797#issuecomment-1206516808
=> fix(MenuToggle): update base type to include div attributes as well

packages/react-core/src/components/Alert/Alert.tsx, packages/react-core/src/components/Alert/__tests__/__snapshots__/Alert.test.tsx.snap
=> chore(Alert): add default aria-label back

packages/react-core/package.json, packages/react-core/src/deprecated/components/index.ts, packages/react-core/src/deprecated/index.ts, packages/react-core/src/next/components/index.ts, packages/react-core/src/next/index.ts, packages/react-core/tsconfig.json, packages/react-docs/patternfly-docs/patternfly-docs.source.js
=> feat: Allow for 'next' and 'deprecated' react-core subpaths

packages/react-core/src/components/Tabs/__tests__/OverflowTab.test.tsx, packages/react-core/src/components/Tabs/__tests__/__snapshots__/OverflowTab.test.tsx.snap, packages/react-integration/cypress/integration/tabshorizontaloverflow.spec.ts, packages/react-integration/demo-app-ts/src/Demos.ts, packages/react-integration/demo-app-ts/src/components/demos/TabsDemo/TabsHorizontalOverflowDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/index.ts
=> chore(Tabs): add tests for overflow tab behavior

packages/react-core/src/components/Select/Select.tsx
=> fix(Select): apply aria-describedby to correct element

packages/react-charts/package.json
Add victory-cursor-container dependency
Closes https://github.com/patternfly/patternfly-react/issues/7791
=> Add victory-cursor-container dependency

package.json, yarn.lock
**What**: towards #7314
Updated to latest minor release
=> Chore(deps): Updated surge dependency

packages/react-core/package.json
=> chore(deps) bump rimraf version to latest

packages/react-core/package.json, yarn.lock
**What**: towards #7314 
bumped rollup versions to latest.
=> chore(deps): bumped rollup versions to latest

packages/react-core/src/components/TimePicker/TimePicker.tsx
=> fix(TimePicker): clean up menuAppendTo feature

packages/react-core/src/components/Card/examples/Card.md, packages/react-core/src/demos/CardDemos.md
Makes progress on patternfly-org/issues/2990
=> Adds content to card react examples

packages/react-core/package.json, yarn.lock
=> chore(dep): Reverted rollup dependency bump

packages/react-core/src/components/NumberInput/NumberInput.tsx, packages/react-core/src/components/NumberInput/__tests__/NumberInput.test.tsx, packages/react-integration/cypress/integration/numberInput.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/NumberInputDemo/NumberInputDemo.tsx
**What**: Closes #7730 
fix for null value
=> fix(NumberInput): manage null value

packages/react-core/src/components/Dropdown/__tests__/Dropdown.test.tsx, packages/react-core/src/components/Dropdown/examples/DropdownPrimaryToggle.tsx
=> chore (Dropdown): update primary example to use toggleVariant=primary

packages/react-core/src/components/ApplicationLauncher/ApplicationLauncher.tsx
=> fix(ApplicationLauncher) Throws error when items prop not provided

packages/react-core/src/components/Tabs/OverflowTab.tsx, packages/react-core/src/components/Tabs/TabButton.tsx, packages/react-core/src/components/Tabs/Tabs.tsx, packages/react-core/src/components/Tabs/__tests__/__snapshots__/OverflowTab.test.tsx.snap, packages/react-core/src/components/Tabs/__tests__/__snapshots__/Tab.test.tsx.snap, packages/react-core/src/components/Tabs/__tests__/__snapshots__/TabButton.test.tsx.snap, packages/react-core/src/components/Tabs/__tests__/__snapshots__/Tabs.test.tsx.snap
=> fix(tab): added button type (#7887)

packages/react-charts/src/components/Chart/Chart.tsx, packages/react-charts/src/components/ChartGroup/ChartGroup.tsx, packages/react-charts/src/components/ChartPie/ChartPie.tsx, packages/react-charts/src/components/ChartStack/ChartStack.tsx, packages/react-charts/src/components/ChartUtils/chart-patterns.tsx
=> Convert 'getDefaultPatternProps' to a hook

packages/react-core/src/components/MenuToggle/MenuToggle.tsx
=> fix(MenuToggle): Fixed props not displaying in docs

packages/react-core/src/components/Page/Page.tsx
**What**: Closes #7810 
Follow-up at #7938 based on discussion related to the linked issue
=> fix(Page): avoid unnecessary re-renders

packages/react-docs/patternfly-docs/patternfly-docs.source.js
=> chore(Layouts): Return missing layout docs

packages/react-core/src/components/Masthead/Masthead.tsx, packages/react-core/src/components/Page/Page.tsx, packages/react-core/src/components/Page/PageBreadcrumb.tsx, packages/react-core/src/components/Page/PageContext.tsx, packages/react-core/src/components/Page/PageGroup.tsx, packages/react-core/src/components/Page/PageHeader.tsx, packages/react-core/src/components/Page/PageHeaderToolsGroup.tsx, packages/react-core/src/components/Page/PageHeaderToolsItem.tsx, packages/react-core/src/components/Page/PageNavigation.tsx, packages/react-core/src/components/Page/PageSection.tsx, packages/react-core/src/components/Page/PageSidebar.tsx, packages/react-core/src/components/Page/PageToggleButton.tsx, packages/react-core/src/components/Page/__tests__/Page.test.tsx, packages/react-core/src/components/Page/__tests__/__snapshots__/Page.test.tsx.snap, packages/react-core/src/components/Page/index.ts, packages/react-core/src/components/Toolbar/Toolbar.tsx, packages/react-core/src/components/Toolbar/ToolbarContent.tsx, packages/react-core/src/components/Toolbar/ToolbarGroup.tsx, packages/react-core/src/components/Toolbar/ToolbarItem.tsx, packages/react-core/src/components/Toolbar/ToolbarToggleGroup.tsx, packages/react-core/src/demos/Page/Page.md
**What**: Closes #7944
I added <PageGroup> back to the Page main group.
I also:
-  Moved the context into a separate file to resolve circular dependency.
- cleaned up unused imports
-  cleaned up console errors with demos.
=> fix(Page): Fixed page group props regression

packages/react-core/src/components/Menu/examples/Menu.md
=> docs(Menu): Added menu group props to documentation

packages/react-core/src/components/Checkbox/Checkbox.tsx, packages/react-core/src/components/Checkbox/examples/Checkbox.md, packages/react-core/src/components/Checkbox/examples/CheckboxRequired.tsx
=> feat(checkbox): add required variant

packages/react-core/src/components/Text/examples/Text.md
=> chore(text): fixed description list example title

packages/react-core/src/components/Tabs/Tabs.tsx, packages/react-core/src/components/Tabs/__tests__/Tabs.test.tsx, packages/react-core/src/components/Tabs/__tests__/__snapshots__/Tabs.test.tsx.snap, packages/react-integration/cypress/integration/tabs.spec.ts
**What**: Closes #7814 
Convenience link: https://patternfly-react-pr-8011.surge.sh/components/tabs#vertical
=> fix(Tabs): prevented scroll buttons from rendering when not needed

.github/release.sh, .github/workflows-src/release.yml, .github/workflows/release.yml
=> chore: Fix lerna creating incorrect version bumps

.github/workflows/add-new-issues-to-project.yml
Closes: https://github.com/patternfly/patternfly-react/issues/8008
All new issues should be added to the PatternFly Issue Project when they are opened
=> chore: add github action for new issues

packages/react-core/src/components/Alert/examples/Alert.md
Makes progress on patternfly/patternfly-org#2990 
(a redo of a former PR with feedback integrated)
=> Adds content to alert react examples

packages/react-core/src/components/DatePicker/DatePicker.tsx
=> fix(DatePicker): Changed  popoverProps type to partial

packages/react-core/src/components/Breadcrumb/Breadcrumb.tsx
=> fix(Breadcrumb): Fixed type error

packages/react-core/src/components/TextArea/TextArea.tsx, packages/react-core/src/components/TextArea/__tests__/TextArea.test.tsx, packages/react-core/src/components/TextArea/__tests__/__snapshots__/TextArea.test.tsx.snap, packages/react-core/src/components/TextArea/examples/TextArea.md, packages/react-core/src/components/TextInput/TextInput.tsx, packages/react-core/src/components/TextInput/__tests__/TextInput.test.tsx, packages/react-core/src/components/TextInput/__tests__/__snapshots__/TextInput.test.tsx.snap, packages/react-core/src/components/TextInput/examples/TextInput.md
=> feat(TextArea+TextInput): added plain read-only variant

packages/react-core/src/components/DatePicker/DatePicker.tsx, packages/react-core/src/components/DatePicker/__tests__/DatePicker.test.tsx
=> fix(DatePicker) Invalid input with multiple validators

packages/react-core/src/helpers/Popper/Popper.tsx, packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/DemoTaskNode.tsx, packages/react-topology/src/pipelines/components/nodes/TaskNode.tsx
**What**: 
Fixes #8100 
/cc @christianvogt @karthikjeeyar
=> fix(Topology): Fix for multiple popovers occurring for pipeline badges

packages/react-core/src/components/Select/Select.tsx, packages/react-core/src/components/Select/SelectToggle.tsx
**What**: Closes #7987 
No idea what else needs to be done, long time no contribution from my side.
=> Add Select dropdown icon change option

packages/react-core/src/components/DatePicker/DatePicker.tsx, packages/react-core/src/components/DatePicker/__tests__/DatePicker.test.tsx, packages/react-integration/cypress/integration/datepicker.spec.ts, packages/react-integration/demo-app-ts/src/Demos.ts, packages/react-integration/demo-app-ts/src/components/demos/DatePickerDemo/DatePickerDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/index.ts
=> fix(DatePicker) clear validation error from outside

packages/react-core/src/components/Form/Form.tsx, packages/react-core/src/components/LoginPage/LoginForm.tsx
**What**: Closes #7899 
It's my first time working with forwardRef and TypeScript together. In this way, I would be very happy for any kind of feedback :)
=> feature(Form): Add support for forwardRef

packages/react-core/src/demos/examples/DashboardHeader.js
=> fix(DashboardHeader): display full kebab at mobile breakpoint

packages/react-core/src/components/TreeView/TreeView.tsx, packages/react-core/src/components/TreeView/TreeViewListItem.tsx, packages/react-core/src/components/TreeView/TreeViewRoot.tsx, packages/react-core/src/components/TreeView/__tests__/__snapshots__/TreeView.test.tsx.snap
**What**: Closes #7759
Waiting on a core update to fix the styling of the text.
=> feat(TreeView): update selectable keyboard interaction

packages/react-table/src/components/TableComposable/Th.tsx
=> fix(Table): Fix occasional double tooltip on Th

packages/react-core/src/helpers/constants.ts
Closes #7972 
wasn't being used anywhere
=> chore: remove keycodes definition

packages/react-console/src/components/AccessConsoles/__tests__/__snapshots__/AccessConsoles.test.tsx.snap, packages/react-console/src/components/SerialConsole/__tests__/__snapshots__/SerialConsole.test.tsx.snap, packages/react-console/src/components/VncConsole/__tests__/__snapshots__/VncConsole.test.tsx.snap, packages/react-core/src/components/Backdrop/examples/BackdropSpinner.tsx, packages/react-core/src/components/Button/__tests__/__snapshots__/Button.test.tsx.snap, packages/react-core/src/components/Spinner/Spinner.tsx, packages/react-core/src/components/Spinner/__tests__/Spinner.test.tsx, packages/react-core/src/components/Spinner/__tests__/__snapshots__/Spinner.test.tsx.snap
=> chore(Spinner): updated isSVG prop default value

packages/react-core/src/components/Menu/examples/MenuWithDrilldown.tsx, packages/react-core/src/components/Menu/examples/MenuWithDrilldownBreadcrumbs.tsx, packages/react-core/src/components/Menu/examples/MenuWithDrilldownSubmenuFunctions.tsx
=> fix(Menu): fixed height issue with drilldown examples

packages/react-core/src/components/EmptyState/examples/EmptyState.md
=> docs(Empty state): Added EmptyStatePrimary to documentation

packages/react-core/src/components/Nav/Nav.tsx, packages/react-core/src/components/Nav/__tests__/__snapshots__/Nav.test.tsx.snap, packages/react-core/src/components/Nav/examples/NavDefault.tsx, packages/react-core/src/components/Nav/examples/NavDrilldown.tsx, packages/react-core/src/components/Nav/examples/NavExpandable.tsx, packages/react-core/src/components/Nav/examples/NavExpandableThirdLevel.tsx, packages/react-core/src/components/Nav/examples/NavFlyout.tsx, packages/react-core/src/components/Nav/examples/NavGrouped.tsx, packages/react-core/src/components/Nav/examples/NavHorizontalPageHeader.tsx, packages/react-core/src/components/Nav/examples/NavHorizontalSubNav.tsx, packages/react-core/src/components/Nav/examples/NavLegacyTertiary.tsx, packages/react-core/src/components/Nav/examples/NavMixed.tsx
=> fix(Nav): horizontalsubnav aria label default to Local

packages/react-core/src/components/ApplicationLauncher/ApplicationLauncher.tsx, packages/react-core/src/components/ContextSelector/ContextSelector.tsx, packages/react-core/src/components/Dropdown/Dropdown.tsx, packages/react-core/src/components/OptionsMenu/OptionsMenu.tsx, packages/react-core/src/components/Select/Select.tsx, packages/react-core/src/helpers/Popper/Popper.tsx
**What**: Closes #7438 
**Additional issues**: #7173 #7435
=> Removed deprecated prop interface ToggleMenuBaseProps

packages/react-core/src/components/SimpleList/examples/SimpleList.md, packages/react-core/src/components/SimpleList/examples/SimpleListBasic.tsx, packages/react-core/src/components/SimpleList/examples/SimpleListGrouped.tsx, packages/react-core/src/components/SimpleList/examples/SimpleListUncontrolled.tsx
=> chore(SimpleList):convert to typescript

packages/react-core/src/components/Slider/Slider.tsx, packages/react-core/src/components/Slider/_tests_/__snapshots__/Slider.test.tsx.snap
=> chore(Slider): revert taborder update

packages/react-core/src/components/Accordion/Accordion.tsx, packages/react-core/src/components/Accordion/__tests__/Accordion.test.tsx, packages/react-core/src/components/Accordion/examples/AccordionBordered.tsx, packages/react-core/src/components/DescriptionList/DescriptionList.tsx, packages/react-core/src/components/DescriptionList/examples/DescriptionList.md, packages/react-core/src/components/DescriptionList/examples/DescriptionListWithLargeDisplaySize.tsx, packages/react-core/src/components/DescriptionList/examples/DescriptionListWithLargeDisplaySizeAndCard.tsx, packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx, packages/react-core/src/components/ExpandableSection/__tests__/ExpandableSection.test.tsx, packages/react-core/src/components/ExpandableSection/examples/ExpandableSectionDisclosure.tsx, packages/react-integration/demo-app-ts/src/components/demos/ExpandableSectionDemo/ExpandableSectionDemo.tsx
=> chore(Accordion, ExpandableSection, DescriptionList): update displaySize prop values

packages/react-core/src/components/Pagination/OptionsToggle.tsx, packages/react-core/src/components/Pagination/Pagination.tsx, packages/react-core/src/components/Pagination/PaginationOptionsMenu.tsx, packages/react-core/src/components/Pagination/__tests__/Generated/__snapshots__/OptionsToggle.test.tsx.snap, packages/react-core/src/components/Pagination/__tests__/Pagination.test.tsx, packages/react-core/src/components/Pagination/__tests__/__snapshots__/Pagination.test.tsx.snap, packages/react-core/src/components/Pagination/examples/PaginationBottom.tsx, packages/react-core/src/components/Pagination/examples/PaginationCompact.tsx, packages/react-core/src/components/Pagination/examples/PaginationDisabled.tsx, packages/react-core/src/components/Pagination/examples/PaginationIndeterminate.tsx, packages/react-core/src/components/Pagination/examples/PaginationNoItems.tsx, packages/react-core/src/components/Pagination/examples/PaginationOnePage.tsx, packages/react-core/src/components/Pagination/examples/PaginationSticky.tsx, packages/react-core/src/components/Pagination/examples/PaginationTop.tsx, packages/react-table/src/docs/demos/table-demos/ColumnManagement.jsx
=> fix(Pagination): prevented regenerating random id on each render

packages/react-catalog-view-extension/package.json, packages/react-console/package.json, packages/react-core/package.json, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
=> chore: bump @patternfly/patternfly to 4.219.2

packages/react-core/src/components/Alert/__tests__/AlertActionCloseButton.test.tsx, packages/react-core/src/components/Alert/__tests__/AlertActionLink.test.tsx, packages/react-core/src/components/Alert/__tests__/AlertToggleExpandButton.test.tsx, packages/react-core/src/components/Alert/__tests__/__snapshots__/AlertActionCloseButton.test.tsx.snap, packages/react-core/src/components/Alert/__tests__/__snapshots__/AlertActionLink.test.tsx.snap, packages/react-core/src/components/Alert/__tests__/__snapshots__/AlertToggleExpandButton.test.tsx.snap, packages/react-core/src/components/BackToTop/__tests__/BackToTop.test.tsx, packages/react-core/src/components/BackToTop/__tests__/__snapshots__/BackToTop.test.tsx.snap, packages/react-core/src/components/Button/__mocks__/Button.tsx, packages/react-core/src/components/Button/__mocks__/index.ts
=> chore(tests): created shareable button mock

packages/react-core/src/components/Backdrop/__tests__/Backdrop.test.tsx, packages/react-core/src/components/Backdrop/__tests__/__snapshots__/Backdrop.test.tsx.snap
=> chore(Backdrop): update component unit tests to meet new RTL standards

packages/react-core/src/components/Button/Button.tsx, packages/react-core/src/components/Button/__tests__/__snapshots__/Button.test.tsx.snap, packages/react-core/src/components/Spinner/Spinner.tsx, packages/react-core/src/components/Spinner/examples/Spinner.md, packages/react-core/src/components/Spinner/examples/SpinnerInline.tsx
fixes https://github.com/patternfly/patternfly-react/issues/8327
=> feat(spinner): added isInline, updated link button

packages/react-docs/RELEASE-NOTES.md
=> chore: fix release notes typos

packages/tsconfig.base.json
=> fix(build): stopped shipping mock files

packages/react-table/src/components/TableComposable/examples/ComposableTableMisc.tsx
=> chore(ComposableTable): Update custom row wrapper example

packages/react-table/src/components/TableComposable/TableComposable.tsx, packages/react-table/src/components/TableComposable/examples/ComposableTableHoverable.tsx
=> feat(TableComposable): remove hasSelectableRowCaption prop

packages/react-core/src/next/components/Dropdown/DropdownItem.tsx
=> fix(Dropdown next): Added itemId to DropdownItem props

packages/react-core/src/components/Wizard/WizardFooterInternal.tsx, packages/react-core/src/components/Wizard/__tests__/Generated/__snapshots__/WizardFooterInternal.test.tsx.snap, packages/react-core/src/components/Wizard/__tests__/__snapshots__/Wizard.test.tsx.snap, packages/react-core/src/components/Wizard/examples/Wizard.md, packages/react-core/src/next/components/Wizard/WizardFooter.tsx, packages/react-core/src/next/components/Wizard/examples/WizardKitchenSink.tsx
**What**: Closes #8166 
Also fixes some bugs in the button functionality within the demos.
=> chore(wizard): updated button order

packages/react-core/src/components/Panel/__tests__/Panel.test.tsx, packages/react-core/src/components/Panel/__tests__/PanelFooter.test.tsx, packages/react-core/src/components/Panel/__tests__/PanelHeader.test.tsx, packages/react-core/src/components/Panel/__tests__/PanelMain.test.tsx, packages/react-core/src/components/Panel/__tests__/PanelMainBody.test.tsx, packages/react-core/src/components/Panel/__tests__/__snapshots__/PanelFooter.test.tsx.snap, packages/react-core/src/components/Panel/__tests__/__snapshots__/PanelHeader.test.tsx.snap, packages/react-core/src/components/Panel/__tests__/__snapshots__/PanelMain.test.tsx.snap, packages/react-core/src/components/Panel/__tests__/__snapshots__/PanelMainBody.test.tsx.snap
=> chore(Panel): update component unit tests to meet new RTL standards

packages/react-core/src/components/Sidebar/SidebarPanel.tsx, packages/react-core/src/components/Sidebar/__tests__/Sidebar.test.tsx, packages/react-core/src/components/Sidebar/__tests__/SidebarContent.test.tsx, packages/react-core/src/components/Sidebar/__tests__/SidebarPanel.test.tsx, packages/react-core/src/components/Sidebar/__tests__/__snapshots__/Sidebar.test.tsx.snap, packages/react-core/src/components/Sidebar/__tests__/__snapshots__/SidebarContent.test.tsx.snap, packages/react-core/src/components/Sidebar/__tests__/__snapshots__/SidebarPanel.test.tsx.snap
=> chore(Sidebar): update tests to new react testing library standards

packages/react-core/src/components/Pagination/Pagination.tsx, packages/react-core/src/components/Pagination/__tests__/Pagination.test.tsx, packages/react-core/src/components/Pagination/__tests__/__snapshots__/Pagination.test.tsx.snap, packages/react-core/src/components/Pagination/examples/Pagination.md, packages/react-core/src/components/Pagination/examples/PaginationInset.tsx
=> fix(Pagination): Added support for insets

packages/react-catalog-view-extension/package.json, packages/react-console/package.json, packages/react-core/package.json, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-integration/cypress/integration/menu.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/MenuDemo/MenuDrilldownDemo.tsx, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
Bumped core version and updated menu demo and failing test
=> Core bump 4 222 3

packages/react-core/src/components/Slider/Slider.tsx, packages/react-core/src/components/Slider/_tests_/__snapshots__/Slider.test.tsx.snap
**What**: Closes #8380 
Should wait until the Core PR is merged and the patternfly version is bumped to ensure the styles are applied properly for this.
=> fix(Slider): updated input text styling

packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/StyleNode.tsx, packages/react-topology/src/components/nodes/DefaultNode.tsx
Signed-off-by: John Swanke <jswanke@redhat.com>
[**What**: Closes #]
https://github.com/patternfly/patternfly-react/issues/8476
=> feat(Topology): Counter scale labels

packages/react-table/src/components/TableComposable/examples/ComposableTable.md, packages/react-table/src/components/TableComposable/examples/ComposableTableTree.tsx
=> fix(TableComposable): Fixed parent checkbox behavior

packages/react-core/src/components/SearchInput/SearchInput.tsx, packages/react-core/src/components/TextInputGroup/TextInputGroupMain.tsx
=> fix(SearchInput) - add a name prop to the input

packages/react-core/src/components/TimePicker/TimePicker.tsx, packages/react-core/src/components/TimePicker/__tests__/TimePicker.test.tsx, packages/react-core/src/components/TimePicker/examples/TimePicker.md, packages/react-core/src/demos/DatePicker/DatePicker.md
=> feat(TimePicker): added event to onChange callback

packages/react-core/src/components/Label/Label.tsx, packages/react-core/src/components/Label/examples/LabelEditable.tsx, packages/react-core/src/components/LabelGroup/examples/LabelGroupEditableAdd.tsx, packages/react-core/src/components/LabelGroup/examples/LabelGroupEditableAddDropdown.tsx, packages/react-core/src/components/LabelGroup/examples/LabelGroupEditableAddModal.tsx, packages/react-core/src/components/LabelGroup/examples/LabelGroupEditableLabels.tsx, packages/react-integration/demo-app-ts/src/components/demos/LabelGroupDemo/LabelGroupEditableDemo.tsx
=> feat(Label): add event parameter

packages/react-table/src/docs/demos/Table.md
Closes https://github.com/patternfly/patternfly-react/issues/8547
=> fix(Table): fixed draggable column management demo

packages/react-core/src/next/components/Dropdown/examples/Dropdown.md
=> Adds content to dropdown next component examples.

packages/react-topology/src/components/TopologyView/examples/Topology.md, packages/react-topology/src/components/TopologyView/examples/TopologyPanZoomDemo.tsx
**What**: Closes https://github.com/patternfly/patternfly-extension-issues/issues/15
=> docs(topology): Add pan/zoom demo

packages/react-core/src/components/Accordion/AccordionContent.tsx, packages/react-core/src/components/Accordion/__tests__/AccordionContent.test.tsx, packages/react-core/src/components/Accordion/examples/AccordionFixedWithMultipleExpandBehavior.tsx, packages/react-integration/cypress/integration/accordion.spec.ts, packages/react-integration/demo-app-ts/src/Demos.ts, packages/react-integration/demo-app-ts/src/components/demos/Accordion/AccordionDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/index.ts
**What**: Closes #8276 
[Accordion fixed with multiple expand example](https://patternfly-react-pr-8515.surge.sh/components/accordion#fixed-with-multiple-expand-behavior)
Also added an aria-labelledby prop and updated the fixed with multiple expand to show the scrollable bar.
=> feat(Accordion): made scrollable content focusable

packages/react-core/src/components/Chip/Chip.tsx, packages/react-core/src/components/Chip/__tests__/__snapshots__/Chip.test.tsx.snap, packages/react-core/src/components/ChipGroup/__tests__/__snapshots__/ChipGroup.test.tsx.snap, packages/react-core/src/components/Select/__tests__/__snapshots__/Select.test.tsx.snap, packages/react-core/src/components/Toolbar/__tests__/__snapshots__/Toolbar.test.tsx.snap
=> fix(Chip): spread fewer props

packages/react-docs/package.json, packages/react-docs/patternfly-docs/patternfly-docs.source.js, yarn.lock
=> fix(react-docs): remove dependency on react-catalog-view-extension

packages/react-docs/CHANGELOG.md, packages/react-docs/RELEASE-NOTES.md, packages/react-docs/package.json, packages/react-docs/patternfly-a11y.config.js, packages/react-docs/patternfly-docs/patternfly-docs.config.js, packages/react-docs/patternfly-docs/patternfly-docs.css.js, packages/react-topology/src/components/TopologyView/examples/Topology.md, packages/react-topology/src/components/TopologyView/examples/topology-example.css
**What**: Towards https://github.com/patternfly/patternfly-org/issues/3349
=> docs(topology): update section to top-level nav item

packages/react-core/src/components/CodeBlock/CodeBlock.tsx, packages/react-core/src/components/CodeBlock/__tests__/__snapshots__/CodeBlock.test.tsx.snap
=> fix(Code block): Fixed to only render the header when actions are defined

packages/react-topology/src/components/TopologyView/examples/TopologySidebar.md, packages/react-topology/src/components/TopologyView/examples/TopologySidebarDemo.tsx, packages/react-topology/src/components/TopologyView/examples/topology-example.css
**What**: Closes https://github.com/patternfly/patternfly-extension-issues/issues/28
=> docs(topology): add sidebar demo and documentation

packages/react-core/src/components/Toolbar/ToolbarContent.tsx, packages/react-core/src/components/Toolbar/ToolbarGroup.tsx, packages/react-core/src/components/Toolbar/ToolbarItem.tsx, packages/react-core/src/components/Toolbar/examples/ToolbarStacked.tsx, packages/react-core/src/demos/Card/Card.md, packages/react-core/src/demos/NotificationDrawer/NotificationDrawer.md, packages/react-core/src/demos/Toolbar.md, packages/react-core/src/demos/examples/DashboardHeader.js, packages/react-core/src/demos/examples/Masthead/MastheadWithUtilitiesAndUserDropdownMenu.tsx, packages/react-core/src/demos/examples/Page/PageStickySectionBreadcrumb.tsx, packages/react-core/src/demos/examples/Page/PageStickySectionGroup.tsx, packages/react-core/src/demos/examples/Page/PageStickySectionGroupAlternate.tsx, packages/react-integration/demo-app-ts/src/components/demos/MastheadDemo/MastheadDemo.tsx, yarn.lock
=> feat(Toolbar): support for vertical alignments

packages/react-topology/src/components/TopologyView/examples/TopologyToolbar.md, packages/react-topology/src/components/TopologyView/examples/TopologyToolbarDemo.tsx, packages/react-topology/src/components/TopologyView/examples/topology-example.css, packages/react-topology/src/types.ts
**What**: Will close https://github.com/patternfly/patternfly-extension-issues/issues/27 once completed
=> docs(topology): add toolbar demo

packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/ContextMenus.tsx, packages/react-topology/src/components/TopologyView/examples/TopologyContextMenu.md, packages/react-topology/src/components/TopologyView/examples/TopologyContextMenuDemo.tsx, packages/react-topology/src/components/TopologyView/examples/TopologySelectable.md, packages/react-topology/src/components/TopologyView/examples/topology-example.css
**What**: Closes https://github.com/patternfly/patternfly-extension-issues/issues/33
=> docs(topology): add context menu demo and documentation

packages/react-topology/src/components/TopologyView/examples/TopologyAnchors.md, packages/react-topology/src/components/TopologyView/examples/TopologyAnchorsDemo.tsx, packages/react-topology/src/components/TopologyView/examples/TopologyToolbar.md, packages/react-topology/src/components/TopologyView/examples/topology-example.css
**What**: Closes https://github.com/patternfly/patternfly-extension-issues/issues/29
=> docs(topology): add anchors demo and documentation

packages/react-docs/patternfly-docs/patternfly-docs.source.js
**What**: Closes #8401 
**Additional issues**: Towards #8005
=> Clean up comments in patternfly-docs.source.js

packages/react-core/src/components/NumberInput/NumberInput.tsx, packages/react-core/src/components/NumberInput/__tests__/NumberInput.test.tsx, packages/react-core/src/components/NumberInput/examples/NumberInputCustomStep.tsx, packages/react-core/src/components/NumberInput/examples/NumberInputCustomStepAndThreshold.tsx, packages/react-core/src/components/NumberInput/examples/NumberInputDefault.tsx, packages/react-core/src/components/NumberInput/examples/NumberInputDisabled.tsx, packages/react-core/src/components/NumberInput/examples/NumberInputUnit.tsx, packages/react-core/src/components/NumberInput/examples/NumberInputUnitThreshold.tsx, packages/react-core/src/components/NumberInput/examples/NumberInputVaryingSizes.tsx, packages/react-core/src/components/NumberInput/examples/NumberInputWithStatus.tsx, packages/react-core/src/demos/examples/AlertGroup/AlertGroupToastWithNotificationDrawer.tsx, packages/react-integration/demo-app-ts/src/components/demos/NumberInputDemo/NumberInputDemo.tsx
=> chore(NumberInput): remove allowEmptyInput prop

packages/react-topology/src/components/TopologySideBar/TopologySideBar.tsx, packages/react-topology/src/components/TopologyView/examples/TopologyControlBar.md, packages/react-topology/src/components/TopologyView/examples/TopologyCustomEdges.md, packages/react-topology/src/components/TopologyView/examples/TopologyCustomNodes.md, packages/react-topology/src/components/TopologyView/examples/TopologyGettingStarted.md, packages/react-topology/src/components/TopologyView/examples/TopologySidebar.md, packages/react-topology/src/components/TopologyView/examples/TopologyToolbar.md, packages/react-topology/src/components/VisualizationProvider.tsx, packages/react-topology/src/components/VisualizationSurface.tsx, packages/react-topology/src/components/edges/DefaultEdge.tsx, packages/react-topology/src/components/nodes/DefaultNode.tsx
**What**:
Closes https://github.com/patternfly/patternfly-extension-issues/issues/36
=> docs(topology): Add props tables to topology docs

package.json
=> chore(linting): updated linting script to ignore built/generated files

packages/react-integration/demo-app-ts/package.json
hopefully fixes issue with demo-app react-core versions not bumping
=> fix(demo-app): update version to alpha

packages/react-core/src/components/Drawer/DrawerPanelContent.tsx, packages/react-core/src/components/Drawer/examples/DrawerResizableOnRight.tsx, packages/react-integration/demo-app-ts/src/components/demos/DrawerDemo/DrawerResizeDemo.tsx
=> fix(Drawer): added event param to onResize callback

packages/react-core/src/components/ApplicationLauncher/ApplicationLauncher.tsx, packages/react-core/src/components/ApplicationLauncher/ApplicationLauncherContext.ts, packages/react-core/src/components/ApplicationLauncher/ApplicationLauncherItem.tsx, packages/react-core/src/components/ApplicationLauncher/examples/ApplicationLauncherFavoritesAndSearch.tsx, packages/react-integration/demo-app-ts/src/components/demos/ApplicationLauncherDemo/ApplicationLauncherFavoritesDemo.tsx
=> feat(ApplicationLauncher): added event param to callbacks

packages/react-core/src/demos/DatePicker/DatePicker.md
**What**: Closes #8730 
Also fixed a bug in the Date/Time Range Picker demo where the "to" inputs were always disabled.
=> fix(DatePicker): fixed errors in demos

packages/react-core/src/components/CalendarMonth/CalendarMonth.tsx, packages/react-core/src/components/CalendarMonth/examples/CalendarMonthSelectableDate.tsx, packages/react-core/src/components/DatePicker/DatePicker.tsx, packages/react-core/src/demos/examples/DateTimePicker/DateTimePicker.tsx
=> feat(CalendarMonth): event param updates

packages/react-core/src/components/TimePicker/TimePicker.tsx, packages/react-core/src/components/TimePicker/__tests__/TimePicker.test.tsx
=> fix(TimePicker): called onChange when pressing Enter

packages/react-core/src/components/Card/Card.tsx, packages/react-core/src/components/Card/examples/CardLegacySelectable.tsx, packages/react-core/src/components/Card/examples/CardSelectable.tsx, packages/react-core/src/components/Card/examples/CardSelectableA11yHighlight.tsx, packages/react-core/src/demos/PrimaryDetail.md
=> feat(Card): changed order of onSelectableInputChange params

package.json
This one seems to be causing test failures Reverts patternfly/patternfly-react#8691
=> Revert "chore(tests) fixate time format"

packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/useTopologyOptions.tsx, packages/react-topology/src/components/TopologyView/examples/TopologyDragDropDemo.md, packages/react-topology/src/components/TopologyView/examples/TopologyDragDropDemo.tsx, packages/react-topology/src/components/TopologyView/examples/TopologyPipelinesGettingStarted.md, packages/react-topology/src/components/TopologyView/examples/topology-example.css
**What**: Closes https://github.com/patternfly/patternfly-extension-issues/issues/17
=> docs(topology): Add drag and drop demo

packages/react-core/src/demos/Card/Card.md
**What**: Closes #8805 
Followup to #8759 , just needed to pass the CardHeader actions similar to the Primary detail demo.
=> fix(Card): fixed card view demo

package.json
Clean build prior to building to fix issues with referencing  old code.
Fixes issue:  https://github.com/patternfly/patternfly-react/issues/8842
=> fix(infrastructure):  Clean build prior to building

packages/react-core/src/next/components/Wizard/examples/WizardWithinModal.tsx
=> bug(Wizard) close Wizard Modal on Escape/cancel + close buttons

packages/react-code-editor/README.md
Closes: https://github.com/patternfly/patternfly-react/issues/8856
=> fix(CodeEditor): fix typo in README

packages/react-core/package.json, yarn.lock
=> chore(deps): Updated focus trap dependency

packages/react-charts/package.json, packages/react-code-editor/package.json, packages/react-core/package.json, packages/react-icons/package.json, packages/react-table/package.json, yarn.lock
=> chore(deps): updated tslib dependencies

packages/react-core/src/components/Wizard/WizardNavItem.tsx, packages/react-core/src/components/Wizard/__tests__/Generated/__snapshots__/WizardNavItem.test.tsx.snap, packages/react-core/src/components/Wizard/__tests__/__snapshots__/Wizard.test.tsx.snap
=> fix(Wizard): add type to nav item buttons

packages/react-core/src/components/Pagination/Pagination.tsx
=> chore(Pagination): Change e to event in onPerPageSelect, onSetPage 

packages/react-table/src/components/Table/Td.tsx, packages/react-table/src/components/Table/base/types.tsx
**What**: Closes #8870
**Additional issues**: 
codemod issue follows: https://github.com/patternfly/pf-codemods/issues/354
=> fix(Table): rename TdActionsType 'disable' prop to 'isDisabled'

packages/react-core/src/demos/examples/Masthead/MastheadWithUtilitiesAndUserDropdownMenu.tsx
=> fix(demo):  fixed MastheadWithUtilitiesAndUserDropdownMenu demo

packages/react-docs/package.json, yarn.lock
version bump follow up to: https://github.com/patternfly/patternfly-org/pull/3474
=> fix(docs-framework): add back props tables and fix errors

packages/react-core/src/components/Card/CardTitle.tsx, packages/react-core/src/components/Card/__tests__/__snapshots__/CardTitle.test.tsx.snap
=> fix(CardTitle): apply pf-c-card__title-text class

packages/react-core/src/components/Nav/Nav.tsx, packages/react-core/src/components/Nav/NavItem.tsx, packages/react-core/src/components/Nav/examples/Nav.md, packages/react-core/src/components/Nav/examples/NavDefault.tsx, packages/react-core/src/components/Nav/examples/NavExpandable.tsx, packages/react-core/src/components/Nav/examples/NavExpandableThirdLevel.tsx, packages/react-core/src/components/Nav/examples/NavFlyout.tsx, packages/react-core/src/components/Nav/examples/NavGrouped.tsx, packages/react-core/src/components/Nav/examples/NavHorizontalSubNav.tsx, packages/react-core/src/components/Nav/examples/NavLegacyTertiary.tsx, packages/react-core/src/components/Nav/examples/NavMixed.tsx, packages/react-core/src/demos/Nav.md, packages/react-core/src/demos/NotificationDrawer/NotificationDrawer.md, packages/react-core/src/demos/Wizard/WizardDemo.md, packages/react-core/src/demos/examples/DashboardWrapper.js, packages/react-core/src/demos/examples/Masthead/MastheadWithUtilitiesAndUserDropdownMenu.tsx, packages/react-core/src/demos/examples/Page/PageStickySectionBreadcrumb.tsx, packages/react-core/src/demos/examples/Page/PageStickySectionGroup.tsx, packages/react-core/src/demos/examples/Page/PageStickySectionGroupAlternate.tsx, packages/react-integration/demo-app-ts/src/App.tsx, packages/react-integration/demo-app-ts/src/components/demos/NavDemo/NavDemo.tsx
=> fix(Nav): updated onSelect and onToggle param order

packages/react-core/src/components/ToggleGroup/ToggleGroupItem.tsx, packages/react-core/src/components/ToggleGroup/__tests__/ToggleGroup.test.tsx, packages/react-core/src/components/ToggleGroup/examples/ToggleGroupCompact.tsx, packages/react-core/src/components/ToggleGroup/examples/ToggleGroupDefaultMultiple.tsx, packages/react-core/src/components/ToggleGroup/examples/ToggleGroupDefaultSingle.tsx, packages/react-core/src/components/ToggleGroup/examples/ToggleGroupIcon.tsx, packages/react-core/src/components/ToggleGroup/examples/ToggleGroupTextIcon.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableDropdwnVariants.tsx, packages/react-integration/demo-app-ts/src/components/demos/TableDemo/TableComposableDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/ToggleGroupDemo/ToggleGroupDemo.tsx, packages/react-table/src/components/Table/examples/TableActions.tsx, packages/react-table/src/components/Table/examples/TableBasic.tsx, packages/react-table/src/deprecated/components/Table/examples/LegacyTableActions.tsx, packages/react-table/src/deprecated/components/Table/examples/LegacyTableBasic.tsx
=> feat(ToggleGroupItem): swapped onChange params

packages/react-core/src/components/Tabs/Tabs.tsx, packages/react-core/src/components/Tabs/examples/TabsVerticalExpandable.tsx, packages/react-integration/demo-app-ts/src/components/demos/TabsDemo/TabsExpandableDemo.tsx
=> feat(Tabs): added event to onToggle

packages/react-core/src/components/DatePicker/DatePicker.tsx, packages/react-core/src/components/Popover/Popover.tsx, packages/react-core/src/components/Popover/examples/PopoverAdvanced.tsx, packages/react-core/src/components/Popover/examples/PopoverCloseControlled.tsx
=> feat(Popover): Swap params of shouldClose and shouldOpen

packages/react-integration/demo-app-ts/src/components/demos/TableDemo/TableEditableDemo.tsx, packages/react-table/src/components/Table/EditableSelectInputCell.tsx, packages/react-table/src/deprecated/components/Table/examples/Table.md
=> feat(Table): swapped param order of onSelect and clearSelection

packages/react-core/src/components/Switch/Switch.tsx, packages/react-core/src/components/Switch/__tests__/Switch.test.tsx, packages/react-core/src/components/Switch/examples/SwitchBasic.tsx, packages/react-core/src/components/Switch/examples/SwitchCheckedWithLabel.tsx, packages/react-core/src/components/Switch/examples/SwitchReversed.tsx, packages/react-core/src/components/Switch/examples/SwitchWithoutLabel.tsx, packages/react-core/src/demos/JumpLinks.md, packages/react-core/src/demos/examples/BackToTop/BackToTopNameDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/SwitchDemo/SwitchDemo.tsx
=> feat(Switch): make event first param for onChange prop

packages/react-core/src/demos/Nav.md, packages/react-core/src/deprecated/components/PageHeader/PageHeader.tsx, packages/react-core/src/deprecated/components/PageHeader/examples/PageVerticalNavUsingPageHeaderComponent.tsx, packages/react-integration/demo-app-ts/src/App.tsx, packages/react-integration/demo-app-ts/src/components/demos/PageDemo/PageDemo.tsx
**What**: Closes #8908
Also fixes broken "Manual Nav" demo
**Additional issues**:  https://github.com/patternfly/pf-codemods/issues/458
=> chore(PageHeader): add event param to onNavToggle

packages/react-core/src/components/LoginPage/LoginForm.tsx, packages/react-core/src/components/LoginPage/LoginMainFooterLinksItem.tsx, packages/react-core/src/components/LoginPage/__tests__/__snapshots__/LoginMainFooterLinksItem.test.tsx.snap, packages/react-core/src/components/LoginPage/examples/LoginPageBasic.tsx, packages/react-core/src/components/LoginPage/examples/LoginPageLanguageSelect.tsx, packages/react-core/src/components/LoginPage/examples/LoginPageShowHidePassword.tsx, packages/react-integration/demo-app-ts/src/components/demos/LoginPageDemo/LoginPageDemo.tsx
=> fix(LoginForm): updated param order

packages/react-core/src/components/FileUpload/FileUpload.tsx, packages/react-core/src/components/FileUpload/examples/FileUpload.md, packages/react-core/src/components/FileUpload/examples/FileUploadSimpleText.tsx, packages/react-core/src/components/FileUpload/examples/FileUploadTextWithEdits.tsx, packages/react-core/src/components/FileUpload/examples/FileUploadTextWithRestrictions.tsx, packages/react-core/src/components/MultipleFileUpload/MultipleFileUpload.tsx, packages/react-core/src/components/MultipleFileUpload/examples/MultipleFileUpload.md, packages/react-core/src/components/MultipleFileUpload/examples/MultipleFileUploadBasic.tsx, packages/react-core/src/demos/examples/MultipleFileUpload/MultipleFileUploadRejectedFile.tsx, packages/react-core/src/helpers/typeUtils.ts, packages/react-integration/demo-app-ts/src/components/demos/FileUploadDemo/FileUploadDemo.tsx
=> fix(FileUpload): added DropEvent as a type exported from react-core

packages/react-core/src/components/InputGroup/InputGroupText.tsx, packages/react-core/src/components/InputGroup/__tests__/InputGroupText.test.tsx, packages/react-core/src/components/InputGroup/examples/InputGroupBasic.tsx, packages/react-integration/demo-app-ts/src/components/demos/InputGroupDemo/InputGroupDemo.tsx
=> fix(Input group): Removed variant prop from input group text

packages/react-core/package.json, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
=> chore(deps): bump core alpha to 64

packages/react-core/src/deprecated/components/Select/Select.tsx, packages/react-core/src/deprecated/components/Select/__tests__/__snapshots__/Select.test.tsx.snap
=> fix(Select deprecated): updated markup for correct styling

packages/react-core/src/components/Alert/examples/alert.css
=> fix(Alert): update examples className to v5 so that custom spacing is applied

packages/react-core/src/components/Alert/AlertGroup.tsx
=> Fix(AlertGroup) - dont pass appendTo to ul tag

packages/react-core/src/components/Pagination/PaginationOptionsMenu.tsx, packages/react-core/src/components/Pagination/__tests__/Generated/PaginationOptionsMenu.test.tsx, packages/react-core/src/components/Pagination/__tests__/Generated/__snapshots__/PaginationOptionsMenu.test.tsx.snap
**What**: Closes #9200
to test: https://patternfly-react-pr-9203.surge.sh/components/pagination#indeterminate
=> fix(Pagination) - render toggleTemplate custom component

packages/react-core/package.json, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
=> chore(deps): Bumped to latest core and docs framework deps

packages/react-table/src/components/Table/Tr.tsx
=> fix(Table): removed invalid output element

packages/react-core/package.json, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
=> chore(deps): Bumped the latest version of core.

.github/release.sh, packages/eslint-plugin-patternfly-react/package.json, packages/react-charts/package.json, packages/react-code-editor/package.json, packages/react-core/package.json, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-integration/demo-app-ts/package.json, packages/react-integration/package.json, packages/react-styles/package.json, packages/react-table/package.json, packages/react-tokens/package.json, yarn.lock
=> fix(release): dryrun publishing prereleases

packages/react-core/package.json, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-integration/demo-app-ts/package.json, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
=> fix(versions): bump core and fix demo-app versions

packages/react-core/package.json, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
=> "chore(deps): Updated core dep to prerelease 8"

packages/react-core/package.json, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
=> chore(deps): bumped to core pre release 10

packages/react-core/src/components/ClipboardCopy/__tests__/Generated/__snapshots__/ClipboardCopy.test.tsx.snap, packages/react-core/src/components/DatePicker/__tests__/__snapshots__/DatePicker.test.tsx.snap, packages/react-core/src/components/FileUpload/__tests__/__snapshots__/FileUpload.test.tsx.snap, packages/react-core/src/components/FileUpload/__tests__/__snapshots__/FileUploadField.test.tsx.snap, packages/react-core/src/components/FormControl/FormControlIcon.tsx, packages/react-core/src/components/FormSelect/FormSelect.tsx, packages/react-core/src/components/FormSelect/__tests__/__snapshots__/FormSelect.test.tsx.snap, packages/react-core/src/components/LoginPage/__tests__/__snapshots__/LoginForm.test.tsx.snap, packages/react-core/src/components/NumberInput/__tests__/__snapshots__/NumberInput.test.tsx.snap, packages/react-core/src/components/Pagination/__tests__/Generated/__snapshots__/Navigation.test.tsx.snap, packages/react-core/src/components/Pagination/__tests__/__snapshots__/Pagination.test.tsx.snap, packages/react-core/src/components/SearchInput/__tests__/__snapshots__/SearchInput.test.tsx.snap, packages/react-core/src/components/Slider/_tests_/__snapshots__/Slider.test.tsx.snap, packages/react-core/src/components/TextArea/TextArea.tsx, packages/react-core/src/components/TextArea/__tests__/__snapshots__/TextArea.test.tsx.snap, packages/react-core/src/components/TextInput/TextInput.tsx, packages/react-core/src/components/TextInput/__tests__/__snapshots__/TextInput.test.tsx.snap, packages/react-core/src/deprecated/components/Select/__tests__/__snapshots__/Select.test.tsx.snap, packages/react-table/src/deprecated/components/Table/__tests__/__snapshots__/Table.test.tsx.snap
=> fix(TextInput,TextArea, FormSelect): changed form control div to a span

packages/react-docs/package.json, yarn.lock
=> chore(deps): bump docs-framework

packages/react-tokens/package.json, packages/react-tokens/single-packages.config.json, packages/transformer-dynamic-imports/index.ts
Fixes issues with /esm/ imports to react tokens package
@wise-king-sullyman this should replace the two Drafs you have opened
cc @evwilkin @wise-king-sullyman
=> Add transformation fallback

packages/react-tokens/package.json, packages/react-tokens/single-packages.config.json, packages/transformer-dynamic-imports/index.ts
Reverts patternfly/patternfly-react#9353
=> Revert "Add transformation fallback"

packages/react-docs/package.json, yarn.lock
=> chore(deps): bump docs framework

packages/react-core/src/demos/Toolbar.md, packages/react-core/src/demos/examples/DashboardWrapper.js
=> fix(Toolbar): resolved typeerror on full page demo

packages/react-core/package.json, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
=> chore(deps): bump to latest chore version

packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx
=> fix(CodeEditor): prevent clicks in textarea from opening fileupload

packages/react-core/src/components/Select/SelectToggle.tsx
=> fix(SelectToggle): corrected removeEventListener on unmount for v4

packages/react-core/src/components/MultipleFileUpload/MultipleFileUpload.tsx
**What**: Closes #9402
Convenience link: https://patternfly-react-pr-9403.surge.sh/components/file-upload/multiple-file-upload
=> fix(MultipleFileUpload): Prevent file upload from opening incorrectly

packages/react-core/src/deprecated/components/Select/SelectToggle.tsx
=> fix(SelectToggle): corrected removeEventListener on unmount for v5

.github/promote.sh, packages/eslint-plugin-patternfly-react/CHANGELOG.md, packages/eslint-plugin-patternfly-react/package.json, packages/react-charts/CHANGELOG.md, packages/react-charts/package.json, packages/react-code-editor/CHANGELOG.md, packages/react-code-editor/package.json, packages/react-core/CHANGELOG.md, packages/react-core/package.json, packages/react-docs/CHANGELOG.md, packages/react-docs/package.json, packages/react-icons/CHANGELOG.md, packages/react-icons/package.json, packages/react-styles/CHANGELOG.md, packages/react-styles/package.json, packages/react-table/CHANGELOG.md, packages/react-table/package.json, packages/react-tokens/CHANGELOG.md, packages/react-tokens/package.json
=> Reset branch and prepare for 5.0.0 release successfully

packages/react-core/src/components/TextArea/examples/TextAreaValidated.tsx
=> fix(TextArea) validated example in docs

package.json, packages/eslint-plugin-patternfly-react/package.json, yarn.lock
Reverts patternfly/patternfly-react#9458
=> Revert "fix(deps): update dependency eslint-plugin-prettier to v5"

.github/ISSUE_TEMPLATE/devX_request.md
Closes https://github.com/patternfly/patternfly-react/issues/9301
=> chore: Update devX issue template

lerna.json
Attempts to resolve the error currently causing our prereleases to fail the release process, which seems to be related to lerna trying to publish the federated modules.
https://lerna.js.org/docs/api-reference/configuration#packages
=> chore(CI): added packages key to lerna config

packages/react-code-editor/src/components/CodeEditor/__test__/CodeEditor.test.tsx, packages/react-core/src/components/TimePicker/examples/TimePickerCustomDelimiter.tsx
Fixed lint errors being caught by CI and preventing release
=> chore(CI): fixed lint errors

packages/react-core/src/components/Button/Button.tsx
=> fix(Button): Fixed incorrect styles when plain variant and isLoading is false

.github/renovate.json
=> chore(deps): update renovate to group and automerge PRs

.github/release.sh
=> fix(release): Update release dry run

packages/react-core/src/components/JumpLinks/JumpLinks.tsx
**What**: Closes #7561 
**Additional issues**: Current solution is just a workaround, the reason of the bug is still unknown.
[Thread in scrum channel](https://patternfly.slack.com/archives/C03LQ25DDLN/p1689003959647329)
=> fix(JumpLinks) jump links dont work after skipToContent

packages/react-core/src/deprecated/components/Select/Select.tsx, packages/react-core/src/deprecated/components/Select/__tests__/__snapshots__/Select.test.tsx.snap
fixes https://github.com/patternfly/patternfly-react/issues/9538
=> fix(select): fixed deprecated menu filter styles

packages/react-docs/package.json, packages/react-docs/patternfly-docs/patternfly-docs.config.js, yarn.lock
fixes https://github.com/patternfly/patternfly-react/issues/9581
I bumped the documentation-framework package manually. Not sure if that's the best way to do it? Looks like this is the bump PR but it's failing https://github.com/patternfly/patternfly-react/pull/9573
=> chore: add rtl switcher, bump docs-framework package

packages/react-core/src/components/BackToTop/BackToTop.tsx, packages/react-core/src/components/BackToTop/__tests__/BackToTop.test.tsx, packages/react-core/src/components/BackToTop/__tests__/__snapshots__/BackToTop.test.tsx.snap, packages/react-core/src/components/Button/Button.tsx, packages/react-core/src/components/Button/examples/ButtonVariations.tsx, packages/react-core/src/components/SearchInput/examples/SearchInputAdvanced.tsx, packages/react-core/src/demos/CardDemos.md
fixes https://github.com/patternfly/patternfly-react/issues/9589
=> fix(button): added logical start/end vals to iconPosition

packages/react-core/src/components/Drawer/Drawer.tsx, packages/react-core/src/components/Drawer/DrawerPanelContent.tsx, packages/react-core/src/components/Drawer/examples/Drawer.md, packages/react-core/src/components/Drawer/examples/DrawerInlinePanelEnd.tsx, packages/react-core/src/components/Drawer/examples/DrawerInlinePanelStart.tsx, packages/react-core/src/components/Drawer/examples/DrawerPanelEnd.tsx, packages/react-core/src/components/Drawer/examples/DrawerPanelStart.tsx, packages/react-core/src/components/Drawer/examples/DrawerResizableAtEnd.tsx, packages/react-core/src/components/Drawer/examples/DrawerResizableAtStart.tsx
=> feat(Drawer): Added start and end to position props, updated resizing to work with RTL

packages/react-core/src/components/Modal/ModalContent.tsx, packages/react-integration/cypress/integration/modal.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/ModalDemo/ModalDemo.tsx
=> fix(Modal): Prevent duplicate ids within Modal

packages/react-core/src/components/Dropdown/Dropdown.tsx
=> fix(Dropdown): Add appendTo to dropdownPopperProps interface

packages/react-core/src/demos/PrimaryDetail.md
=> fix(PrimaryDetail): remove primary detail card view require statement

package.json, yarn.lock
This reverts commit 03985a2c22f4e38166b09ab75ca2232672ea9045.
=> Revert "chore(deps): update dependency ts-patch to v3 (#9271)"

packages/react-core/src/components/BackToTop/BackToTop.tsx
=> fix(BackToTop): fix null exception on load

packages/react-charts/README.md, packages/react-icons/README.md, packages/react-table/README.md, packages/react-tokens/README.md
**What**: Closes https://github.com/patternfly/patternfly-react/issues/9725
=> chore: update references to new workspace URL

packages/react-core/src/components/Wizard/examples/Wizard.md
=> docs(Wizard): remove "next" references

packages/react-core/src/components/Wizard/Wizard.tsx, packages/react-core/src/components/Wizard/WizardNavInternal.tsx, packages/react-core/src/components/Wizard/__tests__/Wizard.test.tsx
=> feat(Wizard): Add prop for nav aria label

packages/react-core/src/components/Menu/Menu.tsx
=> fix(Menu): allow caret to move in input under Menu on left/right arrow press

packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx
**What**: Closes #9682 
This demo shows the issue: https://codesandbox.io/s/stupefied-microservice-vj4y7c
=> fix(ExpandableSection): show toggle button in truncate variant if content changes dynamically

packages/react-core/src/components/TreeView/TreeViewListItem.tsx, packages/react-core/src/components/TreeView/__tests__/__snapshots__/TreeView.test.tsx.snap
=> v4 - add button type to TreeView

packages/react-core/src/components/Nav/examples/NavFlyout.tsx, packages/react-core/src/components/Nav/examples/NavHorizontalSubNav.tsx, packages/react-core/src/components/Nav/examples/NavLegacyTertiary.tsx, packages/react-core/src/components/Pagination/examples/PaginationSticky.tsx, packages/react-core/src/demos/Banner.md, packages/react-core/src/demos/examples/BackToTop/BackToTopNameDemo.tsx, packages/react-core/src/demos/examples/Masthead/MastheadWithUtilitiesAndUserDropdownMenu.tsx, packages/react-core/src/demos/examples/Nav/NavDefault.tsx, packages/react-core/src/demos/examples/Nav/NavExpandable.tsx, packages/react-core/src/demos/examples/Nav/NavHorizontal.tsx, packages/react-core/src/demos/examples/Nav/NavHorizontalWithSubnav.tsx, packages/react-core/src/demos/examples/Nav/NavManual.tsx, packages/react-core/src/demos/examples/Nav/NavWithSubnav.tsx, packages/react-core/src/demos/examples/Nav/deprecated/NavLight.tsx, packages/react-core/src/demos/examples/Nav/deprecated/NavTertiary.tsx, packages/react-core/src/demos/examples/Page/PageStickySectionBreadcrumb.tsx, packages/react-core/src/demos/examples/Page/PageStickySectionGroup.tsx, packages/react-core/src/demos/examples/Page/PageStickySectionGroupAlternate.tsx, packages/react-core/src/demos/examples/Wizard/InModal.tsx, packages/react-integration/demo-app-ts/src/components/demos/BackToTopDemo/BackToTopDemo.tsx
=> chore(misc): clean up instances of Array.apply

packages/react-core/src/components/BackgroundImage/__tests__/BackgroundImage.test.tsx, packages/react-core/src/components/DataList/DataList.tsx, packages/react-core/src/components/DataList/DataListAction.tsx, packages/react-core/src/components/DataList/__tests__/DataList.test.tsx, packages/react-core/src/components/DataList/__tests__/DataListAction.test.tsx, packages/react-core/src/components/DataList/__tests__/DataListCell.test.tsx, packages/react-core/src/components/DataList/__tests__/DataListCheck.test.tsx, packages/react-core/src/components/DataList/__tests__/DataListContent.test.tsx, packages/react-core/src/components/DataList/__tests__/DataListItem.test.tsx, packages/react-core/src/components/DataList/__tests__/DataListItemCells.test.tsx, packages/react-core/src/components/DataList/__tests__/DataListItemRow.test.tsx, packages/react-core/src/components/DataList/__tests__/DataListToggle.test.tsx, packages/react-core/src/components/DataList/__tests__/Generated/__snapshots__/DataListAction.test.tsx.snap, packages/react-core/src/components/DataList/__tests__/__snapshots__/DataList.test.tsx.snap, packages/react-core/src/components/DataList/__tests__/__snapshots__/DataListAction.test.tsx.snap, packages/react-core/src/components/DataList/__tests__/__snapshots__/DataListCell.test.tsx.snap, packages/react-core/src/components/DataList/__tests__/__snapshots__/DataListContent.test.tsx.snap, packages/react-core/src/components/DataList/__tests__/__snapshots__/DataListItem.test.tsx.snap, packages/react-core/src/components/DataList/__tests__/__snapshots__/DataListItemCells.test.tsx.snap, packages/react-core/src/components/DataList/__tests__/__snapshots__/DataListItemRow.test.tsx.snap, packages/react-core/src/components/DataList/__tests__/__snapshots__/DataListToggle.test.tsx.snap, packages/react-core/src/components/DataList/examples/DataListCheckboxes.tsx, packages/react-core/src/components/DataList/examples/DataListMixedExpandable.tsx
=> chore(DataList): update tests

packages/react-core/src/demos/examples/AlertGroup/AlertGroupToastWithNotificationDrawer.tsx
=> fix(AlertGroupDemo): crashed when adding default alerts

packages/react-core/src/components/Button/examples/ButtonVariations.tsx
Closes: https://github.com/patternfly/patternfly-react/issues/9870
=> Chore: add primary button with icon to button docs

packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx, packages/react-core/src/components/ExpandableSection/ExpandableSectionToggle.tsx, packages/react-core/src/components/ExpandableSection/examples/ExpandableSection.md, packages/react-core/src/components/ExpandableSection/examples/ExpandableSectionIndented.tsx
**What**: Closes #9850
No other updates needed to consume Penta tokens
=> chore(ExpandableSection): updated indented example for Penta disclosure variation

packages/react-core/src/components/Panel/Panel.tsx, packages/react-core/src/components/Panel/__tests__/Panel.test.tsx, packages/react-core/src/components/Panel/examples/Panel.md
=> feat(Panel): consumed Penta updates

packages/react-core/src/components/Pagination/Pagination.tsx, packages/react-core/src/components/Pagination/PaginationOptionsMenu.tsx, packages/react-core/src/components/Pagination/__tests__/Generated/__snapshots__/PaginationOptionsMenu.test.tsx.snap, packages/react-core/src/components/Pagination/__tests__/Pagination.test.tsx, packages/react-core/src/components/Pagination/__tests__/PaginationOptionsMenu.test.tsx, packages/react-core/src/components/Pagination/__tests__/__snapshots__/Pagination.test.tsx.snap
**What**: Closes #9878 
[Pagination preview](https://patternfly-react-pr-9971.surge.sh/components/pagination)
~@mcoker based on your [page insets comment in the Core PR](https://github.com/patternfly/patternfly/pull/6089#discussion_r1416225306) I removed the prop that added the pf-m-page-inset class. Let me know if this should be reverted.~ EDIT: adding back per discussion during Penta happy hour
=> feat(Pagination): applied Penta updates

packages/react-docs/package.json, yarn.lock
**What**: Closes https://github.com/patternfly/patternfly-react/issues/9972
=> chore: bump docs-framework to v6 alpha

packages/react-core/src/components/Sidebar/Sidebar.tsx, packages/react-core/src/components/Sidebar/SidebarContent.tsx, packages/react-core/src/components/Sidebar/SidebarPanel.tsx, packages/react-core/src/components/Sidebar/__tests__/SidebarContent.test.tsx, packages/react-core/src/components/Sidebar/__tests__/SidebarPanel.test.tsx
=> feat(Sidebar): consumed Penta updates

packages/eslint-plugin-patternfly-react/CHANGELOG.md, packages/eslint-plugin-patternfly-react/package.json, packages/react-charts/CHANGELOG.md, packages/react-charts/package.json, packages/react-code-editor/CHANGELOG.md, packages/react-code-editor/package.json, packages/react-core/CHANGELOG.md, packages/react-core/package.json, packages/react-docs/CHANGELOG.md, packages/react-docs/package.json, packages/react-drag-drop/CHANGELOG.md, packages/react-drag-drop/package.json, packages/react-icons/CHANGELOG.md, packages/react-icons/package.json, packages/react-styles/CHANGELOG.md, packages/react-styles/package.json, packages/react-table/CHANGELOG.md, packages/react-table/package.json, packages/react-tokens/CHANGELOG.md, packages/react-tokens/package.json
=> Revert release attempt

packages/react-integration/demo-app-ts/package.json, yarn.lock
=> fix: demo-app version bump issue

packages/react-core/src/components/Tile/examples/Tile.css, packages/react-core/src/components/Tile/examples/Tile.md
**What**: Closes #9992
Convenience link: https://patternfly-react-pr-10040.surge.sh/components/tile
=> chore(Tile): add spacing between tile examples/demos

packages/react-docs/package.json, yarn.lock
=> feat(workspace): bump docs framework to support v6 classnames

packages/react-core/src/components/TreeView/TreeViewListItem.tsx, packages/react-core/src/components/TreeView/__tests__/TreeViewListItem.test.tsx
=> feat(TreeView): removed selectable modifier for penta

packages/react-core/package.json, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
=> chore(deps): bump to latest core

packages/react-core/src/components/Menu/Menu.tsx
=> (fix): Menu fix cherry pick for patch

packages/react-table/src/demos/Table.md, packages/react-table/src/index.ts
=> fix(Table): remove demos from package exports

packages/react-table/src/demos/Table.md, packages/react-table/src/index.ts
**What**: Closes #https://github.com/patternfly/patternfly-react/issues/10166
=> fix(Table): remove demos from package exports (#10165)

.github/workflows/release.yml
=> chore(CI): reenable release dist caching

packages/react-core/package.json, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
=> chore(deps): bump to latest core versions

packages/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx
=> fix(ClipboardCopy): warn when clipboard API is unavailable

packages/react-core/src/components/Select/examples/SelectMultiTypeaheadCheckbox.tsx
=> bug(Select): Remove checkbox from no results found option

packages/react-table/src/demos/examples/TableSortableResponsive.tsx
=> fix(TableSortableResponsive demo): end page number

packages/react-core/src/demos/Banner.md, packages/react-core/src/demos/Tabs.md
=> fix(misc): demos not working due to variables not defined

packages/react-core/src/components/Dropdown/Dropdown.tsx
=> feat(Dropdown): Added support for setting height for dropdown

packages/react-core/src/components/MenuToggle/MenuToggle.tsx, packages/react-core/src/components/MenuToggle/__tests__/MenuToggle.test.tsx, packages/react-core/src/components/MenuToggle/examples/MenuToggle.md, packages/react-core/src/components/MenuToggle/examples/MenuToggleStatus.tsx, packages/react-core/src/components/Select/examples/Select.md, packages/react-core/src/components/Select/examples/SelectValidated.tsx
**What**: Closes #10025
* Adds `status` and `statusIcon` to `MenuToggle`
* Adds MenuToggle and Select example for new prop
=> feat(MenuToggle/Select): add status

packages/react-core/src/components/TextArea/TextArea.tsx
=> fix(TextArea): remove invalid `onFocus` and `onBlur` props

packages/react-table/src/components/Table/examples/TableDraggable.tsx, packages/react-table/src/components/Table/examples/TableSelectable.tsx, packages/react-table/src/demos/Table.md, packages/react-table/src/demos/examples/TableExpandCollapseAll.tsx
**What**: Closes #10206
A few additional followups for https://github.com/patternfly/patternfly-react/pull/10152
=> chore(Table): added more arialabeling for empty/nontext Table headers

packages/react-core/package.json, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
=> chore(deps): Updated core alpah version

packages/react-table/src/components/Table/examples/TableStickyColumnsAndHeader.tsx
=> fix(Table): fix sticky header and column example

packages/react-core/src/helpers/GenerateId/GenerateId.ts
=> fix(GenerateId): revert default behavior change

packages/react-core/package.json, packages/react-core/src/demos/CustomMenus/examples/ComposableDateSelect.tsx, packages/react-core/src/demos/CustomMenus/examples/DateSelectDemo.tsx, packages/react-core/src/demos/examples/Card/CardEventsView.tsx, packages/react-core/src/demos/examples/Card/CardLogView.tsx, packages/react-core/src/demos/examples/Card/CardTrendDemo1.tsx, packages/react-core/src/demos/examples/Card/CardTrendDemo2.tsx, packages/react-core/src/demos/examples/Card/CardUtilizationDemo3.tsx, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-styles/package.json, packages/react-table/src/components/Table/examples/TableNestedHeaders.tsx, packages/react-table/src/components/Table/examples/TableNestedStickyHeader.tsx, packages/react-tokens/package.json, yarn.lock
**What**: Closes #10231 
Bumps to the latest core alphas and consumes the Penta utilities changes.  Updates were made to som demos due to changes in Utilities.
=> chore(deps): bump core alpha versions and update for Utilities 

packages/react-integration/demo-app-ts/package.json, yarn.lock
=> chore(release): Fixed issue after releaseing 5.3.0 with seeding 5.4.0

packages/react-core/README.md
=> fix(build): whitespace change to trigger release

scripts/build-single-packages.js, scripts/parse-dynamic-modules.js
=> feat(dist): Generate dist/dynamic-modules.json for relevant packages

packages/react-docs/package.json, yarn.lock
=> fix(docs): Add templates to react-docs

.github/release.sh, packages/react-core/README.md
=> fix(publish): Updated code so that it would publish release.

packages/react-core/package.json, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-integration/demo-app-ts/package.json, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
chore(patch 5.3.2): Updated to latest version of core with page pagination fix.
=> chore(patch 5.3.2): Core pagination fix.

.github/workflows/stale.yml
=> chore(ci): fix stale action commenting "false" before closing issues/PRs

packages/react-core/src/components/Pagination/Pagination.tsx, packages/react-core/src/components/Pagination/PaginationOptionsMenu.tsx, packages/react-core/src/components/Pagination/__tests__/Generated/__snapshots__/PaginationOptionsMenu.test.tsx.snap, packages/react-core/src/components/Pagination/__tests__/__snapshots__/Pagination.test.tsx.snap
**What**: Closes #9783
Note:  the wrapping issue is tracked in core https://github.com/patternfly/patternfly/issues/6582
=> "fix(Pagination): Fix bottom pagination layout"

packages/react-charts/src/components/Skeletons/examples/skeletons.md
Forgot to add a beta flag for the skeletons feature.
https://github.com/patternfly/patternfly-react/issues/10310
=> Chart skeletons - add beta flag

packages/react-core/src/components/Select/Select.tsx
=> fix(Select): set isScrollable internally

package.json, packages/react-charts/package.json, packages/react-code-editor/package.json, packages/react-core/package.json, packages/react-drag-drop/package.json, packages/react-icons/package.json, packages/react-integration/demo-app-ts/package.json, packages/react-integration/package.json, packages/react-styles/package.json, packages/react-table/package.json, packages/react-templates/package.json, scripts/generators/package/package.json.hbs, yarn.lock
Upgrades TypeScript and related dependencies to their respective latest versions.
Closes #10156
=> chore: upgrade TypeScript to version 5

packages/react-core/src/components/Toolbar/ToolbarGroup.tsx, packages/react-core/src/components/Toolbar/ToolbarItem.tsx, packages/react-core/src/components/Toolbar/ToolbarToggleGroup.tsx, packages/react-core/src/components/Toolbar/examples/ToolbarStacked.tsx, packages/react-core/src/demos/CardView/examples/CardView.tsx, packages/react-core/src/demos/DashboardHeader.tsx, packages/react-core/src/demos/DataList/examples/DataListBasic.tsx, packages/react-core/src/demos/NotificationDrawer/examples/NotificationDrawerBasic.tsx, packages/react-core/src/demos/NotificationDrawer/examples/NotificationDrawerGrouped.tsx, packages/react-core/src/demos/RTL/examples/PaginatedTable.jsx, packages/react-core/src/demos/RTL/examples/PaginatedTable.tsx, packages/react-core/src/demos/examples/Masthead/MastheadWithUtilitiesAndUserDropdownMenu.tsx, packages/react-core/src/demos/examples/Nav/NavFlyout.tsx, packages/react-core/src/demos/examples/Nav/NavHorizontal.tsx, packages/react-core/src/demos/examples/Nav/NavHorizontalWithSubnav.tsx, packages/react-core/src/demos/examples/Nav/NavManual.tsx, packages/react-core/src/demos/examples/Page/PageStickySectionBreadcrumb.tsx, packages/react-core/src/demos/examples/Page/PageStickySectionGroup.tsx, packages/react-core/src/demos/examples/Page/PageStickySectionGroupAlternate.tsx, packages/react-core/src/demos/examples/PrimaryDetail/PrimaryDetailCardView.tsx, packages/react-core/src/demos/examples/Toolbar/ConsoleLogViewerToolbar.tsx, packages/react-integration/demo-app-ts/src/components/demos/MastheadDemo/MastheadDemo.tsx, packages/react-table/src/demos/DashboardHeader.tsx
**What**: Closes https://github.com/patternfly/patternfly-react/issues/10343
I opened a code mod issue as well: https://github.com/patternfly/pf-codemods/issues/639
=> fix(Toolbar): update align prop type to alignEnd, alignStart

README.md, packages/react-docs/patternfly-a11y.config.js
=> fix(build): Test ci

packages/react-table/src/demos/examples/TableColumnManagement.tsx, packages/react-table/src/demos/examples/TableColumnManagementWithDraggable.tsx
=> docs(Table): update column management demo to use link button for Cancel action in modal

packages/react-core/src/components/SearchInput/__tests__/__snapshots__/SearchInput.test.tsx.snap
**What**: Closes https://github.com/patternfly/patternfly-react/issues/10604
=> fix: update snapshots to fix CI

package.json, packages/react-core/src/components/Modal/ModalBoxTitle.tsx, packages/react-core/src/components/Modal/ModalHeader.tsx, packages/react-core/src/components/Modal/__tests__/ModalBoxTitle.test.tsx, packages/react-core/src/components/Modal/__tests__/__snapshots__/ModalBoxTitle.test.tsx.snap
=> feat(Modal): Added status variant styling to title V6

.github/renovate.json, package.json, yarn.lock
**What**: Closes #10616
Temporarily run renovate on v6 branch
=> "chore(config): Update renovate config to run on v6 branch"

packages/react-table/src/index.ts
=> fix(build): stop including demos from react-table in build

packages/react-core/src/components/ToggleGroup/examples/ToggleGroup.md
=> docs(toggle-group): Add content about iconPosition.

.github/workflows/stale.yml, .github/workflows/triage-stale-issues.yml
=> chore(CI): Fix GH action to set stale issues status to needs triage

packages/react-core/src/components/Wizard/WizardBody.tsx, packages/react-core/src/components/Wizard/WizardFooter.tsx, packages/react-core/src/components/Wizard/WizardHeader.tsx, packages/react-core/src/components/Wizard/WizardNav.tsx, packages/react-core/src/components/Wizard/WizardNavItem.tsx, packages/react-core/src/components/Wizard/__tests__/WizardBody.test.tsx, packages/react-core/src/components/Wizard/__tests__/WizardFooter.test.tsx, packages/react-core/src/components/Wizard/__tests__/WizardHeader.test.tsx, packages/react-core/src/components/Wizard/__tests__/WizardNav.test.tsx, packages/react-core/src/components/Wizard/__tests__/WizardNavItem.test.tsx
Updating main with the changes from #10670
=> fix(Wizard): add className and spread props when possible

packages/eslint-plugin-patternfly-react/lib/rules/import-default-name.js, packages/eslint-plugin-patternfly-react/lib/rules/no-anonymous-functions.js
**What**: Closes #10282
Updates PF's eslint plugin rules for eslint v9 compatibility.
=> feat(eslint-plugin-patternfly-react): update rules for eslint v9

packages/react-table/src/components/Table/Tr.tsx, packages/react-table/src/components/Table/examples/TableCompoundExpandable.tsx
**What**: Closes #10321 for V6
Additional issues:
=> fix(Table): compound expansion table row styles (V6)

packages/react-core/src/components/DragDrop/examples/DragDropMultipleLists.tsx
`flewGrow` must have a `number` type. This is causing a build error on org
=> fix(DragDrop): fix flexgrow type

packages/react-core/src/components/Wizard/Wizard.tsx, packages/react-core/src/components/Wizard/WizardContext.tsx
**What**: V6 followup for #10779
=> V6 - fix(Wizard): only update new steps when step count changes

packages/react-core/src/components/Slider/examples/Slider.md, packages/react-table/src/demos/Table.md
=> docs(Text): Replace Text imports in md files

packages/react-core/src/components/Label/Label.tsx, packages/react-core/src/components/Label/__tests__/Label.test.tsx, packages/react-core/src/components/Label/__tests__/__snapshots__/Label.test.tsx.snap, packages/react-core/src/components/Label/__tests__/__snapshots__/LabelGroup.test.tsx.snap
=> fix(Label): Added button type

packages/react-core/src/components/Dropdown/Dropdown.tsx, packages/react-core/src/components/SearchInput/__tests__/__snapshots__/SearchInput.test.tsx.snap, packages/react-core/src/components/Select/Select.tsx, packages/react-core/src/deprecated/components/Dropdown/DropdownMenu.tsx, packages/react-core/src/deprecated/components/Dropdown/InternalDropdownItem.tsx, packages/react-core/src/helpers/Popper/Popper.tsx, packages/react-integration/cypress/integration/dropdowndeprecated.spec.ts
**What**: Reverts https://github.com/patternfly/patternfly-react/pull/10797 
=> fix(Popper): reverted display update

packages/react-core/src/demos/examples/BackToTop/BackToTopNameDemo.tsx
=> chore(BackToTop): updated broken demo

packages/react-core/src/components/TimePicker/__tests__/TimePicker.test.tsx
=> chore(TimePicker): re-enabled unit test

packages/react-core/src/demos/CardDemos.md, packages/react-core/src/demos/examples/Card/CardUtilizationDemo3.tsx
**What**: Closes #10582
Updates the demo to use the proper red-orange token as the red tokens were removed.
=> fix(Card demo): use proper token

scripts/promote.sh
Updated promote script to support flags, extensions, and ability to change prerelease tag.
=> fix(release): Updated promote script with new features.

packages/react-core/src/components/Page/Page.tsx, packages/react-core/src/demos/Banner.md, packages/react-core/src/demos/DashboardWrapper.tsx
=> chore(Banner): updated placement in sticky demo

packages/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx, packages/react-core/src/components/ClipboardCopy/ClipboardCopyButton.tsx, packages/react-core/src/components/ClipboardCopy/__tests__/ClipboardCopyButton.test.tsx, packages/react-core/src/components/ClipboardCopy/examples/ClipboardCopyInlineCompactWithAdditionalAction.tsx
=> fix(clipboard copy): Remove button padding for inline-compact variant

packages/react-core/src/demos/examples/Tabs/ModalTabs.tsx, packages/react-core/src/demos/examples/Tabs/NestedTabs.tsx, packages/react-core/src/demos/examples/Tabs/NestedUnindentedTabs.tsx
**What**: Closes #10863
Updates Tabs demos to new Modal/Card, and removes some Tabs props that are no longer used.
=> docs(Tabs): update demos

packages/react-charts/src/components/Chart/Chart.tsx, packages/react-charts/src/components/ChartAxis/ChartAxis.tsx, packages/react-charts/src/components/ChartBar/examples/ChartBar.md, packages/react-charts/src/components/ChartPie/examples/ChartPie.md
- Created a gnatt-like [example](https://patternfly-react-pr-10845.surge.sh/charts/bar-chart#alerts-timeline), demonstrating an alert timeline using horizontal bar charts
- Updated a pie chart [example](https://patternfly-react-pr-10845.surge.sh/charts/pie-chart#custom-color-scale) to demonstrate how to apply custom styles
- Also fixed an issue with undesired space between tick labels and the bottom positioned legend
Closes https://github.com/patternfly/patternfly-react/issues/10844
=> Charts - Port examples to v6

packages/react-core/src/components/Slider/Slider.tsx
=> fix(slider): Add tabular number font styling to tooltips

packages/react-core/src/components/TreeView/examples/TreeViewWithActionItems.tsx
=> fix(tree view): Fix with action items example so menu is closed by default

packages/react-core/src/components/Dropdown/Dropdown.tsx, packages/react-core/src/components/Menu/MenuContainer.tsx, packages/react-core/src/components/Select/Select.tsx, packages/react-integration/cypress/integration/slider.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/SliderDemo/SliderDemo.tsx
=> chore(v6): brought in v5 updates

packages/react-table/src/components/Table/HeaderCellInfoWrapper.tsx
=> fix(Table): Add hasNoPadding prop to header info button

packages/react-core/src/components/Page/Page.tsx
=> fix(Page): Remove drawer content body wrapper from notification drawer

packages/react-core/src/components/ExpandableSection/__tests__/__snapshots__/ExpandableSection.test.tsx.snap, packages/react-core/src/helpers/resizeObserver.tsx
**What**: Closes #10897 
cc @dlabaj we will want to promote a patch release for this
=> fix(nav):  Reverts PR #10644 that caused regression

package.json, yarn.lock
Reverts patternfly/patternfly-react#11084
=> Revert "chore(deps): update dependency rollup to ^4.24.0 (main)"

packages/react-core/package.json, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
=> chore(deps): Update core dependencies on v5 to latest

packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx
What: Closes https://github.com/patternfly/patternfly-react/issues/11033
Related to https://github.com/patternfly/patternfly-react/pull/11034
=> [V5] CodeEditor loading property considered by the Editor

packages/eslint-plugin-patternfly-react/package.json
Commit 995479af173781ee5971e10bf40adc194ac3f596 moved the location of the patternfly-react `README.md` file. This PR adjusts sources to changes.
=> fix: update patternfly-react home page

packages/react-docs/package.json, packages/react-docs/patternfly-a11y.config.js, yarn.lock
**What**: Closes https://github.com/patternfly/patternfly-react/issues/11165
=> fix: bump patternfly-a11y dependency

packages/react-core/src/components/Checkbox/examples/CheckboxReversed.tsx
=> fix(CheckboxReversed example): fix prop

README.md
=> docs: fix broken GitHub links in README

.github/renovate.json
**What**: Closes #11262 
Follow up to PR https://github.com/patternfly/patternfly-react/pull/11066
=> (chore): Update renovate config to not bump v5 branch

.github/workflows/stale.yml
=> chore(actions): Updated github stalebot actions to not close stale issues

packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx, packages/react-code-editor/src/components/CodeEditor/CodeEditorControl.tsx, packages/react-docs/patternfly-docs/pages/icons.js, packages/react-docs/patternfly-docs/pages/index.js, packages/react-drag-drop/src/next/components/DragDrop/DragDropContainer.tsx, packages/react-drag-drop/src/next/components/DragDrop/DraggableDataListItem.tsx, packages/react-integration/demo-app-ts/src/App.tsx, packages/react-table/src/components/Table/Table.tsx, packages/react-table/src/deprecated/components/Table/Table.tsx, packages/react-templates/src/components/Select/CheckboxSelect.tsx, packages/react-templates/src/components/Select/MultiTypeaheadSelect.tsx, packages/react-templates/src/components/Select/TypeaheadSelect.tsx, packages/react-templates/src/components/Select/__tests__/__snapshots__/CheckboxSelectSnapshots.test.tsx.snap
=> refactor(misc): change imports from '@patternfly/react-core' to direct imports (V5)

packages/react-core/src/demos/Skeleton.md, packages/react-core/src/demos/examples/Skeleton/SkeletonCard.tsx
**What**: Closes https://github.com/patternfly/patternfly-react/issues/7214
=> Chore(Skeleton): Adding demo to match core

packages/react-core/src/components/FileUpload/__tests__/__snapshots__/FileUpload.test.tsx.snap, packages/react-core/src/components/FileUpload/__tests__/__snapshots__/FileUploadField.test.tsx.snap, packages/react-core/src/components/TextArea/TextArea.tsx, packages/react-core/src/components/TextArea/__tests__/TextArea.test.tsx, packages/react-core/src/components/TextArea/__tests__/__snapshots__/TextArea.test.tsx.snap
=> fix(TextArea): added missing modifier class

packages/react-core/package.json, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
Update @patternfly/patternfly dependency to v6.2.0-prerelease.4
https://github.com/patternfly/patternfly-react/issues/11526
=> Update @patternfly/patternfly dependency

packages/react-core/src/demos/PasswordGenerator.md, packages/react-core/src/demos/PasswordStrength.md, packages/react-core/src/demos/examples/PasswordStrength/PasswordStrengthDemo.tsx
=> chore(Password demos): moved to Patterns

packages/react-core/src/components/Icon/examples/BodyIconSizes.tsx, packages/react-core/src/components/Icon/examples/HeadingIconSizes.tsx, packages/react-core/src/components/Icon/examples/IconBasic.tsx, packages/react-core/src/components/Icon/examples/IconContentSizes.tsx, packages/react-core/src/components/Icon/examples/IconStatus.tsx, packages/react-core/src/components/Icon/examples/StandaloneIconSizes.tsx
=>  Chore(Icon): added whitespaces to examples

package.json, yarn.lock
=> chore(deps): update dependency concurrently to ^9.1.2

package.json, yarn.lock
=> chore(deps): update dependency rimraf to ^6.0.1

packages/react-core/package.json, yarn.lock
=> chore(deps): update dependency case-anything to ^3.1.0

packages/react-drag-drop/package.json, yarn.lock
=> chore(deps): update dependency @dnd-kit/modifiers to ^9.0.0 and @dnd-kit/sortable to ^10.0.0

package.json, yarn.lock
=> chore(deps): update dependency @octokit/rest to ^21.1.0

packages/react-integration/demo-app-ts/package.json, yarn.lock
=> chore(deps): update dependency vite to ^6.0.11

package.json, yarn.lock
=> chore(deps): updated dependency eslint-plugin-react-hooks to ^5.1.0

packages/react-tokens/README.md
=> chore(readme): fixed broken link for react tokens

packages/react-core/src/components/Card/CardHeader.tsx, packages/react-core/src/components/Card/__tests__/CardHeader.test.tsx
**What**: Closes https://github.com/patternfly/patternfly-react/issues/11500
**Additional issues**: https://github.com/patternfly/patternfly/pull/7396
=> feat(card): add hasHeaderWrap prop and test to support card header wrapping

.github/actions/setup-project/action.yml, CONTRIBUTING.md, package.json, yarn.lock
=> chore(deps): update node to v22

packages/react-core/src/components/Tabs/examples/Tabs.md
=> chore(Tabs): Add TabContentBody to the docs

packages/react-core/package.json, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
=> chore(Core): update core version to latest prerelease

.github/actions/setup-project/action.yml
Attempt to resolve issue causing intermittent CI failure
=> chore(CI): Remove build caching from project setup CI

packages/react-core/package.json, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
=> chore(Core): bumped core versions to 6.2prerelease28

scripts/promote.sh
Adds missing data view and chatbot too promote.sh.
=> fix: Updated promote.sh to include chatbot and data-view

packages/react-core/src/components/Skeleton/examples/SkeletonDefault.tsx, packages/react-core/src/components/Skeleton/examples/SkeletonPercentageHeight.tsx, packages/react-core/src/components/Skeleton/examples/SkeletonPercentageWidth.tsx, packages/react-core/src/components/Skeleton/examples/SkeletonShapes.tsx, packages/react-core/src/components/Skeleton/examples/SkeletonText.tsx, packages/react-core/src/demos/examples/Skeleton/SkeletonCard.tsx
=> chore(skeleton): updated screen reader text

packages/react-core/src/components/Dropdown/DropdownGroup.tsx, packages/react-core/src/components/Select/SelectGroup.tsx
=> chore(dropdown, select): update type definition for label

packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx
**What**: Closes #11649
**Additional issues**: split off from https://github.com/patternfly/patternfly-react/pull/11575 as I realize the changes can be made independently
=> refactor(CodeEditor): rewrite to become a functional component

packages/react-core/src/components/Alert/examples/Alert.md
=> chore(Alert): removed remove button from timeout example

packages/react-core/src/components/CodeBlock/examples/CodeBlockBasic.tsx, packages/react-core/src/components/CodeBlock/examples/CodeBlockExpandable.tsx
=> chore(code block): update aria labels in examples

eslint.config.mjs, package.json, yarn.lock
=> chore(deps): update dependency typescript-eslint to ^8.22.0

packages/react-docs/patternfly-docs/pages/index.js
**What**: Updates the splash screen of the workspace to remove the version number that is 5 years and two major versions out of date. It just seemed like time...
=> chore(workspace): update splash message

packages/react-core/src/demos/PasswordGenerator.md
=> fix(password generator): fixed syntax error in demo

packages/react-core/src/components/Form/FormGroupLabelHelp.tsx
=> chore(form): update use of help icon

packages/react-core/src/components/TreeView/TreeView.tsx, packages/react-core/src/components/TreeView/TreeViewListItem.tsx, packages/react-core/src/components/TreeView/TreeViewRoot.tsx, packages/react-core/src/components/TreeView/__tests__/TreeView.test.tsx, packages/react-core/src/components/TreeView/__tests__/TreeViewList.test.tsx, packages/react-core/src/components/TreeView/__tests__/TreeViewListItem.test.tsx, packages/react-core/src/components/TreeView/__tests__/__snapshots__/TreeView.test.tsx.snap, packages/react-core/src/components/TreeView/examples/TreeViewCompact.tsx, packages/react-core/src/components/TreeView/examples/TreeViewCompactNoBackground.tsx, packages/react-core/src/components/TreeView/examples/TreeViewGuides.tsx, packages/react-core/src/components/TreeView/examples/TreeViewMultiselectable.tsx, packages/react-core/src/components/TreeView/examples/TreeViewSelectionExpansion.tsx, packages/react-core/src/components/TreeView/examples/TreeViewSingleSelectable.tsx, packages/react-core/src/components/TreeView/examples/TreeViewWithActionItems.tsx, packages/react-core/src/components/TreeView/examples/TreeViewWithBadges.tsx, packages/react-core/src/components/TreeView/examples/TreeViewWithCheckboxes.tsx, packages/react-core/src/components/TreeView/examples/TreeViewWithCustomBadges.tsx, packages/react-core/src/components/TreeView/examples/TreeViewWithIconPerItem.tsx, packages/react-core/src/components/TreeView/examples/TreeViewWithIcons.tsx, packages/react-core/src/components/TreeView/examples/TreeViewWithMemoization.tsx, packages/react-core/src/components/TreeView/examples/TreeViewWithSearch.tsx
**What**: Closes #11841 
Accordion from https://github.com/patternfly/patternfly/pull/7539 and Nav from https://github.com/patternfly/patternfly/pull/7542 should also be set without any further React work, but can use confirmation on this
=> feat(TreeView): enabled opt-in animations

packages/react-core/package.json, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
Bumps to latest pre-release of core.
=> fix: Bumped to latest core version.

packages/react-core/package.json, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
Bumped core version to latest prerelease.
=> chore: bumped to latest core version for v6.3 - prerelease.37

packages/react-charts/src/victory/components/Sparkline/examples/SparklineBasic.tsx, packages/react-charts/src/victory/components/Sparkline/examples/SparklineGreen.tsx, packages/react-charts/src/victory/components/Sparkline/examples/sparkline.md
The following examples are converted:
- Basic
- Green
=> chore(sparkline): convert to typescript

packages/react-core/src/demos/examples/PrimaryDetail/PrimaryDetailCardView.tsx
=> fix(primary detail): added padding to correct toolbar alignment

packages/react-core/package.json, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
=> chore: Bumped core version.

packages/react-charts/package.json, packages/react-charts/src/echarts/components/Line/__tests__/__snapshots__/Line.test.tsx.snap, packages/react-charts/src/echarts/components/Sankey/__tests__/__snapshots__/Sankey.test.tsx.snap, packages/react-core/package.json, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
Bumps the versions of patternfly core and echarts.
=> fix: Bumped echarts and core.
