packages/react-core/src/components/SearchInput/examples/SearchInput.md, packages/react-core/src/components/SearchInput/examples/SearchInputAdvanced.tsx, packages/react-core/src/components/SearchInput/examples/SearchInputBasic.tsx, packages/react-core/src/components/SearchInput/examples/SearchInputFocusSearch.tsx, packages/react-core/src/components/SearchInput/examples/SearchInputWithNavigableOptions.tsx, packages/react-core/src/components/SearchInput/examples/SearchInputWithResultCount.tsx, packages/react-core/src/components/SearchInput/examples/SearchInputWithSubmitButton.tsx
=> chore(SearchInput): convert examples to TypeScript

packages/react-core/src/components/Label/Label.tsx, packages/react-core/src/components/LabelGroup/LabelGroup.tsx, packages/react-core/src/components/LabelGroup/examples/LabelGroup.md, packages/react-core/src/components/LabelGroup/examples/LabelGroupEditableAdd.tsx, packages/react-core/src/components/LabelGroup/examples/LabelGroupEditableAddDropdown.tsx, packages/react-core/src/components/LabelGroup/examples/LabelGroupEditableAddModal.tsx
**What**: Closes #7547
Should now make keyboard focus the editable label after finishing an edit. Also fixes some minor focus issues with the add label modal demo.
=> feat(Label): adjust editable keyboard behavior

packages/react-table/src/demos/Table.md, packages/react-table/src/demos/examples/ComposableTableStickyToolbar.tsx
**What**: Closes #7425
Adds a fullpage demo showing a sticky toolbar and table.
=> docs(Table): add sticky toolbar with table demo

packages/react-core/src/components/InputGroup/InputGroup.tsx, packages/react-core/src/components/InputGroup/__tests__/InputGroup.test.tsx, packages/react-core/src/components/NumberInput/NumberInput.tsx, packages/react-core/src/components/NumberInput/__tests__/NumberInput.test.tsx, packages/react-core/src/components/NumberInput/__tests__/__snapshots__/NumberInput.test.tsx.snap, packages/react-core/src/components/NumberInput/examples/NumberInput.md, packages/react-core/src/components/NumberInput/examples/WithStatus.tsx
**What**: Closes #7730 
used `validated` property based on TextInput using that property for such styling.
example: https://patternfly-react-pr-7806.surge.sh/components/number-input#with-status
=> feat(NumberInput): add status validate icons

packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx, packages/react-core/src/components/ExpandableSection/ExpandableSectionToggle.tsx, packages/react-core/src/components/ExpandableSection/__tests__/ExpandableSection.test.tsx, packages/react-core/src/components/ExpandableSection/examples/ExpandableSection.md, packages/react-core/src/components/ExpandableSection/examples/ExpandableSectionTruncateExpansion.tsx
**What**: Closes #7780 
[Expandable section truncate example](https://patternfly-react-pr-7852.surge.sh/components/expandable-section#truncate-expansion)
Also made slight edits to some prop descriptions.
=> feat(ExpandableSection): add truncated variant

packages/react-core/src/components/ContextSelector/examples/ContextSelectorBasic.tsx, packages/react-core/src/components/ContextSelector/examples/ContextSelectorPlainText.tsx, packages/react-core/src/components/ContextSelector/examples/ContextSelectorWithFooter.tsx, packages/react-core/src/components/DualListSelector/examples/DualListSelectorComposable.tsx, packages/react-core/src/components/DualListSelector/examples/DualListSelectorComposableDragDrop.tsx, packages/react-core/src/components/DualListSelector/examples/DualListSelectorComposableTree.tsx, packages/react-core/src/components/DualListSelector/examples/DualListSelectorTreeExample.tsx, packages/react-core/src/components/MenuToggle/MenuToggle.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableActionsMenu.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableApplicationLauncher.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableContextSelector.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableDrilldownMenu.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableFlyout.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableSimpleCheckboxSelect.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableSimpleDropdown.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableSimpleSelect.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableTreeViewMenu.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableTypeaheadSelect.tsx, packages/react-table/src/components/Table/RowWrapper.tsx, packages/react-topology/src/components/layers/LayerContainer.tsx, packages/react-topology/src/pipelines/components/nodes/TaskNode.tsx
Works towards closing #7142. Fixes some common type errors as a result of the React upgrade.
=> Correct types for examples

packages/react-core/src/components/Button/examples/Button.md, packages/react-core/src/demos/Button.md
Makes progress on https://github.com/patternfly/patternfly-org/issues/2990 
=> Adds content to button react examples

packages/react-core/src/components/LoginPage/LoginFooterItem.tsx, packages/react-core/src/components/LoginPage/LoginForm.tsx, packages/react-core/src/components/LoginPage/LoginHeader.tsx, packages/react-core/src/components/LoginPage/LoginMainBody.tsx, packages/react-core/src/components/LoginPage/LoginMainFooter.tsx, packages/react-core/src/components/LoginPage/LoginMainFooterBandItem.tsx, packages/react-core/src/components/LoginPage/LoginMainFooterLinksItem.tsx, packages/react-core/src/components/LoginPage/LoginMainHeader.tsx, packages/react-core/src/components/LoginPage/LoginPage.tsx, packages/react-core/src/components/LoginPage/examples/LoginPage.md, packages/react-core/src/components/LoginPage/examples/LoginPageBasic.tsx, packages/react-core/src/components/LoginPage/examples/LoginPageLanguageSelect.tsx, packages/react-core/src/components/LoginPage/examples/LoginPageShowHidePassword.tsx
**What**: Closes #7228 .
**How**: Added a `headerUtilities` prop in `LoginMainHeader.tsx` using the [styling properties](https://www.patternfly.org/v4/components/login-page/html#with-language-selector) discussed by @mcoker and @mcarrano. Updated `LoginPage.tsx` with a `loginHeaderUtils` prop. Created an example (`LoginPageLanguageSelect.tsx`) to demonstrate the new `Select` component. This example does not change the language of the login page at the moment.
**Additional issues**: N/A.
=> feat(LoginPage): added headerUtilities prop for language selector example

packages/react-core/package.json
Tested this fix in koku-ui locally. Whether this addresses the reported issue with Keycloak is to be determined.
=> fix: react-core should export all contents of dist directory

packages/react-core/src/components/DualListSelector/examples/DualListSelectorComposableDragDrop.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableActionsMenu.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableFlyout.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableSimpleCheckboxSelect.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableSimpleSelect.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableTypeaheadSelect.tsx
Fixes the various syntax errors on the site (one DualListSelector demo and several composable menu demos). Updated the optional function parameters to instead account for undefined in their types (the `?` was registering as a syntax error).
=> fix: syntax errors on surge

packages/react-core/src/components/NumberInput/NumberInput.tsx, packages/react-core/src/components/NumberInput/__tests__/NumberInput.test.tsx
=> fix(NumberInput): prevent errors when onChange is passed via inputProps

.eslintrc.json, packages/react-charts/src/components/ChartUtils/chart-patterns.tsx, packages/react-core/src/components/DualListSelector/DualListSelectorControl.tsx, packages/react-core/src/components/DualListSelector/DualListSelectorControlsWrapper.tsx, packages/react-core/src/components/DualListSelector/DualListSelectorListItem.tsx, packages/react-core/src/components/DualListSelector/DualListSelectorListWrapper.tsx, packages/react-core/src/components/InputGroup/InputGroup.tsx, packages/react-core/src/components/SearchInput/SearchInput.tsx, packages/react-core/src/components/TextInputGroup/TextInputGroup.tsx, packages/react-core/src/components/TextInputGroup/TextInputGroupMain.tsx, packages/react-core/src/next/components/Wizard/WizardToggle.tsx, packages/react-log-viewer/src/LogViewer/LogViewer.tsx, packages/react-table/src/components/TableComposable/TableComposable.tsx, packages/react-topology/src/components/edges/terminals/ConnectorArrow.tsx
The [Rules of Hooks](https://reactjs.org/docs/hooks-rules.html) are being violated in several places. This causes errors in our application when it's being build for production:
This PR removes conditional rendering of hooks where possible to avoid these errors. And enables an ESLint rule to enforce this.
=> Remove conditional usage of React hooks

packages/react-core/src/components/MenuToggle/MenuToggle.tsx
=> fix(MenuToggle): Typeahead variant styles

packages/react-core/src/components/Page/PageSection.tsx, packages/react-core/src/components/Page/__tests__/PageSection.test.tsx
**What**: Closes #7419
Convenience link to the Page component: https://patternfly-react-pr-7891.surge.sh/components/page
=> feat(PageSection): add ability to specify HTML element via prop

packages/react-core/src/components/TimePicker/TimePicker.tsx
**What**: Closes #7747 
I would like to be able to add a test for this bug, but since it's something that only presented in Safari I'm not sure how I would go about that. If anyone has any ideas for that please let me know!
Convenience link: https://patternfly-react-pr-7888.surge.sh/components/time-picker/
=> fix(TimePicker): scroll dropdown to typed value in safari

packages/react-core/src/components/Alert/Alert.tsx, packages/react-core/src/components/AlertGroup/AlertGroupInline.tsx, packages/react-integration/cypress/integration/alertgrouptimeoutfrombottom.spec.ts, packages/react-integration/demo-app-ts/src/Demos.ts, packages/react-integration/demo-app-ts/src/components/demos/AlertGroupDemo/AlertGroupTimeoutFromBottomDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/index.ts
**What**: Closes #7877 
Needed for #7843 
Note: I added an integration test rather than unit tests as I couldn't identify a good way to unit test either side of the Alert/AlertGroup/AlertGroupInline interaction. This is because Alert doesn't *do* anything with `uniqueId` and `AlertGroupInline` just applies it as a `key`.
=> fix(AlertGroup): update AlertGroupInline to not use child index as a key

packages/react-table/src/components/TableComposable/examples/ComposableTable.md
**What**: Closes #7424
Adds a the section about scroll containers (and which are required for what sticky variant) in the top header of the sticky table subsection rather than only mentioning them in each example blurb.
=> docs(Table): add section about scroll containers

packages/react-core/src/helpers/resizeObserver.tsx
**What**: Closes #7938
Followup from discussion related to #7810
=> feat(resizeObserver): allow opting out of using requestAnimationFrame

packages/react-integration/demo-app-ts/src/Demos.ts, packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/PipelineLayout.tsx, packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/PipelineTasks.tsx, packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/DemoFinallyNode.tsx, packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/DemoTaskNode.tsx, packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/pipelineComponentFactory.tsx, packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/utils/pipelineUtils.ts, packages/react-styles/src/css/components/Topology/topology-pipelines.css, packages/react-topology/src/hooks/index.ts, packages/react-topology/src/hooks/useScaleNode.tsx, packages/react-topology/src/pipelines/components/anchors/TaskNodeSourceAnchor.ts, packages/react-topology/src/pipelines/components/nodes/TaskNode.tsx, packages/react-topology/src/pipelines/utils/utils.ts, packages/react-topology/src/utils/getNodeScaleTranslation.ts, packages/react-topology/src/utils/index.ts
**What**:
Closes #7900 
**Screen Shots**:
/cc @andrew-ronaldson @mceledonia @serenamarie125 @karthikjeeyar
=> Change pipeline node visuals as scale, show icons for status

packages/react-core/src/components/AlertGroup/examples/AlertGroup.md
=> Adds content to alert group react examples.

packages/react-core/src/demos/examples/DashboardHeader.js
**What**: Closes #7934 
This PR updates the src used for the `Brand` component within `DashboardHeader` to an absolute import path from the package to continue to work within the workspace/website examples but also enable it to work correctly in Codesandbox examples.
=> fix(dashboardheader): update brand image src to absolute import path

packages/react-table/src/docs/demos/Table.md, packages/react-table/src/docs/demos/table-demos/Compact.jsx, packages/react-table/src/docs/examples/Data.jsx
**What**: Closes #7855 
**Additional issues**: Towards #7384 
**Convenience link to demo:** https://patternfly-react-pr-7857.surge.sh/components/table/react-demos/compact/
=> chore(table): update compact table data

packages/react-core/src/demos/BackToTop.md, packages/react-core/src/demos/Banner.md, packages/react-core/src/demos/Card/Card.md, packages/react-core/src/demos/JumpLinks.md, packages/react-core/src/demos/Nav.md, packages/react-core/src/demos/PrimaryDetail.md, packages/react-core/src/demos/Tabs.md, packages/react-core/src/demos/Toolbar.md, packages/react-core/src/demos/Wizard/WizardDemo.md, packages/react-core/src/demos/examples/BackToTop/BackToTopNameDemo.tsx, packages/react-core/src/demos/examples/DashboardWrapper.js, packages/react-core/src/demos/examples/JumpLinks/JumpLinksWithDrawer.js, packages/react-core/src/demos/examples/Nav/NavDrilldown.tsx, packages/react-core/src/demos/examples/Tabs/GrayTabs.tsx, packages/react-core/src/demos/examples/Tabs/ModalTabs.tsx, packages/react-core/src/demos/examples/Tabs/NestedTabs.tsx, packages/react-core/src/demos/examples/Tabs/NestedUnindentedTabs.tsx, packages/react-core/src/demos/examples/Tabs/TabsAndTable.tsx, packages/react-core/src/demos/examples/Tabs/TabsAndTablesAutoWidthTabs.tsx
**What**: Closes #6596 
This PR changes all imports of `DashboardWrapper` and `DashboardHeader` from relative imports paths to absolute import paths, which allows Codesandbox to properly load the components.
Note: DashboardHeader image is not loading correctly in Codesandbox and will require separate investigation:
Note: a [different solution](https://github.com/patternfly/patternfly-org/pull/3122) was implemented for relative import paths for patternfly.org, but that did not translate to the problem here as that relies on the files being imported from an external package.  Updating the relative paths here will not conflict with that update as it will bypass the check for a relative import path implemented in that issue.
=> Fixed dashboard wrapper codesandbox export error

packages/react-core/src/components/Dropdown/DropdownItem.tsx, packages/react-core/src/components/Dropdown/DropdownToggleCheckbox.tsx, packages/react-core/src/components/Dropdown/InternalDropdownItem.tsx, packages/react-core/src/components/Dropdown/Toggle.tsx, packages/react-core/src/components/Modal/Modal.tsx, packages/react-core/src/components/Modal/ModalBoxTitle.tsx, packages/react-core/src/components/TreeView/TreeView.tsx, packages/react-core/src/components/TreeView/TreeViewListItem.tsx, packages/react-core/src/components/TreeView/TreeViewRoot.tsx
**What**: Closes #7553 
- Made updates based on original issue
- Resolved errors of `Cannot invoke an object which is possibly 'undefined'` for optional function props that get called within components by adding optional chaining
- Few other fixes for `possibly undefined` errors by adding optional chaining or `if` blocks
Created #7889 for potential follow-up
=> fix(Modal, Dropdown, TreeView): updates to resolve strict TS errors

packages/react-core/src/components/TextArea/TextArea.tsx, packages/react-core/src/components/TextArea/examples/TextArea.md
=> fix(TextArea) missing props and auto resize example doesn't work as intended

packages/react-core/src/components/TreeView/examples/TreeView.md
**What**: Closes #7785
Folder selection looked like it wasn't being persisted because the parent folder was technically getting selected (but this doesn't have visual styling by default).
=> fix(Treeview): ignore folder selection in basic example

packages/react-core/src/components/MenuToggle/MenuToggle.tsx, packages/react-core/src/components/MenuToggle/__tests__/MenuToggle.test.tsx
=> fix(MenuToggle): pass onClick to split button variant

packages/react-core/src/components/MenuToggle/MenuToggle.tsx, packages/react-core/src/demos/Filters/FilterDemos.md, packages/react-core/src/demos/Filters/examples/FilterCheckboxSelect.tsx, packages/react-core/src/demos/Filters/examples/FilterSearchInput.tsx, packages/react-core/src/demos/Filters/examples/FilterSingleSelect.tsx
Tied to #6710 but will not fully close the issue (more demos are requested). Since the groundwork of updating older demos to use the newer composable components and putting the demo into TSX/functional form was a bulk of the work and is now done the rest should be quicker to finish, I'm just not positive I'll get them all out in this PR.
Working off the design here: https://marvelapp.com/prototype/7i0dj2d/screen/75593646
Demos are under the Demos section in the "Filters" page. Let me know if they should be moved elsewhere or called something else.
=> docs: add filter demos

packages/react-core/src/next/components/Dropdown/Dropdown.tsx, packages/react-core/src/next/components/Dropdown/DropdownGroup.tsx, packages/react-core/src/next/components/Dropdown/DropdownItem.tsx, packages/react-core/src/next/components/Dropdown/DropdownList.tsx, packages/react-core/src/next/components/Dropdown/examples/Dropdown.md, packages/react-core/src/next/components/Dropdown/examples/DropdownBasic.tsx, packages/react-core/src/next/components/Dropdown/examples/DropdownWithDescriptions.tsx, packages/react-core/src/next/components/Dropdown/examples/DropdownWithGroups.tsx, packages/react-core/src/next/components/Dropdown/examples/DropdownWithKebabToggle.tsx, packages/react-core/src/next/components/Dropdown/index.ts, packages/react-core/src/next/components/index.ts
**What**: Closes #7322
This is a simple implementation of a dropdown using Menu under the hood.
The consumer will pass the toggle in so I did not wrap the menu toggle.
TODO:
=> feat(Dropdown next): Added the next version of the dropdown component

package.json, packages/react-core/src/next/components/Wizard/Wizard.tsx, packages/react-core/src/next/components/Wizard/WizardBody.tsx, packages/react-core/src/next/components/Wizard/WizardContext.tsx, packages/react-core/src/next/components/Wizard/WizardNav.tsx, packages/react-core/src/next/components/Wizard/WizardNavItem.tsx, packages/react-core/src/next/components/Wizard/WizardStep.tsx, packages/react-core/src/next/components/Wizard/WizardToggle.tsx, packages/react-core/src/next/components/Wizard/__tests__/Wizard.test.tsx, packages/react-core/src/next/components/Wizard/__tests__/WizardBody.test.tsx, packages/react-core/src/next/components/Wizard/__tests__/WizardFooter.test.tsx, packages/react-core/src/next/components/Wizard/__tests__/WizardStep.test.tsx, packages/react-core/src/next/components/Wizard/__tests__/WizardToggle.test.tsx, packages/react-core/src/next/components/Wizard/__tests__/utils.test.tsx, packages/react-core/src/next/components/Wizard/examples/Wizard.md, packages/react-core/src/next/components/Wizard/examples/WizardCustomNav.tsx, packages/react-core/src/next/components/Wizard/examples/WizardKitchenSink.tsx, packages/react-core/src/next/components/Wizard/hooks/__tests__/useWizardFooter.test.tsx, packages/react-core/src/next/components/Wizard/hooks/useWizardFooter.tsx, packages/react-core/src/next/components/Wizard/types.tsx, packages/react-core/src/next/components/Wizard/utils.ts, yarn.lock
=> feat(Wizard - next): supporting component unit tests

packages/react-core/src/components/Title/examples/Title.md, packages/react-core/src/components/Title/examples/TitleCustomSizes.tsx, packages/react-core/src/components/Title/examples/TitleDefaultSizes.tsx
**What**: Closes #7997 
Convert Title examples to TypeScript.
=> chore(Title): Convert examples to TypeScript

packages/react-core/src/components/AlertGroup/examples/AlertGroupSingularDynamic.tsx, packages/react-core/src/components/AlertGroup/examples/AlertGroupSingularDynamicOverflow.tsx
**What**: 
The examples "Singular dynamic alert group" and "Singular dynamic alert group with overflow message" in the [alert group React examples](https://www.patternfly.org/v4/components/alert-group) output messages that say "Toast" even though these are not toast alert examples. "Toast" is removed from all success, danger, and info alert simulation messages in these examples.
Closes #7799
=> docs: Remove incorrect terminology in alert group example output

packages/react-core/src/components/ProgressStepper/ProgressStep.tsx, packages/react-core/src/components/ProgressStepper/__tests__/ProgressStepper.test.tsx, packages/react-core/src/components/ProgressStepper/examples/ProgressStepperBasicWithDescription.tsx
**What**: Closes #7801 . Updated the `description` prop in `ProgressStep.tsx` to allow for the use of line breaks. This was demonstrated in the updated example of `ProgressStepperWithBasicDescription.tsx` in the second step.
=> feat(ProgressStepper): updating description prop to ReactNode

packages/react-log-viewer/src/LogViewer/LogViewer.tsx, packages/react-log-viewer/src/LogViewer/examples/LogViewer.md, packages/react-log-viewer/src/react-window/createListComponent.ts
**What**: Closes #7876 
Add a prop named `initialIndexWidth`. Users could specify the char numbers they want to show in the line numbers column. For example, if the user anticipates over 100,0000 lines of logs, they could set `initialIndexWidth={7}`, so the index width would expand enough to hold 7 chars.
Add an example to show the usage.
One thing that needs to be mentioned, the user cannot dynamically set this value if the log viewer is not re-rendered because the row height calculation will be inaccurate.
=> feat(log-viewer): add prop initialIndexWidth to support for custom line number col size

packages/react-core/src/components/SearchInput/SearchInput.tsx, packages/react-core/src/components/SearchInput/__tests__/__snapshots__/SearchInput.test.tsx.snap
fixes https://github.com/patternfly/patternfly-react/issues/7796
=> fix(search-input): wrapped advanced search in div instead of span

packages/react-core/src/components/Tabs/Tabs.tsx, packages/react-core/src/components/Tabs/__tests__/Tabs.test.tsx
**What**: Closes #8021 
Convenience link: https://patternfly-react-pr-8022.surge.sh/components/tabs/react/default-overflow/
=> fix(Tabs): reenabled overflow scroll transition functionality

CONTRIBUTING.md
**What**: These 3 links are not working in the [contribution guidelines](https://github.com/patternfly/patternfly-react/blob/main/CONTRIBUTING.md).
Closes: #8041
=> docs(contributing guide): fixed broken links in contributing outline

packages/react-core/src/components/Tile/examples/Tile.md, packages/react-core/src/components/Tile/examples/TileBasic.tsx, packages/react-core/src/components/Tile/examples/TileStacked.tsx, packages/react-core/src/components/Tile/examples/TileStackedWithLargeIcons.tsx, packages/react-core/src/components/Tile/examples/TileWithExtraContent.tsx, packages/react-core/src/components/Tile/examples/TileWithIcon.tsx, packages/react-core/src/components/Tile/examples/TileWithSubtext.tsx, packages/react-core/src/demos/TileDemo.md
**What**: Closes #8039
Convert Tile examples to TypeScript
=> chore(Tile): Convert examples to typescript

packages/react-core/src/components/Menu/Menu.tsx, packages/react-core/src/components/Select/Select.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableActionsMenu.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableApplicationLauncher.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableContextSelector.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableDrilldownMenu.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableDropdwnVariants.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableFlyout.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableOptionsMenuVariants.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableSimpleCheckboxSelect.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableSimpleDropdown.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableSimpleSelect.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableTreeViewMenu.tsx, packages/react-integration/cypress/integration/select.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectDemo.tsx
**What**: Closes #8095
[menu examples](https://patternfly-react-pr-8111.surge.sh/components/menu/)
[select examples](https://patternfly-react-pr-8111.surge.sh/components/select)
[composable menu demos](https://patternfly-react-pr-8111.surge.sh/demos/composable-menu)
To test, just add `isDisabled` to the first menu option in an example, and focus should still be placed on the first, non-disabled option either after opening the menu toggle or pressing Tab (for the menu examples that don't have a toggle)
Also fixed the same issue that was occurring in the Menu component, as well as updating logic in several of the composable menu demos.
=> fix(Select) - updated logic to focus first nondisabled option

packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx, packages/react-code-editor/src/components/CodeEditor/CodeEditorControl.tsx, packages/react-core/src/components/Alert/Alert.tsx, packages/react-core/src/components/Alert/AlertActionCloseButton.tsx, packages/react-core/src/components/Alert/AlertActionLink.tsx, packages/react-core/src/components/Alert/AlertIcon.tsx, packages/react-core/src/components/Alert/AlertToggleExpandButton.tsx, packages/react-core/src/components/CalendarMonth/CalendarMonth.tsx, packages/react-core/src/components/DatePicker/DatePicker.tsx, packages/react-core/src/components/Popover/Popover.tsx
**What**: Closes #7973
Tried using general verbiage for the CalendarFormat and Popover descriptions, since those are used in multiple components.
In particular I could use some eyes on the DatePickerRef description to see if it matches the intention of that interface.
Also reordered props alphabetically.
=> docs(Alert, calendar month, code editor, date picker) - add sub component descriptions

packages/react-core/src/components/NotificationBadge/NotificationBadge.tsx, packages/react-core/src/components/NotificationBadge/__tests__/NotificationBadge.test.tsx, packages/react-core/src/components/NotificationBadge/__tests__/__snapshots__/NotificationBadge.test.tsx.snap, packages/react-core/src/components/NotificationBadge/examples/NotificationBadge.md, packages/react-core/src/components/NotificationBadge/examples/NotificationBadgeBasic.tsx, packages/react-core/src/components/NotificationBadge/examples/NotificationBadgeWithCount.tsx, packages/react-core/src/demos/NotificationDrawer/NotificationDrawer.md
**What**: Closes #7379, closes #6142 
[Notification badge examples](https://patternfly-react-pr-8010.surge.sh/components/notification-badge)
[Notification drawer demos](https://patternfly-react-pr-8010.surge.sh/components/notification-drawer/react-demos)
- Added an `isExpanded` prop to the Notification Badge component
- Updated the examples so that they match Core (showing read, unread, and attention variants)
- Updated the examples so that the onClick handler updates the expanded state, rather than the variant
- Updated Notification Drawer demos to use this new expanded state 
- Reordered the props alphabetically
N/A
=> feat(NotificationBadge): added expanded state

packages/react-core/src/components/Badge/__tests__/Badge.test.tsx, packages/react-core/src/components/Badge/__tests__/__snapshots__/Badge.test.tsx.snap
=> chore(Badge): update tests to new react testing library standards

packages/react-core/src/components/OverflowMenu/OverflowMenu.tsx, packages/react-core/src/components/OverflowMenu/__tests__/OverflowMenu.test.tsx, packages/react-core/src/components/OverflowMenu/examples/OverflowMenu.md, packages/react-core/src/components/OverflowMenu/examples/OverflowMenuBreakpointOnContainer.tsx, packages/react-integration/cypress/integration/overflowmenu.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/OverflowMenuDemo/OverflowMenuDemo.tsx
**What**: Closes #7376
[Breakpoint on container example](https://patternfly-react-pr-7913.surge.sh/components/overflow-menu#breakpoint-on-container)
=> feat(OverflowMenu): allow breakpoint on container width

packages/react-core/src/components/DualListSelector/DualListSelectorPane.tsx, packages/react-core/src/components/DualListSelector/__tests__/__snapshots__/DualListSelector.test.tsx.snap, packages/react-core/src/components/SearchInput/SearchInput.tsx, packages/react-integration/cypress/integration/duallistselectorbasic.spec.ts, packages/react-integration/cypress/integration/duallistselectortree.spec.ts, packages/react-integration/cypress/integration/duallistselectorwithactions.spec.ts
**What**: Closes #7977
Updates DualListSelector to internally build a SearchInput.
Adds `type` prop to SearchInput to match DualListSelector's initial input type.
=> feat(DualListSelector, SearchInput): use SearchInput in DLS, add type prop to SearchInput

packages/react-core/src/components/Menu/Menu.tsx, packages/react-core/src/components/MenuToggle/MenuToggle.tsx, packages/react-core/src/demos/Filters/FilterDemos.md, packages/react-core/src/demos/Filters/examples/FilterAttributeSearch.tsx, packages/react-core/src/demos/Filters/examples/FilterCheckboxSelect.tsx, packages/react-core/src/demos/Filters/examples/FilterFaceted.tsx, packages/react-core/src/demos/Filters/examples/FilterMixedSelectGroup.tsx, packages/react-core/src/demos/Filters/examples/FilterSameSelectGroup.tsx, packages/react-core/src/demos/Filters/examples/FilterSearchInput.tsx, packages/react-core/src/demos/Filters/examples/FilterSingleSelect.tsx, packages/react-table/src/components/TableComposable/Td.tsx, packages/react-table/src/components/TableComposable/Th.tsx
**What**: Closes #7965
Adds remaining filter demos (attribute search, same select filter group, mixed select filter group, faceted filter).
Updates all filter demos to have the following:
- Bulk select respects filtered state
- Menu ids are unique between demos
- Checkbox column space is maintained when there is an empty state
- `Td`s are truncated to maintain column widths while filtering
While adding the last bullet I also noticed that no tooltip is added when Tds are truncated like Ths should I added that functionality as well.
Other updates in this PR:
- `Td`: Added `tooltip` prop, and when using the truncate modifier, `Td` will attempt to make a default tooltip like `Th`
- `Th`: Updated internal `canDefault` variable name to `canMakeDefaultTooltip` (matched in `Td` as well)
- …
=> feat(Table): add tooltip for truncated Td, docs(Filter): add filter demos

packages/react-core/src/components/SimpleList/SimpleListItem.tsx
=> feat(simple list): removed deprecated prop

packages/react-core/src/components/FileUpload/FileUpload.tsx, packages/react-core/src/components/FileUpload/FileUploadField.tsx, packages/react-core/src/components/FileUpload/__tests__/FileUpload.test.tsx, packages/react-core/src/components/FileUpload/__tests__/FileUploadField.test.tsx
=> chore(FileUpload): remove deprecated onChange prop

packages/react-core/src/components/Pagination/OptionsToggle.tsx, packages/react-core/src/components/Pagination/Pagination.tsx, packages/react-core/src/components/Pagination/PaginationOptionsMenu.tsx, packages/react-core/src/components/Pagination/ToggleTemplate.tsx, packages/react-core/src/components/Pagination/__tests__/Generated/PaginationOptionsMenu.test.tsx, packages/react-core/src/components/Pagination/examples/Pagination.md
=> chore(pagination): rename `ToggleTemplateProps` to `PaginationToggleTemplateProps` in pagination component

packages/react-core/src/components/Accordion/examples/AccordionBordered.tsx, packages/react-core/src/components/Button/Button.tsx, packages/react-core/src/components/Button/__tests__/Button.test.tsx, packages/react-core/src/components/Button/__tests__/__snapshots__/Button.test.tsx.snap, packages/react-core/src/components/Button/examples/Button.md, packages/react-core/src/components/Button/examples/ButtonCallToAction.tsx, packages/react-core/src/components/Button/examples/ButtonSmall.tsx, packages/react-integration/demo-app-ts/src/components/demos/ButtonDemo/ButtonDemo.tsx
=> feat(button): combine isSmall and isLarge into customSize

packages/react-docs/RELEASE-NOTES.md
=> chore(docs): Updated release notes

packages/react-core/src/components/Sidebar/examples/Sidebar.md, packages/react-core/src/components/Sidebar/examples/SidebarBasic.tsx, packages/react-core/src/components/Sidebar/examples/SidebarPanelRightGutter.tsx, packages/react-core/src/components/Sidebar/examples/SidebarResponsivePanel.tsx, packages/react-core/src/components/Sidebar/examples/SidebarStack.tsx, packages/react-core/src/components/Sidebar/examples/SidebarStaticPanel.tsx, packages/react-core/src/components/Sidebar/examples/SidebarStickyPanel.tsx
**What**: Closes #8055 . Converted examples to TS
=> chore(Sidebar): converted examples to typescript

packages/react-core/src/components/Banner/__tests__/Banner.test.tsx, packages/react-core/src/components/Banner/__tests__/__snapshots__/Banner.test.tsx.snap
=> chore(Banner): update tests to new react testing library standards

package.json
**What**: Closes #8143 
prevent certain TZ specific tests from failing if ran on a machine outside EST TZ
=> fix(tests): specify est timezone for jest to run with

packages/react-core/src/components/Page/Page.tsx, packages/react-core/src/components/Page/__tests__/__snapshots__/Page.test.tsx.snap
**What**: Closes #7861 . Removed the default value for `onPageResize` so that it passes in as `undefined` if not explicitly stated by the user.
=> fix(Page): updated onPageResize prop to undefined default

packages/react-core/src/components/Divider/Divider.tsx
=> Chore(divider): Remove isVertical prop

packages/react-core/src/components/Card/Card.tsx, packages/react-core/src/components/Card/__tests__/Card.test.tsx, packages/react-core/src/components/Card/__tests__/__snapshots__/Card.test.tsx.snap
=> chore(Card): removed isHoverable prop

packages/react-core/src/components/Select/Select.tsx, packages/react-core/src/components/Select/__tests__/Select.test.tsx, packages/react-core/src/components/Select/examples/Select.md
**What**: Closes #8163 
Demo here:
https://patternfly-react-pr-8165.surge.sh/components/select#typeahead
Check `isCreatable` and `isCreateOptionOnTop`, then do a typeahead like "new" for example.
=> feat(Select): flag to put create option at top of typeahead

packages/react-core/src/components/Button/Button.tsx, packages/react-core/src/next/components/Dropdown/Dropdown.tsx, packages/react-core/src/next/components/Dropdown/examples/DropdownBasic.tsx, packages/react-core/src/next/components/Dropdown/examples/DropdownWithDescriptions.tsx, packages/react-core/src/next/components/Dropdown/examples/DropdownWithGroups.tsx, packages/react-core/src/next/components/Dropdown/examples/DropdownWithKebabToggle.tsx
=> fix(Dropdown next): Add support for forward ref and updated docs.

packages/react-core/src/components/Slider/Slider.tsx, packages/react-core/src/components/Slider/_tests_/__snapshots__/Slider.test.tsx.snap
=> fix(Slider): correct tab order when input is above thumb

packages/react-core/src/components/Label/examples/LabelEditable.tsx, packages/react-core/src/components/LabelGroup/examples/LabelGroupEditableAdd.tsx, packages/react-core/src/components/LabelGroup/examples/LabelGroupEditableAddDropdown.tsx, packages/react-core/src/components/LabelGroup/examples/LabelGroupEditableAddModal.tsx, packages/react-core/src/components/LabelGroup/examples/LabelGroupEditableLabels.tsx
=> feat(label+labelGroup): update aria-labels to include label text

packages/react-core/src/components/Dropdown/DropdownItem.tsx, packages/react-core/src/components/Dropdown/DropdownMenu.tsx, packages/react-core/src/components/Dropdown/DropdownToggle.tsx, packages/react-core/src/components/Dropdown/Toggle.tsx
**What**: Closes #8088 .
Removed all instances of:
- DropdownItem: `isHovered`
- DropdownMenu: `openedOnEnter`
- DropdownToggle: `isPrimary`
- Toggle: `isPrimary`
=> chore(Dropdown): remove deprecated props

packages/react-core/src/demos/examples/JumpLinks/JumpLinksWithDrawer.js
**What**: Closes #8109
- Removes padding from drawer content
- adds PageSections around the jumplinks and around the main content
- updates the selector to calculate the scrolling offset given the sticky drawer toggle.
=> fix(JumpLinks): clean up demo in a drawer

packages/react-core/src/components/TextArea/__tests__/TextArea.test.tsx, packages/react-core/src/components/TextArea/__tests__/__snapshots__/TextArea.test.tsx.snap
=> TextArea test revamp

packages/react-code-editor/package.json, packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx, packages/react-code-editor/src/components/CodeEditor/__test__/__snapshots__/CodeEditor.test.tsx.snap, packages/react-core/package.json, packages/react-core/src/components/FileUpload/FileUpload.tsx, packages/react-core/src/components/FileUpload/__tests__/__snapshots__/FileUpload.test.tsx.snap, packages/react-core/src/components/FileUpload/examples/FileUploadCustomPreview.tsx, packages/react-core/src/components/FileUpload/examples/FileUploadSimpleFile.tsx, packages/react-core/src/components/FileUpload/examples/FileUploadSimpleText.tsx, packages/react-core/src/components/FileUpload/examples/FileUploadTextWithEdits.tsx, packages/react-core/src/components/FileUpload/examples/FileUploadTextWithRestrictions.tsx, packages/react-core/src/components/MultipleFileUpload/MultipleFileUpload.tsx, packages/react-core/src/components/MultipleFileUpload/__tests__/__snapshots__/MultipleFileUpload.test.tsx.snap, packages/react-core/src/components/MultipleFileUpload/examples/MultipleFileUploadBasic.tsx, packages/react-core/src/demos/examples/MultipleFileUpload/MultipleFileUploadRejectedFile.tsx, yarn.lock
Upgrades `react-dropzone` to the latest version. This is needed as older versions cause compilation errors in our application.
=> Upgrade 'react-dropzone' to latest version

packages/react-core/src/components/DataList/DataListToggle.tsx, packages/react-core/src/components/DataList/examples/DataList.md, packages/react-core/src/components/DataList/examples/DataListMixedExpandable.tsx
**What**: Closes #7950
Adds `buttonProps` to `DataListToggle`, allowing the toggle button to be customized.
Adds new example showcasing a data list that has both expandable and non-expandable rows.
=> feat(DataList): pass button props to toggle

packages/react-core/src/components/Dropdown/DropdownWithContext.tsx
**What**: Closes #8013 
To test, add:
```js
isFlipEnabled
menuAppendTo='parent'
```
to [the right positioned Dropdown example in the preview link](https://patternfly-react-pr-8224.surge.sh/components/dropdown#right-positioned-menu) and verify that the example stays right-aligned and flips properly.
=> fix(Dropdown): enabled right aligned dropdown with isFlipEnabled

packages/react-core/src/components/DatePicker/DatePicker.tsx, packages/react-core/src/components/Popover/Popover.tsx, packages/react-integration/demo-app-ts/src/components/demos/PopoverDemo/PopoverDemo.tsx
**What**: Closes #8092 
Removed all deprecated props
=> chore(Popover): remove deprecated props

packages/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx, packages/react-core/src/components/ClipboardCopy/__tests__/Generated/__snapshots__/ClipboardCopy.test.tsx.snap, packages/react-core/src/components/ClipboardCopy/examples/ClipboardCopy.md, packages/react-core/src/components/Wizard/WizardNav.tsx, packages/react-core/src/components/Wizard/WizardNavItem.tsx, packages/react-core/src/components/Wizard/__tests__/Generated/__snapshots__/WizardNav.test.tsx.snap, packages/react-core/src/components/Wizard/__tests__/Generated/__snapshots__/WizardNavItem.test.tsx.snap, packages/react-core/src/components/Wizard/__tests__/__snapshots__/Wizard.test.tsx.snap, packages/react-core/src/components/Wizard/examples/Wizard.md
**What**: Closes #7767
Adds OUIA props to WizardNav, WizardNavItem, and ClipboardCopy.
Adds OUIA props to the above respective docs pages.
ModalCloseButton does have the OUIA props extended, and the passed ouiaId is set to `{ouiaId}-ModalBoxCloseButton`. Will that be sufficient or should this be changed to directly reflect the ouiaId without the added suffix? @gashcrumb
=> feat(Wizard,ClipboardCopy): add OUIA props to WizardNav, WizardNavItem, ClipboardCopy

packages/react-core/src/components/Tooltip/Tooltip.tsx, packages/react-integration/demo-app-ts/src/components/demos/TooltipDemo/TooltipDemo.tsx
=> chore(Tooltip) remove deprecated props

packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/PipelineLayout.tsx, packages/react-topology/src/Visualization.ts, packages/react-topology/src/types.ts
**What**: 
Closes #8149 
/cc @karthikjeeyar
=> feat(Topology): Add option to fit layout to screen upon layout completion

packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx, packages/react-code-editor/src/components/CodeEditor/CodeEditorControl.tsx, packages/react-code-editor/src/components/CodeEditor/examples/CodeEditorCustomControl.tsx, packages/react-code-editor/src/components/CodeEditor/examples/CodeEditorShortcutMainHeader.tsx, packages/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx, packages/react-core/src/components/ClipboardCopy/ClipboardCopyButton.tsx, packages/react-core/src/components/CodeBlock/examples/CodeBlockBasic.tsx, packages/react-core/src/components/CodeBlock/examples/CodeBlockExpandable.tsx, packages/react-core/src/components/Tooltip/Tooltip.tsx
**What**: Closes #7884 
- we now use `<CodeEditorControl>` for all dynamically built controls in CodeEditor.tsx.
- we now pass tooltipProps to `<CodeEditorControl>` that gets passed along to `<Tooltip>`.
- Code editor now uses tooltip's default prop values unless consumer overrides them with tooltipProps
- Deprecated the previous prop that were passed to the tooltip (they still work)
- Copy to clipboard button in the code editor now triggers with keyboard focus
- created a callback so that the 'copied to clipboard' success text can be reverted back only after the tooltip closes (prevents timings from getting out of sync and the text reverting back right before the tooltip closes)
- Updated copy functions to use `navigator.clipboard()` (keeps broswer focus on the copy button once clicked) …
=> fix(CodeEditor): use codeEditorControls and clean up overall

packages/react-core/src/components/Menu/MenuItem.tsx, packages/react-core/src/components/Menu/examples/Menu.md, packages/react-core/src/components/Menu/examples/MenuDangerMenuItem.tsx
**What**: Closes #8058
Because most of the style in `MenuItem.tsx` is applied based on a boolean prop, I've decided to do the same here.
=> feat(menu): add optional danger state for menu items

packages/react-core/src/components/DualListSelector/DualListSelector.tsx
**What**: Closes #8268
**Additional issues**: Reported in a code review by @sanketpathak https://github.com/openshift/console/pull/12159#issuecomment-1282122767
**Analysis / Root cause**: 
`addAllVisible` and `removeAllVisible` uses `prevState.availableFilteredOptions || prevState.availableOptions` and `prevState.chosenFilteredOptions || prevState.chosenOptions` to take a look into filtered or all options.
`availableFilteredOptions` and `chosenFilteredOptions` was only calculated before when the filter is changed.
But it should be also recalculated when values are moved from the left to the right side and vice versa.
**Solution Description**: 
Calculate `availableFilteredOptions` and `chosenFilteredOptions` also when moving options in `addAllVisible`, `removeAllVisible`, `addSelected` or …
=> fix(DualListSelector): Add/remove button didn't work if search is used

packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/PipelineTasks.tsx, packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/components/DemoTaskNode.tsx, packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/utils/pipelineUtils.ts, packages/react-topology/src/pipelines/components/nodes/TaskNode.tsx
=> feat(topology): Allow tooltip usage on pipeline task node badges

packages/react-core/src/next/components/Dropdown/Dropdown.tsx, packages/react-core/src/next/components/Dropdown/DropdownItem.tsx
**What**: Closes #8046
Did implementation similar to `Button` component.
=> feat: add ouia support to dropdown next

packages/react-core/src/components/Button/__tests__/Button.test.tsx, packages/react-core/src/components/Button/__tests__/__snapshots__/Button.test.tsx.snap, packages/react-core/src/components/Button/examples/ButtonProgress.tsx
**What**: Closes #8107 
**Link to demo for convenience**: https://patternfly-react-pr-8172.surge.sh/components/button#progress-indicators
=> chore(Button): added inline link progress support to demos

packages/react-core/src/components/Alert/AlertIcon.tsx
**What**: Closes #8015
To reproduce, change the variant in an alert [on this page](https://www.patternfly.org/v4/components/alert) to 'error' (which is not a valid variant) and see the error message on the screen.
in my preview build, change the variant in an alert to error and see it just fall back to the default style for alert rather than crashing the component.
=> fix(Alert): prevent error being thrown when using invalid variant

packages/react-code-editor/src/components/CodeEditor/examples/CodeEditor.md, packages/react-core/src/components/AlertGroup/examples/AlertGroup.md, packages/react-core/src/components/CalendarMonth/examples/CalendarMonth.md, packages/react-core/src/components/Card/Card.tsx, packages/react-core/src/components/DataList/DataList.tsx, packages/react-core/src/components/DataList/DataListItem.tsx, packages/react-core/src/components/DualListSelector/examples/DualListSelector.md, packages/react-core/src/components/LabelGroup/examples/LabelGroup.md, packages/react-core/src/components/Masthead/examples/Masthead.md, packages/react-core/src/components/Menu/examples/Menu.md, packages/react-core/src/components/MenuToggle/examples/MenuToggle.md, packages/react-core/src/components/MultipleFileUpload/examples/MultipleFileUpload.md, packages/react-core/src/components/NotificationDrawer/examples/NotificationDrawer.md, packages/react-core/src/components/Panel/examples/Panel.md, packages/react-core/src/components/Popover/Popover.tsx, packages/react-core/src/components/Popover/examples/Popover.md, packages/react-core/src/components/Select/examples/Select.md, packages/react-core/src/components/Slider/examples/Slider.md, packages/react-core/src/components/TextArea/examples/TextArea.md, packages/react-core/src/components/TextInput/examples/TextInput.md, packages/react-core/src/components/TreeView/examples/TreeView.md, packages/react-core/src/components/Wizard/Wizard.tsx, packages/react-core/src/components/Wizard/WizardToggle.tsx, packages/react-core/src/components/Wizard/examples/Wizard.md, packages/react-core/src/demos/MultipleFileUploadDemos.md, packages/react-core/src/demos/NotificationDrawer/NotificationDrawer.md, packages/react-table/src/components/Table/examples/Table.md, packages/react-table/src/components/TableComposable/examples/ComposableTable.md
**What**: Closes #8245
Remove beta tags:
Alert group: overflow
Calendar month
Card: raised variant
Code editor
Data list: selectableRow prop
Dual list selector
icon sprites
Label group (except editable variant)
Masthead
Menu: checkbox variant
Menu toggle
File upload - multiple
Notification drawer
Panel
Popover: alert severity, icon
Select: view more, loading variant
Slider
Table: tree view
Tree view
Wizard with drawer
=> chore(beta-components): promote candidates 2022.14

.github/workflows/extensions.yml
Whenever a patternfly-react issue is tagged with the 'extensions' label, it will automatically get added to the 'PatternFly Extensions' project board
=> Create workflow for extensions issues

packages/react-core/src/components/CalendarMonth/CalendarMonth.tsx, packages/react-core/src/components/DatePicker/DatePicker.tsx, packages/react-core/src/components/Timestamp/Timestamp.tsx, packages/react-core/src/components/Timestamp/__tests__/Timestamp.test.tsx, packages/react-core/src/components/Timestamp/__tests__/__snapshots__/Timestamp.test.tsx.snap, packages/react-core/src/helpers/datetimeUtils.ts, packages/react-core/src/helpers/index.ts
**What**: Closes #7952
[Timestamp preview build](https://patternfly-react-pr-8205.surge.sh/components/timestamp)
Borrowed some logic from our Calendar Month component to have date state internally, which I believe may have been partly causing the original issue (updating example code from our live site causes the datetime attribute to render properly, as does clicking the Timestamp link in our sidenav, but being linked directly to the page causes the issue to occur).
Also made a slight tweak to how props were spread so that a `dateTime` prop didn't get applied to both the outter `span` and inner `time` elements.
=> fix(Timestamp): updated logic for rendering datetime attribute

packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/PipelineLayout.tsx, packages/react-integration/demo-app-ts/src/components/demos/TopologyDemo/useDemoPipelineNodes.tsx, packages/react-topology/src/pipelines/components/groups/DefaultTaskGroup.tsx, packages/react-topology/src/pipelines/utils/utils.ts
**What**:
Closes https://github.com/patternfly/patternfly-react/issues/8298
=> Fix group labels, revert breaking change

packages/react-core/src/components/Skeleton/examples/Skeleton.md, packages/react-core/src/components/Skeleton/examples/SkeletonBasic.tsx, packages/react-core/src/components/Skeleton/examples/SkeletonDefault.tsx, packages/react-core/src/components/Skeleton/examples/SkeletonPercentageHeight.tsx, packages/react-core/src/components/Skeleton/examples/SkeletonPercentageWidth.tsx, packages/react-core/src/components/Skeleton/examples/SkeletonShapes.tsx, packages/react-core/src/components/Skeleton/examples/SkeletonText.tsx
=> chore(Skeleton): update examples to typescript

packages/react-topology/src/components/nodes/DefaultNode.tsx
=> Topology - DefaultNode - Set status decorators to be opaque

packages/react-core/src/components/Label/examples/LabelCompact.tsx
Bug - Label - hrefs in compact example have wrong anchor tag #8311
=> fix(label): fix hrefs in compact example

packages/react-core/src/components/TimePicker/TimePicker.tsx, packages/react-core/src/components/TimePicker/__tests__/TimePicker.test.tsx
**What**: Closes #7953 , closes #7993
[Timepicker on live site](https://www.patternfly.org/v4/components/time-picker)
[Timepicker preview build](https://patternfly-react-pr-8267.surge.sh/components/time-picker)
To test the `minTime`/`maxTime` issue, copy+paste the following code and click the buttons to notice how the timepicker menu updates with the new min/max times in the preview build (but not on the live site):
```
import React from 'react';
import { TimePicker } from '@patternfly/react-core';
const MinimummaximumTimes = () => {
const [minTime, setMinTime] = React.useState("9:30")
const [maxTime, setMaxTime] = React.useState("17:15")
return (
<>
<button onClick={() => setMinTime("8:30")}>Update minTime</button>
<button onClick={() => setMaxTime("18:15")}>Update maxTime</button> …
```
=> fix(TimePicker): fixed bugs when updating time/minTime/maxTime props

packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx, packages/react-core/src/components/Nav/NavList.tsx, packages/react-core/src/components/TextInput/TextInput.tsx, packages/react-core/src/demos/JumpLinks.md, packages/react-core/src/demos/examples/JumpLinks/JumpLinksWithDrawer.js, packages/react-core/src/helpers/resizeObserver.tsx
**What**: Closes #7942 
Changed resizeObserver so that you have to opt-in to the use of `useRequestAnimationFrame` rather than opting out. Also updated wherever `getResizeObserve` is called by adding `true` as a third argument when a non-debounced method is passed in.
=> chore(resizeObserver): refactored use of useRequestAnimationFrame

packages/react-core/src/components/ApplicationLauncher/ApplicationLauncher.tsx, packages/react-core/src/components/ContextSelector/ContextSelector.tsx, packages/react-core/src/components/Dropdown/Dropdown.tsx, packages/react-core/src/components/Dropdown/DropdownWithContext.tsx, packages/react-core/src/components/Nav/NavItem.tsx, packages/react-core/src/components/OptionsMenu/OptionsMenu.tsx, packages/react-core/src/components/SearchInput/SearchInput.tsx, packages/react-core/src/components/Select/Select.tsx, packages/react-core/src/components/Tabs/OverflowTab.tsx, packages/react-core/src/components/TimePicker/TimePicker.tsx, packages/react-core/src/next/components/Dropdown/Dropdown.tsx, packages/react-core/src/next/components/Select/Select.tsx
**What**: Closes #7869
Pipes `zIndex` prop to multiple components to allow customization of the popper z-index. By default this prop is still `9999`, and will be updated in a follow up to better defaults based on guidance from core.
=> feat(Popper, misc): allow components to customize popper z-index

packages/react-code-editor/README.md
I ran into some trouble using the code editor in my project. The main problems were that I had to do extra work that the docs didn't cover because I bootstrapped my project with `create-react-app` and I needed YAML highlighting support which required an extra plugin. This doc update should make it easier for anyone who's in the same boat :)
**What**: Closes #8347
=> Update README with create-react-app and YAML help

packages/react-core/src/components/Text/TextList.tsx, packages/react-core/src/components/Text/TextListItem.tsx, packages/react-core/src/components/Text/__tests__/Generated/__snapshots__/TextList.test.tsx.snap, packages/react-core/src/components/Text/__tests__/Generated/__snapshots__/TextListItem.test.tsx.snap, packages/react-core/src/components/Text/__tests__/Text.test.tsx, packages/react-core/src/components/Text/__tests__/TextContent.text.tsx, packages/react-core/src/components/Text/__tests__/TextList.test.tsx, packages/react-core/src/components/Text/__tests__/TextListItem.test.tsx, packages/react-core/src/components/Text/__tests__/__snapshots__/TextContent.text.tsx.snap, packages/react-core/src/components/Text/__tests__/__snapshots__/TextList.test.tsx.snap, packages/react-core/src/components/Text/__tests__/__snapshots__/TextListItem.test.tsx.snap
=> chore(Text): update tests to new react testing library standards

packages/react-core/src/components/MultipleFileUpload/MultipleFileUploadStatusItem.tsx, packages/react-core/src/components/MultipleFileUpload/__tests__/MultipleFileUploadStatusItem.test.tsx, packages/react-core/src/components/MultipleFileUpload/examples/MultipleFileUpload.md, packages/react-core/src/components/MultipleFileUpload/examples/MultipleFileUploadBasic.tsx
**What**: Closes #8238 
Convenience link: https://patternfly-react-pr-8344.surge.sh/components/file-upload---multiple#basic
Check the "Force uploads to fail" checkbox to see the helper text in action!
=> feat(MultipleFileUpload): added support for helper text

packages/react-core/src/components/Menu/examples/Menu.md, packages/react-core/src/components/Menu/examples/MenuFilteringWithSearchInput.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableApplicationLauncher.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableContextSelector.tsx, packages/react-integration/cypress/integration/menu.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/MenuDemo/MenuDemo.tsx
=> feat(MenuInput): use SearchInput instead of TextInput

packages/react-core/src/components/NumberInput/NumberInput.tsx, packages/react-core/src/components/NumberInput/__tests__/NumberInput.test.tsx, packages/react-core/src/components/NumberInput/examples/NumberInput.md, packages/react-core/src/components/NumberInput/examples/NumberInputCustomStep.tsx, packages/react-core/src/components/NumberInput/examples/NumberInputCustomStepAndThreshold.tsx, packages/react-core/src/components/NumberInput/examples/NumberInputDefault.tsx, packages/react-core/src/components/NumberInput/examples/NumberInputDisabled.tsx, packages/react-core/src/components/NumberInput/examples/NumberInputUnit.tsx, packages/react-core/src/components/NumberInput/examples/NumberInputUnitThreshold.tsx, packages/react-core/src/components/NumberInput/examples/NumberInputVaryingSizes.tsx, packages/react-core/src/components/NumberInput/examples/NumberInputWithStatus.tsx, packages/react-integration/cypress/integration/numberInput.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/NumberInputDemo/NumberInputDemo.tsx
**What**: Closes #8127
Allows the number input to be empty to let a user type in a number to the input.
I did have to update a unit test which is a bit of an edge case, but if the user intentionally passes `null` to `value` then there will be a console error (because an input should not be null). However in the updated example the input is fine when you clear the number (value = '') out to type something in, and the blur handler will bound the input to the min or max values once you move focus away from the input.
=> fix(NumberInput): allow user to back out number to type input

packages/react-core/src/components/Popover/__tests__/__snapshots__/Popover.test.tsx.snap, packages/react-core/src/components/SearchInput/__tests__/__snapshots__/SearchInput.test.tsx.snap, packages/react-core/src/components/Tooltip/__tests__/__snapshots__/Tooltip.test.tsx.snap, packages/react-core/src/helpers/Popper/Popper.tsx
**What**: Closes #8277
This should resolve the layout issues that can occur due to the new `div`.
=> fix(Popper): add display contents to wrapping divs

packages/react-catalog-view-extension/package.json, packages/react-console/package.json, packages/react-core/package.json, packages/react-core/src/components/Tabs/Tab.tsx, packages/react-core/src/components/Tabs/TabAction.tsx, packages/react-core/src/components/Tabs/Tabs.tsx, packages/react-core/src/components/Tabs/__tests__/Tab.test.tsx, packages/react-core/src/components/Tabs/__tests__/__snapshots__/Tab.test.tsx.snap, packages/react-core/src/components/Tabs/examples/Tabs.md, packages/react-core/src/components/Tabs/examples/TabsHelp.tsx, packages/react-core/src/components/Tabs/examples/TabsHelpAndClose.tsx, packages/react-core/src/components/Tabs/index.ts, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
**What**: Closes #8236
Adds `TabAction` component.
Adds `action` prop to `Tab` - inserts content inside the Tab `li` but not as part of the Tab `button`. Accepts a ReactNode, and multiple `TabAction` components (and other things like Popover) can be passed in with an empty tag wrapping them.
Adds example for help popovers and help + close buttons.
Keeps the `Tabs` `onClose` prop currently, but this could be removed if it's too confusing to have both (as passing `action` to Tab will overwrite the content generated from `onClose`). I can just see this prop being useful as a bit of a shortcut if a user wants only the close button for all tabs.
=> feat(Tabs): add TabAction, update core ver

packages/react-core/src/components/TimePicker/TimePicker.tsx
**What**: Closes #8118
onBlur causing validation to flash when clicking into the menu. not needed, since validation already running everytime the onToggle function is called.
=> fix(TimePicker): removed redundant onBlur

packages/react-core/src/components/DataList/DataList.tsx, packages/react-core/src/components/DataList/DataListDragButton.tsx, packages/react-core/src/components/DataList/DataListItem.tsx, packages/react-integration/cypress/integration/datalist.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/DataListDemo/DataListDraggableDemo.tsx
**What**: Closes #8086 
Essentially removed some of what was originally added in by #4852. Also skipped the drag and drop integration test for now, and updated the demo for the test to be more similar to the current [draggable example](https://www.patternfly.org/v4/components/data-list#draggable) (to remove the deprecated props and make it easier for when we come back to refactor the test)
=> chore(DataList): removed deprecated props and logic

packages/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx, packages/react-core/src/components/ClipboardCopy/ClipboardCopyButton.tsx, packages/react-core/src/components/Truncate/Truncate.tsx
**What**: Closes #8368
Adds `removeFindDomNode` opt-in prop to Truncate and ClipboardCopy tooltips, which were missing.
=> feat(ClipboardCopy, Truncate): add removeFindDomNode

packages/react-core/src/components/Pagination/examples/PaginationSticky.tsx
**What**: Closes #7652
To keep the code DRY, I've refactored the build cards functionality.
Also, I've added a logic for when there are less cards in the page than the `perPage` prop.
=> chore(pagination): fixed filter not applying in sticky example

packages/react-core/src/components/Menu/Menu.tsx, packages/react-core/src/components/Menu/examples/Menu.md, packages/react-core/src/components/Menu/examples/MenuFilterDrilldown.tsx
**What**: Closes #6965
Adds a new `shouldFocusOnDrillIn` property to control whether the menu will focus the first option in the list when a drilldown transition happens. This property is used in the demo to prevent re-focusing the first item in the current menu when the list contents change based on the filter state.
Also adds some robustness to the internal keyboard handler props to account for MenuInput (and maintain general menu items and checkbox menu items).
LMK if the demo should remain on the docs page or if this is better off as a codesandbox only demo.
=> feat(Menu): add drilldown filter demo, add flag to support demo & fix some keyboard interaction

packages/react-table/src/components/Table/base/types.tsx, packages/react-table/src/components/TableComposable/Td.tsx, packages/react-table/src/components/TableComposable/Th.tsx, packages/react-table/src/components/TableComposable/examples/ComposableTable.md
**What**: Closes #8322
Allows `Td` to be a sticky column in the same manner as `Th` (testable by swapping the Th for Td in the table body of the sticky column example).
Also adds the disabled and additional properties to `ThSelectType` to match `TdSelectType`, which would let a user keep using `Th` for a select sticky column.
=> feat(Table): add sticky modifiers to Td

packages/react-console/src/components/VncConsole/VncConsole.tsx
The functions that were on the dependency list of the useEffect hook got redefined each time the component got updated, resulting in the component's initialization code, from within the useEffect hook, to be running more than once.
That was unwanted behavior and the useCallback wrappers should prevent it.
Closes #8373
=> fix(VncConsole): prevent running initialization code more than once (#8373)

packages/react-core/src/components/Menu/examples/MenuWithDrilldownBreadcrumbs.tsx
**What**: Closes #7756 
The above issue was mainly fixed by https://github.com/patternfly/patternfly/pull/5271, this PR simply removes an unnecessary li wrapper from an example based on the last comment in the issue
=> fix(Menu): removed li wrapper from breadcrumb example

.github/workflows-src/partials/dist.yml, .github/workflows/pr-preview.yml, .github/workflows/release.yml
**Relates to**: #8438
This change should theoretically lead to the `release/deploy` `Build dist` build step not being skipped due to a cache hit (can see the step was skipped here; https://github.com/patternfly/patternfly-react/actions/runs/3678915968/jobs/6223122730). This will therefore lead to the generation of subpaths anticipated in the referenced, already merged PR.
Changes were made by updating the paths checked in `dist.yml` to determine if there is a cache hit and running `node .github/generate-workflows.js`
=> Update dist.yml to avoid cache hit when subpaths change

packages/react-core/src/components/FileUpload/FileUpload.tsx
`dropzoneProps` appears to have optional and required parameters.
When `dropzoneProps` is not defined in `FileUpload`, the default value is `{}` so I think this prop is intended as additional props on top of what patternfly already used. So not all those props would be used. 
My error: 
```text
Type '{ accept: string; }' is not assignable to type 'DropzoneProps'.
Type '{ accept: string; }' is missing the following properties from type 'Pick<React.HTMLProps<HTMLElement>, PropTypes>': multiple, name, onFocus, onBlur, and 6 more.
```
=> fix(FileUpload): Partial dropzoneProps

packages/react-console/src/components/VncConsole/VncConsole.tsx
In Cockpit machines, we use VNC to show a view of virtual machine.
There is however an issue where if you set Virtual machine system's resolution to something way larger than VNC console shown in the browser, the view will be scaled down, but there will be an offset for mouse:
[false.webm](https://user-images.githubusercontent.com/42733240/209137592-a6bc77ac-d0ea-4f2b-a817-5a962c329fda.webm)
Using dragViewport + clipViewport will allow us to fix this:
[true-(2).webm](https://user-images.githubusercontent.com/42733240/209137676-8a70725e-f81c-4092-88b2-64653485d67d.webm)
https://github.com/cockpit-project/cockpit-machines/issues/29
https://bugzilla.redhat.com/show_bug.cgi?id=2030836
https://bugzilla.redhat.com/show_bug.cgi?id=1913548
=> VncConsole: Introduce RFB clipViewport and dragViewport options

packages/react-core/src/components/Page/examples/Page.md
=> Adds content to page component react examples.

packages/react-core/src/components/SimpleList/SimpleList.tsx, packages/react-core/src/components/SimpleList/__tests__/SimpleList.test.tsx, packages/react-core/src/components/SimpleList/__tests__/__snapshots__/SimpleList.test.tsx.snap
=> fix: aria label added to ungrouped simple list

packages/react-core/src/components/SearchInput/AdvancedSearchMenu.tsx, packages/react-core/src/components/SearchInput/SearchInput.tsx, packages/react-core/src/components/SearchInput/__tests__/SearchInput.test.tsx, packages/react-core/src/components/SearchInput/examples/SearchInput.md, packages/react-core/src/components/SearchInput/examples/SearchInputWithExpandable.tsx
**What**: Part 2 and 3 of #8428 
=> chore(SearchInput): edited ExpandableInput and SearchAttribute

packages/react-core/src/components/LabelGroup/LabelGroup.tsx
**What**: Closes #8495 
Use `React.Children.toArray(children).length` to calculate the label count. So when the label is conditionally rendered it can show the correct count number.
=> fix(LabelGroup): show the correct count of overflow labels

packages/react-core/src/components/NumberInput/NumberInput.tsx, packages/react-core/src/components/NumberInput/__tests__/NumberInput.test.tsx, packages/react-core/src/components/NumberInput/examples/NumberInputCustomStep.tsx, packages/react-core/src/components/NumberInput/examples/NumberInputCustomStepAndThreshold.tsx, packages/react-core/src/components/NumberInput/examples/NumberInputDefault.tsx, packages/react-core/src/components/NumberInput/examples/NumberInputDisabled.tsx, packages/react-core/src/components/NumberInput/examples/NumberInputUnit.tsx, packages/react-core/src/components/NumberInput/examples/NumberInputUnitThreshold.tsx, packages/react-core/src/components/NumberInput/examples/NumberInputVaryingSizes.tsx, packages/react-core/src/components/NumberInput/examples/NumberInputWithStatus.tsx, packages/react-core/src/demos/examples/AlertGroup/AlertGroupToastWithNotificationDrawer.tsx, packages/react-integration/demo-app-ts/src/components/demos/NumberInputDemo/NumberInputDemo.tsx
=> fix(NumberInput): make allowEmptyInput an opt-in prop

packages/react-core/src/components/Tabs/Tabs.tsx
=> feat(Tabs): added event to onAdd callback

packages/react-core/src/components/DatePicker/DatePicker.tsx, packages/react-core/src/components/DatePicker/examples/DatePickerBasic.tsx, packages/react-core/src/components/DatePicker/examples/DatePickerControlled.tsx, packages/react-integration/demo-app-ts/src/components/demos/DatePickerDemo/DatePickerDemo.tsx
**What**: Closes #8424
The onChange fired by `onDateClick` will pass a null event back at the moment because the CalendarMonth callback doesn't give back an event (and is not beta so I think we have to hold off on updating that).
=> feat(Datepicker): add event to callbacks

packages/react-core/src/components/SearchInput/SearchInput.tsx, packages/react-core/src/components/TextInputGroup/TextInputGroupMain.tsx, packages/react-core/src/components/TextInputGroup/examples/TextInputGroupFilters.tsx, packages/react-core/src/components/TextInputGroup/examples/TextInputGroupUtilitiesAndIcon.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableMultipleTypeaheadSelect.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableTypeaheadSelect.tsx, packages/react-core/src/demos/examples/TextInputGroup/AttributeValueFiltering.tsx, packages/react-core/src/demos/examples/TextInputGroup/AutoCompleteSearch.tsx, packages/react-core/src/next/components/Select/examples/SelectMultiTypeahead.tsx, packages/react-core/src/next/components/Select/examples/SelectTypeahead.tsx
=> feat(TextInputGroup): reordered onChange parameters

packages/react-core/src/components/DualListSelector/DualListSelectorPane.tsx, packages/react-core/src/components/DualListSelector/examples/DualListSelector.md, packages/react-core/src/components/DualListSelector/examples/DualListSelectorComposable.tsx, packages/react-core/src/components/DualListSelector/examples/DualListSelectorComposableTree.tsx
**What**: Closes #8080 
The "no results" empty state message is added to the basic composable ([link for convenience](https://patternfly-react-pr-8480.surge.sh/components/dual-list-selector#composable-dual-list-selector)) and composable tree examples ([link for convenience](https://patternfly-react-pr-8480.surge.sh/components/dual-list-selector#composable-with-tree)) when a filter is applied and all the options are being filtered out.
=> fix(DualListSelector): added empty state to composable examples

packages/react-core/src/components/DualListSelector/DualListSelectorPane.tsx, packages/react-core/src/components/DualListSelector/examples/DualListSelectorComposable.tsx, packages/react-core/src/components/DualListSelector/examples/DualListSelectorComposableTree.tsx, packages/react-core/src/components/Menu/examples/MenuFilterDrilldown.tsx, packages/react-core/src/components/Menu/examples/MenuFilteringWithSearchInput.tsx, packages/react-core/src/components/SearchInput/AdvancedSearchMenu.tsx, packages/react-core/src/components/SearchInput/SearchInput.tsx, packages/react-core/src/components/SearchInput/examples/SearchInputAdvanced.tsx, packages/react-core/src/components/SearchInput/examples/SearchInputBasic.tsx, packages/react-core/src/components/SearchInput/examples/SearchInputFocusSearch.tsx, packages/react-core/src/components/SearchInput/examples/SearchInputWithExpandable.tsx, packages/react-core/src/components/SearchInput/examples/SearchInputWithNavigableOptions.tsx, packages/react-core/src/components/SearchInput/examples/SearchInputWithResultCount.tsx, packages/react-core/src/components/SearchInput/examples/SearchInputWithSubmitButton.tsx, packages/react-core/src/components/Toolbar/examples/ToolbarComponentManagedToggleGroups.tsx, packages/react-core/src/components/Toolbar/examples/ToolbarConsumerManagedToggleGroups.tsx, packages/react-core/src/components/Toolbar/examples/ToolbarWithFilters.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableApplicationLauncher.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableContextSelector.tsx, packages/react-core/src/demos/Filters/examples/FilterAttributeSearch.tsx, packages/react-core/src/demos/Filters/examples/FilterSearchInput.tsx, packages/react-core/src/demos/SearchInput/SearchInput.md, packages/react-core/src/demos/Toolbar.md, packages/react-integration/demo-app-ts/src/components/demos/MenuDemo/MenuDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/SearchInputDemo/SearchInputDemo.tsx, packages/react-log-viewer/src/LogViewer/LogViewerSearch.tsx, packages/react-table/src/docs/demos/Table.md
=> chore(SearchInput): reordered props in onChange and onSearch

packages/react-code-editor/README.md, packages/react-code-editor/package.json, packages/react-integration/package.json, yarn.lock
Upgrades `react-monaco-editor` to the latest version (which supports React 18). Works towards closing #7142.
=> chore(react-code-editor): upgrade `react-monaco-editor` to latest version

packages/react-table/src/components/Table/ActionsColumn.tsx, packages/react-table/src/components/Table/Table.tsx, packages/react-table/src/components/Table/TableTypes.tsx, packages/react-table/src/components/Table/base/types.tsx, packages/react-table/src/components/Table/examples/Table.md, packages/react-table/src/components/Table/utils/decorators/cellActions.tsx, packages/react-table/src/components/TableComposable/Td.tsx, packages/react-table/src/components/TableComposable/examples/ComposableTable.md
**What**: Closes #8475
added `actionsMenuAppendTo` to the Table component
added `menuAppendTo` to the TdActionsType for usage in TableComposable
=> chore(Table): added menuAppendTo props to actions tables

packages/react-table/src/components/TableComposable/examples/ComposableTable.md
**What**: fixes this
to show..
=> fix(Table): fix verbiage/formatting in example documentation

packages/react-core/src/components/Select/Select.tsx, packages/react-core/src/components/Select/SelectToggle.tsx, packages/react-core/src/components/Select/examples/Select.md, packages/react-integration/cypress/integration/select.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/SelectDemo/SelectDemo.tsx
**What**: Closes #8478
It looks like the single select variant didn't have support for re-focusing the toggle upon selection. I added the ability to pass in a toggle reference so a user can control when the toggle is focused (typically in the onSelect handler) & updated the related examples. 
Adding the refocus to the Toggle internally is also probably an option but it would be trickier to ensure it fired only the in the right circumstances (currently the toggle handles Tab/Escape because that always closes the menu but with selection, some selects should stay open and not refocus). I can take a crack at making the handling internal if we would rather have that than the external ref though.
=> feat(Select): add toggle ref

packages/react-core/src/components/Menu/Menu.tsx, packages/react-core/src/components/Menu/MenuContext.ts, packages/react-core/src/components/Menu/MenuItem.tsx, packages/react-core/src/components/Menu/examples/MenuFilterDrilldown.tsx, packages/react-core/src/components/Menu/examples/MenuWithDrilldown.tsx, packages/react-core/src/components/Menu/examples/MenuWithDrilldownBreadcrumbs.tsx, packages/react-core/src/components/Menu/examples/MenuWithDrilldownInitialState.tsx, packages/react-core/src/components/Menu/examples/MenuWithDrilldownSubmenuFunctions.tsx, packages/react-core/src/components/Nav/examples/NavDrilldown.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableDrilldownMenu.tsx, packages/react-core/src/demos/examples/Nav/NavDrilldown.tsx, packages/react-integration/demo-app-ts/src/components/demos/MenuDemo/MenuDrilldownDemo.tsx
=> feat(Menu): added event param to onDrillIn and onDrillOut callbacks

packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx, packages/react-integration/cypress/integration/expandablesectiontruncate.ts, packages/react-integration/demo-app-ts/src/Demos.ts, packages/react-integration/demo-app-ts/src/components/demos/ExpandableSectionDemo/ExpandableSectionTruncateDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/index.ts
**What**: Closes #8549
[Expandable section truncate example](https://patternfly-react-pr-8570.surge.sh/components/expandable-section#truncate-expansion)
To test:
1. Add `truncateMaxLines={7}` to the example code as an ExpandableSection prop
2. Notice the toggle no longer renders
3. Resize the window to its minimum width, notice the toggle now renders
4. Resize the window to max size and the toggle no longer renders again
Originally I made the toggle button conditional based only on the expandable content's offset and scroll heights (if there was overflow content, the scrollheight should be greater than the offset and require a toggle). This caused a couple of issues once resizing was taken into account:
- The toggle button would end up being removed if the content was expanded and the …
=> fix(ExpandableSection): made toggle button conditional with truncate variant

packages/react-core/src/components/Alert/Alert.tsx, packages/react-core/src/components/Alert/examples/Alert.md
**What**: Closes https://github.com/patternfly/patternfly-react/issues/8402
deprecates the `titleHeadingLevel`
adds a `component` prop
updates existing examples on the Alert page to avoid new console warnings and advise the use of the component prop.
Created new issue to track the removal of the deprecated titleHeadingLevel prop: https://github.com/patternfly/patternfly-react/issues/8519
=> chore(Alert): Allowed for non header elements to be set at the Alert title

packages/react-core/src/components/Menu/__mocks__/Menu.tsx, packages/react-core/src/components/Menu/__mocks__/MenuContent.tsx, packages/react-core/src/components/Menu/__mocks__/MenuGroup.tsx, packages/react-core/src/components/Menu/__mocks__/MenuItem.tsx, packages/react-core/src/components/Menu/__mocks__/MenuList.tsx, packages/react-core/src/components/Menu/__mocks__/index.ts, packages/react-core/src/helpers/Popper/__mocks__/Popper.tsx, packages/react-core/src/helpers/Popper/__mocks__/index.ts, packages/react-core/src/next/components/Dropdown/__tests__/Dropdown.test.tsx, packages/react-core/src/next/components/Dropdown/__tests__/DropdownGroup.test.tsx, packages/react-core/src/next/components/Dropdown/__tests__/DropdownItem.test.tsx, packages/react-core/src/next/components/Dropdown/__tests__/DropdownList.test.tsx, packages/react-core/src/next/components/Dropdown/__tests__/__snapshots__/Dropdown.test.tsx.snap, packages/react-core/src/next/components/Dropdown/__tests__/__snapshots__/DropdownGroup.test.tsx.snap, packages/react-core/src/next/components/Dropdown/__tests__/__snapshots__/DropdownItem.test.tsx.snap, packages/react-core/src/next/components/Dropdown/__tests__/__snapshots__/DropdownList.test.tsx.snap, packages/react-integration/cypress/integration/dropdownnext.spec.ts, packages/react-integration/demo-app-ts/src/Demos.ts, packages/react-integration/demo-app-ts/src/components/demos/DropdownNextDemo/DropdownNextDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/index.ts
**What**: Closes #7964 
**Additional issues**: #8479 
**Previous PR**: #8446
=> chore(Dropdown next): add testing

packages/react-core/src/components/Menu/MenuItemAction.tsx
=> fix(MenuItemAction): updated aria-label prop to be required

packages/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx, packages/react-core/src/components/ClipboardCopy/__tests__/Generated/ClipboardCopy.test.tsx
=> feat(ClipboardCopy): remove deprecated switchDelay

packages/react-table/src/components/Table/base/types.tsx
**What**: Closes #8330
Changes the `collapseAllAriaLabel` type to `string`. It still defaults to `''` where it is actually used.
If we want to include renaming the `collapseAllAriaLabel` and `areAllExpanded` mentioned in the issue I can add that in to this PR as well, but I'm unsure what to rename them to at the moment.
=> fix(Table): fix ThExpandType label type

packages/react-core/src/components/Icon/Icon.tsx, packages/react-core/src/components/Icon/examples/IconCustomProgress.tsx, packages/react-core/src/components/Spinner/Spinner.tsx, packages/react-core/src/components/Spinner/__tests__/Spinner.test.tsx, packages/react-core/src/components/Spinner/__tests__/__snapshots__/Spinner.test.tsx.snap, packages/react-core/src/components/Spinner/examples/SpinnerBasic.tsx, packages/react-core/src/components/Spinner/examples/SpinnerCustomSize.tsx, packages/react-core/src/components/Spinner/examples/SpinnerInline.tsx, packages/react-core/src/components/Spinner/examples/SpinnerSizeVariations.tsx
=> feat(Spinner): remove legacy variant and svg prop

packages/react-code-editor/src/components/CodeEditor/CodeEditorControl.tsx, packages/react-integration/demo-app-ts/src/components/demos/CodeEditorDemo/CodeEditorDemo.tsx
=> chore(CodeEditorControl): remove deprecated props

packages/react-core/src/components/BackToTop/BackToTop.tsx, packages/react-core/src/components/Button/Button.tsx, packages/react-core/src/components/Menu/MenuGroup.tsx, packages/react-core/src/components/Menu/MenuInput.tsx, packages/react-core/src/components/Menu/MenuItemAction.tsx, packages/react-core/src/components/MenuToggle/MenuToggle.tsx, packages/react-core/src/components/Select/SelectMenu.tsx, packages/react-core/src/components/Tabs/Tab.tsx, packages/react-core/src/components/Tabs/TabContent.tsx, packages/react-core/src/components/TextArea/TextArea.tsx, packages/react-core/src/components/TextInput/TextInput.tsx, packages/react-core/src/components/TextInputGroup/TextInputGroupMain.tsx, packages/react-core/src/components/Toolbar/ToolbarGroup.tsx, packages/react-table/src/components/TableComposable/TableComposable.tsx, packages/react-table/src/components/TableComposable/Tbody.tsx, packages/react-table/src/components/TableComposable/Thead.tsx, packages/react-table/src/components/TableComposable/Tr.tsx
=> fix(innerRefs): hid innerRef props from various component docs

packages/react-core/src/components/Dropdown/DropdownToggleCheckbox.tsx, packages/react-core/src/components/NotificationBadge/NotificationBadge.tsx, packages/react-core/src/components/NotificationBadge/__tests__/NotificationBadge.test.tsx, packages/react-core/src/components/NotificationBadge/__tests__/__snapshots__/NotificationBadge.test.tsx.snap
=> chore(NotificationBadge): remove deprecated isread prop

packages/react-core/src/next/components/Wizard/WizardContext.tsx
=> fix(WizardContext - next): Don't initialize 'currentFooter' to avoid stale props

packages/react-core/src/next/components/Wizard/WizardToggle.tsx
=> fix(Wizard - next): Show parent name instead of child step name as first label when Wizard is in collapsed mode

packages/react-core/src/components/Nav/Nav.tsx, packages/react-core/src/components/Nav/NavItem.tsx, packages/react-core/src/components/Nav/__tests__/Nav.test.tsx, packages/react-core/src/components/Nav/__tests__/__snapshots__/Nav.test.tsx.snap
**What**: Closes #8598 
Convenience link: https://patternfly-react-pr-8628.surge.sh/components/navigation#flyout
=> chore(Nav): appended flyout nav within nav element

packages/react-core/src/components/Menu/MenuItem.tsx, packages/react-core/src/components/TextInputGroup/TextInputGroupMain.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableMultipleTypeaheadSelect.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableTypeaheadSelect.tsx, packages/react-core/src/next/components/Select/examples/SelectMultiTypeahead.tsx, packages/react-core/src/next/components/Select/examples/SelectTypeahead.tsx, packages/react-integration/cypress/integration/menu.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/MenuDemo/MenuDemo.tsx
**What**: Closes #8125 
[Composable typeahead select demo](https://patternfly-react-pr-8633.surge.sh/demos/composable-menu#composable-typeahead-select)
Parts of the linked issue should be resolved by https://github.com/patternfly/patternfly-react/pull/8496 (adding functionality for select menus in Menu components) getting merged into v5 from main, and https://github.com/patternfly/patternfly-react/pull/8623 (placing the menu closer to the toggle in the DOM).
@nicolethoen regarding having options announced, I think one potential caveat of that - either as they type or when the input receives focus - is that it could possibly lead to a very verbose output. In the composable typeahead examples it isn't too bad since they only show a few options, but if the typeahead has dozens of possible …
=> fix(composable typeahead select): updated accessibility

packages/react-core/src/components/Dropdown/DropdownToggleCheckbox.tsx, packages/react-core/src/components/Masthead/MastheadBrand.tsx, packages/react-core/src/components/Masthead/__tests__/Masthead.test.tsx, packages/react-core/src/components/Masthead/__tests__/__snapshots__/Masthead.test.tsx.snap, packages/react-core/src/components/Page/PageHeader.tsx, packages/react-core/src/components/Page/__tests__/PageHeader.test.tsx, packages/react-core/src/components/Page/__tests__/__snapshots__/Page.test.tsx.snap, packages/react-core/src/components/Page/__tests__/__snapshots__/PageHeader.test.tsx.snap
**What**: Closes #4665
Adds logic to component type of Masthead and PageHeader. If an `href` is passed, the component type will be an anchor. If an `onClick` is passed, the type will be a button. Otherwise the type will be a span.
=> feat(Masthead, PageHeader): update component logic

packages/react-core/src/components/Dropdown/DropdownToggleCheckbox.tsx, packages/react-core/src/next/components/Dropdown/Dropdown.tsx, packages/react-core/src/next/components/Select/Select.tsx, packages/react-core/src/next/components/Wizard/WizardContext.tsx, packages/react-core/src/next/components/Wizard/WizardToggle.tsx, packages/react-core/src/next/components/Wizard/utils.ts, packages/react-integration/cypress/integration/tablesimpleactions.spec.ts, packages/react-table/src/components/Table/ActionsColumn.tsx, packages/react-table/src/components/Table/TableTypes.tsx, packages/react-table/src/components/Table/__tests__/__snapshots__/Table.test.tsx.snap, packages/react-table/src/components/Table/examples/LegacyTableActions.tsx, packages/react-table/src/components/Table/utils/decorators/cellActions.tsx, packages/react-table/src/components/TableComposable/examples/ComposableTableActions.tsx
**What**: Closes #8390
- Updates `ActionsColumn` to use Dropdown-next components
- Adds `popperProps` to Dropdown-next to allow customization of Popper (including `direction`, `position`, `popperMatchesTriggerWidth` that is used by `ActionsColumn`). If this would be better as separately piped props let me know and I can update them. But for now this will allow the greatest flexibility.
- Updates examples to use `MenuToggle` for custom toggle
=> feat(Table): update ActionsColumn to use Dropdown next

packages/react-core/src/components/Popover/Popover.tsx, packages/react-core/src/components/Popover/__tests__/__snapshots__/Popover.test.tsx.snap, packages/react-integration/cypress/integration/popover.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/FormDemo/FormDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/PopoverDemo/PopoverDemo.tsx
**What**: Closes #8599
[Popover examples](https://patternfly-react-pr-8621.surge.sh/components/popover)
This results in markup similar to Timepicker (wrapping the Popper in a div internally and appending to that wrapper div). 
=> fix(Popover): updated appendTo to inline by default

packages/react-core/src/demos/ComposableMenu/examples/ComposableActionsMenu.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableApplicationLauncher.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableContextSelector.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableDateSelect.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableDrilldownMenu.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableDropdwnVariants.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableFlyout.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableMultipleTypeaheadSelect.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableOptionsMenuVariants.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableSimpleCheckboxSelect.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableSimpleDropdown.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableSimpleSelect.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableTreeViewMenu.tsx, packages/react-core/src/demos/ComposableMenu/examples/ComposableTypeaheadSelect.tsx
**What**: Closes #8600 
[Composable menu demos](https://patternfly-react-pr-8623.surge.sh/demos/composable-menu)
Moved the `<div ref={containerRef}>` wrapper to the toggle, which is similar to the proposed solution for the "Editable labels with add dropdown" demo in the epic.
Alternatively since all of these demos are setup the same way, we *could* append to `toggleRef.current.parent`, which should always be the wrapper div provided by Popper with `style="display: contents"`:
=> chore(composable menu demos): updated appendTo

packages/react-core/src/components/AboutModal/AboutModal.tsx, packages/react-core/src/components/AboutModal/AboutModalBoxCloseButton.tsx, packages/react-core/src/components/AboutModal/AboutModalContainer.tsx, packages/react-core/src/components/AboutModal/examples/AboutModalBasic.tsx, packages/react-core/src/components/AboutModal/examples/AboutModalComplexUserPositionedContent.tsx, packages/react-core/src/components/AboutModal/examples/AboutModalCustomBackgroundImage.tsx, packages/react-core/src/components/AboutModal/examples/AboutModalWithoutProductName.tsx, packages/react-integration/demo-app-ts/src/components/demos/AboutModal/AboutModalDemo.tsx
=> feat(AboutModal): added event parameter to onClose

packages/react-charts/src/components/ChartLegend/examples/ChartLegend.md, packages/react-charts/src/components/ChartTooltip/examples/ChartTooltip.md
Need to fix two broken legend tooltip examples due to the Tooltip popper outputting a new div tag.
https://github.com/patternfly/patternfly-react/issues/8591
=> Charts - fix broken tooltip examples for v5

packages/react-core/src/components/DatePicker/DatePicker.tsx, packages/react-core/src/components/DatePicker/__tests__/DatePicker.test.tsx, packages/react-core/src/components/DatePicker/__tests__/__snapshots__/DatePicker.test.tsx.snap, packages/react-core/src/helpers/__mocks__/util.ts, packages/react-integration/demo-app-ts/package.json
**What**: Closes #8596 
Convenience link: https://patternfly-react-pr-8636.surge.sh/components/date-picker#basic
=> chore(DatePicker): updated popover to append inline

packages/react-core/src/components/Menu/MenuGroup.tsx, packages/react-integration/demo-app-ts/package.json
remove default titleId prop value, so id is not being set everytime
closes #8162
BREAKING CHANGE
https://github.com/patternfly/patternfly-react/issues/8162
https://www.patternfly.org/v4/components/menu#titled-groups-of-items
=> fix(MenuGroup): do not set id when titleId prop isn't passed

packages/react-table/src/components/Table/ActionsColumn.tsx, packages/react-table/src/components/Table/BodyCell.tsx, packages/react-table/src/components/Table/CollapseColumn.tsx, packages/react-table/src/components/Table/DraggableCell.tsx, packages/react-table/src/components/Table/EditableSelectInputCell.tsx, packages/react-table/src/components/Table/FavoritesCell.tsx, packages/react-table/src/components/Table/HeaderCellInfoWrapper.tsx, packages/react-table/src/components/Table/Table.tsx, packages/react-table/src/components/Table/TableText.tsx, packages/react-table/src/components/Table/TableTypes.tsx, packages/react-table/src/components/Table/base/types.tsx, packages/react-table/src/components/Table/utils/decorators/treeRow.tsx, packages/react-table/src/components/Table/utils/transformers.test.tsx, packages/react-table/src/components/TableComposable/TableComposable.tsx, packages/react-table/src/components/TableComposable/Td.tsx, packages/react-table/src/components/TableComposable/Th.tsx, packages/react-table/src/components/TableComposable/Tr.tsx
This by large avoids importing from the high level export file from
@patternfly/react-core as that exports the whole patternfly react
exported modules, which affects consumers if tree-shaking algorithm does not mark
them as dead code.
Noticed these problematic imports while trying to port our project's build tool to
'esbuild' which created a noticably big dist'ed CSS because of these. [1]
[1] https://github.com/evanw/esbuild/issues/2933
=>  react-table: import from dist/esm like we do in react-core

packages/react-charts/src/components/Chart/Chart.tsx, packages/react-charts/src/components/ChartAxis/ChartAxis.tsx, packages/react-charts/src/components/ChartBullet/ChartBullet.tsx, packages/react-charts/src/components/ChartBullet/ChartBulletGroupTitle.tsx, packages/react-charts/src/components/ChartBullet/ChartBulletTitle.tsx, packages/react-charts/src/components/ChartDonutUtilization/ChartDonutThreshold.tsx, packages/react-charts/src/components/ChartLegend/ChartLegend.tsx, packages/react-charts/src/components/ChartPie/ChartPie.tsx
Ensures chart labels are assigned unique IDs.
ChartAxis examples:
**x-axis label**
- id="chart2-ChartAxis-0-ChartLabel"
**y-axis label**
- id="chart2-ChartAxis-1-ChartLabel"
**Inspector**
Closes https://github.com/patternfly/patternfly-react/issues/8731
=> Charts - add unique IDs to labels

packages/react-charts/src/components/Chart/Chart.tsx, packages/react-charts/src/components/ChartAxis/ChartAxis.tsx, packages/react-charts/src/components/ChartBullet/ChartBullet.tsx, packages/react-charts/src/components/ChartBullet/ChartBulletGroupTitle.tsx, packages/react-charts/src/components/ChartBullet/ChartBulletTitle.tsx, packages/react-charts/src/components/ChartDonutUtilization/ChartDonutThreshold.tsx, packages/react-charts/src/components/ChartLegend/ChartLegend.tsx, packages/react-charts/src/components/ChartPie/ChartPie.tsx
This is a v5 pack port of https://github.com/patternfly/patternfly-react/pull/8732, which ensure labels are assigned unique IDs. 
Closes https://github.com/patternfly/patternfly-react/issues/8739
=> Charts - back port label IDs

packages/react-core/src/components/DataList/DataListItem.tsx
**What**: Closes #8370 
The logic for DataListItem and Tile demos for selecting an item via keyboard look okay on another look. Since the `click` events are on `<div>` elements a Space/Enter keydown won't trigger the click event, so calling an internal function works.
I did update the DataListItem logic to take into account Space key presses, though.
=> fix(DataListItem): made items selectable via space key

packages/react-charts/src/components/ChartLegend/examples/ChartLegend.md, packages/react-charts/src/components/ChartTooltip/examples/ChartTooltip.md
Although the chart's custom tooltip example is working, I'm seeing some warnings in the browser console. Therefore, I've refactored the example to reference `ChartLabel` instead.
Closes https://github.com/patternfly/patternfly-react/issues/8591
=> Charts - fix broken tooltip examples

packages/react-core/src/components/DataList/DataList.tsx, packages/react-core/src/components/DataList/DataListItem.tsx, packages/react-core/src/components/DataList/examples/DataListSelectableRows.tsx, packages/react-integration/demo-app-ts/package.json, packages/react-integration/demo-app-ts/src/components/demos/DataListDemo/DataListCompactDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/DataListDemo/DataListDemo.tsx
**What**: Closes #8719 
Also updated the order of the params for the SelectableRowObject's `onChange`
=> feat(DataList): added event param to callback

packages/react-core/src/components/Menu/MenuContent.tsx, packages/react-integration/demo-app-ts/package.json
**What**: Closes #8180 
All other innerRef props mentioned in the issue were fixed as part of https://github.com/patternfly/patternfly-react/pull/8648
=> fix(Menu): hid innerRef prop from docs

packages/react-core/src/components/Page/__tests__/__snapshots__/Page.test.tsx.snap, packages/react-core/src/components/SkipToContent/SkipToContent.tsx, packages/react-core/src/components/SkipToContent/__tests__/SkipToContent.test.tsx, packages/react-core/src/components/SkipToContent/__tests__/__snapshots__/SkipToContent.test.tsx.snap, packages/react-integration/demo-app-ts/package.json
**What**: Closes #8260
Moves the `pf-c-skip-to-content` class off of the `Button` and onto a div wrapping the `Button`.
=> fix(SkipToContent): Updated markup

packages/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx, packages/react-core/src/components/ClipboardCopy/ClipboardCopyExpanded.tsx
=> feat(ClipboardCopy): added event to onChange prop

packages/react-charts/src/components/Chart/Chart.tsx, packages/react-charts/src/components/ChartBullet/ChartBullet.tsx, packages/react-charts/src/components/ChartBullet/examples/ChartBullet.md, packages/react-charts/src/components/ChartDonut/ChartDonut.tsx, packages/react-charts/src/components/ChartDonutUtilization/ChartDonutUtilization.tsx, packages/react-charts/src/components/ChartLegend/examples/ChartLegend.md, packages/react-charts/src/components/ChartPie/ChartPie.tsx, packages/react-charts/src/components/ChartUtils/chart-legend.ts, packages/react-charts/src/components/Patterns/examples/patterms.md, packages/react-charts/src/components/ResizeObserver/examples/resizeObserver.md
Added an optional callback to compliment the chart's `legendAllowWrap` property. The `legendAllowWrapCallback` prop will be used to adjust the chart's parent container `height` as legend items wrap in response to the available `width`.
Example:
Closes https://github.com/patternfly/patternfly-react/issues/8643
=> Charts - add legendAllowWrap callback

packages/react-core/package.json, packages/react-core/src/components/Popover/PopoverHeader.tsx, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-integration/cypress/integration/form.spec.ts, packages/react-integration/cypress/integration/label.spec.ts, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
=> fix(core): update core to alpha.24

packages/react-core/src/components/DataList/DataListCheck.tsx, packages/react-core/src/components/DataList/__tests__/Generated/DataListCheck.test.tsx, packages/react-table/src/docs/demos/Table.md, packages/react-table/src/docs/demos/table-demos/ColumnManagement.jsx
=> fix(DataListCheck): updated onChange param order

packages/react-topology/src/components/ElementWrapper.tsx, packages/react-topology/src/elements/BaseElement.ts, packages/react-topology/src/types.ts
**What**: Closes https://github.com/patternfly/patternfly-react/issues/8659
This solution skip `Elements` rendering when controller is not available.
Cola animation `tick` schedule mobx observer update and controller is destroyed in between so I was not able to skip the [update action from ColaLayout](https://github.com/patternfly/patternfly-react/blob/main/packages/react-topology/src/layouts/ColaLayout.ts#L66).
=> fix(Topology) Cola animation makes page crash on layout change

packages/react-table/src/components/TableComposable/Td.tsx, packages/react-table/src/components/TableComposable/Th.tsx, packages/react-table/src/components/TableComposable/examples/ComposableTable.md, packages/react-table/src/components/TableComposable/examples/ComposableTableRightStickyColumn.tsx
**What**: Closes #8632
Currently setting the `right` property manually. Will be updated to set `--pf-c-table__sticky-column--Right` after https://github.com/patternfly/patternfly/pull/5393 is merged and rebased in.
=> feat(Table): add right sticky column support

packages/react-core/src/components/Chip/Chip.tsx, packages/react-core/src/components/Chip/__tests__/__snapshots__/Chip.test.tsx.snap, packages/react-core/src/components/ChipGroup/__tests__/__snapshots__/ChipGroup.test.tsx.snap, packages/react-core/src/components/Label/Label.tsx, packages/react-core/src/components/Label/__tests__/__snapshots__/Label.test.tsx.snap, packages/react-core/src/components/Select/__tests__/__snapshots__/Select.test.tsx.snap, packages/react-core/src/components/Toolbar/__tests__/__snapshots__/Toolbar.test.tsx.snap, packages/react-integration/cypress/integration/chipgroup.spec.ts, packages/react-integration/cypress/integration/chipgroupdefaultisopen.spec.ts
=> fix(Chip/Label): update structure to work with core updates

packages/react-core/src/components/Label/Label.tsx, packages/react-core/src/components/Label/__tests__/Label.test.tsx, packages/react-core/src/components/Label/__tests__/__snapshots__/Label.test.tsx.snap, packages/react-core/src/components/Label/examples/LabelCompact.tsx, packages/react-core/src/components/Label/examples/LabelFilled.tsx, packages/react-core/src/components/Label/examples/LabelOutline.tsx, packages/react-core/src/components/Label/examples/LabelRouterLink.tsx, packages/react-core/src/components/LabelGroup/__tests__/__snapshots__/LabelGroup.test.tsx.snap, packages/react-integration/cypress/integration/label.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/LabelDemo/LabelDemo.tsx
**What**: Closes #8258 
Labels: https://patternfly-react-pr-8771.surge.sh/components/label
=> feat(Label): truncate by default

.github/workflows-src/partials/install.yml, .github/workflows/pr-preview.yml, .github/workflows/release.yml, packages/react-docs/package.json, yarn.lock
=> chore(CI): updated node version used for gh actions

packages/react-core/src/components/ContextSelector/ContextSelectorItem.tsx
Changes the type definition of `ContextSelectorItemProps` so that the `onClick`, `index` and `sendRef` props are no longer required. Default values are [already provided ](https://github.com/jonkoops/patternfly-react/blob/280682c003d1292656d95f9d97744eed6bc596aa/packages/react-core/src/components/ContextSelector/ContextSelectorItem.tsx#L29-L31)for these props, so this type was simply wrong.
=> Fix type definition for `ContextSelectorItemProps`

packages/react-core/src/components/Popover/PopoverCloseButton.tsx, packages/react-core/src/components/Popover/PopoverHeader.tsx, packages/react-core/src/components/Popover/PopoverHeaderText.tsx, packages/react-core/src/components/Popover/__tests__/Generated/__snapshots__/PopoverCloseButton.test.tsx.snap, packages/react-core/src/components/Popover/__tests__/Generated/__snapshots__/PopoverHeader.test.tsx.snap, packages/react-integration/cypress/integration/popover.spec.ts
=> fix(Popover): Refactor popover header

package.json
=> chore(tests) fixate time format

packages/react-core/src/components/Timestamp/__tests__/Timestamp.test.tsx, packages/react-core/src/components/Timestamp/__tests__/__snapshots__/Timestamp.test.tsx.snap, packages/react-docs/package.json, packages/react-docs/startDevServer.sh
**What**: For followup issues from #8766
=> fix(tests, scripts): fixed dev server issues/tests related to node 18

packages/react-topology/src/pipelines/components/nodes/TaskNode.tsx
**What**: 
Closes https://github.com/patternfly/patternfly-react/issues/8780
Allows customization of the tooltip on a TaskNode by passing along TooltipProps.
=> fix(topology): Allow tooltip customization on TaskNode

package.json, packages/react-core/CONTRIBUTING.md
**What**: Closes https://github.com/patternfly/patternfly-react/issues/8690
=> fix(test): update script

packages/react-core/src/components/Select/examples/Select.md
=> Adds content to select component examples.

packages/react-core/src/components/Timestamp/__tests__/Timestamp.test.tsx
=> chore(timestamp test): disable failing snapshot test

packages/react-core/src/components/Alert/Alert.tsx, packages/react-core/src/components/Alert/__tests__/Alert.test.tsx
=> fix(Alert): remove deprecated titleHeadingLevel prop

packages/react-charts/package.json, packages/react-code-editor/README.md, packages/react-code-editor/package.json, packages/react-core/package.json, packages/react-docs/UPGRADE-GUIDE.md, packages/react-icons/package.json, packages/react-table/package.json
=> chore(deps):Removed react 16 support

packages/react-core/src/components/Modal/ModalBoxCloseButton.tsx, packages/react-core/src/components/Modal/__tests__/__snapshots__/ModalContent.test.tsx.snap, packages/react-core/src/components/Timestamp/__tests__/__snapshots__/Timestamp.test.tsx.snap
**What**: Closes https://github.com/patternfly/patternfly-react/issues/8687
=> fix(Modal): Add close button wrapper div

packages/react-core/src/components/DataList/DataList.tsx, packages/react-core/src/components/DataList/DataListItem.tsx, packages/react-core/src/components/DataList/__tests__/DataList.test.tsx, packages/react-core/src/components/DataList/examples/DataList.md, packages/react-core/src/components/DataList/examples/DataListSelectableRows.tsx
**What**: Closes https://github.com/patternfly/patternfly-react/issues/8423
=> fix(DataList):removed Selectable row object

packages/react-core/package.json, packages/react-core/src/components/DatePicker/DatePicker.tsx, packages/react-core/src/components/TimePicker/TimePicker.tsx, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-integration/cypress/integration/datepicker.spec.ts, packages/react-styles/package.json, packages/react-table/src/components/TableComposable/Td.tsx, packages/react-table/src/components/TableComposable/Th.tsx, packages/react-tokens/package.json, yarn.lock
closes: #8831 
Bump core version
=> chore(deps): Bump core version

packages/react-core/src/components/Drawer/DrawerPanelContent.tsx
**What**: Closes #8510
can be tested by replacing `packages/react-core/src/components/Drawer/examples/DrawerStackedContentBodyElements.tsx` with: https://codesandbox.io/s/drawerstackedcontentbodyelements-t8v58c?file=/index.tsx
and seeing that `onExpand` counter is not growing when `Show more` is clicked
=> fix(Drawer): expand only onTransitionEnd of the drawer

packages/react-integration/cypress/integration/menu.spec.ts, packages/react-integration/demo-app-ts/src/App.test.tsx, packages/react-integration/demo-app-ts/src/index.tsx
Works towards closing #7142. More information can be found in the React 18 [migration guide](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis).
=> Switch to `createRoot` API for rendering

packages/react-core/src/components/Banner/Banner.tsx, packages/react-core/src/components/Banner/__tests__/Banner.test.tsx, packages/react-core/src/components/Banner/examples/BannerBasic.tsx, packages/react-core/src/components/Banner/examples/BannerStatus.tsx
=> feat(Banner): updated variants to colors

packages/react-core/src/components/Dropdown/DropdownToggleCheckbox.tsx, packages/react-core/src/components/Dropdown/__tests__/DropdownToggleCheckbox.test.tsx, packages/react-core/src/components/Dropdown/examples/DropdownSplitButtonProgressCheckbox.tsx
=> fix(DropdownToggleCheckbox): updated onChange param order

packages/react-core/src/components/DualListSelector/DualListSelectorListItem.tsx
=> chore(DualListSelectorListItem) change the parameter name from e to event in onOptionSelect

packages/react-core/src/components/DualListSelector/DualListSelector.tsx, packages/react-core/src/components/DualListSelector/DualListSelectorPane.tsx, packages/react-core/src/components/DualListSelector/examples/DualListSelectorBasic.tsx, packages/react-core/src/components/DualListSelector/examples/DualListSelectorBasicSearch.tsx, packages/react-core/src/components/DualListSelector/examples/DualListSelectorBasicTooltips.tsx, packages/react-core/src/components/DualListSelector/examples/DualListSelectorTreeExample.tsx, packages/react-integration/demo-app-ts/src/components/demos/DualListSelectorDemo/DualListSelectorBasicDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/DualListSelectorDemo/DualListSelectorTreeDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/DualListSelectorDemo/DualListSelectorWithActionsDemo.tsx
**What**: Closes #8786
Changed props: onAvailableOptionsSearchInputChange, onChosenOptionsSearchInputChanged, onListChange, onOptionCheck, onOptionSelect
=> chore(DualListSelector) verify selected params have event param in the first place

packages/react-table/src/components/Table/ActionsColumn.tsx, packages/react-table/src/components/Table/TableTypes.tsx
**What**: Closes #8709 
Adds `tooltip` and `tooltipProps` to `IAction` and `ActionsColumn` to match the old Dropdown's functionality for tooltip use. Kept the `isSeparator` flag as that was not a flag for the dropdown specifically but for the ActionsColumn to render a divider. 
We could probably refactor ActionsColumn to more directly use `Menu` or Dropdown-next instead of passing data and mapping that to the components if we wanted, but I kept the API the same for now.
=> feat(Table): allow action tooltip

package.json, yarn.lock
=> chore(deps): Update babel dependencies

packages/react-core/src/components/Modal/Modal.tsx, packages/react-core/src/components/Modal/ModalBox.tsx, packages/react-core/src/components/Modal/ModalContent.tsx
=> fix(Modal): updated position prop to have 'default' option

packages/react-core/src/components/Progress/ProgressContainer.tsx, packages/react-core/src/components/Progress/__tests__/__snapshots__/Progress.test.tsx.snap
=> fix(Progress): prevented empty elements from rendering

packages/react-core/package.json, packages/react-core/scripts/copyStyles.js, packages/react-core/src/components/BackgroundImage/BackgroundImage.tsx, packages/react-core/src/components/BackgroundImage/__tests__/__snapshots__/BackgroundImage.test.tsx.snap, packages/react-core/src/components/Icon/Icon.tsx, packages/react-core/src/components/Icon/__tests__/Icon.test.tsx, packages/react-core/src/components/Icon/examples/IconStatus.tsx, packages/react-core/src/components/LoginPage/__tests__/__snapshots__/LoginPage.test.tsx.snap, packages/react-core/src/components/Modal/ModalContent.tsx, packages/react-core/src/components/NotificationDrawer/NotificationDrawerListItem.tsx, packages/react-core/src/components/NotificationDrawer/__tests__/__snapshots__/NotificationDrawerListItem.test.tsx.snap, packages/react-core/src/components/Popover/Popover.tsx, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-integration/cypress/integration/notificationdrawerbasic.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/MastheadDemo/MastheadDemo.tsx, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
=> chore(deps): Bump core to 5.0.0-alpha.37

packages/react-core/src/components/Dropdown/Dropdown.tsx, packages/react-core/src/components/Menu/MenuItem.tsx, packages/react-core/src/components/Menu/examples/Menu.md
=> fix(Menu/Dropdown): updated external link and focus management

packages/react-core/src/components/Nav/NavExpandable.tsx
=> chore(NavExpandable): Change e to event in onExpand

packages/react-core/src/demos/Filters/examples/FilterAttributeSearch.tsx, packages/react-core/src/demos/Filters/examples/FilterCheckboxSelect.tsx, packages/react-core/src/demos/Filters/examples/FilterFaceted.tsx, packages/react-core/src/demos/Filters/examples/FilterMixedSelectGroup.tsx, packages/react-core/src/demos/Filters/examples/FilterSameSelectGroup.tsx, packages/react-core/src/demos/Filters/examples/FilterSearchInput.tsx, packages/react-core/src/demos/Filters/examples/FilterSingleSelect.tsx, packages/react-integration/demo-app-ts/src/components/demos/TableDemo/TableComposableDemo.tsx, packages/react-table/src/components/Table/Td.tsx, packages/react-table/src/components/Table/base/types.tsx, packages/react-table/src/components/Table/examples/TableSelectable.tsx, packages/react-table/src/components/Table/examples/TableSelectableRadio.tsx
**What**: Closes #8419
codemod issue follows: https://github.com/patternfly/pf-codemods/issues/347
=> fix(Table): rename TdSelectType 'disable' prop to 'isDisabled'

packages/react-core/src/components/DatePicker/DatePicker.tsx, packages/react-core/src/components/DatePicker/examples/DatePickerHelperText.tsx, packages/react-core/src/components/TimePicker/TimePicker.tsx
**What**: Closes #8457 
Updates Datepicker and Timepicker to use `HelperText` internally. For `Datepicker`, if the passed `helperText` is a node it will directly render the node instead of wrapping it to allow a user to manually pass a `HelperText`.
=> feat(Datepicker, Timepicker): use HelperText

packages/react-core/src/components/Alert/examples/Alert.md, packages/react-core/src/components/Breadcrumb/examples/BreadcrumbBasic.tsx, packages/react-core/src/components/Button/examples/ButtonVariations.tsx, packages/react-core/src/components/Card/examples/CardBasic.tsx, packages/react-core/src/components/Dropdown/examples/DropdownBasic.tsx, packages/react-core/src/components/FormSelect/examples/FormSelectBasic.tsx, packages/react-core/src/components/Modal/examples/ModalBasic.tsx, packages/react-core/src/components/Nav/examples/NavDefault.tsx, packages/react-core/src/components/Pagination/examples/PaginationTop.tsx, packages/react-core/src/components/Select/examples/Select.md, packages/react-core/src/components/Switch/examples/SwitchBasic.tsx, packages/react-core/src/deprecated/components/ContextSelector/examples/ContextSelectorBasic.tsx, packages/react-core/src/deprecated/components/OptionsMenu/examples/OptionsMenu.md, packages/react-table/src/components/Table/examples/TableSortable.tsx
=> Add OUIA IDs for some components testing page

packages/react-charts/package.json, packages/react-charts/src/components/ChartBoxPlot/ChartBoxPlot.test.tsx, packages/react-charts/src/components/ChartBoxPlot/ChartBoxPlot.tsx, packages/react-charts/src/components/ChartBoxPlot/__snapshots__/ChartBoxPlot.test.tsx.snap, packages/react-charts/src/components/ChartBoxPlot/examples/ChartBoxPlot.md, packages/react-charts/src/components/ChartLegendTooltip/ChartLegendTooltip.tsx, packages/react-charts/src/components/ChartLegendTooltip/ChartLegendTooltipContent.tsx, packages/react-charts/src/components/ChartLegendTooltip/ChartLegendTooltipLabel.tsx, packages/react-charts/src/components/ChartTheme/ChartStyles.ts, packages/react-charts/src/components/ChartTheme/examples/ChartTheme.md, packages/react-charts/src/components/ChartTheme/styles/box-plot-tooltip-styles.ts, packages/react-charts/src/components/ChartTheme/themes/color-theme.ts, packages/react-charts/src/components/ChartTooltip/examples/ChartTooltip.md, packages/react-charts/src/components/ChartUtils/chart-tooltip.ts, packages/react-charts/src/components/index.ts, yarn.lock
Created a component to wrap the Victory box plot chart with PatternFly styles and tooltip functionality.
Closes https://github.com/patternfly/patternfly-react/issues/8837
=> Charts: box plot

packages/react-core/src/components/Sidebar/Sidebar.tsx, packages/react-core/src/components/Sidebar/SidebarContent.tsx, packages/react-core/src/components/Sidebar/SidebarPanel.tsx, packages/react-core/src/components/Sidebar/__tests__/Sidebar.test.tsx, packages/react-core/src/components/Sidebar/__tests__/SidebarContent.test.tsx, packages/react-core/src/components/Sidebar/__tests__/SidebarPanel.test.tsx, packages/react-core/src/components/Sidebar/examples/Sidebar.md, packages/react-core/src/components/Sidebar/examples/SidebarBorder.tsx, packages/react-core/src/components/Sidebar/examples/SidebarPaddingContent.tsx, packages/react-core/src/components/Sidebar/examples/SidebarPaddingPanel.tsx
**What**: Closes #8253
Adds `hasBorder` to `Sidebar`.
Adds `hasPadding` to `SidebarPanel` and `SidebarContent`.
Adds examples & tests.
=> feat(Sidebar): add border and padding

packages/react-core/src/demos/NotificationDrawer/NotificationDrawer.md, packages/react-core/src/demos/examples/AlertGroup/AlertGroupToastWithNotificationDrawer.tsx
**What**: Closes #8797 
Checked all other full page demos and they look fine
=> docs full page mastheads toolbar formatting fix

packages/react-core/src/components/Dropdown/DropdownItem.tsx
**What**: Closes #8509
Adds `isDisabled` and `onClick` props to `DropdownItem` prop table since they are used in the examples.
=> feat(DropdownItem): add missing props to prop table

packages/react-core/package.json, packages/react-core/src/components/Form/FormContext.tsx, packages/react-core/src/components/Form/__tests__/FormContext.test.tsx, packages/react-core/src/components/Form/examples/Form.md, packages/react-core/src/components/Form/examples/FormState.tsx, packages/react-core/src/components/Form/index.ts, packages/react-docs/package.json
=> feat(FormContext): Add context for Form to manage input state

packages/react-core/src/components/LabelGroup/examples/LabelGroupEditableAddModal.tsx, packages/react-core/src/components/Modal/Modal.tsx, packages/react-core/src/components/Modal/ModalBoxCloseButton.tsx, packages/react-core/src/components/Modal/ModalContent.tsx, packages/react-core/src/components/Modal/examples/ModalBasic.tsx, packages/react-core/src/components/Modal/examples/ModalCustomHeaderFooter.tsx, packages/react-core/src/components/Modal/examples/ModalCustomTitleIcon.tsx, packages/react-core/src/components/Modal/examples/ModalCustomWidth.tsx, packages/react-core/src/components/Modal/examples/ModalLarge.tsx, packages/react-core/src/components/Modal/examples/ModalMedium.tsx, packages/react-core/src/components/Modal/examples/ModalNoHeaderFooter.tsx, packages/react-core/src/components/Modal/examples/ModalSmall.tsx, packages/react-core/src/components/Modal/examples/ModalTitleIcon.tsx, packages/react-core/src/components/Modal/examples/ModalTopAligned.tsx, packages/react-core/src/components/Modal/examples/ModalWithDescription.tsx, packages/react-core/src/components/Modal/examples/ModalWithDropdown.tsx, packages/react-core/src/components/Modal/examples/ModalWithForm.tsx, packages/react-core/src/components/Modal/examples/ModalWithHelp.tsx, packages/react-core/src/components/Modal/examples/ModalWithOverflowingContent.tsx, packages/react-core/src/components/Modal/examples/ModalWithWizard.tsx, packages/react-core/src/demos/DatePicker/examples/DateTimePickerInModal.tsx, packages/react-core/src/deprecated/components/Wizard/examples/WizardInModal.tsx, packages/react-integration/demo-app-ts/src/components/demos/ModalDemo/ModalDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/SelectDeprecatedDemo/SelectInModal.tsx, packages/react-table/src/docs/demos/Table.md, packages/react-table/src/docs/demos/table-demos/ColumnManagement.jsx
=> feat(Modal): added event to onClose

packages/react-core/src/components/Radio/Radio.tsx, packages/react-core/src/components/Radio/__tests__/Radio.test.tsx, packages/react-core/src/deprecated/components/Wizard/examples/Wizard.md, packages/react-integration/demo-app-ts/src/App.tsx, packages/react-integration/demo-app-ts/src/components/demos/RadioDemo/RadioDemo.tsx
=> fix(Radio): updated param order for onChange

packages/react-core/src/components/FileUpload/FileUpload.tsx, packages/react-core/src/components/FileUpload/FileUploadField.tsx, packages/react-core/src/components/FileUpload/examples/FileUploadCustomUpload.tsx, packages/react-core/src/components/FileUpload/examples/FileUploadSimpleText.tsx, packages/react-core/src/components/FileUpload/examples/FileUploadTextWithEdits.tsx, packages/react-core/src/components/FileUpload/examples/FileUploadTextWithRestrictions.tsx
=> feat(FileUpload): added event to onTextChange

packages/react-table/src/components/Table/Td.tsx, packages/react-table/src/components/Table/Th.tsx, packages/react-table/src/components/Table/examples/Table.md
**What**: Closes #8829
Updated table sticky feature to use the updated CSS variables, and set the default of the offset variables to 0. This means that both left and right will be set by default, but it shouldn't interfere with the sticky alignment. The alternative is to require that `stickyRightOffset` and `stickyLeftOffset` be set even for the first/last sticky columns with a 0 value.
=> fix(Table): update sticky css props

packages/react-core/src/components/FileUpload/FileUpload.tsx
**What**: Closes #8969
Before the fix, in fileupload examples, clicking on browse would open 2 file upload dialogs and after selecting a file the file name will not be shown.
onFileInputChange should also be called when a file is browsed and not only on drop, event is null on browse upload.
adding noClick as suggested in the react-dropzone docs:
> If you bind a click event on an inner element and use open(), it will trigger a click on the root element too, resulting in the file dialog opening twice. To prevent this, use the noClick on the root
=> Bug - Fileupload - Fix browse

packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx, packages/react-core/src/components/ExpandableSection/examples/ExpandableSectionBasic.tsx, packages/react-core/src/components/ExpandableSection/examples/ExpandableSectionCustomToggle.tsx, packages/react-core/src/components/ExpandableSection/examples/ExpandableSectionDisclosure.tsx, packages/react-core/src/components/ExpandableSection/examples/ExpandableSectionIndented.tsx, packages/react-core/src/components/ExpandableSection/examples/ExpandableSectionTruncateExpansion.tsx, packages/react-integration/demo-app-ts/src/components/demos/ExpandableSectionDemo/ExpandableSectionDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/ExpandableSectionDemo/ExpandableSectionTruncateDemo.tsx
=> feat(ExpandableSection): Add event to onToggle

packages/react-core/src/components/FileUpload/FileUpload.tsx, packages/react-core/src/components/FileUpload/examples/FileUploadSimpleText.tsx, packages/react-core/src/components/FileUpload/examples/FileUploadTextWithEdits.tsx, packages/react-core/src/components/FileUpload/examples/FileUploadTextWithRestrictions.tsx, packages/react-integration/demo-app-ts/src/components/demos/FileUploadDemo/FileUploadDemo.tsx
**What**: Closes #8881
The `onTextChange` cb was already updated as part of #8955
=> feat(FileUpload): added event params to callbacks

packages/react-core/src/components/Form/examples/FormHorizontal.tsx, packages/react-core/src/components/FormSelect/FormSelect.tsx, packages/react-core/src/components/FormSelect/__tests__/FormSelect.test.tsx, packages/react-core/src/components/FormSelect/examples/FormSelectBasic.tsx, packages/react-core/src/components/FormSelect/examples/FormSelectDisabled.tsx, packages/react-core/src/components/FormSelect/examples/FormSelectGrouped.tsx, packages/react-core/src/components/FormSelect/examples/FormSelectIconSpriteVariant.tsx, packages/react-core/src/components/FormSelect/examples/FormSelectValidated.tsx
=> fix(FormSelect): updated order of onChange params

packages/react-core/src/components/NotificationDrawer/NotificationDrawerHeader.tsx, packages/react-core/src/components/NotificationDrawer/examples/NotificationDrawerBasic.tsx, packages/react-core/src/components/NotificationDrawer/examples/NotificationDrawerLightweight.tsx, packages/react-core/src/demos/NotificationDrawer/NotificationDrawer.md, packages/react-core/src/demos/examples/AlertGroup/AlertGroupToastWithNotificationDrawer.tsx, packages/react-integration/demo-app-ts/src/components/demos/NotificationDrawerDemo/NotificationDrawerBasicDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/NotificationDrawerDemo/NotificationDrawerGroupsDemo.tsx
=> chore(NotificationDrawerHeader): add event param to onClose

packages/react-core/src/components/Drawer/Drawer.tsx, packages/react-core/src/components/Drawer/DrawerPanelContent.tsx, packages/react-core/src/components/Page/Page.tsx, packages/react-core/src/demos/Nav.md, packages/react-core/src/demos/NotificationDrawer/NotificationDrawer.md, packages/react-core/src/demos/examples/DashboardWrapper.js
=> chore(Page): add event param to onNotificationDrawerExpand and onPageResize. 

packages/react-core/src/components/MultipleFileUpload/MultipleFileUpload.tsx, packages/react-core/src/components/MultipleFileUpload/examples/MultipleFileUpload.md, packages/react-core/src/components/MultipleFileUpload/examples/MultipleFileUploadBasic.tsx, packages/react-core/src/demos/examples/MultipleFileUpload/MultipleFileUploadRejectedFile.tsx
=> feat(MultiFileUpload): added event param to onFileDrop

packages/react-core/src/components/OverflowMenu/examples/OverflowMenuBreakpointOnContainer.tsx, packages/react-core/src/components/Slider/Slider.tsx, packages/react-core/src/components/Slider/examples/Slider.md, packages/react-core/src/components/Slider/examples/SliderActions.tsx, packages/react-core/src/components/Slider/examples/SliderContinuous.tsx, packages/react-core/src/components/Slider/examples/SliderDisabled.tsx, packages/react-core/src/components/Slider/examples/SliderDiscrete.tsx, packages/react-core/src/components/Slider/examples/SliderThumbValueInput.tsx, packages/react-core/src/components/Slider/examples/SliderValueInput.tsx, packages/react-integration/demo-app-ts/src/components/demos/SliderDemo/SliderDemo.tsx
=> fix(Slider): added event param to onChange

packages/react-table/src/docs/demos/Table.md
=> chore(Table): updated Empty State react demos to use composable table

packages/react-core/src/components/Tabs/examples/Tabs.md
=> Adds content to tabs component examples.

packages/react-core/src/demos/SearchInput/SearchInput.md
**What**: Closes #8941
One of the demos needed the prop update, the other actually had the onChange updated via an anonymous function but changed that to update the actual function signature for consistency.
=> fix(SearchInput demos): add event

packages/react-core/src/demos/examples/DashboardWrapper.js
=> fix(DashboardWrapper): updated passing of onPageResize

packages/react-core/src/components/Popover/Popover.tsx
**What**: Closes #8929 
Notes:
- I did not add an event to `onMount` as that is only fired when the component first renders, which will not have an event associated with it
- I did not add an event to `onHidden` or `onShown` as it would just be a repeat of the `onHide` or `onShow` events which were already sent to the consumer
- The `show` and `hide` functions have the event as an optional param since they are also called by a useEffect when the Popover is being manually controlled by `isVisible`. During this manual operation there are no events to be sent to the consumer, and the consumer would be receiving those events outside of the Popover.
=> feat(Popover): added event to onHide and onShow callback params

packages/react-core/src/demos/Page.md
**What**: Closes #8873
Removes the note about setting height on ancestor elements of Page as this is now the default behavior via CSS.
=> docs(Page): remove height note

packages/react-core/src/components/Dropdown/Dropdown.tsx, packages/react-core/src/components/Dropdown/DropdownGroup.tsx, packages/react-core/src/components/Dropdown/DropdownItem.tsx, packages/react-core/src/components/Dropdown/examples/Dropdown.md, packages/react-core/src/components/Dropdown/examples/DropdownBasic.tsx, packages/react-core/src/components/Dropdown/examples/DropdownWithDescriptions.tsx, packages/react-core/src/components/Dropdown/examples/DropdownWithGroups.tsx, packages/react-core/src/components/Dropdown/examples/DropdownWithKebabToggle.tsx
**What**: Closes #8985
- Fixes Tab/Esc focusing the toggle
- Fixes selection focusing the toggle by passing through the toggle ref to allow a user to control the behavior. While there are less use cases of a dropdown needing to remain open after selection (unlike select which has multiple selection or typeahead), the user still controls whether the menu should stay open and if they decided to keep the menu open an internal toggle focus would be unexpected.
- Adds a similar popper props structure that select got in the related #8992 PR
=> feat(Dropdown): fix focusing, add popper props

packages/react-table/src/docs/demos/Table.md
=> chore(table demos):  update auto pagination demo from deprecated to new table

packages/react-table/src/docs/demos/Table.md
=> chore(table demos): update filterable demo from deprecated to new table

packages/react-core/src/components/Badge/Badge.tsx, packages/react-core/src/components/Badge/__tests__/Badge.test.tsx, packages/react-core/src/components/CalendarMonth/CalendarMonth.tsx, packages/react-core/src/components/Card/Card.tsx, packages/react-core/src/components/DataList/DataListItem.tsx, packages/react-core/src/components/DataList/examples/DataList.md, packages/react-core/src/components/DataList/examples/DataListClickableRows.tsx, packages/react-core/src/components/DataList/examples/DataListDraggable.tsx, packages/react-core/src/components/DatePicker/__tests__/__snapshots__/DatePicker.test.tsx.snap, packages/react-core/src/components/MultipleFileUpload/MultipleFileUploadStatusItem.tsx, packages/react-core/src/components/MultipleFileUpload/__tests__/__snapshots__/MultipleFileUploadStatusItem.test.tsx.snap, packages/react-core/src/demos/ProgressDemo.md, packages/react-core/src/demos/ProgressStepperDemo.md, packages/react-integration/demo-app-ts/src/components/demos/DataListDemo/DataListDraggableDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/TableDemo/TableRowClickDemo.tsx, packages/react-table/src/components/Table/RowWrapper.tsx, packages/react-table/src/components/Table/Table.tsx, packages/react-table/src/components/Table/TableTypes.tsx, packages/react-table/src/components/Table/Tr.tsx, packages/react-table/src/components/Table/examples/Table.md, packages/react-table/src/components/Table/examples/TableClickable.tsx, packages/react-table/src/deprecated/components/Table/examples/LegacyTableClickable.tsx, packages/react-table/src/deprecated/components/Table/examples/Table.md
**What**: Closes https://github.com/patternfly/patternfly-react/issues/9001
This is clean up after core work: https://github.com/patternfly/patternfly/pull/5397
basically, hoverable classnames for DataList and Table have been changed to clickable. 
Changes here:
- updated the relevant Datalist, Table, Deprecated table example titles to match the corresponding core titles.
- changed the table's `isHoverable` prop to `isClickable`
=> fix(DataList, Table): update hoverable reference to clickable

.github/renovate.json, package.json, packages/react-core/src/components/Wizard/hooks/__tests__/useWizardFooter.test.tsx, yarn.lock
**What**: towards #8003 
Removed @testing-library/react-hooks dependencies as it does not support react 18.  support for render hook as been added to @testing-library/react.
=> chore(deps): Removed @testing-library/react-hooks dep

packages/react-core/src/components/Dropdown/DropdownItem.tsx, packages/react-core/src/demos/examples/DashboardWrapper.js, packages/react-core/src/demos/examples/Tabs/TabsAndTable.tsx, packages/react-table/src/components/Table/ActionsColumn.tsx
**What**: Closes #9017 
Convenience link: https://patternfly-react-pr-9093.surge.sh/components/tabs/react-demos/tables-and-tabs/
=> fix(Tabs): fixed keyboard use and positioning of TabsAndTable dropdowns

packages/react-core/src/helpers/Popper/Popper.tsx
**What**: Closes #9012 
This should resolve the recent visual bug for now. Opened #9089 for investigating an alternate solution.
=> fix(Popper): prevented forceUpdate from firing when not necessary

packages/react-core/src/demos/Card/Card.md, packages/react-core/src/demos/Card/CardData.jsx, packages/react-core/src/demos/PrimaryDetail.md
=> chore(Card): Add card data to fix card view demos

packages/react-core/src/layouts/Flex/Flex.tsx, packages/react-core/src/layouts/Flex/__tests__/Flex.test.tsx, packages/react-core/src/layouts/Flex/examples/Flex.md
**What**: Closes #8397
Adds `gap`, `rowGap`, and `columnGap` to `Flex` with breakpoints.
Adds examples & updates tests.
@mcoker The issue mentions a plain `pf-m-gap` class (without the size or breakpoints) that I don't see on the modifiers list, so I left it out for now. Did I miss something?
=> feat(Flex): add gap support

packages/react-core/package.json, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-styles/package.json, packages/react-table/src/components/Table/Caption.tsx, packages/react-table/src/components/Table/Tbody.tsx, packages/react-table/src/components/Table/Td.tsx, packages/react-table/src/components/Table/Th.tsx, packages/react-table/src/components/Table/Thead.tsx, packages/react-table/src/components/Table/Tr.tsx, packages/react-table/src/components/Table/__tests__/__snapshots__/RowWrapper.test.tsx.snap, packages/react-table/src/deprecated/components/Table/__tests__/__snapshots__/Table.test.tsx.snap, packages/react-tokens/package.json, yarn.lock
Closes #9129
~~I branched off of #9132, so only the changes from d2f4887fd1a3743e8b99ae7147b13137fd18778a and 86838184f77912bda33f3276fd4a3d8bf89ceec7 should be reviewed in this PR. I'll rebase this branch again to simplify things once #9132 merges, but wanted to get this available for review now.~~
=> feat(Table): added class names for table elements

packages/react-core/package.json, packages/react-core/src/layouts/Flex/Flex.tsx, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
**What**: Closes #9141
Adds the plain/non-size modifiers to gap, row gap, and column gap.
Currently this will not actually apply any styling because react's core package needs a version bump.
=> feat(Flex): add plain gap spacing

packages/react-table/src/docs/demos/table-demos/ExpandCollapseAll.jsx
**What**: Closes #8976 
I have also revamped the demo to use functional instead of class component.
=> fix(Table) clean up 'Expand collapse all' demo

packages/react-core/src/components/Pagination/Navigation.tsx
**What**: Closes #9117
Adding just `step={1}` solves the whole numbers part, but users could still type `-5` `3-1` so I went with an `onKeyDown` solution
=> Pagination - accept only positive whole numbers

packages/react-core/src/demos/PasswordStrength.md, packages/react-core/src/demos/PrimaryDetail.md, packages/react-core/src/demos/SearchInput/SearchInput.md
**What**: Closes #9192
a few function args weren't swapped in https://github.com/patternfly/patternfly-react/pull/9064
=> fix(TextInput): swap onChange params in demos

packages/react-core/src/components/DatePicker/DatePicker.tsx, packages/react-core/src/components/DatePicker/__tests__/DatePicker.test.tsx
**What**: Closes #9181
Also added some unit tests verifying the expected behavior cited in @mcarrano's reported issue.
=> fix(DatePicker): display errorText instead of helperText when both exist

packages/react-table/src/docs/demos/Table.md, packages/react-table/src/docs/demos/table-demos/BulkSelect.jsx, packages/react-table/src/docs/demos/table-demos/ColumnManagement.jsx, packages/react-table/src/docs/demos/table-demos/Compact.jsx, packages/react-table/src/docs/demos/table-demos/SortableResponsive.jsx, packages/react-table/src/docs/demos/table-demos/StaticBottomPagination.jsx, packages/react-table/src/docs/demos/table-demos/StickyHeader.jsx, packages/react-table/src/docs/demos/table-demos/sampleData.js
**What**: Closes #9032
Moved sample data from a JSX file in its own directory (seemed unnecessary - and also contained no JSX) to be co-located with the table demos.
=> chore(Table): Update sticky header demo to use latest Table component

packages/react-core/src/components/DatePicker/DatePicker.tsx, packages/react-core/src/components/DatePicker/examples/DatePickerControlled.tsx, packages/react-core/src/components/DatePicker/examples/DatePickerControlledCalendar.tsx, packages/react-integration/cypress/integration/datepicker.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/DatePickerDemo/DatePickerDemo.tsx
=> chore(DatePicker): updated controlled examples

packages/react-core/src/components/TimePicker/TimePicker.tsx
**What**: Closes #9156 
[Timepicker preview](https://patternfly-react-pr-9214.surge.sh/components/date-and-time/time-picker)
Issue seemed to be still pointing to the inputRef, which was no longer viable after we updated the markup for form control components to include a wrapper div.
=> fix(TimePicker): resolved border styling on open menu

packages/react-styles/src/css/components/Consoles/AccessConsoles.css, packages/react-styles/src/css/components/Consoles/DesktopViewer.css, packages/react-styles/src/css/components/Consoles/SerialConsole.css, packages/react-styles/src/css/components/Consoles/VncConsole.css, packages/react-styles/src/css/components/Table/inline-edit.css
=> fix(react-styles): updated class names to include versions

packages/react-core/src/components/Pagination/Pagination.tsx, packages/react-core/src/components/Pagination/__tests__/__snapshots__/Pagination.test.tsx.snap
**What**: Closes #9165
I'm not sure why the default is set to 0 here: https://github.com/patternfly/patternfly-react/pull/3383
but users cant type in 0 anyway because of: 
https://github.com/patternfly/patternfly-react/blob/1da6f5e5ad3c3665e0022693a5ce9de2588aa136/packages/react-core/src/components/Pagination/Navigation.tsx#L100
=> fix(Pagination): default page should be 1

packages/react-core/src/deprecated/components/Select/Select.tsx
**What**: Closes #9233 
Tested by adding a deprecated Select to a Modal and appending the Select menu to document body.
=> fix(Select deprecated): added width auto to prevent menu overflow in modal

packages/react-core/src/components/Pagination/Navigation.tsx, packages/react-core/src/components/Pagination/__tests__/Generated/__snapshots__/Navigation.test.tsx.snap, packages/react-core/src/components/Pagination/__tests__/__snapshots__/Pagination.test.tsx.snap, packages/react-integration/cypress/integration/pagination.spec.ts
=> fix(Pagination): remove spin buttons

packages/react-core/src/components/Page/examples/Page.md, packages/react-core/src/components/Toolbar/ToolbarGroup.tsx, packages/react-core/src/components/Toolbar/ToolbarItem.tsx, packages/react-core/src/components/Toolbar/__tests__/ToolbarGroup.test.tsx, packages/react-core/src/components/Toolbar/__tests__/ToolbarItem.test.tsx, packages/react-core/src/demos/Nav.md
=> chore(docs): Updated the Navigation demos to use the masthead instead of the page header

packages/react-core/src/components/Popover/Popover.tsx, packages/react-core/src/components/Popover/examples/Popover.md, packages/react-integration/demo-app-ts/package.json
**What**: Closes #9237 
We could instead update Popover's `position` prop to "auto", which would cause it to reposition before scrolling, though there may still be an issue of it getting cut off by a masthead depending on the layout.
There were also some other components that might be affected (menu like components), but since they don't use a focus trap like Popover does, I'm hesitent to revert those appendTo props to document body. Those could also have scrollbars to reduce the height and avoid the issue, though I don't believe the new dropdown/select currently can be passed the necessary props to achieve that (could be a followup for after v5)
=> fix(Popover): reverted appendTo to document body

packages/react-core/src/components/Nav/examples/NavDrilldown.tsx, packages/react-core/src/demos/examples/Nav/NavDrilldown.tsx, packages/react-integration/demo-app-ts/package.json
=> fix(Nav): updated drilldown navigation heights

packages/react-core/src/components/Drawer/examples/Drawer.md, packages/react-core/src/components/Drawer/examples/DrawerSecondaryBackground.tsx, packages/react-integration/demo-app-ts/package.json
=> chore(Drawer): Updated example name to be applicable for dark theme"

packages/react-charts/single-packages.config.json, packages/react-core/single-packages.config.json, packages/react-icons/package.json, packages/react-icons/single-packages.config.json, packages/react-table/single-packages.config.json, scripts/build-single-packages.js
cc @dlabaj 
- fixes up the build for the module federation environment
- create a new `dynamic` directory in the `dist` folder for all dynamically resolved modules
- enable dynamic output for the icons package
- remove duplicate runs for different output types (ems, cjs)
Based on local testing the packages are correctly shared and "tree shaken" if we use the absolute module paths to the `dynamic` directory.
> __NOTE__: I am using the `pf-5` alias for the module because I also have the v4 running in my test env
**Import example**
```jsx
import { Button as PF5Button } from 'pf-5/dist/dynamic/components/Button';
import { Icon } from 'pf-5/dist/dynamic/components/Icon';
import AdIcon from 'pf-5-icons/dist/dynamic/icons/ad-icon';
```
**Module federation sharing config example**
```js
new …
```
=> fix(release): ensure component package.json file has correct data

packages/react-core/single-packages.config.json, scripts/build-single-packages.js
The current `dynamic` output works well if all modules follow the same directory structure. There is an issue with the `react-core` package that has a mixed directory structure. The `helpers` dir is different from the rest of the modules and can cause issues when building the dynamic output.
- allow multiple custom modules glob pattern to enable mixed source directory structure for building dynamic output
- exclude third-party module directory for the Popper helper.
=> fix(react-core): fix dynamic helpers modules output

packages/react-charts/src/components/ChartLegendTooltip/ChartLegendTooltipContent.tsx, packages/react-charts/src/components/ChartTooltip/examples/ChartTooltip.md, packages/react-charts/src/components/ChartUtils/chart-tooltip.ts
Ensures chart legend tooltips have a minimum spacing between its label and value. Verified with Cost Management and the HCS UI.
Closes https://github.com/patternfly/patternfly-react/issues/9314
**Cost Management UI**
**HCS UI**
=> Bug - v5 preview testing - chart legend tooltip spacing

packages/react-core/src/components/NumberInput/NumberInput.tsx, packages/react-core/src/components/NumberInput/__tests__/NumberInput.test.tsx, packages/react-core/src/components/NumberInput/__tests__/__snapshots__/NumberInput.test.tsx.snap
**What**: Closes #9311 
Fixed regression introduced when TextInput's deprecated `isReadonly` was removed.
=> fix(Number Input): Fixed the readOnly not being applied when no onchange passed

packages/react-core/src/deprecated/components/Select/Select.tsx, packages/react-core/src/deprecated/components/Select/__tests__/__snapshots__/Select.test.tsx.snap
Closes patternfly/patternfly-react#9324
=> fix(SelectDeprecated): use textinput component for typeahead

packages/react-charts/src/components/ChartUtils/chart-theme.ts, packages/react-charts/src/components/index.ts
Exporting our `getThemeColors` util. This will eliminate any need to import unsupported theme color references (e.g., for building custom components).
Example: `getThemeColors(ChartThemeColor.multiUnordered)`
=> fix(charts): export getThemeColors

packages/react-core/src/components/Toolbar/ToolbarContent.tsx, packages/react-core/src/components/Toolbar/ToolbarGroup.tsx, packages/react-core/src/components/Toolbar/ToolbarItem.tsx
**What**: Closes #9194
Allows `alignItems` and `alignSelf` on `ToolbarContent`, `ToolbarGroup` and `ToolbarItem` to have values `start`, `center`, and `baseline`.
Some of the props were already present so updated the allowed values where they already existed. The existing props also allow a `default` value that doesn't apply any css, which I kept in the added props for consistency.
=> feat(Toolbar): update/add alignItems + alignSelf

packages/react-core/src/components/Brand/Brand.tsx, packages/react-core/src/components/Brand/examples/Brand.md, packages/react-core/src/components/Brand/examples/BrandBasic.tsx
fixes https://github.com/patternfly/patternfly-react/issues/9341
=> fix(brand): allowed heights/widths to be set together and be used when no children are passed

packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx, packages/react-core/src/components/ExpandableSection/ExpandableSectionToggle.tsx, packages/react-core/src/components/ExpandableSection/__tests__/ExpandableSection.test.tsx, packages/react-core/src/components/ExpandableSection/__tests__/__snapshots__/ExpandableSection.test.tsx.snap, packages/react-core/src/components/ExpandableSection/examples/ExpandableSection.md, packages/react-core/src/components/ExpandableSection/examples/ExpandableSectionDetached.tsx, packages/react-core/src/components/MultipleFileUpload/MultipleFileUploadStatus.tsx, packages/react-core/src/components/MultipleFileUpload/__tests__/__snapshots__/MultipleFileUploadStatus.test.tsx.snap, packages/react-core/src/components/MultipleFileUpload/examples/MultipleFileUpload.md
**What**: Closes #8504 
Tested with JAWS and FireFox and it seems like the new aria attributes work. Pressing <kbd>Insert</kbd> + <kbd>Alt</kbd> + <kbd>M</kbd> has JAWS announce it's moving to the controlled element, then announces "Show less region" (since the content wrapper is a div with role region now), and navigating to the next element causes JAWS to go into the actual content.
For context, I had come across [Accessibility Support's aria-controls tests](https://a11ysupport.io/tests/tech__aria__aria-controls) when looking into how to navigate to controlled element via keyboard shortcuts in JAWS.
=> fix(ExpandableSection): added ARIA attributes

packages/react-core/src/components/Card/__tests__/CardSelectableActions.test.tsx, packages/react-core/src/components/Card/__tests__/__snapshots__/CardSelectableActions.test.tsx.snap, packages/react-integration/cypress/integration/card.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/CardDemo/CardDemo.tsx
**What**: Closes #9138
Removed some tests that weren't actually being tested in the spec file and would be better suited to unit tests.
=> chore(Card): added tests for new clickable/selectable

packages/react-core/src/components/Slider/Slider.tsx, packages/react-core/src/components/Slider/_tests_/__snapshots__/Slider.test.tsx.snap
=> fix(Slider): reverted taborder

packages/react-integration/demo-app-ts/src/components/demos/WizardDemo/WizardDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/WizardDeprecatedDemo/WizardDeprecatedDemo.tsx
=> fix(chore): Fix deprecated wizard integration tests

packages/react-core/src/components/FileUpload/FileUploadField.tsx, packages/react-core/src/components/FileUpload/__tests__/__snapshots__/FileUpload.test.tsx.snap, packages/react-core/src/components/FileUpload/__tests__/__snapshots__/FileUploadField.test.tsx.snap
Fixes https://github.com/patternfly/patternfly-react/issues/9386
=> fix(fileupload): use default readonly text input instead of plain

packages/react-core/src/components/Toolbar/ToolbarChipGroupContent.tsx, packages/react-core/src/components/Toolbar/__tests__/Generated/__snapshots__/ToolbarChipGroupContent.test.tsx.snap, packages/react-core/src/components/Toolbar/__tests__/__snapshots__/Toolbar.test.tsx.snap
Fixes https://github.com/patternfly/patternfly-react/issues/9378
I yarn linked core from https://github.com/patternfly/patternfly/pull/5769 for this PR and everything looked OK as far as I can tell
=> fix(toolbar): added chip container class to toolbar content

packages/react-core/src/components/Menu/MenuItem.tsx
**What**: Closes #8593
Adds `target` and `rel` to the props list and passed to anchor menu items.
LMK if these would be better off as a generic `linkProps` property that is spread directly onto the link.
=> feat(MenuItem): allow target and rel on links

packages/react-core/src/components/Page/Page.tsx, packages/react-core/src/components/Page/__tests__/__snapshots__/Page.test.tsx.snap
=> fix(Page) allow change of main tag

packages/react-core/src/components/Alert/AlertActionLink.tsx, packages/react-core/src/components/Alert/__tests__/AlertActionLink.test.tsx
=> fix(AlertActionLink) support ReactNode as child

packages/react-core/src/components/MultipleFileUpload/MultipleFileUploadButton.tsx, packages/react-core/src/components/MultipleFileUpload/MultipleFileUploadMain.tsx, packages/react-core/src/components/MultipleFileUpload/__tests__/MultipleFileUploadButton.test.tsx, yarn.lock
**What**: Closes #9274 
**Issue Description:**
The 'Upload' button text in the ['File upload - multiple' PF component](https://www.patternfly.org/v4/components/file-upload---multiple#examples) is [hardcoded](https://github.com/patternfly/patternfly-react/blob/004483dd6c2729052170b8fe72faa1658fa2bd2a/packages/react-core/src/components/MultipleFileUpload/MultipleFileUploadButton.tsx) and cannot be changed.
I expect to be able to change the button text. E.g., label it as 'Browse' instead of 'Upload'.
Currently, this is not a blocker.
I am trying to use this component for a feature in Apicurio Registry. We are expecting to implement this feature in Q4.
=> fix: changed the button lable from Upload to Browse

packages/react-core/src/components/Modal/Modal.tsx, packages/react-core/src/components/Modal/__tests__/Modal.test.tsx
**What**: 
Same than https://github.com/patternfly/patternfly-react/pull/9096, but for `v5` branch.
Might close https://github.com/patternfly/patternfly-react/issues/8925.
=> fix(Modal): remove `aria-hidden` from siblings when unmounting the component (v5)

packages/react-core/src/components/Drawer/Drawer.tsx, packages/react-core/src/components/Drawer/DrawerContent.tsx, packages/react-core/src/components/Drawer/DrawerPanelContent.tsx, packages/react-core/src/components/Drawer/DrawerSection.tsx, packages/react-core/src/demos/PrimaryDetail.md, packages/react-core/src/demos/examples/PrimaryDetail/PrimaryDetailContentPadding.tsx
**What**: Closes #8548
Adds `no-background` to `colorVariant` props in Drawer.
=> feat(Drawer): add noBackground to colorVariant

packages/react-core/src/components/SimpleList/SimpleList.tsx, packages/react-core/src/components/SimpleList/SimpleListGroup.tsx, packages/react-core/src/components/SimpleList/SimpleListItem.tsx, packages/react-core/src/components/SimpleList/__tests__/Generated/__snapshots__/SimpleListGroup.test.tsx.snap, packages/react-core/src/components/SimpleList/__tests__/Generated/__snapshots__/SimpleListItem.test.tsx.snap, packages/react-core/src/components/SimpleList/__tests__/__snapshots__/SimpleList.test.tsx.snap
**What**: Closes #8482
Adds css classes to the SimpleList ul and li (hardcoded because they're not included in react styles).
=> feat(SimpleList): add ul/li classes

packages/react-core/src/components/Modal/Modal.tsx, packages/react-core/src/components/Modal/ModalContent.tsx, packages/react-integration/cypress/integration/wizarddeprecated.spec.ts
**What**: Closes #8351
Adds `maxWidth` property. 
Updates `width` and `maxWidth` to be set via css variables instead of directly as a style property.
=> feat(Modal): use css vars to set width, add maxWidth

packages/react-core/src/demos/examples/Tabs/TabsAndTable.tsx
**What**: Closes #9100 
Convenience link to the changed demo: https://patternfly-react-pr-9395.surge.sh/components/tabs/react-demos/tables-and-tabs/
=> docs(Tabs): converted tabs & tables demo to use inputs for selection

packages/react-core/src/components/AboutModal/AboutModal.tsx
Closes: [#9246](https://github.com/patternfly/patternfly-react/issues/9246)
=> chore(aboutmodal): added token instead off hard coded value

packages/react-core/src/components/Pagination/Pagination.tsx, packages/react-core/src/components/Pagination/examples/Pagination.md, packages/react-core/src/components/Pagination/examples/PaginationOffset.tsx
**What**: Closes #9231
when having a per_page=20, and offset is 20  (skip the first 20 items ,show item numbers 21,22,23...), page should be calculated to 2, but before this change it was calculated as 1
=> feat(Pagination): add offset example

packages/react-core/src/components/DatePicker/DatePicker.tsx, packages/react-core/src/components/DatePicker/__tests__/DatePicker.test.tsx, packages/react-core/src/components/DatePicker/examples/DatePicker.md, packages/react-core/src/components/DatePicker/examples/DatePickerRequired.tsx
**What**: Closes #8779 
Originally had added logic to call `setError` if `pristine && isRequired`, but that would have required a consumer to always pass in a validator to `validators` array; something along the lines of `validators={[(date) => !date ? 'Date cannot be blank' : '']}`.
Just adding a new isRequired and emptyDateText props will make it easier for consumers, and it avoids a case of `isRequired` being passed in but an error message never appearing if a validator isn't passed in.
This is somewhat dependent on #9267, but should just require a slight tweak in that PRs code (the `value === '' && setErrorText('')` line)
=> fix(DatePicker): updated onBlur logic for empty date

packages/react-core/src/components/Modal/ModalBoxCloseButton.tsx
=> feat(Modal): add close button arialabel prop

packages/react-core/src/components/Modal/Modal.tsx, packages/react-core/src/components/Modal/ModalContent.tsx, packages/react-core/src/components/Modal/examples/Modal.md, packages/react-core/src/components/Modal/examples/ModalCustomFocus.tsx, packages/react-integration/cypress/integration/modal.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/ModalDemo/ModalDemo.tsx
**What**: Closes #4018 
[Modal custom focus example](https://patternfly-react-pr-9453.surge.sh/components/modal#custom-focus)
=> feat(Modal): added ability to customize initial focus

packages/react-core/src/components/TimePicker/examples/TimePicker.md, packages/react-core/src/components/TimePicker/examples/TimePickerBasic12Hour.tsx, packages/react-core/src/components/TimePicker/examples/TimePickerBasic24Hour.tsx, packages/react-core/src/components/TimePicker/examples/TimePickerBasic24HoursWithSeconds.tsx, packages/react-core/src/components/TimePicker/examples/TimePickerCustomDelimiter.tsx, packages/react-core/src/components/TimePicker/examples/TimePickerMinMaxTimes.tsx, packages/react-core/src/components/TimePicker/examples/TimePickerWithSeconds.tsx
**What**: Closes #9352 
Convenience link: https://patternfly-react-pr-9430.surge.sh/components/date-and-time/time-picker
=> docs(TimePicker): updated examples to TypeScript

packages/react-core/src/components/Card/Card.tsx, packages/react-core/src/components/Card/CardHeader.tsx
=> fix(Card): updated warning logic for new clickable/selectable card

packages/react-docs/patternfly-a11y.config.js
Closes https://github.com/patternfly/patternfly-react/issues/9327
=> chore(a11y): clean up a11y config so we test valid URLs and limit timeouts

packages/react-core/src/components/Chip/Chip.tsx, packages/react-core/src/components/Chip/examples/ChipDefault.tsx, packages/react-integration/demo-app-ts/src/components/demos/ChipGroupDemo/ChipGroupDefaultIsOpenDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/ChipGroupDemo/ChipGroupDemo.tsx
=> fix(Chip): Added prop to render a badge in the chip after the text

.github/release.sh, packages/react-integration/package.json
**What**: Closes #9505 
Another attempt to resolve the error currently causing our prereleases to fail the release process. This time by updating lerna to run with the --no-private flag.
As part of that I updated react-integration from private to just a restricted publishConfig so that lerna will continue to bump it but the package will (I believe) remain not publicly available.
=> chore(CI): updated lerna to not publish private packages

packages/react-charts/src/components/ChartScatter/ChartScatter.tsx
**What**: `bubbleProperty` of `VictoryScatter` is only considered if the size prop is undefined (see https://github.com/FormidableLabs/victory/blob/bbc1e2a39448d7fb6724f916afacf5f6eab7d1b3/packages/victory-scatter/src/helper-methods.tsx#L35-L43)
This PR updates the code to set the default `size` function only if `bubbleProperty` is not set.
closes: #9504
=> fix(ChartScatter): consider bubbleProperty if it is set

packages/react-table/src/components/Table/Table.tsx, packages/react-table/src/components/Table/examples/Table.md, packages/react-table/src/components/Table/examples/TableTreeNoInset.tsx
Closes https://github.com/patternfly/patternfly-react/issues/8604
=> feat(Table): Added isNoInset prop for flat tree tables

packages/react-core/src/components/TreeView/TreeView.tsx, packages/react-core/src/components/TreeView/TreeViewListItem.tsx, packages/react-core/src/components/TreeView/__tests__/TreeView.test.tsx, packages/react-core/src/components/TreeView/__tests__/__snapshots__/TreeView.test.tsx.snap
**What**: Closes #9361
Adds `onCollapse` callback to `TreeView`. This callback is triggered when a node that has children is clicked.
Does `onCollapse` make the most sense for the name, or would `onToggle` be a better fit?
=> feat(TreeView): onCollapse callback

packages/react-charts/src/components/ChartScatter/ChartScatter.tsx, packages/react-table/src/components/Table/examples/TableTreeNoInset.tsx
=> fix(Charts, Table): Fixed lint errors in charts and table

packages/react-core/src/demos/Card/Card.md, packages/react-core/src/demos/PrimaryDetail.md
=> chore(card view demos): update to new selectable card variant

packages/react-core/src/helpers/FocusTrap/FocusTrap.tsx, packages/react-core/src/helpers/useUnmountEffect.ts
Converts the `FocusTrap` component to a function component, and aligns it so it can work with strict null checks in TypeScript.
Works towards closing #7889
=> feat(FocusTrap): convert to function component

packages/react-core/src/components/DatePicker/DatePicker.tsx, packages/react-core/src/components/DatePicker/examples/DatePicker.md, packages/react-core/src/components/DatePicker/examples/DatePickerRequired.tsx
=> fix(DatePicker): updated v4 onBlur logic

packages/react-core/src/components/Tile/examples/Tile.md
Intended to replace https://github.com/patternfly/patternfly-react/pull/9208
=> docs(tile): Adds documentation to React examples.

packages/react-core/src/components/Icon/Icon.tsx, packages/react-core/src/components/Icon/__tests__/Icon.test.tsx
=> feat(Icon): added prop for mirroring in RTL

packages/react-charts/src/components/ChartLegend/examples/ChartLegend.md
The chart's tooltip example below no longer works. It appears the `reference` prop of `Tooltip` was renamed as `triggerRef` at some point prior to the v5 release.
https://www.patternfly.org/charts/legends/#legend-tooltips
closes: #9619
=> chore(charts): update chart's tooltip example

packages/react-core/src/components/Nav/NavItem.tsx
**What**: Closes #9492
Updates the `component` typing to reflect usage of the prop, which wasn't being used as a node, but as a component type.
=> fix(NavItem): fix incorrect component typing

packages/react-core/src/components/SearchInput/SearchInput.tsx, packages/react-core/src/components/SearchInput/__tests__/__snapshots__/SearchInput.test.tsx.snap, packages/react-core/src/deprecated/components/ContextSelector/__tests__/__snapshots__/ContextSelector.test.tsx.snap
fixes https://github.com/patternfly/patternfly-react/issues/9600
=> fix(search-input): mirror search icon in rtl, fix double border

packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx, packages/react-code-editor/src/components/CodeEditor/__test__/__snapshots__/CodeEditor.test.tsx.snap
fixes https://github.com/patternfly/patternfly-react/issues/9625
=> fix(code-editor): force element that wraps editor to be LTR

packages/react-core/src/components/Checkbox/examples/Checkbox.md, packages/react-core/src/components/Checkbox/examples/CheckboxControlled.tsx, packages/react-core/src/components/Checkbox/examples/checkbox.css
=> chore(Checkbox): updated example CSS to use logical property

packages/react-core/src/demos/DataListDemo.md
=> chore(DataList): added RTL modifier class to icon in demo

packages/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx, packages/react-core/src/components/ClipboardCopy/ClipboardCopyExpanded.tsx, packages/react-core/src/components/ClipboardCopy/ClipboardCopyToggle.tsx, packages/react-core/src/components/ClipboardCopy/__tests__/__snapshots__/ClipboardCopyExpanded.test.tsx.snap, packages/react-core/src/components/ClipboardCopy/__tests__/__snapshots__/ClipboardCopyToggle.test.tsx.snap
fixes https://github.com/patternfly/patternfly-react/issues/9630
This makes the `isCode` variation retain `dir="ltr"` on the toggle text input and expanded content box.
Verified with an RTL speaker that it looks as expected, as well as these examples all look correct and copy/paste the values correctly.
Inline compact
Code
Regular/expanded
Array/expanded
=> fix(clipboard-copy): added rtl support

packages/react-core/src/components/Slider/SliderStep.tsx
**What**: Closes #9563
As the `value` prop is optional, I added the `sliderStepLeft.value` as a default case.
=> refactor(SliderStep): use token instead for hardcoded value

packages/react-core/src/components/Breadcrumb/examples/BreadcrumbDropdown.tsx, packages/react-core/src/components/Menu/examples/MenuWithDrilldownBreadcrumbs.tsx
fixes https://github.com/patternfly/patternfly-react/issues/9587
This may not be a great way to do this, but these are basically drillup items in the breadcrumb menus.
=> chore: update breadcrumb dropdown item arrow to work in RTL

packages/react-core/src/components/Slider/Slider.tsx, packages/react-core/src/components/Slider/_tests_/Slider.test.tsx, packages/react-core/src/components/Slider/examples/SliderActions.tsx
Updated slider to work in RTL. Deprecated` rightActions` and `leftActions` props, added `endActions` and `startActions` props to replace them.
**What**: Closes #9593
=> fix(Slider): Updated slider to work in RTL. 

packages/react-core/src/components/Tabs/examples/Tabs.md
=> docs(tabs): Clean up React documentation content.

packages/react-core/src/components/Timestamp/Timestamp.tsx, packages/react-core/src/components/Timestamp/__tests__/Timestamp.test.tsx, packages/react-core/src/components/Timestamp/examples/Timestamp.md, packages/react-core/src/components/Timestamp/examples/TimestampDefault.tsx, packages/react-core/src/components/Timestamp/examples/TimestampDefaultTooltip.tsx
=> feat(Timestamp): allowed displayed datetime to be UTC

packages/react-core/src/components/Tabs/Tabs.tsx
=> fix(Tabs): allow RTL scrolling

packages/react-core/src/components/Nav/NavList.tsx, packages/react-core/src/components/Nav/__tests__/__snapshots__/Nav.test.tsx.snap, packages/react-core/src/components/Page/__tests__/__snapshots__/Page.test.tsx.snap
=> fix(Nav): allow RTL scrolling

packages/react-core/src/components/BackgroundImage/__tests__/BackgroundImage.test.tsx, packages/react-core/src/components/BackgroundImage/__tests__/__snapshots__/BackgroundImage.test.tsx.snap
=> chore(BackgroundImage): update tests

packages/react-core/src/components/Label/Label.tsx, packages/react-core/src/components/Label/__tests__/Label.test.tsx, packages/react-core/src/components/Label/__tests__/__snapshots__/Label.test.tsx.snap, packages/react-core/src/components/Label/examples/LabelFilled.tsx, packages/react-core/src/components/Label/examples/LabelOutline.tsx
**What**: Closes #8665 
I used `onLabelClick` instead of `onClick` as a prop name because of name conflict. I think maybe a better prop name could be used but I am not sure what it should be.
=> feat(Label) add option to make label clickable

packages/react-charts/src/components/Chart/Chart.tsx, packages/react-charts/src/components/ChartBullet/ChartBullet.tsx, packages/react-charts/src/components/ChartDonut/ChartDonut.tsx, packages/react-charts/src/components/ChartDonutUtilization/ChartDonutUtilization.tsx, packages/react-charts/src/components/ChartPie/ChartPie.tsx, packages/react-charts/src/components/ChartUtils/chart-label.ts, packages/react-charts/src/components/ChartUtils/chart-legend.ts
**What**: Closes #9541
Adds the `legendDirection` property to specify RTL/LTR, and adds `left` and `bottom-right` as valid values for `legendPosition`.
The values for the transform and offset passed to the `ChartLabel` and `ChartPoint` were what ended up working/looking visually correct (basically swapping the legend icon and text positions locally). I'm unsure why `ChartPie` needed a slightly different offset - with 40/10 a left-aligned RTL legend was disappearing off the container regardless of the left padding on the pie chart. 
It should be possible get a RTL legend with the current implementation but that would require manual legend creation. To summarize - to fully enable RTL in charts, a user would need to pass `invertAxis` to the `ChartAxis`, and pass both `legendDirection` and a …
=> feat(charts): add RTL legend support

packages/react-core/src/components/DragDrop/Draggable.tsx
**What**: Closes #9645 
Can test with
`<DragDrop onDrop={onDrop} onDrag={(i) =>  !(i.index == 0 && i.droppableId == 'items1')}>` 
on line 82 of https://patternfly-react-pr-9646.surge.sh/components/drag-and-drop#multiple-lists
It won't let you move the first option in the first list, but also will not disable stuff
=> fix(Draggable): dont disable droppable on false ondrag

packages/react-core/src/next/components/Dropdown/Dropdown.tsx
**What**: 
Closes #9564
This is an update to PatternFly4 Dropdown next component
=> feat(Dropdown next): able to append the menu to any DOM element

packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx, packages/react-code-editor/src/components/CodeEditor/examples/CodeEditorBasic.tsx, packages/react-code-editor/src/components/CodeEditor/examples/CodeEditorShortcutMainHeader.tsx, packages/react-code-editor/src/components/CodeEditor/examples/CodeEditorSizeToFit.tsx
**What**: Closes #9537 
Added code to conditionally remove the footer (Browse btn and Start from scratch link) when it's a read-only code editor. Also removed some leftover console.logs that were being sent on mounts in order to clean up the console on load.
To test, pass isReadOnly to the code editor in the Code Editor with Actions example and verify that the button and link are no longer present.
Note that there is an exception thrown on load of the code editor examples - this was pre-existing and is fixed by a separate PR: https://github.com/patternfly/patternfly-react/pull/9665
=> fix(CodeEditor): hide button and link when read-only

packages/react-integration/demo-app-ts/package.json, yarn.lock
=> fix(build): Fixed version mismatch issue

packages/react-charts/src/components/Chart/Chart.tsx, packages/react-charts/src/components/ChartPie/ChartPie.tsx, packages/react-charts/src/components/ResizeObserver/examples/resizeObserver.md
This ensures legend props are not undefined in the Chart's `useEffect` hook.
https://github.com/patternfly/patternfly-react/issues/9718
=> fix(charts): legendAllowWrap function generates an error

packages/react-core/src/components/TextInputGroup/examples/TextInputGroupBasic.tsx
=> chore(TextInputGroup): allow input in basic example

packages/react-core/src/components/Text/examples/Text.md
=> docs(Text): add description

packages/react-integration/cypress/integration/wizard.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/WizardDemo/WizardDemo.tsx
**What**: Closes #9724
Also tried looking at the demos that are failing a11y in some PRs lately, looks like it's caused by:
- the plain button that should only be visible at certain viewport widths having an `aria-controls` of an ID that doesn't exist yet
- possibly the `aria-controls` and the respective `id` (when rendered) being updated due to the internal incrementing of the `currentId` suffix within ToolbarContent
=> chore(Wizard): updated integration tests to avoid PR failures

packages/react-core/src/components/Alert/examples/Alert.md, packages/react-integration/demo-app-ts/src/components/demos/AlertGroupDemo/AlertGroupTimeoutFromBottomDemo.tsx
**What**: Closes #9331
**Additional issues**: 
Few things I'd also improve in [Alert docs](https://www.patternfly.org/components/alert/):
- actionClose: instead of opening a pop-up alert, it could close the alert notification (same way as in the demo)
- the 3rd and 4th variations could be merged to one just to demonstrate the actionClose https://www.patternfly.org/components/alert#alert-variations (or we can demonstrate the actionClose on the 1st or 2nd example)
=> docs(Alert): update AlertActionLink props so they follow guidelines

packages/react-core/src/components/Button/examples/Button.md
**What**: Closes #9745 
This PR fixes the `input group` link listed beside in the description for the `Control` variant:
- https://www.patternfly.org/components/button/#variant-examples
=> chore(docs): fix link on button page

packages/react-core/src/components/InputGroup/InputGroup.tsx, packages/react-core/src/components/InputGroup/__tests__/InputGroup.test.tsx, packages/react-core/src/components/NumberInput/__tests__/NumberInput.test.tsx
Same than https://github.com/patternfly/patternfly-react/pull/9670, but for `v4`  branch.
**What**: Closes https://github.com/patternfly/patternfly-react/issues/9667.
=> [v4] fix(InputGroup): don't add aria-describedby automatically

packages/react-core/src/helpers/Popper/Popper.tsx
**What**: Closes #9698
Fix to update popper's internal trigger element when the given `trigger` changes and `triggerRef` remains the same (in the case of the trigger content updating or changing).
Verified testing locally with the issue's [codesandbox](https://codesandbox.io/s/amazing-firefly-lqd5kj?file=/index.tsx:123-2730). The code should be copied into the surge to check this PR, as we don't currently have an example of a dynamically updating toggle.
=> fix(popper): update trigger element when content changes

packages/react-core/src/components/SearchInput/SearchInput.tsx, packages/react-core/src/components/SearchInput/__tests__/SearchInput.test.tsx
=> feat(Search input): Added a prop to display utilities

packages/react-core/src/components/CalendarMonth/CalendarMonth.tsx, packages/react-core/src/helpers/datetimeUtils.ts
**What**: Closes #9700
The bug was related to incorrect setting of `initialDate`, if `dateProp` was null, `new Date(null)` returns a valid date: 1 st Jan 1970, but in countries with UTC minus it returns 31 Dec 1969, then if the initial day is 31 it was causing issues in `changeMonth` function, which is now also refactored and fixed.
Other changes made:
* `changeMonth` refactoring (as we are not focusing dates on month change, `changeMonth` was simplified to always return the first day of the month)
* change year functionality refactoring
* unfocusing date, when changing year by clicking on small arrows
=> fix(CalendarMonth): does not skip a month on arrow click

packages/react-core/src/components/InputGroup/InputGroup.tsx, packages/react-core/src/components/InputGroup/__tests__/InputGroup.test.tsx, packages/react-core/src/components/NumberInput/__tests__/NumberInput.test.tsx
**What**: Closes #9667 
This contribution complete one of the two tasks mentioned by @thatblindgeye at https://github.com/orgs/patternfly/discussions/5954#discussioncomment-7103093
>  Ideally what we'd want to do is:
>
>    * Remove the automated application of the aria-describedby attribute, and have it simply be something passed by the consumer when applicable like most/all of our other components
>    * Possibly provide an example showcasing when an aria-describedby would make sense
Hope it helps.
=> fix(InputGroup): don't add aria-describedby automatically

packages/react-core/src/components/Nav/NavExpandable.tsx, packages/react-core/src/components/Nav/NavItem.tsx, packages/react-core/src/components/Nav/examples/Nav.md, packages/react-core/src/components/Nav/examples/NavExpandableThirdLevel.tsx, packages/react-core/src/components/Nav/examples/NavLinkText.tsx, packages/react-core/src/components/Nav/examples/nav.css
=> feat(Nav): Updated to add wrapper for nav link text

packages/react-core/src/components/Chip/Chip.tsx, packages/react-core/src/components/Chip/__tests__/Chip.test.tsx, packages/react-core/src/components/Chip/__tests__/__snapshots__/Chip.test.tsx.snap, packages/react-integration/cypress/integration/chip.spec.ts, packages/react-integration/demo-app-ts/src/Demos.ts, packages/react-integration/demo-app-ts/src/components/demos/ChipDemo/ChipDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/index.ts
**What**: Closes #9530 
Added integration test to check that tooltipPosition is passed to Tooltip properly
=> chore(Chip): updated unit tests

packages/react-core/src/components/Dropdown/Dropdown.tsx, packages/react-core/src/components/Menu/MenuContainer.tsx, packages/react-core/src/components/Select/Select.tsx, packages/react-core/src/helpers/Popper/Popper.tsx
=> fix(popper): improve flip behavior in RTL

packages/react-core/src/components/Drawer/DrawerPanelContent.tsx, packages/react-core/src/components/Nav/NavList.tsx, packages/react-core/src/components/Slider/Slider.tsx, packages/react-core/src/components/Tabs/Tabs.tsx, packages/react-core/src/helpers/Popper/Popper.tsx, packages/react-core/src/helpers/__mocks__/util.ts, packages/react-core/src/helpers/util.ts
=> chore(RTL): move RTL helper to utils file, refactor components to use it

packages/react-core/src/components/Wizard/Wizard.tsx, packages/react-core/src/components/Wizard/WizardBody.tsx, packages/react-core/src/components/Wizard/WizardNavInternal.tsx, packages/react-core/src/components/Wizard/WizardToggle.tsx, packages/react-core/src/components/Wizard/__tests__/Wizard.test.tsx, packages/react-core/src/components/Wizard/__tests__/WizardBody.test.tsx, packages/react-core/src/components/Wizard/examples/WizardGetCurrentStep.tsx, packages/react-core/src/components/Wizard/utils.ts
**What**: Closes #9736
**Summary**:
- Updated logic to skip over isHidden and isDisabled steps onStepChange
- Updated logic to disable sub steps when the parent step has isDisabled === true
- Updated existing unit tests for onStepChange
- Added new tests verifying scenarios where basic, parent, and sub steps are hidden or disabled
=> fix(Wizard): onStepChange - skip isDisabled & isHidden

packages/react-core/src/components/Nav/__tests__/__snapshots__/Nav.test.tsx.snap, packages/react-core/src/components/NotificationDrawer/NotificationDrawerHeader.tsx, packages/react-core/src/components/NotificationDrawer/NotificationDrawerListItem.tsx, packages/react-core/src/components/NotificationDrawer/__tests__/NotificationDrawerListItem.test.tsx, packages/react-core/src/components/NotificationDrawer/__tests__/__snapshots__/NotificationDrawerHeader.test.tsx.snap, packages/react-core/src/components/NotificationDrawer/__tests__/__snapshots__/NotificationDrawerListItem.test.tsx.snap
=> fix(Notification Drawer): Added screen reader text for notification drawer item read state

packages/react-core/src/components/Divider/__tests__/Divider.test.tsx, packages/react-core/src/components/Divider/__tests__/__snapshots__/Divider.test.tsx.snap
=> chore(Divider): update tests to new standards

packages/react-core/src/components/TreeView/TreeViewListItem.tsx, packages/react-core/src/components/TreeView/__tests__/__snapshots__/TreeView.test.tsx.snap
Declares `type='button'` explicitly so wrapping `TreeView` in a form doesn't cause node selection/expansion to submit the form (because the default button type in a form is 'submit').
=> fix(TreeView): define button type

packages/react-core/src/components/DatePicker/DatePicker.tsx
=> fix(DatePicker): updated logic for parsing and focus management

packages/react-core/src/components/DatePicker/DatePicker.tsx, packages/react-core/src/components/DatePicker/__tests__/__snapshots__/DatePicker.test.tsx.snap, packages/react-core/src/demos/SearchInput/SearchInput.md
**What**: Closes #9442
1. selecting a date would crash the page because of incorrect variables passed to `onChange`
2. DatePicker should not have used `isFill` since it will always use the `--pf-v5-c-date-picker__input--c-form-control--Width` width. Previously the width was ignored because input had `flex: 2;` but that css was removed in a input-group refactor
=> fix Search Input - composable advanced search demo

packages/react-code-editor/src/components/CodeEditor/examples/CodeEditor.md
This link is pointing to latest react-code-editor (v5) but it should point to v4
**What**: Closes #9813 
**Additional issues**: Not that I know of
=> [v4] Fix package.json link for code editor required peer deps

packages/react-core/src/demos/CustomMenus/CustomMenus.md, packages/react-core/src/demos/CustomMenus/examples/FilterMenuDemo.tsx, packages/react-core/src/demos/CustomMenus/examples/InlineSearchFilterMenuDemo.tsx
**What**: Closes #9468
- I think that **Context selector menu** examples should be updated both in [custom menus](https://www.patternfly.org/components/menus/custom-menus#context-selector-menu) and in the [context selector](https://www.patternfly.org/components/menus/context-selector) site too. Right now, it has following problems:
1. does not use instant filtering, you have to click on the search button instead (even _enter_ key does not work)
2. when scrolling down, search bar will not stick at place
We could update the Context selector, so it works very similarly to this "With search input filtering" menu, or even merge them into one improved Context selector example. What do you think?
=> docs(custom menu): add example with search input inline filtering

packages/react-core/src/components/HelperText/__tests__/HelperText.test.tsx, packages/react-core/src/components/HelperText/__tests__/HelperTextItem.test.tsx, packages/react-core/src/components/HelperText/__tests__/__snapshots__/HelperText.test.tsx.snap, packages/react-core/src/components/HelperText/__tests__/__snapshots__/HelperTextItem.test.tsx.snap
=> chore(HelperText): update tests

packages/react-core/src/components/Chip/Chip.tsx
**What**: Closes #9690 
Adds logic for `Chip` to update its internal `isTooltipVisible` prop when chip updates.
Can be tested by going to `ExpandableSection` examples and adding the following as a child (before this PR, the long chip text would not trigger its tooltip). 
`<ChipGroup className="pf-u-mb-lg">
<Chip id="1">
Very long text which. The tooltip will show because the chip is
initially rendered visible.
</Chip>
</ChipGroup>`
=> fix(Chip): update tooltip vis when chip updates

README.md
**Fix contributor's info link** : Closes https://github.com/patternfly/patternfly-react/issues/9839
=> fix link to patternfly community contributors document

packages/react-core/package.json, packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx, packages/react-core/src/components/ExpandableSection/ExpandableSectionToggle.tsx, packages/react-core/src/components/ExpandableSection/__tests__/__snapshots__/ExpandableSection.test.tsx.snap, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-integration/cypress/integration/expandablesection.spec.ts, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
**What**: Closes #9835
Towards: #9850 
- Converted `pf-v5-c-expandable-section__toggle-text` to placholder class
- removed `pf-m-detached` modifier
=> chore(deps): update v6 core deps

packages/react-table/src/components/Table/SelectColumn.tsx, packages/react-table/src/components/Table/SortColumn.tsx, packages/react-table/src/components/Table/TableText.tsx, packages/react-table/src/components/Table/TableTypes.tsx, packages/react-table/src/components/Table/Th.tsx, packages/react-table/src/components/Table/utils/decorators/selectable.tsx, packages/react-table/src/components/Table/utils/decorators/sortable.tsx
**What**: Closes #9658
There are two different tooltips being set and controlled for a `th` - one controlled by `TableText` for sortable columns and one controlled by `Th` for everything else. In both cases, the tooltip is only displayed when the content overflows. The `tooltip` prop in `Th` was not connected to `TableText` so sortable column tooltips couldn't be customized, and for `th` content that was not text, such as a selectable column's checkbox, `Th`'s tooltip wouldn't display because the content wasn't considered as overflowing.
- Adds tooltip to `SelectColumn` to allow a tooltip on the checkbox
- Adds `tooltipProps` to `Th` to allow additional tooltip customization
- Connects `Th` `tooltip` prop through to decorators to customize sortable/selectable tooltips
- Disables `Th` …
=> fix(Table): make tooltip prop consistent

packages/react-core/src/components/Page/PageSection.tsx, packages/react-core/src/components/Page/examples/Page.md, packages/react-core/src/components/Page/examples/PageHorizontalNav.tsx, packages/react-core/src/components/Page/examples/PageVerticalNav.tsx, packages/react-core/src/components/Page/examples/page.css
**What**: Closes #9808
We probably want to remove the deprecated tertiary nav Page example whenever we also remove the React deprecated tab.
=> feat(Page): Added secondary variant styling for Penta work

packages/react-core/src/components/Popover/Popover.tsx
Do not return focus on deactivate if `withFocusTrap` prop is false
**What**: Closes #9863
=> Popover FocusTrap returnFocusOnDeactivate prop dependent on withFocusTrap prop #9866

packages/react-core/src/components/Menu/MenuItem.tsx, packages/react-integration/demo-app-ts/src/components/demos/DropdownDemo/DropdownDemo.tsx
=> Add download to MenuItem

packages/react-core/src/components/Banner/Banner.tsx, packages/react-core/src/components/Banner/__tests__/Banner.test.tsx, packages/react-core/src/components/Banner/examples/Banner.md, packages/react-core/src/components/Banner/examples/BannerBasic.tsx, packages/react-core/src/components/Banner/examples/BannerStatus.tsx
=> feat(banner): add support for new styles in penta

packages/react-core/src/components/Accordion/Accordion.tsx, packages/react-core/src/components/Accordion/AccordionContext.ts, packages/react-core/src/components/Accordion/AccordionToggle.tsx, packages/react-core/src/components/Accordion/__tests__/Accordion.test.tsx, packages/react-core/src/components/Accordion/__tests__/AccordionToggle.test.tsx, packages/react-core/src/components/Accordion/examples/Accordion.md, packages/react-core/src/components/Accordion/examples/AccordionToggleIconAtStart.tsx
**What**: Closes #9786
[Accordion toggle icon at start example preview](https://patternfly-react-pr-9877.surge.sh/components/accordion#toggle-icon-at-start)
=> feat(Accordion): added toggle alignment functionality

packages/react-core/src/components/Chip/Chip.tsx, packages/react-core/src/components/Chip/__tests__/__snapshots__/Chip.test.tsx.snap, packages/react-integration/cypress/integration/chip.spec.ts
**What**: Closes #9764
Prior to https://github.com/patternfly/patternfly-react/pull/8383, the original logic was that the `id` prop would be applied to the chip text for a non-overflow chip, so this is just preserving that original functionality. We could alternatively have the `id` prop spread to the outer Chip element and only apply a randomId to the chip text (or suffix the passed in `id` with "chip-text-[random number]" or something).
=> fix(Chip): prevented duplicate ID being applied

packages/react-core/src/demos/ExpandableSection/ExpandableSection.md, packages/react-core/src/demos/ExpandableSection/examples/ExpandableTextDemo.tsx
Added a demo to show how to use expandable section to create an expandable text component.
Closes #9888
=> chore(expandablesection): Added a demo to show how to use expandable section to create an expandable text component.

packages/react-core/src/next/components/Modal/__tests__/Modal.test.tsx, packages/react-core/src/next/components/Modal/__tests__/ModalBoxHeader.test.tsx, packages/react-core/src/next/components/Modal/__tests__/ModalBoxTitle.test.tsx, packages/react-core/src/next/components/Modal/__tests__/ModalContent.test.tsx, packages/react-core/src/next/components/Modal/__tests__/ModalFooter.test.tsx
=> chore(build): Fix lint issues

packages/react-core/src/components/Checkbox/Checkbox.tsx, packages/react-core/src/components/Checkbox/__tests__/Checkbox.test.tsx, packages/react-core/src/components/Radio/Radio.tsx, packages/react-core/src/components/Radio/__tests__/Radio.test.tsx
**What**: Closes #9710
Both `isLabelWrapped` and `component` props are now supported in Checkbox and Radio. I also added support for `isLabelBeforeButton` to checkbox, as we have it in the Radio component.
`MenuToggleCheckbox` was not rewritten to use `Checkbox` internally yet. I had issues with incompatible types. This can possibly be done in a followup PR.
=> Add support for isLabelWrapped and component in Checkbox / Radio

packages/react-core/src/components/Checkbox/__tests__/Checkbox.test.tsx, packages/react-core/src/components/Radio/__tests__/Radio.test.tsx
=> chore(build): Fix lint errors

packages/react-core/src/components/Popover/Popover.tsx
**What**: Closes #9951
Clicking on the trigger element causes both the trigger click handler and document click handler to activate. The document click handler should ignore trigger element click events (as they should already be handled by the trigger handler) in addition to popper element events.
=> fix(Popover): click event trigger logic

packages/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx
**What**: Closes #9962
There was a bug introduced in https://github.com/patternfly/patternfly-react/pull/9975:
https://github.com/patternfly/patternfly-react/assets/84135613/9977cafb-8e2f-43f9-b5ae-0cae0ace0deb
This PR reverts https://github.com/patternfly/patternfly-react/pull/9975 and closes the original #9962 issue.
https://github.com/patternfly/patternfly-react/assets/84135613/08967b46-5234-4c30-b863-f1fed5021dab
=> fix(ClipboardCopy): update main content on children change when expanded

packages/react-core/src/components/Avatar/Avatar.tsx, packages/react-core/src/components/Avatar/__tests__/Avatar.test.tsx, packages/react-core/src/components/Avatar/examples/Avatar.md, packages/react-core/src/components/Avatar/examples/AvatarBasic.tsx, packages/react-core/src/components/Avatar/examples/AvatarBordered.tsx, packages/react-core/src/components/Avatar/examples/AvatarSizeVariations.tsx, packages/react-core/src/components/Avatar/examples/example.css
=> feat(Avatar): Penta updates

packages/react-drag-drop/src/next/components/DragDrop/DragDropSort.tsx, packages/react-drag-drop/src/next/components/DragDrop/DragDropUtil.tsx, packages/react-drag-drop/src/next/components/DragDrop/examples/DragDrop.md, packages/react-drag-drop/src/next/components/DragDrop/examples/DragDropDemos.md, packages/react-drag-drop/src/next/components/DragDrop/index.ts
=> feat(DragDrop): fix import warning

packages/react-core/src/components/SimpleList/SimpleListItem.tsx, packages/react-core/src/components/SimpleList/examples/SimpleList.md, packages/react-core/src/components/SimpleList/examples/SimpleListBasic.tsx, packages/react-core/src/components/SimpleList/examples/SimpleListLinks.tsx
**What**: Closes #9926
Added new modifier class when `SimpleListItem` is a link.
=> feat(SimpleList): penta updates

packages/react-core/package.json, packages/react-core/src/components/MultipleFileUpload/MultipleFileUploadStatusItem.tsx, packages/react-core/src/components/MultipleFileUpload/__tests__/__snapshots__/MultipleFileUploadStatusItem.test.tsx.snap, packages/react-core/src/components/Toolbar/ToolbarChipGroupContent.tsx, packages/react-core/src/components/Toolbar/ToolbarExpandableContent.tsx, packages/react-core/src/components/Toolbar/ToolbarGroup.tsx, packages/react-core/src/components/Toolbar/ToolbarItem.tsx, packages/react-core/src/components/Toolbar/ToolbarToggleGroup.tsx, packages/react-core/src/components/Toolbar/__tests__/__snapshots__/ToolbarItem.test.tsx.snap, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
**What**: Closes #10018
Additional core bump PR
Towards: #9997, #9677
- Multifile upload (#9997): 
- Removed class "styles.multipleFileUploadStatusItemClose" that no longer exists
- Toolbar (#9677):
- removed application of `pf-m-chip-container` modifier on toolbar group in ToolbarExpandableContent.tsx
-  removed application of `pf-m-buttonGroup` modifier on toolbar group in 
- removed import of `@patternfly/react-tokens/dist/esm/c_toolbar__item_Width` since it no longer exists. also comment out `widths` prop application since it depends on the token.
- Removed `bulkSelect`, `overflowMenu`, `searchFilter` modifier applications on toolbar item
=> Bump core lts alphas

packages/react-core/src/components/Checkbox/Checkbox.tsx, packages/react-core/src/components/Radio/Radio.tsx
release candidates flagging this error introduced during https://github.com/patternfly/patternfly-react/pull/9830
=> fix: prevent console warning in checkbox & radio

packages/react-core/src/components/NotificationBadge/NotificationBadge.tsx, packages/react-core/src/components/NotificationBadge/__tests__/NotificationBadge.test.tsx, packages/react-core/src/components/NotificationBadge/__tests__/__snapshots__/NotificationBadge.test.tsx.snap, packages/react-core/src/components/NotificationBadge/examples/NotificationBadge.md, packages/react-core/src/components/NotificationBadge/examples/NotificationBadgeBasic.tsx, packages/react-core/src/components/NotificationBadge/examples/NotificationBadgeWithCount.tsx, packages/react-core/src/components/NotificationBadge/examples/notificationBadge.css, packages/react-integration/cypress/integration/notificationbadge.spec.ts
**What**: Closes #9811 
Core is removing the notification badge, this PR internally replaces our notification badge with the button component while keeping the external API the same.
Convenience link: https://patternfly-react-pr-10020.surge.sh/components/notification-badge
=> feat(NotificationBadge): refactor to use status buttons for penta

jest.config.js, packages/react-core/package.json, packages/react-core/src/components/Icon/Icon.tsx, packages/react-core/src/components/Icon/__tests__/Icon.test.tsx, packages/react-core/src/components/Icon/examples/BodyIconSizes.tsx, packages/react-core/src/components/Icon/examples/HeadingIconSizes.tsx, packages/react-core/src/components/Icon/examples/Icon.md, packages/react-core/src/components/Icon/examples/StandaloneIconSizes.tsx, yarn.lock
**What**: Closes #9988
I added the `case-anything` package to handle changing case (i.e. cameCase to kebab-case) for us, needed it for converting prop values to class names in the updated Icon tests.
Convenience link: https://patternfly-react-pr-10030.surge.sh/components/icon/
=> feat(Icon): add new icon sizes for penta

packages/react-core/src/components/MultipleFileUpload/MultipleFileUploadStatus.tsx, packages/react-core/src/components/MultipleFileUpload/MultipleFileUploadStatusItem.tsx, packages/react-core/src/components/MultipleFileUpload/__tests__/__snapshots__/MultipleFileUploadStatus.test.tsx.snap, packages/react-core/src/components/MultipleFileUpload/__tests__/__snapshots__/MultipleFileUploadStatusItem.test.tsx.snap
**What**: Closes #9997
Convenience link: https://patternfly-react-pr-10031.surge.sh/components/file-upload/multiple-file-upload
=> feat(MultipleFileUpload): update for penta

packages/react-core/package.json, packages/react-core/src/components/Tabs/TabContent.tsx, packages/react-core/src/components/Tabs/TabTitleIcon.tsx, packages/react-core/src/components/Tabs/Tabs.tsx, packages/react-core/src/components/Tabs/TabsContext.ts, packages/react-core/src/components/Tabs/__tests__/Generated/__snapshots__/TabContent.test.tsx.snap, packages/react-core/src/components/Tabs/__tests__/Tabs.test.tsx, packages/react-core/src/components/Tabs/__tests__/__snapshots__/Tabs.test.tsx.snap, packages/react-core/src/components/Tabs/examples/Tabs.md, packages/react-core/src/components/Tabs/examples/TabsBoxSecondary.tsx, packages/react-core/src/components/Tabs/examples/TabsNavSubtab.tsx, packages/react-core/src/components/Tabs/examples/TabsSubtabs.tsx, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-integration/cypress/integration/tabs.spec.ts, packages/react-integration/cypress/integration/tabuncontrolleddemo.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/TabsDemo/TabsDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/TabsDemo/TabsUncontrolledDemo.tsx, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
**What**: Closes #10043, closes #9909
[Codemod for tabs](https://github.com/patternfly/pf-codemods/issues/555)
[Preview for tabs](https://patternfly-react-pr-10044.surge.sh/components/tabs)
As an FYI this PR suffers (may suffer depending on whether it affects you) the same visual bug mentioned in the original Core PR, which that will require a followup.
This also bumps the core alphas as they're needed for this update.
Per convo with design during one of the Penta meetings, it was decided that the `secondary` styling for TabContent should only be enabled when the Tabs component has both `pf-m-box` and `pf-m-secondary`, as the background colors of the current tab and the tab content will match as intended. Consumers can still use a non-box Tabs with secondary TabContent styling, though. If …
=> feat(Tabs): consumed Penta updates

packages/react-core/src/components/FileUpload/FileUpload.tsx, packages/react-core/src/components/FileUpload/FileUploadField.tsx, packages/react-core/src/components/FileUpload/FileUploadHelperText.tsx, packages/react-core/src/components/FileUpload/__tests__/FileUploadField.test.tsx, packages/react-core/src/components/FileUpload/__tests__/FileUploadHelperText.test.tsx, packages/react-core/src/components/FileUpload/__tests__/__snapshots__/FileUpload.test.tsx.snap, packages/react-core/src/components/FileUpload/__tests__/__snapshots__/FileUploadField.test.tsx.snap, packages/react-core/src/components/FileUpload/__tests__/__snapshots__/FileUploadHelperText.test.tsx.snap, packages/react-core/src/components/FileUpload/examples/FileUpload.md, packages/react-core/src/components/FileUpload/examples/FileUploadCustomPreview.tsx, packages/react-core/src/components/FileUpload/examples/FileUploadCustomUpload.tsx, packages/react-core/src/components/FileUpload/examples/FileUploadTextWithRestrictions.tsx, packages/react-core/src/components/FileUpload/examples/FileUploadWithHelperText.tsx, packages/react-core/src/components/FileUpload/index.ts
**What**: Closes #9996
codemod: https://github.com/patternfly/pf-codemods/issues/551
=> feat(SimpleFileUpload): consumed Penta updates

.github/workflows/release.yml, package.json, packages/react-core/package.json, packages/react-core/scripts/cleanDistExports.js
**What**: Attempts to fix an issue in our shipped files caused by us now shipping our demos.
=> chore(build): add script to stop exporting demos in built files

packages/react-core/src/components/ToggleGroup/ToggleGroupItem.tsx, packages/react-core/src/components/ToggleGroup/examples/ToggleGroupDefaultMultiple.tsx
**What**: Closes #9982
No token update was necessary.
- updated 1 example to show toggle group at the top
- refactoring
**QUESTION**: in HTML examples https://pf6.patternfly.org/components/toggle-group#icon-and-text there is also a variant with icon **_after_** text. 
We currently don't support that in React - is it something we want? 
(I checked design guidelines and none of the examples shows the icon after text)
=> refactor(ToggleGroup)

packages/react-core/src/components/JumpLinks/JumpLinks.tsx, packages/react-core/src/components/JumpLinks/JumpLinksItem.tsx, packages/react-core/src/components/JumpLinks/__tests__/JumpLinks.test.tsx, packages/react-core/src/components/JumpLinks/__tests__/__snapshots__/JumpLinks.test.tsx.snap, packages/react-core/src/components/JumpLinks/examples/JumpLinksBasic.tsx, packages/react-core/src/components/JumpLinks/examples/JumpLinksExpandableVerticalWithSubsection.tsx, packages/react-core/src/components/JumpLinks/examples/JumpLinksVertical.tsx, packages/react-core/src/components/JumpLinks/examples/JumpLinksVerticalWithLabel.tsx, packages/react-core/src/components/JumpLinks/examples/JumpLinksWithCenteredList.tsx, packages/react-core/src/components/JumpLinks/examples/JumpLinksWithLabel.tsx
=> feat(JumpLinks): consumed Penta updates

packages/react-core/src/components/ActionList/ActionList.tsx, packages/react-core/src/components/ActionList/ActionListGroup.tsx, packages/react-core/src/components/ActionList/ActionListItem.tsx, packages/react-core/src/components/ActionList/__tests__/ActionListGroup.test.tsx, packages/react-core/src/components/ActionList/examples/ActionListSingleGroup.tsx, packages/react-core/src/components/ActionList/examples/ActionListWithCancelButton.tsx, packages/react-core/src/components/ActionList/examples/ActionListWithIcons.tsx
**What**: Towards #9677
Couple questions:
- For the "Action list with cancel button" example, should the "Cancel" button be in the same group as "Next" and "Back" buttons (how it is in Core), or should it be separate visually and structurally (how it is in this PR)? EDIT: update core example to use separate groups
- For the "Action list with icons" example, is it intended that that is the only time ActionListItem component should not be wrapped in an ActionListGroup? Or should we be consistent about always needing the ActionListGroup wrapping ActionListItem components? EDIT:~Open core issue to update pf-m-icons styling on pf-v5-c-action-list to also update group column-gap var (column-gap on action list should remain the same)~ PR opened by Matt - …
=> feat(ActionList): consumed Penta updates

packages/react-code-editor/README.md, packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx
=> feat(CodeEditor): pass additional props to monaco-editor, update readme

packages/react-core/src/components/JumpLinks/JumpLinks.tsx, packages/react-core/src/demos/JumpLinks.md, packages/react-core/src/demos/examples/JumpLinks/JumpLinksWithDrawer.js
**What**: Closes #9636
Possible improvements:
- rewrite demos to TypeScript
=> feat(JumpLinks): support passing a reference to scroll element

packages/react-core/src/components/MenuToggle/MenuToggle.tsx, packages/react-core/src/components/MenuToggle/examples/MenuToggleTypeahead.tsx, packages/react-core/src/components/Select/examples/SelectMultiTypeahead.tsx, packages/react-core/src/components/Select/examples/SelectMultiTypeaheadCheckbox.tsx, packages/react-core/src/components/Select/examples/SelectMultiTypeaheadCreatable.tsx, packages/react-core/src/components/Select/examples/SelectTypeahead.tsx, packages/react-core/src/components/Select/examples/SelectTypeaheadCreatable.tsx
=> fix(Menu toggle): Passed aria label prop value to typeahead variant

packages/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx, packages/react-core/src/components/ClipboardCopy/ClipboardCopyExpanded.tsx
Reverts patternfly/patternfly-react#9743
=> Revert "bug(ClipboardCopy): change children type to string"

packages/react-core/src/helpers/Popper/Popper.tsx
**What**: Closes #9936
@nicolethoen I guess this should fix the error, when I try to reproduce the bug in patternfly runtime, I get the `children is undefined` error right away from the docs build, so I cannot reproduce the bug properly
=> fix(Popper): check for undefined

packages/react-core/src/components/Select/Select.tsx
=> bug(Select): expose height and max height props for Menu content

packages/react-core/src/components/SearchInput/SearchInput.tsx, packages/react-core/src/components/TextInputGroup/TextInputGroupMain.tsx, packages/react-core/src/components/TextInputGroup/__tests__/TextInputGroupMain.test.tsx
=> feat(SearchInput): Add ability to add id to input in SearchInput component

packages/react-core/src/components/Button/Button.tsx, packages/react-core/src/components/CalendarMonth/examples/CalendarMonth.md, packages/react-core/src/components/Menu/MenuItemAction.tsx, packages/react-core/src/helpers/KeyboardHandler.tsx, packages/react-integration/cypress/integration/menu.spec.ts, packages/react-table/src/deprecated/components/Table/__tests__/__snapshots__/Table.test.tsx.snap
**What**: Closes #9985, closes #10076
There's some styling issues on hover for the menu item action. This is because in Core there's no `pf-v5-c-menu__item-action-icon` wrapper around the icon, while in React there is.
=> feat(Menu): consumed Penta updates

packages/react-charts/src/components/ChartLegendTooltip/ChartLegendTooltip.tsx
=> fix(charts) - ChartLegendTooltip.title has wrong type (#10129)

packages/react-core/src/components/Dropdown/Dropdown.tsx, packages/react-core/src/components/Menu/MenuContainer.tsx, packages/react-core/src/components/Pagination/PaginationOptionsMenu.tsx, packages/react-core/src/components/Select/Select.tsx
=> fix(Select): focus first item when opened by click

packages/react-core/src/components/MenuToggle/MenuToggle.tsx, packages/react-core/src/components/MenuToggle/__tests__/MenuToggle.test.tsx, packages/react-core/src/components/MenuToggle/__tests__/__snapshots__/MenuToggle.test.tsx.snap, packages/react-core/src/components/MenuToggle/examples/MenuToggle.md, packages/react-core/src/demos/DataList/examples/DataListBasic.tsx, packages/react-core/src/demos/examples/Tabs/TabsAndTable.tsx, packages/react-integration/demo-app-ts/src/components/demos/CardDemo/CardDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/DataListDemo/DataListDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/DualListSelectorDemo/DualListSelectorWithActionsDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/PageDemo/PageDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/ToolbarDemo/ToolbarDemo.tsx, packages/react-table/src/components/Table/ActionsColumn.tsx, packages/react-table/src/components/Table/examples/TableActionsOverflow.tsx, packages/react-table/src/components/Table/examples/TableSortableCustom.tsx, packages/react-table/src/demos/examples/TableColumnManagement.tsx, packages/react-table/src/demos/examples/TableColumnManagementWithDraggable.tsx, packages/react-table/src/demos/examples/TableCompact.tsx, packages/react-table/src/demos/examples/TableCompoundExpansion.tsx, packages/react-table/src/demos/examples/TableSortableResponsive.tsx, packages/react-table/src/demos/examples/TableStaticBottomPagination.tsx, packages/react-table/src/deprecated/components/Table/__tests__/__snapshots__/Table.test.tsx.snap, packages/react-table/src/deprecated/components/Table/examples/LegacyTableSortableCustom.tsx
**What**: Closes #9986
[Codemod](https://github.com/patternfly/pf-codemods/issues/584)
This also bumps the Core versions
=> feat(MenuToggle): consumed Penta updates

packages/react-core/src/components/DataList/examples/DataList.md, packages/react-core/src/components/DataList/examples/DataListWidthModifiers.tsx
**What**: Closes https://github.com/patternfly/patternfly-react/issues/10119
Removing old css tokens that won't be used in penta. This also updates the example to match core.
=> docs(DataList): remove old css tokens

packages/react-core/src/components/CalendarMonth/CalendarMonth.tsx
**What**: Closes #10135
Before:
https://github.com/patternfly/patternfly-react/assets/11218376/5e91bdab-833e-4124-9acd-d8115492e0f7
After:
https://github.com/patternfly/patternfly-react/assets/11218376/3142a649-c3d2-4935-b76d-25c2f5e2d1b0
=> fix(DatePicker) Address datepicker crashing when manually entering year

packages/react-core/src/components/DragDrop/examples/DragDrop.md
=> chore(Drag and drop): Marked old implementation as deprecated

packages/react-code-editor/README.md, packages/react-code-editor/package.json, packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx, yarn.lock
Adds the missing `monaco-editor` dependency to `@patternfly/react-code-editor`'s development dependencies. This ensures that it is installed during the build proccess, preventing errors.
This is needed because right now `monaco-editor` just happens to be installed because it is a dependency of `react-monaco-editor`, which is a dependency of `@patternfly/documentation-framework`. But once the documentation framework is upgraded, this dependency no longer exists, causing [build failures](https://github.com/patternfly/patternfly-react/actions/runs/8428322121/job/23080581638?pr=10189).
I've also modified the installation instructions to reflect to users that they must also install `monaco-editor`, since it is a peer dependency of `@patternfly/react-code-editor`.
=> chore(react-code-editor): add missing `monaco-editor` dependency

packages/react-core/src/components/Checkbox/Checkbox.tsx, packages/react-core/src/components/Checkbox/__tests__/Checkbox.test.tsx, packages/react-core/src/components/Form/FormFieldGroupHeader.tsx, packages/react-core/src/components/Form/FormGroup.tsx, packages/react-core/src/components/Form/FormGroupLabelHelp.tsx, packages/react-core/src/components/Form/__tests__/__snapshots__/FormGroup.test.tsx.snap, packages/react-core/src/components/Form/examples/Form.md, packages/react-core/src/components/Form/examples/FormBasic.tsx, packages/react-core/src/components/Form/examples/FormGroupLabelInfo.tsx, packages/react-core/src/components/Form/examples/FormLimitWidth.tsx, packages/react-core/src/components/Form/index.ts, packages/react-core/src/components/LoginPage/__tests__/__snapshots__/LoginForm.test.tsx.snap, packages/react-core/src/components/Modal/examples/ModalWithForm.tsx, packages/react-core/src/components/Radio/Radio.tsx, packages/react-core/src/components/Radio/__tests__/Radio.test.tsx, packages/react-core/src/components/Radio/__tests__/__snapshots__/Radio.test.tsx.snap, packages/react-core/src/components/Radio/examples/RadioReversed.tsx, packages/react-core/src/components/SearchInput/__tests__/__snapshots__/SearchInput.test.tsx.snap, packages/react-core/src/demos/examples/PasswordStrength/PasswordStrengthDemo.tsx, packages/react-core/src/next/components/Modal/examples/ModalWithForm.tsx, packages/react-integration/demo-app-ts/src/components/demos/FormDemo/FormDemo.tsx
**What**: Closes #9931, closes #10055
Things done:
- introduced `FormGroupLabelHelp` component to make using `labelIcon` prop simple
- added some spaces next to label in **FormGroup** to look similar to core
Breaking changes done:
- renamed `labelIcon` prop in **FormGroup** to `labelHelp`
- renamed `isLabelBeforeButton` prop in **Checkbox/Radio** to `labelPosition?: 'start' | 'end'`
Todo:
- update examples of **Checkbox** to show `isLabelWrapped` and `labelPosition="start"` (issue: https://github.com/patternfly/patternfly-react/issues/10085)
- (add Form control examples in React too)
=> Consume core Penta updates: Form controls, checkbox, radio

packages/react-core/src/demos/Filters/examples/FilterAttributeSearch.tsx, packages/react-core/src/demos/Filters/examples/FilterCheckboxSelect.tsx, packages/react-core/src/demos/Filters/examples/FilterFaceted.tsx, packages/react-core/src/demos/Filters/examples/FilterMixedSelectGroup.tsx, packages/react-core/src/demos/Filters/examples/FilterSameSelectGroup.tsx, packages/react-core/src/demos/Filters/examples/FilterSearchInput.tsx, packages/react-core/src/demos/Filters/examples/FilterSingleSelect.tsx, packages/react-core/src/demos/examples/Card/CardStatus.tsx, packages/react-core/src/demos/examples/Tabs/TabsAndTable.tsx, packages/react-integration/cypress/integration/tableselectable.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/TableDemo/TableComposableDemo.tsx, packages/react-table/src/components/Table/Th.tsx, packages/react-table/src/components/Table/__tests__/Th.test.tsx, packages/react-table/src/components/Table/examples/TableActions.tsx, packages/react-table/src/components/Table/examples/TableActionsOverflow.tsx, packages/react-table/src/components/Table/examples/TableCompoundExpandable.tsx, packages/react-table/src/components/Table/examples/TableDraggable.tsx, packages/react-table/src/components/Table/examples/TableExpandable.tsx, packages/react-table/src/components/Table/examples/TableNestedExpandable.tsx, packages/react-table/src/components/Table/examples/TableNestedStickyHeader.tsx, packages/react-table/src/components/Table/examples/TableNestedTableExpandable.tsx, packages/react-table/src/components/Table/examples/TableSelectableRadio.tsx, packages/react-table/src/components/Table/examples/TableStripedExpandable.tsx, packages/react-table/src/components/Table/utils/decorators/selectable.tsx, packages/react-table/src/demos/examples/TableBulkSelect.tsx, packages/react-table/src/demos/examples/TableCompoundExpansion.tsx, packages/react-table/src/deprecated/components/Table/__tests__/__snapshots__/Table.test.tsx.snap
**What**: Closes #10057 , closes #9969
=> fix(Table): updated a11y for empty/nontext Th components

packages/react-table/src/components/Table/ActionsColumn.tsx, packages/react-table/src/components/Table/TableTypes.tsx
**What**: Closes #8971 
Tested adding logic to open a Modal upon clicking an action item with the new `shouldCloseOnClick: false` and it works fine. Only thing is that `event.stopPropagation()` has to be called in whatever logic controls closing the Modal itself, so that will have to be handled by the consumer.
Another thing is that clicking with mouse when a modal is open will close the dropdown toggle, but that should be expected behavior since the `onOpenChange` callback controls closing the dropdown on click outside/Escape press. Without it the dropdown won't close unless an action item is clicked.
To test on the [table with actions example](https://patternfly-react-pr-10179.surge.sh/components/table#actions):
1. Add the following code at the top of the export of the example code:
``` …
```
=> fix(Table): added ActionsColumn prop to control close on click

packages/react-core/src/components/Chip/__tests__/ChipGroup.test.tsx, packages/react-core/src/components/ClipboardCopy/__tests__/ClipboardCopy.test.tsx, packages/react-core/src/components/ClipboardCopy/__tests__/__snapshots__/ClipboardCopy.test.tsx.snap, packages/react-core/src/components/Drawer/__tests__/Drawer.test.tsx, packages/react-core/src/components/Drawer/__tests__/DrawerPanelContent.test.tsx, packages/react-core/src/components/Drawer/__tests__/Generated/DrawerPanelContent.test.tsx, packages/react-core/src/components/Drawer/__tests__/Generated/__snapshots__/DrawerPanelContent.test.tsx.snap, packages/react-core/src/components/Drawer/__tests__/__snapshots__/Drawer.test.tsx.snap, packages/react-core/src/components/Form/__tests__/FormFieldGroup.test.tsx, packages/react-core/src/components/Form/__tests__/FormSection.test.tsx, packages/react-core/src/components/Form/__tests__/__snapshots__/FormFieldGroup.test.tsx.snap, packages/react-core/src/components/Form/__tests__/__snapshots__/FormSection.test.tsx.snap, packages/react-core/src/components/Label/__tests__/LabelGroup.test.tsx, packages/react-core/src/components/Label/__tests__/__snapshots__/LabelGroup.test.tsx.snap, packages/react-core/src/components/MultipleFileUpload/__tests__/MultipleFileUpload.test.tsx, packages/react-core/src/components/MultipleFileUpload/__tests__/MultipleFileUploadStatus.test.tsx, packages/react-core/src/components/MultipleFileUpload/__tests__/__snapshots__/MultipleFileUploadStatus.test.tsx.snap, packages/react-core/src/components/SearchInput/__tests__/SearchInput.test.tsx, packages/react-core/src/components/SearchInput/__tests__/__snapshots__/SearchInput.test.tsx.snap, packages/react-core/src/components/Tabs/__tests__/Tabs.test.tsx, packages/react-core/src/components/Tabs/__tests__/__snapshots__/Tabs.test.tsx.snap, packages/react-core/src/components/Toolbar/__tests__/Toolbar.test.tsx, packages/react-core/src/components/Toolbar/__tests__/__snapshots__/Toolbar.test.tsx.snap, packages/react-core/src/deprecated/components/Select/__tests__/Select.test.tsx, packages/react-core/src/deprecated/components/Select/__tests__/__snapshots__/Select.test.tsx.snap, packages/react-core/src/helpers/GenerateId/GenerateId.ts, packages/react-core/src/helpers/GenerateId/__mocks__/GenerateId.ts, packages/react-core/src/helpers/GenerateId/__tests__/GenerateId.test.tsx
=> fix(GenerateId): add randomness to id generator to prevent id collisions

packages/react-core/package.json, packages/react-core/src/components/Drawer/DrawerContent.tsx, packages/react-core/src/components/Drawer/examples/DrawerSecondaryBackground.tsx, packages/react-core/src/components/Page/Page.tsx, packages/react-core/src/components/Page/__tests__/__snapshots__/Page.test.tsx.snap, packages/react-core/src/layouts/Bullseye/examples/Bullseye.md, packages/react-core/src/layouts/Bullseye/examples/bullseye.css, packages/react-core/src/layouts/Flex/examples/Flex.md, packages/react-core/src/layouts/Flex/examples/flex.css, packages/react-core/src/layouts/Gallery/examples/Gallery.md, packages/react-core/src/layouts/Gallery/examples/gallery.css, packages/react-core/src/layouts/Grid/examples/Grid.md, packages/react-core/src/layouts/Grid/examples/grid.css, packages/react-core/src/layouts/Level/examples/Level.md, packages/react-core/src/layouts/Level/examples/level.css, packages/react-core/src/layouts/Split/examples/Split.md, packages/react-core/src/layouts/Split/examples/split.css, packages/react-core/src/layouts/Stack/examples/Stack.md, packages/react-core/src/layouts/Stack/examples/stack.css, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-integration/cypress/integration/jumplinks.spec.ts, packages/react-styles/package.json, packages/react-tokens/package.json, packages/react-tokens/scripts/generateTokens.js, yarn.lock
**What**: Closes #10203
* Added div around page-main for page-main-container
* Replaced noBackground with primary for DrawerContent and separated into a new enum.
* Updated layout custom CSS and md with core bump
* Updated core ver to 107
* Added temp fix for tokens parsing
=> feat(Page,Drawer): core bump and updates

packages/react-core/src/components/Card/Card.tsx, packages/react-core/src/components/Card/CardHeader.tsx, packages/react-core/src/components/Card/examples/Card.md, packages/react-core/src/components/Card/examples/CardClickableSelectable.tsx, packages/react-core/src/components/Card/examples/CardSelectable.tsx, packages/react-core/src/components/Card/examples/CardSingleSelectable.tsx, packages/react-integration/cypress/integration/card.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/CardDemo/CardDemo.tsx
=> fix(Card): updated v5 logic to prevent unclickable cards

packages/react-core/src/components/Label/Label.tsx, packages/react-core/src/components/Label/examples/LabelCompact.tsx, packages/react-core/src/components/Label/examples/LabelFilled.tsx, packages/react-core/src/components/Label/examples/LabelOutline.tsx
**What**: Closes #10195 for `main` branch, `v6` update is yet to done
1. React main branch probably needs a core bump, styles from core are not applied, because the `pf-m-disabled` token (`styles.modifiers.disabled`) is missing. Markup is the same with one exception:
2. Close button in core has these attributes: `class="pf-v5-c-button pf-m-plain" disabled=""`, to achieve this in React, we would have to pass only `disabled` attribute to the Button component. But internally, Button applies {...props} before specifying `disabled={isButtonElement ? isDisabled : null}` attribute. So it always will be overwritten by the latter, and the only way to achieve `disabled=""` is thus with the `isDisabled` prop. Applying the `isDisabled` prop will however lead to this markup: …
=> feat(Label): allow clickable labels to be disabled

packages/react-core/src/components/MenuToggle/MenuToggle.tsx, packages/react-core/src/components/MenuToggle/examples/MenuToggle.md, packages/react-core/src/components/MenuToggle/examples/MenuToggleSplitButtonCheckboxWithToggleText.tsx
Allows toggle button text for a split button menu toggle, by passing `children` to `MenuToggle` (instead of `MenuToggleCheckbox` in the example).
=> feat(MenuToggle): allow split action toggle text

packages/react-core/src/components/Label/Label.tsx, packages/react-core/src/components/Label/__tests__/Label.test.tsx
=> test(Label): add tests for disabled labels

packages/react-core/src/components/Pagination/Navigation.tsx, packages/react-core/src/components/Pagination/Pagination.tsx
Refactors the types of the pagination navigation so that they will compile when upgrading to TypeScript 5. This is needed to land #10156.
=> chore: fix types for pagination navigation

packages/react-core/src/components/NumberInput/NumberInput.tsx
Refactors the types of the number input so that they will compile when upgrading to TypeScript 5. This is needed to land #10156.
=> chore: fix types for number input

scripts/build-single-packages.js, scripts/parse-dynamic-modules.js
This PR modifies `scripts/build-single-packages.js` so that a `dist/dynamic-modules.json` file is generated for each package containing dynamic modules.
```sh
$ find . -name dynamic-modules.json
./packages/react-core/dist/dynamic-modules.json
./packages/react-icons/dist/dynamic-modules.json
./packages/react-table/dist/dynamic-modules.json
./packages/react-templates/dist/dynamic-modules.json
```
We generate `dynamic-modules.json` files to make it easier for consuming projects to share specific PatternFly dynamic modules (instead of sharing the whole package indexes) via [webpack module federation](https://webpack.js.org/concepts/module-federation/).
Each `dynamic-modules.json` file maps package index exports to their corresponding dynamic modules, for example:
```jsonc
// …
```
=> Generate dist/dynamic-modules.json for relevant packages

packages/react-core/src/components/ToggleGroup/ToggleGroupItem.tsx, packages/react-core/src/components/ToggleGroup/examples/ToggleGroupTextIcon.tsx
=> feat(Toggle group): Add support for icon position

packages/react-core/src/components/Drawer/DrawerPanelContent.tsx, packages/react-core/src/components/Page/Page.tsx
=> feat(Page): add prop to set width of drawer

packages/react-drag-drop/src/next/components/DragDrop/DragDropSort.tsx, packages/react-drag-drop/src/next/components/DragDrop/__tests__/DragDrop.test.tsx
**What**: Closes #10090
Change was done based on this [comment](https://github.com/clauderic/dnd-kit/issues/464#issuecomment-1008316262) from the author of the `dnd-kit` package.
I assume that a div with `id="root"` will always be present in a React app, which I don't know if it is 100% true.
We should also do this change for V6 once DragDrop is removed from the `next` folder.
=> fix(DragDropSort): fix positioning of DragOverlay

packages/react-docs/patternfly-docs/patternfly-docs.source.js
Opened as follow on to https://github.com/patternfly/patternfly-org/pull/3981
Fixes the ignore paths for the examples/tests/mocks when the docs go to find props tables.
=> feat(docs): fix props ignore paths

packages/react-core/src/components/DatePicker/DatePicker.tsx
=> fix(Datepicker): revalidate on validators prop change

packages/react-core/src/components/Wizard/Wizard.tsx, packages/react-core/src/components/Wizard/WizardBody.tsx, packages/react-core/src/components/Wizard/WizardContext.tsx, packages/react-core/src/components/Wizard/WizardNavItem.tsx, packages/react-core/src/components/Wizard/WizardToggle.tsx, packages/react-core/src/components/Wizard/__tests__/Wizard.test.tsx, packages/react-core/src/components/Wizard/examples/Wizard.md, packages/react-core/src/components/Wizard/examples/WizardFocusOnNextBack.tsx, packages/react-core/src/components/Wizard/examples/WizardWithCustomFooter.tsx
**What**: Closes #10249
Some comments on changes below
=> fix(Wizard): added prop to focus content on next/back

packages/react-core/src/components/Toolbar/Toolbar.tsx, packages/react-core/src/components/Toolbar/__tests__/Toolbar.test.tsx, packages/react-core/src/components/Toolbar/examples/Toolbar.md, packages/react-core/src/components/Toolbar/examples/ToolbarColorVariant.tsx
**What**: Closes #10226 
**Additional issues**: Followup to https://github.com/patternfly/patternfly/pull/6490
=> feat(toolbar): adds color variant

packages/react-core/src/deprecated/components/ApplicationLauncher/examples/ApplicationLauncher.md
**What**: Closes #10304 
convenience  link: https://patternfly-react-pr-10305.surge.sh/components/menus/application-launcher/react-deprecated#router-link
=> fix(chore): Fix broken application launcher example.

.github/workflows/release.yml
Fixes the release job that is currently broken on `main`, I was a bit too optimistic in my code removal. This restores the token passed into `action/checkout` and also fetches all the tags from Git, as was done previously. I have no way of testing this on short notice, but I am fairly confident this should fix the issue.
=> bug(ci): fix broken release job

.github/actions/setup-project/action.yml
Fixes an issue where the CI will sometimes break due to a Node.js crash that seems related to the way V8 handles the compile cache (https://github.com/nodejs/node/issues/51555). The problem seems to be mitigated by disabling the compile cache for now, and is likely resolved by upgrading to a new LTS version in the future.
This issue seems to only occur on CI, as I was not able to reproduce it locally with the same version of Node.js, and this is likely related to the specific way the GitHub actions runners are set up. So I believe this will not impact local development.
=> fix(ci): prevent V8 crashes during build

packages/react-core/src/components/MenuToggle/MenuToggle.tsx, packages/react-core/src/components/Select/Select.tsx, packages/react-core/src/components/Select/examples/SelectTypeahead.tsx, packages/react-templates/src/components/Select/SelectTypeahead.tsx, packages/react-templates/src/components/Select/examples/SelectTemplates.md, packages/react-templates/src/components/Select/examples/SelectTypeaheadDemo.tsx, packages/react-templates/src/components/Select/index.ts
**What**: Closes #10113
Based on changes from https://github.com/patternfly/patternfly-react/pull/10207. For this PR, only the last 2 commits: bb7e7f8a530fb40b601dc46395f96235e6a0c14c dacd40dc485497d9466fb66a0e64866bea2effb9 should be reviewed
TODO: add tests (possibly as a followup, once the changes from this PR are confirmed)
=> feat(Select): Typeahead template

packages/react-charts/src/components/Chart/Chart.tsx, packages/react-charts/src/components/ChartAxis/ChartAxis.tsx, packages/react-charts/src/components/ChartBullet/ChartBullet.tsx, packages/react-charts/src/components/ChartBullet/ChartBulletComparativeMeasure.tsx, packages/react-charts/src/components/ChartBullet/ChartBulletComparativeWarningMeasure.tsx, packages/react-charts/src/components/ChartBullet/ChartBulletGroupTitle.tsx, packages/react-charts/src/components/ChartBullet/ChartBulletTitle.tsx, packages/react-charts/src/components/ChartBullet/utils/chart-bullet-theme.ts, packages/react-charts/src/components/ChartCursorContainer/ChartCursorContainer.tsx, packages/react-charts/src/components/ChartDonut/ChartDonut.tsx, packages/react-charts/src/components/ChartLegend/ChartLegend.tsx, packages/react-charts/src/components/ChartTheme/ChartTheme.ts, packages/react-charts/src/components/ChartTheme/ChartThemeColor.ts, packages/react-charts/src/components/ChartTheme/ChartThemeTypes.ts, packages/react-charts/src/components/ChartTheme/themes/base-theme.ts, packages/react-charts/src/components/ChartTheme/themes/colors/skeleton-theme.ts, packages/react-charts/src/components/ChartTheme/themes/skeleton-theme.ts, packages/react-charts/src/components/ChartThreshold/examples/ChartThreshold.md, packages/react-charts/src/components/ChartUtils/chart-theme-types.ts, packages/react-charts/src/components/ChartUtils/chart-theme.ts, packages/react-charts/src/components/ResizeObserver/examples/resizeObserver.md, packages/react-charts/src/components/Skeletons/examples/skeletons.md
The UX design team wants to show chart skeletons in place of a generic empty state.
I created a new theme to fill-in all labels grey, but also removed chart interactions like tooltips, cursors, etc.
Developers can provide their own fake data to represent their graphs or copy the examples provided.
For UX design and mocks, please see https://github.com/patternfly/patternfly-react/issues/10310
**Examples**
https://patternfly-react-pr-10311.surge.sh/charts/skeletons
=> feat(charts): skeletons

packages/react-core/src/components/Select/Select.tsx, packages/react-core/src/components/Select/examples/SelectMultiTypeahead.tsx, packages/react-core/src/components/Select/examples/SelectMultiTypeaheadCheckbox.tsx, packages/react-core/src/components/Select/examples/SelectMultiTypeaheadCreatable.tsx, packages/react-core/src/components/Select/examples/SelectTypeahead.tsx, packages/react-core/src/components/Select/examples/SelectTypeaheadCreatable.tsx, packages/react-templates/src/components/Select/SelectTypeahead.tsx
**What**: Closes #10180
- introduces new prop `shouldFocusFirstMenuItemOnOpen` in `Select`, because typeahead would auto focus on the first item (instead of keeping the focus on the input)
- adds `tabindex={-1}` to the `MenuToggle` arrow button for typeahead variant to prevent being able to use typeahead as a classic select and focus items (I wonder if this might break some consumer's tests and we should warn them?)
- hover on MenuItem and keep the cursor there, then move in the menu via arrows up/down -> the originally hovered item will still have the hovered styling (which is not ideal when the hover and focus styling looks the same)
=> feat(Select): Typeahead example

packages/react-core/src/components/ToggleGroup/examples/ToggleGroup.md
=> docs(toggle-group): Adds example documentation.

packages/react-templates/src/components/Dropdown/DropdownSimple.tsx, packages/react-templates/src/components/Dropdown/__tests__/DropdownSimple.test.tsx, packages/react-templates/src/components/Dropdown/__tests__/__snapshots__/DropdownSimple.test.tsx.snap, packages/react-templates/src/components/Dropdown/examples/DropdownSimpleExample.tsx, packages/react-templates/src/components/Dropdown/examples/DropdownTemplates.md, packages/react-templates/src/components/Dropdown/index.ts, packages/react-templates/src/components/index.ts
=> feat(Dropdown): Added simple template

packages/react-core/src/components/Button/examples/ButtonInlineSpanLink.tsx, packages/react-core/src/components/Form/FormGroupLabelHelp.tsx, packages/react-core/src/components/Form/examples/FormBasic.tsx, packages/react-core/src/components/Form/examples/FormGroupLabelInfo.tsx, packages/react-core/src/components/Form/examples/FormLimitWidth.tsx, packages/react-core/src/components/Modal/examples/ModalWithForm.tsx, packages/react-core/src/demos/SearchInput/SearchInput.md, packages/react-core/src/demos/examples/PasswordStrength/PasswordStrengthDemo.tsx, packages/react-core/src/next/components/Modal/examples/ModalWithForm.tsx, packages/react-integration/demo-app-ts/src/components/demos/FormDemo/FormDemo.tsx, packages/react-table/src/components/Table/Table.tsx
**What**: Closes #10158
I am not sure if the last two commits are necessary. I did them so the `<div style="display: contents;">` is not present in the markup and there is no better way to hide it from Popover than by passing both the `children` and the `triggerRef` prop to Popover.
=> feat(FormGroupLabelHelp): update markup to match core

packages/react-core/src/components/Tabs/Tabs.tsx
=> fix(Tabs): uncontrolled Tabs react to updated defaultActiveKey

packages/react-charts/src/components/ChartTooltip/examples/ChartTooltip.md
Created a donut example showing the chart's tooltip in a fixed position.
Live example: https://patternfly-react-pr-10338.surge.sh/charts/tooltips#fixed-tooltip
Closes https://github.com/patternfly/patternfly-react/issues/10337
=> Chart examples - demo tooltip in a fixed position

packages/react-core/src/components/Tooltip/Tooltip.tsx, packages/react-core/src/components/Truncate/Truncate.tsx, packages/react-core/src/components/Truncate/__tests__/Truncate.test.tsx
**What**: Closes #10053 
**Additional issues**: I have also added `hidden` prop to the `Tooltip` component which is useful both for this issue and in general
=> fix(truncate) tooltip shows without truncation

packages/react-core/src/components/Checkbox/examples/Checkbox.md, packages/react-core/src/components/Checkbox/examples/CheckboxLabelWraps.tsx, packages/react-core/src/components/Checkbox/examples/CheckboxReversed.tsx, packages/react-core/src/components/Radio/examples/Radio.md
=> docs(Checkbox): add examples of reversed and label wraps

packages/react-core/src/components/NotificationDrawer/NotificationDrawerGroup.tsx, packages/react-core/src/deprecated/components/OptionsMenu/OptionsMenuItemGroup.tsx, packages/react-core/src/deprecated/components/Select/Select.tsx, packages/react-table/src/components/Table/TableTypes.tsx, packages/react-table/src/deprecated/components/Table/examples/Table.md
=> chore: remove redundant string type

.github/promote.sh, .github/workflows/promote.yml, .github/workflows/release.yml
Cleans up the release and promote workflows so that secrets are only being passed where used, as well as removing some redundant code.
=> chore(ci): clean up release and promote workflows

packages/react-charts/src/components/ChartUtils/chart-tooltip.ts
Preserve tooltip whitespace for Safari
Closes https://github.com/patternfly/patternfly-react/issues/10354
=> fix(charts): tooltip whitespace is not preserved for Safari

.github/renovate.json
Changes the Renovate configuration to extend the [recommended preset](https://docs.renovatebot.com/presets-config/#configrecommended), and configures it to exclude major upgrades (for now).
The reason for this is that a lot of minor and patch upgrades being skipped because they are getting bunched up into big PRs that fail the CI (see #9970, #9970). The recommended preset will instead create a separate PR for each dependency, increasing the chances of a successful merge that doesn't hold up other updates.
To avoid queuing up too many PRs the limit of the recommended config is set to a [maximum of 10 branches](https://docs.renovatebot.com/configuration-options/#branchconcurrentlimit) at any given time (CVEs excluded), this can be seen in action on [my …
=> chore: enable default configuration for Renovate

packages/react-core/src/demos/examples/PasswordStrength/PasswordStrengthDemo.tsx
=> fix(PasswordStrength) remove popover in demo

.github/workflows/release.yml
Cancels the release workflow if a new commit is pushed that could create failures if the workflows start competing for Git tags needed for release. This uses the [`concurrency`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-concurrency-and-the-default-behavior) feature in GitHub actions to automatically cancel any runs before the last.
=> chore(ci): cancel release workflow if new release is triggered

.github/workflows/documentation.yml
Fixes a bug where the documentation deployed under PRs is instead deployed from `main`, causing the wrong version to be uploaded.
=> fix(ci): check out `HEAD` of PR when building documentation

packages/eslint-plugin-patternfly-react/package.json, yarn.lock
Removes the `eslint-plugin-node` dependency from `eslint-plugin-patternfly-react`, as it is [no longer](https://github.com/mysticatea/eslint-plugin-node#readme) actively maintained. It also appears that the dependency was never used anywhere in the first place, as none of the configurations in `eslint-plugin-patternfly-react` refer to this dependency.
Supersedes #10376
=> core(deps): remove `eslint-plugin-node` dependency

packages/react-charts/src/components/ChartBullet/__snapshots__/ChartBullet.test.tsx.snap, packages/react-charts/src/components/ChartBullet/__snapshots__/ChartBulletQualitativeRange.test.tsx.snap, packages/react-core/package.json, packages/react-core/src/components/Toolbar/ToolbarGroup.tsx, packages/react-core/src/components/Toolbar/ToolbarItem.tsx, packages/react-core/src/components/Toolbar/ToolbarToggleGroup.tsx, packages/react-core/src/components/Toolbar/examples/Toolbar.md, packages/react-core/src/components/Toolbar/examples/ToolbarSpacers.tsx, packages/react-core/src/demos/DashboardHeader.tsx, packages/react-core/src/demos/NotificationDrawer/examples/NotificationDrawerBasic.tsx, packages/react-core/src/demos/NotificationDrawer/examples/NotificationDrawerGrouped.tsx, packages/react-core/src/demos/RTL/examples/PaginatedTable.jsx, packages/react-core/src/demos/RTL/examples/PaginatedTable.tsx, packages/react-core/src/demos/examples/Masthead/MastheadWithUtilitiesAndUserDropdownMenu.tsx, packages/react-core/src/demos/examples/Nav/NavFlyout.tsx, packages/react-core/src/demos/examples/Nav/NavHorizontal.tsx, packages/react-core/src/demos/examples/Nav/NavHorizontalWithSubnav.tsx, packages/react-core/src/demos/examples/Nav/NavManual.tsx, packages/react-core/src/demos/examples/Page/PageStickySectionBreadcrumb.tsx, packages/react-core/src/demos/examples/Page/PageStickySectionGroup.tsx, packages/react-core/src/demos/examples/Page/PageStickySectionGroupAlternate.tsx, packages/react-core/src/helpers/util.ts, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-styles/package.json, packages/react-table/src/demos/DashboardHeader.tsx, packages/react-tokens/package.json, yarn.lock
**What**: Closes #10387 
Couple notes (in addition to the one below in another comment):
- I imagine we'll want to add these same props onto ToolbarContent since Core supports it. Opted to not include it here since we don't currently, and the API may be even more verbose since we currently don't have a separate ContentSection component. So we may end up needing props like `gap`, `sectionGap` and so on.
- May be worth a followup at some point (not necessarily for v6) to simplify the API in terms of these new/replacement props. `gapNone" etc end up verbose, and it'd be great if we could simplify it to just "none" and so on.
=> feat(Toolbar): updated spacer props to gap

.github/renovate.json
Configures Renovate to [bump](https://docs.renovatebot.com/configuration-options/#rangestrategy) the versions in the package file, instead of only the lockfile, which helps keeps the versions consistent between them.
=> chore(ci): configure Renovate to bump package versions

package.json, packages/rollup.base.mjs, yarn.lock
Restores the SVG plugin that was removed under #10389, this is needed for the `v6` branch, which still imports SVGs. This should fix the CI for #10478
=> chore: restore SVG plugin in Rollup config

packages/react-core/src/components/Page/examples/Page.md, packages/react-core/src/components/Page/examples/PageMainSectionVariations.tsx, packages/react-core/src/components/Page/examples/page.css
**What**: Closes #9868
- `Section with type="nav" for tertiary navigation`: the `tertiary` navigation was removed in V6, we should rename it in the upcoming React example for V6 and the Core V6 example too - but what is the `type="nav"` used for in V6 if not tertiary navigation?
=> docs(Page): add example showing different type prop variants

packages/react-core/src/components/Modal/Modal.tsx, packages/react-core/src/components/Modal/ModalContent.tsx
=> feat(Modal): support ReactNode type for 'title' prop

packages/react-core/src/components/CalendarMonth/CalendarMonth.tsx, packages/react-core/src/components/DatePicker/DatePicker.tsx
Closes #9933
- shows styling on a range even if some of the dates of the range (including `rangeStart`) may be disabled with the `validators` prop
- tries to autofocus the `dateProp` first (rangeEnd) over rangeStart. If no dateProp is given, tries to autofocus the `rangeStart` over today
Related to discussion on the working session - I decided **not** to attempt to find a closest focusable date, neither to add the prop to customize which month should be open. It might be useful only in rare use case like having a validator that disables large amount of dates (and it could complicate things more than be useful). - but let me know if it is something we might want to add
=> fix(DatePicker/CalendarMonth): better range styling when some dates are disabled

packages/react-core/src/components/MenuToggle/examples/MenuToggle.md
=> docs(menu-toggle): Adds docs for split button examples.

packages/react-core/src/components/EmptyState/index.ts, packages/react-core/src/demos/Filters/FilterDemos.md, packages/react-core/src/deprecated/components/Wizard/examples/Wizard.md, packages/react-docs/package.json, packages/react-table/src/demos/examples/TableEmptyStateDefault.tsx, packages/react-table/src/demos/examples/TableEmptyStateError.tsx, packages/react-table/src/demos/examples/TableEmptyStateLoading.tsx, packages/react-table/src/demos/examples/TableFilterable.tsx, yarn.lock
=> fix(EmptyState): Removed export of Header and Icon subcomponents

packages/react-core/src/demos/DescriptionList/DescriptionList.md, packages/react-core/src/demos/DescriptionList/examples/DescriptionListBasic.tsx
**What**: Closes https://github.com/patternfly/patternfly-react/issues/7000
Add description list basic demo
=> Add description list basic demo

package.json, packages/react-charts/package.json, packages/react-core/package.json, packages/react-icons/package.json, packages/react-styles/package.json, packages/react-styles/scripts/generateClassMaps.js, packages/react-tokens/package.json, packages/react-tokens/scripts/generateTokens.js, scripts/build-single-packages.js, scripts/parse-dynamic-modules.js, yarn.lock
Upgrades `glob` to the latest version and share it as a development dependency for the entire workspace.
=> chore(deps): upgrade `glob` to latest version

packages/react-core/src/next/components/Modal/ModalBoxTitle.tsx, packages/react-core/src/next/components/Modal/ModalHeader.tsx, packages/react-core/src/next/components/Modal/__tests__/ModalBoxTitle.test.tsx, packages/react-core/src/next/components/Modal/__tests__/__snapshots__/ModalBoxTitle.test.tsx.snap
=> feat(Modal Next): Added status variant styling to title

.github/workflows/stale.yml, .github/workflows/triage-stale-issues.yml
**What**: Towards #10525 
What I know this PR should do (assuming the stale actions docs are accurate):
- Change the stale label to `stale` instead of `wontfix`
- Stop PRs and issues from being closed due to being stale
What I think it should also do (this wasn't supported by stale action so I had to DIY it):
- Update the status back to `Needs triage` in the project board so that it can be re-prioritized
=> chore(CI): Update stale action to not close things

package.json, packages/transformer-cjs-imports/index.js, packages/transformer-react-styles-esm-imports/index.ts, yarn.lock
**What**: Closes #10522 
V6 version of https://github.com/patternfly/patternfly-react/pull/10477
It seems that our custom TS transformers haven't been working, probably since the TS version bump.
This PR updates ts-patch (which gets them running again) and updates them to work with our current TS version.
To test pull this branch, do a build, and verify that the files in react-core/dist/js have their dist/esm import paths properly updated to dist/js. Compare to line seven of this [dist/js file in our latest v5 prerelease](https://www.unpkg.com/browse/@patternfly/react-core@5.4.0-prerelease.14/dist/js/components/AboutModal/AboutModal.js) where it's trying to import from the ESM build.
=> fix(build): get our custom TS transformers working again (v6)

packages/react-code-editor/src/components/CodeEditor/examples/CodeEditorShortcutMainHeader.tsx
=> fix(CodeEditor) support Mac and PC shortcuts in example

packages/react-templates/src/components/Select/__tests__/SimpleSelect.test.tsx, packages/react-templates/src/components/Select/__tests__/TypeaheadSelect.test.tsx, packages/react-templates/src/components/Select/__tests__/__snapshots__/SimpleSelect.test.tsx.snap, packages/react-templates/src/components/Select/__tests__/__snapshots__/TypeaheadSelect.test.tsx.snap
**What**: Closes #10069
Adds unit tests for TypeaheadSelect template
=> feat(templates): add TypeaheadSelect tests

packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx
=> fix(expandable section): Fix uncaught exception

packages/react-table/src/components/Table/Tr.tsx, packages/react-table/src/components/Table/examples/TableCompoundExpandable.tsx
**What**: Closes #10321 for V5
=> fix(Table): compound expansion table row styles

package.json
Limits the depth of the Yarn workspaces to one level to prevent `package.json` files in the distribution from being picked up.
=> fix: limit depth of Yarn workspaces

packages/react-templates/src/components/Select/CheckboxSelect.tsx, packages/react-templates/src/components/Select/SimpleSelect.tsx, packages/react-templates/src/components/Select/__tests__/__snapshots__/CheckboxSelectSnapshots.test.tsx.snap, packages/react-templates/src/components/Select/examples/CheckboxSelectDemo.tsx, packages/react-templates/src/components/Select/examples/SimpleSelectDemo.tsx
**What**: 
Closes #10732
Handle initial selected options and options that get updated.
=> fix(SimpleSelect,CheckboxSelect): Handle initial selection(s)

packages/react-core/src/components/Wizard/Wizard.tsx, packages/react-core/src/components/Wizard/WizardContext.tsx
**What**: Closes #9752
Adds two useEffect blocks to update steps when the initial children change, and reset the active step index when the children change.
This [codesandbox](https://codesandbox.io/s/competent-fire-dd3vgr?file=/index.tsx) from the issue can be pasted into one of our Wizard examples to verify the fix.
=> fix(Wizard): allow dynamic step update

packages/react-code-editor/README.md
**What**: Closes #10664
Updates docs to clarify edge cases where additional configuration and webpack plugins may be required, as `monaco-editor` is not bundled with `react-code-editor`.
=> docs(CodeEditor): document CDN workaround

packages/react-core/src/components/DragDrop/Draggable.tsx, packages/react-core/src/components/DragDrop/examples/DragDropMultipleLists.tsx
Updated example for multi list to use flex so that target list will maintain size when empty
**What**: Closes #9749 
=> chore(Drag and drop): Updated example for multi list to use flex 

packages/react-core/src/components/Pagination/Pagination.tsx, packages/react-core/src/components/Pagination/PaginationOptionsMenu.tsx
=> feat(Pagination): allowed customizing appendTo of options menu

packages/react-core/src/components/Pagination/PaginationOptionsMenu.tsx, packages/react-core/src/components/Pagination/__tests__/Generated/__snapshots__/PaginationOptionsMenu.test.tsx.snap, packages/react-core/src/components/Pagination/__tests__/__snapshots__/Pagination.test.tsx.snap
=> feat(Pagination): Added wrapper around menu toggle

packages/react-table/src/components/Table/examples/Table.md, packages/react-table/src/components/Table/examples/TableEditable.tsx
=> docs(Table): add Editable Table example

packages/react-templates/src/components/Select/MultiTypeaheadSelect.tsx, packages/react-templates/src/components/Select/__tests__/MultiTypeaheadSelect.test.tsx, packages/react-templates/src/components/Select/__tests__/__snapshots__/MultiTypeaheadSelect.test.tsx.snap, packages/react-templates/src/components/Select/examples/MultiTypeaheadSelectDemo.tsx, packages/react-templates/src/components/Select/examples/SelectTemplates.md, packages/react-templates/src/components/Select/index.ts
**What**:
Closes #10733 
Adds a `MultiTypeaheadSelect` component to the @patternfly/react-templates package and a demo of the component for the docs apge.
=> feat(MultiTypeaheadSelect): Add MultiTypeaheadSelect to react-templates

packages/react-core/src/components/MenuToggle/MenuToggle.tsx
**What**: Closes #10774 (for v5)
Replaces custom styling with new `pf-m-text` modifier.
=> feat(MenuToggle): replace custom styles with text modifier

packages/react-core/src/components/Wizard/Wizard.tsx, packages/react-core/src/components/Wizard/WizardContext.tsx
**What**: Fix / followup to #10748
You can compare the new behaviors against the previous PR's surge https://patternfly-react-pr-10748.surge.sh/components/wizard#enabled-on-form-validation (step navigation was not updating, and changing the age field was resetting the wizard).
=> fix(Wizard): only update new steps when step count changes

packages/react-templates/src/components/Select/TypeaheadSelect.tsx
**What**:
Closes #10789 
Updates the input text correctly when the selection is updated.
Adds a customizable message to the menu when there are no options available.
=> fix(TypeaheadSelect): Correctly show the newly selected item on selection

packages/react-core/src/components/Dropdown/Dropdown.tsx, packages/react-core/src/components/SearchInput/__tests__/__snapshots__/SearchInput.test.tsx.snap, packages/react-core/src/components/Select/Select.tsx, packages/react-core/src/deprecated/components/Dropdown/DropdownMenu.tsx, packages/react-core/src/deprecated/components/Dropdown/InternalDropdownItem.tsx, packages/react-core/src/helpers/Popper/Popper.tsx, packages/react-integration/cypress/integration/dropdowndeprecated.spec.ts, packages/react-templates/src/components/Select/__tests__/CheckboxSelect.test.tsx, packages/react-templates/src/components/Select/__tests__/MultiTypeaheadSelect.test.tsx, packages/react-templates/src/components/Select/__tests__/SimpleSelect.test.tsx, packages/react-templates/src/components/Select/__tests__/__snapshots__/MultiTypeaheadSelect.test.tsx.snap
**What**: Closes #10790
Also goes towards https://github.com/patternfly/patternfly-react/issues/10511 that was closed by another fix
=> fix(Popper): added display styling to prevent page scroll

packages/react-core/src/components/Label/Label.tsx, packages/react-core/src/components/Label/__tests__/Label.test.tsx, packages/react-core/src/components/Label/__tests__/__snapshots__/Label.test.tsx.snap, packages/react-core/src/components/Label/__tests__/__snapshots__/LabelGroup.test.tsx.snap
**What**: towards #10800 v6 fix
=> fix(Label):Added button type V6

packages/react-templates/src/components/Select/TypeaheadSelect.tsx, packages/react-templates/src/components/Select/examples/TypeaheadSelectDemo.tsx
**What**:
Closes #10798
Adds options to allow creation of new items from the `@patternfly/react-templates` TypeaheadSelect component.
=> feat(TypeaheadSelect) Add creation options to TypeaheadSelect

packages/react-templates/src/components/Select/TypeaheadSelect.tsx, packages/react-templates/src/components/Select/examples/TypeaheadSelectDemo.tsx
**What**:
Closes #10825 
Update the input value to the new selection (when options are updated) only when it contains the previous selection
=> fix(TypeaheadSelect): Update input value only when appropriate

packages/react-core/src/components/MenuToggle/MenuToggle.tsx, packages/react-core/src/components/MenuToggle/examples/MenuToggle.md, packages/react-core/src/components/Select/examples/Select.md
**What**: Closes #10836 
Per convo this PR only promotes MenuToggle/Select validation from beta since it was a consumer request, we can take stock of other v6 promotions that can/should be made in v5 in another PR.
=> chore(MenuToggle/Select): promoted status/validation

packages/react-templates/src/components/Select/TypeaheadSelect.tsx, packages/react-templates/src/components/Select/__tests__/TypeaheadSelect.test.tsx, packages/react-templates/src/components/Select/__tests__/__snapshots__/TypeaheadSelect.test.tsx.snap, packages/react-templates/src/components/Select/examples/SelectTemplates.md, packages/react-templates/src/components/Select/examples/TypeaheadSelectDemo.tsx
**What**: 
Closes #
Updates the props for `TypeaheadSelect` and does not keep selection info in state. Fixes an issue where the menu would incorrectly open on option changes.
=> Templates(TypeaheadSelect): Fix handling of selection and dropdown opening

packages/react-core/src/components/Dropdown/Dropdown.tsx, packages/react-core/src/components/Menu/Menu.tsx, packages/react-core/src/components/Menu/MenuContainer.tsx, packages/react-core/src/components/Select/Select.tsx, packages/react-integration/cypress/integration/notificationdrawerbasic.spec.ts, packages/react-integration/cypress/integration/notificationdrawergroups.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/DropdownDemo/DropdownDemo.tsx
**What**: Closes #10840
Updates the logic for Menu to only include the drilldown transition handler when the Menu is a drilldown (after transitions were added in core to the base Menu, this event handler was firing for all Menus instead of only Drilldowns).
Updates the logic in Dropdown/Select/MenuContainer to focus the first item on an isOpen change rather than in the click handler.
Adds `shouldFocusFirstItemOnOpen` to MenuContainer for parity.
=> fix(Menu): update drilldown transition event handler

packages/react-core/package.json, packages/react-core/src/components/Card/CardHeader.tsx, packages/react-core/src/components/Card/__tests__/CardHeader.test.tsx, packages/react-core/src/components/Card/examples/CardClickable.tsx, packages/react-core/src/components/Card/examples/CardClickableSelectable.tsx, packages/react-core/src/components/Card/examples/CardSelectable.tsx, packages/react-core/src/components/Card/examples/CardSingleSelectable.tsx, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-integration/cypress/integration/card.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/CardDemo/CardDemo.tsx, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
=> fix(Card): updated markup for actionable cards

packages/react-core/src/components/NotificationDrawer/NotificationDrawerListItemHeader.tsx, packages/react-core/src/components/NotificationDrawer/__tests__/NotificationDrawerListItemHeader.test.tsx, packages/react-core/src/components/NotificationDrawer/examples/NotificationDrawerBasic.tsx, packages/react-core/src/components/NotificationDrawer/examples/NotificationDrawerGroups.tsx
**What**: Closes #10715
- Adds `actionHasNoOffset` property.
- Adds tests for new prop.
=> feat(NotificationDrawer): add no offset prop

packages/react-table/src/components/Table/utils/transformers.test.tsx, packages/react-table/src/components/Table/utils/transformers.tsx, packages/react-table/src/deprecated/components/Table/__tests__/__snapshots__/Table.test.tsx.snap
**What**: Closes https://github.com/patternfly/patternfly-react/issues/10874
=> fix(Table): remove blank scope in empty deprecated table headers

packages/react-core/src/components/DualListSelector/examples/DualListSelector.md, packages/react-core/src/components/Modal/examples/Modal.md, packages/react-drag-drop/src/components/DragDrop/examples/DragDrop.md, packages/react-drag-drop/src/components/DragDrop/examples/DragDropDemos.md
Closes: https://github.com/patternfly/patternfly-react/issues/10827
Updates docs for
- DualListSelector
- Modal
- DragDrop
=> fix: promote former next components out of beta

packages/react-core/src/components/LoginPage/LoginMainHeader.tsx, packages/react-core/src/components/LoginPage/__tests__/__snapshots__/LoginMainHeader.test.tsx.snap, packages/react-core/src/components/LoginPage/__tests__/__snapshots__/LoginPage.test.tsx.snap
=> fix(LoginPage): updated markup for LoginMainHeader

packages/react-code-editor/src/components/CodeEditor/__test__/__snapshots__/CodeEditor.test.tsx.snap, packages/react-code-editor/src/components/CodeEditor/__test__/__snapshots__/CodeEditorControl.test.tsx.snap, packages/react-core/src/components/AboutModal/__tests__/__snapshots__/AboutModalBoxCloseButton.test.tsx.snap, packages/react-core/src/components/Alert/__tests__/Generated/__snapshots__/AlertActionCloseButton.test.tsx.snap, packages/react-core/src/components/Button/Button.tsx, packages/react-core/src/components/Card/__tests__/__snapshots__/CardHeader.test.tsx.snap, packages/react-core/src/components/ClipboardCopy/__tests__/__snapshots__/ClipboardCopyButton.test.tsx.snap, packages/react-core/src/components/ClipboardCopy/__tests__/__snapshots__/ClipboardCopyToggle.test.tsx.snap, packages/react-core/src/components/DataList/__tests__/Generated/__snapshots__/DataListToggle.test.tsx.snap, packages/react-core/src/components/DataList/__tests__/__snapshots__/DataListToggle.test.tsx.snap, packages/react-core/src/components/DatePicker/__tests__/__snapshots__/DatePicker.test.tsx.snap, packages/react-core/src/components/Form/__tests__/__snapshots__/FormFieldGroup.test.tsx.snap, packages/react-core/src/components/Label/__tests__/__snapshots__/Label.test.tsx.snap, packages/react-core/src/components/Label/__tests__/__snapshots__/LabelGroup.test.tsx.snap, packages/react-core/src/components/LoginPage/__tests__/__snapshots__/LoginForm.test.tsx.snap, packages/react-core/src/components/Modal/__tests__/__snapshots__/ModalContent.test.tsx.snap, packages/react-core/src/components/MultipleFileUpload/__tests__/__snapshots__/MultipleFileUploadStatusItem.test.tsx.snap, packages/react-core/src/components/Pagination/__tests__/Generated/__snapshots__/Navigation.test.tsx.snap, packages/react-core/src/components/Pagination/__tests__/__snapshots__/Pagination.test.tsx.snap, packages/react-core/src/components/Popover/__tests__/Generated/__snapshots__/PopoverCloseButton.test.tsx.snap, packages/react-core/src/components/SearchInput/__tests__/__snapshots__/SearchInput.test.tsx.snap, packages/react-core/src/components/Toolbar/__tests__/__snapshots__/Toolbar.test.tsx.snap, packages/react-core/src/deprecated/components/Chip/__tests__/__snapshots__/Chip.test.tsx.snap, packages/react-core/src/deprecated/components/Modal/__tests__/__snapshots__/ModalContent.test.tsx.snap, packages/react-core/src/deprecated/components/Wizard/__tests__/__snapshots__/Wizard.test.tsx.snap, packages/react-table/src/deprecated/components/Table/__tests__/__snapshots__/Table.test.tsx.snap, packages/react-templates/src/components/Select/__tests__/__snapshots__/TypeaheadSelect.test.tsx.snap
=> fix(Button): rendered position modifier only when children are passed

packages/react-charts/src/components/Chart/Chart.tsx, packages/react-charts/src/components/ChartAxis/ChartAxis.tsx, packages/react-charts/src/components/ChartBar/examples/ChartBar.md, packages/react-charts/src/components/ChartPie/examples/ChartPie.md
- Created a gnatt-like [example](https://patternfly-react-pr-10845.surge.sh/charts/bar-chart#alerts-timeline), demonstrating an alert timeline using horizontal bar charts
- Updated a pie chart [example](https://patternfly-react-pr-10845.surge.sh/charts/pie-chart#custom-color-scale) to demonstrate how to apply custom styles
- Also fixed an issue with undesired space between tick labels and the bottom positioned legend
Closes https://github.com/patternfly/patternfly-react/issues/10844
=> Charts - more examples

packages/react-core/src/components/DatePicker/__tests__/__snapshots__/DatePicker.test.tsx.snap, packages/react-core/src/components/Drawer/__tests__/__snapshots__/Drawer.test.tsx.snap, packages/react-core/src/components/ExpandableSection/__tests__/__snapshots__/ExpandableSection.test.tsx.snap, packages/react-core/src/components/NumberInput/__tests__/__snapshots__/NumberInput.test.tsx.snap, packages/react-core/src/components/Tabs/__tests__/__snapshots__/Tab.test.tsx.snap, packages/react-drag-drop/src/components/DragDrop/__tests__/__snapshots__/DragDrop.test.tsx.snap, packages/react-table/src/deprecated/components/Table/__tests__/__snapshots__/Table.test.tsx.snap
=> fix(CI): Update snapshot tests

packages/eslint-plugin-patternfly-react/package.json
This change fixes the publication issues outlined by [`publint`](https://publint.dev/), namely:
- Add an explicit `type` of `commonjs` to the package.
- Replace `main` with the more modern `exports`, which restricts the importable API surface.
- Fix a misformatted URL in the `repository` field.
Works towards closing #10833
=> Fix publint errors for `eslint-plugin-patternfly-react`

packages/react-core/src/demos/DashboardHeader.tsx, packages/react-core/src/demos/NotificationDrawer/examples/NotificationDrawerBasic.tsx, packages/react-core/src/demos/NotificationDrawer/examples/NotificationDrawerGrouped.tsx, packages/react-core/src/demos/RTL/examples/PaginatedTable.jsx, packages/react-core/src/demos/RTL/examples/PaginatedTable.tsx, packages/react-core/src/demos/examples/Masthead/MastheadWithHorizontalNav.tsx, packages/react-core/src/demos/examples/Masthead/MastheadWithUtilitiesAndUserDropdownMenu.tsx, packages/react-core/src/demos/examples/Nav/NavFlyout.tsx, packages/react-core/src/demos/examples/Nav/NavHorizontal.tsx, packages/react-core/src/demos/examples/Nav/NavHorizontalWithSubnav.tsx, packages/react-core/src/demos/examples/Nav/NavManual.tsx, packages/react-core/src/demos/examples/Page/PageContextSelector.tsx, packages/react-core/src/demos/examples/Page/PageStickySectionBreadcrumb.tsx, packages/react-core/src/demos/examples/Page/PageStickySectionGroup.tsx, packages/react-core/src/demos/examples/Page/PageStickySectionGroupAlternate.tsx, packages/react-table/src/demos/DashboardHeader.tsx
**What**: Closes #10814
- Removed `isFullHeight` from Toolbar and MenuToggle used in Page wrappers for examples/demos
- Added `size="sm"` to Avatar in the above MenuToggles
- Updated docs-framework version to pull in Masthead structure fix for surge
=> feat(misc): remove isFullHeight from page toolbar and dropdown

packages/transformer-react-styles-esm-imports/package.json
Fixes the build failure with the tags around transformer-react-styles-esm-imports.
Here is the error that this is fixing: https://github.com/patternfly/patternfly-react/actions/runs/10742197639/job/29794712314#step:4:35
=> chore: Fixed release issue with transformer-react-styles-esm-imports

packages/react-core/src/components/MenuToggle/MenuToggle.tsx, packages/react-core/src/components/MenuToggle/__tests__/MenuToggle.test.tsx, packages/react-core/src/components/MenuToggle/examples/MenuToggle.md, packages/react-core/src/components/MenuToggle/examples/MenuTogglePlaceholder.tsx
**What**: Closes #10861
- Adds `isPlaceholder` to `MenuToggle`
- Adds example & test
- Bumps core to `alpha.211`
=> feat(MenuToggle): add placeholder support

packages/react-integration/cypress/integration/slider.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/SliderDemo/SliderDemo.tsx
=> chore(Slider) update integration tests

packages/react-core/src/components/Content/Content.tsx, packages/react-core/src/components/Content/__tests__/Content.test.tsx, packages/react-core/src/components/Content/examples/Content.md, packages/react-core/src/components/Content/examples/ContentEditorial.tsx
**What**: Closes #10855
- Adds `isEditorial` to `Content`. This will add the new modifier to either a wrapping Content or a specific component Content.
- Adds new example showing both use cases.
- Adds tests
=> feat(Content): add editorial support

packages/react-core/src/components/MenuToggle/examples/MenuToggle.md
=> docs(menu-toggle): Updates split toggle example names.

packages/react-core/src/components/EmptyState/EmptyState.tsx, packages/react-core/src/components/EmptyState/EmptyStateHeader.tsx, packages/react-core/src/components/EmptyState/__tests__/EmptyState.test.tsx
=> fix(empty state): Do not require titleText prop)

packages/react-core/src/components/Dropdown/Dropdown.tsx, packages/react-core/src/components/Select/Select.tsx
**What**: 
Closes #10896 
Add a slight delay before setting focus on the first dropdown item when `shouldFocusFirstItemOnOpen` is set. This gives enough time for the popover to be shown in the correct location so the scrollable doesn't scroll to the invalid location.
=> fix(dropdown): Delay setting focus on first item to prevent inadvertent scroll

packages/react-charts/src/components/ChartBar/examples/ChartBar.md, packages/react-charts/src/components/ChartTheme/styles/box-plot-tooltip-styles.ts, packages/react-charts/src/components/ChartTheme/styles/legend-tooltip-styles.ts, packages/react-core/src/components/Page/Page.tsx, packages/react-core/src/components/Skeleton/examples/Skeleton.md, packages/react-core/src/components/Skeleton/examples/SkeletonText.tsx, packages/react-core/src/components/Toolbar/ToolbarToggleGroup.tsx, packages/react-core/src/components/Toolbar/ToolbarUtils.tsx, packages/react-core/src/demos/CardDemos.md, packages/react-core/src/demos/examples/Card/CardStatus.tsx, packages/react-core/src/helpers/constants.ts, packages/react-docs/patternfly-docs/pages/icons.js, packages/react-integration/demo-app-ts/src/components/demos/TableDemo/TableComposableDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/TableDemo/TableRowWrapperDemo.tsx, packages/react-table/src/components/Table/examples/Table.md, packages/react-table/src/components/Table/examples/TableMisc.tsx, packages/react-table/src/deprecated/components/Table/examples/LegacyTableMisc.tsx, packages/react-table/src/deprecated/components/Table/examples/Table.md, packages/react-tokens/README.md, packages/react-tokens/scripts/generateTokens.mjs, packages/react-tokens/tests/react-tokens.test.js
**What**: Closes #10985 
A issue was noticed that react-token created chart token exports that differed  by one uppercase character. example 
`export { chart_global_label_Margin } from './chart_global_label_Margin';
export { chart_global_label_margin } from './chart_global_label_margin';
`
To test pull down this branch, build and look at the `react-tokens` `dist` directory.
**eg. of token before change**
**after change**
@thatblindgeye could we write code mod for this?
=> fix(generate tokens): prefix tokens with a t_

packages/react-core/src/components/Modal/Modal.tsx, packages/react-core/src/components/Modal/ModalContent.tsx, packages/react-core/src/components/Modal/__tests__/Modal.test.tsx, packages/react-core/src/components/Modal/__tests__/__snapshots__/ModalContent.test.tsx.snap
=> fix(Modal): Prevent auto aria-labelledby if aria-label is passed

packages/react-charts/src/components/ChartArea/examples/ChartArea.md, packages/react-charts/src/components/ChartCursorContainer/ChartCursorContainer.tsx, packages/react-charts/src/components/ChartCursorTooltip/ChartCursorFlyout.tsx, packages/react-charts/src/components/ChartUtils/chart-container.tsx, packages/react-charts/src/components/ChartUtils/chart-tooltip.ts, packages/react-charts/src/components/ChartVoronoiContainer/ChartVoronoiContainer.tsx
Resolves a deprecation warning related to `defaultProps`. Tested with Cost Management.
Closes https://github.com/patternfly/patternfly-react/issues/11019
=> fix(charts): defaultProps deprecation warning (v5)

packages/react-charts/src/components/ChartArea/examples/ChartArea.md, packages/react-charts/src/components/ChartCursorContainer/ChartCursorContainer.tsx, packages/react-charts/src/components/ChartCursorTooltip/ChartCursorFlyout.tsx, packages/react-charts/src/components/ChartUtils/chart-container.tsx, packages/react-charts/src/components/ChartUtils/chart-tooltip.ts, packages/react-charts/src/components/ChartVoronoiContainer/ChartVoronoiContainer.tsx
Resolves a deprecation warning related to `defaultProps`. Tested with Cost Management.
Closes https://github.com/patternfly/patternfly-react/issues/11019
=> fix(charts): defaultProps deprecation warning (v6)

packages/react-core/src/components/TextInputGroup/examples/TextInputGroup.md
=> docs(text-input-group): Adds React docs.

packages/react-integration/demo-app-ts/src/components/demos/TableDemo/TableFavoritesDemo.tsx, packages/react-table/src/components/Table/SortColumn.tsx, packages/react-table/src/components/Table/TableTypes.tsx, packages/react-table/src/components/Table/Th.tsx, packages/react-table/src/components/Table/base/types.tsx, packages/react-table/src/components/Table/examples/TableFavoritable.tsx, packages/react-table/src/components/Table/utils/decorators/sortable.tsx
**What**: Closes #10415
I am not sure what styling should be applied to the star icon in the header when it is clicked. Previously it had the blue color applied (same as the sort arrow indicator). But now it is a separate button. I don't think we have a suitable class for that case. For now I just applied `pf-m-favorited` (the same as for the individual rows with stars), it can be seen on the example bellow:
https://github.com/user-attachments/assets/5032ec52-bab8-47e8-bfaa-ca7d12a98b83
Now that the `pf-v6-c-table__favorite` class (`styles.tableFavorite`) is applied to `th` instead of `pf-m-favorite` (`styles.modifiers.favorite`), it messes up the deprecated example. (I assume it is OK, given that it already was deprecated in V5)
=> feat(Table): favoritable sortable header cell and example

packages/react-integration/cypress/integration/form.spec.ts, packages/react-integration/cypress/integration/page.spec.ts, packages/react-integration/cypress/integration/tableeditable.spec.ts, packages/react-integration/cypress/integration/toolbar.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/FormDemo/FormDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/PageDemo/PageDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/TableDemo/TableEditableDemo.tsx, packages/react-table/src/components/Table/EditableSelectInputCell.tsx, packages/react-table/src/deprecated/components/Table/examples/Table.md
**What**: Closes #10365
- Updated deprecated Editable table example
- Reenabled editable table tests.
- Updated Page demo and reenabled page test
- reenabled toolbar test
- update form demo and reenabled test ~~(i disabled the select test that is not working due to this issue #10840)~~
- added isPlaceholder prop to `EditableSelectInputCell`
=> Deprecate follow up

packages/react-core/src/components/DataList/DataListCheck.tsx, packages/react-core/src/components/DataList/__tests__/DataListCheck.test.tsx, packages/react-core/src/components/DataList/__tests__/Generated/DataListCheck.test.tsx, packages/react-core/src/components/DataList/__tests__/Generated/__snapshots__/DataListCheck.test.tsx.snap, packages/react-core/src/components/DataList/examples/DataListCheckboxes.tsx, packages/react-core/src/components/DataList/examples/DataListDraggable.tsx, packages/react-core/src/components/DataList/examples/DataListWidthModifiers.tsx, packages/react-drag-drop/src/components/DragDrop/examples/DataListDraggable.tsx, packages/react-drag-drop/src/components/DragDrop/examples/DragDropContainerDataList.tsx
**What**: Closes #10886
Refactors DataListCheck to use Checkbox internally - this also fixes the broken checkboxes in the examples.
**This will mean `id` is now a required prop for DataListCheck.**
Updates examples/tests.
=> feat(DataList): use Checkbox in DataListCheck

packages/react-core/src/components/Modal/Modal.tsx, packages/react-core/src/components/Modal/ModalContent.tsx
We need to adjust the behavior in Virtual Assistant, but there's no way for us to target it specifically. This would let us pass a class down.
Fixes https://github.com/patternfly/patternfly-react/issues/11016.
=> fix(Modal): Allow users to add classes to backdrop

packages/react-core/src/demos/examples/JumpLinks/JumpLinksWithDrawer.js
Closes #11051 
This PR fixes the incorrect `offset` used in the jumplinks with drawer demo by removing the complicated offset calculation altogether and simply applying `hasOverflowScroll` to the scrolling page section.
=> chore(jumplinks): fix overflow in jumplinks demo

packages/react-core/src/components/ExpandableSection/ExpandableSection.tsx
**What**: Closes #10869
Added checks for the containerRef, tested locally and it no longer produces the errors
=> fix: add checks for contentRef to avoid errors in console

packages/react-core/package.json, packages/react-core/src/components/MenuToggle/MenuToggle.tsx, packages/react-core/src/components/MenuToggle/__tests__/MenuToggle.test.tsx, packages/react-core/src/components/MenuToggle/examples/MenuToggle.md, packages/react-core/src/components/MenuToggle/examples/MenuToggleSplitButtonAction.tsx, packages/react-core/src/components/MenuToggle/examples/MenuToggleSplitButtonCheckbox.tsx, packages/react-core/src/components/MenuToggle/examples/MenuToggleSplitButtonCheckboxWithText.tsx, packages/react-core/src/components/MenuToggle/examples/MenuToggleSplitButtonCheckboxWithToggleText.tsx, packages/react-core/src/components/Toolbar/examples/ToolbarStacked.tsx, packages/react-core/src/demos/CardView/examples/CardView.tsx, packages/react-core/src/demos/DataList/examples/DataListBasic.tsx, packages/react-core/src/demos/Filters/examples/FilterAttributeSearch.tsx, packages/react-core/src/demos/Filters/examples/FilterCheckboxSelect.tsx, packages/react-core/src/demos/Filters/examples/FilterFaceted.tsx, packages/react-core/src/demos/Filters/examples/FilterMixedSelectGroup.tsx, packages/react-core/src/demos/Filters/examples/FilterSameSelectGroup.tsx, packages/react-core/src/demos/Filters/examples/FilterSearchInput.tsx, packages/react-core/src/demos/Filters/examples/FilterSingleSelect.tsx, packages/react-core/src/demos/examples/PrimaryDetail/PrimaryDetailCardView.tsx, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-integration/cypress/integration/slider.spec.ts, packages/react-styles/package.json, packages/react-table/src/demos/examples/TableBulkSelect.tsx, packages/react-tokens/package.json, yarn.lock
**What**: Closes #11095
This PR does the following:
- bumps core versions to latest
- Removed the `SplitButtonOptions` interface and prop since it is no longer needed because  there is no longer a variant.  Consumers will now pass items directly to `splitButtonItems` prop
- update all demos that are impacted by new API
=> fix(Menu toggle): Remove pf-m-action modifier

packages/react-core/src/components/ExpandableSection/__tests__/__snapshots__/ExpandableSection.test.tsx.snap, packages/react-core/src/next/components/Modal/Modal.tsx, packages/react-core/src/next/components/Modal/ModalContent.tsx, packages/react-core/src/next/components/Modal/__tests__/Modal.test.tsx, packages/react-core/src/next/components/Modal/__tests__/__snapshots__/ModalContent.test.tsx.snap
=> fix(next modal): prevent auto aria-labelledby if aria-label is passed

packages/react-core/src/components/Dropdown/Dropdown.tsx, packages/react-core/src/components/Menu/MenuContainer.tsx, packages/react-core/src/components/Pagination/PaginationOptionsMenu.tsx, packages/react-core/src/components/Select/Select.tsx, packages/react-core/src/components/Tabs/OverflowTab.tsx
Closes #11053 
Prevents inconsistent scrolling behaviour on a number of select/menu components.
This also removes the timeout, which appears is no longer needed. 
(Slightly snappier without, with/without barely noticeable).
**What**: Closes 11053
[Associated External issue from Red Hat Insights team](https://issues.redhat.com/browse/HMS-4746)
=> Fixes 11053: focus event causing jumpy scroll effect

scripts/promote.sh
This fix allows us to promote the code on the prerelease-v5 channel to npm.
=> fix: Updated to release the code on the v5 prerelase channel.

packages/react-charts/package.json, yarn.lock
Victory peer dependencies should be marked optional via `peerDependenciesMeta`
https://github.com/patternfly/patternfly-react/issues/11125
=> Victory packages to be marked optional (v6)

packages/react-core/src/components/Dropdown/Dropdown.tsx, packages/react-core/src/components/Select/Select.tsx, packages/react-integration/cypress/integration/dropdown.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/DropdownDemo/DropdownDemo.tsx
**What**: Towards #10393 
We have a followup to investigate [improving the focus logic/styling overall](https://github.com/patternfly/patternfly-react/issues/11025) post-v6
=> fix(Select/Dropdown): updated autofocus to false by default in v6

packages/react-core/src/components/Dropdown/Dropdown.tsx, packages/react-core/src/components/Menu/MenuContainer.tsx, packages/react-core/src/components/Pagination/PaginationOptionsMenu.tsx, packages/react-core/src/components/Select/Select.tsx, packages/react-core/src/components/Tabs/OverflowTab.tsx
**What**: Closes #11053, closes #11020
v6 followup to https://github.com/patternfly/patternfly-react/pull/11056
=> fix(Menus): added new fix for scroll jump bug

packages/react-core/src/components/DualListSelector/examples/DualListSelectorTree.tsx, packages/react-integration/cypress/integration/duallistselectortree.spec.ts, packages/react-integration/cypress/integration/notificationdrawergroups.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/DualListSelectorDemo/DualListSelectorTreeDemo.tsx
**What**: Closes #10862
- Should I also fix this example in V5 for DualListSelector Next?
=> fix(DualListSelector example): improved behaviour when filter is applied

packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx
=> CodeEditor loading property considered by the Editor

eslint.config.mjs, packages/react-table/src/components/Table/utils/decorators/sortable.tsx, packages/react-table/src/deprecated/components/Table/__tests__/__snapshots__/Table.test.tsx.snap
V6 versions of https://github.com/patternfly/patternfly-react/pull/11144
=> fix(table,a11y): only apply aria-sort when sorting for V6

eslint.config.mjs, packages/react-table/src/components/Table/utils/decorators/sortable.tsx, packages/react-table/src/deprecated/components/Table/__tests__/__snapshots__/Table.test.tsx.snap
**What**: Closes #11023
- Prevents `aria-sort` from being added if the column is not actively being sorted.
- Updates screenshots
Also updates the lint config to ignore .cache directories.
=> fix(table,a11y): only apply aria-sort when sorting

packages/react-charts/src/components/ChartUtils/chart-tooltip.ts
Fixes https://github.com/patternfly/patternfly-react/issues/11154
**Example 1**
**Example 2**
=> fix(charts) - legend tooltip missing space between label and value (v5)

packages/react-charts/src/victory/components/ChartUtils/chart-tooltip.ts
Fixes https://github.com/patternfly/patternfly-react/issues/11154
**Example 1**
**Example 2**
=> fix(charts) - legend tooltip missing space between label and value (v6)

eslint.config.mjs, package.json, yarn.lock
Adds the new [React Compiler linter](https://react.dev/learn/react-compiler#installing-eslint-plugin-react-compiler) to the linting configuration and sets it to emit warnings where violations are detected. These warnings will need to be fixed and then turned into errors as a follow up (see #11138).
Closes #11137
=> Add the React Compiler linter

packages/react-core/src/components/MenuToggle/MenuToggleCheckbox.tsx
MenuToggleCheckboxProps inherits from HTMLInputElement and defaultChecked is typed there as `undefined | boolean`, null is not a valid type.
Found by typescript's `tsc` in strict mode.
=> fix(MenuToggle): incorrect inheritance of HTMLInputElement

packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx, packages/react-code-editor/src/components/CodeEditor/__test__/__snapshots__/CodeEditor.test.tsx.snap, packages/react-code-editor/src/components/CodeEditor/examples/CodeEditor.md, packages/react-code-editor/src/components/CodeEditor/examples/CodeEditorFullHeight.tsx, packages/react-core/package.json, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
The docs state that the default height for CodeEditor is 100%. However, the examples just break if you don't pass in a height. I got it to work with these changes.
We just need to upgrade Core once a release comes out that contains these classes.
**What**: Closes https://github.com/patternfly/patternfly-react/issues/11013
Related to https://github.com/patternfly/patternfly/pull/7087
=> fix(CodeEditor): Set default height

packages/react-templates/src/components/Select/TypeaheadSelect.tsx
Here are a few small changes to the TypeaheadSelect that we could use in Cockpit.
- Our linter doesn't like the "any" type.
- TypeScript actually reports a typing error for the "isDisabled" property, which seems easily fixed.
- Not all our typeahead users specify a "onClearSelection" function, and for those the "X" button was still there but did nothing. I think it is better to not show that button in that case.
Thanks!
=> Improvements to the TypeaheadSelect template

packages/react-core/src/layouts/Split/Split.tsx, packages/react-core/src/layouts/Split/SplitItem.tsx, packages/react-core/src/layouts/Split/__tests__/Split.test.tsx, packages/react-core/src/layouts/Split/__tests__/__snapshots__/Split.test.tsx.snap, packages/react-core/src/layouts/Stack/Stack.tsx, packages/react-core/src/layouts/Stack/StackItem.tsx, packages/react-core/src/layouts/Stack/__tests__/Stack.test.tsx, packages/react-core/src/layouts/Stack/__tests__/__snapshots__/Stack.test.tsx.snap
fixes https://github.com/patternfly/patternfly-react/issues/11169
Also cleans up the docs a little. Let me know if you'd like me to revert/update any of that @tlabaj
=> fix(split/stack): add component prop to StackItem/SplitItem

packages/react-core/src/components/Modal/Modal.tsx, packages/react-core/src/components/Modal/ModalContent.tsx, packages/react-core/src/components/Modal/__tests__/Modal.test.tsx, packages/react-core/src/deprecated/components/Modal/Modal.tsx, packages/react-core/src/deprecated/components/Modal/ModalContent.tsx, packages/react-core/src/deprecated/components/Modal/__tests__/Modal.test.tsx
=> fix(Modal): Fixes various bugs in the Modal and deprecated Modal

packages/react-core/src/components/DataList/examples/DataList.md, packages/react-core/src/components/DualListSelector/examples/DualListSelector.md
**What**: Closes #10196.
To prevent duplicated example code, I referenced the example files locally and this does appear to work for the surge as well as locally. If the file location changes though we would need to update this reference as well. 
Does anyone have any opinions on the file reference in the mds?
=> feat(docs): add draggable demos to component pages

packages/react-core/src/components/Dropdown/Dropdown.tsx, packages/react-core/src/components/Menu/MenuContainer.tsx, packages/react-core/src/components/Select/Select.tsx, packages/react-core/src/components/Select/examples/SelectMultiTypeahead.tsx, packages/react-core/src/components/Select/examples/SelectMultiTypeaheadCheckbox.tsx, packages/react-core/src/components/Select/examples/SelectMultiTypeaheadCreatable.tsx, packages/react-core/src/components/Select/examples/SelectTypeahead.tsx, packages/react-core/src/components/Select/examples/SelectTypeaheadCreatable.tsx, packages/react-core/src/helpers/KeyboardHandler.tsx, packages/react-templates/src/components/Select/MultiTypeaheadSelect.tsx, packages/react-templates/src/components/Select/TypeaheadSelect.tsx
Closes #11131
Potential problem: if consumers pass a `component` prop to MenuItem other than `button` / `input` / `a`, it won't focus the item. They can always override the `onArrowUpDownKeyDown` themselves, but I am wondering whether we should provide some prop to specify, what is the html element they want to focus.
=> feat(Select/Dropdown/MenuContainer): arrow key handling to focus items

packages/react-core/src/components/FileUpload/FileUpload.tsx, packages/react-core/src/components/FileUpload/examples/FileUpload.md, packages/react-core/src/components/FileUpload/examples/FileUploadTextWithRestrictions.tsx
**What**: Closes #10521 
This allows devs to capture and act on native react-dropzone error codes. Added an example of doing so to the existing FileUploadWithRestrictions example. Also fixed a legacy bug in that example in which, after dropping an invalid file, the error states were remaining even if subsequently dragging and dropping valid files.
=> feat(FileUpload): expose dropdown error types

packages/react-core/src/demos/ExpandableSection/examples/ExpandableTextDemo.tsx
…
**What**: Closes https://github.com/patternfly/patternfly-react/issues/11225
https://github.com/patternfly/patternfly/issues/7181
=> fix(expandable section): Remove returns within text content so that example truncates correctly

packages/react-core/package.json, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
=> chore(deps): Update core versions

packages/react-core/src/components/CalendarMonth/CalendarMonth.tsx
**What**: Closes #11329
CalendarMonth's select was closing the Datepicker popover because the Select wasn't inline/was appended to the body (so the Datepicker saw the click as coming from outside the picker).
The timeout in the selection handler doesn't seem to be necessary in v6.
=> fix(CalendarMonth): fix selection closing datepicker popover

packages/react-core/src/components/LoginPage/examples/LoginPage.md, packages/react-core/src/components/LoginPage/examples/LoginPageBasic.tsx, packages/react-core/src/components/LoginPage/examples/LoginPageLanguageSelect.tsx, packages/react-core/src/components/LoginPage/examples/LoginPageShowHidePassword.tsx, packages/react-core/src/demos/CustomMenus/ApplicationLauncher.md, packages/react-core/src/demos/CustomMenus/CustomMenus.md, packages/react-core/src/demos/CustomMenus/examples/ApplicationLauncherDemo.tsx, packages/react-core/src/demos/assets/PF-IconLogo.svg
**What**: Closes #9443
I initially tried to use the new horizontal logo with LoginPage, but it was very large and currently LoginPage has no method to customize the internal Brand component, so I went with the icon logo instead. LMK if we want to still go with the horizontal logo + add a Brand spread props to LoginPage.
=> docs(misc): update to new logo

packages/react-core/src/components/DualListSelector/DualListSelector.tsx
**What**: Closes #10695 
This should resolve all `tsc` error output cause by PF type declarations in PF5. 
I pulled down and worked off react-core 5.3.3 to replicate the same environment as the reporter of the issue, but could not reproduce the exact same set of tsc errors that they were encountering. However, there were 14 or so errors flagged by tsc (running in strict mode), all of which were located in `DualListSelector`, so I cleaned these up. This should result in clean runs of the tsc compiler for PF5.
=> fix(DualListSelector): Resolve tsc type issues

packages/react-core/src/components/AboutModal/AboutModal.tsx, packages/react-core/src/demos/DatePicker/examples/DateTimePickerInModal.tsx, packages/react-core/src/demos/examples/MultipleFileUpload/MultipleFileUploadRejectedFile.tsx, packages/react-integration/demo-app-ts/src/components/demos/WizardDemo/WizardDemo.tsx
=> chore(Modal): updated deprecated usage to promoted version

packages/react-core/src/deprecated/components/DualListSelector/DualListSelector.tsx
**What**: Closes #10695 
This is a follow-up to #11346 which was a fix for all found `tsc` compile errors in PF5, all of which were occurring in `DualListSelector`. These errors were also occurring in PF6 so the same changes apply.
=> fix(DualListSelector): Resolve tsc type issues in PF6

packages/react-core/src/components/FileUpload/examples/FileUploadTextWithRestrictions.tsx
**What**: Closes #11347 
This is a follow-up to #11289 in which the `FileUploadTextWithRestrictions` example was changed to take advantage of `react-dropzone` error codes, and as part of that the double icon issue on error was fixed. But an empty `<Icon>` remained in the code example, and although it's not visible or breaking anything, it could confuse viewers of the code example. So it's now removed and that part of the example is more simplified.
=> fix(FileUpload): Remove empty icon from example

packages/react-charts/src/victory/components/ChartBar/examples/ChartBar.md
Update "alerts timeline" example so tooltips appear centered horizontally, above each bar. This will help the OpenShift team with their implementation.
fixes https://github.com/patternfly/patternfly-react/issues/11378
**Before**
**After**
=> Demo - ChartBar - center tooltip for "alerts timeline" example

packages/react-core/src/demos/DataList/examples/DataListStaticBottomPagination.tsx, packages/react-core/src/demos/DataListDemo.md, packages/react-core/src/demos/sampleData.tsx
**What**: Closes #10247 
Based on latest updates from https://github.com/patternfly/patternfly-react/pull/10276 and includes updates from Coker, this targets the main v6 branch instead.
=> chore(DataList): added bottom static pagination demo

packages/react-core/src/demos/DataList/examples/DataListActionable.tsx, packages/react-core/src/demos/DataListDemo.md
**What**: Closes #10243
Based on latsst updates made in https://github.com/patternfly/patternfly-react/pull/10251, which will be closed out in favor of this to merge into our main v6 branch.
=> chore(DataList): added Actionable demo

packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx, packages/react-code-editor/src/components/CodeEditor/CodeEditorControl.tsx, packages/react-docs/patternfly-docs/pages/icons.js, packages/react-docs/patternfly-docs/pages/index.js, packages/react-drag-drop/src/components/DragDrop/DragButton.tsx, packages/react-drag-drop/src/components/DragDrop/DragDropContainer.tsx, packages/react-drag-drop/src/components/DragDrop/DraggableDataListItem.tsx, packages/react-integration/demo-app-ts/src/App.tsx, packages/react-table/src/components/Table/SortColumn.tsx, packages/react-table/src/components/Table/Table.tsx, packages/react-table/src/components/Table/base/types.tsx, packages/react-table/src/deprecated/components/Table/Table.tsx, packages/react-templates/src/components/Select/CheckboxSelect.tsx, packages/react-templates/src/components/Select/MultiTypeaheadSelect.tsx, packages/react-templates/src/components/Select/TypeaheadSelect.tsx
=> refactor(misc): change imports from '@patternfly/react-core' to direct imports

packages/react-core/src/components/TextArea/TextArea.tsx, packages/react-core/src/components/TextArea/__tests__/TextArea.test.tsx, packages/react-core/src/components/TextArea/examples/TextArea.md, packages/react-core/src/components/TextArea/examples/TextAreaResizableNone.tsx
=> feat(Text area): Add resize disable feature

packages/react-core/src/demos/DescriptionList/DescriptionList.md, packages/react-core/src/demos/DescriptionList/examples/DescriptionListInDrawer.tsx
**What**: Closes #10227 
Based off latest updates to https://github.com/patternfly/patternfly-react/pull/10229, and also updating/removing things based on v6 changes (updating or removing props, replacing Text and TextContent with Content).
=> chore(DescriptionList): added in drawer demo

packages/react-core/src/components/TreeView/examples/TreeView.md, packages/react-core/src/components/TreeView/examples/TreeViewWithIconPerItem.tsx
=> docs(TreeView): add example with unique icon per item

packages/react-charts/README.md
Update install section of readme
https://github.com/patternfly/patternfly-react/issues/11344
=> chore(charts) - update install section of readme

packages/react-charts/src/victory/components/ChartBoxPlot/examples/ChartBoxPlot.md, packages/react-charts/src/victory/components/ChartBullet/examples/ChartBullet.md, packages/react-charts/src/victory/components/ChartTheme/examples/ChartTheme.md, packages/react-charts/src/victory/components/ChartTooltip/examples/ChartTooltip.md, packages/react-charts/src/victory/components/Skeletons/examples/skeletons.md, packages/react-charts/src/victory/components/Sparkline/examples/sparkline.md
Some chart examples are missing ChartThemeColor import statements. As a result, CodeSandbox examples fail to load.
Also updated Victory to the latest packages.
https://github.com/patternfly/patternfly-react/issues/11459
=> Bug - v6 Charts - update CodeSandbox examples

packages/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx, packages/react-core/src/components/ClipboardCopy/__tests__/ClipboardCopy.test.tsx, packages/react-core/src/components/ClipboardCopy/__tests__/__snapshots__/ClipboardCopy.test.tsx.snap
The ClipboardCopy component already handles string[] but didn't have it written in the props as valid.
**What**: Closes #11186
=> fix(ClipboardCopy): Add string[] type to children

packages/react-core/src/components/Truncate/Truncate.tsx, packages/react-core/src/components/Truncate/__tests__/Truncate.test.tsx
=> fix(Truncate): fix text duplication in middle position

packages/react-core/src/components/FileUpload/FileUploadField.tsx, packages/react-core/src/components/FileUpload/__tests__/FileUploadField.test.tsx, packages/react-core/src/components/FileUpload/examples/FileUploadCustomUpload.tsx
=> fix(FileUploadField): Allow browse button disable

packages/react-core/src/components/JumpLinks/JumpLinks.tsx
=> feat(JumpLinks): Add replaceNavHistory option

packages/react-core/src/demos/DashboardHeader.tsx, packages/react-core/src/demos/examples/Masthead/MastheadWithHorizontalNav.tsx, packages/react-core/src/demos/examples/Masthead/MastheadWithUtilitiesAndUserDropdownMenu.tsx, packages/react-core/src/demos/examples/Nav/NavFlyout.tsx, packages/react-core/src/demos/examples/Nav/NavHorizontal.tsx, packages/react-core/src/demos/examples/Nav/NavHorizontalWithSubnav.tsx, packages/react-core/src/demos/examples/Nav/NavManual.tsx, packages/react-core/src/demos/examples/Page/PageContextSelector.tsx, packages/react-core/src/demos/examples/Page/PageStickySectionBreadcrumb.tsx, packages/react-core/src/demos/examples/Page/PageStickySectionGroup.tsx, packages/react-core/src/demos/examples/Page/PageStickySectionGroupAlternate.tsx, packages/react-table/src/demos/DashboardHeader.tsx
=> chore(Demos): Replace notification buttons with NotificationBadge

packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx, packages/react-code-editor/src/components/CodeEditor/__test__/__snapshots__/CodeEditor.test.tsx.snap
=> fix(CodeEditor): do not include extra div if `headerMainContent` is unset

packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx, packages/react-code-editor/src/components/CodeEditor/__test__/__snapshots__/CodeEditor.test.tsx.snap, packages/react-core/src/components/FileUpload/FileUpload.tsx, packages/react-core/src/components/FileUpload/__tests__/__snapshots__/FileUpload.test.tsx.snap, packages/react-core/src/components/MultipleFileUpload/MultipleFileUpload.tsx, packages/react-core/src/components/MultipleFileUpload/__tests__/__snapshots__/MultipleFileUpload.test.tsx.snap
**What**: Towards #11343 
The input was not intended to be exposed to users to navigate to and was simply required for dropzone. Keeping it exposed ends up allowing it to be focused which when it is, focus ends up being lost on the page. There should be enough context elsewhere in the components to indicate file uploading capability.
To test, go to an example in both components and navigate via keyboard and VoiceOver. Via keyboard the focus shouldn't get lost when navigating through the component elements, and via VoiceOver you should not hear an announcement along the lines of "Choose a file: no file chosen" (this is the output from the input type="file" element).
=> fix(FileUpload): hid input of type file from AT

packages/react-core/src/components/FileUpload/FileUpload.tsx, packages/react-core/src/components/FileUpload/__tests__/__snapshots__/FileUpload.test.tsx.snap, packages/react-core/src/components/MultipleFileUpload/MultipleFileUpload.tsx, packages/react-core/src/components/MultipleFileUpload/__tests__/__snapshots__/MultipleFileUpload.test.tsx.snap
**What**: Towards #11343 
The input was not intended to be exposed to users to navigate to and was simply required for dropzone. Keeping it exposed ends up allowing it to be focused which when it is, focus ends up being lost on the page. There should be enough context elsewhere in the components to indicate file uploading capability.
To test, go to an example in both components and navigate via keyboard and VoiceOver. Via keyboard the focus shouldn't get lost when navigating through the component elements, and via VoiceOver you should not hear an announcement along the lines of "Choose a file: no file chosen" (this is the output from the input type="file" element).
=> fix(FileUpload): hid input of type file from AT (v5)

packages/react-core/src/components/SearchInput/SearchInput.tsx, packages/react-core/src/components/SearchInput/__tests__/SearchInput.test.tsx, packages/react-core/src/components/TextInputGroup/TextInputGroupMain.tsx, packages/react-core/src/components/TextInputGroup/__tests__/TextInputGroupMain.test.tsx
**What**: Closes #10889 
Adds an additional prop to spread to input element. Original issue can be resolved in SearchInput via `<SearchInput inputProps={{autofocus: 'true'}} />`.
=> fix(SearchInput): allowed spreading of props to input element

packages/react-charts/victory/package.json, packages/react-core/src/components/DescriptionList/DescriptionListTermHelpTextButton.tsx
**What**: Closes #10350
V5 mirror of https://github.com/patternfly/patternfly-react/pull/11546
=> fix(DescriptionList): V5 - allow help text button popover to open via keyboard

packages/react-core/src/components/DescriptionList/DescriptionListTermHelpTextButton.tsx
**What**: Closes #10846
The issue is due to the help text button actually being a `span` with `role="button"`/`tab-index="0"`, which doesn't have keyboard interaction automatically like a button element does. The popover uses a click event to trigger.
This could also be solved by changing the element to a button, but I couldn't get the styling to work out, and I'm not sure it's valid HTML to nest a button inside a dt.
=> fix(DescriptionList): allow help text button popover to open via keyboard

packages/react-core/src/demos/examples/Wizard/InModal.tsx, packages/react-core/src/demos/examples/Wizard/InModalWithDrawer.tsx, packages/react-core/src/demos/examples/Wizard/InModalWithDrawerInformationalStep.tsx, packages/react-core/src/demos/examples/Wizard/InPage.tsx, packages/react-core/src/demos/examples/Wizard/InPageWithDrawer.tsx, packages/react-core/src/demos/examples/Wizard/InPageWithDrawerInformationalStep.tsx
=> chore(Wizard): updated demos per design

packages/react-core/src/components/Label/Label.tsx, packages/react-core/src/components/Label/examples/Label.md, packages/react-core/src/components/Label/examples/LabelCustomRender.tsx, packages/react-core/src/components/Label/examples/LabelRouterLink.tsx
**What**: Closes #11142
Adds `isClickable` as a prop to set the modifier when the render prop is also used. Also updated the example to remove the actual router usage.
=> feat(Label): allow isClickable to be set manually

babel.config.js, eslint.config.mjs, packages/react-charts/src/victory/components/ChartUtils/chart-container.tsx, packages/react-core/src/components/Avatar/examples/AvatarBasic.tsx, packages/react-core/src/components/Avatar/examples/AvatarBordered.tsx, packages/react-core/src/components/Button/__mocks__/Button.tsx, packages/react-core/src/components/Drawer/__tests__/DrawerPanelDescription.tsx, packages/react-core/src/components/HelperText/__mocks__/HelperText.tsx, packages/react-core/src/components/HelperText/__mocks__/HelperTextItem.tsx, packages/react-core/src/components/Menu/__mocks__/Menu.tsx, packages/react-core/src/components/Menu/__mocks__/MenuContent.tsx, packages/react-core/src/components/Menu/__mocks__/MenuGroup.tsx, packages/react-core/src/components/Menu/__mocks__/MenuItem.tsx, packages/react-core/src/components/Menu/__mocks__/MenuList.tsx, packages/react-core/src/components/ProgressStepper/examples/ProgressStepperHelpPopover.tsx, packages/react-core/src/helpers/FocusTrap/FocusTrap.tsx, packages/react-core/src/helpers/Popper/__mocks__/Popper.tsx, packages/react-core/tsconfig.json, packages/react-docs/patternfly-docs/pages/icons.js, packages/react-docs/patternfly-docs/pages/index.js, packages/react-icons/scripts/writeIcons.mjs, packages/react-integration/tsconfig.json, packages/react-table/src/components/Table/utils/decorators/draggable.tsx, packages/react-table/src/components/Table/utils/decorators/editable.tsx, packages/react-table/tsconfig.json, packages/tsconfig.base.json
**What**: Closes #9289 
Introduces the [new JSX transform](https://pl.legacy.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html) which removes the need to import React in every file that contains JSX. This is a change required to add support for React 19.
Update 2/20/25:
This implementation covers almost all of patternfly-react... however in react-docs, the index.js and icons.js files still require a react import. This is due to it being required by the current iteration of the doc framework, much like the js files in that repo. The new doc framework that is in development will allow this to be addressed much more easily.
For now, adds a lint configuration to support the new transformation, including a rule to ban the default React import (`import React from 'react'`) in …
=> chore(deps): Use new JSX transform

packages/react-core/src/components/ClipboardCopy/examples/ClipboardCopyInlineCompactWithAdditionalAction.tsx, packages/react-core/src/components/CodeBlock/examples/CodeBlockBasic.tsx, packages/react-core/src/components/CodeBlock/examples/CodeBlockExpandable.tsx
=> Chore(ClipboardCopy): add tooltip to play icon

packages/react-core/src/components/DataList/DataListItem.tsx, packages/react-core/src/components/DataList/__tests__/Generated/__snapshots__/DataListItem.test.tsx.snap, packages/react-core/src/components/DataList/__tests__/__snapshots__/DataListItem.test.tsx.snap
=> Refactor(DataList): removed aria-labelledby and aria-selected

eslint.config.mjs, packages/react-core/src/components/Menu/MenuItem.tsx
**What**: Closes https://github.com/patternfly/patternfly-react/issues/11358
=> fix(MenuItem): mouse can trigger tooltip on aria-disabled items

packages/react-charts/src/victory/components/ChartLegend/examples/ChartLegend.md
=> Chore(ChartLegend): updated interactive legend example

packages/react-templates/src/components/Select/MultiTypeaheadSelect.tsx, packages/react-templates/src/components/Select/TypeaheadSelect.tsx, packages/react-templates/src/components/Select/__tests__/MultiTypeaheadSelect.test.tsx, packages/react-templates/src/components/Select/__tests__/TypeaheadSelect.test.tsx, packages/react-templates/src/components/Select/__tests__/__snapshots__/MultiTypeaheadSelect.test.tsx.snap, packages/react-templates/src/components/Select/__tests__/__snapshots__/TypeaheadSelect.test.tsx.snap
=> fix(Select templates): allowed custom keydown handling

packages/react-core/src/components/DataList/DataListCell.tsx
**What**: Closes #11389
Adds logic to display a tooltip when a DataListCell's wrap modifier is set to truncate and the content is overflowing.
=> feat(DataList): add tooltip to truncated DataListCell

eslint.config.mjs, packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx, packages/react-code-editor/src/components/CodeEditor/__test__/CodeEditor.test.tsx, packages/react-code-editor/src/components/CodeEditor/__test__/__snapshots__/CodeEditor.test.tsx.snap
**What**: Closes https://github.com/patternfly/patternfly-react/issues/11518
=> fix(CodeEditor): only include pf-v6-c-code-editor__upload when hovering is active over an empty state

packages/react-core/package.json, packages/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx, packages/react-core/src/components/ClipboardCopy/__tests__/ClipboardCopy.test.tsx, packages/react-core/src/components/ClipboardCopy/__tests__/__snapshots__/ClipboardCopy.test.tsx.snap, packages/react-core/src/components/ClipboardCopy/examples/ClipboardCopy.md, packages/react-core/src/components/ClipboardCopy/examples/ClipboardCopyInlineCompactTruncation.tsx, packages/react-core/src/components/ClipboardCopy/examples/ClipboardCopyTruncation.tsx, packages/react-core/src/components/Truncate/Truncate.tsx, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
=> feat(ClipboardCopy): added truncation for inlinecompact variant

packages/react-core/src/components/Toolbar/Toolbar.tsx, packages/react-core/src/components/Toolbar/__tests__/Toolbar.test.tsx, packages/react-core/src/components/Toolbar/__tests__/__snapshots__/Toolbar.test.tsx.snap
**What**: Closes https://github.com/patternfly/patternfly-react/issues/11647
**Additional issues**: https://github.com/patternfly/patternfly/issues/7332
=> feat(toolbar): add hasNoPadding prop

packages/react-core/src/components/Alert/examples/Alert.md, packages/react-core/src/components/Alert/examples/AlertAsyncLiveRegion.tsx, packages/react-core/src/components/Alert/examples/AlertDynamicLiveRegion.tsx, packages/react-core/src/components/Alert/examples/AlertGroupAsync.tsx, packages/react-core/src/components/Alert/examples/AlertGroupMultipleDynamic.tsx, packages/react-core/src/components/Alert/examples/AlertGroupSingularDynamic.tsx, packages/react-core/src/components/Alert/examples/AlertGroupSingularDynamicOverflow.tsx, packages/react-core/src/components/Alert/examples/AlertGroupToast.tsx, packages/react-core/src/components/Alert/examples/AlertGroupToastOverflowCapture.tsx, packages/react-core/src/demos/examples/AlertGroup/AlertGroupToastWithNotificationDrawer.tsx
**What**: Closes #11684
@edonehoo @andrew-ronaldson wdyt about the verbiage above the examples? More or less using the copy from the release highlights, but curious if you think it's worth including/helpful here.
=> chore(Alert): updated examples to enable animations

packages/react-charts/src/echarts/components/utils/tooltip.tsx
The `Sankey` tooltip must call `valueFormatter`. This is necessary in order to format values as currency.
https://github.com/patternfly/patternfly-react/issues/11710
=> fix(charts): tooltip must call valueFormatter

packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx, packages/react-code-editor/src/components/CodeEditor/__test__/__snapshots__/CodeEditor.test.tsx.snap
=> fix(CodeeEditor): rendered file input when editor has content

packages/react-core/src/components/DatePicker/DatePicker.tsx, packages/react-core/src/components/DatePicker/__tests__/DatePicker.test.tsx, packages/react-core/src/components/DatePicker/__tests__/__snapshots__/DatePicker.test.tsx.snap
=> fix(DatePicker): prevented textless helper text from rendering

packages/react-core/src/components/ExpandableSection/examples/ExpandableSectionBasic.tsx, packages/react-core/src/components/ExpandableSection/examples/ExpandableSectionDetached.tsx, packages/react-core/src/components/ExpandableSection/examples/ExpandableSectionDisclosure.tsx, packages/react-core/src/components/ExpandableSection/examples/ExpandableSectionIndented.tsx, packages/react-core/src/components/ExpandableSection/examples/ExpandableSectionTruncateExpansion.tsx, packages/react-core/src/components/ExpandableSection/examples/ExpandableSectionUncontrolled.tsx, packages/react-core/src/components/ExpandableSection/examples/ExpandableSectionUncontrolledDynamicToggleText.tsx, packages/react-core/src/demos/ExpandableSection/examples/ExpandableTextDemo.tsx
=> chore(expandable section): improve toggle text to be descriptive

packages/react-integration/cypress/integration/descriptionlist.spec.ts
=> chore(DescriptionList): added keyboard interaction cypress test

packages/react-core/src/components/LoginPage/LoginForm.tsx, packages/react-core/src/components/LoginPage/__tests__/LoginForm.test.tsx, packages/react-core/src/components/LoginPage/examples/LoginPage.md
=> feat(LoginPage): added isPasswordRequired prop

packages/react-code-editor/src/components/CodeEditor/examples/CodeEditorShortcutMainHeader.tsx
=> chore(code editor): add headerMainContent prop to example

packages/react-core/package.json, packages/react-core/src/components/Page/Page.tsx, packages/react-core/src/components/Page/__tests__/Page.test.tsx, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
=> feat(Page): Added support for sidebar-less layout

packages/react-core/src/deprecated/components/Wizard/WizardNavItem.tsx, packages/react-core/src/deprecated/components/Wizard/__tests__/Generated/__snapshots__/WizardNavItem.test.tsx.snap, packages/react-core/src/deprecated/components/Wizard/__tests__/__snapshots__/Wizard.test.tsx.snap
=> fix(Wizard deprecated): added wrapper for step name

packages/react-core/src/components/Divider/Divider.tsx, packages/react-core/src/components/Divider/__tests__/Divider.test.tsx, packages/react-core/src/components/Nav/NavItemSeparator.tsx, packages/react-core/src/components/Toolbar/ToolbarItem.tsx
**What**: Closes #11717 
Opted to not create an interface to expose for NavItemSeparator, as I'm wondering if we should consider deprecating it and just using the Divider component. Right now NavItemSeparator is just a wordier wrapper for Divider, and we're not doing anything special within it. One purpose of keeping this would be to have documentation explicitly about when to set the props to what (assuming we intend for this component to be used as either a separator between NavItems or just anywhere within a Nav; if the intent is only for between NavItems, then we should consider not allowing role or component to be customized).
=> fix(Nav): added role presentation to NavItemSeparator

packages/react-core/src/components/Truncate/Truncate.tsx, packages/react-core/src/components/Truncate/__tests__/Truncate.test.tsx, packages/react-core/src/components/Truncate/__tests__/__snapshots__/Truncate.test.tsx.snap, packages/react-core/src/components/Truncate/examples/Truncate.md, packages/react-core/src/components/Truncate/examples/TruncateCustomTooltipPosition.tsx, packages/react-core/src/components/Truncate/examples/TruncateDefault.tsx, packages/react-core/src/components/Truncate/examples/TruncateMaxChars.tsx, packages/react-core/src/components/Truncate/examples/TruncateMiddle.tsx, packages/react-core/src/components/Truncate/examples/TruncateStart.tsx
=> feat(Truncate): added logic to truncate based on max characters

packages/react-core/src/components/TreeView/TreeViewListItem.tsx, packages/react-core/src/components/TreeView/__tests__/TreeView.test.tsx, packages/react-core/src/components/TreeView/__tests__/TreeViewList.test.tsx, packages/react-core/src/components/TreeView/__tests__/TreeViewListItem.test.tsx, packages/react-core/src/components/TreeView/__tests__/TreeViewSearch.test.tsx, packages/react-core/src/components/TreeView/__tests__/__snapshots__/TreeView.test.tsx.snap
**What**: Closes #9825
Not exactly sure how best (or at all) we can test the useMemo prop since it's only being used within the React `memo`. 
=> chore(TreeView): added and updated unit tests

packages/react-core/src/components/Progress/ProgressContainer.tsx, packages/react-core/src/components/Truncate/Truncate.tsx, packages/react-core/src/components/Truncate/__tests__/Truncate.test.tsx, packages/react-core/src/components/Truncate/__tests__/__snapshots__/Truncate.test.tsx.snap, packages/react-integration/cypress/integration/truncate.spec.ts, packages/react-integration/demo-app-ts/src/Demos.ts, packages/react-integration/demo-app-ts/src/components/demos/TruncateDemo/TruncateDemo.tsx, packages/react-integration/demo-app-ts/src/components/demos/index.ts
**What**: Closes #11384
Progress:
- Adds a `tabIndex` to allow keyboard focus and an `updateTooltip` handler to also trigger the tooltip creation. The `useEffect` block is there to refocus the title text after the state updates and rerenders with the tooltip.
Truncate:
- Addes a `tabIndex` to the subparent to allow keyboard focus
- Updates Tooltip to remove wrapping contents div & updates parentElement logic to account for the removal
=> fix(Truncate, Progress): enable truncated tooltip via keyboard

packages/react-core/src/components/LoginPage/examples/LoginPageBasic.tsx, packages/react-core/src/components/LoginPage/examples/LoginPageLanguageSelect.tsx, packages/react-core/src/components/LoginPage/examples/LoginPageShowHidePassword.tsx
=> fix(login page): update demo background

packages/react-core/src/components/Truncate/Truncate.tsx, packages/react-core/src/components/Truncate/__tests__/Truncate.test.tsx, packages/react-core/src/components/Truncate/__tests__/__snapshots__/Truncate.test.tsx.snap
**What**: Closes #11777
don't think we can rely on a unit test to validate this doesn't break again; everything renders in the DOM as expected, it's just the `direction: rtl` styling that causes things to visually get out of order.
=> fix(Truncate): allowed punctuation at start of content

packages/react-core/src/components/Nav/NavExpandable.tsx, packages/react-core/src/components/Nav/__tests__/Generated/__snapshots__/NavExpandable.test.tsx.snap, packages/react-core/src/components/Nav/__tests__/NavExpandable.test.tsx, packages/react-core/src/components/Nav/__tests__/__snapshots__/Nav.test.tsx.snap
=> feat(navigation) - add inert attribute to NavExpandable

packages/react-templates/src/components/Select/MultiTypeaheadSelect.tsx, packages/react-templates/src/components/Select/__tests__/MultiTypeaheadSelect.test.tsx, packages/react-templates/src/components/Select/__tests__/__snapshots__/MultiTypeaheadSelect.test.tsx.snap
**What**: Closes #11790 
~~- also removes the `setInputValue('')` line from the `closeMenu` function~~
- this behavior (clearing caused by `onOpenChange` - clicking outside of the input or pressing escape) was not consistent with closing the menu by clicking on the toggle and then outside of the input, the [example code](https://www.patternfly.org/components/menus/select#multiple-typeahead-with-chips) also doesn't clear the input 
- it actually might be a good feature and I don't want to break someone's existing code because of this change. I wonder whether I should instead add a prop, something like "`clearInputOnMenuClose`" (default to true?), which would also clear the input on closing by clicking the toggle (which is not happening now)
=> feat(MultiTypeaheadSelect): add initialInputValue prop

packages/react-charts/src/victory/components/ChartDonutUtilization/examples/ChartDonutUtilization.md, packages/react-charts/src/victory/components/ChartDonutUtilization/examples/ChartUtilInvertedStatic.tsx, packages/react-charts/src/victory/components/ChartDonutUtilization/examples/ChartUtilSmallRightAlignedSubtitle.tsx, packages/react-charts/src/victory/components/ChartDonutUtilization/examples/ChartUtilSmallStatic.tsx, packages/react-charts/src/victory/components/ChartDonutUtilization/examples/ChartUtilSmallStaticRightLegend.tsx, packages/react-charts/src/victory/components/ChartDonutUtilization/examples/ChartUtilSmallSubtitle.tsx, packages/react-charts/src/victory/components/ChartDonutUtilization/examples/ChartUtilStatic.tsx, packages/react-charts/src/victory/components/ChartDonutUtilization/examples/ChartUtilStaticBottomLegend.tsx, packages/react-charts/src/victory/components/ChartDonutUtilization/examples/ChartUtilStaticCustomLegend.tsx, packages/react-charts/src/victory/components/ChartDonutUtilization/examples/ChartUtilStaticRightLegend.tsx
Towards #11719
The following examples of Chart Donut will be converted to TypeScript:
- Static thresholds
- Static thresholds with right aligned legend
- Inverted static thresholds with right aligned legend
- Static thresholds with custom legend
- Static thresholds with bottom aligned legend
- Small with static thresholds
- Small with static thresholds and right aligned legend
- Small with subtitle
- Small with thresholds and right aligned subtitle
This is related to #11819. The remaining 9 examples are converted in this PR to make it easier for reviewing.
=> chore(chart donut utilization): convert to typescript part two

packages/react-charts/src/victory/components/ChartDonut/examples/ChartDonut.md, packages/react-charts/src/victory/components/ChartDonut/examples/ChartDonutBasic.tsx, packages/react-charts/src/victory/components/ChartDonut/examples/ChartDonutBottomAlignedLegend.tsx, packages/react-charts/src/victory/components/ChartDonut/examples/ChartDonutMultiColor.tsx, packages/react-charts/src/victory/components/ChartDonut/examples/ChartDonutRightAlignedLegend.tsx, packages/react-charts/src/victory/components/ChartDonut/examples/ChartDonutSmall.tsx, packages/react-charts/src/victory/components/ChartDonut/examples/ChartDonutSmallBottomSubtitle.tsx, packages/react-charts/src/victory/components/ChartDonut/examples/ChartDonutSmallRightLegend.tsx, packages/react-charts/src/victory/components/ChartDonut/examples/ChartDonutSmallRightSubtitle.tsx
The following examples of Chart Donut will be converted to TypeScript:
- Basic
- Right aligned legend
- Multi-color (ordered) with right aligned legend
- Bottom aligned legend
- Small
- Small with right aligned legend
- Small with bottom aligned subtitle
- Small with right aligned subtitle
=> chore(chart donut): convert to typescript

packages/react-core/package.json, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-styles/package.json, packages/react-table/src/components/Table/Tr.tsx, packages/react-table/src/components/Table/__tests__/__snapshots__/RowWrapper.test.tsx.snap, packages/react-table/src/components/Table/examples/TableExpandable.tsx, packages/react-table/src/components/Table/examples/TableNestedTableExpandable.tsx, packages/react-table/src/demos/examples/TableExpandCollapseAll.tsx, packages/react-table/src/deprecated/components/Table/__tests__/__snapshots__/Table.test.tsx.snap, packages/react-tokens/package.json, packages/react-tokens/scripts/generateTokens.mjs, yarn.lock
**What**: Closes #11812, closes #11807, closes #11808
Table was updated to a more correct logic of applying certain classes from Core as were a few examples updates to show the correct way to set the tables up with those closes.
The animations aspect just needs to have confirmed that accordion, expandable section, and table expansion look good.
=> fix(Table): removed divider for expanded rows

packages/react-charts/src/victory/components/ChartDonutUtilization/examples/ChartDonutUtilization.md, packages/react-charts/src/victory/components/ChartDonutUtilization/examples/ChartUtilBasic.tsx, packages/react-charts/src/victory/components/ChartDonutUtilization/examples/ChartUtilBottomAlignedLegend.tsx, packages/react-charts/src/victory/components/ChartDonutUtilization/examples/ChartUtilInvertedRightLegend.tsx, packages/react-charts/src/victory/components/ChartDonutUtilization/examples/ChartUtilRightAlignedLegend.tsx, packages/react-charts/src/victory/components/ChartDonutUtilization/examples/ChartUtilRightVerticalLegend.tsx, packages/react-charts/src/victory/components/ChartDonutUtilization/examples/ChartUtilSmall.tsx, packages/react-charts/src/victory/components/ChartDonutUtilization/examples/ChartUtilSmallBottomSubtitle.tsx, packages/react-charts/src/victory/components/ChartDonutUtilization/examples/ChartUtilSmallRightLegend.tsx, packages/react-charts/src/victory/components/ChartDonutUtilization/examples/ChartUtilSmallRightSubtitle.tsx
Towards #11719
The following examples of Chart Donut will be converted to TypeScript:
- Basic
- Right aligned legend
- Inverted with right aligned legend
- Right aligned vertical legend
- Bottom aligned legend
- Small
- Small with right aligned legend
- Small with bottom aligned subtitle
- Small with right aligned subtitle
Since there are 18 examples, I'll divide this into 2 PRs making it easier for reviewing.
2nd PR - #11822
=> chore(chart donut utilization): convert to typescript

packages/react-core/package.json, packages/react-core/src/components/Tabs/OverflowTab.tsx, packages/react-core/src/components/Tabs/Tab.tsx, packages/react-core/src/components/Tabs/Tabs.tsx, packages/react-core/src/components/Tabs/TabsContext.ts, packages/react-core/src/components/Tabs/__tests__/Tabs.test.tsx, packages/react-core/src/components/Tabs/__tests__/__snapshots__/Tabs.test.tsx.snap, packages/react-core/src/components/Tabs/examples/Tabs.md, packages/react-core/src/helpers/util.ts, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-integration/cypress/integration/tabshorizontaloverflow.spec.ts, packages/react-integration/demo-app-ts/src/components/demos/TabsDemo/TabsHorizontalOverflowDemo.tsx, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
**What**: Closes #11348 
Looks like with the update to Tabs styling, we'll have to make updates in Org for the tabs being used for component pages. If any consumers are using tabs classes similar to how we are in Org (applying the tabs classes to elements rather than using the Tabs components themselves), they will probably run into a similar issue.
I updated and skipped some tests for now. Old tests didn't seem relevant with the unit tests for OverflowTab, and 1 test relies on a potential Core fix and the other was just acting up no matter what I had tried. Basically if there were 2 tests interacting with the OverflowTab, the 1st test would fail to find an item within that overflow menu while the 2nd test worked fine (using the same exact selectors/assertions). Remove the 1st test and …
=> feat(Tabs): added animations

packages/react-core/src/components/Tabs/Tabs.tsx, packages/react-core/src/components/Tabs/__tests__/Tabs.test.tsx
Closes https://github.com/patternfly/patternfly-react/issues/11873
This PR adds the option to make the `+` button in the `Tabs` component disabled, if the isAddButtonDisabled prop is set.
Although the change in the code is really small, I'm not fully familiar with the project and couldn't make it run locally to check visually how the component behaves :cry: . Feel free to confirm that it behaves as expected. All tests pass on my end, so it should be good to go.
=> feat(Tabs): add the option to disable the Add button

packages/react-core/src/components/TextArea/TextArea.tsx, packages/react-core/src/components/TextArea/__tests__/__snapshots__/TextArea.test.tsx.snap
**What**: Closes #11921 
**Additional issues**:  https://issues.redhat.com/browse/AAP-47692 
For consideration - 2 options for pulling this fix into Core as described by @mcoker but would change the markup so be potentially breaking:
Option 1:
```diff
diff --git a/packages/react-core/src/components/TextArea/TextArea.tsx b/packages/react-core/src/components/TextArea/TextArea.tsx
index 267e67728a..b794fed2d7 100644
--- a/packages/react-core/src/components/TextArea/TextArea.tsx
+++ b/packages/react-core/src/components/TextArea/TextArea.tsx
@@ -60,16 +60,12 @@ class TextAreaBase extends Component<TextAreaProps> {
private setAutoHeight = (field: HTMLTextAreaElement) => {
const parent = field.parentElement;
parent.style.setProperty('height', 'inherit');
const computed = …
```
=> fix(textarea): fix height logic for autoresize textarea

packages/react-charts/src/victory/components/ChartThreshold/examples/ChartThreshold.md, packages/react-charts/src/victory/components/ChartThreshold/examples/ChartThresholdMultiColorOrdered.tsx
The following examples are converted:
- Multi-color (unordered) with responsive container
=> chore(chart threshold): convert to typescript

packages/react-charts/src/victory/components/ChartStack/examples/ChartStack.md, packages/react-charts/src/victory/components/ChartStack/examples/ChartStackBasicRightLegend.tsx, packages/react-charts/src/victory/components/ChartStack/examples/ChartStackBottomLegend.tsx, packages/react-charts/src/victory/components/ChartStack/examples/ChartStackHorizontalBottomLegend.tsx, packages/react-charts/src/victory/components/ChartStack/examples/ChartStackMonthlyResponsive.tsx, packages/react-charts/src/victory/components/ChartStack/examples/ChartStackMultiColorOrdered.tsx, packages/react-charts/src/victory/components/ChartStack/examples/ChartStackMultiColorUnordered.tsx
The following examples are converted:
- Basic with right aligned legend
- Horizontal with bottom aligned legend
- Multi-color (ordered) horizontal with bottom aligned legend
- Monthly data with responsive container
- Multi-color (unordered) responsive container
=> chore(chart stack): convert to typescript

packages/react-charts/src/victory/components/ChartScatter/examples/ChartScatter.md, packages/react-charts/src/victory/components/ChartScatter/examples/ChartScatterAreaChart.tsx, packages/react-charts/src/victory/components/ChartScatter/examples/ChartScatterBasic.tsx, packages/react-charts/src/victory/components/ChartScatter/examples/ChartScatterLineChart.tsx
The following examples are converted:
- Basic
- Line chart
- Area chart
=> chore(chart scatter): convert to typescript

packages/react-core/src/components/Tooltip/Tooltip.tsx, packages/react-core/src/components/Tooltip/__tests__/Tooltip.test.tsx
Aided by Cursor
**What**: Closes #9517
Going this route also resolves an issue seen in our Tooltip ref examples where an aria-describedby/labelledby attribute is always rendered on the trigger, causing axe to flag an error over it. This dynamically renders those attributes when applicable.
The alternative would be just updating MenuItem code so that the Tooltip wraps `<Component>` on line 348 to get the tooltip to render properly, but that wouldn't really resolve the underlying problem with how Tooltips can be used - there'd still be open any issues elsewhere either in our own code where a Tooltip is being used with only a triggerRef and no children, or for consumers who are doing that. 
=> fix(Tooltip): added aria attributes for triggerRef

packages/react-core/package.json, packages/react-core/src/components/Wizard/WizardNavItem.tsx, packages/react-core/src/deprecated/components/Wizard/WizardNavItem.tsx, packages/react-docs/package.json, packages/react-icons/package.json, packages/react-styles/package.json, packages/react-tokens/package.json, yarn.lock
manually bumps core to latest prerelease
closes https://github.com/patternfly/patternfly-react/pull/11971 - the renovate core bump which [wants to bump to 6.3.1](https://github.com/patternfly/patternfly-react/pull/11971#issuecomment-3254395504)
=> chore(deps): bump patternfly/patternfly to 6.3.0-prerelease.55

packages/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx, packages/react-core/src/components/ClipboardCopy/ClipboardCopyButton.tsx, packages/react-core/src/components/ClipboardCopy/ClipboardCopyToggle.tsx, packages/react-core/src/components/ClipboardCopy/__tests__/ClipboardCopy.test.tsx, packages/react-core/src/components/ClipboardCopy/__tests__/ClipboardCopyButton.test.tsx, packages/react-core/src/components/ClipboardCopy/__tests__/ClipboardCopyToggle.test.tsx, packages/react-core/src/components/ClipboardCopy/__tests__/__snapshots__/ClipboardCopy.test.tsx.snap, packages/react-core/src/components/ClipboardCopy/__tests__/__snapshots__/ClipboardCopyButton.test.tsx.snap, packages/react-core/src/components/ClipboardCopy/__tests__/__snapshots__/ClipboardCopyToggle.test.tsx.snap, packages/react-core/src/components/ClipboardCopy/examples/ClipboardCopyBasic.tsx, packages/react-core/src/components/ClipboardCopy/examples/ClipboardCopyExpanded.tsx, packages/react-core/src/components/ClipboardCopy/examples/ClipboardCopyExpandedWithArray.tsx, packages/react-core/src/components/ClipboardCopy/examples/ClipboardCopyInlineCompact.tsx, packages/react-core/src/components/ClipboardCopy/examples/ClipboardCopyInlineCompactCode.tsx, packages/react-core/src/components/ClipboardCopy/examples/ClipboardCopyInlineCompactInSentence.tsx, packages/react-core/src/components/ClipboardCopy/examples/ClipboardCopyInlineCompactTruncation.tsx, packages/react-core/src/components/ClipboardCopy/examples/ClipboardCopyInlineCompactWithAdditionalAction.tsx, packages/react-core/src/components/ClipboardCopy/examples/ClipboardCopyJSONObject.tsx, packages/react-core/src/components/ClipboardCopy/examples/ClipboardCopyReadOnly.tsx, packages/react-core/src/components/ClipboardCopy/examples/ClipboardCopyReadOnlyExpanded.tsx, packages/react-core/src/components/ClipboardCopy/examples/ClipboardCopyReadOnlyExpandedByDefault.tsx
**What**: Remove aria-labelled by from copy and expand buttons in favor of aria-label. In case of copy button, add new prop for aria-label and pull from hoverTip if not provided. Long term, we will want to further separate these two in a breaking release.
Closes #[11372](https://github.com/patternfly/patternfly-react/issues/11372)
=> fix(ClipboardCopy): Adjust aria-labels on buttons

packages/react-core/src/helpers/Popper/Popper.tsx
Towards #11987 
Adds a passthrough for Popper's `offset` (`distance` may still be used and still remains as a default if `offset` isn't present).
=> feat(Popper): add passthrough for offset

packages/react-core/src/components/Dropdown/Dropdown.tsx, packages/react-core/src/components/Dropdown/examples/Dropdown.md, packages/react-core/src/components/Menu/MenuContainer.tsx, packages/react-core/src/components/Menu/examples/Menu.md, packages/react-core/src/components/Select/Select.tsx, packages/react-core/src/components/Select/examples/Select.md, packages/react-core/src/components/Tabs/OverflowTab.tsx, packages/react-core/src/components/Tabs/examples/Tabs.md, packages/react-core/src/helpers/Popper/Popper.tsx
**What**: 
Closes #11929 
Closes #11574
=> feat: extend `PopperProps` in derivative component types 

packages/react-core/src/components/Dropdown/Dropdown.tsx, packages/react-core/src/components/Menu/Menu.tsx, packages/react-core/src/components/Menu/__tests__/Menu.test.tsx, packages/react-core/src/components/Select/Select.tsx, packages/react-core/src/components/Tabs/Tabs.tsx, packages/react-templates/src/components/Dropdown/SimpleDropdown.tsx, packages/react-templates/src/components/Select/CheckboxSelect.tsx, packages/react-templates/src/components/Select/SimpleSelect.tsx, packages/react-templates/src/components/Select/TypeaheadSelect.tsx
**What**: Closes #11361
Non-breaking change to loosen the expected type of `onSelect`'s `value` parameter, to match `SelectOptionProps`
This PR wold allow for the removal of a bunch of `ts-expect-error`s I added in openshift/console#14783
=> fix(Select): improve type consistency in `onSelect`

packages/react-core/src/helpers/Popper/Popper.tsx
See https://github.com/patternfly/patternfly-react/issues/11778#issuecomment-3300329410 for how I troubleshot this.
I spoke to the team and it sounds like they want to just update the docs around this.
Alternatively, we can also set preventOverflow to true by default if left or right are used, but it sounds like the team wants to avoid setting defaults like that.
**What**: Closes #11778
=> chore(docs): Update docs to suggest using preventOverflow

packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx, packages/react-code-editor/src/components/CodeEditor/CodeEditorTheme.ts, packages/react-code-editor/src/components/CodeEditor/themeTokenMapping.ts
What: Closes #11506 #11764
Includes the changes from #11575 but now it overwrites every token from the [base vs theme](https://github.com/microsoft/vscode/blob/main/src/vs/editor/standalone/common/themes.ts)
Note there should be some additional CSS in PatternFly to make this look better (so that the margin around the CodeEditor matches the monaco background color), but I'm not sure of the best way to implement it:
```css
.pf-v6-theme-dark {
.pf-v6-c-code-editor:not(.pf-m-read-only) {
--pf-v6-c-code-editor__main--BackgroundColor: var(--pf-t--color--gray--90);
--pf-v6-c-code-editor__tab--BackgroundColor: var(--pf-t--color--gray--90);
}
}
```
I tried looking into using `pf-t--global--background--color--primary--default`, but it doesn't provide enough contrast in dark mode. Meanwhile, …
=> feat(CodeEditor): use custom PatternFly monaco theme
